= Extending {branding} Platform Application
include::config.adoc[]

== Overview

This page supports developers creating extensions of the existing framework.

== Whitelist

The following packages have been exported by the DDF Platform application and are approved for use by third parties:

* ddf.action
* ddf.action.impl
* ddf.mime
* ddf.security
* ddf.security.assertion
* ddf.security.common.audit
* ddf.security.permission
* ddf.security.service
* ddf.security.ws.policy
* ddf.security.ws.proxy
* ddf.security.encryption
* org.codice.ddf.configuration
* org.codice.ddf.platform.status

WARNING: The Platform Application includes other third party packages such as Apache CXF and Apache Camel. These are available for use by third party developers but their versions can change at any time with future releases of the Platform Application.

== Developing Action Components (Action Framework)

The Action Framework was designed as a way to limit dependencies between applications (apps) in a system. For instance, a feature in an app, such as a Atom feed generator, might want to include an external link as part of its feed's entries. That feature does not have to be coupled to a REST endpoint to work, nor does it have to depend on a specific implementation to get a link. In reality, the feature does not identify how the link is generated, but it does identify whether link works or does not work when retrievi ng the intended entry's metadata. Instead of creating its own mechanism or adding an unrelated feature, it could use the Action Framework to query out in the OSGi container for any service that can provide a link. This does two things: it allows the feature to be independent of implementations, and it encourages reuse of common services. 

The Action Framework consists of two major Java interfaces in its API:

. `ddf.action.Action`
. `ddf.action.ActionProvider`

=== Usage

To provide a service, such as a link to a record, the `ActionProvider` interface should be implemented. An `ActionProvider` essentially provides an `Action` when given input that it can recognize and handle. For instance, if a REST endpoint ActionProvider was given a metacard, it could provide a link based on the metacard's ID. An Action Provider performs an action when given a subject that it understands. If it does not understand the subject or does not know how to handle the given input, it will return `null`. An Action Provider is required to have an ActionProvider id. The Action Provider must register itself in the OSGi Service Registry with the `ddf.action.ActionProvider` interface and must also have a service property value for `id`. An action is a URL that, when invoked, provides a resource or executes intended business logic. 

==== Naming Convention
For each Action, a title and description should be provided to describe what the action does.  The recommended naming convention is to use the verb 'Get' when retrieving a portion of the metacard, such as the metadata or thumbnail, or when you are downloading the product.  The verb 'Export' or expression 'Export as' is recommended when the metacard is bring exported in a different format or presented after going some transformation.

==== Taxonomy

An Action Provider registers an `id` as a service property in the OGSi Service Registry based on the type of service or action that is provided. Regardless of implementation, if more than one Action Provider provides the same service, such as providing a URL to a thumbnail for a given metacard, they must both register under the same `id`. Therefore, Action Provider implementers must follow an Action Taxonomy. 


The following is a sample taxonomy: 

. _catalog.data.metacard_ shall be the grouping that represents Actions on a Catalog metacard.
.. _catalog.data.metacard.view_
.. _catalog.data.metacard.thumbnail_
.. _catalog.data.metacard.html_
.. _catalog.data.metacard.resource_
.. _catalog.data.metacard.metadata_

===== Action ID Service Descriptions

[cols="2,4,1" options="header"]
|===
|ID
|Required Action
|Naming Convention

|catalog.data.metacard.view
|Provides a valid URL to view all of a metacard data. Format of data is not specified; i.e. the representation can be in XML, JSON, or other.
|Export as ...

|catalog.data.metacard.thumbnail
|Provides a valid URL to the bytes of a thumbnail (Metacard.THUMBNAIL) with MIME type image/jpeg.
|Get Thumbnail

|catalog.data.metacard.html
|Provides a valid URL that, when invoked, provides an HTML representation of the metacard.
|Export as ...

|catalog.data.metacard.resource
|Provides a valid URL that, when invoked, provides the underlying resource of the metacard.
|Get Resource

|catalog.data.metacard.metadata
|Provides a valid URL to the XML metadata in the metacard (Metacard.METADATA).
|Get Metadata

|===
