= Integrating with the {branding} Admin Application Service
include::config.adoc[]

== Overview

The Application Service is a service that allows components to perform operations on applications. This includes adding, removing, starting, stopping, and viewing status.

== API

The Application service has multiple interfaces which are exposed on to the OSGi runtime for other applications to use. For more information on these interfaces, see Application Service Interfaces.

== JMX Managed Bean

Some of the Application service API is exposed via JMX. It can either be accessed using the JMX API or from a REST-based interface created by http://jolokia.org[Jolokia] that comes with DDF. Here are the interfaces that are exposed in the Managed Bean:

.getApplicationTree
----
Creates an application hierarchy tree that shows relationships between applications.
----
.startApplication
----
Starts an application with the given name.
----
.stopApplication
----
Stops an application with the given name.
----
.addApplications
----
Adds a list of application that are specified by their URL.
----

== Configuration Files

Support for configuration files was added to allow for an initial installation of applications on first run.

=== Initial Application Installation

[WARNING]
====
This application list configuration file is only read on first start.
====
To minimize the chance of accidentally installing and uninstalling application, the configuration file for installing the initial applications is only read the first time that DDF is started. The only way to change what applications are active after DDF has been started is to use the console commands. Similar operations can also be done with the administrator web console that comes with DDF using the Features tab and installing the main feature for the desired application. This way will be deprecated after the application module has been built for the Admin UI.

The application list file is located at `DDF_HOME/etc/org.codice.ddf.admin.applicationlist.properties`

Applications should be defined in a `<name>=<format>` syntax where location may be empty for applications that have already been added to DDF or were prepackaged with the distribution.

Examples:
----
# Local application:
opendj-embedded

# Application installed into a local maven repository:
opendj-embedded=mvn:org.codice.opendj.embedded/opendj-embedded-app/1.0.1-SNAPSHOT/xml/features

# Application located on the file system:
opendj-embedded=file:/location/to/opendj-embedded-app-1.0.1-SNAPSHOT.kar
----
Applications will be started in the order they are listed in the file. If an application is listed, DDF will also attempt to install all dependencies for that application.

=== Defining Platform Settings

The platform settings can be configured by a file located in `DDF_HOME/etc/ddf.platform.config.cfg`

The settings in this file can be changed at any time during the DDF lifecycle (before installation, after, or during run-time) and will immediately update the corresponding properties for the platform global configuration.

== Console Commands

The application service comes with various console commands that can be executed on the DDF system console. More information is available on the `Application Commands` page.

== Application Service Interfaces

The Application service has multiple ways of interacting with it. This methods range from being at the coding level to operations that can be performed by administrators and end users.

=== Installing and Uninstalling

The Admin App installs this service by default. It is recommended to NOT uninstall the application service unless absolutely necessary.

=== Configuring
None.

=== Interface Details

The Application Service comes with several interfaces to use. 

==== ApplicationService

The ApplicationService interface is the main class that is used to operate on applications.

.getApplications
----
This method returns a set of all applications that are installed on the system. Callers can then use the Application handle to get the name and any underlying features and bundles that this application contains.
----
.getApplication
----
Returns the application that has the given name.
----
.startApplication
----
Starts an application, including any defined dependencies in the application.
----
.stopApplication
----
Stops an application, does not include any external transitive dependencies as they may be needed by other applications.
----
.addApplication
----
Adds a new application to the application list. *NOTE: This does NOT start the application.*
----
.removeApplication
----
Removes an application that has the given URI.
----
.isApplicationStarted
----
This method takes in an application and returns a boolean value that says if the application is started or not. This method is generally called after retrieving a list of applications in the first method.
----
.getApplicationStatus
----
This method, unlike isApplicationStarted, returns a full status of an application. This status contains detailed information about the health of the application and is described in the ApplicationStatus interface section.
----
.getApplicationTree
----
Creates a hierarchy tree of application nodes that show the relationship between applications.
----
.findFeature
----
Determine which application contains a certain feature.
----
==== Application
.getName
----
Name of the application. Should be unique among applications.
----
.getFeatures
----
Retrieves all of the features that this application contains regardless if they are required.
----
.getBundles
----
Retrieves all of the bundles that are defined by the features and included in this application.
----
==== ApplicationStatus
.getApplication
----
Sends back the application that is associated with this status.
----
.getState
----
Returns the application's state as defined by ApplicationState.
----
.getErrorFeatures
----
Returns a set of Features that were required for this application but did not start correctly.
----
.getErrorBundles
----
Returns a set of Bundles that were required for this application but did not start correctly.
----
==== ApplicationNode
.getApplication
----
Returns the application this node is referencing.
----
.getStatus
----
Returns the status for the application this node is referencing.
----
.getParent
----
Returns the parent of the application.
----
.getChildren
----
Returns the children of this application. That is, the applications that have a requirement on this application
----
== Implementation Details
[NOTE]
====
A client of this service is provided as an extension to the administrative console. Information about how to use it is available on the Application Commands page.
====
=== Imported Services

[cols="4*", options="header"]
|===
|Registered Interface
|Availability
|Multiple
|Notes

|org.apache.karaf.features.FeaturesService
|required
|false
|Provided by Karaf Framework

|org.apache.karaf.bundle.core.BundleStateService
|required
|true
|Installed as part of Platform Status feature.
|===

=== Exported Services
[cols="3*", options="header"]
|===
|Registered Interface
|Implementation Class
|Notes

|org.codice.ddf.admin.application.service.ApplicationService
|org.codice.ddf.admin.application.service.impl.ApplicationServiceImpl
|

|===
