:title: All File Formats Supported
:type: subMetadataReference
:status: published
:parent: File Format-specific Attributes
:order: 99
:summary: Complete list of supported file types.

////
The tables in this section have 3 defined columns.
If adding or removing items, be sure to add or subtract empty cells at the end of the table to avoid losing data in the rendered version.
////
== {title}

.Supported File Types
Using the various input transformers, ${branding} supports ingest of the following MIME types.
While ingest is possible for these files, metadata will be limited unless otherwise noted.

.Application File Types
[cols="3"]
|===
m|activemessage
m|andrew-inset
m|applefile
m|applixware
m|atom+xml
m|atomcat+xml
m|atomicmail
m|atomsvc+xml
m|auth-policy+xml
m|batch-smtp
m|beep+xml
m|bizagi-modeler
m|cals-1840
m|cbor
m|ccxml+xml
m|cea-2018+xml
m|cellml+xml
m|cnrp+xml
m|commonground
m|conference-info+xml
m|cpl+xml
m|csta+xml
m|cstadata+xml
m|cu-seeme
m|cybercash
m|davmount+xml
m|dca-rft
m|dec-dx
m|dialog-info+xml
m|dicom
m|dif+xml
m|dita+xml
m|dita+xml
m|dita+xml
m|dita+xml
m|dita+xml
m|dita+xml
m|dns
m|dvcs
m|ecmascript
m|edi-consent
m|edi-x12
m|edifact
m|emma+xml
m|epp+xml
m|epub+zip
m|eshop
m|example
m|fastinfoset
m|fastsoap
m|fits
m|font-tdpfr
m|gzip
m|h224
m|http
m|hyperstudio
m|ibe-key-request+xml
m|ibe-pkg-reply+xml
m|ibe-pp-data
m|iges
m|illustrator
m|im-iscomposing+xml
m|index
m|index.cmd
m|index.obj
m|index.response
m|index.vnd
m|inf
m|iotp
m|ipp
m|isup
m|java-archive
m|java-serialized-object
m|java-vm
m|javascript
m|json
m|kate
m|kpml-request+xml
m|kpml-response+xml
m|lost+xml
m|mac-binhex40
m|mac-compactpro
m|macwriteii
m|marc
m|mathematica
m|mathml+xml
m|mbms-associated-procedure-description+xml
m|mbms-deregister+xml
m|mbms-envelope+xml
m|mbms-msk+xml
m|mbms-msk-response+xml
m|mbms-protection-description+xml
m|mbms-reception-report+xml
m|mbms-register+xml
m|mbms-register-response+xml
m|mbms-user-service-description+xml
m|mbox
m|media_control+xml
m|mediaservercontrol+xml
m|mikey
m|moss-keys
m|moss-signature
m|mosskey-data
m|mosskey-request
m|mp4
m|mpeg4-generic
m|mpeg4-iod
m|mpeg4-iod-xmt
m|msword
m|msword2
m|msword5
m|mxf
m|nasdata
m|news-checkgroups
m|news-groupinfo
m|news-transmission
m|nss
m|ocsp-request
m|ocsp-response
m|octet-stream
m|oda
m|oebps-package+xml
m|ogg
m|onenote
m|parityfec
m|patch-ops-error+xml
m|pdf
m|pgp-encrypted
m|pgp-keys
m|pgp-signature
m|pics-rules
m|pidf+xml
m|pidf-diff+xml
m|pkcs10
m|pkcs7-mime
m|pkcs7-signature
m|pkix-cert
m|pkix-crl
m|pkix-pkipath
m|pkixcmp
m|pls+xml
m|poc-settings+xml
m|postscript
m|prs.alvestrand.titrax-sheet
m|prs.cww
m|prs.nprend
m|prs.plucker
m|qsig
m|quicktime
m|rdf+xml
m|reginfo+xml
m|relax-ng-compact-syntax
m|remote-printing
m|resource-lists+xml
m|resource-lists-diff+xml
m|riscos
m|rlmi+xml
m|rls-services+xml
m|rsd+xml
m|rss+xml
m|rtf
m|rtx
m|samlassertion+xml
m|samlmetadata+xml
m|sbml+xml
m|scvp-cv-request
m|scvp-cv-response
m|scvp-vp-request
m|scvp-vp-response
m|sdp
m|sereal
m|sereal
m|sereal
m|sereal
m|set-payment
m|set-payment-initiation
m|set-registration
m|set-registration-initiation
m|sgml
m|sgml-open-catalog
m|shf+xml
m|sieve
m|simple-filter+xml
m|simple-message-summary
m|simplesymbolcontainer
m|slate
m|sldworks
m|smil+xml
m|soap+fastinfoset
m|soap+xml
m|sparql-query
m|sparql-results+xml
m|spirits-event+xml
m|srgs
m|srgs+xml
m|ssml+xml
m|timestamp-query
m|timestamp-reply
m|tve-trigger
m|ulpfec
m|vemmi
m|vividence.scriptfile
m|vnd.3gpp.bsf+xml
m|vnd.3gpp.pic-bw-large
m|vnd.3gpp.pic-bw-small
m|vnd.3gpp.pic-bw-var
m|vnd.3gpp.sms
m|vnd.3gpp2.bcmcsinfo+xml
m|vnd.3gpp2.sms
m|vnd.3gpp2.tcap
m|vnd.3m.post-it-notes
m|vnd.accpac.simply.aso
m|vnd.accpac.simply.imp
m|vnd.acucobol
m|vnd.acucorp
m|vnd.adobe.aftereffects.project
m|vnd.adobe.aftereffects.template
m|vnd.adobe.air-application-installer-package+zip
m|vnd.adobe.xdp+xml
m|vnd.adobe.xfdf
m|vnd.aether.imp
m|vnd.airzip.filesecure.azf
m|vnd.airzip.filesecure.azs
m|vnd.amazon.ebook
m|vnd.americandynamics.acc
m|vnd.amiga.ami
m|vnd.android.package-archive
m|vnd.anser-web-certificate-issue-initiation
m|vnd.anser-web-funds-transfer-initiation
m|vnd.antix.game-component
m|vnd.apple.installer+xml
m|vnd.apple.iwork
m|vnd.apple.keynote
m|vnd.apple.numbers
m|vnd.apple.pages
m|vnd.arastra.swi
m|vnd.audiograph
m|vnd.autopackage
m|vnd.avistar+xml
m|vnd.blueice.multipass
m|vnd.bluetooth.ep.oob
m|vnd.bmi
m|vnd.businessobjects
m|vnd.cab-jscript
m|vnd.canon-cpdl
m|vnd.canon-lips
m|vnd.cendio.thinlinc.clientconf
m|vnd.chemdraw+xml
m|vnd.chipnuts.karaoke-mmd
m|vnd.cinderella
m|vnd.cirpack.isdn-ext
m|vnd.claymore
m|vnd.clonk.c4group
m|vnd.commerce-battelle
m|vnd.commonspace
m|vnd.contact.cmsg
m|vnd.cosmocaller
m|vnd.crick.clicker
m|vnd.crick.clicker.keyboard
m|vnd.crick.clicker.palette
m|vnd.crick.clicker.template
m|vnd.crick.clicker.wordbank
m|vnd.criticaltools.wbs+xml
m|vnd.ctc-posml
m|vnd.ctct.ws+xml
m|vnd.cups-pdf
m|vnd.cups-postscript
m|vnd.cups-ppd
m|vnd.cups-raster
m|vnd.cups-raw
m|vnd.curl.car
m|vnd.curl.pcurl
m|vnd.cybank
m|vnd.data-vision.rdz
m|vnd.denovo.fcselayout-link
m|vnd.dir-bi.plate-dl-nosuffix
m|vnd.dna
m|vnd.dolby.mlp
m|vnd.dolby.mobile.1
m|vnd.dolby.mobile.2
m|vnd.dpgraph
m|vnd.dreamfactory
m|vnd.dvb.esgcontainer
m|vnd.dvb.ipdcdftnotifaccess
m|vnd.dvb.ipdcesgaccess
m|vnd.dvb.ipdcroaming
m|vnd.dvb.iptv.alfec-base
m|vnd.dvb.iptv.alfec-enhancement
m|vnd.dvb.notif-aggregate-root+xml
m|vnd.dvb.notif-container+xml
m|vnd.dvb.notif-generic+xml
m|vnd.dvb.notif-ia-msglist+xml
m|vnd.dvb.notif-ia-registration-request+xml
m|vnd.dvb.notif-ia-registration-response+xml
m|vnd.dvb.notif-init+xml
m|vnd.dxr
m|vnd.dynageo
m|vnd.ecdis-update
m|vnd.ecowin.chart
m|vnd.ecowin.filerequest
m|vnd.ecowin.fileupdate
m|vnd.ecowin.series
m|vnd.ecowin.seriesrequest
m|vnd.ecowin.seriesupdate
m|vnd.emclient.accessrequest+xml
m|vnd.enliven
m|vnd.epson.esf
m|vnd.epson.msf
m|vnd.epson.quickanime
m|vnd.epson.salt
m|vnd.epson.ssf
m|vnd.ericsson.quickcall
m|vnd.eszigno3+xml
m|vnd.etsi.aoc+xml
m|vnd.etsi.asic-e+zip
m|vnd.etsi.asic-s+zip
m|vnd.etsi.cug+xml
m|vnd.etsi.iptvcommand+xml
m|vnd.etsi.iptvdiscovery+xml
m|vnd.etsi.iptvprofile+xml
m|vnd.etsi.iptvsad-bc+xml
m|vnd.etsi.iptvsad-cod+xml
m|vnd.etsi.iptvsad-npvr+xml
m|vnd.etsi.iptvueprofile+xml
m|vnd.etsi.mcid+xml
m|vnd.etsi.sci+xml
m|vnd.etsi.simservs+xml
m|vnd.eudora.data
m|vnd.ezpix-album
m|vnd.ezpix-package
m|vnd.f-secure.mobile
m|vnd.fdf
m|vnd.fdsn.mseed
m|vnd.fdsn.seed
m|vnd.ffsns
m|vnd.fints
m|vnd.flographit
m|vnd.fluxtime.clip
m|vnd.font-fontforge-sfd
m|vnd.framemaker
m|vnd.frogans.fnc
m|vnd.frogans.ltf
m|vnd.fsc.weblaunch
m|vnd.fujitsu.oasys
m|vnd.fujitsu.oasys2
m|vnd.fujitsu.oasys3
m|vnd.fujitsu.oasysgp
m|vnd.fujitsu.oasysprs
m|vnd.fujixerox.art-ex
m|vnd.fujixerox.art4
m|vnd.fujixerox.ddd
m|vnd.fujixerox.docuworks
m|vnd.fujixerox.docuworks.binder
m|vnd.fujixerox.hbpl
m|vnd.fut-misnet
m|vnd.fuzzysheet
m|vnd.genomatix.tuxedo
m|vnd.geogebra.file
m|vnd.geogebra.tool
m|vnd.geometry-explorer
m|vnd.gmx
m|vnd.google-earth.kml+xml
m|vnd.google-earth.kmz
m|vnd.grafeq
m|vnd.gridmp
m|vnd.groove-account
m|vnd.groove-help
m|vnd.groove-identity-message
m|vnd.groove-injector
m|vnd.groove-tool-message
m|vnd.groove-tool-template
m|vnd.groove-vcard
m|vnd.handheld-entertainment+xml
m|vnd.hbci
m|vnd.hcl-bireports
m|vnd.hhe.lesson-player
m|vnd.hp-hpgl
m|vnd.hp-hpid
m|vnd.hp-hps
m|vnd.hp-jlyt
m|vnd.hp-pcl
m|vnd.hp-pclxl
m|vnd.httphone
m|vnd.hydrostatix.sof-data
m|vnd.hzn-3d-crossword
m|vnd.ibm.afplinedata
m|vnd.ibm.electronic-media
m|vnd.ibm.minipay
m|vnd.ibm.modcap
m|vnd.ibm.rights-management
m|vnd.ibm.secure-container
m|vnd.iccprofile
m|vnd.igloader
m|vnd.immervision-ivp
m|vnd.immervision-ivu
m|vnd.informedcontrol.rms+xml
m|vnd.informix-visionary
m|vnd.intercon.formnet
m|vnd.intertrust.digibox
m|vnd.intertrust.nncp
m|vnd.intu.qbo
m|vnd.intu.qfx
m|vnd.iptc.g2.conceptitem+xml
m|vnd.iptc.g2.knowledgeitem+xml
m|vnd.iptc.g2.newsitem+xml
m|vnd.iptc.g2.packageitem+xml
m|vnd.ipunplugged.rcprofile
m|vnd.irepository.package+xml
m|vnd.is-xpr
m|vnd.jam
m|vnd.japannet-directory-service
m|vnd.japannet-jpnstore-wakeup
m|vnd.japannet-payment-wakeup
m|vnd.japannet-registration
m|vnd.japannet-registration-wakeup
m|vnd.japannet-setstore-wakeup
m|vnd.japannet-verification
m|vnd.japannet-verification-wakeup
m|vnd.jcp.javame.midlet-rms
m|vnd.jisp
m|vnd.joost.joda-archive
m|vnd.kahootz
m|vnd.kde.karbon
m|vnd.kde.kchart
m|vnd.kde.kformula
m|vnd.kde.kivio
m|vnd.kde.kontour
m|vnd.kde.kpresenter
m|vnd.kde.kspread
m|vnd.kde.kword
m|vnd.kenameaapp
m|vnd.kidspiration
m|vnd.kinar
m|vnd.koan
m|vnd.kodak-descriptor
m|vnd.liberty-request+xml
m|vnd.llamagraphics.life-balance.desktop
m|vnd.llamagraphics.life-balance.exchange+xml
m|vnd.lotus-1-2-3
m|vnd.lotus-approach
m|vnd.lotus-freelance
m|vnd.lotus-notes
m|vnd.lotus-organizer
m|vnd.lotus-screencam
m|vnd.lotus-wordpro
m|vnd.macports.portpkg
m|vnd.marlin.drm.actiontoken+xml
m|vnd.marlin.drm.conftoken+xml
m|vnd.marlin.drm.license+xml
m|vnd.marlin.drm.mdcf
m|vnd.mcd
m|vnd.medcalcdata
m|vnd.mediastation.cdkey
m|vnd.meridian-slingshot
m|vnd.mfer
m|vnd.mfmp
m|vnd.micrografx.flo
m|vnd.micrografx.igx
m|vnd.mif
m|vnd.mindjet.mindmanager
m|vnd.minisoft-hp3000-save
m|vnd.mitsubishi.misty-guard.trustweb
m|vnd.mobius.daf
m|vnd.mobius.dis
m|vnd.mobius.mbk
m|vnd.mobius.mqy
m|vnd.mobius.msl
m|vnd.mobius.plc
m|vnd.mobius.txf
m|vnd.mophun.application
m|vnd.mophun.certificate
m|vnd.motorola.flexsuite
m|vnd.motorola.flexsuite.adsi
m|vnd.motorola.flexsuite.fis
m|vnd.motorola.flexsuite.gotap
m|vnd.motorola.flexsuite.kmr
m|vnd.motorola.flexsuite.ttc
m|vnd.motorola.flexsuite.wem
m|vnd.motorola.iprm
m|vnd.mozilla.xul+xml
m|vnd.ms-artgalry
m|vnd.ms-asf
m|vnd.ms-cab-compressed
m|vnd.ms-excel
m|vnd.ms-excel.addin.macroenabled.12
m|vnd.ms-excel.sheet.2
m|vnd.ms-excel.sheet.3
m|vnd.ms-excel.sheet.4
m|vnd.ms-excel.sheet.binary.macroenabled.12
m|vnd.ms-excel.sheet.macroenabled.12
m|vnd.ms-excel.template.macroenabled.12
m|vnd.ms-excel.workspace.3
m|vnd.ms-excel.workspace.4
m|vnd.ms-fontobject
m|vnd.ms-htmlhelp
m|vnd.ms-ims
m|vnd.ms-lrm
m|vnd.ms-outlook
m|vnd.ms-outlook-pst
m|vnd.ms-pki.seccat
m|vnd.ms-pki.stl
m|vnd.ms-playready.initiator+xml
m|vnd.ms-powerpoint
m|vnd.ms-powerpoint.addin.macroenabled.12
m|vnd.ms-powerpoint.presentation.macroenabled.12
m|vnd.ms-powerpoint.slide.macroenabled.12
m|vnd.ms-powerpoint.slideshow.macroenabled.12
m|vnd.ms-powerpoint.template.macroenabled.12
m|vnd.ms-project
m|vnd.ms-tnef
m|vnd.ms-visio.drawing
m|vnd.ms-visio.drawing.macroenabled.12
m|vnd.ms-visio.stencil
m|vnd.ms-visio.stencil.macroenabled.12
m|vnd.ms-visio.template
m|vnd.ms-visio.template.macroenabled.12
m|vnd.ms-visio.viewer
m|vnd.ms-wmdrm.lic-chlg-req
m|vnd.ms-wmdrm.lic-resp
m|vnd.ms-wmdrm.meter-chlg-req
m|vnd.ms-wmdrm.meter-resp
m|vnd.ms-word.document.macroenabled.12
m|vnd.ms-word.template.macroenabled.12
m|vnd.ms-works
m|vnd.ms-wpl
m|vnd.ms-xpsdocument
m|vnd.mseq
m|vnd.msign
m|vnd.multiad.creator
m|vnd.multiad.creator.cif
m|vnd.music-niff
m|vnd.musician
m|vnd.muvee.style
m|vnd.ncd.control
m|vnd.ncd.reference
m|vnd.nervana
m|vnd.netfpx
m|vnd.neurolanguage.nlu
m|vnd.noblenet-directory
m|vnd.noblenet-sealer
m|vnd.noblenet-web
m|vnd.nokia.catalogs
m|vnd.nokia.conml+wbxml
m|vnd.nokia.conml+xml
m|vnd.nokia.iptv.config+xml
m|vnd.nokia.isds-radio-presets
m|vnd.nokia.landmark+wbxml
m|vnd.nokia.landmark+xml
m|vnd.nokia.landmarkcollection+xml
m|vnd.nokia.n-gage.ac+xml
m|vnd.nokia.n-gage.data
m|vnd.nokia.n-gage.symbian.install
m|vnd.nokia.ncd
m|vnd.nokia.pcd+wbxml
m|vnd.nokia.pcd+xml
m|vnd.nokia.radio-preset
m|vnd.nokia.radio-presets
m|vnd.novadigm.edm
m|vnd.novadigm.edx
m|vnd.novadigm.ext
m|vnd.oasis.opendocument.chart
m|vnd.oasis.opendocument.chart-template
m|vnd.oasis.opendocument.database
m|vnd.oasis.opendocument.formula
m|vnd.oasis.opendocument.formula-template
m|vnd.oasis.opendocument.graphics
m|vnd.oasis.opendocument.graphics-template
m|vnd.oasis.opendocument.image
m|vnd.oasis.opendocument.image-template
m|vnd.oasis.opendocument.presentation
m|vnd.oasis.opendocument.presentation-template
m|vnd.oasis.opendocument.spreadsheet
m|vnd.oasis.opendocument.spreadsheet-template
m|vnd.oasis.opendocument.text
m|vnd.oasis.opendocument.text-master
m|vnd.oasis.opendocument.text-template
m|vnd.oasis.opendocument.text-web
m|vnd.obn
m|vnd.olpc-sugar
m|vnd.oma-scws-config
m|vnd.oma-scws-http-request
m|vnd.oma-scws-http-response
m|vnd.oma.bcast.associated-procedure-parameter+xml
m|vnd.oma.bcast.drm-trigger+xml
m|vnd.oma.bcast.imd+xml
m|vnd.oma.bcast.ltkm
m|vnd.oma.bcast.notification+xml
m|vnd.oma.bcast.provisioningtrigger
m|vnd.oma.bcast.sgboot
m|vnd.oma.bcast.sgdd+xml
m|vnd.oma.bcast.sgdu
m|vnd.oma.bcast.simple-symbol-container
m|vnd.oma.bcast.smartcard-trigger+xml
m|vnd.oma.bcast.sprov+xml
m|vnd.oma.bcast.stkm
m|vnd.oma.dcd
m|vnd.oma.dcdc
m|vnd.oma.dd2+xml
m|vnd.oma.drm.risd+xml
m|vnd.oma.group-usage-list+xml
m|vnd.oma.poc.detailed-progress-report+xml
m|vnd.oma.poc.final-report+xml
m|vnd.oma.poc.groups+xml
m|vnd.oma.poc.invocation-descriptor+xml
m|vnd.oma.poc.optimized-progress-report+xml
m|vnd.oma.xcap-directory+xml
m|vnd.omads-email+xml
m|vnd.omads-file+xml
m|vnd.omads-folder+xml
m|vnd.omaloc-supl-init
m|vnd.openofficeorg.extension
m|vnd.openxmlformats-officedocument.presentationml.presentation
m|vnd.openxmlformats-officedocument.presentationml.slide
m|vnd.openxmlformats-officedocument.presentationml.slideshow
m|vnd.openxmlformats-officedocument.presentationml.template
m|vnd.openxmlformats-officedocument.spreadsheetml.sheet
m|vnd.openxmlformats-officedocument.spreadsheetml.template
m|vnd.openxmlformats-officedocument.wordprocessingml.document
m|vnd.openxmlformats-officedocument.wordprocessingml.template
m|vnd.osa.netdeploy
m|vnd.osgi.bundle
m|vnd.osgi.dp
m|vnd.otps.ct-kip+xml
m|vnd.palm
m|vnd.paos.xml
m|vnd.pg.format
m|vnd.pg.osasli
m|vnd.piaccess.application-licence
m|vnd.picsel
m|vnd.poc.group-advertisement+xml
m|vnd.pocketlearn
m|vnd.powerbuilder6
m|vnd.powerbuilder6-s
m|vnd.powerbuilder7
m|vnd.powerbuilder7-s
m|vnd.powerbuilder75
m|vnd.powerbuilder75-s
m|vnd.preminet
m|vnd.previewsystems.box
m|vnd.proteus.magazine
m|vnd.publishare-delta-tree
m|vnd.pvi.ptid1
m|vnd.pwg-multiplexed
m|vnd.pwg-xhtml-print+xml
m|vnd.qualcomm.brew-app-res
m|vnd.quark.quarkxpress
m|vnd.rapid
m|vnd.recordare.musicxml
m|vnd.recordare.musicxml+xml
m|vnd.renlearn.rlprint
m|vnd.rim.cod
m|vnd.rn-realmedia
m|vnd.route66.link66+xml
m|vnd.ruckus.download
m|vnd.s3sms
m|vnd.sbm.cid
m|vnd.sbm.mid2
m|vnd.scribus
m|vnd.sealed.3df
m|vnd.sealed.csf
m|vnd.sealed.doc
m|vnd.sealed.eml
m|vnd.sealed.mht
m|vnd.sealed.net
m|vnd.sealed.ppt
m|vnd.sealed.tiff
m|vnd.sealed.xls
m|vnd.sealedmedia.softseal.html
m|vnd.sealedmedia.softseal.pdf
m|vnd.seemail
m|vnd.sema
m|vnd.semd
m|vnd.semf
m|vnd.shana.informed.formdata
m|vnd.shana.informed.formtemplate
m|vnd.shana.informed.interchange
m|vnd.shana.informed.package
m|vnd.simtech-mindmapper
m|vnd.smaf
m|vnd.smart.teacher
m|vnd.software602.filler.form+xml
m|vnd.software602.filler.form-xml-zip
m|vnd.solent.sdkm+xml
m|vnd.spotfire.dxp
m|vnd.spotfire.sfs
m|vnd.sss-cod
m|vnd.sss-dtf
m|vnd.sss-ntf
m|vnd.stardivision.calc
m|vnd.stardivision.draw
m|vnd.stardivision.impress
m|vnd.stardivision.math
m|vnd.stardivision.writer
m|vnd.stardivision.writer-global
m|vnd.street-stream
m|vnd.sun.wadl+xml
m|vnd.sun.xml.calc
m|vnd.sun.xml.calc.template
m|vnd.sun.xml.draw
m|vnd.sun.xml.draw.template
m|vnd.sun.xml.impress
m|vnd.sun.xml.impress.template
m|vnd.sun.xml.math
m|vnd.sun.xml.writer
m|vnd.sun.xml.writer.global
m|vnd.sun.xml.writer.template
m|vnd.sus-calendar
m|vnd.svd
m|vnd.swiftview-ics
m|vnd.symbian.install
m|vnd.syncml+xml
m|vnd.syncml.dm+wbxml
m|vnd.syncml.dm+xml
m|vnd.syncml.dm.notification
m|vnd.syncml.ds.notification
m|vnd.tao.intent-module-archive
m|vnd.tcpdump.pcap
m|vnd.tmobile-livetv
m|vnd.trid.tpt
m|vnd.triscape.mxs
m|vnd.trueapp
m|vnd.truedoc
m|vnd.ufdl
m|vnd.uiq.theme
m|vnd.umajin
m|vnd.unity
m|vnd.uoml+xml
m|vnd.uplanet.alert
m|vnd.uplanet.alert-wbxml
m|vnd.uplanet.bearer-choice
m|vnd.uplanet.bearer-choice-wbxml
m|vnd.uplanet.cacheop
m|vnd.uplanet.cacheop-wbxml
m|vnd.uplanet.channel
m|vnd.uplanet.channel-wbxml
m|vnd.uplanet.list
m|vnd.uplanet.list-wbxml
m|vnd.uplanet.listcmd
m|vnd.uplanet.listcmd-wbxml
m|vnd.uplanet.signal
m|vnd.vcx
m|vnd.vd-study
m|vnd.vectorworks
m|vnd.vidsoft.vidconference
m|vnd.visio
m|vnd.visionary
m|vnd.vividence.scriptfile
m|vnd.vsf
m|vnd.wap.sic
m|vnd.wap.slc
m|vnd.wap.wbxml
m|vnd.wap.wmlc
m|vnd.wap.wmlscriptc
m|vnd.webturbo
m|vnd.wfa.wsc
m|vnd.wmc
m|vnd.wmf.bootstrap
m|vnd.wordperfect
m|vnd.wqd
m|vnd.wrq-hp3000-labelled
m|vnd.wt.stf
m|vnd.wv.csp+wbxml
m|vnd.wv.csp+xml
m|vnd.wv.ssp+xml
m|vnd.xara
m|vnd.xfdl
m|vnd.xfdl.webform
m|vnd.xmi+xml
m|vnd.xmpie.cpkg
m|vnd.xmpie.dpkg
m|vnd.xmpie.plan
m|vnd.xmpie.ppkg
m|vnd.xmpie.xlim
m|vnd.yamaha.hv-dic
m|vnd.yamaha.hv-script
m|vnd.yamaha.hv-voice
m|vnd.yamaha.openscoreformat
m|vnd.yamaha.openscoreformat.osfpvg+xml
m|vnd.yamaha.smaf-audio
m|vnd.yamaha.smaf-phrase
m|vnd.yellowriver-custom-menu
m|vnd.zul
m|vnd.zzazz.deck+xml
m|voicexml+xml
m|watcherinfo+xml
m|whoispp-query
m|whoispp-response
m|winhlp
m|wita
m|wordperfect5.1
m|wsdl+xml
m|wspolicy+xml
m|x-123
m|x-7z-compressed
m|x-abiword
m|x-ace-compressed
m|x-adobe-indesign
m|x-adobe-indesign-interchange
m|x-apple-diskimage
m|x-appleworks
m|x-archive
m|x-arj
m|x-authorware-bin
m|x-authorware-map
m|x-authorware-seg
m|x-axcrypt
m|x-bcpio
m|x-berkeley-db
m|x-berkeley-db
m|x-berkeley-db
m|x-berkeley-db
m|x-berkeley-db
m|x-berkeley-db
m|x-berkeley-db
m|x-berkeley-db
m|x-berkeley-db
m|x-berkeley-db
m|x-berkeley-db
m|x-berkeley-db
m|x-bibtex-text-file
m|x-bittorrent
m|x-bplist
m|x-bzip
m|x-bzip2
m|x-cdlink
m|x-chat
m|x-chess-pgn
m|x-chrome-package
m|x-compress
m|x-coredump
m|x-corelpresentations
m|x-cpio
m|x-csh
m|x-debian-package
m|x-dex
m|x-director
m|x-doom
m|x-dosexec
m|x-dtbncx+xml
m|x-dtbook+xml
m|x-dtbresource+xml
m|x-dvi
m|x-elc
m|x-elf
m|x-emf
m|x-erdas-hfa
m|x-executable
m|x-fictionbook+xml
m|x-filemaker
m|x-font-adobe-metric
m|x-font-bdf
m|x-font-dos
m|x-font-framemaker
m|x-font-ghostscript
m|x-font-libgrx
m|x-font-linux-psf
m|x-font-otf
m|x-font-pcf
m|x-font-printer-metric
m|x-font-snf
m|x-font-speedo
m|x-font-sunos-news
m|x-font-ttf
m|x-font-type1
m|x-font-vfont
m|x-foxmail
m|x-futuresplash
m|x-gnucash
m|x-gnumeric
m|x-grib
m|x-gtar
m|x-hdf
m|x-hwp
m|x-hwp-v5
m|x-ibooks+zip
m|x-isatab
m|x-isatab-assay
m|x-isatab-investigation
m|x-iso9660-image
m|x-itunes-ipa
m|x-java-jnilib
m|x-java-jnlp-file
m|x-java-pack200
m|x-kdelnk
m|x-killustrator
m|x-latex
m|x-lha
m|x-lharc
m|x-matlab-data
m|x-matroska
m|x-mobipocket-ebook
m|x-ms-application
m|x-ms-installer
m|x-ms-wmd
m|x-ms-wmz
m|x-ms-xbap
m|x-msaccess
m|x-msbinder
m|x-mscardfile
m|x-msclip
m|x-msdownload
m|x-msdownload
m|x-msdownload
m|x-msdownload
m|x-msdownload
m|x-msdownload
m|x-msdownload
m|x-msmediaview
m|x-msmetafile
m|x-msmoney
m|x-mspublisher
m|x-msschedule
m|x-msterminal
m|x-mswrite
m|x-mysql-db
m|x-mysql-misam-compressed-index
m|x-mysql-misam-data
m|x-mysql-misam-index
m|x-mysql-table-definition
m|x-netcdf
m|x-object
m|x-pkcs12
m|x-pkcs7-certificates
m|x-pkcs7-certreqresp
m|x-project
m|x-prt
m|x-quattro-pro
m|x-rar-compressed
m|x-roxio-toast
m|x-rpm
m|x-sas
m|x-sas-access
m|x-sas-audit
m|x-sas-backup
m|x-sas-catalog
m|x-sas-data
m|x-sas-data-index
m|x-sas-dmdb
m|x-sas-fdb
m|x-sas-itemstor
m|x-sas-mddb
m|x-sas-program-data
m|x-sas-putility
m|x-sas-transport
m|x-sas-utility
m|x-sas-view
m|x-sc
m|x-sfdu
m|x-sh
m|x-shapefile
m|x-shar
m|x-sharedlib
m|x-shockwave-flash
m|x-silverlight-app
m|x-snappy-framed
m|x-sqlite3
m|x-staroffice-template
m|x-stuffit
m|x-stuffitx
m|x-sv4cpio
m|x-sv4crc
m|x-tar
m|x-tex
m|x-tex-tfm
m|x-texinfo
m|x-tika-iworks-protected
m|x-tika-java-enterprise-archive
m|x-tika-java-web-archive
m|x-tika-msoffice
m|x-tika-msoffice-embedded
m|x-tika-msoffice-embedded
m|x-tika-msoffice-embedded
m|x-tika-msworks-spreadsheet
m|x-tika-old-excel
m|x-tika-ooxml
m|x-tika-ooxml-protected
m|x-tika-staroffice
m|x-tika-unix-dump
m|x-tika-visio-ooxml
m|x-uc2-compressed
m|x-ustar
m|x-vhd
m|x-vmdk
m|x-wais-source
m|x-webarchive
m|x-x509-ca-cert
m|x-xfig
m|x-xmind
m|x-xpinstall
m|x-xz
m|x-zoo
m|x400-bp
m|xcap-att+xml
m|xcap-caps+xml
m|xcap-el+xml
m|xcap-error+xml
m|xcap-ns+xml
m|xcon-conference-info+xml
m|xcon-conference-info-diff+xml
m|xenc+xml
m|xhtml+xml
m|xhtml-voice+xml
m|xml
m|xml-dtd
m|xml-external-parsed-entity
m|xmpp+xml
m|xop+xml
m|xquery
m|xslfo+xml
m|xslt+xml
m|xspf+xml
m|xv+xml
m|zip
m|zlib
|===

.Audio File Types
[cols="3"]
|===
m|32kadpcm
m|3gpp
m|3gpp2
m|ac3
m|adpcm
m|amr
m|amr-wb
m|amr-wb+
m|asc
m|basic
m|bv16
m|bv32
m|clearmode
m|cn
m|dat12
m|dls
m|dsr-es201108
m|dsr-es202050
m|dsr-es202211
m|dsr-es202212
m|dvi4
m|eac3
m|evrc
m|evrc-qcp
m|evrc0
m|evrc1
m|evrcb
m|evrcb0
m|evrcb1
m|evrcwb
m|evrcwb0
m|evrcwb1
m|example
m|g719
m|g722
m|g7221
m|g723
m|g726-16
m|g726-24
m|g726-32
m|g726-40
m|g728
m|g729
m|g7291
m|g729d
m|g729e
m|gsm
m|gsm-efr
m|ilbc
m|l16
m|l20
m|l24
m|l8
m|lpc
m|midi
m|mobile-xmf
m|mp4
m|mp4a-latm
m|mpa
m|mpa-robust
m|mpeg
m|mpeg4-generic
m|ogg
m|opus
m|parityfec
m|pcma
m|pcma-wb
m|pcmu
m|pcmu-wb
m|prs.sid
m|qcelp
m|red
m|rtp-enc-aescm128
m|rtp-midi
m|rtx
m|smv
m|smv-qcp
m|smv0
m|sp-midi
m|speex
m|t140c
m|t38
m|telephone-event
m|tone
m|ulpfec
m|vdvi
m|vmr-wb
m|vnd.3gpp.iufp
m|vnd.4sb
m|vnd.adobe.soundbooth
m|vnd.audiokoz
m|vnd.celp
m|vnd.cisco.nse
m|vnd.cmles.radio-events
m|vnd.cns.anp1
m|vnd.cns.inf1
m|vnd.digital-winds
m|vnd.dlna.adts
m|vnd.dolby.heaac.1
m|vnd.dolby.heaac.2
m|vnd.dolby.mlp
m|vnd.dolby.mps
m|vnd.dolby.pl2
m|vnd.dolby.pl2x
m|vnd.dolby.pl2z
m|vnd.dts
m|vnd.dts.hd
m|vnd.everad.plj
m|vnd.hns.audio
m|vnd.lucent.voice
m|vnd.ms-playready.media.pya
m|vnd.nokia.mobile-xmf
m|vnd.nortel.vbk
m|vnd.nuera.ecelp4800
m|vnd.nuera.ecelp7470
m|vnd.nuera.ecelp9600
m|vnd.octel.sbc
m|vnd.qcelp
m|vnd.rhetorex.32kadpcm
m|vnd.sealedmedia.softseal.mpeg
m|vnd.vmx.cvsd
m|vorbis
m|vorbis-config
m|x-aac
m|x-adbcm
m|x-aiff
m|x-dec-adbcm
m|x-dec-basic
m|x-flac
m|x-matroska
m|x-mod
m|x-mpegurl
m|x-ms-wax
m|x-ms-wma
m|x-oggflac
m|x-oggpcm
m|x-pn-realaudio
m|x-pn-realaudio-plugin
m|x-wav
m|
m|
|===

.Chemical File Types
[cols="3"]
|===
m|x-cdx
m|x-cif
m|x-cmdf
m|x-cml
m|x-csml
m|x-pdb
m|x-xyz
|
|
|===

.Image File Types
[cols="3"]
|===
m|bmp
m|cgm
m|example
m|fits
m|g3fax
m|gif
m|icns
m|ief
m|jp2
m|jpeg
m|jpm
m|jpx
m|naplps
m|nitf
m|png
m|prs.btif
m|prs.pti
m|svg+xml
m|t38
m|tiff
m|tiff-fx
m|vnd.adobe.photoshop
m|vnd.adobe.premiere
m|vnd.cns.inf2
m|vnd.djvu
m|vnd.dwg
m|vnd.dxb
m|vnd.dxf
m|vnd.dxf
m|vnd.dxf
m|vnd.fastbidsheet
m|vnd.fpx
m|vnd.fst
m|vnd.fujixerox.edmics-mmr
m|vnd.fujixerox.edmics-rlc
m|vnd.globalgraphics.pgb
m|vnd.microsoft.icon
m|vnd.mix
m|vnd.ms-modi
m|vnd.net-fpx
m|vnd.radiance
m|vnd.sealed.png
m|vnd.sealedmedia.softseal.gif
m|vnd.sealedmedia.softseal.jpg
m|vnd.svf
m|vnd.wap.wbmp
m|vnd.xiff
m|webp
m|x-bpg
m|x-cmu-raster
m|x-cmx
m|x-freehand
m|x-jp2-codestream
m|x-jp2-container
m|x-ms-bmp
m|x-niff
m|x-pcx
m|x-pict
m|x-portable-anymap
m|x-portable-bitmap
m|x-portable-graymap
m|x-portable-pixmap
m|x-raw-adobe
m|x-raw-canon
m|x-raw-casio
m|x-raw-epson
m|x-raw-fuji
m|x-raw-hasselblad
m|x-raw-imacon
m|x-raw-kodak
m|x-raw-leaf
m|x-raw-logitech
m|x-raw-mamiya
m|x-raw-minolta
m|x-raw-nikon
m|x-raw-olympus
m|x-raw-panasonic
m|x-raw-pentax
m|x-raw-phaseone
m|x-raw-rawzor
m|x-raw-red
m|x-raw-sigma
m|x-raw-sony
m|x-rgb
m|x-xbitmap
m|x-xcf
m|x-xpixmap
m|x-xwindowdump
|
|
|===

.Message File Types
[cols="3"]
|===
m|cpim
m|delivery-status
m|disposition-notification
m|example
m|external-body
m|global
m|global-delivery-status
m|global-disposition-notification
m|global-headers
m|http
m|imdn+xml
m|news
m|partial
m|rfc822
m|s-http
m|sip
m|sipfrag
m|tracking-status
m|vnd.si.simp
m|x-emlx
|
|===

.Model File Types
[cols="3"]
|===
m|example
m|iges
m|mesh
m|vnd.dwf
m|vnd.dwf
m|vnd.dwf
m|vnd.dwf
m|vnd.dwfx+xps
m|vnd.flatland.3dml
m|vnd.gdl
m|vnd.gs-gdl
m|vnd.gs.gdl
m|vnd.gtw
m|vnd.moml+xml
m|vnd.mts
m|vnd.parasolid.transmit.binary
m|vnd.parasolid.transmit.text
m|vnd.vtu
m|vrml
|
|
|===

.Multipart File Types
[cols="3"]
|===
m|alternative
m|appledouble
m|byteranges
m|digest
m|encrypted
m|example
m|form-data
m|header-set
m|mixed
m|parallel
m|related
m|report
m|signed
m|voice-message
|
|===

.Text File Types
[cols="3"]
|===
m|asp
m|aspdotnet
m|calendar
m|css
m|csv
m|directory
m|dns
m|ecmascript
m|enriched
m|example
m|html
m|iso19139+xml
m|parityfec
m|plain
m|prs.fallenstein.rst
m|prs.lines.tag
m|red
m|rfc822-headers
m|richtext
m|rtp-enc-aescm128
m|rtx
m|sgml
m|t140
m|tab-separated-values
m|troff
m|ulpfec
m|uri-list
m|vnd.abc
m|vnd.curl
m|vnd.curl.dcurl
m|vnd.curl.mcurl
m|vnd.curl.scurl
m|vnd.dmclientscript
m|vnd.esmertec.theme-descriptor
m|vnd.fly
m|vnd.fmi.flexstor
m|vnd.graphviz
m|vnd.in3d.3dml
m|vnd.in3d.spot
m|vnd.iptc.anpa
m|vnd.iptc.newsml
m|vnd.iptc.nitf
m|vnd.latex-z
m|vnd.motorola.reflex
m|vnd.ms-mediapackage
m|vnd.net2phone.commcenter.command
m|vnd.si.uricatalogue
m|vnd.sun.j2me.app-descriptor
m|vnd.trolltech.linguist
m|vnd.wap.si
m|vnd.wap.sl
m|vnd.wap.wml
m|vnd.wap.wmlscript
m|vtt
m|x-actionscript
m|x-ada
m|x-applescript
m|x-asciidoc
m|x-aspectj
m|x-assembly
m|x-awk
m|x-basic
m|x-c++hdr
m|x-c++src
m|x-cgi
m|x-chdr
m|x-clojure
m|x-cobol
m|x-coffeescript
m|x-coldfusion
m|x-common-lisp
m|x-csharp
m|x-csrc
m|x-d
m|x-diff
m|x-eiffel
m|x-emacs-lisp
m|x-erlang
m|x-expect
m|x-forth
m|x-fortran
m|x-go
m|x-groovy
m|x-haml
m|x-haskell
m|x-haxe
m|x-idl
m|x-ini
m|x-java-properties
m|x-java-source
m|x-jsp
m|x-less
m|x-lex
m|x-log
m|x-lua
m|x-matlab
m|x-ml
m|x-modula
m|x-objcsrc
m|x-ocaml
m|x-pascal
m|x-perl
m|x-php
m|x-prolog
m|x-python
m|x-rexx
m|x-rsrc
m|x-rst
m|x-ruby
m|x-scala
m|x-scheme
m|x-sed
m|x-setext
m|x-sql
m|x-stsrc
m|x-tcl
m|x-tika-text-based-message
m|x-uuencode
m|x-vbasic
m|x-vbdotnet
m|x-vbscript
m|x-vcalendar
m|x-vcard
m|x-verilog
m|x-vhdl
m|x-web-markdown
m|x-yacc
m|x-yaml
|
|===

.Video File Types
[cols="3"]
|===
m|3gpp
m|3gpp-tt
m|3gpp2
m|bmpeg
m|bt656
m|celb
m|daala
m|dv
m|example
m|h261
m|h263
m|h263-1998
m|h263-2000
m|h264
m|jpeg
m|jpeg2000
m|mj2
m|mp1s
m|mp2p
m|mp2t
m|mp4
m|mp4v-es
m|mpeg
m|mpeg4-generic
m|mpv
m|nv
m|ogg
m|parityfec
m|pointer
m|quicktime
m|raw
m|rtp-enc-aescm128
m|rtx
m|smpte292m
m|theora
m|ulpfec
m|vc1
m|vnd.cctv
m|vnd.dlna.mpeg-tts
m|vnd.fvt
m|vnd.hns.video
m|vnd.iptvforum.1dparityfec-1010
m|vnd.iptvforum.1dparityfec-2005
m|vnd.iptvforum.2dparityfec-1010
m|vnd.iptvforum.2dparityfec-2005
m|vnd.iptvforum.ttsavc
m|vnd.iptvforum.ttsmpeg2
m|vnd.motorola.video
m|vnd.motorola.videop
m|vnd.mpegurl
m|vnd.ms-playready.media.pyv
m|vnd.nokia.interleaved-multimedia
m|vnd.nokia.videovoip
m|vnd.objectvideo
m|vnd.sealed.mpeg1
m|vnd.sealed.mpeg4
m|vnd.sealed.swf
m|vnd.sealedmedia.softseal.mov
m|vnd.vivo
m|webm
m|x-dirac
m|x-f4v
m|x-flc
m|x-fli
m|x-flv
m|x-jng
m|x-m4v
m|x-matroska
m|x-mng
m|x-ms-asf
m|x-ms-wm
m|x-ms-wmv
m|x-ms-wmx
m|x-ms-wvx
m|x-msvideo
m|x-oggrgb
m|x-ogguvs
m|x-oggyuv
m|x-ogm
m|x-sgi-movie
|
|===

.x-conference File Types
[cols="3"]
|===
m|x-cooltalk
|
|
|===
