:title: Common Metadata Attributes
:type: metadataReference
:status: published
:parent: Metadata Attributes
:summary: Support for a variety of file types and data types.
:order: 00

== {title}

${branding} supports a wide variety of file types and data types for ingest.
The ${branding}'s internal Input Transformers extract the necessary data into a <<{metadata-prefix}catalog_taxonomy_definitions,generalized format>>.
${branding} supports ingest of many datatypes and commonly used file formats, such as Microsoft office products: Word documents, Excel spreadsheets, and PowerPoint presentations as well as .pdf files, GeoJson and others. See <<{metadata-prefix}all_file_formats_supported,complete list>>.
Many of these file types support additional <<_file_format_specific_attributes,file format-specific attributes>> from which additional metadata can be extracted.

[NOTE]
====
These attributes will be available in all the specified file formats; however, values will only be present if present in the original document/resource.
====

These attributes are supported by any file type ingested into ${branding}:

.Common Attributes in All Supported File Types
* metadata
* id
* modified (date)
* title (filename)
* metadata content type (mime type)
* effective (date)
* created (date)

These 'media' file types have support for additional attributes to be available when ingested into ${branding}:

.File Types Supporting Additional Attributes
* Video Types
** WMV
** AVI
** MP4
** MOV
** h.264 MPEG2
* Image Types
** JPEG-2000
* Document Types
** .DOC, .DOCX, .DOTX, .DOCM
** .PPT, .PPTX
** .XLS, .XLSX
** .PDF

These are the attributes common to any of the media file types which support additional attributes:

.Additional Possible Attributes Common to 'Media' File Types
* `media.format-version`
* `media.format`
* `media.bit-rate`
* `media.bits-per-sample`
* `media.compression`
* `media.encoding`
* `media.frame-center`
* `media.frame-rate`
* `media.height-pixels`
* `media.number-of-bands`
* `media.scanning-mode`
* `media.type`
* `media.duration`
* `media.page-count`
* `datatype`
* `description`
* `contact.point-of-contact-name`
* `contact.contributor-name`
* `contact.creator-name`
* `contact.publisher-name`
* `contact.point-of-contact-phone`
* `topic.keyword`
