
This section supports integrating {branding} with existing applications or frameworks.

=== Quick Start
This quick tutorial will demonstrate:

- [*] Installation
- [*] Catalog Capabilities: Ingest and query using every endpoint
- [*] Use of the Content Framework
- [*] Metrics Reporting

==== Install {branding}

. Install {branding} by unzipping the zip file.
This will create an installation directory, which is typically created with the name and version of the application.
This installation directory will be referred to as `<DISTRIBUTION_INSTALL_DIR>`.
Substitute the actual directory name in place of this.
. Start {branding} by running the `<DISTRIBUTION_INSTALL_DIR>/bin/ddf` script (or `ddf.bat` on Windows).
. Verify the distribution is running.
. Go to https://localhost:8993/admin.
. Enter the default username of "admin" (no quotes) and the password of "admin" (no quotes).
. Follow the install instructions for more extensive install guidance, or use the command line console (which appears after the  <DISTRIBUTION_INSTALL_DIR>/bin/ddf script starts) to install a few applications as mentioned below.
+
----
app:start catalog-app
app:start content-app
app:start solr-app
----
+
[NOTE]
====
Other applications may be installed at a later time.
====
+
. After the installation has been configured the instance should be restarted.
. Go to https://localhost:8993/services and verify five REST services are available: admin, application, metrics, catalog, and catalog/query.
. Click on the links to each REST service's WADL to see its interface.
. In the Admin Console (at /admin), configure the system settings.
.. Enter the username of "admin" (no quotes) and the password "admin" (no quotes).
.. Select Platform app
.. Select Platform Global Configuration.
.. Enter the port and host where the distribution is running.

==== Catalog Capabilities

. Create an entry in the Catalog by ingesting a valid GeoJson file (attached to this page). This ingest can be performed using:
.. A REST client, such as Google Chrome's Advanced REST Client. OR
.. Using the following curl command to POST to the Catalog REST CRUD endpoint.
+
.Windows Example
----
curl -H "Content-type: application/json;id=geojson" -i -X POST -d @"C:\path\to\geojson_valid.json" https://localhost:8993/services/catalog
----
+
.*NIX Example
----
curl -H "Content-type: application/json;id=geojson" -i -X POST -d @geojson_valid.json https://localhost:8993/services/catalog
----
+
Where:
*-H* adds an HTTP header. In this case, Content-type header `application/json;id=geojson` is added to match the data being sent in the request.
*-i* requests that HTTP headers are displayed in the response.
*-X* specifies the type of HTTP operation. For this example, it is necessary to POST (ingest) data to the server.
*-d* specifies the data sent in the POST request. The @ character is necessary to specify that the data is a file.
+
The last parameter is the URL of the server that will receive the data.
+
This should return a response similar to the following (the actual catalog ID in the id and Location URL fields will be different):
+
.Sample Response
[source,http,linenums]
----
HTTP/1.1 201 Created
Content-Length: 0
Date: Mon, 22 Apr 2013 22:02:22 GMT
id: 44dc84da101c4f9d9f751e38d9c4d97b
Location: https://localhost:8993/services/catalog/44dc84da101c4f9d9f751e38d9c4d97b
Server: Jetty(7.5.4.v20111024)
----
+
. Verify the entry was successfully ingested by entering in a browser the URL returned in the POST response's HTTP header. For instance in our example, it was `/services/catalog/44dc84da101c4f9d9f751e38d9c4d97b`. This should display the catalog entry in XML within the browser.
. Verify the catalog entry exists by executing a query via the OpenSearch endpoint.
. Enter the following URL in a browser /services/catalog/query?q=ddf. A single result, in Atom format, should be returned.

==== Use of the Content Framework
Using the Content framework's directory monitor, ingest a file so that it is stored in the content repository with a metacard created and inserted into the Catalog.

. In the Web Console, select the Configuration tab.
. Select the *Content Directory Monitor*.
. Set the directory path to *inbox*.
. Click the *Save* button.
. Copy the attached link:geojson_valid.json[geojson] file to the `<DISTRIBUTION_INSTALL_DIR>/inbox` directory.
+
The Content Framework will:
+
.. ingest the file,
.. store it in the content repository at <DISTRIBUTION_INSTALL_DIR>/content/store/<GUID>/geojson_valid.json,
.. look up the GeoJson Input Transformer based on the mime type of the ingested file,
.. create a metacard based on the metadata parsed from the ingested GeoJson file, and
.. insert the metacard into the Catalog using the CatalogFramework.
+
Note that XML metadata for text searching is not automatically generated from GeoJson fields.
. Verify GeoJson file was stored using the Content REST endpoint.
.. Install the feature content-rest-endpoint using the Features tab in the Web Console.
.. Send a GET command to read the content from the content repository using the Content REST endpoint. This can be done using curl command below. Note that the GUID will be different for each ingest. The GUID can be determined by going to the <DISTRIBUTION_INSTALL_DIR>/content/store directory and copying the sub-directory in this folder (there should only be one).

.Windows Example
[source,terminal]
----
curl -X GET https://localhost:8993/services/content/c90147bf86294d46a9d35ebbd44992c5
----

.*NIX Example
[source,terminal]
----
curl -X GET https://localhost:8993/services/content/c90147bf86294d46a9d35ebbd44992c5
----

The response to the GET command will be the contents of the `geojson_valid.json` file originally ingested.

=== Understanding Metadata and Metacards

Metadata is information about a resource, organized into a schema to make it possible to search against.
The {branding} Catalog stores this metadata and allows access to it. If desired, the {branding} Content application can be installed to store the resources themselves.
Metacards are single instances of metadata, representing a single record, in the Metadata Catalog (MDC).
Metacards follow one of several schemas to ensure reliable, accurate, and complee metadata.
Essentially, Metacards function as containers of metadata.

=== Populating Metacards (during ingest)

Upon ingest, a metacard transformer will read the data from the ingested file and populate the fields of the metacard.
Exactly how this is accomplished depends on the origin of the data, but most fields (except id) are imported directly.

=== Searching Metadata

{branding} provides the capability to search the Metadata Catalog (MDC) for metadata.
There are a number of different types of searches that can be performed on the MDC, and these searches are accessed using one of several interfaces.
This section provides are very high level overview of introductory concepts of searching with {branding}.
These concepts are expanded upon in later sections.

==== Search Types
There are four basic types of metadata search.
Additionally, any of the types can be combined to create a compound search.

===== Contextual Search
A contextual search is used when searching for textual information.
It is similar to a Google search over the metadata contained in the MDC.
Contextual searches may use wildcards, logical operators, and approximate matches.

===== Spatial Search
A spatial search is used for Area of Interest (AOI) searches.
Polygon and point radius searches are supported.
Specifically, the spatial search looks at the metacards' location attribute and coordinates are specified in WGS 84 decimal degrees.

===== Temporal Search
A temporal search finds information from a specific time range.
Two types of temporal searches are supported, relative and absolute.
Relative searches contain an offset from the current time, while absolute searches contain a start and an end timestamp.
Temporal searches can look at the effective date attribute or the modified date.

===== Datatype
A datatype search is used to search for metadata based on the datatype, and optional versions.
Wildcards (*) can be used in both the datatype and version fields.
Metadata that matches any of the datatypes (and associated versions if specified) will be returned.
If a version is not specified, then all metadata records for the specified datatype(s) regardless of version will be returned.

===== Compound Search
These search types may be combined to create Compound searches.
For example, a Contextual and Spatial search could be combined into one Compound search to search for certain text in metadata in a particular region of the world.

==== Search Interfaces

===== {branding} Search UI Application
The {branding} Search UI application provides a graphic interface to return results in HTML format and locate them on an interactive globe or map.
For more details on using this application, go to {branding} Search UI User's Guide.

===== SSH
Additionally, it is possible to use a client script to remotely access {branding} via SSH and send console commands to search and ingest data.

=== Catalog Search Result Objects
Data is returned from searches as Catalog Search Result objects.
This is a subtype of Catalog Entry that also contains additional data based on what type of sort policy was applied to the search.
Because it is a subtype of Catalog Entry, a Catalog Search Result has all Catalog Entry’s fields such as metadata, effective time, and modified time.
It also contains some of the following fields, depending on type of search, that are populated by {branding} when the search occurs:

* Distance: Populated when a point radius spatial search occurs.
Numerical value that indicates the result’s distance from the center point of the search.
* Units: Populated when a point radius spatial search occurs.
Indicates the units (kilometer, mile, etc.) for the distance field.
* Relevance: Populated when a contextual search occurs.
Numerical value that indicates how relevant the text in the result is to the text originally searched for.

==== Search Programmatic Flow
Searching the catalog involves three basic steps:

. Define the search criteria (contextual, spatial, temporal, or compound – a combination of two or more types of searches).
.. Optionally define a sort policy and assign it to the criteria.
.. For contextual search, optionally set the `fuzzy` flag to `true` or `false` (the default value for the `Metadata Catalog` `fuzzy` flag is `true`, while the `portal` default value is `false`).
.. For contextual search, optionally set the caseSensitive flag to true (the default is that caseSensitive flag is NOT set and queries are not case sensitive).
Doing so enables case sensitive matching on the search criteria.
For example, if caseSensitive is set to true and the phrase is “Baghdad” then only metadata containing “Baghdad” with the same matching case will be returned.
Words such as “baghdad”, “BAGHDAD”,  and “baghDad” will not be returned because they do not match the exact case of the search term.
. Issue a search
. Examine the results

These steps are performed in the same basic order but using different classes depending on whether the Web services or Search UI interfaces are used.

===== Sort Policies

Searches can also be sorted according to various built-in policies.
A sort policy is applied to the search criteria after its creation but before the search is issued.
The policy specifies to the {branding} the order the MDC search results should be in when they are returned to the requesting client.
Only one sort policy may be defined per search.

There are three policies available.

.Sort Policies
[cols="4" options="header"]
|===

|Sort Policy
|Sorts By
|Default Order
|Available for

|Temporal
|The catalog search result’s effective time field
|Newest to oldest
|All Search Types

|Distance
|The catalog search result’s distance field
|Nearest to farthest
|Point-Radius Spatial searches

|Relevance
|The catalog search result’s relevance field
|Most to least relevant
|Contextual

|===

If no sort policy is defined for a particular search, the temporal policy will automatically be applied.

[WARNING]
====
For Compound searches, the parent Compound search’s sort policy is used.
For example, if a Spatial search and Contextual search are the components of a Compound search, the Spatial search might have a distance policy and the Contextual search might have a relevance policy.
The parent Compound search, though, does not use the policy of its child objects to define its sorting approach.
The Compound search itself has its own temporal sort policy field that it will use to order the results of the search.
====
