:title: Developing Metacard Transformers
:type: developingComponent
:status: published
:link: _developing_metacard_transformers
:summary: Creating a custom metacard transformer.
:order: 08

In general, a `MetacardTransformer` is used to transform a `Metacard` into some desired format useful to the end user or as input to another process.
Programmatically, a `MetacardTransformer` transforms a `Metacard` into a `BinaryContent` instance, which translates the `Metacard` into the desired final format.
Metacard transformers can be used through the Catalog Framework `transform` convenience method or requested from the OSGi Service Registry by endpoints or other bundles.

==== Creating a New Metacard Transformer

Existing metacard transformers are written as Java classes, and these steps walk through the steps to create a custom metacard transformer.

. Create a new Java class that implements `ddf.catalog.transform.MetacardTransformer`. +
`public class SampleMetacardTransformer implements ddf.catalog.transform.MetacardTransformer`
. Implement the `transform` method. +
`public BinaryContent transform(Metacard metacard, Map<String, Serializable> arguments) throws CatalogTransformerException` +
.. `transform` must return a `Metacard` or throw an exception. It cannot return null.
. Import the ${branding} interface packages to the bundle manifest (in addition to any other required packages). +
`Import-Package: ddf.catalog,ddf.catalog.transform`
. Create an OSGi descriptor file to communicate with the OSGi Service registry (described in the <<Working with OSGi,Working with OSGi section>>). Export the service to the OSGi registry and declare service properties.
+
.Metacard Transformer Blueprint Descriptor Example
[source,xml,linenums]
----
...
<service ref="[[SampleMetacardTransformer]]" interface="ddf.catalog.transform.MetacardTransformer">
    <service-properties>
        <entry key="shortname" value="[[sampletransform]]" />
        <entry key="title" value="[[Sample Metacard Transformer]]" />
        <entry key="description" value="[[A new transformer for metacards.]]" />
    </service-properties>
</service>
...
----
+
. Deploy OSGi Bundle to OSGi runtime.

.Metacard Transformer Blueprint Service Properties / Variable Descriptions
[cols="3" options="header"]
|===
|Key
|Description of Value
|Example

|`shortname`
|(Required) An abbreviation for the return type of the BinaryContent being sent to the user.
|atom

|`title`
|(Optional) A user-readable title that describes (in greater detail than the shortname) the service.
|Atom Entry Transformer Service

|`description`
|(Optional) A short, human-readable description that describes the functionality of the service and the output.
|This service converts a single metacard xml document to an atom entry element.

|===
