
=== ${admin-console}

The ${admin-console} is the centralized location for administering the system.
The ${admin-console} allows an administrator to install and remove selected applications and their dependencies and access configuration pages to configure and tailor system services and properties.
The default address for the ${admin-console} is \${secure_url}/admin.

==== ${admin-console} Modules

The ${admin-console} is a modular system that can be expanded with additional modules as necessary.
${ddf-admin} comes with the Configuration module and the Installer modules.
However, new modules can be added, and each module is presented in its own tab of the ${admin-console}.

Admin Modules are single components that implement the `org.codice.ddf.ui.admin.api.module.AdminModule` interface.
Once they implement and expose themselves as a service, they are added to the ${admin-console} as a new tab.

===== Included Modules

* <<_installer_module, Installer Module>>
* <<_configuration_module, Configuration Module>>

====== Installer Module

The application installer module enables a user to install and remove applications.
Each application includes a features file that provides a description of the application and a list of the dependencies required to successfully run that application.
The installer reads the features file and presents the applications in a manner that allows the administrator to visualize these dependencies.
As applications are selected or deselected, the corresponding dependent applications are selected or deselected as necessary.

====== Set Up the Installer Module

. Install the module if it is not already pre-installed. +
`feature:install admin-modules-installer`

. Open a web browser and navigate to the Installation page. +
`http://DDF_HOST:DDF_PORT/admin`
- Adding the `?dev=true` query string will auto generate the certificates +
`http://DDF_HOST:DDF_PORT/admin/index.html?dev=true`

. Log in with the default username of "admin" (no quotes) and the default password of "admin" (no quotes).

. Select the Setup tab if not already selected.

[IMPORTANT]
====
Do NOT deselect/uninstall the Platform App or the Admin App.
Doing so will disable the use of this installer and the ability to install/uninstall other applications.
====

* Installation Profile Page
** When a profile is selected, it will auto select applications on the *Select Application* page and install them automatically.
** If customizing a profile, manually select the applications on the *Select Application* page.
* On the *Select Applications* page, hover over each application to view additional details about the application.
* New applications can be added and existing applications can be upgraded using the *Applications* Module.
* When an application is selected, dependent applications will automatically be selected.
* When an application is unselected, dependent applications will automatically be unselected.

===== Custom Installation

* If apps are preselected when the *Select Applications* page is reached, they will be uninstalled if unselected.

* Applications can also be installed using kar deployment as stated in <<_application_installation,Application Installation>>.

[WARNING]
====
The ${ddf-platform}, ${ddf-admin}, and ${ddf-security} applications are required and CANNOT be selected or unselected.

The ${ddf-security} Application appears to be unselected upon first view of the tree structure, but it is in fact automatically installed with a later part of the installation process.
====

[NOTE]
====
Certificate information needs to be provided if the host is changed.
If the `?dev=true` query string was provided, the certificate information will be auto generated using a demo CA
====

[NOTE]
====
The redirect will only work if the certificates are configured in the browser. +
Otherwise the redirect link must be used.
====

====== Configuration Module

The configuration module allows administrators to change bundle and service configurations.

====== Set Up the Configuration Module

. Install the module if it is not pre-installed.
`feature:install admin-modules-configuration`

. Open a web browser and navigate to the ${admin-console} page.

`http://DDF_HOST:DDF_PORT/admin`

. Select the Configurations tab if not already selected.

====== Configurations Tab

==== ${admin-console} Access Control

If you have integrated ${branding} with your existing security infrastructure, then you may want to limit access to parts of the ${branding} based on user roles/groups.

===== Restricting ${branding} Access

. Select the *Web Context Policy Manager*. (see <<_web_context_policy_manager,Web Context Policy Manager>> for details.)

.. A dialogue will pop up that allows you to edit ${branding} access restrictions.

.. Once you have configured your realms in your security infrastructure, you can associate them with ${branding} contexts.

.. If your infrastructure supports multiple authentication methods, they may be specified on a per-context basis.

.. Role requirements may be enforced by configuring the required attributes for a given context.

.. The whitelist allows child contexts to be excluded from the authentication constraints of their parents.

===== Restricting ${branding} Feature, App, Service, and Configuration Access

. Select the *Admin Configuration Policy* under the ${ddf-admin} Application.

. To add a feature or app permission:

.. Add a new field to "Feature and App Permissions" in the format of: `feature name/app name = "attribute name=attribute value","attribute name2=attribute value2", ...`

.. For example, to restrict access of any user without an admin role to the catalog-app: `catalog-app = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/role=admin", ...`

. To add a configuration permission:

.. Add a new field to "Configuration Permissions" in the format of: `configuration id = "attribute name=attribute value","attribute name2=attribute value2", ...`

.. For example, to restrict access of any user without an admin role to the Web Context Policy Manager: `org.codice.ddf.security.policy.context.impl.PolicyManager="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/role=admin"`

If a permission is specified, any user without the required attributes will be unable to see or modify the feature, app, or configuration.

==== LDAP Admin Role Configuration

The admin role will default to `system-admin`. This can be configured to work with an external LDAP with a few minor changes.

===== Update the Admin Role in `INSTALL_HOME/etc/users.properties`

Change the value of 'system-admin' to the new admin role for any users needing the new role.

.Example `user.properties` entries:
[source]
----
admin=admin,group,admin,manager,viewer,system-admin
localhost=localhost,group,admin,manager,viewer,system-admin
----

[NOTE]
====
A system restart is required for the changes to `users.properties` to take effect.
====

===== Update the Web Context Policy to Point to the New Admin Role

. Navigate to the *${admin-console}*.
. Select the *${ddf-security}* Application.
. Select the *Configuration* tab.
. Select the *Web Context Policy Manager*.
. Update the entries under 'Required Attributes' to set the new admin role.

