
The Platform application is considered to be a core application of the distribution.
The Platform application provides the fundamental building blocks that the distribution needs to run.
These building blocks include subsets of:

* http://karaf.apache.org/[Karaf], 
* http://cxf.apache.org/CXF[CXF],  and 
* http://camel.apache.org/[Camel]. 

A Command Scheduler is also included as part of the Platform application.
The Command Scheduler allows users to schedule Command Line Shell Commands to run at certain specified intervals.

=== Using Platform Application

The Platform application is a core building block for any application and should be referenced for its core component versions so that developers can ensure compatibility with their own applications.
The Command Scheduler included in the Platform application should be for the convenience of a "platform independent" method of running certain commands, such as backing up data or logging settings.

=== Installing and Uninstalling Platform

==== Prerequisites
Before the {branding} Platform application can be installed:

* the {branding} Kernel must be running.

==== Installing

The Platform application is installed by default on a standard installation.

==== Configuring {branding} Platform
 
[cols="1,1,2" options="header"]
|===
|Configuration
|ID
|Description

|Landing Page
|`org.codice.ddf.distribution.landing-page.properties`
|Customize elements seen on landing page.

|MIME Custom Types
|`DDF_Custom_Mime_Type_Resolver`
|Add or configure resolvers to identify files by type.

|Metrics Reporting
|`MetricsReporting`
|Allocate resources for metrics collection.

|Persistent Store
|`org.codice.ddf.persistence.internal.PersistentStoreImpl`
|Set URL for Solr server used as persistant store.

|Platform Command Scheduler
|`ddf.platform.scheduler.Command`
|Schedule shell commands to run periodically.

|Platform UI Configuration
|`ddf.platform.ui.config`
|

|===
