:title: URL Resource Reader
:type: subArchitecture
:status: published
:parent: Resource Readers
:order: 00
:summary: URL Resource Reader.

((({title})))
The `URLResourceReader` is an implementation of `ResourceReader` which is included in the ${branding} Catalog.
It obtains a resource given an http, https, or file-based URL.
The `URLResourceReader` connects to the provided Resource URL and reads the resource's bytes into an `InputStream`.

[WARNING]
====
When a resource linked using a file-based URL is in the product cache, the ``URLResourceReader``'s `rootResourceDirectories` is not checked when downloading.
It is downloaded from the product cache which bypasses the `URLResourceReader`.
For example, if path `/my/valid/path` is configured in the ``URLResourceReader``'s `rootResourceDirectories` and one downloads the product with resource-uri `file:///my/valid/path/product.txt` and then one removes `/my/valid/path` from the ``URLResourceReader``'s `rootResourceDirectories` configuration, the product is still accessible via the product cache.
====

== Installing the URL Resource Reader

The `URLResourceReader` is installed by default with a standard installation in the ${ddf-catalog} application.

== Configuring the URL Resource Reader

Configure the URL Resource Reader from the ${admin-console}.

. Navigate to the *${admin-console}*.
. Select the *OSGi*.
. Select the *Configuration* tab.
. Select the *URL Resource Reader*.

See <<{reference-prefix}ddf.catalog.resource.impl.URLResourceReader,URL Resource Reader configurations>> for all possible configurations.

== Using the URL Resource Reader

`URLResourceReader` is used by the Catalog Framework to obtain a resource whose metacard is cataloged in the local data store.
This particular `ResourceReader` is chosen by the `CatalogFramework` if the requested resource's URL has a protocol of `http`, `https`, or `file`.

For example, requesting a resource with the following URL makes the Catalog Framework invoke the `URLResourceReader` for retrieval.

.Example
[source,http]
----
file:///home/users/${ddf-branding}_user/data/example.txt
----

If a resource was requested with the URL `udp://123.45.67.89:80/SampleResourceStream`, the `URLResourceReader` would _not_ be invoked.

.Supported Schemes:
* http
* https
* file

[NOTE]
====
If a file-based URL is passed to the `URLResourceReader`, that file path needs to be accessible by the ${branding} instance.
====
