
====== Installer Module

The application installer module enables a user to install and remove applications.
Each application includes a features file that provides a description of the application and a list of the dependencies required to successfully run that application.
The installer reads the features file and presents the applications in a manner that allows the administrator to visualize these dependencies.
As applications are selected or deselected, the corresponding dependent applications are selected or deselected as necessary.

====== Set Up the Installer Module

. Install the module if it is not already pre-installed. +
`feature:install admin-modules-installer`

. Open a web browser and navigate to the Installation page. +
`${secure_url}/admin`
- Adding the `?dev=true` query string will auto-generate certificates +
`${secure_url}admin/index.html?dev=true`

. Log in with the default username of "admin" (no quotes) and the default password of "admin" (no quotes).

. Select the Setup tab if not already selected.

[IMPORTANT]
====
Do NOT deselect/uninstall the Platform App or the Admin App.
Doing so will disable the use of this installer and the ability to install/uninstall other applications.
====
