
== ${branding} Use of OGC Filter

An OGC Filter is a Open Geospatial Consortium (OGC) standard that describes a query expression in terms of XML and KVP.

The OGC Filter is used to represent a query to be sent to <<_sources,Sources>> and the <<_Catalog_Provider,Catalog Provider>>, as well as to represent a <<_subscription,Subscription>>.
The OGC Filter provides support for expression processing such as being able to Add or Divide expressions in a query, but that is not the intended use for ${ddf-branding}.

The ${ddf-branding} Catalog Framework utilizes the implementation provided by Geotools that is a Java representation of the standard.
Geotools originally provided standard Java classes for the OGC Filter Encoding 1.0, under the package name `org.opengis.filter`, which is where `org.opengis.filter.Filter` is located.
A special note should be added that there is no intent right now that Java developers should be parsing or viewing the XML representation.
The intention is that developers will use the Java objects exclusively to complete query tasks.
