:title: Configuring Included STS
:type: subConfiguration
:status: published
:parent: Configuring REST Services for Users
:order: 01
:summary: Configuring STS.

// This is a subsection of Configuring Included IdP and has a added title level.
=== {title}

An LDAP server can be used to maintain a list of ${branding} users and the attributes associated with them.
The <<{integrating-prefix}security_sts,Security Token Service (STS)>> can use an LDAP server as an attribute store and convert those attributes to SAML claims.

${branding} includes a demo <<{developing-prefix}embedded_ldap_server,LDAP server>>, but an external LDAP is required for actual installation.

The STS is installed by default in ${branding}.

.Configuring STS
. Verify that the `serverKeystores.jks` file in `${home_directory}/etc/keystores` trusts the hostnames used in your environment (the hostnames of LDAP, and any ${branding} users that make use of this STS server).
. Navigate to the *${admin-console}*.
. Select the *System* tab.
. Select the *Features* tab.
. Start the `security-sts-ldaplogin` and `security-sts-ldapclaimshandler` features.
. Select the *Configuration* tab.
. Select the *Security STS LDAP Login* configuration.
. Verify that the *LDAP URL*, *LDAP Bind User DN*, and *LDAP Bind User Password* fields match your LDAP server's information.
.. The default ${branding} LDAP settings will match up with the default settings of the OpenDJ embedded LDAP server. Change these values to map to the location and settings of the LDAP server being used.
. Select the *Save changes* button if changes were made.
. Open the *Security STS LDAP and Roles Claims Handler* configuration.
. Populate the same URL, user, and password fields with your LDAP server information.
. Select the *Save Changes* button.

.Configuring ${branding} Authentication Scheme
Configure the ${branding} to use this authentication scheme.

. Navigate to the *${admin-console}*.
. Select the *${ddf-catalog}* application.
. Open the *Web Context Policy Manager* configuration.
.. Under *Context Realms* add the contexts that should be protected under the ldap realm.
... The default setting is `/=karaf`, the `karaf` realm refers to the `users.properties` user store file located in the `${home_directory}/etc` directory. This can be changed to `/=ldap`, if it is desired that the entire container be protected under ldap. If the `/admin` context is changed to something other than the default (`karaf`), it will be required that you refresh the page in order to log in again, or your changes may not be saved. This includes changing the root context to something other than `karaf`, without specifically setting `/admin` to a realm. The policies for all contexts will roll up, for example: the `/admin` context policy will roll up to the karaf realm with the default configuration because `/` is higher in the context heirarchy than `/admin` and no realm is specifically set for `/admin`.
.. Under *Authentication Types*, make any desired authentication changes to contexts.
... In order to use the SAML 2.0 Web SSO profile against a context, you must specify only the IdP authentication type.

.Security STS Client
Configure the client connecting to the STS.

. Navigate to the *${admin-console}*.
. Select the *${ddf-security}* application.
. Open the *Security STS Client* configuration.
. Verify that the host/port information in the *STS Address* field points to your STS server. If you are using the default bundled STS, this information will already be correct.

See <<{application-prefix}ddf.security.sts.client.configuration,Security STS Client>> table for all configuration options.

The ${branding} should now use the SSO/STS/LDAP servers when it attempts to authenticate a user upon an attempted log in.

.STS Server
Connect to the server hosting the STS.

. Navigate to the *${admin-console}*.
. Select the *${ddf-security}* application.
. Select the *Security STS Server* configuration.
. Verify the hostname and usernames are correct.

See <<{application-prefix}ddf.security.sts,Security STS Server>> table for all configuration options.

.SAML Name ID
Set up alternatives to displaying the username of the logged in user.

. Navigate to the *${admin-console}*.
. Select the *${ddf-security}* application.
. Select the *SAML NameID Policy* configuration.
. Add any desired attributes to display instead of the username. (The first matching attribute will be used.)

.[[_limiting_access_to_the_sts]]Limiting Access to the STS
Be sure to limit the hosts that are allowed to connect to the STS:

* *{hardening-step}*

* Open the `${home_directory}/etc/custom.system.properties` file.
* Edit the line `ws-security.subject.cert.constraints = .\*CN=<MY_HOST_CN>.*`.
** By default this will only allow your hostname. To allow other desired hosts add their CNs to the regular expression within parentheses delimited by `|`:
*** `ws-security.subject.cert.constraints = .\*CN=(<MY_HOST_CN>|<OTHER_HOST_CN>|<ANOTHER_HOST_CN>).*`
