:title: Content Directory Monitor
:type: configuration
:status: published
:parent: Configuring Data Management
:order: 03
:summary: Content Directory Monitor.

== {title}

The Content Directory Monitor (CDM) provides the capability to easily add content and metacards into the ${ddf-catalog} by placing a file in a directory.

=== Installing the Content Directory Monitor

The Content Directory Monitor is installed by default with a standard installation of the ${ddf-catalog} application.

=== Configuring the Content Directory Monitor

Configure the CDM from the ${admin-console}:

. Navigate to the *${admin-console}*.
. Select the *${ddf-catalog}* application.
. Select the *Configuration* tab.
. Select *Catalog Content Directory Monitor*.

.Content Directory Monitor Permissions
[IMPORTANT]
====
When setting monitored directory, make sure to set permissions on the new directory to allow ${branding} to access it.
====

See <<org.codice.ddf.catalog.content.monitor.ContentDirectoryMonitor,Content Directory Monitor configurations>> for all possible configurations.

=== Using the Content Directory Monitor

The CDM processes files in a directory, and all of its sub-directories. The CDM offers three options:

* Delete
* Move
* Monitor in place

Regardless of the option, the ${branding} takes each file in a monitored directory structure and creates a metacard for it. The metacard is linked to the file. The behavior of each option is given below.

.Delete
* Copies the file into the Content Repository.
* Creates a metacard in the Catalog from the file.
* *Erases* the original file from the monitored directory.

.Move
* Copies the file into the directory `.\ingested` *(this will double the disk space used)*
* Copies the file into the Content Repository.
* Creates a metacard in the Catalog from the file.
* *Erases* the original file from the monitored directory.

.Monitor in place
* Creates a metacard in the Catalog from the file.
* Creates a reference from the metacard to the original file in the monitored directory.
* If the original file is deleted, the metacard is removed from the Catalog.
* If the original file is modified, the metacard is updated to reflect the new content.
* If the original file is renamed, the old metacard is deleted and a new metacard is created.

.Parallel Processing
The CDM supports parallel processing of files (up to 8 files processed concurrently).  This is configured by setting the number of *Maximum Concurrent Files* in the configuration.  A maximum of 8 is imposed to protect system resources.

.Read Lock
When the CDM is set up, the directory specified is continuously scanned, and files are locked for processing based on the *ReadLock Time Interval*.  This does not apply to the *Monitor in place* processing directive.  Files will not be ingested without having a ReadLock that has observed no change in the file size.
This is done so that files that are in transit will not be ingested prematurely. The interval should be dependent on the speed of the copy to the directory monitor (ex. network drive vs local disk).
For local files, the default value of 500 milliseconds is recommended. The recommended interval for network drives is 1000 - 2000 milliseconds.  If the value provided is less than 100, 100 milliseconds will be used.
It is also recommended that the *ReadLock Time Interval* be set to a lower amount of time when the *Maximum Concurrent Files* is set above 1 so that files are
locked in a timely manner and processed as soon as possible.  When a higher *ReadLock Time Interval* is set, the time it takes for files to be processed is increased.

.Attribute Overrides
The CDM supports setting metacard attributes directly when ${branding} ingests a file. Custom overrides are entered in the form:

`*attribute-name=attribute-value*`

For example, to set the contact email for all metacards, add the attribute override:

`*contact.point-of-contact-email=doctor@clinic.com*`

Each override sets the value of a single metacard attribute. To set the value of an additional attribute, select the "plus"
 icon in the UI. This creates an empty line for the entry.

To set multi-valued attributes, use a separate override for each value. For example, to add the keywords _PPI_ and _radiology_ to each metacard, add the custom attribute overrides:

`*topic.keyword=PPI*` +
`*topic.keyword=radiology*`

Attributes will only be overridden if they are part of the <<_metacard_type, metacard type>> or are <<_attribute_injection_definition,injected>>.

All attributes in the <<_catalog_taxonomy_definitions, catalog taxonomy tables>> are injected into all metacards by default and can be overridden.

[IMPORTANT]
====
If an overridden attribute is not part of the <<_metacard_type, metacard type>> or <<_attribute_injection_definition,injected>> the attribute will not be added to the metacard.
====

For example, if the metacard type contains contact email,

`*contact.point-of-contact-email*`

but the value is not currently set, adding an attribute override will set the attribute value.
To override attributes that are not part of the metacard type, <<_attribute_injection_definition,attribute injection>> can be used.

.Blacklist
The CDM blacklist uses the "bad.files" and "bad.file.extensions" properties from the system.properties file in "etc/" in order to prevent
malicious or unwanted data from being ingested into DDF.  While the CDM automatically omits hidden files, this is particularly useful when
an operating system automatically generates files that should not be ingested.  One such example of this is "thumbs.db" in Windows.
This file type and any temporary files are included in the blacklist.

.Errors
If the CDM fails to read the file, an error will be logged in the ingest log. If the directory monitor is
configured to *Delete* or *Move*, the original file is also moved to the `\.errors` directory.

.Other
* Multiple directories can be monitored. Each directory has an independent configuration.
* To support the monitoring in place behavior, ${branding} indexes the files to track their names and modification timestamps. This enables the Content Directory Monitor to take appropriate action when files are changed or deleted.
* The Content Directory Monitor recursively processes all subdirectories.

