:title: Hardening Solr Index
:type: subConfiguration
:status: published
:parent: Configuring Solr
:summary: Hardening Solr Index.
:order: 02

== {title}

The following sections provide hardening guidance for Solr; however, they are to serve only as reference and other an additional security requirements may be added. These instructions are relevant only
to the <<_external_solr, externally managed Solr configuration>>.

=== Hardening an Internally Managed Solr Server

The internally managed Solr configuration is configured to be secure by default. No additional
hardening should be necessary.

=== Hardening an External Solr Server

There is more than one way to configure the system to ensure secure communication between
${branding} and an external Solr server. If the external server runs on a different host than
${branding}, it is recommended that the Solr server be configured to use two-way TLS. See
Apache Solr Reference Guide,
https://lucene.apache.org/solr/guide/6_6/enabling-ssl.html#enabling-ssl[Enabling SSL]

For an example of configuring a host to use two-way TLS, see the script function named
`


=== Configuring Solr Encryption

While it is possible to encrypt the Solr index, it decreases performance significantly.
An encrypted Solr index also can only perform exact match queries, not relative or contextual queries.
As this drastically reduces the usefulness of the index, this configuration is not recommended.
The recommended approach is to encrypt the entire drive through the Operating System of the server on which the index is located.
