:title: Hardening Solr Index
:type: subConfiguration
:status: published
:parent: Configuring Solr
:summary: Hardening Solr Index.
:order: 02

== {title}

The following sections provide hardening guidance for Solr; however, they are to serve only as reference and other an additional security requirements may be added.

=== Hardening Solr Server Configuration

The Solr server configuration is configured to be secure by default. No additional
hardening should be necessary. Solr is configured to reject all remote requests
by default. It is only accessible locally. This is a necessary part of a secure configuration.
To enable remote requests for troubleshooting, edit the script
file `ddf` (or the `ddf.bat` file for Windows) and remove
the `solr.jetty.host` and `jetty.host` parameters.

=== Configuring Solr Encryption

While it is possible to encrypt the Solr index, it decreases performance significantly.
An encrypted Solr index also can only perform exact match queries, not relative or contextual queries.
As this drastically reduces the usefulness of the index, this configuration is not recommended.
The recommended approach is to encrypt the entire drive through the Operating System of the server on which the index is located.
