:title: Hiding Errors and Warnings from Users Based on Role
:type: subConfiguration
:status: published
:parent: Configuring Errors and Warnings
:order: 02
:summary: Prevent certain users from seeing data with certain types of errors or warnings.

== {title}

Prevent certain users from seeing data with certain types of errors or warnings.
Typically, this is used for security markings.
If the *Metacard Validation Filter Plugin* is configured to *Filter errors* and/or *Filter warnings*, metacards with errors/warnings will be hidden from users without the specified user attributes.

. Navigate to the *${admin-console}*.
. Select the *${ddf-catalog}* application.
. Select *Configuration*.
. Select *Metacard Validation Filter Plugin*.
. For *Attribute map*, enter both the metacard `SECURITY` attribute to filter and the user attribute to filter.
.. The default attribute for viewing invalid metacards is `invalid-state`
... `invalid-state=<USER ROLE>`.
... Replace `<USER ROLE>` with the roles that should be allowed to view invalid metacards.
[NOTE]
To prevent other ${branding} systems from querying invalid data in the local catalog, it is
recommended to create and set user roles that are unique to the local system (ie. a user role
that includes a UUID).
. Select *Filter errors* to filter errors. Users without the `invalid-state` attribute will not see metacards with errors.
. Select *Filter warnings* to filter warnings. Users without the `invalid-state` attribute will not see metacards with warnings.
