:title: Importing the Exported Configuration Settings
:type: configuration
:status: published
:parent: Reusing Configurations
:summary: Importing the exported configuration settings.
:order: 01

== {title}

To import a previously exported configuration file from the ${command-console}:

. Launch the newly installed ${branding}.
. Step through the installation process.
. Copy the previously exported file from your secure place to the `exported` directory underneath `${home_directory}`, but an alternative location can be specified with the `migration:import`. Create the directory if it does not exist.
. Run the command migration:import from the ${command-console}.
. Finish <<_hardening_checklist,hardening>> the system (e.g. file and directory permissions).

[IMPORTANT]
====
* The following is currently not supported when importing configuration files:
** importing from a different ${branding} version
** importing from a system installed on a different OS
** importing from a system installed in a different directory location
* To keep the export/import process simple and consistent, all system configuration files are required to be under the `${home_directory}` directory and not be softlinks. Presence of external files or symbolic links during export will not fail the export; they will yield warnings. It will be up to the adminsitrator to manually copy these files over to the new system before proceeding with the import. The import process will verify their presence and consistency and yield warnings if they don't match the original files.
* The import process will re-import all configurations done on the original system as part of the <<_hardening_checklist,hardening process>> including changes to starting scripts and certificates.
====

