:title: Login and Logout Page Configuration
:type: configuration
:status: published
:parent: Admin Theming Configurations
:summary: Configure login and logout pages displayed on ${branding}.
:order: 01

== {title}

The login and logout pages are presented to users through the navigation of ${branding}.
These pages have features that can optionally be changed if non-default features are desired.

=== Navigating to Login and Logout Configuration

Configure the Login and Logout pages from the ${admin-console}:

. Navigate to the *${admin-console}*.
. Select *${ddf-security}* Application.
. Select *Configuration* tab.
. Select:
.. *Login Page*.
.. *Logout Page*.

=== Login Page Customization

The login page has 4 fields that can be configured:

. Header
. Footer
. Style
. Text Color

See <<org.codice.ddf.security.handler.guest.configuration,Login Page configuration>> for detailed configurations.

=== Logout Page Customization

The customizable feature of the logout page is the *Log Out Page Time Out*. This is the time limit the IDP
client will wait for a user to click log out on the logout page.

. *Default value*: 3600000


