:title: Platform UI Themes
:type: configuration
:status: published
:parent: Configuring UI Themes
:summary: Configure theme of all pages displayed on ${branding}.
:order: 02

== {title}

The Platform UI Configuration allows for the customization of attributes of all pages within ${branding}.
It contains settings to display messages to users at login or in banners in the headers and footers of all pages,
along with changing the colors of text and backgrounds.

=== Navigating to UI Theme Configuration

. Navigate to the *${admin-console}*.
. Select the *${ddf-platform}* application.
. Select *Configuration*.
. Select *Platform UI Configuration*.

=== Customizing the UI Theme

The customization of the UI theme across ${branding} is available through the capabilities of Platform UI Configuration.
The banner has four items to configure:

. *Header* (text)
. *Footer* (text)
. *Text Color*
. *Background Color*

See the <<{reference-prefix}ddf.platform.ui.config,Platform UI>> for all possible configurations of the Platform UI Configuration.