:title: Reusing Configurations
:type: subConfiguration
:status: published
:parent: Multiple Installations
:summary: Export a current ${branding} configuration and use it to restore the system to the same state on a brand new installation.
:order: 00

== {title}

The Migration Export/Import capability allows administrators to export the current ${branding} configuration and use it to restore the same state for either a brand new installation or a second node for a Highly Available Cluster.

To export the current configuration settings:

. Run the command migration:export from the ${command-console}.
. A file named `${branding-lowercase}-${project.version}.dar` will be created in the `exported` directory underneath `${home_directory}`. Copy this file to a secure location.

To import previously exported configuration settings:

. Install ${branding}
. Restore all external files, softlinks, and directories that would not have been exported and for which warnings would have been generated during export. This could include (but is not limited to) external certificates or monitored directories.
. Launch the newly installed ${branding}.
. Step through the installation process.
. Make sure to install and re-enable the ${branding} <<_starting_as_a_service_with_automatic_start_on_system_boot,service>> on the new system if it was installed and enabled on the original system
. Copy the previously exported file from your secure location to the `exported` directory underneath `${home_directory}`. Create the directory if it does not exist.
. Run the command migration:import from the ${command-console}.
. ${branding} will automatically restart if the command is successful. Otherwise address any generated warnings before manually restarting ${branding}.
. Finish <<_hardening_checklist,hardening>> the system (e.g. file and directory permissions).

[IMPORTANT]
====
* The following is currently not supported when importing configuration files:
** importing from a different ${branding} version
** importing from a system installed on a different OS
** importing from a system installed in a different directory location
* To keep the export/import process simple and consistent, all system configuration files are required to be under the `${home_directory}` directory and not be softlinks. Presence of external files or symbolic links during export will not fail the export; they will yield warnings. It will be up to the adminsitrator to manually copy these files over to the new system before proceeding with the import. The import process will verify their presence and consistency and yield warnings if they don't match the original files.
* The import process will re-import all configurations done on the original system as part of the <<_hardening_checklist,hardening process>> including changes to starting scripts and certificates.
====
