
Introduction: The ${catalog-ui} represents the most advanced search interface available with ${branding}.
It provides a metadata search and discovery, resource retrieval, and workspace management with a 3d or optional 2d map visualization.

[NOTE]
====
For more detail on any feature or button within the Catalog UI, click the `?` button in the upper right of the screen; then, hover over any item on the screen and a contextual tooltip will to define its purpose.
To exit this mode, click the `?` again or press `escape`.
====

=== Accessing ${catalog-ui}

The default location for the ${catalog-ui} is ${secure_url}/search/catalog

=== Catalog UI Guest Users

If Guest access has been enabled, users not signed in to ${branding} (guest users) will have access to search functions, but all workspace configuration and settings will only exist locally and not be available for sharing.

=== Workspaces in ${catalog-ui}

Within the ${catalog-ui}, workspaces are collections of settings, searches, and bookmarks that can be shared between users and stored to be accessed repeatedly.

==== Creating a Workspace in ${catalog-ui}

Before searching in ${branding}, at least one workspace must be created.
Use an existing template or create a blank workspace.

.Default Workspace Templates
Local:: an example of a local search.
Federated:: an example of a federated search.
Location:: an example of a geographically constrained search.
Temporal:: an example of a temporally constrained search.

==== Configuring a Workspace in ${catalog-ui}

Configure each workspace with queries and share options.

.Adding searches
. Select the default name of the workspace (*New Workspace* or template name) to change to a unique name.
. If *Blank* workspace was selected, select *Add Search* to add the first search. Each workspace can have up to ten searches.
.. Select *Basic* Search to select simple search criteria, such as *text*, *time*, and *location*.
.. Select *Advanced* Search to access a query-builder for more complex queries.

.Navigator Menu Options
* *Workspaces*: View all available workspaces.
* *Upload*: Interface to add resources to catalog.
* *Open Workspaces* (if applicable): Shows a list of open workspaces.

.Workspace Menu Options
* Select the *Menu* button next to the Workspace name.
** *Save*: Save changes to the workspace.
** *Run All Searches*: Start all saved searches within this workspace.
** *Cancel All Searches*: Cancel all running searches.
** *Open in New Tab*: Opens this workspace in a separate tab.
** *View Sharing*: View and edit settings for sharing this workspace. (User must be signed in to share or view shared workspaces.)
** *View Details*: View the current details for a cloud-based workspace (User must be signed in).
** *Duplicate*: Create a copy of this workspace.
** *Subscribe*: Receive email notifications for search results on this workspace (If email notifications have been enabled).
** *Move to Trash*: Delete (archive) this workspace.

==== Sharing Workspaces

In the ${catalog-ui}, workspaces can be shared between users at different levels of access as needed.

.Share a Workspace
. Select the Workspace.
. Select the *Options* menu.
. Select *View Sharing*.
.. To share by user role, set the drop-down menu to *Can Access* for each desired role. All users with that role will be able to view.
.. To share with an individual user, add their email to the email list.
. Click *Apply*.

.Remove Sharing on a Workspace
. Select the Workspace.
. Select the *Options* Menu.
. Select *View Sharing*.
.. To remove the workspace from users with specific roles, set the drop-down menu to *No Access* for that role.
.. To remove individual users, remove their email from the email list.

=== Searching with ${catalog-ui}

The Search pane has three tabs: *Searches*, *Results*, and *Bookmarks*.

==== Searches Tab

View, edit, and add searches from this tab.

.Search Menu Options
* *Run*: Trigger this search to begin immediately.
* *Stop*: Stop this search.
* *Delete*: Remove this search
* *Duplicate*: Create a copy of this search as a starting point
* *Search Archived*: Execute the search, but specifically for archived results.

===== Editing a Search

Existing searches and their settings can be updated by clicking on the search in the *Searches* tab of the workspace.

The editable components of a search are defined on these tabs:

* *Basic*: Define a <<_text_search,Text>>, <<_spatial_search,Spatial>>, <<_temporal_search,Temporal>>, or <<_datatype_search,Datatype>> Search.
* *Advanced*: Advanced query builder to create more specific searches.
* *Settings*: Set preferences for *Sorting* and *Federation*.
* *Notifications*: Define the frequency at which to run this search and receive notification of new results
* *Status*: View details of recent instances of this search.

====== Editing Search Settings

Under the settings tab for each search, edit the default *Sorting* and *Federation* (which sources are searched).

====== Setting Search Frequency

Edit the *Notifications* tab for a search to set the interval at which to run the query.

====== Viewing Search Status

The *Status* tab on the search preview displays the creation date and the sources successfully searched.

==== Viewing Search Results

Returned search results can be refined further, bookmarked, and/or downloaded from the *Results* tab.
Results sets are color-coded by source as a visual aid.
There is no semantic meaning to the colors assigned.

. Select a saved query.
. Perform any of these action upon the results list of the selected query:
.. Filter results further.
.. Re-sort list(default is _title_/_ascending_).
.. Toggle between *list* and *gallery* view.

==== Bookmarks Tab

Search Results that have been bookmarked can be filtered and sorted.

.Bookmarked Result Options
* *Add to Bookmarks*.
** Changes to *Remove from Bookmarks* for bookmarked items.
* *Hide from Future Searches*.
* *Expand Metacard View*.
* *Download*.

=== Result Preview Pane

On the *Result Preview* pane, view a summary of information about the selected resource.
The *Details* tab provides a list of specific metadata.

<<_viewing_revision_history,History>>:: View revision history of this resource.
<<_editing_associations_on_a_record,Associations>>:: View or edit the relationship(s) between this resource and others in the catalog.
<<_viewing_metadata_quality,Quality>>:: View the completeness and accuracy of the metadata for this resource.
<<_exporting_a_record,Actions>>:: Export the metadata/resource to a specific format.
<<_archiving_a_record,Archive>>:: Remove the selected record from standard search results.
<<_overwriting_a_record,Overwrite>>:: Overwrite a record.

==== Editing Records

Records can be edited from the *Summary* or *Details* tabs.

==== Editing Associations on a Record

Update relationships between records through *Associations*.

. Select the desired record from the *Results* tab.
. Select the *Associations* tab.
. Select *Edit*.
. For a new association, select *Add Association*. (Only items in the current result set can be added as associations).
.. Select the related record from either the *Parent* or *Child* menu.
.. Select the type of relationship from the *Relationship* menu.
.. Select *Save*.
. To edit an existing association, update the selections from the appropriate menu and select *Save*.

==== Viewing Revision History

View the complete revision history of a record.

. Select the desired record from the *Results* tab.
. Select the *History* tab.
.. Select a previous version from the list to preview.
.. If desired, select *Revert to Selected Version* to undo changes made after that revision.

==== Viewing Metadata Quality

View and fix issues with metadata quality in a record.

[NOTE]
====
Correcting metadata issues may require heightened permissions.
====

. Select the desired record from the *Results* tab.
. Select *More*.
. Select *Quality*.
. A report is displayed showing any issues:
.. Metacard Validation Issues.
.. Attribute Validation Issues.

==== Exporting a Record

Export and view a resource and/or its metadata into another format.

. Select the desired record from the *Results* tab.
. Select *More*.
. Select *Actions*.
. Available export formats are listed. Select desired format.
. Export opens in a new browser tab. Save, if desired.

==== Archiving a Record

To remove a record from active search results, archive it.

. Select the desired record from the *Results* tab.
. Select *More*.
. Select *Archive*.
. Confirm archiving the record.

==== Restoring an Archived Record

Restore an archived record to return it to active search results.

. Select the *Search Archived* option from the query options menu.
. Select the desired record from the *Results* tab.
. Select *Archive*.
. Confirm restoring the record.

==== Overwriting a Record

Replace a resource.

. Select the desired record from the *Results* tab.
. Select *More*.
. Select *Overwrite*.


