
=== Migration API

[NOTE]
====
This code is experimental. While this interface is functional and tested, it may change or be removed in a future version of the library.
====

${branding} currently has an experimental API for making bundles migratable. Interfaces in `platform/migration/platform-migratable-api` are
used by the system to identify bundles that provide implementations for  export and import(_coming soon_) operations.

The `Migratable` API provides a mechanism for bundles to handle exporting data required to clone a ${branding} system.
The migration process is meant to be flexible, so an implementation of `org.codice.ddf.migration.Migratable` can handle exporting data for a single bundle or groups of bundles such as applications.
For example, the `org.codice.ddf.platform.migratable.impl.PlatformMigratable` handles exporting core system files for the ${ddf-platform} Application.
Exporting configurations stored in `org.osgi.service.cm.ConfigurationAdmin` does not need to be handled by implementations of `org.codice.ddf.migration.Migratable` as all `ConfigurationAdmin` configurations are exported by `org.codice.ddf.configuration.admin.ConfigurationAdminMigratable`.
An export operation can be performed through the ${command-console} or through the ${admin-console}. When an export operation is processed, the migration API will do a look-up for all registered OSGi services that are implementing `Migratable` and call their `export()` method.

The services that implement one of the migratable interfaces will be called one at a time, in any order, and do not need to be thread safe.
A bundle or a feature can have as many services implementing the interfaces as needed.

==== The Migratable API Interfaces

. `org.codice.ddf.migration.Migratable`
. `org.codice.ddf.migration.AbstractMigratable`
. `org.codice.ddf.migration.MigrationException`
. `org.codice.ddf.migration.MigrationMetadata`
. `org.codice.ddf.migration.MigrationWarning`

===== `Migratable`

The contract for a `migratable` is stored here. It is used by both sub-interfaces `ConfigurationMigratable` and `DataMigratable`.

[WARNING]
====
Do not implement `Migratable` directly; it is intended for use only as a common base interface.
Instead, the appropriate sub-interface should be used.
====

The `org.codice.ddf.migration.Migratable` interface defines these methods:

.`MigrationMetadata export(Path exportPath) throws MigrationException`
.`String getDescription()`
.`boolean isOptional()`

The `exportPath` in `export(Path exportPath)` is the path where all of the exportable data is copied.
It is provided via an argument to the `migration:export` console command or via the Export Dialog in the ${admin-console}.
The default value is `<${branding}_HOME>/etc/exported`.
It is the responsibility of a `Migratable` to prevent naming collisions upon export.
For example, if a `Migratable` writes files for its export, it must namespace the files.
The `getDescription()` operation returns a short description of the type of data exported by the `Migratable`.
The `isOptional()` operation returns whether the exported data for the `Migratable` is optional or required.
The description and optional flag are for display purposes in the ${admin-console}.

In order to create a `Migratable` for a module of the system, the `org.codice.ddf.migration.Migratable` interface must be implemented and the implementation must be registered under the `org.codice.ddf.migration.Migratable` interface as an OSGI service in the OSGI service registry.
Creating an OSGI service allows for the `org.codice.ddf.configuration.migration.ConfigurationMigrationManager` to lookup all implementations of `org.codice.ddf.migration.Migratable` and command them to export.

====== `ConfigurationMigratable`

This is the base interface that must be implemented by all bundles or features that need to export and/or import system related settings
(e.g., bundle specific Java properties, XML or JSON configuration files) during system migration.
The information exported must allow the new system to have the same configuration as the original system.
Only bundle- or feature-specific settings need be handled. All configurations stored in OSGi's
`ConfigurationAdmin` will automatically be migrated and do not need to be managed by implementors of this class.

Also, any other data not related to the system's configuration and settings (for example, data stored in Solr) should be handled by a different
service that implements the `DataMigratable` interface, not by implementors of this class.

====== `DataMigratable`

This is the interface that must be implemented by all bundles or features that need to export and/or import data during system migration.
The data is not mandatory for the system to come up (e.g., data stored in Solr) and doesn't affect the system's configuration,
i.e., without this data, the new system will still have the same configuration as the original one.

Any system related configuration and settings should be handled by a different service that implements the
`ConfigurationMigratable` interface, not by implementors of this class.

===== `AbstractMigratable`

The abstract base class `org.codice.ddf.migration.AbstractMigratable` in the `platform-migratable-api` implements common boilerplate code required when implementing `org.codice.ddf.migration.Migratable` and should be extended when creating an `org.codice.ddf.migration.Migratable`.

===== `MigrationException`

An `org.codice.ddf.migration.MigrationException` should be thrown when an unrecoverable exception occurs that prevents required data from exporting.
The exception message is displayed to the administrator.

===== `MigrationMetadata`

The `org.codice.ddf.migration.MigrationMetadata` provides metadata with details of the exported `org.codice.ddf.migration.Migratable`.

===== `MigrationWarning`

An `org.codice.ddf.migration.MigrationWarning` should be used when a `Migratable` wants to warn an admin that certain aspects of the export may cause problems upon import.
For example, if an absolute path is encountered, that path may not exist on the target system and cause the installation to fail.
All migration warnings are displayed to the administrator.

.Do Not Use FileBackedOutputStream
[WARNING]
====
It is recommended to avoid using `com.google.common.io.FileBackedOutputStream` (FBOS).
FBOS can create temporary files that are not automatically removed when FBOS is closed.
Use `org.codice.ddf.platform.util.TemporaryFileBackedOutputStream` (TFBOS).
TFBOS provides the same method calls as FBOS, but will remove temporary files when it is closed.
====
