:title: Federated Identity
:type: securityFramework
:status: published
:parent: Security Framework
:order: 10
:summary: How a user's identity is shared with federated Sources during queries

== {title}

Each instance of {branding} may be configured with its own security policy that determines the
resources a user may access and the actions they may perform. To decide whether a given request is
permitted, {branding} references any attributes stored internally in the requestor's
<<_subject,Subject>>. Based on these
attributes and the configured policy, {branding} makes an authorization decision. See
<<_security_pdp, Security PDP>> for more information.

This authorization process works when the requestor authenticates directly with {branding} as they
are guaranteed to have a Subject. However, when federating, {branding} proxies requests to federated
Sources and this poses a problem. The requestor doesn't authenticate with federated Sources, but
Sources still need to make authorization decisions.

To solve this problem, {branding} will use its own identity (PKI or configured username/password per
source) or in the case of OAuth 2, ask the user
to allow the system to perform the request on their behalf. When performing any federated request
(query, resource retrival, etc), {branding} will attempt to authenticate with the remote endpoint.
The remote endpoint will validate the authentication information sent by the source.
If validated, the federated Endpoint will construct a Subject for the
requestor and perform the request using that Subject. The remote Endpoint can then make authorization
decisions using the process already described.

. A user submits a search to {branding}.
. {branding} generates a catalog request.
. If using OAuth 2, request permission from the user to perform the action.
. If not using OAuth 2, request uses PKI and/or configured username/password for the source.
. A remote Endpoint receives this request and authenticates according to its local Web Context Policy Configuration.
If the authentication is valid, the federated
Source generates a Subject to represent the system (or user in the cause of OAuth 2) who initiated the request.
. The remote system <<_filtering,filters>> all results that the user is not authorized to view
and returns the rest to {branding}.
. {branding} then takes the results from all Sources, filters those that the user is not authorized to
view according to its local policy and returns the remaining results to the user.

NOTE: Results are filtered both by the federated Source and client
{branding}. This is important as each may have different authorization policies.

WARNING: Support for filtering was added in DDF 2.8.x. Federated Sources older than this
will not perform any filtering. Instead, they will return all available results and leave filtering
up to the client.

