:title: Federated Identity
:type: securityFramework
:status: published
:parent: Security Framework
:order: 10
:summary: How a user's identity is shared with federated Sources during queries

== {title}

Each instance of {branding} may be configured with its own security policy that determines the
resources a user may access and the actions they may perform. To decide whether a given request is
permitted, {branding} references the SAML assertion stored internally in the requestor's
<<_subject,Subject>>. This assertion is generated by the <<_security_token_service, STS>> during
authentication and contains a collection of attributes that identify the requestor. Based on these
attributes and the configured policy, {branding} makes an authorization decision. See
<<_security_pdp, Security PDP>> for more information.

This authorization process works when the requestor authenticates directly with {branding} as they
are guaranteed to have a Subject. However, when federating, {branding} proxies requests to federated
Sources and this poses a problem. The requestor doesn't authenticate with federated Sources, but
Sources still need to make authorization decisions.

To solve this problem, {branding} uses federated identity. When performing any federated request
(query, resource retrival, etc), {branding} attaches the requestor's SAML assertion to the outgoing
request. The federated Source extracts the assertion and validates its signature to make sure it
was generated by a trusted entity. If so, the federated Source will construct a Subject for the
requestor and perform the request using that Subject. The Source can then make authorization
decisions using the process already described.

How {branding} attaches SAML assertions to federated requests depends on the endpoint used to
connect to a federated Source. When using a REST endpoint such as CSW, {branding} places the
assertion in the HTTP Authorization header. When using a SOAP endpoint, it places the assertion
in the SOAP security header.

The figure below shows a federated query between two instances of {branding} that support
federated identity.

[ditaa, federated_identity, png, ${image-width}]
....
                  /---------------------------\           /--------------------------\
                  | cDEF       DDF            |           |     Federated Source     |
/--------\        | +-----------------------+ |           | cDEF                     |
|  User  +------->| |    Send request to    | |           | +----------------------+ |
|  cDEF  | Search | |   Catalog Framework   | |  /------->| |   Recreate Subject   | |
\--------/        | +-----------------------+ |  | Query  | +----------------------+ |
     ^            |             |             |  |        |             |            |
     |            |             v             |  |        |             v            |
     |            | +-----------------------+ |  |        | +----------------------+ |
     |            | | Create HTTP request & | +--/        | | Run query as Subject | |
     |            | | attach SAML assertion | |           | +----------------------+ |
     |            | +-----------------------+ |           |             |            |
     |            |                           |           |             v            |
     |            | +-----------------------+ |           | +----------------------+ |
     \------------+ |     Filter results    | |<----------+ |    Filter results    | |
                  | +-----------------------+ |  Filtered | +----------------------+ |
                  \---------------------------/   results \--------------------------/
....

. A user submits a search to {branding}.
. {branding} generates a catalog request, attaches the user's Subject, and sends the request to the
Catalog Framework.
. The Catalog Framework extracts the SAML assertion from the Subject and sends an HTTP request
to each federated Source with the assertion attached.
. A federated Source receives this request and extracts the SAML assertion. The federated Source
then validates the authenticity of the SAML Assertion. If the assertion is valid, the federated
Source generates a Subject from the assertion to represent the user who initiated the request.
. The federated Source <<_filtering,filters>> all results that the user is not authorized to view
and returns the rest to {branding}.
. {branding} takes the results from all Sources, filters those that the user is not authorized to
view and returns the remaining results to the user.

NOTE: With federated identity, results are filtered both by the federated Source and client
{branding}. This is important as each may have different authorization policies.

WARNING: Support for federated identity was added in DDF 2.8.x. Federated Sources older than this
will not perform any filtering. Instead, they will return all available results and leave filtering
up to the client.

