:title: Guest Interceptor
:type: subSecurityFramework
:status: published
:parent: Security PDP
:order: 01
:summary: Guest Interceptor.

== {title}

The goal of the `GuestInterceptor` is to attach a guest subject to a SOAP endpoint that is not using security headers. 

All requests to secure SOAP endpoints must satisfy any WS-SecurityPolicy that is included in the WSDL. The endpoint should use the PEPAuthorizingInterceptor to create the subject to be used for the request.

=== Installing Guest Interceptor

The `GuestInterceptor` is installed by default with ${ddf-security} Application.

=== Configuring Guest Interceptor

Configure the Guest Interceptor from the ${admin-console}:

. Navigate to the *${admin-console}* at \${secure_url}/admin
. Select the *${ddf-security}* application.
. Select the *Configuration* tab.
. Select the *Guest Claims Configuration* configuration.
. Select the `+` next to Attributes to add a new attribute.
. Add any additional attributes that will apply to every user.
. Select *Save changes*.

Once these configurations have been added, the GuestInterceptor is ready for use.
