:title: Realms
:type: subSecurityFramework
:status: published
:parent: Subject
:order: 01
:summary: Shiro realms.

== {title}

${branding} uses https://shiro.org[Apache Shiro] {external-link} for the concept of https://shiro.apache.org/realm.html[Realms] {external-link} for Authentication and Authorization.
Realms are components that access security data such as such as users or permissions.

=== Authenticating Realms

`org.apache.shiro.realm.AuthenticatingRealm`

Authenticating Realms are used to authenticate an incoming Authentication Token and return https://shiro.apache.org/static/1.2.6/apidocs/org/apache/shiro/authc/AuthenticationInfo.html[Authentication Info] {external-link} on successful authentication.
This Authentication Info is used by the Shiro framework to put together a resulting Subject.
A Subject represents the application user and contains all available security-relevant information about that user.

.Implementations of Authenticating Realms in ${branding}:
[cols="1m,2" options="header"]
|===

|Classname
|Description

|org.codice.ddf.security.guest.realm.GuestRealm
|This realm checks if Guest access is allowed on the incoming Authentication Token, and if so the Guest realm returns the Guest Authentication Info.

|org.codice.ddf.security.oidc.realm.OidcRealm
|This realm takes in any OIDC/OAuth credentials found on the incoming Authentication Token, and if so resolves the ID_Token using those credentials. The ID_Token is then used to put together the resulting Authentication Info.

|ddf.security.realm.sts.StsRealm
|This realm delegates authentication to the Secure Token Service (STS). It creates a `RequestSecurityToken` message from the incoming Authentication Token and converts a successful STS response into Authentication Info.
|===

=== Authorizing Realms

`org.apache.shiro.realm.AuthorizingRealm`

Authorizing Realms are used to perform authorization on the current Subject.
These are used when performing both service authorization and filtering.
They are passed in the `AuthorizationInfo` of the Subject along with the permissions of the object wanting to be accessed. The response from these realms is a true (if the Subject has permission to access) or false (if the Subject does not).

.Other implementations of the Security API within ${branding}
[cols="1m,2" options="header"]
|===

|Classname
|Description

|org.codice.ddf.platform.filter.delegate.DelegateServletFilter
|The `DelegateServletFilter` detects any servlet filters that have been exposed as OSGi services implementing `org.codice.ddf.platform.filter.SecurityFilter` and places them in-order in front of any servlet or web application running on the container.

|org.codice.ddf.security.filter.websso.WebSSOFilter
|This filter is the main security filter that works with a number of handlers to protect a variety of web contexts, each using different authentication schemes and policies.
It attaches an Authentication Token to the request by either checking the session or calling the configured Security Handlers.

|org.codice.ddf.security.handler.basic.BasicAuthenticationHandler
|Checks for basic authentication credentials in the http request header.
If no credentials are found, it supports the acquisition of basic credentials on user-agent requests.

|org.codice.ddf.security.handler.pki.PKIHandler
|Handler for PKI based authentication.
X509 chain will be extracted from the HTTP request.

|org.codice.security.idp.client.IdpHandler
|Handler for IdP/SAML based authentication.
If no credentials are found, it supports the acquisition of credentials through the configured SAML IdP.

|org.codice.ddf.security.handler.oidc.OidcHandler
|Handler for OIDC based authentication.
If no credentials are found, and is a user-agent request, this handler supports the acquisition of credentials through the configured OIDC IdP.

|org.codice.ddf.security.handler.oauth.OAuthHandler
|Handler for OAuth based authentication.
Does not support the acquisition of credentials.

|org.codice.ddf.security.filter.login.LoginFilter
|This filter runs immediately after the WebSSOFilter and exchanges an Authentication Token found in the request with a Subject via Shiro.

|org.codice.ddf.security.filter.authorization.AuthorizationFilter
|This filter runs immediately after the `LoginFilter` and checks any permissions assigned to the web context against the attributes of the Subject via Shiro.

|org.apache.shiro.realm.AuthenticatingRealm
|This is an abstract authenticating realm that exchanges an `org.apache.shiro.authc.AuthenticationToken` for a `org.apache.shiro.authc.AuthenticationInfo`, which is used by the Shiro framework to put together a `ddf.security.Subject`.

|ddf.security.service.AbstractAuthorizingRealm
|This is an abstract authorizing realm that takes care of caching and parsing the Subject's `AuthorizingInfo` and should be extended to allow the implementing realm to focus on making the decision.

|ddf.security.pdp.realm.AuthZRealm
|This realm performs the authorization decision and may or may not delegate out to the external XACML processing engine. It uses the incoming permissions to create a decision.
However, it is possible to extend this realm using the ddf.security.policy.extension.PolicyExtension interface.
This interface allows an integrator to add additional policy information to the PDP that can't be covered via its generic matching policies.
This approach is often easier to configure for those that are not familiar with XACML.

|org.codice.ddf.security.validator.*
|A number of validators are provided for X.509 and Username tokens.

|===

[WARNING]
====
An update was made to the IdpHandler to pass SAML assertions through the Authorization HTTP header.
Cookies _are_ still accepted and processed to maintain legacy federation compatibility, but assertions are sent in the header on outbound requests.
While a machine's identity will still federate between versions, a user's identity will ONLY be federated when a ${branding} version 2.7.x server communicates with a ${branding} version 2.8.x+ server, or between two servers whose versions are 2.8.x or higher.
====
