:title: Realms
:type: subSecurityFramework
:status: published
:parent: Subject
:order: 01
:summary: Shiro realms.

== {title}

${branding} uses https://shiro.org[Apache Shiro] for the concept of https://shiro.apache.org/realm.html[Realms] for Authentication and Authorization.
Realms are components that access security data such as such as users or permissions.

=== Authenticating Realms

`org.apache.shiro.realm.AuthenticatingRealm`

Authenticating Realms are used to authenticate an incoming authentication token and create a https://shiro.apache.org/subject.html[Subject] on successful authentication.
A Subject is an application user and all available security-relevant information about that user.

.Implementations of Authenticating Realms in ${branding}:
[cols="1m,2" options="header"]
|===

|Classname
|Description

|ddf.security.realm.sts.StsRealm
|This realm delegates authentication to the Secure Token Service (STS). It creates a `RequestSecurityToken` message from the incoming Authentication Token and converts a successful STS response into a Subject.

|===

=== Authorizing Realms

`org.apache.shiro.realm.AuthorizingRealm`

Authorizing Realms are used to perform authorization on the current Subject.
These are used when performing both service authorization and filtering.
They are passed in the `AuthorizationInfo` of the Subject along with the permissions of the object wanting to be accessed. The response from these realms is a true (if the Subject has permission to access) or false (if the Subject does not).

.Other implementations of the Security API within ${branding}
[cols="1m,2" options="header"]
|===

|Classname
|Description

|org.codice.ddf.platform.filter.delegate.DelegateServletFilter
|The `DelegateServletFilter` detects any servlet filters that have been exposed as OSGi services implementing `org.codice.ddf.platform.filter.SecurityFilter` and places them in-order in front of any servlet or web application running on the container.

|org.codice.ddf.security.filter.websso.WebSSOFilter
|This filter is the main security filter that works with a number of handlers to protect a variety of web contexts, each using different authentication schemes and policies.

|org.codice.ddf.security.handler.saml.SAMLAssertionHandler
|This handler is executed by the WebSSOFilter for any contexts configured to use it.
This handler should always come first when configured in the Web Context Policy Manager, as it provides a caching capability to web contexts that use it.
The handler will first check for the existence of an HTTP Authorization header of type SAML, whose value is a Base64 + deflate SAML assertion.
If that is not found, then the handler will check for the existence of the deprecated `org.codice.websso.saml.token` cookie with the same value.
Failing that, it will check for a JSESSIONID cookie to use as a reference to a cached assertion.
If the JSESSIONID is valid, the `SecurityToken` will be retrieved from the cache.

|org.codice.ddf.security.handler.basic.BasicAuthenticationHandler
|Checks for basic authentication credentials in the http request header.
If they exist, they are retrieved and passed to the `LoginFilter` for exchange.

|org.codice.ddf.security.handler.pki.PKIHandler
|Handler for PKI based authentication.
X509 chain will be extracted from the HTTP request and converted to a `BinarySecurityToken`.

|org.codice.ddf.security.handler.guest.GuestHandler
|Handler that allows guest user access via a guest user account.
The guest account credentials are configured via the org.codice.ddf.security.claims.guest.GuestClaimsHandler.
The `GuestHandler` also checks for the existence of basic auth credentials or PKI credentials that might be able to override the use of the guest user.

|org.codice.ddf.security.filter.login.LoginFilter
|This filter runs immediately after the WebSSOFilter and exchanges any authentication information found in the request with a Subject via Shiro.

|org.codice.ddf.security.filter.authorization.AuthorizationFilter
|This filter runs immediately after the `LoginFilter` and checks any permissions assigned to the web context against the attributes of the user via Shiro.

|org.apache.shiro.realm.AuthenticatingRealm
|This is an abstract authenticating realm that exchanges an `org.apache.shiro.authc.AuthenticationToken` for a `ddf.security.Subject` in the form of an `org.apache.shiro.authc.AuthenticationInfo`

|ddf.security.realm.sts.StsRealm
|This realm is an implementation of `org.apache.shiro.realm.AuthenticatingRealm` and connects to an STS (configurable) to exchange the authentication token for a Subject.

|ddf.security.service.AbstractAuthorizingRealm
|This is an abstract authorizing realm that takes care of caching and parsing the Subject's `AuthorizingInfo` and should be extended to allow the implementing realm to focus on making the decision.

|ddf.security.pdp.realm.AuthZRealm
|This realm performs the authorization decision and may or may not delegate out to the external XACML processing engine. It uses the incoming permissions to create a decision.
However, it is possible to extend this realm using the ddf.security.policy.extension.PolicyExtension interface.
This interface allows an integrator to add additional policy information to the PDP that can't be covered via its generic matching policies.
This approach is often easier to configure for those that are not familiar with XACML.

|org.codice.ddf.security.validator.*
|A number of STS validators are provided for X.509 (BinarySecurityToken), UsernameToken, SAML Assertion, and ${branding} custom tokens.
The ${branding} custom tokens are all `BinarySecurityTokens` that may have PKI or username/password information as well as an authentication realm (correlates to JAAS realms installed in the container).
The authentication realm allows an administrator to restrict which services they wish to use to authenticate users.
For example: installing the `security-sts-ldaplogin` feature will enable a JAAS realm with the name "ldap".
This realm can then be specified on any context using the Web Context Policy Manager.
That realm selection is then passed via the token sent to the STS to determine which validator to use.

|===

[NOTE]
====
Using the SAML Web SSO Identity Provider for authentication will ignore any realm settings and simply use all configured JAAS realms.
====

[WARNING]
====
An update was made to the SAML Assertion Handler to pass SAML assertions through the Authorization HTTP header.
Cookies _are_ still accepted and processed to maintain legacy federation compatibility, but assertions are sent in the header on outbound requests.
While a machine's identity will still federate between versions, a user's identity will ONLY be federated when a ${branding} version 2.7.x server communicates with a ${branding} version 2.8.x+ server, or between two servers whose versions are 2.8.x or higher.
====
