:title: Claims Handlers
:type: subSecurityFramework
:status: published
:parent: Realms
:children: Security LDAP Claims Handler
:order: 00
:summary: Claims Handlers.

== {title}

Claims handlers are classes that retrieve a set of attribute claims that will be populated in the user Subject object.
Most Realms also call out to the installed claims handler to retrieve claims information from some source.
The notable exceptions to this, would be the SamlRealm and OidcRealm, as it is expected the Identity Provider would supply all the necessary claims.
In this scenario, ${branding} acts only as a client to the system providing SSO capability and is not directly involved in building the user's identity.

An example claims handler would be the LdapClaimsHandler that takes in the user's credentials and retrieves the user's attributes from a back-end LDAP server.
These attributes are then mapped and added to the Subject being created.
Integrators and developers can add more claims handlers that can handle other types of external services that store user attributes.
