:title: Security Encryption Commands
:type: subSecurityFramework
:status: published
:parent: Security Encryption
:order: 02
:summary: Security Encryption commands.

== {title}

The Security Encryption Commands bundle enhances the ${branding} system console by allowing administrators and integrators to encrypt and decrypt values directly from the console.

The `security:encrypt` command allows plain text to be encrypted using AES for encryption.
It uses randomly generated keys and associated data that are created when the system is installed, and can be found in the `${home_directory}/etc/keysets` directory.
This is useful when displaying password fields in a GUI.

Below is an example of the security:encrypt command used to encrypt the plain text "myPasswordToEncrypt".
The output, `bR9mJpDVo8bTRwqGwIFxHJ5yFJzatKwjXjIo/8USWm8=`, is the encrypted value.

[source%nowrap.java]
----
${ddf-branding-lowercase}@local>security:encrypt myPasswordToEncrypt

bR9mJpDVo8bTRwqGwIFxHJ5yFJzatKwjXjIo/8USWm8=
----

=== Installing the Security Encryption Commands

This bundle is installed by default with the `security-encryption` feature.
This bundle is tied specifically to the ${branding} console and can be uninstalled if not needed.
When uninstalled, however, administrators will not be able to encrypt and decrypt data from the console.

=== Configuring the Security Encryption Commands

The Security Encryption Commands have no configurable properties.
