:title: Securing SOAP
:type: subSecurityFramework
:status: published
:parent: Web Service Security Architecture
:order: 01
:summary: Securing SOAP.

== {title}

[ditaa,soap_security_flow,png]
....
+--------------------------------------------------------------------------------------------+
|                                                                                            |
| /--------\              /-------------\                                                    |
| |        |   get WSDL   |             |                                                    |
| | Secure |------------->|             |                                                    |
| |  SOAP  |              |    SOAP     |                                                    |
| | Client |              |  Endpoint   |<-------\                                           |
| |        |     WSDL     |             |        |                                           |
| |        |<-------------|        c5F5 |        |                                           |
| |        |              |             |        |                                           |
| |        |              \-------------/        |                                           |
| |        |                                     |                                           |
| |        |              /-------------\        |                                           |
| |        |  get token   |             |        |                                           |
| |        |------------->|             |<-------|-------\                                   |
| |        |              |    STS      |        |       |                                   |
| |        |              |   Server    |        |   /-------\                               |
| |        |     token    |             |        |   |       |                               |
| |        |<-------------|        cDEF |        |   |  STS  |                               |
| |        |              |             |        |   | Realm |                               |
| |        |              \-------------/        |   |       |                               |
| |        |                                     |   \-----=-/                               |
| |        |              /-------------\        |       ^                                   |
| |        | secure call  |             |--------/       |                                   |
| |        |------------->|             |Authorized? /-------\       /-------------\         |
| |        |              |   Policy    |----------->|--=--->|------>|             |         |
| |        |              | Enforcement | Decision   |       |       |    PDP      |         |
| |        |   results    |   Point     |<-----------|<--=---|<------|             |         |
| | cDEF   |<-------------|        cDEF |            |       |       |             |         |
| |        |              |             |<-------\   |       |       |             |         |
| \--------/              \-------------/        |   |       |       |    cDEF     |         |
|                                                |   |       |       \-------------/         |
| /--------\              /-------------\        |   |       |           ^    |              |
| |        |              |             |        |   |       |           |    |              |
| |  Dumb  |              |  Anonymous  |        |   |  c444 |           |    v              |
| |  SOAP  |              | Interceptor |        |   | Shiro |       /----------=--\         |
| | Client |call endpoint | /---------\ |        |   |       |       |             |         |
| |        |------------->| |  Read   | |        |   |       |       | Expansion   |         |
| | cDEF   |              | | Policy  | |        |   |       |       | Service     |         |
| |        |              | \---------/ |        |   |       |       |             |         |
| \--------/              |      |      |        |   |       |       |             |         |
|                         |      v      |        |   |       |       |             |         |
|                         | /---------\ |        |   |       |       \-------------/         |
|                         | |  Build  | |        |   |       |                               |
|                         | |Security | |        |   |       |                               |
|                         | | Headers | |        |   |       |                               |
|                         | \---------/ |        |   |       |                               |
|                         |      |      |        |   |       |                               |
|                         |      v      |        |   |       |                               |
|                         | /---------\ |        |   |       |                               |
|                         | |   Get   | |        |   |       |                               |
|                         | |Anon SAML| |        |   |       |                               |
|                         | \---------/ |--------/   |       |                               |
|                         |      | cDEF |            |       |                               |
|                         |      v      |            |       |                               |
|                         \-------------/            |       |                               |
|                            ^   |    Anon Token     |       |                               |
|                            |   \------------------>|       |                               |
|                            |         Subject       |       |                               |
|                            \-----------------------|       |                               |
|                                                    \-------/                               |
|                                                                                            |
+--------------------------------------------------------------------------------------------+
....

=== SOAP Secure Client

When calling to an endpoint from a SOAP secure client, it first requests the WSDL from the endpoint and the SOAP endpoint returns the WSDL.
The client then calls to STS for authentication token to proceed.
If the client receives the token, it makes a secure call to the endpoint and receives results.

=== Policy-unaware SOAP Client

If calling an endpoint from a non-secure client, at the point the of the initial call, the Guest Interceptor catches the request and prepares it to be accepted by the endpoint.

First, the interceptor reads the configured policy, builds a security header, and gets an anonymous SAML assertion.
Using this, it makes a `getSubject` call which is sent through Shiro to the STS realm.
Upon success, the STS realm returns the subject and the call is made to the endpoint.

