:title: Embedded LDAP Server
:type: subSecurityFramework
:status: published
:parent: Security LDAP
:order: 00
:summary: Embedded LDAP server.

== {title}

${branding} includes an embedded LDAP server (OpenDJ) for testing and demonstration purposes.

[WARNING]
====
The embedded LDAP server is intended for testing purposes only and is not recommended for production use.
====

=== Installing the Embedded LDAP Server

The embedded LDAP server is not installed by default with a standard installation.

. Navigate to the *${admin-console}*.
. Select the *System* tab.
. Select the *Features* tab.
. Install the `opendj-embedded` feature.

=== Configuring the Embedded LDAP

Configure the Embedded LDAP from the ${admin-console}:

. Navigate to the *${admin-console}*.
. Select the *OpenDj Embedded* application.
. Select the *Configuration* tab.

.OpenDJ Embedded Configurable Properties
[cols="1,7" options="header"]
|===

|Configuration Name
|Description

|LDAP Port
|Sets the port for LDAP (plaintext and startTLS). 0 will disable the port.

|LDAPS Port
|Sets the port for LDAPS. 0 will disable the port.

|Base LDIF File
|Location on the server for a LDIF file.
This file will be loaded into the LDAP and overwrite any existing entries.
This option should be used when updating the default groups/users with a new LDIF file for testing.
The LDIF file being loaded may contain any LDAP entries (schemas, users, groups, etc.).
If the location is left blank, the default base LDIF file will be used that comes with ${branding}.

|===

=== Connecting to Standalone LDAP Servers

${branding} instances can connect to external LDAP servers by installing and configuring the `security-sts-ldaplogin` and `security-sts-ldapclaimshandler` features detailed here.

In order to connect to more than one LDAP server, configure these features for each LDAP server.

=== Embedded LDAP Configuration

The Embedded LDAP application contains an LDAP server (OpenDJ version 2.6.2) that has a default set of schemas and users loaded to help facilitate authentication and authorization testing.


.Embedded LDAP Default Ports Settings
[cols="2" options="header"]
|===

|Protocol
|Default Port

|`LDAP`
|1389

|`LDAPS`
|1636

|`StartTLS`
|1389

|===

.Embedded LDAP Default Users
[cols="1,1,1,3" options="header"]
|===

|Username
|Password
|Groups
|Description

|`testuser1`
|`password1`
|
|General test user for authentication

|`testuser2`
|`password2`
| 
|General test user for authentication

|`nromanova`
|`password1`
|`avengers`
|General test user for authentication

|`lcage`
|`password1`
|`admin`, `avengers`
|General test user for authentication, Admin user for karaf

|`jhowlett`
|`password1`
|`admin`, `avengers`
|General test user for authentication, Admin user for karaf

|`pparker`
|`password1`
|`admin`, `avengers`
|General test user for authentication, Admin user for karaf

|`jdrew`
|`password1`
|`admin`, `avengers`
|General test user for authentication, Admin user for karaf

|`tstark`
|`password1`
|`admin`, `avengers`
|General test user for authentication, Admin user for karaf

|`bbanner`
|`password1`
|`admin`, `avengers`
|General test user for authentication, Admin user for karaf

|`srogers`
|`password1`
|`admin`, `avengers`
|General test user for authentication, Admin user for karaf

|`admin`
|`admin`
|`admin`
|Admin user for karaf

|===

.Embedded LDAP Default Admin User Settings
[cols="5" options="header"]
|===
|Username
|Password
|Groups
|Attributes
|Description

|`admin`
|`secret`
|
|
|Administrative User for LDAP

|===

=== Schemas

The default schemas loaded into the LDAP instance are the same defaults that come with OpenDJ.

.Embedded LDAP Default Schemas
[cols="1,7" options="header"]
|===

|Schema File Name
| https://backstage.forgerock.com/docs/opendj/2.6/admin-guide/#chap-schema[Schema Description] {external-link}

|`00-core.ldif`
|This file contains a core set of attribute type and objectlass definitions from several standard LDAP documents, including `draft-ietf-boreham-numsubordinates`, `draft-findlay-ldap-groupofentries`, `draft-furuseth-ldap-untypedobject`, `draft-good-ldap-changelog`, `draft-ietf-ldup-subentry`, `draft-wahl-ldap-adminaddr`, RFC 1274, RFC 2079, RFC 2256, RFC 2798, RFC 3045, RFC 3296, RFC 3671, RFC 3672, RFC 4512, RFC 4519, RFC 4523, RFC 4524, RFC 4530, RFC 5020, and X.501.

|`01-pwpolicy.ldif`
|This file contains schema definitions from `draft-behera-ldap-password-policy`, which defines a mechanism for storing password policy information in an LDAP directory server.

|`02-config.ldif`
|This file contains the attribute type and `objectclass` definitions for use with the directory server configuration.

|`03-changelog.ldif`
|This file contains schema definitions from `draft-good-ldap-changelog`, which defines a mechanism for storing information about changes to directory server data.

|`03-rfc2713.ldif`
|This file contains schema definitions from RFC 2713, which defines a mechanism for storing serialized Java objects in the directory server.

|`03-rfc2714.ldif`
|This file contains schema definitions from RFC 2714, which defines a mechanism for storing CORBA objects in the directory server.

|`03-rfc2739.ldif`
|This file contains schema definitions from RFC 2739, which defines a mechanism for storing calendar and vCard objects in the directory server. Note that the definition in RFC 2739 contains a number of errors, and this schema file has been altered from the standard definition in order to fix a number of those problems.

|`03-rfc2926.ldif`
|This file contains schema definitions from RFC 2926, which defines a mechanism for mapping between Service Location Protocol (SLP) advertisements and LDAP.

|`03-rfc3112.ldif`
|This file contains schema definitions from RFC 3112, which defines the authentication password schema.

|`03-rfc3712.ldif`
|This file contains schema definitions from RFC 3712, which defines a mechanism for storing printer information in the directory server.

|`03-uddiv3.ldif`
|This file contains schema definitions from RFC 4403, which defines a mechanism for storing UDDIv3 information in the directory server.

|`04-rfc2307bis.ldif`
|This file contains schema definitions from the `draft-howard-rfc2307bis` specification, used to store naming service information in the directory server.

|`05-rfc4876.ldif`
|This file contains schema definitions from RFC 4876, which defines a schema for storing Directory User Agent (DUA) profiles and preferences in the directory server.

|`05-samba.ldif`
|This file contains schema definitions required when storing Samba user accounts in the directory server.

|`05-solaris.ldif`
|This file contains schema definitions required for Solaris and OpenSolaris LDAP naming services.

|`06-compat.ldif`
|This file contains the attribute type and `objectclass` definitions for use with the directory server configuration.

|===

=== Starting and Stopping the Embedded LDAP

The embedded LDAP application installs a feature with the name `ldap-embedded`.
Installing and uninstalling this feature will start and stop the embedded LDAP server.
This will also install a fresh instance of the server each time.
If changes need to persist, stop then start the `embedded-ldap-opendj` bundle (rather than installing/uninstalling the feature).

All settings, configurations, and changes made to the embedded LDAP instances are persisted across ${branding} restarts.
If ${branding} is stopped while the LDAP feature is installed and started, it will automatically restart with the saved settings on the next ${branding} start.

=== Limitations of the Embedded LDAP

Current limitations for the embedded LDAP instances include:

* Inability to store the LDAP files/storage outside of the ${branding} installation directory. This results in any LDAP data (i.e., LDAP user information) being lost when the `ldap-embedded` feature is uninstalled.
* Cannot be run standalone from ${branding}. In order to run `embedded-ldap`, the ${branding} must be started.

=== External Links for the Embedded LDAP

Location to the default base LDIF file in the ${branding} https://github.com/codice/opendj-osgi/blob/master/embedded/opendj-embedded-server/src/main/resources/default-users.ldif[source code] {external-link}.

https://backstage.forgerock.com/docs/opendj/2.6[OpenDJ documentation] {external-link}

=== LDAP Administration

OpenDJ provides a number of tools for LDAP administration. Refer to the https://backstage.forgerock.com/docs/opendj/2.6/admin-guide/[OpenDJ Admin Guide] {external-link}.

=== Downloading the Admin Tools

Download https://backstage.forgerock.com/downloads/OpenDJ/OpenDJ%20Enterprise/2.6.4#browse[OpenDJ (Version 2.6.4)] {external-link} and the included tool suite.

=== Using the Admin Tools

The admin tools are located in `<opendj-installation>/bat` for Windows and `<opendj-installation>/bin` for `*nix`. 
These tools can be used to administer both local and remote LDAP servers by setting the *host* and *port* parameters appropriately.


In this example, the user *Bruce Banner (uid=bbanner)* is disabled using the *manage-account* command on Windows.
Run *manage-account --help* for usage instructions.

.Example Commands for Disabling/Enabling a User's Account
----
D:\OpenDJ-2.4.6\bat>manage-account set-account-is-disabled -h localhost -p 4444 -O true
-D "cn=admin" -w secret -b "uid=bbanner,ou=users,dc=example,dc=com"
The server is using the following certificate:
    Subject DN:  CN=Win7-1, O=Administration Connector Self-Signed Certificate
    Issuer DN:  CN=Win7-1, O=Administration Connector Self-Signed Certificate
    Validity:  Wed Sep 04 15:36:46 MST 2013 through Fri Sep 04 15:36:46 MST 2015
Do you wish to trust this certificate and continue connecting to the server?
Please enter "yes" or "no":yes
Account Is Disabled:  true
----


Notice `Account Is Disabled: true` in the listing:

.Verifying an Account is Disabled
----
D:\OpenDJ-2.4.6\bat>manage-account get-all -h localhost -p 4444  -D "cn=admin" -w secret
-b "uid=bbanner,ou=users,dc=example,dc=com"
The server is using the following certificate:
    Subject DN:  CN=Win7-1, O=Administration Connector Self-Signed Certificate
    Issuer DN:  CN=Win7-1, O=Administration Connector Self-Signed Certificate
    Validity:  Wed Sep 04 15:36:46 MST 2013 through Fri Sep 04 15:36:46 MST 2015
Do you wish to trust this certificate and continue connecting to the server?
Please enter "yes" or "no":yes
Password Policy DN:  cn=Default Password Policy,cn=Password Policies,cn=config
Account Is Disabled:  true
Account Expiration Time:
Seconds Until Account Expiration:
Password Changed Time:  19700101000000.000Z
Password Expiration Warned Time:
Seconds Until Password Expiration:
Seconds Until Password Expiration Warning:
Authentication Failure Times:
Seconds Until Authentication Failure Unlock:
Remaining Authentication Failure Count:
Last Login Time:
Seconds Until Idle Account Lockout:
Password Is Reset:  false
Seconds Until Password Reset Lockout:
Grace Login Use Times:
Remaining Grace Login Count:  0
Password Changed by Required Time:
Seconds Until Required Change Time:
Password History:
----

.Enabling an Account
----
D:\OpenDJ-2.4.6\bat>manage-account clear-account-is-disabled  -h localhost -p 4444  -D
"cn=admin" -w secret -b "uid=bbanner,ou=users,dc=example,dc=com"
The server is using the following certificate:
    Subject DN:  CN=Win7-1, O=Administration Connector Self-Signed Certificate
    Issuer DN:  CN=Win7-1, O=Administration Connector Self-Signed Certificate
    Validity:  Wed Sep 04 15:36:46 MST 2013 through Fri Sep 04 15:36:46 MST 2015
Do you wish to trust this certificate and continue connecting to the server?
Please enter "yes" or "no":yes
Account Is Disabled:  false
----


Notice `Account Is Disabled: false` in the listing.

.Verifying an Account is Enabled
----
D:\OpenDJ-2.4.6\bat>manage-account get-all -h localhost -p 4444  -D "cn=admin" -w secret
-b "uid=bbanner,ou=users,dc=example,dc=com"
The server is using the following certificate:
    Subject DN:  CN=Win7-1, O=Administration Connector Self-Signed Certificate
    Issuer DN:  CN=Win7-1, O=Administration Connector Self-Signed Certificate
    Validity:  Wed Sep 04 15:36:46 MST 2013 through Fri Sep 04 15:36:46 MST 2015
Do you wish to trust this certificate and continue connecting to the server?
Please enter "yes" or "no":yes
Password Policy DN:  cn=Default Password Policy,cn=Password Policies,cn=config
Account Is Disabled:  false
Account Expiration Time:
Seconds Until Account Expiration:
Password Changed Time:  19700101000000.000Z
Password Expiration Warned Time:
Seconds Until Password Expiration:
Seconds Until Password Expiration Warning:
Authentication Failure Times:
Seconds Until Authentication Failure Unlock:
Remaining Authentication Failure Count:
Last Login Time:
Seconds Until Idle Account Lockout:
Password Is Reset:  false
Seconds Until Password Reset Lockout:
Grace Login Use Times:
Remaining Grace Login Count:  0
Password Changed by Required Time:
Seconds Until Required Change Time:
Password History:
----
