:title: PPTX Input Transformer
:type: transformer
:subtype: input
:status: published
:link: _pptx_input_transformer
:summary: Translates Microsoft PowerPoint (OOXML only) documents into Catalog Metacards.

The PPTX Input Transformer translates Microsoft PowerPoint (OOXML only) documents into Catalog Metacards, using https://tika.apache.org/[Apache Tika] for basic metadata and https://poi.apache.org/[Apache POI] for thumbnail creation.
The PPTX Input Transformer ingests PPTX documents into the ${branding} Content Repository and the Metadata Catalog, and adds a thumbnail of the first page in the PPTX document.

The PPTX Input Transformer will take precedence over the Tika Input Transformer for PPTX documents.

===== Installing the PPTX Input Transformer

This transformer is installed by default with a standard installation in the ${ddf-catalog} application.

===== Configuring the PPTX Input Transformer

To configure the PPTX Input Transformer:

. Navigate to the *${ddf-catalog}* application.
. Select the *Configuration* tab.
. Select the *PPTX Input Transformer*.

These configurations are available for the PDF Input Transformer:

include::{adoc-include}/_tables/ddf.catalog.transformer.input.pptx.PptxInputTransformer-table-contents.adoc[]

'''
