:title: Application Service API
:type: architectureIntro
:status: published
:children:
:order: 08
:summary: Introduction to the Application Service API.

The Application service has multiple interfaces which are exposed on top of the OSGi runtime for other applications to use.
For more information on these interfaces, see <<_application_service_api,Application Service Interfaces>>.

=== JMX Managed Bean

Some of the Application service API is exposed via JMX.
It can either be accessed using the JMX API or from a REST-based interface created by http://jolokia.org[Jolokia] that comes with ${branding}.
Here are the interfaces that are exposed in the Managed Bean:

getApplicationTree:: Creates an application hierarchy tree that shows relationships between applications.
startApplication:: Starts an application with the given name.
stopApplication:: Stops an application with the given name.
addApplications:: Adds a list of applications that are specified by their URL.

=== Initial Application Installation

In ${branding}, an *application* is a collection of one or more *features*.

[WARNING]
====
This application list configuration file is only read the first time the server is started after being unzipped.
====

To minimize the chance of accidentally installing and uninstalling applications, the configuration file for installing the initial applications is only read the first time that ${branding} is started.
The only way to change what applications are active on startup is to use the console commands.
Operations can also be done with the ${admin-console} that comes with ${branding} using the *Features* tab and installing the main feature for the desired application.

The application list file is located at `<${branding}_HOME>/etc/org.codice.ddf.admin.applicationlist.properties`

Applications should be defined in a `<name>=<location>` syntax where location may be empty for applications that have already been added to ${branding} or were prepackaged with the distribution.

.Examples:
[source]
----
# Local application:
opendj-embedded

# Application installed into a local maven repository:
opendj-embedded=mvn:org.codice.opendj.embedded/opendj-embedded-app/1.0.1-SNAPSHOT/xml/features

# Application located on the file system:
opendj-embedded=file:/location/to/opendj-embedded-app-1.0.1-SNAPSHOT.kar
----

Applications will be started in the order they are listed in the file.
If an application is listed, ${branding} will also attempt to install all dependencies for that application.

=== Application Service Interfaces

The interfaces used by that application service subsystem are `ApplicationService`, `Application`, `ApplicationStatus`, and `ApplicationNode`.
The purpose of these interfaces and their public methods are explained below.

==== ApplicationService Interface

The ApplicationService interface is the main class that is used to operate on applications.

`getApplications()`:: Returns a set of all applications that are installed on the system. Callers can then use the Application handle to get the name and any underlying features and bundles that this application contains.
`getApplication(String applicationName)`:: Returns the application that has the given name.
`startApplication(Application application)`:: Starts an application, including any defined dependencies in the application.
`stopApplication(Application application)`:: Stops an application, does not include any external transitive dependencies as they may be needed by other applications.
`addApplication(URI applicationURL)`:: Adds a new application to the application list. *NOTE: This does NOT start the application.*
`removeApplication(URI applicationURL)`:: Removes an application that has the given URI.
`isApplicationStarted(Application application)`:: Returns a boolean value relating whether a given application is started or not. This method is generally called after retrieving a list of applications in the first method.
`getApplicationStatus(Application application)`:: Returns the full status of an application. This status contains detailed information about the health of the application and is described in the `ApplicationStatus` interface section.
`getApplicationTree()`:: Creates a hierarchy tree of application nodes that show the relationship between applications.
`findFeature(Feature feature)`:: Determine which application contains a certain feature.

==== Application Interface

`getName()`:: Returns the name of the application, which should be unique among applications.
`getFeatures()`:: Returns all of the features that this application contains regardless if they are required.
`getBundles()`:: Returns all of the bundles that are defined by the features and included in this application.

==== ApplicationStatus Interface

`getApplication`:: Returns the application that is associated with this status.
`getState`:: Returns the application's state as defined by ApplicationState.
`getErrorFeatures`:: Returns a set of Features that were required for this application but did not start correctly.
`getErrorBundles`:: Returns a set of Bundles that were required for this application but did not start correctly.

==== ApplicationNode Interface

`getApplication()`:: Returns the application for a node reference.
`getStatus()`:: Returns the status for the referenced application.
`getParent()`:: Returns the parent of the application.
`getChildren()`:: Returns the children of this application. That is, the applications that depend on this application.
