:title: Configuring Schematron Services
:type: dataManagement
:status: published
:parent: Validating Data
:order: 01
:summary: Adding Schematron Validation Services.

== {title}

${branding} uses https://github.com/schematron[Schematron Validation] {external-link} to validate metadata ingested into the catalog.

Custom schematron rulesets can be used to validate metacard metadata.
Multiple services can be created, and each service can have multiple rulesets associated with it.
Namespaces are used to distinguish services.
The root schematron files may be placed anywhere on the file system as long as they are configured with an absolute path.
Any root schematron files with a relative path are assumed to be relative to `${home_directory}/schematron`.

[TIP]
====
Schematron files may reference other schematron files using an include statement with a relative path.
However, when using the document function within a schematron ruleset to reference another file, the path must be absolute or relative to the ${branding} installation home directory.
====

Schematron validation services are configured with a namespace and one or more schematron rulesets.
Additionally, warnings may be suppressed so that only errors are reported.

To create a new service:

* Navigate to the *${admin-console}*.
* Select the *${ddf-catalog}*.
* Select *Configuration*.
* Ensure that `catalog-schematron-plugin` is started.
* Select *Schematron Validation Services*.
