:title: FTP Endpoint
:type: endpoint
:status: published
:link: _ftp_endpoint
:summary: Ingests files directly into the ${branding} Catalog using the FTP protocol.
:implements: https://tools.ietf.org/html/rfc959[FTP] {external-link}

The FTP Endpoint provides a method for ingesting files directly into the ${branding} Catalog using the FTP protocol.
The files sent over FTP are not first written to the file system, like the Directory Monitor, but instead the FTP stream of the file is ingested directly into the ${branding} catalog, thus avoiding extra I/O overhead.

===== Installing the FTP Endpoint

The FTP Endpoint is not installed by default with a standard installation.

To install:

. Navigate to the *${admin-console}*.
. Select the *System* tab.
. Select the *Features* tab.
. Install the *catalog-core-ftp* feature.

===== Configuring the FTP Endpoint

Once installed, the configurable properties for the FTP Endpoint are accessed from the *FTP Endpoint* Configuration:

. Navigate to the *${admin-console}*.
. Select the *${ddf-catalog}* application.
. Select the *FTP Enpoint*.

See <<{reference-prefix}ddf.catalog.ftp.FtpServerManager,FTP Endpoint configurations>> for all possible configurations.

===== Using FTP Endpoint

.FTP Endpoint URL
----
ftp://<FQDN>:8021/
----

The FTP endpoint supports the `PUT`, `MPUT DELE`, `RETR`, `RMD`, `APPE`, `RNTO`, `STOU`, and `SITE` operations.

The FTP endpoint supports files being uploaded as a dot-file (e.g., `.foo`) and then being renamed to the final filename (e.g., `some-file.pdf`). The endpoint will complete the ingest process when the rename command is sent.

====== From Code:

Custom Ftplets can be implemented by extending the `DefaultFtplet` class provided by Apache FTP Server. Doing this will allow custom handling of various FTP commands by overriding the methods of the `DefaultFtplet`. Refer to `https://mina.apache.org/ftpserver-project/ftplet.html` for available methods that can be overridden.
After creating a custom Ftplet, it needs to be added to the FTP server’s Ftplets before the server is started. Any Ftplets that are registered to the FTP server will execute the FTP command in the order that they were registered.

====== From an FTP client:

The FTP endpoint can be accessed from any FTP client of choice. Some common clients are FileZilla, PuTTY, or the FTP client provided in the terminal. The default port number is *8021*. If FTPS is enabled with 2-way TLS, a client that supports client authentication is required.
