:title: KML Endpoint
:type: endpoint
:status: published
:link: _kml_endpoint
:summary: Generates a view-based KML Query Results Network Link.
:implements: https://developers.google.com/kml/documentation/kmlreference[Keyhole Markup Language] {external-link}

Keyhole Markup Language (_KML_) is an XML notation for describing geographic annotation and visualization for 2- and 3- dimensional maps.

The KML Network Link endpoint allows a user to generate a view-based KML Query Results Network Link. This network link can be opened with Google Earth, establishing a dynamic connection between Google Earth and ${branding}.
The root network link will create a network link for each configured source, including the local catalog.
The individual source network links will perform a query against the OpenSearch Endpoint periodically based on the current view in the KML client.
The query parameters for this query are obtained by a bounding box generated by Google Earth.
The root network link will refresh every 12 hours or can be forced to refresh.
As a user changes their current view, the query will be re-executed with the bounding box of the new view.
(This query gets re-executed two seconds after the user stops moving the view.)

===== Installing the KML Endpoint

The KML Network Link Endpoint is installed by default with a standard installation as part of the ${ddf-spatial} application.

===== Configuring the KML Endpoint

This KML Network Link endpoint has the ability to serve up custom KML style documents and Icons to be used within that document.
The KML style document must be a valid XML document containing a KML style.
The KML Icons should be placed in a single level directory and must be an image type (png, jpg, tif, etc.).
The Description will be displayed as a pop-up from the root network link on Google Earth.
This may contain the general purpose of the network and URLs to external resources.￼￼￼

See <<{reference-prefix}org.codice.ddf.spatial.kml.endpoint.KmlEndpoint,KML Endpoint configurations>> for all possible configurations.

===== Using the KML Endpoint

Once installed, the KML Network Link endpoint can be accessed at:
----
${secure_url}/services/catalog/kml
----

After the above request is sent, a KML Network Link document is returned as a response to download or open.
This KML Network Link can then be opened in Google Earth.

.Example Output from KML Endpoint
[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<kml xmlns="http://www.opengis.net/kml/2.2" xmlns:ns2="http://www.google.com/kml/ext/2.2"
  xmlns:ns3="http://www.w3.org/2005/Atom" xmlns:ns4="urn:oasis:names:tc:ciq:xsdschema:xAL:2.0">
  <NetworkLink>
    <name>${branding}</name>
    <open xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:type="xs:boolean">true</open>
    <Snippet maxLines="0"/>
    <Link>
      <href>http://0.0.0.0:8181/services/catalog/kml/sources</href>
      <refreshMode>onInterval</refreshMode>
      <refreshInterval>43200.0</refreshInterval>
      <viewRefreshMode>never</viewRefreshMode>
      <viewRefreshTime>0.0</viewRefreshTime>
      <viewBoundScale>0.0</viewBoundScale>
    </Link>
  </NetworkLink>
</kml>
----



The KML endpoint can also serve up Icons to be used in conjunction with the KML style document.
The request below shows the format to return an icon.

[NOTE]
====
`<icon-name>` must be the name of an icon contained in the directory being served.
====

.Return KML Icon
----
${secure_url}/services/catalog/kml/icons?<icon-name>
----
