:title: Metrics Endpoint
:type: endpoint
:status: published
:link: _metrics_endpoint
:summary: Reports on system metrics.
:implements:

[NOTE]
====
EXPERIMENTAL
====

[WARNING]
====
Note that the Metrics endpoint URL is marked "internal."
This indicates that this endpoint is intended for internal use by the ${branding} code.
This endpoint is subject to change in future versions.
====

The Metrics Endpoint is used by the <<{reference-prefix}metrics_collection_application,Metrics Collection Application>> to report on system metrics.

===== Installing the Metrics Endpoint

The Metrics Endpoint is installed by default with a standard installation in the ${ddf-platform} application.

===== Configuring the Metrics Endpoint

No configuration can be made for the Metrics Endpoint.
All of the metrics that it collects data on are pre-configured in ${branding}.

===== Using the Metrics Endpoint

.Metrics Endpoint URL
[source,http]
----
${secure_url}/services/internal/metrics/catalogQueries.png?startDate=2013-03-31T06:00:00-07:00&endDate=2013-04-01T11:00:00-07:00
----

The table below lists all of the options for the Metrics endpoint URL to execute custom metrics data requests:

.Metrics Endpoint URL Options
[cols="1m,3,2,1" options="header"]
|===

|Parameter
|Description
|Example
|Required

|startDate
|Specifies the start of the time range of the search on the metric's data (RFC-3339 - Date and Time format, i.e. YYYY-MM-DDTHH:mm:ssZ). Date/time must be earlier than the endDate. +
_This parameter cannot be used with the `dateOffset` parameter._
|`startDate=2013-03-31T06:00:00-07:00`
|true

|endDate
|Specifies the end of the time range of the search on the metric's data (RFC-3339 - Date and Time format, i.e. `YYYY-MM-DDTHH:mm:ssZ`). Date/time must be later than the startDate. +
_This parameter cannot be used with the `dateOffset` parameter._
|`endDate=2013-04-01T11:00:00-07:00`
|true

|dateOffset
|Specifies an offset, backwards from the current time, to search on the modified time field for entries. Defined in seconds and must be a positive Integer. +
_This parameter cannot be used with the `startDate` or `endDate` parameters._
|`dateOffset=1800`
|true

|yAxisLabel
|The label to apply to the graph's y-axis. Will default to the metric's name, e.g., Catalog Queries. +
_This parameter is only applicable for the metric's graph display format._
|Catalog Query Count
|false

|title
|The title to be applied to the graph.
+
Will default to the metric's name plus the time range used for the graph.
+
_This parameter is only applicable for the metric's graph display format._
|Catalog Query Count for the last 15 minutes
|false

|===

====== Metrics Data Supported Formats

The metric's historical data can be displayed in several formats, including PNG , a CSV file, an Excel .xls file, a PowerPoint .ppt file, an XML file, and a JSON file.
The PNG, CSV, and XLS formats are accessed via hyperlinks provided in the Metrics tab web page.
The PPT, XML, and JSON formats are accessed by specifying the format in the custom URL, e.g., ${public_url}/services/internal/metrics/catalogQueries.json?dateOffset=1800.

The table below describes each of the supported formats, how to access them, and an example where applicable. (NOTE: all example URLs begin with \${secure_url} which is omitted in the table for brevity.)

.Metrics Formats
[cols="1,2,1,3a" options="header"]
|===

|Display Format
|Description
|How To Access
|Example URL

.5+|PNG
.5+|Displays the metric's data as a PNG-formatted graph, where the x-axis is time and the y-axis is the metric's sampled data values.

.5+|Via hyperlink on the Metrics tab or directly via custom URL.

|Accessing Catalog Queries metric data for last 8 hours (8 * 60 * 60 = 28800 seconds):

|`/services/internal/metrics/catalogQueries.png?dateOffset=28800&yAxisLabel=mylabel&title=mygraphtitle`

|Accessing Catalog Queries metric data between 6:00 am on March 10, 2013, and 10:00 am on April 2, 2013:

|`/services/internal/metrics/catalogQueries.png?startDate=2013-03-10T06:00:00-07:00&endDate=2013-04-02T10:00:00-07:00&yAxisLabel=mylabel&title=mygraphtitle`

|_Note that the `yAxisLabel` and `title` parameters are optional_.

.4+|CSV
.4+|Displays the metric's data as a Comma-Separated Value (CSV) file, which can be auto-displayed in Excel based on browser settings.

The generated CSV file will consist of two columns of data: Timestamp and Value, where the first row contains the column headers and the remaining rows contain the metric's sampled data over the specified time range.
.4+|Via hyperlink on the Metrics tab or directly via custom URL.
|Accessing Catalog Queries metric data for last 8 hours (8 * 60 * 60 = 28800 seconds):
|`/services/internal/metrics/catalogQueries.csv?dateOffset=28800`
|Accessing Catalog Queries metric data between 6:00 am on March 10, 2013, and 10:00 am on April 2, 2013:
|`/services/internal/metrics/catalogQueries.csv?startDate=2013-03-10T06:00:00-07:00&endDate=2013-04-02T10:00:00-07:00`

.4+|XLS
.4+|Displays the metric's data as an Excel (XLS) file, which can be auto-displayed in Excel based on browser settings. The generated XLS file will consist of: Title in first row based on metric's name and specified time range Column headers for Timestamp and Value; Two columns of data containing the metric's sampled data over the specified time range; The total count, if applicable, in the last row
.4+|Via hyperlink on the Metrics tab or directly via custom URL.
|Accessing Catalog Queries metric data for last 8 hours (8 * 60 * 60 = 28800 seconds):
|`/services/internal/metrics/catalogQueries.xls?dateOffset=28800`
|Accessing Catalog Queries metric data between 6:00 am on March 10, 2013, and 10:00 am on April 2, 2013:
|`/services/internal/metrics/catalogQueries.xls?startDate=2013-03-10T06:00:00-07:00&endDate=2013-04-02T10:00:00-07:00`

.4+|PPT
.4+|Displays the metric's data as a PowerPoint (PPT) file, which can be auto-displayed in PowerPoint based on browser settings. The generated PPT file will consist of a single slide containing: A title based on the metric's name; The metric's PNG graph embedded as a picture in the slide The total count, if applicable
.4+|Via custom URL only
|Accessing Catalog Queries metric data for last 8 hours (8 * 60 * 60 = 28800 seconds):
|`/services/internal/metrics/catalogQueries.ppt?dateOffset=28800`
|Accessing Catalog Queries metric data between 6:00 am on March 10, 2013, and 10:00 am on April 2, 2013:
|`/services/internal/metrics/catalogQueries.ppt?startDate=2013-03-10T06:00:00-07:00&endDate=2013-04-02T10:00:00-07:00`

.5+|XML
.5+|Displays the metric's data as an XML-formatted file.
.5+|via custom URL only
|Accessing Catalog Queries metric data for last 8 hours (8 * 60 * 60 = 28800 seconds):
|`/services/internal/metrics/catalogQueries.xml?dateOffset=28800`
|Accessing Catalog Queries metric data between 6:00 am on March 10, 2013, and 10:00 am on April 2, 2013:
|`/services/internal/metrics/catalogQueries.xml?startDate=2013-03-10T06:00:00-07:00&endDate=2013-04-02T10:00:00-07:00`
|See <<_sample_xml_metrics_output,Sample XML-formatted output>>.


.5+|JSON
.5+|Displays the metric's data as an JSON-formatted file.
.5+|via custom URL only
|Accessing Catalog Queries metric data for last 8 hours (8 * 60 * 60 = 28800 seconds):
|`/services/internal/metrics/catalogQueries.json?dateOffset=28800`
|Accessing Catalog Queries metric data between 6:00 am on March 10, 2013, and 10:00 am on April 2, 2013:
|`/services/internal/metrics/catalogQueries.json?startDate=2013-03-10T06:00:00-07:00&endDate=2013-04-02T10:00:00-07:00`
|See <<_sample_json_metrics_output,Sample JSON-Formatted Output>>.

|===

[[_sample_xml_metrics_output]]
.Sample XML-Formatted Output
[source,xml,linenums]
----
<catalogQueries>
    <title>Catalog Queries for Apr 15 2013 08:45:53 to Apr 15 2013 09:00:53</title>
        <data>
            <sample>
                 <timestamp>Apr 15 2013 08:45:00</timestamp>
                 <value>361</value>
            </sample>
            <sample>
                <timestamp>Apr 15 2013 09:00:00</timestamp>
                <value>353</value>
            </sample>
            <totalCount>5721</totalCount>
        </data>
</catalogQueries>
----

[[_sample_json_metrics_output]]
.Sample JSON-formatted Output
[source,json,linenums]
----
{
 "title":"Query Count for Jul 9 1998 09:00:00 to Jul 9 1998 09:50:00",
 "totalCount":322,
 "data":[
    {
       "timestamp":"Jul 9 1998 09:20:00",
       "value":54
    },
    {
       "timestamp":"Jul 9 1998 09:45:00",
       "value":51
    }
  ]
}
----

====== Add Custom Metrics to the Metrics Tab

It is possible to add custom (or existing, but non-collected) metrics to the Metrics tab by writing an application.
Refer to the SDK example source code for Sample Metrics located in the ${branding} source code at `sdk/sample-metrics` and `sdk/sdk-app`.

[WARNING]
====
The Metrics framework is not an open API, but rather a closed, internal framework that can change at any time in future releases.
Be aware that any custom code written may not work with future releases.
====

===== Usage Limitations of the Metrics Endpoint

The Metrics Collecting Application uses a “round robin” database.
It uses one that does not store individual values but, instead, stores the rate of change between values at different times. 
Due to the nature of this method of storage, along with the fact that some processes can cross time frames, small discrepancies (differences in values of one or two have been experienced) may appear in values for different time frames. 
These will be especially apparent for reports covering shorter time frames such as 15 minutes or one hour. 
These are due to the averaging of data over time periods and should not impact the values over longer periods of time.
