////
NOTE TO REVIEWERS:
The Content in this file is being migrated to other files. Ignore changes here, as the content has been moved to a new home. A nice farm; upstate.
////
The ${ddf-catalog} provides a framework for storing, searching, processing, and transforming information.
Clients typically perform query, create, read, update, and delete (QCRUD) operations against the Catalog.  
At the core of the Catalog functionality is the Catalog Framework, which routes all requests and responses through the system, invoking additional processing per the system configuration.

=== Whitelist

The following packages have been exported by the ${ddf-catalog} application and are approved for use by third parties:

* `${ddf-branding-lowercase}.camel.component.catalog`
* `${ddf-branding-lowercase}.catalog`
* `${ddf-branding-lowercase}.catalog.cache`
* `${ddf-branding-lowercase}.catalog.data`
* `${ddf-branding-lowercase}.catalog.data.metacardtype`
* `${ddf-branding-lowercase}.catalog.event`
* `${ddf-branding-lowercase}.catalog.federation`
* `${ddf-branding-lowercase}.catalog.federation.impl`
* `${ddf-branding-lowercase}.catalog.filter`
* `${ddf-branding-lowercase}.catalog.filter.delegate`
* `${ddf-branding-lowercase}.catalog.impl.filter`
* `${ddf-branding-lowercase}.catalog.operation`
* `${ddf-branding-lowercase}.catalog.plugin`
* `${ddf-branding-lowercase}.catalog.plugin.groomer`
* `${ddf-branding-lowercase}.catalog.pubsub`
* `${ddf-branding-lowercase}.catalog.pubsub.tracker`
* `${ddf-branding-lowercase}.catalog.resource`
* `${ddf-branding-lowercase}.catalog.resource.data`
* `${ddf-branding-lowercase}.catalog.resource.impl`
* `${ddf-branding-lowercase}.catalog.resourceretriever`
* `${ddf-branding-lowercase}.catalog.service`
* `${ddf-branding-lowercase}.catalog.source`
* `${ddf-branding-lowercase}.catalog.transform`
* `${ddf-branding-lowercase}.catalog.transformer.api`
* `${ddf-branding-lowercase}.catalog.transformer.metacard.geojson`
* `${ddf-branding-lowercase}.catalog.util`
* `${ddf-branding-lowercase}.catalog.validation`
* `${ddf-branding-lowercase}.common`
* `${ddf-branding-lowercase}.geo.formatter`
* `${ddf-branding-lowercase}.util`
* `org.codice.${ddf-branding-lowercase}.endpoints`
* `org.codice.${ddf-branding-lowercase}.endpoints.rest`
* `org.codice.${ddf-branding-lowercase}.endpoints.rest.action`
* `org.codice.${ddf-branding-lowercase}.opensearch.query`
* `org.codice.${ddf-branding-lowercase}.opensearch.query.filter`


=== Catalog Development Fundamentals

This section introduces the fundamentals of working with the Catalog API the OGC Filter for Queries.

==== Simple Catalog API Implementations

The Catalog API implementations, which are denoted with the suffix of `Impl` on the Java file names, have multiple purposes and uses.

* First, they provide a good starting point for other developers to extend functionality in the framework. For instance, extending the `MetacardImpl` allows developers to focus less on the inner workings of ${branding} and more on the developer's intended purposes and objectives. 

* Second, the Catalog API Implementations display the proper usage of an interface and an interface's intentions. Also, they are good code examples for future implementations. If a developer does not want to extend the simple implementations, the developer can at least have a working code reference to base future development.

==== Use of the Whiteboard Design Pattern

The ${ddf-catalog} makes extensive use of the Whiteboard Design Pattern.
Catalog Components are registered as services in the OSGi Service Registry, and the Catalog Framework or any other clients tracking the OSGi Service Registry are automatically notified by the OSGi Framework of additions and removals of relevant services.

The Whiteboard Design Pattern is a common OSGi technique that is derived from a technical whitepaper provided by the OSGi Alliance in 2004.
It is recommended to use the Whiteboard pattern over the Listener pattern in OSGi because it provides less complexity in code (both on the client and server sides), fewer deadlock possibilities than the Listener pattern, and closely models the intended usage of the OSGi framework.


==== Developing Console Commands

===== Console Commands

${branding} supports development of custom console commands.

${branding} includes custom commands for working with the Catalog, as described in the <<managing.adoc#_console_commands, Managing Console Commands>> section.







