
==== Configuring with .config Files

The ${branding} is configured using `.config` files.
Like the Karaf `.cfg` files, these configuration files must be located in the `<${branding}_HOME>/etc/` directory.
Unlike the Karaf `.cfg` files, `.config` files must follow the naming convention that includes the _configuration persistence ID_ (PID) that they represent.
The filenames must be the pid with a `.config` extension.
This type of configuration file also supports lists within configuration values (metatype `cardinality` attribute greater than 1) and String, Boolean, Integer, Long, Float, and Double values.

[IMPORTANT]
====
This new configuration file format *must* be used for any configuration that makes use of lists.
Examples include Web Context Policy Manager (`org.codice.ddf.security.policy.context.impl.PolicyManager.config`)
and Security STS Guest Claims Handler (`ddf.security.sts.guestclaims.config`).
====

[WARNING]
====
Only one configuration file should exist for any given PID.
The result of having both a `.cfg` and a `.config` file for the same PID is undefined and could cause the application to fail.
====

The main purpose of the configuration files is to allow administrators to pre-configure ${branding} without having to use the ${admin-console}.
In order to do so, the configuration files need to be copied to the `<${branding}_HOME>/etc` directory after ${branding} zip has been extracted.

Upon start up, all the `.config` files located in `<${branding}_HOME>/etc` are automatically read and processed.
${branding} monitors the `<${branding}_HOME>/etc` directory for any new `.config` file that gets added.
As soon as a new file is detected, it is read and processed.
Changes to these configurations from the ${admin-console} or otherwise are persisted in the original configuration file in the `<${branding}_HOME>/etc` directory.