
==== Importing the Exported Configuration Settings

[WARNING]
====
Importing of configurations must take place before starting the new installation for the first time and after performing OS-level hardening.
====

To import a previously exported configuration file from the ${command-console}:

. Launch the newly installed ${branding}.
. Type in `migration:import <directory>`. This command reads the previously exported configuration file `exported-${project-version}.zip` from the specified directory. If no directory is specified it will default to `<${branding}_HOME>/exported`
. Shutdowns ${branding} by typing in `shutdown`
. Re-launch the newly migrated ${branding}

[NOTE]
====
Before proceeding with importing the exported configurations, the system will automatically export all configurations to a file named `exported-${project.version}-<timestamp>.zip` in the same directory. This exported file can be used to restore the state of the system to what it was before the import started in case any errors occurs.
====

[IMPORTANT]
====
Some system configuration files contain paths to other configuration files. For instance, the `system.properties` file contains the `javax.net.ssl.keyStore` property which provides the path to system key store.
The files referred to in the system configuration files would have been included in the export process only if the path is relative to `<${branding}_HOME>`. It is the responsibility of the administrator to ensure these files exists on the new system.
Using absolute paths and/or symbolic links in those cases will cause the `migration:import` command to display warnings about those files if they are no longer available at import time.
The import process itself will not be aborted.
====
