
==== Managing Applications from ${admin-console}

The *Manage* button enables activation/deactivation and adding/removing applications.

===== Activating / Deactivating Applications

The *Deactivate* button stops individual applications and any dependent apps.
Certain applications are central to overall functionality and cannot be deactivated.
These will have the *Deactivate* button disabled.
Disabled apps will be moved to a list at the bottom of the page, with an enable button to reactivate, if desired.

The *Add Application* button is at the end of the list of currently active applications.

===== Removing Applications

To remove an application, it must first be deactivated.
This enables the *Remove Application* button.

===== Upgrading Applications

Each application tile includes an upgrade button to select a new version to install.

===== System Settings Tab

The configuration and features installed can be viewed and edited from the System tab as well; however, it is recommended that configuration be managed from the applications tab.

[IMPORTANT]
====
In general, applications should be managed via the applications tab.
Configuration via this page could result in an unstable system.
Proceed with caution!
====

==== Federation

It is recommended to use the *${ddf-catalog} App -> Sources* tab to configure and manage sites/sources.
