==== Custom Mime Type Resolver

The Custom Mime Type Resolver is a `MimeTypeResolver` that defines the custom mime types that ${branding} will support out of the box.
These are mime types not supported by the default `TikaMimeTypeResolver`.

.Custom Mime Type Resolver Default Supported Mime Types
[cols="1m,2m" options="header"]
|===

|File Extension
|Mime Type

|nitf
|image/nitf

|ntf
|image/nitf

|json
|json=application/json;id=geojson

|===

New custom mime type resolver mappings can be added using the Admin Console.

As a `MimeTypeResolver`, the Custom Mime Type Resolver will provide methods to map the file extension to the corresponding mime type, and vice versa.

The Custom Mime Type Resolver is used when mime types need to be added that are not supported by ${branding} out of the box.
By adding custom mime type resolvers to ${branding}, new content with that mime type can be processed by ${branding}.

===== Installing the Custom Mime Type Resolver

One Custom Mime Type Resolver is configured and installed out of the box for the `image/nitf` mime type.
This custom resolver is bundled in the `mime-core-app` application and is part of the `mime-core` feature.

Additional Custom Mime Type Resolvers can be added for other custom mime types.

====== Configuring the Custom Mime Type Resolver

The configurable properties for the Custom Mime Type Resolver are accessed from the *MIME Custom Types* configuration in the Admin Console.

*Managed Service Factory PID*

* `${ddf-branding}_Custom_Mime_Type_Resolver`

.Custom Mime Type Resolver Configurable Properties
[cols="1,1,1,3,1,1" options="header"]
|===
|Title
|Property
|Type
|Description
|Default Value
|Required

|Resolver Name
|`name`
|String
|Unique name for the custom mime type resolver.
|N/A
|Yes

|Priority
|`priority`
|Integer
|Execution priority of the resolver.

Range is 0 to 100, with 100 being the highest priority.
|10
|Yes

|File Extensions to Mime Types
|`customMimeTypes`
|String
|Comma-delimited list of key/value pairs where key is the file extension and value is the mime type, e.g., `nitf=image/nitf`.
|N/A
|Yes

|===

.Custom Mime Type Resolver Imported Services
[cols="4,1,1" options="header"]
|===

|Registered Interface
|Availability
|Multiple

|`${ddf-branding-lowercase}.catalog.transform.InputTransformer`
|optional
|true

|`${ddf-branding-lowercase}.catalog.transform.QueryResponseTransformer`
|optional
|true

|`${ddf-branding-lowercase}.mime.MimeTypeResolver`
|optional
|true

|===

.Custom Mime Type Resolver Exported Services
[cols="4,2,1" options="header"]
|===

|Registered Interface
|Service Property
|Value

|`${ddf-branding-lowercase}.mime.MimeTypeToTransformerMapper`
|
|
 
|`${ddf-branding-lowercase}.mime.MimeTypeMapper`
|
|
 
|===

