==== GeoJSON Metacard Transformer

GeoJSON Metacard Transformer translates a Metacard into GeoJSON.

===== Installing the GeoJSON Metacard Transformer

The GeoJSON Metacard Transformer is not installed by default on a standard installation.
To Install:

* Navigate to the ${admin-console}
* Navigate to the *${ddf-catalog}* application.
* Navigate to the *Features* tab.
* Install the `catalog-transformer-json` feature.

===== Configuring the GeoJSON Metacard Transformer

None.

===== Using the GeoJSON Metacard Transformer

The GeoJSON Metacard Transformer can be used programmatically by requesting a `MetacardTransformer` with the id `geojson`.
It can also be used within the REST Endpoint by providing the transform option as `geojson`.

.Example REST GET method with the GeoJSON MetacardTransformer
----
${secure_url}/services/catalog/0123456789abcdef0123456789abcdef?transform=geojson
----

.Example Output
[source,javascript,linenums]
----
{
    "properties":{
        "title":"myTitle",
        "thumbnail":"CA==",
        "resource-uri":"http:\/\/example.com",
        "created":"2012-08-31T23:55:19.518+0000",
        "metadata-content-type-version":"myVersion",
        "metadata-content-type":"myType",
        "metadata":"<xml>text<\/xml>",
        "modified":"2012-08-31T23:55:19.518+0000",
        "metacard-type": "${ddf-branding}.metacard"
    },
    "type":"Feature",
    "geometry":{
        "type":"LineString",
        "coordinates":[
            [
                30.0,
                10.0
            ],
            [
                10.0,
                30.0
            ],
            [
                40.0,
                40.0
            ]
        ]
    }
}
----

.Implementation Details
[cols="3*" options="header"]
|===
|Registered Interface
|Service Property
|Value

1.3+^|`${ddf-branding}.catalog.transform.MetacardTransformer`
|mime-type
|application/json

|id
|geojson

|shortname (for backwards compatibility)
|geojson

|===

===== Known Issues with the GeoJSON Metacard Transformer

None.
