
==== HTML Metacard Transformer

The HTML metacard transformer is responsible for translating a metacard into an HTML-formatted document.

===== Installing the HTML Metacard Transformer

The HTML Metacard Transformer is installed by default with standard installation in the ${ddf-ui} application.

===== Configuring the HTML Metacard Transformer

The HTML Metacard Transformer has no configurable properties.

===== Using the HTML Metacard Transformer

Using the REST Endpoint for example, request a metacard with the transform option set to the HTML shortname.
----
${secure_url}/services/catalog/0123456789abcdef0123456789abcdef?transform=html
----

.HTML Metacard Transformer Example Output
----
html metacard.png
----

.HTML Metacard Transformer Implementation Details
[cols="3*" options="header"]
|===
|Registered Interface
|Service Property
|Value

1.3+^|`ddf.catalog.transform.MetacardTransformer`
|title
|View as html...
|description
|Transforms query results into html
|shortname (for backwards compatibility)
|html

|===
