==== Metadata Metacard Transformer

The Metadata Metacard Transformer returns the `Metacard.METADATA` attribute when given a metacard.
The MIME Type returned is `text/xml`.

===== Installing the Metadata Metacard Transformer

The Metadata Metacard Transformer is installed by default with a standard installation in the ${ddf-catalog} application.

This transformer's feature, `catalog-transformer-metadata`, can be uninstalled.

===== Configuring the Metadata Metacard Transformer

The Metadata Metacard Transformer has no configurable properties.

===== Using the Metadata Metacard Transformer

The Metadata Metacard Transformer can be used programmatically by requesting a metacard transformer with the id `metadata`.
It can also be used within the REST Endpoint by providing the transform option as `metadata`.

.Example REST GET method with the Metadata Metacard Transformer
----
${public_url}/services/catalog/0123456789abcdef0123456789abcdef?transform=metadata
----

.Metadata Metacard Transformer Exported Services
[cols="3" options="header"]
|===
|Registered Interface
|Service Property
|Value

1.3+^|`ddf.catalog.transform.MetacardTransformer`

|mime-type
|`text/xml`

|id
|metadata

|shortname (for backwards compatibility)
|metadata

|===
