
=== Metacard Transformers

The following metacard transformers are available with a standard installation of ${branding}.

<<_geojson_metacard_transformer,GeoJSON Metacard Transformer>>:: Translates a Metacard into GeoJSON.

<<_html_metacard_transformer,HTML Metacard Transformer>>:: Translates a metacard into an HTML formatted document.

<<_kml_metacard_transformer, KML Metacard Transformer>>:: _implements [KML]_. Translates a metacard into a KML-formatted document.

<<_kml_style_mapper,KML Style Mapper>>:: Provides the ability for the `KmlTransformer` to map a KML Style URL to a metacard based on that metacard's attributes.

<<_metadata_metacard_transformer,Metadata Metacard Transformer>>:: Returns the `Metacard.METADATA` attribute when given a metacard.

<<_registry_transformer,RegistryTransformer>>:: Translates a Registry metacard.

<<_resource-metacard_transformer,Resource Metacard Transformer>>:: Retrieves the resource bytes of a metacard by returning the product associated with the metacard.

<<_thumbnail_metacard_transformer,Thumbnail Metacard Transformer>>:: Retrieves the thumbnail bytes of a Metacard by returning the `Metacard.THUMBNAIL` attribute value.

<<_xml_metacard_transformer,XML Metacard Transformer>>:: Translates a metacard into an XML-formatted document.
