# a docker-compose.yml to start a simple cluster with one ZooKeeper node and two Solr nodes.
#
version: '3.7'

services:

  zoo:
    image: zookeeper:3.4
    container_name: zoo
    restart: always
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo:2888:3888
    volumes:
      - ./zoo.cfg:/conf/zoo.cfg
      - zoo_data:/data
    networks:
      - solrcloud

  solr1:
    image: codice/ddf-solr:2.22.0-SNAPSHOT
    container_name: solr1
    hostname: localhost
    restart: always
    entrypoint: docker-entrypoint.sh
    command: solr-fg
    ports:
      - "8994:8994"
      - "8995:8995"
    environment:
      - SOLR_HOME=/opt/solr/server/solr/nodes/node1
      - SOLR_HOST=localhost
      - SOLR_PORT=8994
      - ZK_HOST=zoo:2181
    volumes:
      - ./solr.xml:/opt/solr/server/solr/nodes/node1/solr.xml
      - solr1_data:/opt/solr/server/solr/nodes/node1
    networks:
      - solrcloud
    depends_on:
      - zoo

  solr2:
    image: codice/ddf-solr:2.22.0-SNAPSHOT
    container_name: solr2
    restart: always
    entrypoint: docker-entrypoint.sh
    command: solr-fg
    environment:
      - SOLR_HOME=/opt/solr/server/solr/nodes/node2
      - SOLR_HOST=localhost
      - SOLR_PORT=8995
      - ZK_HOST=zoo:2181
    volumes:
      - ./solr.xml:/opt/solr/server/solr/nodes/node2/solr.xml
      - solr2_data:/opt/solr/server/solr/nodes/node2
    network_mode: "service:solr1"
    depends_on:
      - zoo
      - solr1

networks:
  solrcloud:

volumes:
  solr1_data:
  solr2_data:
  zoo_data:
