:type: securityService
:status: published
:title: Expansion Service
:link: _expansion_service
:order: 02
:summary: Defines rulesets to map metacard and user attributes to more complete sets of values.

The expansion service defines rulesets to map metacard attributes and user attributes to more complete sets of values.
For example if a user has an attribute "alphabet" that contained the value "full", the expansion service can be configured to expand the "full" value out to ["a","b","c",...].

==== Configuring Expansion Service

To use the expansion service, modify the following two files within the `<${branding}_HOME>/etc` directory:

* `<${branding}_HOME>/etc/pdp/${ddf-branding-lowercase}-metacard-attribute-ruleset.cfg`
* `<${branding}_HOME>/etc/pdp/${ddf-branding-lowercase}-user-attribute-ruleset.cfg`

Within these files, the following configuration details will be defined.

===== Expansion Service Instances and Configuration

It is expected that multiple instances of the expansion service will be running at the same time.
Each instance of the service defines a unique property that is useful for retrieving specific instances of the expansion service.
The following table lists the two pre-defined instances used by ${ddf-branding} for expanding user attributes and metacard attributes respectively.

[cols="1,3,5" options="header"]
|===
|Property Name
|Value
|Description

|mapping
|`security.user.attribute.mapping`
|This instance is configured with rules that expand the user's attribute values for security checking.

|mapping
|`security.metacard.attribute.mapping`
|This instance is configured with rules that expand the metacard's security attributes before comparing with the user's attributes.

|===

Each instance of the expansion service can be configured using a configuration file.
The configuration file can have three different types of lines:
comments:: any line prefixed with the `#` character is ignored as a comment (for readability, blank lines are also ignored)
attribute separator:: a line starting with `separator=` defines the attribute separator string.
rule:: all other lines are assumed to be rules defined in a string format `<key>:<original value>:<new value>`

The following configuration file defines the rules shown above in the example table (using the space as a separator):

----
# This defines the separator that will be used when the expansion string contains multiple
# values - each will be separated by this string. The expanded string will be split at the
# separator string and each resulting attributed added to the attribute set (duplicates are
# suppressed). No value indicates the defualt value of ' ' (space).
separator=

# The following rules define the attribute expansion to be performed. The rules are of the
# form:
#       <attribute name>:<original value>:<expanded value>
# The rules are ordered, so replacements from the first rules may be found in the original
# values of subsequent rules.
Location:Goodyear:Goodyear AZ
Location:AZ:AZ USA
Location:CA:CA USA
Title:VP-Sales:VP-Sales VP Sales
Title:VP-Engineering:VP-Engineering VP Engineering
----

.Expansion Commands
[cols="2,1,4" options="header"]
|===

|Title
|Namespace
|Description

|${ddf-branding}::Security::Expansion::Commands
|security
|The expansion commands provide detailed information about the expansion rules in place and the ability to see the results of expanding specific values against the active ruleset.
|===

[cols="2m,5"]
|===
|Command
|Description

|security:expand
|Runs the expansion service on the provided data returning the expanded value.

|security:expansions
|Dumps the ruleset for each active expansion service.
|===

===== Expansion Command Examples and Explanation

====== security:expansions

The `security:expansions` command dumps the ruleset for each active expansion service.
It takes no arguments and displays each rule on a separate line in the form: `<attribute name> : <original string> : <expanded string>`.
The following example shows the results of executing the expansions command with no active expansion service.

[source]
----
${branding-lowercase}${at-symbol}local>security:expansions
No expansion services currently available.
----

After installing the expansions service and configuring it with an appropriate set of rules, the expansions command will provide output similar to the following:

[source]
----
${branding-lowercase}${at-symbol}local>security:expansions
Location : Goodyear : Goodyear AZ
Location : AZ : AZ USA
Location : CA : CA USA
Title : VP-Sales : VP-Sales VP Sales
Title : VP-Engineering : VP-Engineering VP Engineering
----

====== security:expand

The security:expand command runs the expansion service on the provided data.
It takes an attribute and an original value, expands the original value using the current expansion service and ruleset and dumps the results.
For the ruleset shown above, the expand command produces the following results:

[source]
----
${branding-lowercase}${at-symbol}local>security:expand Location Goodyear
[Goodyear, USA, AZ]

${branding-lowercase}${at-symbol}local>security:expand Title VP-Engineering
[VP-Engineering, Engineering, VP]

${branding-lowercase}${at-symbol}local>expand Title "VP-Engineering Manager"
[VP-Engineering, Engineering, VP, Manager]
----
