:type: securitySts
:status: published
:title: Security STS Client Config
:link: _security_sts_client_config
:order: 01

The ${ddf-security} STS Client Config bundle keeps track and exposes configurations and settings for the CXF STS client.
This client can be used by other services to create their own STS client.
Once a service is registered as a watcher of the configuration, it will be updated whenever the settings change for the sts client.

===== Installing the Security STS Client Config

This bundle is installed by default.

===== Configuring the Security STS Client Config

Configure the Security STS Client Config from the ${admin-console}:

. Navigate to the ${admin-console}.
. Select *${ddf-security}* Application.
. Select *Configuration* tab.
. Select *Security STS Client*.

See <<ddf.security.sts.client.configuration,Security STS Client configurations>> for all possible configurations.

.Security STS Client Config Imported Services
[cols="3" options="header"]
|===

|Registered Interface
|Availability
|Multiple

|`org.osgi.service.cm.ConfigurationAdmin`
|required
|false

|===

.Security STS Client Config Exported Services
None.
