
=== ${branding} Schematron

${branding} uses http://www.schematron.com/overview.html[Schematron Validation] to validate metadata ingested into the catalog.

Custom schematron rulesets can be used to validate metacard metadata.
Multiple services can be created, and each service can have multiple rule sets associated with it.
Namespaces are used to distinguish services.
The root schematron files may be placed anywhere on the file system as long as they are configured with an absolute path.
Any root schematron files with a relative path are assumed to be relative to `${ddf-branding}_HOME/schematron`.

[TIP]
====
Schematron files may reference other schematron files using an include statement with a relative path.
However, when using the document function within a schematron ruleset to reference another file, the path must be absolute or relative to the ${ddf-branding} installation home directory.
====

==== Configuring Schematron Services

Schematron validation services are configured with a namespace and one or more schematron rule sets.
Additionally, warnings may be suppressed so that only errors are reported.
To create a new service, ensure that catalog-schematron-plugin is started and then click Schematron Validation Services.
