:title: Using ${catalog-ui}
:type: usingIntro
:status: published
:summary: Introduction to using Intrigue.

== {title}

${catalog-ui} represents the most advanced search interface available with ${branding}.
It provides metadata search and discovery, resource retrieval, and workspace management with a 3D or optional 2D map visualization.

.Contextual Help Feature
[NOTE]
====
For more detail on any feature or button within ${catalog-ui}, click the `?` icon in the upper right of the screen; then, hover over any item on the screen and a contextual tooltip will be displayed to define its purpose.
To exit this mode, click the `?` again or press `escape`.
====

.Glossary of Terms
====
<<{using-prefix}advanced_query_builder,((Advanced Query Builder))>>:: Search tool for building complex queries beyond basic searches.
<<{using-prefix}associations,((Associations))>>:: User-defined relationships between different data products.
<<{using-prefix}using_the_attribute_editor,((Attribute Editor))>>:: Tool used to edit metadata attributes on uploads.
<<{using-prefix}basic_search,((Basic Search Tool))>>:: Search tool for building simple searches.
<<{using-prefix}inspector,((Inspector))>>:: Tool for viewing and editing metadata attributes.
<<{using-prefix}using_lists,((Lists))>>:: User-defined collections of related results or products.
<<{using-prefix}map_tools,((Map Tools Widget))>>:: Tool for customizing or navigating the map view.
<<{using-prefix}viewing_metadata_quality,((Metadata Quality))>>:: A measure of the completeness or correctness of the metadata of a product.
<<{using-prefix}using_result_forms,((Result Forms))>>:: Customizable templates of the attributes shown when viewing searches.
<<{using-prefix}using_search_forms,((Search Forms))>>:: Customizable templates of the attributes used in creating searches.
<<{using-prefix}sources_view,((Sources View))>>:: View the health and status of all configured data sources
<<{using-prefix}temporal_search_details,((Temporal Search))>>:: Basic search using time-based search terms.
<<{using-prefix}spatial_search_details,((Spatial Search))>>:: Basic search using location-based search terms.
<<{using-prefix}text_search_details,((Text Search))>>:: Basic search using the text of documents and/or metadata.
<<{using-prefix}adding_visuals,((Visuals))>>:: Tools to view search results or the information about them.
<<{using-prefix}using_workspaces,((Workspaces))>>:: User-defined collections of searches and search settings.
====
