
This quick tutorial will enable install, configuring and using a basic instance of ${branding}.

[NOTE]
====
This tutorial is intended for setting up a test, demonstration, or trial installation of ${branding}.
For more complete installation and configuration steps, see <<_installing,Installing>>.
====

These steps will demonstrate:

- [*] <<_quick_install_prerequisites,Prerequisites>>.
- [*] <<_quick_install_of_${branding-lowercase},Quick Install of ${branding}>>.
- [*] <<_ingesting_sample_data,Ingesting Data>>.

=== Quick Install Prerequisites

These are the basic requirements to set up the environment to run a ${branding}.

==== Java Requirements (Quick Install)

Set up Java to run ${branding}.

* Install/Upgrade to Java 8 http://www.oracle.com/technetwork/java/javase/downloads/index.html[J2SE 8 SDK]
** The recommended version is http://www.oracle.com/technetwork/java/javase/8u60-relnotes-2620227.html[8u60] or later.
** Java Version and Build numbers must contain only number values.
* Supported platforms are *NIX - Unix/Linux/OSX, Solaris, and Windows.
* http://www.oracle.com/technetwork/java/javase/downloads/index.html[JDK8] must be installed.
* The `JAVA_HOME` environment variable must be set to the location where the JDK is installed.

.Setting JAVA_HOME variable (Replace `<JAVA_VERSION>` with the version and build number installed.)
====

. Determine Java Installation Directory (This varies between operating system versions).

.Find Java Path in *NIX
----
which java
----

.Find Java Path in Windows
----
for %i in (java.exe) do @echo. %~$PATH:i
----

. Copy path to Java installation. (example: `/usr/java/<JAVA_VERSION>`)
. Set `JAVA_HOME` by replacing <PATH_TO_JAVA> with the copied path in this command:

.Setting `JAVA_HOME` on *NIX
----
JAVA_HOME=<PATH_TO_JAVA><JAVA_VERSION>
export JAVA_HOME
----

.Setting `JAVA_HOME` on Windows
----
set JAVA_HOME=<PATH_TO_JAVA><JAVA_VERSION> /m
----

.Adding `JAVA_HOME` to `PATH` Environment Variable on Windows
----
setx PATH "%PATH%;%JAVA_HOME%\bin" /m
----
====

.*NIX
[WARNING]
====
Unlink `JAVA_HOME` if it is already linked to a previous version of the JRE:
`unlink JAVA_HOME`
====

.Verify that the `JAVA_HOME` was set correctly.
[TIP]
====

.*NIX
----
echo $JAVA_HOME
----

.Windows
----
echo %JAVA_HOME%
----
====

.File Descriptor Limit on Linux
[NOTE]
====
* For Linux systems, increase the file descriptor limit by editing `/etc/sysctl.conf` to include:

----
fs.file-max = 6815744
----

* (This file may need permissions changed to allow write access).
* For the change to take effect, a restart is required.

. *Nix Restart Command
----
init 6
----
====

.Check System Time
[WARNING]
====
Prior to installing ${branding}, ensure the system time is accurate to prevent federation issues.
====

=== Quick Install of ${branding}

.Check System Time
[WARNING]
====
Prior to installing ${branding}, ensure the system time is accurate to prevent federation issues.
====

. Download the ${branding} {download-url}[zip file].
. Install ${branding} by unzipping the zip file.
+
.Windows Zip Utility Warning
[WARNING]
====
The default Windows zip utility (such as double-clicking file) will not work to unzip the distribution, use Java or a third party utility instead.

.Use Java to Unzip in Windows(Replace `<PATH_TO_JAVA>` with correct path `and <JAVA_VERSION>` with current version.)
----
"<PATH_TO_JAVA>\jdk<JAVA_VERSION>\bin\jar.exe" xf ${branding-lowercase}-${project.version}.zip
----
====
+
. This will create an installation directory, which is typically created with the name and version of the application.
This installation directory will be referred to as `<${branding}_HOME>`.
(Substitute the actual directory name.)
. Start ${branding} by running the `<${branding}_HOME>/bin/${branding-lowercase}` script (or `${branding-lowercase}.bat` on Windows).
. The ${command-console} will display.

.${command-console} Prompt
----
${branding-lowercase}${at-symbol}local>
----
