
This section supports developers creating extensions of the existing framework.

=== Whitelist

The following packages have been exported by the ${ddf-platform} application and are approved for use by third parties:

* `${ddf-branding-lowercase}.security`
* `${ddf-branding-lowercase}.security.assertion`
* `${ddf-branding-lowercase}.security.common.audit`
* `${ddf-branding-lowercase}.security.http`
* `${ddf-branding-lowercase}.security.permission`
* `${ddf-branding-lowercase}.security.policy.extension`
* `${ddf-branding-lowercase}.security.principal`
* `${ddf-branding-lowercase}.security.samlp`
* `${ddf-branding-lowercase}.security.service`
* `${ddf-branding-lowercase}.security.settings`
* `${ddf-branding-lowercase}.security.sts.client.configuration`
* `${ddf-branding-lowercase}.security.ws.policy`
* `${ddf-branding-lowercase}.security.ws.proxy`
* `org.codice.${ddf-branding-lowercase}.branding`
* `org.codice.${ddf-branding-lowercase}.configuration`
* `org.codice.${ddf-branding-lowercase}.configuration.admin`
* `org.codice.${ddf-branding-lowercase}.configuration.migration`
* `org.codice.${ddf-branding-lowercase}.configuration.persistence`
* `org.codice.${ddf-branding-lowercase}.configuration.persistence.felix`
* `org.codice.${ddf-branding-lowercase}.configuration.status`
* `org.codice.${ddf-branding-lowercase}.notifications.store`
* `org.codice.${ddf-branding-lowercase}.parser`
* `org.codice.${ddf-branding-lowercase}.parser.xml`
* `org.codice.${ddf-branding-lowercase}.platform.error.handler`
* `org.codice.${ddf-branding-lowercase}.platform.util`

[WARNING]
====
The Platform Application includes other third party packages such as Apache CXF and Apache Camel.
These are available for use by third party developers but their versions can change at any time with future releases of the Platform Application.
====

=== Developing Action Components (Action Framework)

The Action Framework was designed as a way to limit dependencies between applications (apps) in a system.
For instance, a feature in an app, such as a Atom feed generator, might want to include an external link as part of its feed's entries.
That feature does not have to be coupled to a REST endpoint to work, nor does it have to depend on a specific implementation to get a link.
In reality, the feature does not identify how the link is generated, but it does identify whether link works or does not work when retrieving the intended entry's metadata. \Instead of creating its own mechanism or adding an unrelated feature, it could use the Action Framework to query out in the OSGi container for any service that can provide a link.
This does two things: it allows the feature to be independent of implementations, and it encourages reuse of common services. 

The Action Framework consists of two major Java interfaces in its API:

. `${ddf-branding-lowercase}.action.Action`
. `${ddf-branding-lowercase}.action.ActionProvider`

==== Usage

To provide a service, such as a link to a record, the `ActionProvider` interface should be implemented.
An `ActionProvider` essentially provides a List of  `Action`s when given input that it can recognize and handle.
For instance, if a REST endpoint ActionProvider was given a metacard, it could provide a link based on the metacard's ID. 
An Action Provider performs an action when given a subject that it understands.
If it does not understand the subject or does not know how to handle the given input, it will return `Collections.emptyList()`.
An Action Provider is required to have an ActionProvider id.
The Action Provider must register itself in the OSGi Service Registry with the `${ddf-branding-lowercase}.action.ActionProvider` interface and must also have a service property value for `id`. 
An action is a URL that, when invoked, provides a resource or executes intended business logic. 

==== Naming Convention

For each Action, a title and description should be provided to describe what the action does.
The recommended naming convention is to use the verb 'Get' when retrieving a portion of the metacard, such as the metadata or thumbnail, or when you are downloading the product.
The verb 'Export' or expression 'Export as' is recommended when the metacard is bring exported in a different format or presented after going some transformation.

==== Taxonomy

An Action Provider registers an `id` as a service property in the OGSi Service Registry based on the type of service or action that is provided.
Regardless of implementation, if more than one Action Provider provides the same service, such as providing a URL to a thumbnail for a given metacard, they must both register under the same `id`.
Therefore, Action Provider implementers must follow an Action Taxonomy. 


The following is a sample taxonomy: 

. `catalog.data.metacard` shall be the grouping that represents Actions on a Catalog metacard.
.. `catalog.data.metacard.view`
.. `catalog.data.metacard.thumbnail`
.. `catalog.data.metacard.html`
.. `catalog.data.metacard.resource`
.. `catalog.data.metacard.metadata`

===== Action ID Service Descriptions

[cols="2,4,1" options="header"]
|===
|ID
|Required Action
|Naming Convention

|`catalog.data.metacard.view`
|Provides a valid URL to view all of a metacard data. Format of data is not specified; i.e. the representation can be in XML, JSON, or other.
|Export as ...

|`catalog.data.metacard.thumbnail`
|Provides a valid URL to the bytes of a thumbnail (`Metacard.THUMBNAIL`) with MIME type image/jpeg.
|Get Thumbnail

|`catalog.data.metacard.html`
|Provides a valid URL that, when invoked, provides an HTML representation of the metacard.
|Export as ...

|`catalog.data.metacard.resource`
|Provides a valid URL that, when invoked, provides the underlying resource of the metacard.
|Get Resource

|`catalog.data.metacard.metadata`
|Provides a valid URL to the XML metadata in the metacard (`Metacard.METADATA`).
|Get Metadata

|===

=== Developing Migratables

The `Migratable` API provides a mechanism for bundles to handle exporting data required to clone a ${branding} system.
The migration process is meant to be flexible, so an implementation of `org.codice.${ddf-branding-lowercase}.migration.Migratable` can handle
exporting data for a single bundle or groups of bundles such as applications. For example, the
`org.codice.${ddf-branding-lowercase}.platform.migratable.impl.PlatformMigratable` handles exporting core system files for the ${ddf-platform} Application.
Exporting configurations stored in `org.osgi.service.cm.ConfigurationAdmin` does not need to be handled by implementations of
`org.codice.${ddf-branding-lowercase}.migration.Migratable` as all `ConfigurationAdmin` configurations are exported by
`org.codice.${ddf-branding-lowercase}.configuration.admin.ConfigurationAminMigration`.

The Migratable API includes:

. `org.codice.${ddf-branding-lowercase}.migration.Migratable`
. `org.codice.${ddf-branding-lowercase}.migration.AbstractMigratable`
. `org.codice.${ddf-branding-lowercase}.migration.MigrationException`
. `org.codice.${ddf-branding-lowercase}.migration.MigrationMetadata`
. `org.codice.${ddf-branding-lowercase}.migration.MigrationWarning`

==== Usage

The `org.codice.${ddf-branding-lowercase}.migration.Migratable` interface defines these methods:

.`MigrationMetadata export(Path exportPath) throws MigrationException`
.`String getDescription()`
.`boolean isOptional()`

The `exportPath` in `export(Path exportPath)` is the path where all of the exportable data is copied. It is provided via an argument
to the `migration:export` console command or via the Export Dialog in the Admin Console. The default value is `<DISTRIBUTION HOME>/etc/exported`.
It is the responsibility of a `Migratable` to prevent naming collisions upon export. For example, if a `Migratable` writes files for its export, it
must namespace the files. The `getDescription()` operation returns a short description of the type of data exported by the `Migratable`.
The `isOptional()` operation returns whether the exported data for the `Migratable` is optional or required. The description and optional flag are
for display purposes in the Admin Console.

A `org.codice.${ddf-branding-lowercase}.migration.MigrationException` should be thrown when an unrecoverable exception occurs that prevents required data from exporting.
The exception message is displayed to the admin.

A `org.codice.${ddf-branding-lowercase}.migration.MigrationWarning` should be used when a `Migratable` wants to warn an admin that certain aspects of the export may
cause problems upon import. For example, if an absolute path is encountered, that path may not exist on the target system and cause
the installation to fail. All migration warnings are displayed to the admin.

In order to create a `Migratable` for a module of the system, the `org.codice.${ddf-branding-lowercase}.migration.Migratable` interface must be implemented
and the implementation must be registered under the `org.codice.${ddf-branding-lowercase}.migration.Migratable` interface as an OSGI service in
the OSGI service registry. Creating an OSGI service allows for the `org.codice.${ddf-branding-lowercase}.configuration.migration.ConfigurationMigrationManager`
to lookup all implementations of `org.codice.${ddf-branding-lowercase}.migration.Migratable` and command them to export.

The abstract base class `org.codice.${ddf-branding-lowercase}.migration.AbstractMigratable` in the `platform-migratable-api` implements common boilerplate code required
when implementing `org.codice.${ddf-branding-lowercase}.migration.Migratable` and should be extended when creating a `org.codice.${ddf-branding-lowercase}.migration.Migratable`.

=== Do Not Use FileBackedOutputStream

It is recommended to avoid using `com.google.common.io.FileBackedOutputStream` (FBOS). FBOS can create temporary files that are not automatically
removed when FBOS is closed. Use `org.codice.ddf.platform.util.TemporaryFileBackedOutputStream` (TFBOS). TFBOS provides the same method calls as FBOS, but
will remove temporary files when it is closed.
