
This section supports integration of this application with external frameworks.

=== Platform UI Settings

The Platform UI Settings are the system-wide configuration settings used throughout ${branding} to customize certain aspects of the ${branding} UI.

==== Configuration

The configurable properties for the platform-wide configuration are accessed from *${ddf-platform} -> Configuration -> Platform UI Configuration* in the Admin Console.

==== Configurable Properties

[cols="6" options="header"]
|===

|Title
|Property
|Type
|Description
|Default Value
|Required

|Enable System Usage Message
|`systemUsageEnabled`
|Boolean
|Turns on a system usage message, which is shown when the Search Application is opened
|
|yes

|System Usage Message Title
|`systemUsageTitle`
|String
|A title for the system usage Message when the application is opened
|
|yes

|System Usage Message
|`systemUsageMessage`
|String
|A system usage message to be displayed to the user each time the user opens the application
|
|yes

|Show System Usage Message once per session
|`systemUsageOncePerSession`
|Boolean
|With this selected, the system usage message will be shown once for each browser session. Uncheck this to have the usage message appear every time the search window is opened or refreshed.
|true
|yes

|Header
|`header`
|String
|Specifies the header text to be rendered on all pages.
|
|yes

|Footer
|`footer`
|String
|Specifies the footer text to be rendered on all pages.
|
|yes

|Text Color
|`color`
|String
|Specifies the Text Color of the Header and Footer. Use html css colors or `#rrggbb`.
|
|yes

|Background Color
|`background`
|String
|Specifies the Background Color of the Header and Footer. Use html css colors or `#rrggbb`.
|
|yes

|===

=== Landing Page

The ${branding} landing page offers a starting point and general information for a ${branding} node.
It is accessible at `/(index|home|landing(.htm|html))`.

==== Configuration

The configurable properties for the landing page configuration are accessed from *${ddf-platform} -> Landing Page* in the Admin UI.

==== Configurable Properties

[cols="6" options="header"]
|===

|Title
|Property
|Type
|Description
|Default Value
|Required

|Description
|`description`
|String
|Specifies the description to display on the landing page.
|As a common data layer, ${branding} provides secure enterprise-wide data access for both users and systems.
|yes

|Phone Number
|`phone`
|String
|Specifies the phone number to display on the landing page.
|
|yes

|Email Address
|`email`
|String
|Specifies the email address to display on the landing page.
|
|yes

|External Web Site
|`externalUrl`
|String
|Specifies the external web site URL to display on the landing page.
|
|yes

|Announcements
|`announcements`
|String
|Announcements that will be displayed on the landing page. Can be prefixed with a date of the form `mm/dd/yy`, leading zeroes not required.
|
|yes

|Branding Background
|`background`
|String
|Specifies the landing page Background Color. Use html css colors or `#rrggbb`.
|
|yes

|Branding Foreground
|`foreground`
|String
|Specifies the landing page Foreground Color. Use html css colors or `#rrggbb`.
|
|yes

|Branding Logo
|`logo`
|String
|Specifies the landing page Logo.  Use a base64 encoded image. You can use openssl to encode an image. +
`openssl base64 -in <infile> -out <outfile>` +
The contents of `<outfile>` should be pasted into this field.
|
|yes

|===

=== ${ddf-branding} Mime Framework

==== Mime Type Mapper

The MimeTypeMapper is the entry point in ${branding} for resolving file extensions to mime types, and vice versa.

`MimeTypeMappers` are used by the `ResourceReader` to determine the file extension for a given mime type in aid of retrieving a product.
`MimeTypeMappers` are also used by the `FileSystemProvider` in the Catalog Framework to read a file from the content file repository.

The `MimeTypeMapper` maintains a list of all of the `MimeTypeResolvers` in ${branding}.

The `MimeTypeMapper` accesses each `MimeTypeResolver` according to its priority until the provided file extension is successfully mapped to its corresponding mime type.
If no mapping is found for the file extension, `null` is returned for the mime type. 
Similarly, the `MimeTypeMapper` accesses each `MimeTypeResolver` according to its priority until the provided mime type is successfully mapped to its corresponding file extension.
If no mapping is found for the mime type, `null` is returned for the file extension.

==== Included Mime Type Mappers

===== ${ddf-branding} Mime Type Mapper

The ${ddf-branding} Mime Type Mapper is the core implementation of the ${ddf-branding} Mime API.
It provides access to all `MimeTypeResolvers` within ${branding}, which provide mapping of mime types to file extensions and file extensions to mime types.

===== Installing and Uninstalling

The ${ddf-branding} Mime Type Mapper is bundled in the `mime-core` feature, which is installed by default, as part of the `mime-core-app` application.

===== Configuring

There is no configuration needed for this feature.

==== Mime Type Resolver

A `MimeTypeResolver` is a ${branding} service that can map a file extension to its corresponding mime type and, conversely, can map a mime type to its file extension.

`MimeTypeResolvers` are assigned a priority (0-100, with the higher the number indicating the higher priority).
This priority is used to sort all of the `MimeTypeResolvers` in the order they should be checked for mapping a file extension to a mime type (or vice versa).
This priority also allows custom `MimeTypeResolvers` to be invoked before default `MimeTypeResolvers` if the custom resolver's priority is set higher than the default's.

`MimeTypeResolvers` are not typically invoked directly.
Rather, the `MimeTypeMapper` maintains a list of `MimeTypeResolvers` (sorted by their priority) that it invokes to resolve a mime type to its file extension (or to resolve a file extension to its mime type).

===== Tika Mime Type Resolver

The `TikaMimeTypeResolver` is a `MimeTypeResolver` that is implemented using the Apache Tika open source product.

Using the Apache Tika content analysis toolkit, the `TikaMimeTypeResolver` provides support for resolving over 1300 mime types.

The `TikaMimeTypeResolver` is assigned a default priority of `-1` to insure that it is always invoked last by the `MimeTypeMapper`.
This insures that any custom `MimeTypeResolvers` that may be installed will be invoked before the `TikaMimeTypeResolver`.

====== Using

The `TikaMimeTypeResolver` provides the bulk of the default mime type support for ${branding}.

====== Installing and Uninstalling

The `TikaMimeTypeResolver` is bundled as the `mime-tika-resolver` feature in the `mime-tika-app` application.

This feature is installed by default.

====== Configuring

There are no configuration properties for the `mime-tika-resolver`.

====== Implementation Details

*Exported Services*

[cols="3" options="header"]
|===

|Registered Interface
|Service Property
|Value

|`${ddf-branding-lowercase}.mime.MimeTypeResolver`
|
|`tika-mimetypes.xml`

|===

===== Custom Mime Type Resolver

The Custom Mime Type Resolver is a `MimeTypeResolver` that defines the custom mime types that ${branding} will support out of the box.
These are mime types not supported by the default `TikaMimeTypeResolver`.

Currently, the custom mime types supported by the Custom Mime Type Resolver that are configured for ${branding} out-of-the-box are:

[cols="1,2" options="header"]
|===

|File Extension
|Mime Type

|nitf
|image/nitf

|ntf
|image/nitf

|json
|json=application/json;id=geojson

|===

New custom mime type resolver mappings can be added using the Admin Console.

As a `MimeTypeResolver`, the Custom Mime Type Resolver will provide methods to map the file extension to the corresponding mime type, and vice versa.

====== Using

The Custom Mime Type Resolver is used when mime types need to be added that are not supported by ${branding} out of the box.
By adding custom mime type resolvers to ${branding}, new content with that mime type can be processed by ${branding}.

====== Installing and Uninstalling

One Custom Mime Type Resolver is configured and installed out of the box for the `image/nitf` mime type.
This custom resolver is bundled in the `mime-core-app` application and is part of the `mime-core` feature.

Additional Custom Mime Type Resolvers can be added for other custom mime types.

====== Configuring

The configurable properties for the Custom Mime Type Resolver are accessed from the *MIME Custom Types* configuration in the Admin Console.

*Managed Service Factory PID*

* `${ddf-branding}_Custom_Mime_Type_Resolver`

.Configurable Properties
[cols="1,1,1,3,1,1" options="header"]
|===
|Title
|Property
|Type
|Description
|Default Value
|Required

|Resolver Name
|`name`
|String
|Unique name for the custom mime type resolver.
|N/A
|Yes

|Priority
|`priority`
|Integer
|Execution priority of the resolver.

Range is 0 to 100, with 100 being the highest priority.
|10
|Yes

|File Extensions to Mime Types
|`customMimeTypes`
|String
|Comma-delimited list of key/value pairs where key is the file extension and value is the mime type, e.g., `nitf=image/nitf`.
|N/A
|Yes

|===

====== Implementation Details

.Imported Services
[cols="4,1,1" options="header"]
|===

|Registered Interface
|Availability
|Multiple

|`${ddf-branding-lowercase}.catalog.transform.InputTransformer`
|optional
|true

|`${ddf-branding-lowercase}.catalog.transform.QueryResponseTransformer`
|optional
|true

|`${ddf-branding-lowercase}.mime.MimeTypeResolver`
|optional
|true

|===

.Exported Services
[cols="4,2,1" options="header"]
|===

|Registered Interface
|Service Property
|Value

|`${ddf-branding-lowercase}.mime.MimeTypeToTransformerMapper`
|
|
 
|`${ddf-branding-lowercase}.mime.MimeTypeMapper`
|
|
 
|===

=== Security Core API

The Security Core API contains all of the ${branding} Security Framework APIs that are used to perform security operations within ${branding}.


==== Install and Uninstall

The Security Services App installs this bundle by default.
Do not uninstall the Security Core API as it is integral to system function and all of the other security services depend upon it.

==== Configuration

None

==== Implementation Details

===== Imported Services

None

===== Exported Services

None

=== Compression Services

The compression services offer CXF-based message encoding that allows for compression of outgoing and incoming messages.


==== Install and Uninstall

The compression services are not installed by default within the platform application. Installing them can be done by doing:

[source]
----
feature:install compression-[DESIRED COMPRESSION SERVICE]
----

Where [DESIRED COMPRESSION SERVICE] is one of the following:

[cols="2,6" options="header"]
|===

|Compression Type
|Description

|`exi`
|Adds Efficient XML Interchange (EXI) support to outgoing responses. EXI is an W3C standard for XML encoding that shrinks xml to a smaller size than normal GZip compression. More information is available at http://www.w3.org/XML/EXI/[EXI].

|`gzip`
|Adds GZip compression to in and outgoing messages through CXF components. Code comes with CXF.

|===

[WARNING]
====
Due to the way CXF features work, the compression services either need to be installed BEFORE the desired CXF service is started or the CXF service needs to be refreshed / restarted after the compression service is installed.
====

==== Configuration

None

==== Implementation Details

===== Imported Services

None

===== Exported Services

[cols="2,3,2,1" options="header"]
|===
|Registered Interface
|Implemented Class(es)
|Service Property
|Value

|`org.apache.cxf.feature.Feature`
|`${ddf-branding-lowercase}.compression.exi.EXIFeature`

`org.apache.cxf.transport.common.gzip.GZIPFeature`
|N/A
|N/A

|===
