
The ${ddf-platform} application is considered to be a core application of the distribution.
The Platform application provides the fundamental building blocks that the distribution needs to run.
These building blocks include subsets of:

* http://karaf.apache.org/[Karaf], 
* http://cxf.apache.org/CXF[CXF],  and 
* http://camel.apache.org/[Camel]. 

A Command Scheduler is also included as part of the Platform application.
The Command Scheduler allows users to schedule Command Line Shell Commands to run at certain specified intervals.

=== Using ${ddf-platform} Application

The Platform application is a core building block for any application and should be referenced for its core component versions so that developers can ensure compatibility with their own applications.
The Command Scheduler included in the Platform application should be for the convenience of a "platform independent" method of running certain commands, such as backing up data or logging settings.

=== Installing and Uninstalling Platform

==== Prerequisites

None.

==== Installing ${ddf-platform}

The Platform application is installed by default on a standard installation.

==== Configuring ${ddf-platform}
 
[cols="1,1,2" options="header"]
|===
|Configuration
|ID
|Description

|Landing Page
|`org.codice.${ddf-branding-lowercase}.distribution.landing-page.properties`
|Customize elements seen on landing page.

|MIME Custom Types
|`${ddf-branding}_Custom_Mime_Type_Resolver`
|Add or configure resolvers to identify files by type.

|Metrics Reporting
|`MetricsReporting`
|Allocate resources for metrics collection.

|Persistent Store
|`org.codice.${ddf-branding-lowercase}.persistence.internal.PersistentStoreImpl`
|Set URL for Solr server used as persistant store.

|Platform Command Scheduler
|`${ddf-branding-lowercase}.platform.scheduler.Command`
|Schedule shell commands to run periodically.

|Platform UI Configuration
|`${ddf-branding-lowercase}.platform.ui.config`
|

|===

==== Country Code Converter

In the Platform Application, you have the option to install a feature called `platform-country-local`.
This feature provides an OSGi service to convert country codes into various formats by performing a local lookup.

This feature works by loading in a static properties file containing the FIPS 10-4 to ISO 3166-1 alpha 3 country code mappings and builds multi maps from the mappings to perform the conversions. The mappings file can be found at: ${branding-lowercase}.home/etc/fipsToIso.properties and should only be modified in the case the mappings would ever change. If the country code mappings file needs to be modified, it's required to restart the feature's bundle in order for the service to pick up on the new changes.
The mappings file contains each mapping in the following format, where the country on the left side of the equals sign is FIPS 10-4 and the country or countries on the right side of the equals sign is ISO 3166-1 alpha 3, and a new line separating each mapping:

* If there is a single FIPS 10-4 country that maps to a single ISO 3166-1 alpha 3 country: AB=ABC

* If there is a single FIPS 10-4 country that maps to multiple ISO 3166-1 alpha 3 countries: ZZ=ZZZ,YYY

===== Installing Country Code Converter

The Country Code Converter is not installed by default with a standard installation.
To install:

. Navigate to the *${admin-console}*.
. Select the *${ddf-platform}* application.
. Select the *Features* tab.
. Install the `platform-country-local` feature.