/**
 * Copyright (c) Codice Foundation
 *
 * This is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser
 * General Public License as published by the Free Software Foundation, either version 3 of the
 * License, or any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
 * even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details. A copy of the GNU Lesser General Public License
 * is distributed along with this program and can be found at
 * <http://www.gnu.org/licenses/lgpl.html>.
 *
 **/
type HTMLAttributes = {
  about?: any
  acceptCharset?: any
  accessKey?: any
  allowFullScreen?: any
  allowTransparency?: any
  autoComplete?: any
  autoFocus?: any
  autoPlay?: any
  capture?: any
  cellPadding?: any
  cellSpacing?: any
  charSet?: any
  classID?: any
  className?: any
  colSpan?: any
  contentEditable?: any
  contextMenu?: any
  crossOrigin?: any
  dangerouslySetInnerHTML?: any
  datatype?: any
  dateTime?: any
  dir?: any
  draggable?: any
  encType?: any
  formAction?: any
  formEncType?: any
  formMethod?: any
  formNoValidate?: any
  formTarget?: any
  frameBorder?: any
  hidden?: any
  hrefLang?: any
  htmlFor?: any
  httpEquiv?: any
  icon?: any
  id?: any
  inlist?: any
  inputMode?: any
  is?: any
  itemID?: any
  itemProp?: any
  itemRef?: any
  itemScope?: any
  itemType?: any
  keyParams?: any
  keyType?: any
  lang?: any
  marginHeight?: any
  marginWidth?: any
  maxLength?: any
  mediaGroup?: any
  minLength?: any
  noValidate?: any
  onBlur?: any
  onFocus?: any
  onKeyDown?: any
  onKeyPress?: any
  onKeyUp?: any
  prefix?: any
  property?: any
  radioGroup?: any
  readOnly?: any
  resource?: any
  role?: any
  rowSpan?: any
  scoped?: any
  seamless?: any
  security?: any
  spellCheck?: any
  srcDoc?: any
  srcLang?: any
  srcSet?: any
  style?: any
  suppressContentEditableWarning?: any
  tabIndex?: any
  title?: any
  typeof?: any
  unselectable?: any
  useMap?: any
  vocab?: any
  wmode?: any
  coords?: any
  download?: any
  href?: any
  name?: any
  rel?: any
  shape?: any
  target?: any
  type?: any
  onClick?: any
  alt?: any
  height?: any
  width?: any
  controls?: any
  loop?: any
  muted?: any
  preload?: any
  src?: any
  size?: any
  cite?: any
  disabled?: any
  form?: any
  value?: any
  span?: any
  open?: any
  accept?: any
  action?: any
  method?: any
  onChange?: any
  onInput?: any
  onInvalid?: any
  onSubmit?: any
  scrolling?: any
  cols?: any
  rows?: any
  profile?: any
  manifest?: any
  sandbox?: any
  sizes?: any
  autoCapitalize?: any
  autoCorrect?: any
  autoSave?: any
  checked?: any
  defaultChecked?: any
  defaultValue?: any
  list?: any
  max?: any
  min?: any
  multiple?: any
  pattern?: any
  placeholder?: any
  required?: any
  results?: any
  step?: any
  challenge?: any
  color?: any
  integrity?: any
  media?: any
  nonce?: any
  scope?: any
  content?: any
  high?: any
  low?: any
  optimum?: any
  data?: any
  reversed?: any
  start?: any
  label?: any
  selected?: any
  async?: any
  defer?: any
  summary?: any
  headers?: any
  wrap?: any
  default?: any
  kind?: any
  playsInline?: any
  poster?: any
  accentHeight?: any
  accumulate?: any
  additive?: any
  alignmentBaseline?: any
  allowReorder?: any
  alphabetic?: any
  amplitude?: any
  arabicForm?: any
  ascent?: any
  attributeName?: any
  attributeType?: any
  autoReverse?: any
  azimuth?: any
  baseFrequency?: any
  baseProfile?: any
  baselineShift?: any
  bbox?: any
  begin?: any
  bias?: any
  by?: any
  calcMode?: any
  capHeight?: any
  clip?: any
  clipPath?: any
  clipPathUnits?: any
  clipRule?: any
  colorInterpolation?: any
  colorInterpolationFilters?: any
  colorProfile?: any
  colorRendering?: any
  contentScriptType?: any
  contentStyleType?: any
  cursor?: any
  cx?: any
  cy?: any
  d?: any
  decelerate?: any
  descent?: any
  diffuseConstant?: any
  direction?: any
  display?: any
  divisor?: any
  dominantBaseline?: any
  dur?: any
  dx?: any
  dy?: any
  edgeMode?: any
  elevation?: any
  enableBackground?: any
  end?: any
  exponent?: any
  externalResourcesRequired?: any
  fill?: any
  fillOpacity?: any
  fillRule?: any
  filter?: any
  filterRes?: any
  filterUnits?: any
  floodColor?: any
  floodOpacity?: any
  focusable?: any
  fontFamily?: any
  fontSize?: any
  fontSizeAdjust?: any
  fontStretch?: any
  fontStyle?: any
  fontVariant?: any
  fontWeight?: any
  format?: any
  from?: any
  fx?: any
  fy?: any
  g1?: any
  g2?: any
  glyphName?: any
  glyphOrientationHorizontal?: any
  glyphOrientationVertical?: any
  glyphRef?: any
  gradientTransform?: any
  gradientUnits?: any
  hanging?: any
  horizAdvX?: any
  horizOriginX?: any
  ideographic?: any
  imageRendering?: any
  in?: any
  in2?: any
  intercept?: any
  k?: any
  k1?: any
  k2?: any
  k3?: any
  k4?: any
  kernelMatrix?: any
  kernelUnitLength?: any
  kerning?: any
  keyPoints?: any
  keySplines?: any
  keyTimes?: any
  lengthAdjust?: any
  letterSpacing?: any
  lightingColor?: any
  limitingConeAngle?: any
  local?: any
  markerEnd?: any
  markerHeight?: any
  markerMid?: any
  markerStart?: any
  markerUnits?: any
  markerWidth?: any
  mask?: any
  maskContentUnits?: any
  maskUnits?: any
  mathematical?: any
  mode?: any
  numOctaves?: any
  offset?: any
  opacity?: any
  operator?: any
  order?: any
  orient?: any
  orientation?: any
  origin?: any
  overflow?: any
  overlinePosition?: any
  overlineThickness?: any
  paintOrder?: any
  panose1?: any
  pathLength?: any
  patternContentUnits?: any
  patternTransform?: any
  patternUnits?: any
  pointerEvents?: any
  points?: any
  pointsAtX?: any
  pointsAtY?: any
  pointsAtZ?: any
  preserveAlpha?: any
  preserveAspectRatio?: any
  primitiveUnits?: any
  r?: any
  radius?: any
  refX?: any
  refY?: any
  renderingIntent?: any
  repeatCount?: any
  repeatDur?: any
  requiredExtensions?: any
  requiredFeatures?: any
  restart?: any
  result?: any
  rotate?: any
  rx?: any
  ry?: any
  scale?: any
  seed?: any
  shapeRendering?: any
  slope?: any
  spacing?: any
  specularConstant?: any
  specularExponent?: any
  speed?: any
  spreadMethod?: any
  startOffset?: any
  stdDeviation?: any
  stemh?: any
  stemv?: any
  stitchTiles?: any
  stopColor?: any
  stopOpacity?: any
  strikethroughPosition?: any
  strikethroughThickness?: any
  string?: any
  stroke?: any
  strokeDasharray?: any
  strokeDashoffset?: any
  strokeLinecap?: any
  strokeLinejoin?: any
  strokeMiterlimit?: any
  strokeOpacity?: any
  strokeWidth?: any
  surfaceScale?: any
  systemLanguage?: any
  tableValues?: any
  targetX?: any
  targetY?: any
  textAnchor?: any
  textDecoration?: any
  textLength?: any
  textRendering?: any
  to?: any
  transform?: any
  u1?: any
  u2?: any
  underlinePosition?: any
  underlineThickness?: any
  unicode?: any
  unicodeBidi?: any
  unicodeRange?: any
  unitsPerEm?: any
  vAlphabetic?: any
  vHanging?: any
  vIdeographic?: any
  vMathematical?: any
  values?: any
  vectorEffect?: any
  version?: any
  vertAdvY?: any
  vertOriginX?: any
  vertOriginY?: any
  viewBox?: any
  viewTarget?: any
  visibility?: any
  widths?: any
  wordSpacing?: any
  writingMode?: any
  x?: any
  x1?: any
  x2?: any
  xChannelSelector?: any
  xHeight?: any
  xlinkActuate?: any
  xlinkArcrole?: any
  xlinkHref?: any
  xlinkRole?: any
  xlinkShow?: any
  xlinkTitle?: any
  xlinkType?: any
  xmlBase?: any
  xmlLang?: any
  xmlSpace?: any
  xmlns?: any
  xmlnsXlink?: any
  y?: any
  y1?: any
  y2?: any
  yChannelSelector?: any
  z?: any
  zoomAndPan?: any
  a?: any
  abbr?: any
  address?: any
  area?: any
  article?: any
  aside?: any
  audio?: any
  b?: any
  base?: any
  bdi?: any
  bdo?: any
  blockquote?: any
  body?: any
  br?: any
  button?: any
  canvas?: any
  caption?: any
  code?: any
  col?: any
  colgroup?: any
  datalist?: any
  dd?: any
  del?: any
  details?: any
  dfn?: any
  dialog?: any
  div?: any
  dl?: any
  dt?: any
  em?: any
  embed?: any
  fieldset?: any
  figcaption?: any
  figure?: any
  footer?: any
  h1?: any
  h2?: any
  h3?: any
  h4?: any
  h5?: any
  h6?: any
  head?: any
  header?: any
  hgroup?: any
  hr?: any
  html?: any
  i?: any
  iframe?: any
  img?: any
  input?: any
  ins?: any
  kbd?: any
  keygen?: any
  legend?: any
  li?: any
  link?: any
  main?: any
  map?: any
  mark?: any
  math?: any
  menu?: any
  menuitem?: any
  meta?: any
  meter?: any
  nav?: any
  noscript?: any
  object?: any
  ol?: any
  optgroup?: any
  option?: any
  output?: any
  p?: any
  param?: any
  picture?: any
  pre?: any
  progress?: any
  q?: any
  rb?: any
  rp?: any
  rt?: any
  rtc?: any
  ruby?: any
  s?: any
  samp?: any
  script?: any
  section?: any
  select?: any
  slot?: any
  small?: any
  source?: any
  strong?: any
  sub?: any
  sup?: any
  svg?: any
  table?: any
  tbody?: any
  td?: any
  template?: any
  textarea?: any
  tfoot?: any
  th?: any
  thead?: any
  time?: any
  tr?: any
  track?: any
  u?: any
  ul?: any
  var?: any
  video?: any
  wbr?: any
  altGlyph?: any
  altGlyphDef?: any
  altGlyphItem?: any
  animate?: any
  animateColor?: any
  animateMotion?: any
  animateTransform?: any
  circle?: any
  'color-profile'?: any
  defs?: any
  desc?: any
  ellipse?: any
  feBlend?: any
  feColorMatrix?: any
  feComponentTransfer?: any
  feComposite?: any
  feConvolveMatrix?: any
  feDiffuseLighting?: any
  feDisplacementMap?: any
  feDistantLight?: any
  feFlood?: any
  feFuncA?: any
  feFuncB?: any
  feFuncG?: any
  feFuncR?: any
  feGaussianBlur?: any
  feImage?: any
  feMerge?: any
  feMergeNode?: any
  feMorphology?: any
  feOffset?: any
  fePointLight?: any
  feSpecularLighting?: any
  feSpotLight?: any
  feTile?: any
  feTurbulence?: any
  font?: any
  'font-face'?: any
  'font-face-format'?: any
  'font-face-name'?: any
  'font-face-src'?: any
  'font-face-uri'?: any
  foreignObject?: any
  g?: any
  glyph?: any
  hkern?: any
  image?: any
  line?: any
  linearGradient?: any
  marker?: any
  metadata?: any
  'missing-glyph'?: any
  mpath?: any
  path?: any
  polygon?: any
  polyline?: any
  radialGradient?: any
  rect?: any
  set?: any
  stop?: any
  switch?: any
  symbol?: any
  text?: any
  textPath?: any
  tref?: any
  tspan?: any
  use?: any
  view?: any
  vkern?: any
}

export default HTMLAttributes
