
== Overview

The DDF Standard Search UI application allows a user to search for records in the local Catalog (provider) and federated sources. Results of the search are returned in HTML format and are displayed on a globe, providing a visual representation of where the records were found.

This page supports integration of this application with external frameworks.


== CometD
The Standard Search UI utilizes http://cometd.org[CometD] to communicate with the DDF. This protocol is used to execute searches, retrieve results, and receive notifications.

For an example of using CometD within a webapp see: `distribution/sdk/sample-cometd/`

=== Query

Queries can be executed over CometD using the `/service/query` channel. Query messages are json formatted and use cql alongside several other parameters.

[cols="1,3,1", options="header"]
.Query Parameters
|===
|Parameter Name|Description|Required

|src
|Catalog Source
|No

|cql
|CQL query
|Yes

|sort
|Sort Type
|No

|id
|Query ID (Should be a uuid), This determines the channel that the query results will be returned on.
|Yes
|===

Before a query is published the client should subscribe to the channel that will be passed in to the `id` field in order to receive query results once the query is executed.

For example if the following id was generated `3b19bc9c-2155-4ca6-bae8-65a9c8e373f6`, the client should subscribe to `/3b19bc9c-2155-4ca6-bae8-65a9c8e373f6`

Then the following example query could be executed:

[source,json]
./service/query
----
{
  "cql":"(\"anyText\" ILIKE 'foo')",
  "id":"3b19bc9c-2155-4ca6-bae8-65a9c8e373f6"
}
----

This would return any results matching the text `foo` on the `/3b19bc9c-2155-4ca6-bae8-65a9c8e373f6` channel

=== Notifications

Notifications are published by the server on several notification channels depending on the type.

* subscribing to `/ddf/notifications/**` will cause the client to receive all notifications.
* subscribing to `/ddf/notifications/catalog/downloads` will cause the client to only receive notifications of downloads.

==== Persistence

Notifications are persisted between sessions, however due to the nature of cometd communications, they will not be visible at first connection/subscription to `/ddf/notifications/**`.

In order to retrieve notifications that were persisted or may have occurred since the previous session a client simply must publish an empty json message, `{}` to `/ddf/notifications`.
This will return all existing notifications to the user.
