:type: plugin
:status: published
:title: GeoCoder Plugin
:link: {architecture-prefix}geocoder_plugin
:plugintypes: preingest
:summary: Populates the `Location.COUNTRY_CODE` attribute if the Metacard has an associated location.

The GeoCoder Plugin is a pre-ingest plugin that is responsible for populating the Metacard's `Location.COUNTRY_CODE` attribute if the Metacard has an associated location.
If there is a valid country code for the Metacard, it will be in ISO 3166-1 alpha-3 format.
If the metacard's country code is already populated, the plugin will *not* override it.
The GeoCoder relies on either the WebService or <<{reference-prefix}offline_gazetteer_service,Offline Gazetteer>> to retrieve country code information.

[WARNING]
====
For a polygon or polygons, this plugin takes the center point of the bounding box to assign the country code.
====

===== Installing the GeoCoder Plugin

The GeoCoder Plugin is installed by default with the ${ddf-spatial} application, when the WebService or Offline Gazetteer is started.

===== Configuring the GeoCoder Plugin

To configure the GeoCoder Plugin:

. Navigate to the *${admin-console}*.
. Select *${ddf-spatial}* application.
. Select *Configuration* tab.
. Select *GeoCoder Plugin*.

See <<{reference-prefix}org.codice.ddf.spatial.geocoding.plugin.GeoCoderPlugin,GeoCoder Plugin configurations>> for all possible configurations.
