:type: plugin
:status: published
:title: Metacard Ingest Network Plugin
:link: {architecture-prefix}metacard_ingest_network_plugin
:plugintypes: preauthorization
:summary: Adds attributes for network info from ingest request.

The Metacard Ingest Network Plugin allows the conditional insertion of new attributes on metacards during ingest based on network information from the ingest request; including IP address and hostname.

For the extent of this section, a 'rule' will refer to a configured, single instance of this plugin.

===== Related Components to the Metacard Ingest Network Plugin

* <<_client_info_plugin,Client Info Plugin>>

===== Installing the Metacard Ingest Network Plugin

The Metacard Ingest Network Plugin is installed by default during a standard installation in the ${ddf-catalog} application.

===== Configuring the Metacard Ingest Network Plugin

To configure the Metacard Ingest Network Plugin:

* Navigate to the *${admin-console}*.
* Select the ${ddf-catalog} application.
* Select the *Configuration* tab.
* Select the label _Metacard Ingest Network Plugin_ to setup a network rule.

See <<{reference-prefix}org.codice.ddf.catalog.plugin.metacard.MetacardIngestNetworkPlugin,Metacard Ingest Network Plugin configurations>> for all possible configurations.

Multiple instances of the plugin can be configured by clicking on its configuration title within the configuration tab of the ${ddf-catalog} app.
Each instance represents a conditional statement, or a 'rule', that gets evaluated for each ingest request.
For any request that meets the configured criteria of a rule, that rule will attempt to transform its list of key-value pairs to become new attributes on all metacards in that request.

The rule is divided into two fields: "Criteria" and "Expected Value".
The "Criteria" field features a drop-down list containing the four elements for which equality can be tested:

* IP Address of where the ingest request came from
* Host Name of where the ingest request came from
* Scheme that the ingest request arrived on, for example, _http_ vs _https_
* Context Path that the ingest request arrived on, for example, _/services/catalog_

In order for a rule to evaluate to true and the attributes be applied, the value in the "Expected Value" field must be an exact match to the actual value of the selected criteria.
For example, if the selected criteria is "IP Address" with an expected value of "192.168.0.1", the rule only evaluates to true for ingest requests coming from "192.168.0.1" and nowhere else.

.Check for IPv6
IMPORTANT: Verify your system's IP configuration. Rules using "IP Address" may need to be written in IPv6 format.

The key-value pairs within each rule should take the following form: "key = value" where the "key" is the name of the attribute and the "value" is the value assigned to that attribute. Whitespace is ignored unless it is within the key or value. Multi-valued attributes can be expressed in comma-separated format if necessary.

.Examples of Valid Attribute Assignments
----
contact.contributor-name = John Doe
contact.contributor-email = john.doe@example.net
language = English
language = English, French, German
security.access-groups = SJ202, SR 101, JS2201
----


====== Useful Attributes

The following table provides some useful attributes that may commonly be set by this plugin:

.Useful Attributes
|===
|Attribute Name |Expected Format |Multi-Valued

|expiration
|ISO DateTime
|no

|description
|Any String
|no

|metacard.owner
|Any String
|no

|language
|Any String
|yes

|security.access-groups
|Any String
|yes

|security.access-individuals
|Any String
|yes
|===

===== Usage Limitations of the Metacard Ingest Network Plugin

* This plugin only works for ingest (create requests) performed over a network; data ingested via command line does not get processed by this plugin.
* Any attribute that is already set on the metacard will not be overwritten by the plugin.
* The order of execution is not guaranteed. For any rule configuration where two or more rules add different values for the same attribute, it is undefined what the final value for that attribute will be in the case where more than one of those rules evaluates to true.
