:type: plugin
:status: published
:title: Video Thumbnail Plugin
:link: _video_thumbnail_plugin
:plugintypes: postcreatestorage, postupdatestorage
:summary: Generates thumbnails for video files.

The Video Thumbnail Plugin provides the ability to generate thumbnails for video files stored in the Content Repository.

It is an implementation of both the `PostCreateStoragePlugin` and `PostUpdateStoragePlugin` interfaces. When installed, it is invoked by the Catalog Framework immediately after a content item has been created or updated by the Storage Provider.

This plugin uses a custom 32-bit LGPL build of https://ffmpeg.org/[FFmpeg] (a video processing program) to generate thumbnails. When this plugin is installed, it places the FFmpeg executable appropriate for the current operating system in `${home_directory}/bin_third_party/ffmpeg`. When invoked, this plugin runs the FFmpeg binary in a separate process to generate the thumbnail. The `${home_directory}/bin_third_party/ffmpeg` directory is deleted when the plugin is uninstalled.

[NOTE]
====
Prebuilt FFmpeg binaries are provided for Linux, Mac, and Windows only.
====

===== Installing the Video Thumbnail Plugin

The Video Thumbnail Plugin is installed by default with a standard installation in the ${ddf-catalog} application.

===== Configuring the Video Thumbnail Plugin

To configure the Video Thumbnail Plugin:

. Navigate to the *${admin-console}*.
. Select the *${ddf-catalog}* application.
. Select the *Configuration* tab.
. Select the *Video Thumbnail Plugin*.

See <<{reference-prefix}org.codice.ddf.catalog.content.plugin.video.VideoThumbnailPlugin,Video Thumbnail Plugin configurations>> for all possible configurations.
