:title: ${ddf-spatial}
:status: published
:type: applicationReference
:summary: Provides KML transformer and a KML network link endpoint that allows a user to generate a View-based KML Query Results Network Link.
:order: 11

== {title} Application Reference

The ${ddf-spatial} Application provides KML transformer and a KML network link endpoint that allows a user to generate a View-based KML Query Results Network Link.

=== Offline Gazetteer Service

In the ${ddf-spatial} Application, the `offline-gazetteer` is installed by default.
This feature enables you to use an offline source of GeoNames data (as an alternative to the GeoNames Web service enabled by the `webservice-gazetteer` feature) to perform searches via the gazetteer search box in the Search UI.

By default a small set of GeoNames data is included with the offline gazetteer. The GeoNames data is stored as metacards in the core catalog and are tagged with `geonames` and `gazetteer`. This collection of GeoNames metacards can be expanded or updated by using the `gazetteer:update` command.

==== ${ddf-spatial} Gazetteer Console Commands

The `gazetteer` commands provide the ability to interact with the local GeoNames metacard collection in the core catalog. These GeoNames metacards are used by the `offline-gazetteer` feature, which is an optional feature available in this application and is explained above. Note that these commands are only available if the `offline-gazetteer` feature is installed.

.Gazetteer Command Descriptions
[cols="2,8a,1m" options="header"]
|===
|Command
|Description
|Usage

|`update`
|Adds new gazetteer metacards to the core catalog. Entries can be a URL or local file path to GeoNames data or a local file path to GeoJSON data (GeoJSON URLs are not supported). Currently .txt and .zip files are supported for manual GeoNames entries and .geo.json files are supported for manual GeoJSON entries. GeoNames data can be manually downloaded from http://download.geonames.org/export/dump, where the absolute path of the file would be passed as an argument to the command (ex. /Users/johndoe/Downloads/AU.zip). Entries can also be automatically downloaded from http://download.geonames.org/export/dump by passing the country code as an argument to the command (ex. AU) which will add the country as GeoNames metacards in the core catalog. The full list of country codes available can be found in http://download.geonames.org/export/dump/countryInfo.txt. Using the argument "all" will download all of the current country codes (this process may take some time). In addition to country codes, GeoNames also provides entries for cities based on their population sizes. The arguments "cities1000", "cities5000", and "cities15000" will add cities to the index that have at least 1000, 5000, or 15000 people respectively.

The `-c` or `--create` flag can be used to clear out the existing gazetteer metacards before adding new entries.
|gazetteer:update

|===

===  ${ddf-spatial} Prerequisites

To use the ${ddf-spatial} Application, the following apps/features must be installed:

* ${ddf-platform}
* ${ddf-catalog}

===  Installing ${ddf-spatial}

Install the ${ddf-spatial} application through the ${admin-console}.

. Navigate to the *${admin-console}*.
. Select the *System* tab.
. Select the *Features* tab.
. Install the `spatial-app` feature.
