:type: plugin
:status: published
:title: XML Attribute Security Policy Plugin
:link: {developing-prefix}xml_attribute_security_policy_plugin
:plugintypes: policy
:summary: Finds security attributes contained in a metacard's metadata.

The ((XML Attribute Security Policy Plugin)) parses XML metadata contained within a metacard for security attributes on any number of XML elements in the metadata.
The configuration for the plugin contains one field for setting the XML elements that are parsed for security attributes and the other two configurations contain the XML attributes that are pulled off of those elements.
The *Security Attributes (union)* field computes the union of values for each attribute defined and the *Security Attributes (intersection)* field computes the intersection of values for each attribute defined.

== Installing the XML Attribute Security Policy Plugin

The XML Attribute Security Policy Plugin is installed by default with a standard installation in the ${ddf-security} application.

