:title: Metrics
:type: architectureIntro
:status: published
:children: Metrics Collection Application, Metrics Reporting Application
:order: 04
:summary: Introduction to Metrics.

${branding} includes a system of data-collection to enable monitoring system health, user interactions, and overall system performance: *Metrics Collection*.

The Metrics Collection Application collects data for all of the pre-configured metrics in ${branding} and stores them in custom JMX Management Bean (MBean) attributes.
Samples of each metric's data is collected every 60 seconds and stored in the `${home_directory}/data/metrics` directory with each metric stored in its own `.rrd` file.
Refer to the Metrics Reporting Application for how the stored metrics data can be viewed.

[WARNING]
====
Do not remove the `${home_directory}/data/metrics` directory or any files in it.
If this is done, all existing metrics data will be permanently lost.

Also note that if ${branding} is uninstalled/re-installed that all existing metrics data will be permanently lost.
====

.Types of Metrics Collected
<<_catalog_metrics,Catalog Metrics>>:: Metrics collected about the catalog status.
<<_source_metrics,Source Metrics>>:: Metrics collected per source.

