:title: URL Resource Reader
:type: subArchitecture
:status: published
:parent: Resource Readers
:order: 00
:summary: URL Resource Reader.

The `URLResourceReader` is an implementation of `ResourceReader` which is included in the ${branding} Catalog. 
It obtains a resource given an http, https, or file-based URL. 
The `URLResourceReader` will connect to the provided Resource URL and read the resource's bytes into an `InputStream`.  

[WARNING]
====
When a resource linked using a file-based URL is in the product cache, the `URLResourceReader`&#8217;s rootResourceDirectories is not checked when downloading the product.
It is downloaded from the product cache which bypasses the `URLResourceReader`.
For example, if path `/my/valid/path` is configured in the `URLResourceReader`&#8217;s rootResourceDirectories and one downloads the product with resource-uri `file:///my/valid/path/product.txt` and then one removes `/my/valid/path` from the `URLResourceReader`&#8217;s `rootResourceDirectories` configuration, the product will still be accessible via the product cache.
====

===== Installing the URL Resource Reader

The `URLResourceReader` is installed by default with a standard installation in the ${ddf-catalog} application.

===== Configuring the URL Resource Reader

Configure the URL Resource Reader from the ${admin-console}.

. Navigate to the *${admin-console}*.
. Select the *${ddf-catalog}* application.
. Select the *Configuration* tab.
. Select the *URL Resource Reader*.

See <<{reference-prefix}ddf.catalog.resource.impl.URLResourceReader,URL Resource Reader configurations>> for all possible configurations.

===== Configuring Permissions for the URL Resource Reader

Configuring the URL Resource Reader to retrieve files requires adding Security Manager read permissions to the directory containing the resources. The following permissions, replacing <DIRECTORY_PATH> with the path of the directory containing resources should be placed in the URL Resource Reader section inside ${home_directory}/security/configurations.policy.

.Adding New Permissions
[WARNING]
====
After adding permissions, a system restart is required for them to take effect.
====

. permission java.io.FilePermission "<DIRECTORY_PATH>", "read";
. permission java.io.FilePermission "<DIRECTORY_PATH>${/}-", "read";

Trailing slashes after <DIRECTORY_PATH> have no effect on the permissions granted. For example, adding a permission for "${/}test${/}path" and "${/}test${/}path${/}" are equivalent. The recursive forms "${/}test${/}path${/}-", and "${/}test${/}path${/}${/}-" are also equivalent.

Line 1 gives the URL Resource Reader the permissions to read from the directory. Line 2 gives the URL Resource Reader the permissions to recursively read from the directory, specified by the directory path's suffix "${/}-".

===== Using the URL Resource Reader

`URLResourceReader` will be used by the Catalog Framework to obtain a resource whose metacard is cataloged in the local data store.
This particular `ResourceReader` will be chosen by the `CatalogFramework` if the requested resource's URL has a protocol of `http`, `https`, or `file`.  

For example, requesting a resource with the following URL will make the Catalog Framework invoke the `URLResourceReader` to retrieve the product.

.Example
[source,http]
----
file:///home/users/${ddf-branding}_user/data/example.txt
----

If a resource was requested with the URL `udp://123.45.67.89:80/SampleResourceStream`, the `URLResourceReader` would _not_ be invoked.

.Supported Schemes:
* http
* https
* file

[NOTE]
====
If a file-based URL is passed to the `URLResourceReader`, that file path needs to be accessible by the ${branding} instance.
====
