
The ${ddf-content} Framework is a framework for storing, reading, processing, and transforming content information.
Content information consists of files that the client wants parsed and created with a metacard that is subsequently used to create a catalog entry in the Metadata Catalog and stored in the ${ddf-content} Repository.

The files passed into the ${ddf-content} Framework can be of any type, (e.g., NITF, PDF, Microsoft Word, etc.), as long as:

* the mime type can be resolved,
* an Input Transformer capable of parsing their content into a metacard exists,
* and the generated metacard satisfies the constraints of the catalog provider into which the generated metacard will be inserted.

For example, if the Tika Input Transformer is installed, Microsoft Office documents and PDF files can be transformed into metacards.
If the Solr catalog provider is being used, the generated metacard can be successfully inserted.

Clients typically perform create, read, update, and delete (CRUD) operations against the content repository.
At the core of the Content functionality is the Content Framework, which routes all requests and responses through the system, invoking additional processing per the system configuration.

The ${ddf-content} Framework has several components and an API that connects them together.
The Content API consists of the Java interfaces that define ${branding} functionality.
These interfaces provide the ability for components to interact without a dependency on a particular underlying implementation. This allows for alternate implementations that can maintain interoperability and share developed components. 
As such, new capabilities can be developed both independently and modularly with the Content API interfaces and reused by other ${branding} installations.

The ${ddf-content} API will evolve with ${branding} itself, but great care is taken to retain backwards compatibility with developed components.
Compatibility is reflected in version numbers.

=== Content Framework Architecture

.Architecture
[ditaa, content_framework_architecture, png, ${image.width}]
....
+------------------------------------------------------------------------------+
|                 /-=-----------------\                                        |
|                 |      Clients      |                                        |
|                 \-------------------/                                        |
|                           ^                                                  |
|                           |                                                  |
|                           v                                                  |
|                 /-------------------\                                        |
|                 |cDEF Endpoints     |                                        |
|                 +------------+------+                                        |
|                 | cDEF       | cDEF |                                        |
|                 | Operations | Data |                                        |
|                 +------------+------+-----------------------\                |
|                 | cDEF              |cDEF Transformers      |                |
|                 |                   +-----------------------+                |
|                 | Content Framework |cDEFStorage Plugins    |                |
|                 |                   +-----------------------+                |
|                 |                   |cDEFContent Plugins    |                |
|                 +-------------------+-----------------------/                |
|                 |cDEF               |                                        |
|                 | Storage Provider  |                                        |
|                 \-------------------/                                        |
|                           ^                                                  |
|                           |                                                  |
|                           v                                                  |
|                   +-=-------------+                LEGEND                    |
|                   |{s}            |                /--------------------\    |
|                   |   Content     |                |cDEF${branding} Component   |    |
|                   |  Repository   |                \--------------------/    |
|                   +---------------+                /-=------------------\    |
|                                                    | External Component |    |
|                                                    \--------------------/    |
+------------------------------------------------------------------------------+
....

==== Design

The ${ddf-content} Framework design consists of several major components, namely: endpoints, input transformers, the core Content Framework, storage providers, storage plugins, and Content plugins.

The endpoints provide external clients access to the Framework.
Input transformers convert incoming content into a metacard.
The core Content Framework routes requests and responses through the system.
The storage providers provide storage of the content to specific types of  storage, e.g., file system, relational database, XML database.
Storage plugins provide pluggable functionality that can be executed either immediately before or immediately after content has been stored or updated.
The Content plugins provide pluggable functionality that can be executed after the content has been stored/update/deleted and after the storage plugins but before the response has been returned to the client.

==== ${ddf-content} API Packaging

The Content API consists of the Java interfaces that define the methods that this API supports.
The following illustration shows these interfaces and how they are packaged.

.Content API Packaging
[ditaa, content_api_packaging, png]
....
+-------------------------------------------------------------------------------------------------------------------------------------------------\
|${ddf-content} API cCCC                                                                                                                             |
|+----------------------------------\ +-------------------\ +---------------------------------------------------------------\ +------------------\|
||${ddf-branding}.content.plugin                | |${ddf-branding}.contentprovider| |${ddf-branding}.content.operation                                          | |${ddf-branding}.content       ||
||   +-------------\ +-------------\| |  +---------------\| | +---------\ +-------\ +--------\ +-------------\              | |+----------------\||
||   |ContentPlugin| |PreUpdate    || |  |StorageProvider|| | |Operation| |Request| |Response| |CreateRequest|              | ||ContentFramework|||
||   |cFFC         | |StoragePlugin|| |  |cFFC           || | |cFFC     | |cFFC   | |cFFC    | |cFFC         |              | ||cFFC            |||
||   \-------------/ |cFFC         || |  \---------------/| | \---------/ \-------/ \--------/ \-------------/              | |\----------------/||
||   +-------------\ \-------------/| |cDEF               | | +--------------\ +-----------\ +------------\ +-------------\ | |cDEF              ||
||   |PreCreate    | +-------------\| \-------------------/ | |CreateResponse| |ReadRequest| |ReadResponse| |UpdateRequest| | \------------------/|
||   |StoragePlugin| |PostUpdate   ||                       | |cFFC          | | cFFC      | | cFFC       | | cFFC        | |                     |
||   |cFFC         | |StoragePlugin||                       | \--------------/ \-----------/ \------------/ \-------------/ |                     | +-----------------------------------\
||   \-------------/ |cFFC         ||                       | +--------------\ +-------------\ +--------------\             |                     | |${branding} Mime Types Support             |
||   +-------------\ \-------------/|                       | |UpdateResponse| |DeleteRequest| |DeleteResponse|  cDEF       |                     | |+----------------\ +--------------\|
||   |PostCreate   |                |                       | |cFFC          | | cFFC        | |cFFC          |             |                     | ||MimeTypeResolver| |MimeTypeMapper||
||   |StoragePlugin|                |                       | \--------------/ \-------------/ \--------------/             |                     | ||cFFC            | |cFFC          ||
||   |cFFC         |                |                       \---------------------------------------------------------------/                     | |\----------------/ \--------------/|
||   \-------------/                |                                                                                                             | \-----------------------------------/
|\----------------------------------/                                                                                                             |
\-------------------------------------------------------------------------------------------------------------------------------------------------/
....

==== ${ddf-content} API Reference Implementation

The Content API Reference Implementation consists of the Java classes that implement the methods defined in the Content API.
The following illustration shows these classes and how they are packaged.

.Content API Packaging Implementation
[ditaa, content_api_reference_impl, png]
....
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------\
|${ddf-content} API Impl                                                                                                                                                          |
|+------------------------------------\ +-------------------------\ +-------------------------------------------------------------------------------\ +----------------------\ |
||${ddf-branding}.content.plugin.cataloger cDEF   | |${ddf-branding}.content.provider.file| |${ddf-branding}.content.operation.impl                                                     | |${ddf-branding}.content.impl      | |
||+---------\ +----------------------\| |     +------------------\| | +-------------\ +-----------\ +------------\ +-----------------\              | |+--------------------\| |
|||Cataloger| |CatalogContentPlugin  || |     |FileSystemProvider|| | |OperationImpl| |RequestImpl| |ResponseImpl| |CreateRequestImpl|              | ||ContentFrameworkImpl|| |
||| cFFC    | | cFFC                 || |     | cFFC             || | |cFFC         | |cFFC       | |cFFC        | |cFFC             |    cDEF      | ||cFFC                || |
||\---------/ \----------------------/| |     \------------------/| | \-------------/ \-----------/ \------------/ \-----------------/              | |\--------------------/| |
||                                    | |   cDEF                  | | +------------------\ +---------------\ +----------------\ +-----------------\ | | cDEF                 | |
|\------------------------------------/ \-------------------------/ | |CreateResponseImpl| |ReadRequestImpl| |ReadResponseImpl| |UpdateRequestImpl| | \----------------------/ |
|+------------------------------------\                             | |cFFC              | |cFFC           | |cFFC            | |cFFC             | |                          |
||${ddf-branding}.content.plugin.video cDEF       |                             | \------------------/ \---------------/ \----------------/ \-----------------/ |                          |
||+----------------------\            |                             | +------------------\ +-----------------\ +------------------\                 |                          |
|||VideoThumbnailPlugin  |            |                             | |UpdateResponseImpl| |DeleteRequestImpl| |DeleteResponseImpl|                 |                          |
||| cFFC                 |            |                             | |cFFC              | |cFFC             | | cFFC             |                 |                          |
||\----------------------/            |                             | \------------------/ \-----------------/ \------------------/                 |                          |
|\------------------------------------/                             |                                                                               |                          |
|                                                                   \-------------------------------------------------------------------------------/                          |
\------------------------------------------------------------------------------------------------------------------------------------------------------------------------------/
....


=== Content Component Types

==== Content Data Components

.Content Data Component Architecture
[ditaa, content_data_components, png,${image.width}]
....
+------------------------------------------------------------------------------+
|                 /-=-----------------\                                        |
|                 |      Clients      |                                        |
|                 \-------------------/                                        |
|                           ^                                                  |
|                           |                                                  |
|                           v                                                  |
|                 /-------------------\                                        |
|                 |cDEF Endpoints     |                                        |
|                 +------------+------+                                        |
|                 | cDEF       | c369 |                                        |
|                 | Operations | Data |                                        |
|                 +------------+------+-----------------------\                |
|                 | cDEF              |cDEF Transformers      |                |
|                 |                   +-----------------------+                |
|                 | Content Framework |cDEFStorage Plugins    |                |
|                 |                   +-----------------------+                |
|                 |                   |cDEFContent Plugins    |                |
|                 +-------------------+-----------------------/                |
|                 |cDEF               |                                        |
|                 | Storage Provider  |                                        |
|                 \-------------------/                                        |
|                           ^                                                  |
|                           |                                                  |
|                           v                                                  |
|                   +-=-------------+                LEGEND                    |
|                   |{s}            |                /--------------------\    |
|                   |   Content     |                |cDEF${branding} Component   |    |
|                   |  Repository   |                \--------------------/    |
|                   +---------------+                /-=------------------\    |
|                                                    | External Component |    |
|                                                    \--------------------/    |
+------------------------------------------------------------------------------+
....


===== Content Item

Content Item is the domain object populated by the Content Endpoint from the client request that represents the information about the content to be stored in the Storage Provider.
A Content Item encapsulates the content's globally unique ID, mime type, and input stream (i.e., the actual content).

==== Content Endpoints

.Content Endpoint Architecture
[ditaa, content_endpoints, png,${image.width}]
....
+------------------------------------------------------------------------------+
|                 /-=-----------------\                                        |
|                 |      Clients      |                                        |
|                 \-------------------/                                        |
|                           ^                                                  |
|                           |                                                  |
|                           v                                                  |
|                 /-------------------\                                        |
|                 |c369 Endpoints     |                                        |
|                 +------------+------+                                        |
|                 | cDEF       | cDEF |                                        |
|                 | Operations | Data |                                        |
|                 +------------+------+-----------------------\                |
|                 | cDEF              |cDEF Transformers      |                |
|                 |                   +-----------------------+                |
|                 | Content Framework |cDEFStorage Plugins    |                |
|                 |                   +-----------------------+                |
|                 |                   |cDEFContent Plugins    |                |
|                 +-------------------+-----------------------/                |
|                 |cDEF               |                                        |
|                 | Storage Provider  |                                        |
|                 \-------------------/                                        |
|                           ^                                                  |
|                           |                                                  |
|                           v                                                  |
|                   +-=-------------+                LEGEND                    |
|                   |{s}            |                /--------------------\    |
|                   |   Content     |                |cDEF${branding} Component   |    |
|                   |  Repository   |                \--------------------/    |
|                   +---------------+                /-=------------------\    |
|                                                    | External Component |    |
|                                                    \--------------------/    |
+------------------------------------------------------------------------------+
....

Content endpoints act as a proxy between the client and the Content Framework.
Endpoints expose the client to the Content Framework.

Endpoint interface formats/protocols can include a variety of formats, including (but not limited to):

* SOAP Web services
* RESTful services
* JMS
* RMI
* JSON
* OpenSearch

Content endpoints provide the capability to create, read, update, and delete content in the content repository, as well as create, update, and delete metacards corresponding to the content in the Metadata Catalog.

Endpoints are the only client-accessible components in ${branding}.

===== Examples

The following endpoints are provided with the Content Framework out of the box:

* Content REST CRUD Endpoint

==== Content Framework

.Content Framework Architecture
[ditaa, content_framework, png,${image.width}]
....
+------------------------------------------------------------------------------+
|                 /-=-----------------\                                        |
|                 |      Clients      |                                        |
|                 \-------------------/                                        |
|                           ^                                                  |
|                           |                                                  |
|                           v                                                  |
|                 /-------------------\                                        |
|                 |cDEF Endpoints     |                                        |
|                 +------------+------+                                        |
|                 | cDEF       | cDEF |                                        |
|                 | Operations | Data |                                        |
|                 +------------+------+-----------------------\                |
|                 | c369              |cDEF Transformers      |                |
|                 |                   +-----------------------+                |
|                 | Content Framework |cDEFStorage Plugins    |                |
|                 |                   +-----------------------+                |
|                 |                   |cDEFContent Plugins    |                |
|                 +-------------------+-----------------------/                |
|                 |cDEF               |                                        |
|                 | Storage Provider  |                                        |
|                 \-------------------/                                        |
|                           ^                                                  |
|                           |                                                  |
|                           v                                                  |
|                   +-=-------------+                LEGEND                    |
|                   |{s}            |                /--------------------\    |
|                   |   Content     |                |cDEF${branding} Component   |    |
|                   |  Repository   |                \--------------------/    |
|                   +---------------+                /-=------------------\    |
|                                                    | External Component |    |
|                                                    \--------------------/    |
+------------------------------------------------------------------------------+
....

The Content Framework wires all Content components together via OSGi and the Content API.
It handles all Content operations requested by endpoints, invoking Content Plugins as needed, and for most Operations, sending the request to a Storage Provider for execution.

===== Examples

The ${ddf-content} comes with the following Content Frameworks out of the box:

* Standard Content Framework

==== Content Operations

.Content Operations Architecture
[ditaa, content_operations, png,${image.width}]
....
+------------------------------------------------------------------------------+
|                 /-=-----------------\                                        |
|                 |      Clients      |                                        |
|                 \-------------------/                                        |
|                           ^                                                  |
|                           |                                                  |
|                           v                                                  |
|                 /-------------------\                                        |
|                 |cDEF Endpoints     |                                        |
|                 +------------+------+                                        |
|                 | c369       | cDEF |                                        |
|                 | Operations | Data |                                        |
|                 +------------+------+-----------------------\                |
|                 | cDEF              |cDEF Transformers      |                |
|                 |                   +-----------------------+                |
|                 | Content Framework |cDEFStorage Plugins    |                |
|                 |                   +-----------------------+                |
|                 |                   |cDEFContent Plugins    |                |
|                 +-------------------+-----------------------/                |
|                 |cDEF               |                                        |
|                 | Storage Provider  |                                        |
|                 \-------------------/                                        |
|                           ^                                                  |
|                           |                                                  |
|                           v                                                  |
|                   +-=-------------+                LEGEND                    |
|                   |{s}            |                /--------------------\    |
|                   |   Content     |                |cDEF${branding} Component   |    |
|                   |  Repository   |                \--------------------/    |
|                   +---------------+                /-=------------------\    |
|                                                    | External Component |    |
|                                                    \--------------------/    |
+------------------------------------------------------------------------------+
....

The ${branding} Content provides the capability to read, create, update, and delete content from the ${branding} Content Repository.

Each of these operations follow a request/response paradigm.
The request is the input to the operation and contains all of the input parameters needed by the Content Framework's operation to communicate with the Storage Providers and Content Plugins.
The response is the output from the execution of the operation that is returned to the client and contains all of the data returned by the Storage Providers and  Content Plugins.
For each operation, there is an associated request/response pair, e.g., the `CreateRequest` and `CreateResponse` pair for the Content Framework's create operation.

All of the request and response objects are extensible in that they can contain additional key/value properties on each request/response.
This allows additional capability to be added without changing the Content API, helping to maintain backwards compatibility.

==== Storage Plugins
[ditaa, storage_plugin, png,${image.width}]
....
+------------------------------------------------------------------------------+
|                 /-=-----------------\                                        |
|                 |      Clients      |                                        |
|                 \-------------------/                                        |
|                           ^                                                  |
|                           |                                                  |
|                           v                                                  |
|                 /-------------------\                                        |
|                 |cDEF Endpoints     |                                        |
|                 +------------+------+                                        |
|                 | cDEF       | cDEF |                                        |
|                 | Operations | Data |                                        |
|                 +------------+------+-----------------------\                |
|                 | cDEF              |cDEF Transformers      |                |
|                 |                   +-----------------------+                |
|                 | Content Framework |c369Storage Plugins    |                |
|                 |                   +-----------------------+                |
|                 |                   |cDEFContent Plugins    |                |
|                 +-------------------+-----------------------/                |
|                 |cDEF               |                                        |
|                 | Storage Provider  |                                        |
|                 \-------------------/                                        |
|                           ^                                                  |
|                           |                                                  |
|                           v                                                  |
|                   +-=-------------+                LEGEND                    |
|                   |{s}            |                /--------------------\    |
|                   |   Content     |                |cDEF${branding} Component   |    |
|                   |  Repository   |                \--------------------/    |
|                   +---------------+                /-=------------------\    |
|                                                    | External Component |    |
|                                                    \--------------------/    |
+------------------------------------------------------------------------------+
....

The Content Framework calls Storage Plugins to process each request both immediately before and immediately after an item is created or updated in the content repository. Storage Plugins are only run if the request specifies content storage.

===== Examples
Types of Storage Plugins available out of the box:

* Video Thumbnail Plugin, which is both a PostCreateStoragePlugin and a PostUpdateStoragePlugin and is used to generate thumbnails for video files stored in the content repository.

==== Content Plugins

.Content Plugin Architecture
[ditaa, content_plugin, png,${image.width}]
....
+------------------------------------------------------------------------------+
|                 /-=-----------------\                                        |
|                 |      Clients      |                                        |
|                 \-------------------/                                        |
|                           ^                                                  |
|                           |                                                  |
|                           v                                                  |
|                 /-------------------\                                        |
|                 |cDEF Endpoints     |                                        |
|                 +------------+------+                                        |
|                 | cDEF       | cDEF |                                        |
|                 | Operations | Data |                                        |
|                 +------------+------+-----------------------\                |
|                 | cDEF              |cDEF Transformers      |                |
|                 |                   +-----------------------+                |
|                 | Content Framework |cDEFStorage Plugins    |                |
|                 |                   +-----------------------+                |
|                 |                   |c369Content Plugins    |                |
|                 +-------------------+-----------------------/                |
|                 |cDEF               |                                        |
|                 | Storage Provider  |                                        |
|                 \-------------------/                                        |
|                           ^                                                  |
|                           |                                                  |
|                           v                                                  |
|                   +-=-------------+                LEGEND                    |
|                   |{s}            |                /--------------------\    |
|                   |   Content     |                |cDEF${branding} Component   |    |
|                   |  Repository   |                \--------------------/    |
|                   +---------------+                /-=------------------\    |
|                                                    | External Component |    |
|                                                    \--------------------/    |
+------------------------------------------------------------------------------+
....

The Content Framework calls Content plugins to process requests after they have been processed by the Storage Provider (and after any PostCreateStorage/PostUpdateStoragePlugins).
If the request does not specify content storage (only processing), the Content Plugins are called immediately by the Content Framework.

===== Examples

Types of Content Plugins available out of the box:

* Content Cataloger Plugin

==== Storage Providers

.Storage Provider Architecture
[ditaa, storage_provider, png,${image.width}]
....
+------------------------------------------------------------------------------+
|                 /-=-----------------\                                        |
|                 |      Clients      |                                        |
|                 \-------------------/                                        |
|                           ^                                                  |
|                           |                                                  |
|                           v                                                  |
|                 /-------------------\                                        |
|                 |cDEF Endpoints     |                                        |
|                 +------------+------+                                        |
|                 | cDEF       | cDEF |                                        |
|                 | Operations | Data |                                        |
|                 +------------+------+-----------------------\                |
|                 | cDEF              |cDEF Transformers      |                |
|                 |                   +-----------------------+                |
|                 | Content Framework |cDEFStorage Plugins    |                |
|                 |                   +-----------------------+                |
|                 |                   |cDEFContent Plugins    |                |
|                 +-------------------+-----------------------/                |
|                 |c369               |                                        |
|                 | Storage Provider  |                                        |
|                 \-------------------/                                        |
|                           ^                                                  |
|                           |                                                  |
|                           v                                                  |
|                   +-=-------------+                LEGEND                    |
|                   |{s}            |                /--------------------\    |
|                   |   Content     |                |cDEF${branding} Component   |    |
|                   |  Repository   |                \--------------------/    |
|                   +---------------+                /-=------------------\    |
|                                                    | External Component |    |
|                                                    \--------------------/    |
+------------------------------------------------------------------------------+
....

Storage providers act as a proxy between the Content Framework and the mechanism storing the content, e.g., file system, relational database.
Storage providers expose the storage mechanism to the Content Framework.

Storage providers provide the capability to the Content Framework to create, read, update, and delete content in the content repository.

===== Examples

The following storage providers are provided with the Content Framework out of the box:

* File System Storage Provider

=== ${ddf-content} Core

The `content-core` bundle is a collection of default catalog components that can be used for most situations.

==== Standard Content Framework

The Standard Content Framework provides the reference implementation of a Content Framework that implements all requirements of the Content API. 
`ContentFrameworkImpl` is the implementation of the Standard Content Framework.

===== Using

The Standard Content Framework is the core class of ${branding} Content.
It provides the methods for read, create, update, and delete (CRUD) operations on the Storage Provider.

Use this framework if:

* access to a storage provider to create, update, and delete content items in the ${ddf-content} Repository is required or
* the ability to parse content, create a metacard, and then create, update, and delete catalog entries in the Metadata Catalog based on the parsed content are required.

===== Installing and Uninstalling

The Standard Content Framework is bundled in the `content-core` feature and is part of the `content-core-app`. 
It can be installed and uninstalled using the normal processes described in the Configuration section.

===== Configuring

There are no configuration properties for this component.
This component can only be installed and uninstalled.

==== Known Issues

None

=== Video Thumbnail Plugin

The Video Thumbnail Plugin provides the ability to generate thumbnails for video files stored in the Content Repository.

It is an implementation of both the PostCreateStoragePlugin and PostUpdateStoragePlugin interfaces. When installed, it is invoked by the Content Framework immediately after a content item has been created or updated by the Storage Provider.

==== Using

This plugin uses a custom 32-bit LGPL build of https://ffmpeg.org/[FFmpeg] (a video processing program) to generate thumbnails. When this plugin is installed, it places the FFmpeg executable appropriate for the current operating system in `<${branding}_INSTALL_DIR>/bin_third_party/ffmpeg`. When invoked, this plugin runs the FFmpeg binary in a separate process to generate the thumbnail. The `<${branding}_INSTALL_DIR>/bin_third_party/ffmpeg` directory is deleted when the plugin is uninstalled.

NOTE: Prebuilt FFmpeg binaries are provided for Linux, Mac, and Windows only.

==== Installing and Uninstalling

The Video Thumbnail Plugin is bundled as the `content-core-videothumbnailplugin`. It is not installed by default.

==== Configuring

There are no configurable properties for this component. This component can only be installed and uninstalled.

==== Known Issues

None

=== Content Cataloger Plugin

The Content Cataloger Plugin provides the implementation to parse content, create a Metacard, and create, update, and delete catalog entries in the Metadata Catalog.

The Content Cataloger Plugin is an implementation of the `ContentPlugin` interface.
When installed, it is invoked by the Content Framework after a content item has been processed by the Storage Provider (and after any PostCreateStorage/PostUpdateStoragePlugins), but before the response is returned to the Content Endpoint.

The Content Cataloger Plugin searches the OSGi service registry for all services registered as `InputTransformers` that can process the content item's mime type.
If such a service is found, the service is invoked (for `create` and `update` operations; `delete` operations are handled internally by the Content Cataloger Plugin).
The `inputTransformer` service accepts the content item's `InputStream` and parses it, creating a Metacard that is returned to the Content Cataloger Plugin.
This Metacard is then used in the `create` and `update` operations invoked on the Catalog Framework to interface with the Metadata Catalog.

===== Using

Use the Content Cataloger Plugin if create/update/delete of catalog entries in the Metadata Catalog based on the content item are desired.
These CRUD operations on the Metadata Catalog are made possible by parsing the content item to create a metacard and then using this metacard in the CRUD operations on the Catalog Framework.
The Content Cataloger Plugin is the only component in the ${ddf-content} Framework that has the ability to interface with the Catalog Framework (and thus the Metadata Catalog).

===== Installing and Uninstalling

The Content Cataloger Plugin is bundled as the `content-core-catalogerplugin` feature.

===== Configuring

There are no configurable properties for this component.
This component can only be installed and uninstalled.

==== Known Issues

Content Cataloger Plugin is only partially transactional.
On create operations where the content is being stored in the content repository and the content is being parsed to generated a metacard for insertion into the Metadata Catalog, the content storage will be undone (i.e., the recently inserted content removed from the content repository) if the Metadata Catalog insertion encountered problems. Update and delete operations have no transactional capabilities.
Once the content is updated or deleted this cannot be undone.
Therefore, the content repository and Metadata Catalog could get out of sync.

=== Directory Monitor

The Content Directory Monitor allows files placed in a monitored directory to be ingested into the ${ddf-content} Repository and/or the Metadata Catalog (MDC). 
A monitored directory is a directory configured to be polled by ${branding} periodically (typically once per second) for any new files added to the directory that should be ingested into the Content Framework.

The typical execution flow of the Directory Monitor is:

. A new file is detected in the monitored directory, 
. The file's contents are passed on to the Content Framework and processed based on whether the monitored directory's processing directive was:
.. configured to just store the file in the ${ddf-content} Repository,
.. configured to just process the file's metadata and ingest it into the MDC, or 
.. configured to both store the file in the Content Repository and ingest it into the MDC.
. If the response from the Content Framework is successful, indicating the content was stored and/or processed, the file in the monitored directory is either deleted (default behavior) or copied to a sub-directory called `.ingested` (see below for how to configure this behavior). If the response from the Content Framework was unsuccessful or a failure occurred, the file is moved from the monitored directory to a sub-folder named `.errors`, allowing easy identification of the ingested files that had problems.

Multiple monitored directories can be configured, each monitoring different directories.

==== Using

The Content Directory Monitor provides the capability to easily create content in the ${ddf-content} Repository and metacards in the MDC by simply placing a file in a directory that has been configured to be monitored by ${branding}.
For example, this would be useful for copying files from a hard drive (or directory) in a batch-like operation to the monitored directory and having all of the files processed by the Content Framework.

===== Sample Usage Scenarios

====== Scenario 1: Monitor single directory for storage and processing, with no file backup

* The Content Directory Monitor has the following configurations.
** The *relative* path of `inbox` for the directory path.
** The Processing Directive is set to Store and Process.
** The *Copy Ingested Files* option is not checked.
* As files are placed in the monitored directory `<${branding}_INSTALL_DIR>/inbox`, the files are ingested into the Content Framework.
** The Content Framework generates a GUID for the create request for this ingested file.
** Since the Store and Process directive was configured the ingested file is passed on to the Content File System Storage Provider, which creates a sub-directory in the Content Repository using the GUID and places the ingested file into this GUID sub-directory using the file name provided in the request.
** The Content Framework then invokes the Catalog Content Plugin, which looks up the Input Transformer associated with the ingested file's mime type and invokes the Catalog Framework, which inserts the metacard into the MDC. This Input Transformer creates a metacard based on the contents of the ingested file.
** The Content Framework sends back a successful status to the Camel route that was monitoring the directory.
** Camel route completes and deletes the file from the monitored directory.

====== Scenario 2: Monitor single directory for storage with file backup

* The Content Directory Monitor has the following configurations.
** The *absolute* path of `/usr/my/home/dir/inbox` for the directory path. 
** The Processing Directive is set to store only. 
** The *Copy Ingested Files* option is checked.
* As files are placed in the monitored directory `/usr/my/home/dir/inbox`, the files are ingested into the Content Framework.
** The Content Framework generates a GUID for the create request for this ingested file.
** Since the Store directive was configured, the ingested file is passed on to the Content File System Storage Provider, which creates a sub-directory in the Content Repository using the GUID and places the ingested file into this GUID sub-directory using the file name provided in the request.
** The Content Framework sends back a successful status to the Camel route that was monitoring the directory.
** The Camel route completes and moves the file from the monitored directory to its sub-directory `/usr/my/home/dir/inbox/.ingested`.

====== Scenario 3: Monitor multiple directories for processing only with file backup - errors encountered on some ingests

* Two different Content Directory Monitors have the following configurations.
** The *relative* path of `inbox` and `inbox2` for the directory path. 
** The Processing Directive on both directory monitors is set to Process.
** The Copy Ingested Files option is checked for both directory monitors.
* As files are placed in the monitored directory `<${branding}_INSTALL_DIR>/inbox`, the files are ingested into the Content Framework.
** The Content Framework generates a GUID for the create request for this ingested file.
** Since the Process directive was configured, the ingested file is passed on to the Catalog Content Plugin, which looks up the Input Transformer associated with the ingested file's mime type (but no Input Transformer is found) and an exception is thrown.
** The Content Framework sends back a failure status to the Camel route that was monitoring the directory.
** The Camel route completes and moves the file from the monitored directory to the `.errors` sub-directory.
* As files are placed in the monitored directory `<${branding}_INSTALL_DIR>/inbox2`, the files are ingested into the Content Framework.
** The Content Framework generates a GUID for the create request for this ingested file.
** The Content Framework then invokes the Catalog Content Plugin, which looks up the Input Transformer associated with the ingested file's mime type and invokes the Catalog Framework, which inserts the metacard into the MDC. This Input Transformer creates a metacard based on the contents of the ingested file.
** The Content Framework sends back a successful status to the Camel route that was monitoring the directory.
** The Camel route completes and moves the file from the monitored directory to its `.ingested` sub-directory.

==== Installing and Uninstalling

The Content Directory Monitor is packaged as the `content-core-directorymonitor` feature and is part of the `content-core-app`. It is installed by default.

[NOTE]
====
Note that the `content-core-catalogerplugin` feature must be installed for the metacards to be created and inserted into the MDC.
This feature provides the linkage between the Content Framework and the  Catalog Framework.
If the client attempts a STORE_AND_PROCESS or a PROCESS only without this feature installed a failure will be returned.
====

==== Configuring

The configurable properties for the Content Directory Monitor are accessed from the *Content Directory Monitor* Configuration in the Admin Console.

===== Configuring Content Directory Monitors

Managed Service Factory PID:
`${ddf-branding}.content.core.directorymonitor.ContentDirectoryMonitor`

===== Configurable Properties

[cols="1,1,1,4a,1,1," options="header"]
|===

|Title
|Property
|Type
|Description
|Default Value
|Required

|Directory Path
|`monitoredDirectoryPath`
|String
|Specifies the directory to be monitored.
Can be a fully-qualified directory or a relative path (which is relative to the ${branding} installation directory).
|N/A
|Yes

|Processing Directive
|`directive`
|String
|One of three possible values from a drop down box:

* Store only - indicates to only store content in Content Repository
* Process only - indicates to only create metacard and insert into MDC
* Store and Process - do both
|Store and Process
|Yes

|Copy Files to Backup Directory
|`copyIngestedFiles`
|Boolean
|Checking this option indicates that a backup of the file placed in the monitored directory should be made upon successful processing of the file. The file is moved into the `.ingested` sub-directory of the monitored directory.
|False
|No

|===

==== Known Issues

None

=== File System Storage Provider

The File System Storage Provider is used to create/update/delete content items as files in the ${ddf-content} Repository. 
The File System Storage Provider is an implementation of the Storage Provider interface.
When installed, it is invoked by the Content Framework to create, update,or delete a file in the ${ddf-content} Repository.

* For `create` operations, the File System Storage Provider (using the `MimeTypeMapper`) examines the mime type of the content item and determines the extension to use for the file to be stored.
The File System Storage Provider also auto-generates a Globally Unique ID (GUID) for the content item.
This GUID is used as the sub-directory for the content item's location in the Content Repository.
This is to insure the files in the Content Repository are more evenly distributed rather than all being stored in one monolithic directory. 
The content is stored using the file name specified in the create request.

For example, if the content item's mime type was `image/nitf`, then:

** the file extension would be `.nitf`,
** a GUID would be auto-generated (an example GUID would be `54947df8-0e9e-4471-a2f9-9af509fb5889`),
** the file name is specified in the `create` request (example: myfile.nitf), and
** the location in the Content Repository would be determined based on the GUID and the file name specified in the request (example: `54947df80e9e4471a2f99af509fb5889/myfile.nitf`).

* For `read` operations, the File System Storage Provider reads the content file with the GUID specified in the `ReadRequest`.
* For `update` operations, the File System Storage Provider updates the content file with the content item's new `InputStream` contents. The GUID of the content file to be updated is included in the `UpdateRequest`.
* For `delete` operations, the File System Storage Provider deletes the content file with the GUID specified in the `DeleteRequest`.

[WARNING]
====
A sub-directory is created for each entry in the content store, so there will be limitations based on the file system that is used, i.e., the maximum amount of sub-directories supported for a file system.
====

==== Using

Use the File System Storage Provider if creating, reading, updating, and/or deleting contents in a file system is desired.

==== Installing and Uninstalling

The File System Storage Provider is packaged as the `content-core-filesystemstorageprovider` feature and is installed by default.

==== Configuring

The location used for content storage can be configured in the ${admin-console} under ${ddf-content} -> Configuration -> Content File System Storage Provider.

==== Known Issues

None.

=== ${ddf-content} REST CRUD Endpoint

The Content REST endpoint provides a CDR REST Retrieve v2.0-compliant ${ddf-branding} endpoint that allows clients to perform CRUD operations on the Content Repository using REST, a simple architectural style that performs communication using HTTP.

The URL exposing the REST functionality will be located at `http://<${branding}_HOST>:<${branding}_PORT>/services/content`, where `${branding}_HOST` is the IP address of where ${branding} is installed and `${branding}_PORT` is the port number on which ${branding} is listening.

The Content REST CRUD endpoint provides the capability to read, create, update, and delete content in the Content Repository, as well as create, update, and delete metacards in the catalog provider, i.e., the Metadata Catalog (MDC).
Furthermore, this endpoint allows the client to perform the create/update/delete operations on just the Content Repository, just the MDC, or both in one operation.

[WARNING]
====
The Content Framework is currently transactional for create operations only.
Therefore, the client sends a create request to create content in the ${ddf-content} Repository, processes the content to create a metacard, and ingests it into the MDC (i.e.,directive=STORE_AND_PROCESS).
If a problem is encountered during the catalog ingest, the content is removed from the ${ddf-content} Repository, analogous to a rollback.
This is so that the ${ddf-content} Repository and the MDC are kept in sync.

The Content Framework does not support rollback capability for update or delete operations that affect both the ${ddf-content} Repository and the MDC.
====

==== Using

The Content REST CRUD endpoint provides the capability to read, create, update, and delete content in the ${ddf-content} Repository as well as create, update, and delete metacards in the catalog provider as follows. Sample requests and repsonses are provided in a separate table.

[cols="2,2,4a,4"]
|===

|Operation
|HTTP Request
|Details
|Example URL

|Create Content and Catalog Entry
|HTTP POST
|The multipart/form-data REST request that contains the binary data to be stored in the ${ddf-content} Repository and to be parsed to create a metacard for ingest into the MDC. This binary data can be included in the request's body or as a file attachment.

An HTTP 201 CREATED status code is returned to the client with:

* Content-ID HTTP header set to GUID assigned to content item by Content Framework

* Catalog-ID HTTP header set to the catalog ID assigned to the new catalog entry created based on the metacard generated from the parsed content

* Content-URI HTTP header set to the resource URI for the content stored in the ${ddf-content} Repository

* Location URI HTTP header with URI containing the content ID

|\http://<${branding}_HOST>:<${branding}_PORT>/services/content

Where the `directive` form parameter is set to `STORE_AND_PROCESS`, and the `file` form parameter that specifies the binary data with an optional `filename` parameter that should be stored as in the ${ddf-content} Repository.
 
|Create Content Only
|HTTP POST
|The multipart/form-data REST request that contains the binary data to be stored in the ${ddf-content} Repository. This binary data can be included in the request's body or as a file attachment.

An HTTP 201 CREATED status code is returned to the client with:

* Content-ID HTTP header set to GUID assigned to content item by Content Framework
* Location URI HTTP header with URI containing the content ID

|\http://<${branding}_HOST>:<${branding}_PORT>/services/content

Where the `directive` form parameter is set to `STORE`, and the `file` form parameter that specifies the binary data with an optional `filename` parameter that should be stored as in the ${ddf-content} Repository.

|Create Catalog Entry Only
|HTTP POST
|The multipart/form-data REST request that contains the binary data to be parsed to create a metacard for ingest into the MDC. This binary data can be included in the request's body or as a file attachment.

An HTTP 200 OK status code is returned to the client with:

* Catalog-ID HTTP header set to the catalog ID assigned to the new catalog entry created based on the metacard generated from the parsed content

|\http://<${branding}_HOST>:<${branding}_PORT>/services/content

Where the `directive` form parameter is set to `PROCESS`, the `contentUri` form parameter is set to the URI of content being processed, and the `file` form parameter specifying the binary data.

|Update Content and Catalog Entry
|HTTP PUT
|The ID of the content item in the ${ddf-content} Repository to be updated is appended to the end of the URL.

The body of the REST request contains the binary data to update the ${ddf-content} Repository.

An HTTP 200 OK status code is returned to the client with:

* Content-ID HTTP header set to GUID updated by the Content Framework
* Catalog-ID HTTP header set to the catalog ID that was updated in the MDC
|\http://<${branding}_HOST>:<${branding}_PORT>/services/content/ABC123

Where `ABC123` is the ID of the content item to be updated, and the `directive` HTTP header parameter is set to `STORE_AND_PROCESS`.

|Update Content Only
|HTTP PUT
|The ID of the content item in the ${ddf-content} Repository to be updated is appended to the end of the URL.

The body of the REST request contains the data to update the ${ddf-content} Repository.

An HTTP 200 OK status code is returned to
the client with:

* Content-ID HTTP header set to GUID updated by the Content Framework
|\http://<${branding}_HOST>:<${branding}_PORT>/services/content/ABC123

Where `ABC123` is the ID of the content item to be updated, and the `directive` HTTP header parameter is set to `STORE`.

|Update Catalog Entry Only and Content ID is provided
|HTTP PUT
|The ID of the content item in the ${ddf-content} Repository to be updated is appended to the end of the URL.

The body of the REST request contains the data to update the catalog entry in the MDC.

An HTTP 200 OK status code is returned to the client with:

* Catalog-ID HTTP header set to the catalog ID that was updated in the MDC
* Content-ID HTTP header set to GUID updated by the Content Framework 
|\http://<${branding}_HOST>:<${branding}_PORT>/services/content/ABC123

Where `ABC123` is the ID of the content item to be updated, and the `directive` HTTP header parameter is set to `STORE_AND_PROCESS`.

|Update Catalog Entry Only and Content URI is provided
|HTTP PUT
|The URI of the content item in the MDC to be updated is specified in the `contentUri` HTTP header parameter.

The body of the REST request contains the data to update the catalog entry in the MDC.

An HTTP 200 OK status code is returned to the client with:

*Catalog-ID HTTP header set to the catalog ID that was updated in the MDC
|\http://<${branding}_HOST>:<${branding}_PORT>/services/content

The directive is set to `PROCESS` in the Content REST Endpoint; it does not need to be explicitly set in the the `directive` HTTP header parameter.

|Delete Content and Catalog Entry
|HTTP DELETE
|The ID of the content item in the ${ddf-content} Repository to be deleted is appended to the end of the URL.

HTTP status code of 204 NO CONTENT is returned upon successful deletion.

* Content-ID
* HTTP header set to GUID deleted by the Content Framework
* Catalog-ID HTTP header set to the catalog ID that was deleted from the MDC
|`http://<${branding}_HOST>:<${branding}_PORT>/services/content/ABC123`

Where `ABC123` is the ID of the content item to be deleted, and the `directive` HTTP header parameter is set to `STORE_AND_PROCESS`.

|Delete Content Only
|HTTP DELETE
|The ID of the content item in the ${ddf-content} Repository to be deleted is appended to the end of the URL.

HTTP status code of 204 NO CONTENT is returned upon successful deletion.
|\http://<${branding}_HOST>:<${branding}_PORT>/services/content/ABC123

Where `ABC123` is the ID of the content item to be deleted, and the directive HTTP header parameter is set to `STORE`.

|Delete Catalog Entry Only
|HTTP DELETE
|The URI of the content item in the MDC to be deleted is specified in the `contentUri` HTTP header parameter.

HTTP status code of 204 NO CONTENT is returned to the client upon successful
deletion with:

* Catalog-ID HTTP header set to the catalog ID that was deleted from the MDC
|\http://<${branding}_HOST>:<${branding}_PORT>/services/content

The `contentUri` HTTP header parameter is set to the URI of the catalog entry in the MDC to be deleted.

|Read
|HTTP GET
|The ID of the content item in the ${ddf-content} Repository to be retrieved is appended to the end of the URL.

An HTTP 200 OK status code is returned upon successful read, and the contents of the retrieved content item are contained in the HTTP body.

|\http://<${branding}_HOST>:<${branding}_PORT>/services/content/ABC123

Where `ABC123` is the ID of the content item to be retrieved

|===

[TIP]
====
For all Content REST CRUD commands, only one content item ID is supported in the URL.
Bulk operations are not supported.
====

===== Interact with REST Endpoint

Any web browser can be used to perform a REST read.
Various other tools and libraries can be used to perform the other HTTP operations on the REST endpoint (e.g., soapUI, cURL, etc.).

====== Create Request Multipart/Form-Data Parameters

The `create` (`HTTP POST`) request is a multipart/form-data request, allowing the binary data (i.e., the content) to be either included in the request's body or attached as a file.
This binary data is defined in a `Content-Disposition` part of the request where the `name` parameter is set to `file`, and the optional `filename` parameter indicates the name of the file that should store the content.

Optional form parameters for the `create` request are the `directive` and `contentUri`. 
The `directive` form parameter's value can be either`STORE`, `PROCESS`, or `STORE_AND_PROCESS`, indicating if the content should be only stored in the Content Repository, only processed to generate a metacard and then ingested into the MDC, or both.
The `directive` form parameter will default to `STORE_AND_PROCESS` if it is not specified. 

The `contentUri` form parameter allows the client to specify the URI of a product stored remotely/externally (relative to ${branding}).
This `contentUri` is used to indicate that the client will manage the content storage but wants the Content Framework to parse the content and create/update/delete a catalog entry in the MDC using this content URI as the entry's product URI. 
This parameter is used when the `directive` is set to `PROCESS`.

====== Update and Delete Request HTTP Header Parameters

Two optional HTTP header parameters are available on the `update` and `delete` RESTful URLs.

The `directive` header parameter allows the client to optionally direct the Content Framework to:

* only store the content in the ${ddf-content} Repository (`directive=STORE`)
* store the content in the repository and parse the content to create a metacard (`directive=STORE_AND_PROCESS`); this metacard is then created/updated/deleted in the Metadata Catalog (by invoking the Catalog Framework operations)

`STORE_AND_PROCESS` is the default value for the `directive` header parameter.
The `directive` header parameter is only used on the `PUT` and `DELETE` RESTful URLs that have a `contentId` in the URL.

The `contentUri` header parameter allows the client to specify the URI of a product stored remotely/externally (relative to ${branding}).
The `contentUri` header parameter is only used with the `PUT` and `DELETE` RESTful URLs, where the `contentId` is not appended to the URL.

====== Sample Requests and Responses

The table below displays sample REST requests and their responses for each of the operations supported by the Content REST endpoint.

For the examples below, ${branding} was running on host `${branding}_HOST` on port `${branding}_PORT`. Also, for all examples below the binary data, i.e., the "content", is not included in the request's body.

[cols="2,3a,3a" options="header"]
|===

|Operation
|Request
|Response

|Create Content and Catalog Entry
|
----
POST http://${branding}_HOST:${branding}_PORT/services/content/ HTTP/1.1

Content-Type: multipart/form-data; boundary=ARCFormBoundaryuxprlpjxmakbj4i

--ARCFormBoundaryuxprlpjxmakbj4i
Content-Disposition: form-data; name="directive"

STORE_AND_PROCESS
--ARCFormBoundaryuxprlpjxmakbj4i
Content-Disposition: form-data; name="file";
filename="C:\${branding}\geojson_valid.json"
Content-Type: application/json;id=geojson

<content included in payload but omitted here for brevity>
--ARCFormBoundaryuxprlpjxmakbj4i--
----

|
----
HTTP/1.1 201 Created
Catalog-ID: e82a31253e634a409c83d7164638f029
Content-ID: ef0ef614bbdb4ede99e2371ebd2280ee
Content-Length: 0
Content-URI:
content:ef0ef614bbdb4ede99e2371ebd2280ee
Date: Wed, 13 Feb 2013 21:56:15 GMT
Location:
http://127.0.0.1:8181/services/content/ef0ef614bbdb4ede99e2371ebd2280ee
Server: Jetty(7.5.4.v20111024)
----

|Create Content Only
|
----
POST http://${branding}_HOST:${branding}_PORT/services/content/ HTTP/1.1
Content-Type: multipart/form-data; boundary=ARCFormBoundaryuxprlpjxmakbj4i

--ARCFormBoundaryuxprlpjxmakbj4i
Content-Disposition: form-data; name="directive"

STORE
--ARCFormBoundaryuxprlpjxmakbj4i
Content-Disposition: form-data; name="file";
filename="C:\${branding}\geojson_valid.json"
Content-Type: application/json;id=geojson

<content included in payload but omitted here for brevity>
--ARCFormBoundaryuxprlpjxmakbj4i--
----
|
----
HTTP/1.1 201 Created
Content-ID: 7d671cd8e9aa4637960b37c7b3870aed
Content-Length: 0
Content-URI:
content:7d671cd8e9aa4637960b37c7b3870aed
Date: Wed, 13 Feb 2013 21:56:16 GMT
Location:
http://127.0.0.1:8181/services/content/7d671cd8e9aa4637960b37c7b3870aed
Server: Jetty(7.5.4.v20111024)

|Create Catalog Entry Only
|
----
POST http://${branding}_HOST:${branding}_PORT/services/content/ HTTP/1.1

Content-Type: multipart/form-data; boundary=ARCFormBoundaryuxprlpjxmakbj4i

--ARCFormBoundaryuxprlpjxmakbj4i
Content-Disposition: form-data; name="directive"

PROCESS

--ARCFormBoundaryuxprlpjxmakbj4i
Content-Disposition: form-data; name="contentUri"

http://localhost:8080/some/path/file.json
--ARCFormBoundaryuxprlpjxmakbj4i
Content-Disposition: form-data; name="file"; filename="C:\${branding}\geojson_valid.json"
Content-Type: application/json;id=geojson

<content included in payload but omitted here for brevity>
--ARCFormBoundaryuxprlpjxmakbj4i--
----
|
----
HTTP/1.1 200 OK
Catalog-ID: 94d8fae228a84e29a7396196542e2608
Content-Length: 0
Date: Wed, 13 Feb 2013 21:56:16 GMT
Server: Jetty(7.5.4.v20111024)
----
|Update Content and Catalog Entry
|
----
PUT http://${branding}_HOST:${branding}_PORT/services/content/bf9763c2e74d46f68a9ed591c4b74591 HTTP/1.1
Accept-Encoding: gzip,deflate
directive: STORE_AND_PROCESS
Content-Type: application/json;id=geojson
User-Agent: Jakarta Commons-HttpClient/3.1
Host: 127.0.0.1:8181
Content-Length: 9608

<content included in payload but omitted here for brevity>
----
|
----
HTTP/1.1 200 OK
Catalog-ID: d9ccbc9d139a4abbb0b1cdded1de0921
Content-ID: bf9763c2e74d46f68a9ed591c4b74591
Content-Length: 0
Date: Wed, 13 Feb 2013 21:56:25 GMT
Server: Jetty(7.5.4.v20111024)
----

|Update Content Only
|
----
PUT http://${branding}_HOST:${branding}_PORT/services/content/bf9763c2e74d46f68a9ed591c4b74591 HTTP/1.1
Accept-Encoding: gzip,deflate
directive: STORE
Content-Type: application/json;id=geojson
User-Agent: Jakarta Commons-HttpClient/3.1
Host: 127.0.0.1:8181
Content-Length: 9608

<content included in payload but omitted here for brevity>
----

|
----
HTTP/1.1 200 OK
Content-ID: 7a702cd5c95347d2aa79ccc25b39e4f6
Content-Length: 0
Date: Wed, 13 Feb 2013 21:56:25 GMT
Server: Jetty(7.5.4.v20111024)
----
|Update Catalog Entry Only and Content ID is provided (STORE_AND_PROCESS)
|
---
PUT http://${branding}_HOST:${branding}_PORT/services/content/bf9763c2e74d46f68a9ed591c4b74591 HTTP/1.1
Accept-Encoding: gzip,deflate
directive: STORE_AND_PROCESS
Content-Type: application/json;id=geojson
User-Agent: Jakarta Commons-HttpClient/3.1
Host: 127.0.0.1:8181
Content-Length: 9608

<content included in payload but omitted here for brevity>
---
|
----
HTTP/1.1 200 OK
Catalog-ID: 54a42215bf514322ba60bee97dab68e7
Content-ID: bf9763c2e74d46f68a9ed591c4b74591
Content-Length: 0
Date: Wed, 11 Sep 2013 15:22:59 GMT
Server: Jetty(7.6.8.v20121106)
----

|Update Catalog Entry Only and Content URI is provided (PROCESS only)
|
----
PUT http://${branding}_HOST:${branding}_PORT/services/content/ HTTP/1.1
Accept-Encoding: gzip,deflate
contentUri: http://${branding}_HOST:${branding}_PORT/some/path4/file.json
Content-Type: application/json;id=geojson

<content included in payload but omitted here for brevity>
----

|
----
HTTP/1.1 200 OK
Catalog-ID: b7a95aab99cd4318b8021eeef2715e4b
Content-Length: 0
Date: Wed, 11 Sep 2013 15:23:01 GMT
Server: Jetty(7.6.8.v20121106)
----

|Delete Content and Catalog Entry
|
----
DELETE http://${branding}_HOST:${branding}_PORT/services/content/911e27aba723448ea420142b0e793d38 HTTP/1.1
Accept-Encoding: gzip,deflate
directive: STORE_AND_PROCESS
User-Agent: Jakarta Commons-HttpClient/3.1
Host: 127.0.0.1:8181
----
|
----
HTTP/1.1 204 No Content
Catalog-ID: 5236910acbd14d97a786f1fa95d43d58
Content-ID: 911e27aba723448ea420142b0e793d38
Content-Length: 0
Date: Wed, 13 Feb 2013 21:56:31 GMT
Server: Jetty(7.5.4.v20111024)
----

|Delete Content Only
|
----
DELETE http://${branding}_HOST:${branding}_PORT/services/content/eb91c8ee225d4cddb4d9fbe2d9bf5d7c HTTP/1.1
Accept-Encoding: gzip,deflate
directive: STORE
User-Agent: Jakarta Commons-HttpClient/3.1
Host: 127.0.0.1:8181
----
|
----
HTTP/1.1 204 No Content
Content-ID: eb91c8ee225d4cddb4d9fbe2d9bf5d7c
Content-Length: 0
Date: Wed, 13 Feb 2013 21:56:31 GMT
Server: Jetty(7.5.4.v20111024)
----

|Delete Catalog Entry Only
|
----
DELETE http://${branding}_HOST:${branding}_PORT/services/content/ HTTP/1.1
Accept-Encoding: gzip,deflate
contentUri:http://${branding}_HOST:${branding}_PORT/some/path5/file.json
User-Agent: Jakarta Commons-HttpClient/3.1
Host: 127.0.0.1:8181
----
|
----
HTTP/1.1 204 No Content
Catalog-ID: c9a2b1c395f74300b33529483f095196
Content-Length: 0
Date: Wed, 13 Feb 2013 21:56:31 GMT
Server: Jetty(7.5.4.v20111024)
----

|Read
|
----
GET http://${branding}_HOST:${branding}_PORT/services/content/d34fd2b31f314aa6ade162015ba3016f HTTP/1.1
Accept-Encoding: gzip,deflate
User-Agent: Jakarta Commons-HttpClient/3.1
Host: 127.0.0.1:8181
----
|
----
HTTP/1.1 200 OK
Content-Length: 9579
Content-Type: application/json;id=geojson
Date: Wed, 13 Feb 2013 21:56:24 GMT
Server: Jetty(7.5.4.v20111024)
...  (remaining data of content item retrieved omitted for brevity) ...
----

|===

==== cURL Commands

The table below illustrates sample cURL commands corresponding to a few of the above REST requests.
Pay special attention to the flags, as they vary between operations.

For these examples, ${branding} was running on host `${branding}_HOST` on port `${branding}_PORT`.
We ingested/updated a file named `geojson_valid.json` whose MIME type was `application/json;id=geojson`, and whose content ID ended up being `CONTENT_ID`.

To perform each operation without using the catalog, replace `STORE_AND_PROCESS` with `STORE`. 
To manipulate the catalog entry only, replace `STORE_AND_PROCESS` with `PROCESS`.

[cols="2,5a" options="header"]
|===

|Operation
|Command

|Create Content and Catalog Entry
|
----
curl -i -X POST -F "directive=STORE_AND_PROCESS" -F "filename=geojson_valid.json" -F "file=${at-symbol}geojson_valid.json;type=application/json;id=geojson" http://${branding}_HOST:${branding}_PORT/services/content/
----

|Update Content and Catalog Entry
|
----
curl -i -X PUT -H "directive: STORE_AND_PROCESS" -H "Content-Type: application/json;id=geojson" --data-binary "${at-symbol}geojson_valid.json" http://${branding}_HOST:${branding}_PORT/services/content/CONTENT_ID
----
 
|Delete Content and Catalog Entry
|
----
curl -i -X DELETE -H "directive: STORE_AND_PROCESS" http://
${branding}_HOST
:
${branding}_PORT
/services/content/
CONTENT_ID

|Read
|
----
curl -i -X GET http://${branding}_HOST:${branding}_PORT/services/content/CONTENT_ID
----

|===

===== Install and Uninstall

The Content REST CRUD endpoint is packaged as the `content-rest-endpoint` feature.

===== Configuration

The Content REST CRUD endpoint has no configurable properties.
It can only be installed or uninstalled.

===== Known Issues

None
