
This section documents the installation, maintenance, and support of this application.

=== Prerequisites

Before the ${ddf-content} application can be installed, the following prerequisites must be met:

* the ${ddf-platform} Application and
* the ${ddf-catalog} Application must be installed. 

The Content application will continue to function properly as a content store without the Catalog application.
However, the Content application will not support creating metacards for ingested content.
Additionally, without the Catalog application, the Content application will be displayed as `FAILED` by the Platform Status Service and the Application Commands.

=== Installing ${ddf-content}

The Content application is installed by default with a standard installation.

=== Configuring ${ddf-content}

[cols="1,2,2" options="header"]
|===
|Configuration
|ID
|Description

|Content Directory Monitor
|`ddf.content.core.directorymonitor.ContentDirectoryMonitor`
|Enable automatic ingest of files placed in designated directory.

|Content File System Storage Provider
|`ddf.content.provider.filesystem.FileSystemProvider`
|Set directory on file system to use to store content.
|===
