
This section documents the installation, maintenance, and support of this application.

=== Prerequisites

Before the {branding} Content application can be installed, the following prerequisites must be met:

* the {branding} Kernel must be running,
* the {branding} Platform Application must be installed, and
* the {branding} Catalog Application must be installed. 

The Content application will continue to function properly as a content store without the Catalog application.
However, the Content application will not support creating metacards for ingested content.
Additionally, without the Catalog application, the Content application will be displayed as `FAILED` by the Platform Status Service and the Application Commands.

=== Installing {branding} Content

The Content application is installed by default with a standard installation.

=== Configuring {branding} Content

[cols="1,2,2" options="header"]
|===
|Configuration
|ID
|Description

|Content Directory Monitor
|`ddf.content.core.directorymonitor.ContentDirectoryMonitor`
|Enable automatic ingest of files placed in designated directory.

|Content File System Storage Provider
|`ddf.content.provider.filesystem.FileSystemProvider`
|Set directory on file system to use to store content.
|===
