:title: Using the Search UI
:type: usingIntro
:status: published
:parent: Using Search UI
:summary: Using the Simple Search user interface.
:order: 99

== {title}

The ${branding} ((Search UI)) application provides a low-bandwidth option for searching records in the local Catalog (provider) and federated sources.
Results are in HTML format.

=== Search

The *Input* form allows the user to specify keyword, geospatial, temporal, and type query parameters.
It also allows the user to select the sources to search and the number of results to return.

==== Search Criteria

Enter one or more of the available search criteria to execute a query:

Keyword Search:: A text box allowing the user to enter a textual query. This supports the use of (*) wildcards. If blank, the query contains a contextual component.
Sort Order:: Select from *Last Modified*, *Title*, *ID*, or *Keyword Relevance*.
Date Range:: Select from *Any Time*, *Past Day*, *Past Week*, *Past Month*, or *Past Year*.

==== Results

The table of results shows the details of the results found, as well as a link to download the resource if applicable.

===== Results  Summary

Total Results:: Total Number of Results available for this query. If there are more results than the number displayed per page then a page navigation link appears to the right.
Previous and Next:: Provides page navigation, which generate queries for requesting additional pages of results.

===== Results Table

The Results table provides a preview of and links to the results.
The table consists of these columns:

Title:: Displays title of the metacard. This is a link which can clicked to view the metacard in the Metacard View.
Source:: Displays where the metadata came from, which could be the local provider or a federated source.
Preview:: Shows the thumbnail of the metacard, if available.
Download:: A download link to retrieve the resource associated with the metacard, when applicable, if available.

==== Result View

This view shows more detailed look at a result. Use the browser's back page button to return to the Results table.

Preview:: Shows the thumbnail of the metacard, if available.
Download:: A download link to retrieve the resource associated with the metacard, when applicable, if available.
Result Table:: Provides the list of properties and associated values of a single search result.
