
Set up a complete, secure instance of ${branding}.
For simplified steps used for a testing, development, or demonstration installation, see the <<_quick_start_tutorial,${branding} Quick Start>>.

[IMPORTANT]
====
Although ${branding} can be installed by any user, it is recommended for security reasons to have a non-`root` user execute the ${branding} installation.
====

[NOTE]
====
Hardening guidance assumes a Standard installation.

Adding other components does not have any security/hardening implications.
====

=== Installation Prerequisites

These are the system/environment requirements to configure _prior_ to an installation.

======

.Using the Standard installation of the ${branding} application:
[cols="2,3,3" options="header"]
|===

|
2+^|Minimum and Recommended Requirements for ${branding} Systems in Production Mode*



|*Criteria*
|*Minimum*
|*Recommended*

|Operating System
|Windows Server 2012, Linux CentOS 5, Mac OS X 10.9 Mavericks
|Windows 10, Linux CentOS 7.3. macOS Sierra 10.12

|Additional Software
|JDK 8, IE 10
|JDK 8, Edge/FireFox/Chrome

|CPU
|Dual Core 1.6 GHz
|Quad Core 2.6 GHz

|RAM
|4 GB**
|32 GB

|Disk Space
|2 GB
|4 GB

|Video Card
|WebGL capable GPU
|

|===
*These requirements assume the use of a remote catalog. Extra resources will need to be allocated if the system will also be hosting a local catalog.

**The amount of RAM can be increased to support memory-intensive applications. See <<jvm-memory-configuration, Memory Considerations>>

======

.Java Requirements
* Supported platforms are *NIX - Unix/Linux/OSX, Solaris, and Windows.
* http://www.oracle.com/technetwork/java/javase/downloads/index.html[JDK8] must be installed.
* The `JAVA_HOME` environment variable must be set to the location where the JDK is installed.

. Install/Upgrade to Java 8 http://www.oracle.com/technetwork/java/javase/downloads/index.html[J2SE 8 SDK]
.. The recommended version is http://www.oracle.com/technetwork/java/javase/8u60-relnotes-2620227.html[8u60] or later.
.. Java version must contain only number values.
. Install/Upgrade to http://www.oracle.com/technetwork/java/javase/downloads/index.html[JDK8].
. Set the `JAVA_HOME` environment variable to the location where the JDK is installed.

.Setting JAVA_HOME variable
****

.*NIX
[WARNING]
====
Unlink `JAVA_HOME` if it is already linked to a previous version of the JRE:

`unlink JAVA_HOME`
====

Replace `<JAVA_VERSION>` with the version and build number installed.

. Open a terminal window(*NIX) or command prompt (Windows) with administrator privileges.
. Determine Java Installation Directory (This varies between operating system versions).
+
.Find Java Path in *NIX
----
which java
----
+
.Find Java Path in Windows
The path to the JDK can vary between versions of Windows, so manually verify the path under:
+
----
C:\Program Files\Java\jdk<M.m.p_build>
----
+
. Copy path of Java installation to clipboard. (example: `/usr/java/<JAVA_VERSION`>)
. Set `JAVA_HOME` by replacing <PATH_TO_JAVA> with the copied path in this command:
+
.Setting `JAVA_HOME` on *NIX
----
JAVA_HOME=<PATH_TO_JAVA><JAVA_VERSION>
export JAVA_HOME
----
+
.Setting `JAVA_HOME` on Windows
----
set JAVA_HOME=<PATH_TO_JAVA><JAVA_VERSION>
setx JAVA_HOME "<PATH_TO_JAVA><JAVA_VERSION>" /m
----
+
.Adding `JAVA_HOME` to `PATH` Environment Variable on Windows
----
setx PATH "%PATH%;%JAVA_HOME%\bin" /m
----
+
. Restart Terminal (shell) or Command Prompt.

* Verify that the `JAVA_HOME` was set correctly.
====

.*NIX
----
echo $JAVA_HOME
----

.Windows
----
echo %JAVA_HOME%
----
====
****

.File Descriptor Limit on Linux
[NOTE]
====
* For Linux systems, increase the file descriptor limit by editing `/etc/sysctl.conf` to include:

----
fs.file-max = 6815744
----

* For the change to take effect, a restart is required.

.*Nix Restart Command
----
init 6
----

====

=== Installing With the ${branding} Distribution Zip

.Check System Time
[WARNING]
====
Prior to installing ${branding}, ensure the system time is accurate to prevent federation issues.
====

To install the ${branding} distribution zip, perform the following:

. Download the ${branding} {download-url}[zip file].
. After the <<_installation_prerequisites,prerequisites>> have been met, change the current directory to the desired install directory, creating a new directory if desired.
This will be referred to as `<${branding}_HOME>`.
+
.Windows Pathname Warning
[WARNING]
====
Do not use spaces in directory or file names of the `<${branding}_HOME>` path.
For example, do not install in the default `Program Files` directory.
====
+
.Example: Create a Directory (Windows and *NIX)
----
mkdir new_installation
----
+
.. Use a Non-`root` User on *NIX. (Windows users skip this step)
+
It is recommended that the `root` user create a new install directory that can be owned by a non-`root` user (e.g., ${branding}_USER).
This can be a new or existing user.
This ${branding}_USER can now be used for the remaining installation instructions.
.. Create a new group or use an existing group (e.g., ${branding}_GROUP) (Windows users skip this step)
+
.Example: Add New Group on *NIX
----
groupadd ${branding}_GROUP
----
+
.Example: Switch User on *NIX
----
chown ${branding}_USER:${branding}_GROUP new_installation

su - ${branding}_USER
----
+
. Change the current directory to the location of the zip file (${branding-lowercase}-${project.version}.zip).
+
.*NIX (Example assumes ${branding} has been downloaded to a CD/DVD)
----
cd /home/user/cdrom
----
+
.Windows (Example assumes ${branding} has been downloaded to the D drive)
----
cd D:\
----
. Copy ${branding-lowercase}-${project.version}.zip to <${branding}_HOME>.
+
.*NIX
----
cp ${branding-lowercase}-${project.version}.zip <${branding}_HOME>
----
+
.Windows
----
copy ${branding-lowercase}-${project.version}.zip <${branding}_HOME>
----
+
. Change the current directory to the desired install location.
+
.*NIX or Windows
----
cd <${branding}_HOME>
----
+
. The ${branding} zip is now located within the `<${branding}_HOME>`. Unzip ${branding-lowercase}-${project.version}.zip.
+
.*NIX
----
unzip ${branding-lowercase}-${project.version}.zip
----
+
.Windows Zip Utility Warning
[WARNING]
====
The Windows Zip implementation, which is invoked when a user double-clicks on a zip file in the Windows Explorer, creates a corrupted installation.
This is a consequence of its inability to process long file paths.
Instead, use the java jar command line utility to unzip the distribution (see example below) or use a third party utility such as 7-Zip.

.Use Java to Unzip in Windows(Replace `<PATH_TO_JAVA>` with correct path `and <JAVA_VERSION>` with current version.)
----
"<PATH_TO_JAVA>\jdk<JAVA_VERSION>\bin\jar.exe" xf ${branding-lowercase}-${project.version}.zip
----

The unzipping process may take time to complete.
The command prompt will stop responding to input during this time.
====