:title: CSW Federation Profile Source
:type: source
:status: published
:link: _csw_federation_profile_source
:summary: Queries a CSW version 2.0.2 compliant service.
:federated: x
:connected:
:catalogprovider:
:storageprovider:
:catalogstore:

== {title}

The CSW Federation Profile Source is ${branding}'s CSW Federation Profile which supports the ability to search collections of descriptive information (metadata) for data, services, and related information objects.

Use the CSW Federation Profile Source when federating to a ${ddf-branding}-based system.

.Installing the CSW Federation Profile Source
Configure the CSW Federation Profile Source through the ${admin-console}:

. Navigate to the *${admin-console}*.
. Select the *${ddf-catalog}* application.
. Add a New source.
. Name the New source.
. Select *CSW Specification Profile Federated Source* from *Source Type*.

.Configuring the CSW Federation Profile Source
Configure an Existing CSW Federated Source through the ${admin-console}:

. Navigate to the *${admin-console}*.
. Select the *${ddf-catalog}* application.
. Select the *Sources* tab.
. Select the name of the source to edit.

See <<{reference-prefix}Csw_Federation_Profile_Source,CSW Federation Profile Source configurations>> for all possible configurations.

.Usage Limitations of the CSW Federation Profile Source
* Nearest neighbor spatial searches are not supported.
