:title: Federation Strategy
:type: configuration
:status: published
:parent: Configuring Federation
:order: 03
:summary: Federation Strategy.

== {title}

A federation strategy federates a query to all of the Remote Sources in the query's list, processes the results in a unique way, and then returns the results to the client. 
For example, implementations can choose to halt processing until all results return and then perform a mass sort or return the results back to the client as soon as they are received back from a Federated Source.

An endpoint can optionally specify the federation strategy to use when it invokes the query operation.
Otherwise, the Catalog provides a default federation strategy that will be used: the Catalog Federation Strategy.

=== Configuring Federation Strategy

The Catalog Federation Strategy configuration can be found in the ${admin-console}.

. Navigate to ${admin-console}.
. Select *${ddf-catalog}*
. Select *Configuration*
. Select *Catalog Federation Strategy*.

See <<{reference-prefix}ddf.catalog.federation.impl.CachingFederationStrategy,Federation Strategy configurations>> for all possible configurations.

==== Catalog Federation Strategy [[_catalogFederationStrategy]]

The Catalog Federation Strategy is the default federation strategy and is based on sorting metacards by the sorting parameter specified in the federated query.

The possible sorting values are:

* metacard's effective date/time
* temporal data in the query result
* distance data in the query result
* relevance of the query result

The supported sorting orders are ascending and descending.

The default sorting value/order automatically used is relevance descending.

[WARNING]
====
The Catalog Federation Strategy expects the results returned from the Source to be sorted based on whatever sorting criteria were specified.
If a metadata record in the query results contains null values for the sorting criteria elements, the Catalog Federation Strategy expects that result to come at the end of the result list.
====
