:title: GMD CSW Source
:type: source
:status: published
:link: _gmd_csw_source
:summary: Queries a GMD CSW APISO compliant service.
:federated: x
:connected:
:catalogprovider:
:storageprovider:
:catalogstore:

== {title}

The Geographic MetaData extensible markup language (GMD) CSW source supports the ability to search collections of descriptive information (metadata) for data, services, and related information objects, based on the https://portal.opengeospatial.org/files/?artifact_id=6495[Application Profile ISO 19115/ISO19119] {external-link}.

Use the GMD CSW source if querying a GMD CSW APISO compliant service.

.Installing the GMD CSW APISO v2.0.2 Source
The GMD CSW source is installed by default with a standard installation in the ${ddf-spatial} application.

Configure a new GMD CSW APISO v2.0.2 Source through the ${admin-console}:

* Navigate to the *${admin-console}*.
* Select the *${ddf-catalog}* application.
* Select the *Sources* tab.
* Add a New source.
* Name the New source.
* Select *GMD CSW ISO Federated Source* from *Binding Configurations*.

.Configuring the GMD CSW APISO v2.0.2 Source
Configure an existing GMD CSW APISO v2.0.2 Source through the ${admin-console}:

* Navigate to the *${admin-console}*.
* Select the *${ddf-catalog}* application.
* Select the *Sources* tab.
* Select the name of the source to edit.

See <<{reference-prefix}Gmd_Csw_Federated_Source,GMD CSW APISO v2.0.2 Source configurations>> for all possible configurations.
