:title: Solr Catalog Provider
:type: source
:status: published
:link: _solr_catalog_provider
:summary: Uses Solr as a catalog.
:federated:
:connected:
:catalogprovider: x
:storageprovider:
:catalogstore:

== {title}

The Solr Catalog Provider is included with a standard installation of ${branding}. There are two configurations available:

.[[_internal_solr]]Solr Server (default)::
${branding} is bundled with a distribution
of Apache Solr. This distribution includes special JAR libraries used by ${branding}.
This ${branding} scripts manage the starting and stopping of the Solr server.
Considerations include:

* No configuration necessary. Simply start ${branding} and ${branding} manages starting and
stopping the Solr server.
* Backup can be performed using ${branding} console's `backup` command.
* This configuration cannot be scaled larger than the single Solr server.
* All data is located inside the {$branding} home directory. If the Solr index grows
  large, the storage volume may run low on space.

.Installing Solr Server
No installation is required because ${branding} includes a distribution of Apache Solr.

.Configuring Solr Server
No configuration.

.[[_solr_cloud]]Solr Cloud
Solr Cloud is a cluster of distributed Solr servers used for high
availability and scalability. If the ${branding} needs to be available with little or no downtime,
 then the Solr Cloud configuration should be used. The general considerations for selecting
  this configuration are:

 * SolrCloud can scale to support over 2 billion indexed documents.
 * Has network overhead and requires additional protection to be secure.
 * Installation is more involved (requires Zookeeper)
 * Configuration and administration is more complex due to replication, sharding, etc.
 * No way to backup currently, but will automatically recover from system failure.

Configuration shared between Solr Server instances is managed by Zookeeper.
Zookeeper helps manage the overall structure.

.Solr Cloud Deployment
[ditaa,solrcloud-diagram,png]
....
  Container(JVM)         Solr Cloud
 +=-----------------+   +=--------------------+
 |                  |   |                     |
 | /-----------\    |   | +---------+         |
 | |cDEF       |    |   | |Solr cFF0|         |
 | | DDF       |    |   | +---------+         |
 | |           |    |   |                     |
 | |           |  http  |         +---------+ |
 | |           +------->|         |Solr cFF0| |
 | |           |    |   |         +---------+ |
 | |           |    |   |                     |
 | |           |    |   | +---------+         |
 | |           |    |   | |Solr cFF0|         |
 | \-----------/    |   | +---------+         |
 |                  |   |                     |
 +------------------+   +---------------------+
....

[NOTE]
====
The instructions on setting up Solr Cloud for ${branding} only include setup in a *NIX environment.
====

.Solr Cloud Prerequisites
Before Solr Cloud can be installed:

* ZooKeeper 3.4.5 (Refer to https://zookeeper.apache.org/doc/r3.1.2/zookeeperStarted.html#sc_Download for installation instructions.)
* *NIX environment
* JDK 8 or greater

[NOTE]
====
A minimum of three Zookeeper nodes required.
Three Zookeeper nodes are needed to form a quorum.
A three Zookeeper ensemble allows for a single server to fail and the service will still be available.
More Zookeeper nodes can be added to achieve greater fault tolerance. The total number of nodes must always be an odd number.
See https://lucene.apache.org/solr/guide/7_4/setting-up-an-external-zookeeper-ensemble.html#SettingUpanExternalZooKeeperEnsemble-SettingupaZooKeeperEnsemble[
Setting Up an External Zoo Keeper Ensemble] for more information.
====

.Installing Solr Cloud

Before starting the install procedure, download the extension jars. The jars are needed to support
geospatial and xpath queries and need to be installed on every Solr server instance after the Solr
Cloud installation instructions have been followed.

The JARs can be found here:

.. http://artifacts.codice.org/service/local/repositories/releases/content/org/codice/thirdparty/jts/1.14.0_1/jts-1.14.0_1.jar
.. http://artifacts.codice.org/service/local/artifact/maven/content?r=public&g=ddf.platform.solr&a=solr-xpath&v=${ddf.version}

Repeat the following procedure for each Solr server instance that will be part of the Solr Cloud cluster:

. Refer to https://cwiki.apache.org/confluence/display/solr/Apache+Solr+Reference+Guide for installation instructions.
. Copy downloaded jar files to: `<SOLR_INSTALL_DIR>/server/solr-webapp/webapp/WEB-INF/lib/`

[NOTE]
====
A minimum of two Solr server instances is required. Each Solr server instance must have a minimum of two shards.
Having two Solr server instances guarantees that at least one Solr server is available if one fails.
The two shards enables the document mapping to be restored if one shard becomes unavailable.
====

.Configuring Solr Cloud
. On the ${branding} server, edit `${home_directory}/etc/custom.system.properties`:
.. Comment out the Solr Client Configuration for *Http Solr Client* section.
.. Uncomment the section for the *Cloud Solr Client*:
.. Set `solr.cloud.zookeeper` to `<ZOOKEEPER_1_HOSTNAME>:<PORT_NUMBER>`, `<ZOOKEEPER_2_HOSTNAME>:<PORT_NUMBER>`, `<ZOOKEEPER_n_HOSTNAME>:<PORT_NUMBER>`
.. Set `solr.data.dir` to the desired data directory.

.Solr Cloud System Properties
----
solr.client = CloudSolrClient
solr.data.dir = ${karaf.home}/data/solr
solr.cloud.zookeeper = zk1:2181,zk2:2181,zk3:2181
----
