:title: ${ddf-geowebcache} Application Reference
:status: published
:type: applicationReference
:summary: Enables a server providing a map tile cache and tile service aggregation.
:order: 04

== {title}

${ddf-geowebcache} enables a server providing a map tile cache and tile service aggregation.

[WARNING]
====
The ${ddf-geowebcache} application is currently in an EXPERIMENTAL status and should not be installed on a security-hardened installation.
====

${ddf-geowebcache} enables a server providing a tile cache and tile service aggregation.
See (http://geowebcache.org[GeoWebCache] {external-link}) for more information.
This application also provides an administrative plugin for the management of GeoWebCached layers.
GeoWebCache also provides a user interface for previewing, truncating, or seeding layers at \${secure_url}/geowebcache/.

===  ${ddf-geowebcache} Application Prerequisites

None.

===  Installing ${ddf-geowebcache}

Install the ${ddf-geowebcache} application through the ${admin-console}.

. Navigate to the *${admin-console}*.
. Select the *System* tab.
. Select the *Features* tab.
. Install the `geowebcache-app` feature.

===  Configuring ${ddf-geowebcache}

${ddf-geowebcache} can be configured to cache layers locally, using the following procedures.

==== Adding GeoWebCache Layers

Add layers to the local cache:

. Navigate to the ${admin-console}.
. Select the ${ddf-geowebcache} Application.
. Select the *GeoWebCache Layers* tab.
. Click the *Add* button.
. Enter the data in the fields provided.
. If necessary, click the *Add* button to add additional MIME types.
. If necessary, click the *Add* button to add additional WMS Layer Names.

.Add Layer
[cols="1,1m,1,2,1" options="header"]
|===
|Name
|Property
|Type
|Description
|Default Value

|Name
|
|String
|Unique name assigned.
|

|Mime Formats
|
|String
|List of mime formats used.
|

|URL
|
|URI
|URL location of layer to add.
|

|WMS Layer Name
|
|String
|The name(s) of WMS layers that exist at the URL specified above. If no WMS Layer names are specified, GeoWebCache will look for the Layer Name specified in the name field.  Otherwise, it will attempt to find all layer names added here and combine them into one layer.
|

|===

==== Editing GeoWebCache Layers

. Navigate to the ${admin-console}.
. Select the ${ddf-geowebcache} application.
. Navigate to the *GeoWebCache Layers* tab.
. Click the *Name* field of the layer to edit.

==== Removing GeoWebCache Layers

. Click the *Delete* icon at the end of the row of the layer to be deleted.

==== Configuring GWC Disk Quota

Storage usage for a GeoWebCache server is managed by a `diskquota.xml` file with configuration details to prevent image-intensive data from filling the available storage.

To view the disk quota XML representative: \${secure_url}/geowebcache/rest/diskquota.xml

To update the disk quota, a client can post a new XML configuration: `curl -v -k -XPUT -H "Content-type: text/xml" -d ${at-symbol}diskquota.xml "${secure_url}/geowebcache/rest/diskquota.xml"`

.Example `diskquota.xml`
[source,xml,linenums]
----
<gwcQuotaConfiguration>
  <enabled>true</enabled>
  <diskBlockSize>2048</diskBlockSize>
  <cacheCleanUpFrequency>5</cacheCleanUpFrequency>
  <cacheCleanUpUnits>SECONDS</cacheCleanUpUnits>
  <maxConcurrentCleanUps>5</maxConcurrentCleanUps>
  <globalExpirationPolicyName>LFU</globalExpirationPolicyName>
  <globalQuota>
    <value>100</value>
    <units>GiB</units>
  </globalQuota>
  <layerQuotas/>
</gwcQuotaConfiguration>
----

See http://geowebcache.org/docs/current/configuration/diskquotas.html[Disk Quotas] for more information on configuration options for disk quota.
