:title: ${ddf-resource-management}
:status: published
:type: applicationReference
:summary: Provides administrative functionality to monitor and manage data usage on the system.
:order: 08

== {title} Application Reference

The ${ddf-resource-management} Application provides administrative functionality to monitor and manage data usage on the system.
This application allows an administrator to:

* View data usage.
* Set limits on users.
* View and terminate searches that are in progress.

Components of the ${ddf-resource-management} application include:

${ddf-resource-management} Data Usage Tab:: View data usage and configure users' data limits and reset times for those limits.

${ddf-resource-management} Queries Tab:: View and cancel actively running queries.

=== ${ddf-resource-management} Prerequisites

To use the ${ddf-resource-management} Application, the following apps/features must be installed:

* ${ddf-platform}
* ${ddf-security}
* ${ddf-admin}
* ${ddf-catalog}

=== Installing ${ddf-resource-management}

Install the ${ddf-resource-management} application through the ${admin-console}.

. Navigate to the *${admin-console}*.
. Select the *System* tab.
. Select the *Features* tab.
. Install the `resourcemanagement-app` feature.

