:title: ${ddf-security}
:status: published
:type: applicationReference
:summary: Provides authentication, authorization, and auditing services.
:order: 09

== {title} Application Reference

The Security application provides authentication, authorization, and auditing services for the ${branding}.
These services comprise both a framework that developers and integrators can extend as well as a reference implementation that meets security requirements.

This section documents the installation, maintenance, and support of this application.

.Applications Included in ${ddf-security}
* Security Core
* Security Encryption
* Security IdP
* Security PEP
* Security PDP
* Security STS

===  ${ddf-security} Prerequisites

To use the ${ddf-security} application, the following applications/features must be installed:

* ${ddf-platform}

===  Installing ${ddf-security}

Install the ${ddf-security} application through the ${admin-console}.

. Navigate to the *${admin-console}*.
. Select the *System* tab.
. Select the *Features* tab.
. Install the `security-app` feature.
