:title: ${ddf-spatial}
:status: published
:type: applicationReference
:summary: Provides KML transformer and a KML network link endpoint that allows a user to generate a View-based KML Query Results Network Link.
:order: 11

== {title} Application Reference

The ${ddf-spatial} Application provides KML transformer and a KML network link endpoint that allows a user to generate a View-based KML Query Results Network Link.

=== Offline Gazetteer Service

In the ${ddf-spatial} Application, the `offline-gazetteer` is installed by default.
This feature enables you to use an offline source of GeoNames data (as an alternative to the GeoNames Web service enabled by the `webservice-gazetteer` feature) to perform searches via the gazetteer search box in the Search UI.

Installing the `offline-gazetteer-index` feature will provide a small set of GeoNames data to use with the offline gazetteer. The GeoNames data is stored as metacards in the core catalog and are tagged with `geonames` and `gazetteer`. This collection of GeoNames metacards can be expanded or updated by using the `gazetteer:update` command.

==== ${ddf-spatial} Gazetteer Console Commands

The `gazetteer` commands provide the ability to interact with the local GeoNames metacard collection in the core catalog. These GeoNames metacards are used by the `offline-gazetteer` feature, which is an optional feature available in this application and is explained above. Note that these commands are only available if the `offline-gazetteer` feature is installed.

.Gazetteer Command Descriptions
[cols="2,8a" options="header"]
|===
|Command
|Description

|`gazetteer:update`
|Adds new gazetteer metacards to the core catalog from a resource.

The resource argument can be one of three types:

* a local file path to a `.txt`, `.zip`, or `.geo.json` GeoNames data file. If a path to a file ends in .geo.json, it will processed as a geoJSON feature collection and imported as supplementary shape data for GeoNames entries.
* a URL to a `.txt` or `.zip` GeoNames data file. GeoJSON URLs are not supported.
* a keyword to automatically process a GeoNames file from from http://download.geonames.org/export/dump. Valid keywords include
  ** a country code, which will add the country as GeoNames metacards in the core catalog. The full list of country codes available can be found in http://download.geonames.org/export/dump/countryInfo.txt.
  ** `cities1000`, `cities5000`, and `cities15000`, which will add cities to the index that have at least 1000, 5000, or 15000 people, respectively.
  ** `all`, which will download all of the current country codes. This process may take some time.

The `-c` or `--create` flag can be used to clear out the existing gazetteer metacards before adding new entries.

|`build-suggester-index`
|Builds the Solr suggester index used for placename autocompletion in Intrigue when using the
offline gazetteer. This index is built automatically whenever gazetteer metacards are created,
updated, or deleted, but if those builds fail then this command can be used to attempt to build the
index again.

|===

===  ${ddf-spatial} Prerequisites

To use the ${ddf-spatial} Application, the following apps/features must be installed:

* ${ddf-platform}
* ${ddf-catalog}

===  Installing ${ddf-spatial}

Install the ${ddf-spatial} application through the ${admin-console}.

. Navigate to the *${admin-console}*.
. Select the *System* tab.
. Select the *Features* tab.
. Install the `spatial-app` feature.
