:title: Auditing
:type: configuringAdminConsole
:status: published
:summary: Configure auditing.
:order: 14

==== Auditing

* *{hardening-step}*

Audit logging captures security-specific system events for monitoring and review.
${ddf-branding} provides a <<_security_logging_plugin,Audit Plugin>> that logs all catalog transactions to the `security.log`.
Information captured includes user identity, query information, and resources retrieved.

Follow all operational requirements for the retention of the log files.
This may include using cryptographic mechanisms, such as encrypted file volumes or databases, to protect the integrity of audit information.

[NOTE]
====
The Audit Log default location is `<${branding}_HOME>/data/log/security.log`
====

.Audit Logging Best Practices
[NOTE]
====
For the most reliable audit trail, it is recommended to configure the operational environment of the ${branding} to generate alerts to notify adminstrators of:

* auditing software/hardware errors
* failures in audit capturing mechanisms
* audit storage capacity (or desired percentage threshold) being reached or exceeded.
====

[WARNING]
====
The security audit logging function does not have any configuration for audit reduction or report generation.
The logs themselves could be used to generate such reports outside the scope of ${branding}.
====

===== Enabling Fallback Audit Logging

* *{hardening-step}*

In the event the system is unable to write to the `security.log` file, ${branding} must be configured to fall back to report the error in the application log:

* edit `<INSTALL_HOME>/etc/org.ops4j.pax.logging.cfg`
** uncomment the line (remove the `#` from the beginning of the line) for `log4j2` (`org.ops4j.pax.logging.log4j2.config.file = ${karaf.etc}/log4j2.config.xml`)
** delete all subsequent lines
* edit `<INSTALL_HOME>/etc/log4j2.config.xml`
** find the entry for the `securityBackup` appender. (see example)
** change value of `filename` and prefix of `filePattern` to the name/path of the desired failover security logs (<NEW_FILE_NAME>)

.`securityBackup` Appender Before
[source,xml,linenums]
----
<RollingFile name="securityBackup" append="true" ignoreExceptions="false"
                     fileName="${sys:karaf.data}/log/securityBackup.log"
                     filePattern="${sys:karaf.data}/log/securityBackup.log-%d{yyyy-MM-dd-HH}-%i.log.gz">
----

.`securityBackup` Appender After
[source,xml,linenums]
----
<RollingFile name="securityBackup" append="true" ignoreExceptions="false"
                     fileName="${sys:karaf.data}/log/<NEW_FILE_NAME>"
                     filePattern="${sys:karaf.data}/log/<NEW_FILE_NAME>-%d{yyyy-MM-dd-HH}-%i.log.gz">
----

[WARNING]
====
If the system is unable to write to the `security.log` file on system startup, fallback logging will be unavailable.
Verify that the `security.log` file is properly configured and contains logs before configuring a fall back.
====
