:title: Catalog Filtering
:type: configuringAdminConsole
:status: published
:summary: Catalog filtering.
:order: 13

==== Catalog Filtering

Filtering is performed by an Access plugin, after a query or delete has been performed or before ingest has been performed.

===== How Filtering Works

Each metacard result can contain security attributes that are pulled from the metadata record after being processed by a `PolicyPlugin` that populates this attribute.
The security attribute is a Map containing a set of keys that map to lists of values.
The metacard is then processed by a filter plugin that creates a `KeyValueCollectionPermission` from the metacard's security attribute.
This permission is then checked against the user subject to determine if the subject has the correct claims to view that metacard.
The decision to filter the metacard eventually relies on the installed <<_security_pdp,Policy Decision Point>> (PDP).
The PDP that is being used returns a decision, and the metacard will either be filtered or allowed to pass through.

How a metacard gets filtered is left up to any number of FilterStrategy implementations that might be installed.
Each FilterStrategy will return a result to the filter plugin that says whether or not it was able to process the metacard, along with the metacard or response itself.
This allows a metacard or entire response to be partially filtered to allow some data to pass back to the requester.
This could also include filtering any products sent back to a requester.

The security attributes populated on the metacard are completely dependent on the type of the metacard.
Each type of metacard must have its own `PolicyPlugin` that reads the metadata being returned and then returns the appropriate attributes.

.Example (represented as simple XML for ease of understanding):
[source,xml,linenums]
----
<metacard>
    <security>
        <map>
            <entry assertedAttribute1="A,B" />
            <entry assertedAttribute2="X,Y" />
            <entry assertedAttribute3="USA,GBR" />
            <entry assertedAttribute4="USA,AUS" />
        </map>
    </security>
</metacard>
----

[source,xml,linenums]
----
<user>
    <claim name="subjectAttribute1">
        <value>A</value>
        <value>B</value>
    </claim>
    <claim name="subjectAttribute2">
        <value>X</value>
        <value>Y</value>
    </claim>
    <claim name="subjectAttribute3">
        <value>USA</value>
    </claim>
    <claim name="subjectAttribute4">
        <value>USA</value>
    </claim>
</user>
----

In the above example, the user's claims are represented very simply and are similar to how they would actually appear in a SAML 2 assertion.
Each of these user (or subject) claims will be converted to a `KeyValuePermission` object.
These permission objects will be implied against the permission object generated from the metacard record.
In this particular case, the metacard might be allowed if the policy is configured appropriately because all of the permissions line up correctly.

===== Configuring Filtering Policies

There are two options for processing filtering policies: internally, or through the use of a policy formatted in eXtensible Access Control Markup Language (XACML).
The procedure for setting up a policy differs depending on whether that policy is to be used internally or by the external XACML processing engine.
Setting up an internal policy is as follows:

. Navigate to the *${admin-console}*.
. Select the *${ddf-security}* application.
. Click the *Configuration* tab.
. Click on the *Security AuthZ Realm* configuration.
. Add any attribute mappings necessary to map between subject attributes and the attributes to be asserted.
.. For example, the above example would require two Match All mappings of `subjectAttribute1=assertedAttribute1` and `subjectAttribute2=assertedAttribute2``
.. Match One mappings would contain `subjectAttribute3=assertedAttribute3` and `subjectAttribute4=assertedAttribute4`.

With the `security-pdp-authz` feature configured in this way, the above Metacard would be displayed to the user.
Note that this particular configuration would not require any XACML rules to be present.
All of the attributes can be matched internally and there is no reason to call out to the external XACML processing engine.
For more complex decisions, it might be necessary to write a XACML policy to handle certain attributes.

To set up a XACML policy, place the desired XACML policy in the `<distribution root>/etc/pdp/policies` directory and update the included `access-policy.xml` to include the new policy.
This is the directory in which the PDP will look for XACML policies every 60 seconds.
A sample XACML policy is located at the end of this page.
Information on specific bundle configurations and names can be found on the Security PDP application page.

===== Catalog Filter Policy Plugins

Several Policy Plugins for catalog filtering exist currently: <<_metacard_attribute_security_policy_plugin,Metacard Attribute Security Policy Plugin>> and <<_xml_attribute_security_policy_plugin,XML Attribute Security Policy Plugin>>.
These Policy Plugin implementations allow an administrator to easily add filtering capabilities to some standard Metacard types for all ${ddf-catalog} operations.
These plugins will place policy information on the Metacard itself that allows the Filter Plugin to restrict unauthorized users from viewing content they are not allowed to view.

===== Creating a XACML Policy

This document assumes familiarity with the XACML schema and does not go into detail on the XACML language.
When creating a policy, a target is used to indicate that a certain action should be run only for one type of request.
Targets can be used on both the main policy element and any individual rules.
Targets are geared toward the actions that are set in the request.
These actions generally consist of the standard CRUD operations (create, read, update, delete) or a SOAPAction if the request is coming through a SOAP endpoint.

[NOTE]
====
These are only the action values that are currently created by the components that come with ${branding}.
Additional components can be created and added to ${branding} to identify specific actions.
====

In the examples below, the policy has specified targets for the above type of calls.
For the Filtering code, the target was set for "filter", and the Service validation code targets were geared toward two services: `query` and `LocalSiteName`.
In a production environment, these actions for service authorization will generally be full URNs that are described within the SOAP WSDL.

===== XACML Policy Attributes

Attributes for the XACML request are populated with the information in the calling subject and the resource being checked.

===== XACML Policy Subject

The attributes for the subject are obtained from the SAML claims and populated within the XACML policy as individual attributes under the `urn:oasis:names:tc:xacml:1.0:subject-category:access-subject` category.
The name of the claim is used for the `AttributeId` value.
Examples of the items being populated are available at the end of this page.

===== XACML Policy Resource

The attributes for resources are obtained through the permissions process.
When checking permissions, the XACML processing engine retrieves a list of permissions that should be checked against the subject.
These permissions are populated outside of the engine and should be populated with the attributes that should be asserted against the subject.
When the permissions are of a key-value type, the key being used is populated as the AttributeId value under the urn:oasis:names:tc:xacml:3.0:attribute-category:resource category.

===== Using a XACML Policy

To use a XACML policy, copy the XACML policy into the `<${branding}_HOME>/etc/pdp/policies` directory.
