:title: Configuring Managed Service Factory Bundles
:type: configuringConfigFile
:status: published
:summary: Configuring Managed Service Factory bundles.
:order: 07

==== Configuring Managed Service Factory Bundles

Services that are created using a Managed Service Factory can be configured using `.config` files as well.
These configuration files, however, follow a different naming convention than `.cfg` files.
The filenames must start with the Managed Service Factory PID, be followed by a dash and a unique identifier, and have a `.config` extension.
For instance, assuming that the Managed Service Factory PID is `org.codice.ddf.factory.pid` and two instances of the service need to be configured, files `org.codice.ddf.factory.pid-<UNIQUE ID 1>.config` and `org.codice.ddf.factory.pid-<UNIQUE ID 2>.config` should be created and added to `<${branding}_HOME>/etc`.

The unique identifiers used in the file names have no impact on the order in which the configuration files are processed.
No specific processing order should be assumed.
Also, a new service will be created and configured every time a configuration file matching the Managed Service Factory PID is added to the directory, regardless of the _unique id_ used.

Any `service.factoryPid` and `service.pid` values in these `.config` files will be overridden by the values parsed from the file name, so `.config` files should not contain these properties.

===== File Format

The basic syntax of the `.config` configuration files is similar to the older `.cfg` files but introduces support for lists and types other than simple strings.
The type associated with a property must match the type attribute used in the corresponding `metatype.xml` file when applicable.

The following table shows the format to use for each property type supported.

.Property Formats
[cols="1,2,3" options="header"]
|===
|Type
|Format
|Example

|Strings
|name="value"
|`name="john"`

|Booleans
|name=B"true\|false"
|`authorized=B"true"`

|Integers
|name=I"value"
|`timeout=I"60"`

|Longs
|name=L"value"
|`diameter=L"10000"`

|Floats
|name=F"value"
|`cost=F"0x41280000"`

|Doubles
|name=D"value"
|`latitude=D"0x423417f6"`

|Lists of Strings
|name=["value1","value2",…​]
|`complexStringArray=["{\"url\"\ \"http://test.sample.com\"\ \"layers\"\ [\"0\"]\ \"VERSION\"\ \"1.1\|1.2\"\ \"image/png\"}\ \"beta\"\ 1}","{\"url\"\ \"http://test.sample.com"\ 0.5}","/solr\=SAML\|PKI\|basic","/security-config\=SAML\|basic"]`

|Lists of Booleans
|name=B["true\|false","true\|false",…​]
|`authorizedList=B["true","false"]`

|Lists of Integers
|name=I["value1","value2",…​]
|`sizes=I["10","20","30"]`

|Lists of Longs
|name=L["value1","value2",…​]
|`sizes=L["100","200","300"]`

|Lists of Floats
|name=F["value1","value2",…​]
|`sizes=F["0x3f8ccccd","0x400ccccd","0x40533333"]`

|Lists of Doubles
|name=D["value1","value2",…​]
|`sizes=D["0x3f8fbe77","0x400ef9db","0x4056147b"]`

|Vectors of Strings
|name=("value1","value2",…​)
|`names=("A","B","C")`

|Vectors of Booleans
|name=B("true\|false","true\|false",…​)
|`authorizedVector=B("true","false")`

|Vectors of Integers
|name=I("value1","value2",…​)
|`sizes=I("10","20","30")`

|Vectors of Longs
|name=L("value1","value2",…​)
|`sizes=L("100","200","300")`

|Vectors of Floats
|name=F("value1","value2",…​)
|`sizes=F("0x3f8ccccd","0x400ccccd","0x40533333")`

|Vectors of Doubles
|name=D("value1","value2",…​)
|`sizes=D("0x3f8fbe77","0x400ef9db","0x4056147b")`

|===

[NOTE]
====
* Lists and Vectors of values can be prefixed with any of the supported types (`B`, `I`, `L`, `F` or `D`).
* To prevent any configuration issues, the `=` signs used in values should be escaped using a backslash (`\`).
* Boolean values will default to `false` if any value other than `true` is provided.
* Escape character in values must be used for double quotes (`"`) and spaces, but cannot be used with `{` `}` or `[` `]` pairings.
* Floats and Longs must be written in the IEEE 754 format. For example, the example for the Floats and Doubles in the table above correspond to 10.50 and 45.0234, respectively.
====

.Sample configuration file
[source,linenums]
----
authenticationTypes=["/\=SAML|GUEST","/admin\=SAML|basic","/system\=basic","/solr\=SAML|PKI|basic","/sources\=SAML|basic","/security-config\=SAML|basic","/search\=basic"]

realms=["/\=karaf"]

requiredAttributes=["/\=","/admin\={http://schemas.xmlsoap.org/ws/2005/05/identity/claims/role\=admin}","/solr\={http://schemas.xmlsoap.org/ws/2005/05/identity/claims/role\=admin}","/system\={http://schemas.xmlsoap.org/ws/2005/05/identity/claims/role\=admin}","/security-config\={http://schemas.xmlsoap.org/ws/2005/05/identity/claims/role\=admin}"]

whiteListContexts=["/services/SecurityTokenService","/services/internal/metrics","/services/saml","/proxy","/services/csw"]
----
