:title: Environment Hardening
:type: configuringOther
:status: published
:summary: Environment security mitigations.
:order: 00

==== Environment Hardening

* *{hardening-step}*

[IMPORTANT]
====
It is recommended to apply the following security mitigations to the ${branding}.
====


[cols="1,3,6",options="header]
|===

|Protocol/Type
|Risk
|Mitigation

|JMX
|tampering, information disclosure, and unauthorized access
a|* Stop the management feature using the command line console: `feature:stop management`. +

|File System Access
|tampering, information disclosure, and denial of service
a|Set OS File permissions under the `<${branding}_HOME>` directory (e.g. `/deploy`, `/etc`) to ensure unauthorized viewing and writing is not allowed.

 If Caching is installed:

* Set permissions for the installation directory `/data/product-cache` such that only the ${branding} process and users with the appropriate SCI controls and classification levels can view any stored product. +
* Caching can be turned off as well to mitigate this risk. +
** To disable caching, navigate to ${ddf-catalog}. +
** Select *Resource Download Settings*. +
** Uncheck the `Enable Product Caching` box. +
* Install ${ddf-security} to ensure only the appropriate users are accessing the products. +
** From the ${admin-console}, select *Manage*. +
** Install ${ddf-security}, if applicable. +
* Cached files are written by the user running the ${branding} `process/application`. +

On system: ensure that not everyone can change ACLs on your object.

|SSH
|tampering, information disclosure, and denial of service
a|Create accounts for authentication (modify the default user's password) or remove ssh feature. By definition the connection will be secure when authenticated. Optionally, disable the ssh port (`default: 8101`) and set the `karaf.startRemoteShell` system property to false.

[WARNING]
====
Disabling ssh will be more secure, but will disable any direct command line access to the ${branding}.
====

Set `karaf.shutdown.port=-1` in `etc/custom.properties` or `etc/config.properties`.

|SSL/TLS
|man-in-the-middle, information disclosure
a|Update the `<${branding}_HOME>/etc/org.ops4j.pax.web.cfg` file to add the entry `org.ops4j.pax.web.ssl.clientauthneeded=true`.

[WARNING]
====
Setting this configuration may break compatibility to legacy systems that do not support two-way SSL.
====

[WARNING]
====
Setting this configuration will require a certificate to be installed in the browser.
====

|Session Inactivity Timeout
|unauthorized access
a|Update the Session configuration to have no greater than a 10 minute Session Timeout. +

 * Navigate to the *${admin-console}*. +
 * Select the *${ddf-security}* application. +
 * Select the *Configuration* tab. +
 * Select `Session`. +
 * Set `Session Timeout (in minutes)` to `10` (or less). +
|===
