:title: Environment Hardening
:type: configuringOther
:status: published
:summary: Environment security mitigations.
:order: 00

==== Environment Hardening

* *{hardening-step}*

[IMPORTANT]
====
It is recommended to apply the following security mitigations to the ${branding}.
====


[cols="1,3,6",options="header]
|===

|Protocol/Type
|Risk
|Mitigation

|JMX
|tampering, information disclosure, and unauthorized access
a|* Stop the management feature using the command line console: `feature:stop management`. +

|File System Access
|tampering, information disclosure, and denial of service
a|Set OS File permissions under the `<${branding}_HOME>` directory (e.g. `/deploy`, `/etc`) to ensure unauthorized viewing and writing is not allowed.

 If Caching is installed:

* Set permissions for the installation directory `/data/product-cache` such that only the ${branding} process and users with the appropriate SCI controls and classification levels can view any stored product. +
* Caching can be turned off as well to mitigate this risk. +
** To disable caching, navigate to ${ddf-catalog}. +
** Select *Resource Download Settings*. +
** Uncheck the `Enable Product Caching` box. +
* Install ${ddf-security} to ensure only the appropriate users are accessing the products. +
** From the ${admin-console}, select *Manage*. +
** Install ${ddf-security}, if applicable. +
* Cached files are written by the user running the ${branding} `process/application`. +

On system: ensure that not everyone can change ACLs on your object.

|SSH
|tampering, information disclosure, and denial of service
a|By default, SSH access is disabled in ${branding}. To turn it on, edit the `<${branding}_HOME>/etc/org.apache.karaf.shell.cfg`
file, uncommenting the `sshPort` property. SSH can also be authenticated and authorized through an external Realm,
such as LDAP. This can be accomplished by editing the `<${branding}_HOME>/etc/org.apache.karaf.shell.cfg` file and setting the
value for `sshRealm`, e.g. to `ldap`. No restart of ${branding} is necessary after this change.

By definition, all connections over SSH will be authenticated and authorized and secure from eavesdropping.

[WARNING]
====
Enabling SSH will expose your file system such that any user with access to your ${branding} shell will
have read/write access to all directories and files accessible to your installation user. It is not
recommended in a secure environment.
====

Set `karaf.shutdown.port=-1` in `<${branding}_HOME>/etc/custom.properties` or `<${branding}_HOME>/etc/config.properties`.

|SSL/TLS
|man-in-the-middle, information disclosure
a|Update the `<${branding}_HOME>/etc/org.ops4j.pax.web.cfg` file to add the entry `org.ops4j.pax.web.ssl.clientauthneeded=true`.

[WARNING]
====
Setting this configuration may break compatibility to legacy systems that do not support two-way SSL.
====

[WARNING]
====
Setting this configuration will require a certificate to be installed in the browser.
====

|Session Inactivity Timeout
|unauthorized access
a|Update the Session configuration to have no greater than a 10 minute Session Timeout. +

 * Navigate to the *${admin-console}*. +
 * Select the *${ddf-security}* application. +
 * Select the *Configuration* tab. +
 * Select `Session`. +
 * Set `Session Timeout (in minutes)` to `10` (or less). +
|===
