:title: Removing Default Users
:type: configuringConfigFile
:status: published
:summary: Removing default users.
:order: 03

==== Removing Default Users

* *{hardening-step}*

Once ${branding} is configured to use an external user (such as LDAP), remove the `users.properties` file from the `<INSTALL_HOME>/etc` directory.
Use of a `users.properties` file should be limited to emergency recovery operations and replaced as soon as effectively possible.

.Emergency Use of `users.properties` file
[NOTE]
====
Typically, the ${branding} does not manage passwords.
Authenticators are stored in an external identity management solution. However, ${branding} may be configure the `users.properties` file to include an account with a username and password for emergency use.

If a system recovery account is configured in `users.properties`, ensure:

* The use of this account should be for as short a time as possible.
* The default username/password of "`admin/admin`" should not be used.
* All organizational standards for password complexity should still apply.
* The password should be encrypted. For steps on how, see the section "Passwords Encryption" at https://karaf.apache.org/manual/latest/security.
====

[NOTE]
====
It is recommended to perform yearly reviews of accounts for compliance with organizational account management requirements.
====
