:title: Managing Keystores and Certificates
:type: configuringIntro
:status: published
:summary: Keystore and certificate instructions.
:order: 0502

=== Managing Keystores and Certificates

* *{hardening-step}*

${branding} uses certificates in two ways:

. Ensuring the privacy and integrity of messages sent or received over a network.
. Authenticating an incoming user request.

To ensure proper configuration of keystore, truststore, and certificates, follow the options below according to situation.

.Configuring Certificates Workflow
[ditaa,configuring-certificates-workflow,png]
....
                      /----------------------------\
                      |                            |
                      |      Provided with         |
                      |      server keystore?      |
                      |                   cDEF     |
                      \----+---------------------+-/
        +--+               |                     |
        |1 |            Yes|                     |No
        +--+               v                     v
      /----------------------------\       /----------------------------\        /----------------------------\
      |                            |       |                            |        |                            |
      |                            |       | Provided with private key  |        |   A private key and        |
      |                            |       | & signed certificate for   |  No    |   signed certificate       |
      |                            |       | the server?                |------->|   are required             |
      | Replace default keystore   |       |                 cDEF       |        |                  cF00      |
      | with provided file and     |       \------------+---------------/        \----------------------------/
      | edit system.properties     |        +--+        |
      | file with filenames,       |        |2 |     Yes|
      | passwords, file types      |        +--+        v
      |                            |       /----------------------------\
      |                            |       |                            |
      |                            |       | Create a private-key-entry |
      |                            |       | in the serverKeystore file |
/---->|                            |       | using the provided private |
|     |                            |       | key and signed certificate |
|     |                   cCCC     |       |                 cCCC       |
|     \--------------------+-------/       \----+-----------------------/
|                          |                    |
|                          |                    |
|                          v                    v
|                      /----------------------------\                            /----------------------------\
|                      |                            |                            |                            |
|                      |  The truststore file has   |       Yes                  | Restart server to          |
|                      |  the proper certificates?  +--------------------------->| complete configuration     |
|                      |                 cDEF       |                            |                   c0F0     |
|                      \--+----------------------+--/                            \----------------------------/
|                         |
|                         |No
|                         v
|     /----------------------------\       /----------------------------\        /----------------------------\
|     |                            |  No   |                            |        |                            |
|     |     Provided with          |------>|   Provided with CA         |  No    |   A CA certificate         |
|     |     trust keystore?        |  +--->|   certificate?             |------->|   is required              |
|     |                   cDEF     |  |    |                    cDEF    |        |                   cF00     |
|     \-----------+----------------/  |    \---------+------------------/        \----------------------------/
|       +--+      |                   |              |
|       |3 |   Yes|                   |              |Yes
|       +--+      v                   |              |
|     /----------------------------\  |     +--+     |
|     |                            |  |     |4 |     |
|     |  Replace truststore with   |  |     +--+     v
|     |  provided file             |  |    /-----------------------------\
|     |                 cCCC       |  |    |                             |
|     \-----------+----------------/  |    |  Import the CA certificate  |
|                 |                   |    |  into the serverTrustStore  |
|                 |                 No|    |  and serverKeystore files   |
|                 v                   |    |                   cCCC      |
|     /----------------------------\  |    \---------+-------------------/
|     |                            +--+       ^      |
|     | Server keystore includes   |          |      |
|     | the CA certificate used    |          |      |
|     | to sign the server's       |   Yes    |      |
|     | certificate?               |----------/      |
|     |                  cDEF      |                 |
|     \----------------------------/                 |
|                                                    |
|                                                    |
\----------------------------------------------------/
....

Jump to the steps referenced in the diagram:

.Certificate Workflow Steps
. <<_adding_an_existing_server_keystore,Adding an Existing Keystore>>
. <<_creating_a_new_keystore_truststore_with_an_existing_certificate_and_private_key,Creating a New Keystore/Truststore with an Existing Certificate and Private Key>>
. <<_adding_an_existing_server_truststore,Adding an Existing Truststore>>
. <<_creating_a_server_keystore,Creating a Server Keystore>>
.. <<_creating_a_server_truststore,Creating a Server Truststore>>

==== Managing Keystores

Certificates, and sometimes their associated private keys, are stored in keystore files.
${branding} includes two default keystore files, the server key store and the server trust store.
The server keystore holds the certificates and private keys that ${branding} uses to identify itself to other nodes on the network.
The truststore holds the certificates of nodes or other entities that ${branding} needs to trust.

===== Adding an Existing Server Keystore

If provided an existing keystore for use with ${branding}, follow these steps to replace the default keystore.

. Remove the default keystore at `etc/keystore/serverKeystore.jks`.
. Add the desired keystore file to the `etc/keystore` directory.
. Edit `system.properties` file to set filenames and passwords.
.. If using a type of keystore other than `jks` (such as `pkcs12`), change the `javax.net.ssl.keyStoreType` property as well.
. If the truststore has the correct certificates, restart server to complete configuration.
.. If provided with an existing server truststore, continue to <<_adding_an_existing_server_truststore,Adding an Existing Server Truststore>>.
.. Otherwise, <<_creating_a_server_keystore,create a server truststore>>.

====== Adding an Existing Server Truststore

. Remove the default truststore at `etc/keystore/serverTruststore.jks`.
. Add the desired truststore file to the `etc/keystore` directory.
. Edit `system.properties` file to set filenames and passwords.
.. If using a type of truststore other than `jks` (such as `pkcs12`), change the `javax.net.ssl.trustStoreType` property as well.

If the provided server keystore does not include the CA certificate that was used to sign the server's certificate, <<_creating_a_server_keystore,add the CA certificate into the `serverKeystore` file>>.

====== Creating a New Keystore/Truststore with an Existing Certificate and Private Key

If provide an existing certificate create a new keystore and truststore with it.

[NOTE]
====
${branding} requires that the keystore contains both the private key and the CA.
====

. [[_creating_a_server_keystore]]Using the private key, certificate, and CA certificate, create a new keystore containing the data from the new files.
+
[source]
----
cat client.crt >> client.key
openssl pkcs12 -export -in client.key -out client.p12
keytool -importkeystore -srckeystore client.p12 -destkeystore serverKeystore.jks -srcstoretype pkcs12 -alias 1
keytool -changealias -alias 1 -destalias client -keystore serverKeystore.jks
keytool -importcert -file ca.crt -keystore serverKeystore.jks -alias "ca"
keytool -importcert -file ca-root.crt -keystore serverKeystore.jks -alias "ca-root"
----
+
. [[_creating_a_server_truststore]]Create the truststore using only the CA certificate. Based on the concept of CA signing, the CA should be the only entry needed in the truststore.
+
----
keytool -import -trustcacerts -alias "ca" -file ca.crt -keystore truststore.jks
keytool -import -trustcacerts -alias "ca-root" -file ca-root.crt -keystore truststore.jks
----
+
. Create a PEM file using the certificate, as some applications require that format.
+
----
openssl x509 -in client.crt -out client.der -outform DER
openssl x509 -in client.der -inform DER -out client.pem -outform PEM
----

====== Updating Key Store / Trust Store via the ${admin-console}

Certificates (and certificates with keys) can be managed in the ${admin-console}.

. Navigate to the ${admin-console}.
. Select the *${ddf-security}* application.
. Select the *Certificates* tab.
. Add and remove certificates and private keys as necessary.
. Restart ${branding}.

[IMPORTANT]
====
The default trust store and key store files for ${branding} included in `etc/keystores` use self-signed certificates.
Self-signed certificates should never be used outside of development/testing areas.
====

This view shows the alias (name) of every certificate in the trust store and the key store.
It also displays if the entry includes a private key ("Is Key") and the encryption scheme (typically "RSA" or "EC").

This view allows administrators remove certificates from ${branding}'s key and trust stores.
It also allows administrators to import certificates and private keys into the keystores with the "+" button.
The import function has two options: import from a file or import over HTTPS.
The file option accepts a Java Keystore file or a PKCS12 keystore file.
Because keystores can hold many keys, the import dialog asks the administrator to provide the alias of the key to import.
Private keys are typically encrypted and the import dialog prompts the administrator to enter the password for the private key.
Additionally, keystore files themselves are typically encrypted and the dialog asks for the keystore ("Store") password.

The name and location of the ${branding} trust and key stores can be changed by editing the system properties files, `etc/system.properties`.
Additionally, the password that ${branding} uses to decrypt (unlock) the key and trust stores can be changed here.

[IMPORTANT]
====
${branding} assumes that password used to unlock the keystore is the same password that unlocks private keys in the keystore.
====

The location, file name, passwords and type of the server and trust key stores can be set in the `system.properties` file:

. Setting the Keystore and Truststore Java Properties
[source]
----
javax.net.ssl.keyStore=etc/keystores/serverKeystore.jks
javax.net.ssl.keyStorePassword=changeit
javax.net.ssl.trustStore=etc/keystores/serverTruststore.jks
javax.net.ssl.trustStorePassword=changeit
javax.net.ssl.keyStoreType=jks
javax.net.ssl.trustStoreType=jks
----

[NOTE]
====
If the server's fully qualified domain name is not recognized, the name may need to be added to the network's DNS server.
====

[TIP]
====
The ${branding} instance can be tested even if there is no entry for the FQDN in the DNS.
First, test if the FQDN is already recognized.
Execute this command:

`ping <FQDN>`

If the command responds with an error message such as unknown host, then modify the system's `hosts` file to point the server's FQDN to the loopback address.
For example:

`127.0.0.1 <FQDN>`
====

.Changing Default Passwords
[NOTE]
====
This step is not required for a hardened system.

* The default password in `system.properties` for `serverKeystore.jks` is `changeit`. This needs to be modified.
** `ds-cfg-key-store-file: ../../keystores/serverKeystore.jks`
** `ds-cfg-key-store-type: JKS`
** `ds-cfg-key-store-pin: password`
** `cn: JKS`
* The default password in `system.properties` for `serverTruststore.jks` is `changeit`.  This needs to be modified.
** `ds-cfg-trust-store-file: ../../keystores/serverTruststore.jks`
** `ds-cfg-trust-store-pin: password`
** `cn: JKS`
====

==== Managing Certificate Revocation List (CRL)

* *{hardening-step}*

For hardening purposes, it is recommended to implement a way to verify the CRL at least daily.

A Certificate Revocation List is a collection of formerly-valid certificates that should explicitly _not_ be accepted.

===== Creating a Certificate Revocation List (CRL)

Create a CRL in which the token issuer's certificate is valid.
The example uses OpenSSL.

`$> openssl ca -gencrl -out crl-tokenissuer-valid.pem`

.Windows and OpenSSL
[NOTE]
====
Windows does not include OpenSSL by default.
For Windows platforms, a additional download of https://www.openssl.org/source/[OpenSSL] or an alternative is required.
====

====== Revoke a Certificate and Create a New CRL that Contains the Revoked Certificate

----
$> openssl ca -revoke tokenissuer.crt

$> openssl ca -gencrl -out crl-tokenissuer-revoked.pem
----

====== Viewing a CRL

. Use the following command to view the serial numbers of the revoked certificates:
`$> openssl crl -inform PEM -text -noout -in crl-tokenissuer-revoked.pem`

====== Enabling Revocation

[NOTE]
====
Enabling CRL revocation or modifying the CRL file will require a restart of ${branding} to apply updates.
====

. Place the CRL in <${branding}_HOME>/etc/keystores.
. Add the line `org.apache.ws.security.crypto.merlin.x509crl.file=etc/keystores/<CRL_FILENAME>` to the following files (Replace `<CRL_FILENAME>` with the URL or file path of the CRL location):
.. `<${branding}_HOME>/etc/ws-security/server/encryption.properties`
.. `<${branding}_HOME>/etc/ws-security/issuer/encryption.properties`
.. `<${branding}_HOME>/etc/ws-security/server/signature.properties`
.. `<${branding}_HOME>/etc/ws-security/issuer/signature.properties`
. (Replace <CRL_FILENAME> with the file path or URL of the CRL file used in previous step.)

Adding this property will also enable CRL revocation for any context policy implementing PKI authentication.
For example, adding an authentication policy in the Web Context Policy Manager of `/search=SAML|PKI` will disable basic authentication, require a certificate for the search UI, and allow a SAML SSO session to be created.
If a certificate is not in the CRL, it will be allowed through, otherwise it will get a 401 error.
If no certificate is provided, the guest handler will grant guest access.

This also enables CRL revocation for the STS endpoint.
The STS CRL Interceptor monitors the same `encryption.properties` file and operates in an identical manner to the PKI Authenication's CRL handler. Enabling the CRL via the `encryption.properties` file will also enable it for the STS, and also requires a restart.

====== Add Revocation to a Web Context

The PKIHandler implements CRL revocation, so any web context that is configured to use PKI authentication will also use CRL revocation if revocation is enabled.

. After enabling revocation (see above), open the *Web Context Policy Manager*.
. Add or modify a Web Context to use PKI in authentication. For example, enabling CRL for the search ui endpoint would require adding an authorization policy of `/search=SAML|PKI`
. If guest access is required, add `GUEST` to the policy. Ex, `/search=SAML|PKI|GUEST`.

With guest access, a user with a revoked certificate will be given a 401 error, but users without a certificate will be able to access the web context as the guest user.

The STS CRL interceptor does not need a web context specified.
The CRL interceptor for the STS will become active after specifying the CRL file path, or the URL for the CRL, in the `encryption.properties` file and restarting ${branding}.

[NOTE]
====
Disabling or enabling CRL revocation or modifying the CRL file will require a restart of ${branding} to apply updates.
If CRL checking is already enabled, adding a new context via the *Web Context Policy Manager* will not require a restart.
====

====== Adding Revocation to an Endpoint

[NOTE]
====
This section explains how to add CXF's CRL revocation method to an endpoint and not the CRL revocation method in the `PKIHandler`.
====

This guide assumes that the endpoint being created uses CXF and is being started via Blueprint from inside the OSGi container.
If other tools are being used the configuration may differ.

Add the following property to the `jasws` endpoint in the endpoint's `blueprint.xml`:

[source]
----
<entry key="ws-security.enableRevocation" value="true"/>
----

.Example xml snippet for the `jaxws:endpoint` with the property:
[source]
----
<jaxws:endpoint id="Test" implementor="#testImpl"
                wsdlLocation="classpath:META-INF/wsdl/TestService.wsdl"
                address="/TestService">

    <jaxws:properties>
        <entry key="ws-security.enableRevocation" value="true"/>
    </jaxws:properties>
</jaxws:endpoint>
----

====== Verifying Revocation

A *Warning* similar to the following will be displayed in the logs of the source and endpoint showing the exception encountered during certificate validation:

[source]
----
11:48:00,016 | WARN  | tp2085517656-302 | WSS4JInInterceptor               | ecurity.wss4j.WSS4JInInterceptor  330 | 164 - org.apache.cxf.cxf-rt-ws-security - 2.7.3 |
org.apache.ws.security.WSSecurityException: General security error (Error during certificate path validation: Certificate has been revoked, reason: unspecified)
    at org.apache.ws.security.components.crypto.Merlin.verifyTrust(Merlin.java:838)[161:org.apache.ws.security.wss4j:1.6.9]
    at org.apache.ws.security.validate.SignatureTrustValidator.verifyTrustInCert(SignatureTrustValidator.java:213)[161:org.apache.ws.security.wss4j:1.6.9]

[ ... section removed for space]

Caused by: java.security.cert.CertPathValidatorException: Certificate has been revoked, reason: unspecified
    at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:139)[:1.6.0_33]
    at sun.security.provider.certpath.PKIXCertPathValidator.doValidate(PKIXCertPathValidator.java:330)[:1.6.0_33]
    at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:178)[:1.6.0_33]
    at java.security.cert.CertPathValidator.validate(CertPathValidator.java:250)[:1.6.0_33]
    at org.apache.ws.security.components.crypto.Merlin.verifyTrust(Merlin.java:814)[161:org.apache.ws.security.wss4j:1.6.9]
    ... 45 more
----

==== Disallowing Login Without Certificates

${branding} can be configured to prevent login without a valid PKI certificate.

* Navigate to *${admin-console}*
* Under *${ddf-security}*, select -> *Web Context Policy Manager*
* Add a policy for each context requiring restriction
** For example: `/search=SAML|PKI` will disallow login without certificates to the Search UI.
** The format for the policy should be: `/<CONTEXT>=SAML|PKI`
* Click *Save*

[NOTE]
====
Ensure certificates comply with organizational hardening policies.
====
