:title: Installing (Quick Start)
:type: quickStart
:level: section
:parent: Quick Start Tutorial
:section: quickStart
:status: published
:summary: Installation of an example instance.
:order: 00

== {title}

These are the basic requirements to set up the environment to run a ${branding}.

[WARNING]
====
For security reasons, ${branding} cannot be started from a user's home directory. If attempted, the system will automatically shut down.
====

=== Quick Install Prerequisites
.Hardware Requirements (Quick Install)
* At least 4096MB of memory for ${branding}.
** This amount can be increased to support memory-intensive applications. See <<{managing-prefix}jvm_memory_configuration, Memory Considerations>>.

.Java Requirements (Quick Install)
Set up Java to run ${branding}.

* Install/Upgrade to Java 8 x64 http://www.oracle.com/technetwork/java/javase/downloads/index.html[J2SE 8 SDK]
** The recommended version is http://www.oracle.com/technetwork/java/javase/8u60-relnotes-2620227.html[8u60] or later.
** Java Version and Build numbers must contain only number values.
* Microsoft Windows and Linux are supported. For more information about supported versions, see <<{managing-prefix}installation_prerequisites,Installation Prerequisites>>
* http://www.oracle.com/technetwork/java/javase/downloads/index.html[JDK8x64] must be installed.
* The `JAVA_HOME` environment variable must be set to the location where the JDK is installed.

.Setting JAVA_HOME variable (Replace `<JAVA_VERSION>` with the version and build number installed.)
====

. Determine Java Installation Directory (This varies between operating system versions).

.Find Java Path in Windows
----
for %i in (java.exe) do @echo. %~$PATH:i
----

.Find Java Path in *nix
----
which java
----

. Copy path to Java installation. (example: `/usr/java/<JAVA_VERSION>`)
. Set `JAVA_HOME` by replacing <PATH_TO_JAVA> with the copied path in this command:

.Setting `JAVA_HOME` on Windows
----
set JAVA_HOME=<PATH_TO_JAVA><JAVA_VERSION>
----

.Adding `JAVA_HOME` to `PATH` Environment Variable on Windows
----
setx PATH "%PATH%;%JAVA_HOME%\bin"
----

.Setting `JAVA_HOME` on *nix
----
JAVA_HOME=<PATH_TO_JAVA><JAVA_VERSION>
export JAVA_HOME
----
====

.*nix
[WARNING]
====
Unlink `JAVA_HOME` if it is already linked to a previous version of the JRE:
`unlink JAVA_HOME`
====

.Verify that the `JAVA_HOME` was set correctly.
[TIP]
====

.Windows
----
echo %JAVA_HOME%
----

.*nix
----
echo $JAVA_HOME
----
====

.File Descriptor Limit on Linux
[NOTE]
====
* For Linux systems, increase the file descriptor limit by editing `/etc/sysctl.conf` to include:

----
fs.file-max = 6815744
----

* (This file may need permissions changed to allow write access).
* For the change to take effect, a restart is required.

. *nix Restart Command
----
init 6
----
====

.Check System Time
[WARNING]
====
Prior to installing ${branding}, ensure the system time is accurate to prevent federation issues.
====

=== Quick Install of ${branding}

. Download the ${branding} {download-url}[zip file].
. Install ${branding} by unzipping the zip file.
+
.Windows Zip Utility Warning
[WARNING]
====
The Windows Zip implementation, which is invoked when a user double-clicks on a zip file in the Windows Explorer, creates a corrupted installation.
This is a consequence of its inability to process long file paths.
Instead, use the java jar command line utility to unzip the distribution (see example below) or use a third party utility such as 7-Zip.

.Use Java to Unzip in Windows(Replace `<PATH_TO_JAVA>` with correct path `and <JAVA_VERSION>` with current version.)
----
"<PATH_TO_JAVA>\jdk<JAVA_VERSION>\bin\jar.exe" xf ${branding-lowercase}-${project.version}.zip
----
====
+
. This will create an installation directory, which is typically created with the name and version of the application.
This installation directory will be referred to as `${home_directory}`.
(Substitute the actual directory name.)
. Start ${branding} by running the `${home_directory}/bin/${branding-lowercase}` script (or `${branding-lowercase}.bat` on Windows).
. Startup may take a few minutes.
.. Optionally, a `waitForReady` command (aliased to `wfr`) can be used to notify when setup is complete. A "System Ready" message will display. *nix users will see progress indicated before the message.
. The ${command-console} will display.

.${command-console} Prompt
----
${branding-lowercase}${at-symbol}local>

----

=== Quick Install of ${branding} on a remote headless server

If ${branding} is being installed on a remote server that has no user interface some additional steps must be taken prior to starting the system.

. Update any references to localhost in the following files. These references to localhost should be updated to match either the hostname or IP of the system.
** `${home_directory}/etc/custom.system.properties`
** `${home_directory}/etc/users.properties`
** `${home_directory}/etc/users.attributes`
. From the console go to ${home_directory}/etc/certs.
.. If using a hostname run: `sh CertNew.sh -cn <hostname> -san "DNS:<hostname>"` (or `CertNew -cn <hostname> -san "DNS:<hostname>"` on windows).
.. If using an IP address run: `sh CertNew.sh -cn <IP> -san "IP:<IP>"` (or `CertNew -cn <IP> -san "IP:<IP>"` on windows).
. Proceed with starting the system and continue as usual.
