:title: FTP Endpoint
:type: endpoint
:status: published
:link: _ftp_endpoint
:operations: ingest
:summary: Ingests files directly into the ${branding} catalog using the FTP protocol.

== {title}

The FTP endpoint provides a method for ingesting files directly into the ${branding} catalog using the FTP protocol.

The FTP endpoint can be accessed from any FTP client of choice.
Some common clients are FileZilla, PuTTY, or the FTP client provided in the terminal.
The default port number is *8021*.
If FTPS is enabled with 2-way TLS, a client that supports client authentication is required.

=== FTP Endpoint Create Examples

To ingest files into ${branding} send an FTP `PUT` request to the ${branding} server.

.FTP Endpoint URL
[source,ftp]
----
ftp://<FQDN>:<PORT>
----

=== FTP Endpoint Rename Command

The FTP endpoint also supports renaming files as they are ingested with the FTP `RNTO` operation.

Files named with a leading `.`, such as `.<FILENAME>`,  are held by ${branding} without being ingested until the `rename` command is sent.

.PUT Command Example
[source,ftp]
----
PUT .<FILENAME>.txt
----

.Rename Command Example
[source,ftp]
----
rename .<NEW_FILENAME>.txt
----

The endpoint will complete the ingest process when the rename command is sent.
The filename on the original file system will NOT be changed.
