:title: OpenSearch Endpoint
:type: endpoint
:status: published
:operations: query
:link: _opensearch_endpoint
:summary: Sends query parameters and receives search results.

== {title}

The OpenSearch Endpoint enables a client to send query parameters and receive search results.
This endpoint uses the input query parameters to create an OpenSearch query.
The client does not need to specify all of the query parameters, only the query parameters of interest.

The OpenSearch specification defines a file format to describe an OpenSearch endpoint.
This file is XML-based and is used to programatically retrieve a site's endpoint, as well as the different parameter options a site holds.
The parameters are defined via the http://www.opensearch.org/Specifications/OpenSearch/1.1[OpenSearch] {external-link} and https://www.dni.gov/index.php/about/organization/chief-information-officer/cdr-search[CDR IPT] {external-link} Specifications.

=== OpenSearch Contextual Queries

To use the OpenSearch endpoint for a query, send a `GET` request with the query options as parameters

.OpenSearch Query URL
[source,https]
----
https://<FQDN>:<PORT>/services/catalog/query?<NAME>="<VALUE>"
----

.OpenSearch Parameter List
[cols="4*", options="header"]
|===
|OpenSearch Element
|HTTPS Parameter
|Possible Values
|Comments

|`searchTerms`
|`q`
|URL-encoded, space-delimited list of search terms
|Complex contextual search string.

|`count`
|`count`
|Integer >= 0
|Maximum # of results to retrieve.

default: `10`

|`startIndex`
|`start`
|integer > 0
|Index of first result to return.

This value uses a one-based index for the results.

default: `1`

|`format`
|`format`
|Requires a transformer shortname as a string, possible values include, when available, `atom`, `html`, and `kml`.

See <<{architecture-prefix}available_query_response_transformers,Query Response transformers>> for more possible values.
|Defines the format that the return type should be in.

default: `atom`
|===

.Sample OpenSearch Textual Query
[source,https]
----
https://<FQDN>:<PORT>/services/catalog/query?q="Aliquam"&count=20
----

==== Complex OpenSearch Contextual Query Format

The OpenSearch Endpoint supports the following operators: `AND`, `OR`, and `NOT`.
These operators are case sensitive.
Implicit `ANDs` are also supported.

Use parentheses to change the order of operations.
Use quotes to group keywords into literal expressions.

See the http://www.opensearch.org/Specifications/OpenSearch/1.1[OpenSearch] specification for more syntax specifics.

.OpenSearch Endpoint Complex Query Example
[source,https]
----
https://<FQDN>:<PORT>/services/catalog/query?q='cat OR dog'
----

=== OpenSearch Temporal Queries
Queries can also specify a start and end time to narrow results.

.OpenSearch Temporal Parameters
[cols="4*", options="header"]
|===
|OpenSearch Element
|HTTPS Parameter
|Possible Values
|Comments

|`start`
|`dtstart`
|RFC-3399-defined value:`YYYY-MM-DDTHH:mm:ssZ` or `yyyy-MM-dd'T'HH:mm:ss.SSSZZ`
|Specifies the beginning of the time slice of the search.

Default value of "1970-01-01T00:00:00Z" is used when `dtend` is specified but `dtstart` is not specified.

|`end`
|`dtend`
|RFC-3399-defined value:`YYYY-MM-DDTHH:mm:ssZ` or `yyyy-MM-dd'T'HH:mm:ss.SSSZZ`
|Specifies the ending of the time slice of the search

Current GMT date/time is used when `dtstart` is specified but `dtend` is not specified.
|===

.OpenSearch Temporal Query Example
[source,https]
----
https://<FQDN>:<PORT>/services/catalog/query?q='*'&dtstart=${timestamp}T00:00:00Z&dtend=${timestamp}T18:00:00Z
----

[NOTE]
====
The start and end temporal criteria must be of the format specified above. Other formats are currently not supported. Example:

`${timestamp}T12:00:00.111-04:00`.

*The start and end temporal elements are based on <<{metadata-prefix}modified,modified>> timestamps for a metacard.*
====

=== OpenSearch Geospatial Queries
Query by location.

Use geospatial query parameters to create a geospatial `INTERSECTS` query, where `INTERSECTS` means geometries that are not `DISJOINT` to the given geospatial parameters. 

.Opensearch Geospatial Parameters
[cols="4", options="header"]
|===
|OpenSearch Element
|HTTPS Parameter
|Possible Values
|Comments

|`lat`
|`lat`
|`EPSG:4326 (WGS84)` decimal degrees
|Used in conjunction with the `lon` and `radius` parameters.

|`lon`
|`lon`
|`EPSG:4326 (WGS84)` decimal degrees
|Used in conjunction with the `lat` and `radius` parameters.

|`radius`
|`radius`
|`EPSG:4326 (WGS84)` meters along the Earth's surface > 0
|Specifies the search distance in meters from the `lon`,`lat` point.

Used in conjunction with the `lat` and `lon` parameters.

default: `5000`

|`polygon`
|`polygon`
|Comma-delimited list of lat/lon (`EPSG:4326 (WGS84)` decimal degrees) pairs, in clockwise order around the polygon, where the last point is the same as the first in order to close the polygon.
(e.g. `-80,-170,0,-170,80,-170,80,170,0,170,-80,170,-80,-170`)
|According to the OpenSearch Geo Specification this is *deprecated*. Use the `geometry` parameter instead.

|`box`
|`bbox`
|4 comma-delimited `EPSG:4326 (WGS84)` decimal degrees coordinates in the format West,South,East,North
|

|`geometry`
|`geometry` 
|WKT Geometries

Examples:

`POINT(10 20)` where 10 is the longitude and 20 is the latitude.

`POLYGON ( ( 30 10, 10 20, 20 40, 40 40, 30 10 ) )`. 30 is longitude and 10 is latitude for the first point.

`MULTIPOLYGON (((40 40, 20 45, 45 30, 40 40)), ((20 35, 10 30, 10 10, 30 5, 45 20, 20 35), (30 20, 20 15, 20 25, 30 20)))`

`GEOMETRYCOLLECTION(POINT(4 6),LINESTRING(4 6,7 10))`
|Make sure to repeat the starting point as the last point to close the polygon.

|===

.OpenSearch GeoSpatial Query Example
[source,https]
----
https://localhost:8993/services/catalog/query?q='*'&lon=44.792&lat=-6.171
----

=== Additional OpenSearch Query Parameters
The OpenSearch Endpoint can also use these additional parameters to refine queries

.OpenSearch Query Extensions
[cols="4*", options="header"]
|===
|OpenSearch Element
|HTTPS Parameter
|Possible Values
|Comments

|`sort`
|`sort`
|`<sbfield>:<sborder>` where

`<sbfield>` is `date` or `relevance`

`<sborder>` is `asc` or `desc`
|`<sborder>` is optional but has a value of `asc` or `desc` (default is `desc`).
However, when `<sbfield>` is `relevance`, `<sborder>` must be `desc`.

Sorting by `date` will sort the results by the <<{metadata-prefix}effective,`effective`>> date.

default: `relevance:desc`

|`maxResults`
|`mr`
|Integer >= 0
|Maximum # of results to return.

If `count` is also specified, the `count` value will take precedence over the `maxResults` value.

default: `1000`

|`maxTimeout`
|`mt`
|Integer > 0
|Maximum timeout (milliseconds) for query to respond.

default: `300000` (5 minutes)

|`dateOffset`
|`dtoffset`
|Integer > 0
|Specifies an offset (milliseconds), backwards from the current time, to search on the <<{metadata-prefix}modified, modified>> time field for entries.

|`type`
|`type`
|Any valid datatype (e.g. `Text`)
|Specifies the type of data to search for.

|`version`
|`version`
|Comma-delimited list of strings (e.g. 20,30)
|Version values for which to search.

|`selector`
|`selector`
|Comma-delimited list of XPath string selectors (e.g. `//namespace:example`, //example`)
|Selectors to narrow the query.

|===

.Federated Search
[cols="4*", options="header"]
|===
|OpenSearch Element
|HTTPS Parameter
|Possible Values
|Comments

|`routeTo`
|`src`
|Comma-delimited list of site names to query. Varies depending on the names of the sites in the federation. `local` specifies to query the local site.
|If `src` is not provided, the default behavior is to execute an enterprise search to the entire federation.

|===
