:title: WPS Endpoint
:type: endpoint
:status: published
:operations: other
:link: _wps_endpoint
:url: \${secure_url}/services/WPS
:summary: Execute and monitor long running processes.
:implements: http://www.opengeospatial.org/standards/wps[Web Processing Service (WPS) standard.

== {title}

[NOTE]
====
EXPERIMENTAL
====

The WPS endpoint enables a client to execute and monitor long running processes.

For a typical sequence of WPS requests, a client would first issue a GetCapabilities request to the server to obtain an up-to-date listing of available processes.
Then, it may issue a DescribeProcess request to find out more details about the particular processes offered, including the supported data formats.
To run a process with the desired input data, a client will issue an Execute request.
The operations GetStatus and GetResult are used in conjunction with asynchronous execution.

For brevity the examples below use GET Key-value pair requests but POST is also supported.
See the OGC WPS 2.0 Interface Standard for more details.

.WPS Endpoint Operations
[cols="2,1m,2,5m", options="header"]
|===

|Operation
|HTTP Request Type
|Details
|Example URL

|
|
|
|{url}

|===

.`GetCapabilities` Operation
This operation allows a client to request information about the server’s capabilities and processes offered.

[[_get_capabilities]]
.GetCapabilities (GetCapabilities)
.`GetCapabilities` KVP (Key-Value Pairs) Encoding
----
${secure_url}/services/wps?service=WPS&version=2.0.0&request=GetCapabilities&acceptVersions=2.0.0&sections=Contents,OperationsMetadata,ServiceIdentification,ServiceProvider
----


[[_capabilities]]
.Capabilities (Capabilities)
[source,xml]
----
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns4:Capabilities xmlns:ns2="http://www.opengis.net/ows/2.0" xmlns:ns3="http://www.w3.org/1999/xlink" xmlns:ns4="http://www.opengis.net/wps/2.0" service="WPS" version="2.0.0">
    <ns2:ServiceIdentification>
        <ns2:Title>Web Processing Service</ns2:Title>
        <ns2:Abstract>DDF WPS Endpoint</ns2:Abstract>
        <ns2:ServiceType>WPS</ns2:ServiceType>
        <ns2:Fees>NONE</ns2:Fees>
        <ns2:AccessConstraints>NONE</ns2:AccessConstraints>
    </ns2:ServiceIdentification>
    <ns2:ServiceProvider>
        <ns2:ProviderName>DDF</ns2:ProviderName>
        <ns2:ProviderSite/>
        <ns2:ServiceContact/>
    </ns2:ServiceProvider>
    <ns2:OperationsMetadata>
        <ns2:Operation name="GetCapabilities">
            <ns2:DCP>
                <ns2:HTTP>
                    <ns2:Get ns3:href="https://host:8993/services/wps"/>
                    <ns2:Post ns3:href="https://host:8993/services/wps"/>
                </ns2:HTTP>
            </ns2:DCP>
        </ns2:Operation>
        <ns2:Operation name="DescribeProcess">
            <ns2:DCP>
                <ns2:HTTP>
                    <ns2:Get ns3:href="https://host:8993/services/wps"/>
                    <ns2:Post ns3:href="https://host:8993/services/wps"/>
                </ns2:HTTP>
            </ns2:DCP>
        </ns2:Operation>
        <ns2:Operation name="Execute">
            <ns2:DCP>
                <ns2:HTTP>
                    <ns2:Post ns3:href="https://host:8993/services/wps"/>
                </ns2:HTTP>
            </ns2:DCP>
        </ns2:Operation>
        <ns2:Operation name="GetStatus">
            <ns2:DCP>
                <ns2:HTTP>
                    <ns2:Get ns3:href="https://host:8993/services/wps"/>
                    <ns2:Post ns3:href="https://host:8993/services/wps"/>
                </ns2:HTTP>
            </ns2:DCP>
        </ns2:Operation>
        <ns2:Operation name="GetResult">
            <ns2:DCP>
                <ns2:HTTP>
                    <ns2:Get ns3:href="https://host:8993/services/wps"/>
                    <ns2:Post ns3:href="https://host:8993/services/wps"/>
                </ns2:HTTP>
            </ns2:DCP>
        </ns2:Operation>
        <ns2:Operation name="Dismiss">
            <ns2:DCP>
                <ns2:HTTP>
                    <ns2:Get ns3:href="https://host:8993/services/wps"/>
                    <ns2:Post ns3:href="https://host:8993/services/wps"/>
                </ns2:HTTP>
            </ns2:DCP>
        </ns2:Operation>
    </ns2:OperationsMetadata>
    <ns4:Contents>
        <ns4:ProcessSummary jobControlOptions="async-execute" outputTransmission="reference" processVersion="1.0">
            <ns2:Title>Test Primitives</ns2:Title>
            <ns2:Abstract>Test for modeled, primitive data types.</ns2:Abstract>
            <ns2:Identifier>testPrimitives</ns2:Identifier>
        </ns4:ProcessSummary>
    </ns4:Contents>
</ns4:Capabilities>
----

.`DescribeProcess` Operation
This operation allows a client to request detailed metadata on selected processes offered by a server.

[[_get__describeprocessrequest]]
.`DescribeProcess` KVP (Key-Value Pairs) Encoding
----
${secure_url}/services/wps?service=WPS&version=2.0.0&request=DescribeProcess&identifier=testPrimitives
----

[[_describeprocessrequest]]
.Describe Process Request
[source,xml]
----
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns4:ProcessOfferings xmlns:ns2="http://www.opengis.net/ows/2.0" xmlns:ns3="http://www.w3.org/1999/xlink" xmlns:ns4="http://www.opengis.net/wps/2.0">
    <ns4:ProcessOffering jobControlOptions="async-execute" outputTransmission="reference" processVersion="1.0">
        <ns4:Process>
            <ns2:Title>Test Primitives</ns2:Title>
            <ns2:Abstract>Test for modeled, primitive data types.</ns2:Abstract>
            <ns2:Identifier>testPrimitives</ns2:Identifier>
            <ns4:Input minOccurs="1" maxOccurs="1">
                <ns2:Title>intParam</ns2:Title>
                <ns2:Abstract>An integer value [-2^31, 2^31-1]</ns2:Abstract>
                <ns2:Identifier>intParam</ns2:Identifier>
                <ns4:LiteralData>
                    <ns4:Format encoding="UTF-8" default="true"/>
                    <LiteralDataDomain default="true">
                        <ns2:AnyValue/>
                        <ns2:DataType ns2:reference="http://www.w3.org/TR/xmlschema-2/#integer">Integer</ns2:DataType>
                        <ns2:DefaultValue>3</ns2:DefaultValue>
                    </LiteralDataDomain>
                </ns4:LiteralData>
            </ns4:Input>
            <ns4:Input minOccurs="1" maxOccurs="1">
                <ns2:Title>doubleParam</ns2:Title>
                <ns2:Abstract>A double-precision floating point value</ns2:Abstract>
                <ns2:Identifier>doubleParam</ns2:Identifier>
                <ns4:LiteralData>
                    <ns4:Format encoding="UTF-8" default="true"/>
                    <LiteralDataDomain default="true">
                        <ns2:AllowedValues>
                            <ns2:Range ns2:rangeClosure="open">
                                <ns2:MinimumValue>15.0</ns2:MinimumValue>
                                <ns2:MaximumValue>50.0</ns2:MaximumValue>
                            </ns2:Range>
                        </ns2:AllowedValues>
                        <ns2:DataType ns2:reference="http://www.w3.org/TR/xmlschema-2/#double">Double</ns2:DataType>
                        <ns2:DefaultValue>50.0</ns2:DefaultValue>
                    </LiteralDataDomain>
                </ns4:LiteralData>
            </ns4:Input>
            <ns4:Input minOccurs="1" maxOccurs="1">
                <ns2:Title>byteParam</ns2:Title>
                <ns2:Abstract>A byte value [-128, 127]</ns2:Abstract>
                <ns2:Identifier>byteParam</ns2:Identifier>
                <ns4:LiteralData>
                    <ns4:Format encoding="UTF-8" default="true"/>
                    <LiteralDataDomain default="true">
                        <ns2:AnyValue/>
                        <ns2:DataType ns2:reference="http://www.w3.org/TR/xmlschema-2/#byte">Byte</ns2:DataType>
                        <ns2:DefaultValue>1</ns2:DefaultValue>
                    </LiteralDataDomain>
                </ns4:LiteralData>
            </ns4:Input>
            <ns4:Input minOccurs="1" maxOccurs="1">
                <ns2:Title>shortParam</ns2:Title>
                <ns2:Abstract>A short value [-32768, 32767]</ns2:Abstract>
                <ns2:Identifier>shortParam</ns2:Identifier>
                <ns4:LiteralData>
                    <ns4:Format encoding="UTF-8" default="true"/>
                    <LiteralDataDomain default="true">
                        <ns2:AnyValue/>
                        <ns2:DataType ns2:reference="http://www.w3.org/TR/xmlschema-2/#short">Short</ns2:DataType>
                        <ns2:DefaultValue>2</ns2:DefaultValue>
                    </LiteralDataDomain>
                </ns4:LiteralData>
            </ns4:Input>
            <ns4:Input minOccurs="1" maxOccurs="1">
                <ns2:Title>longParam</ns2:Title>
                <ns2:Abstract>A long value [-2^63, 2^63-1]</ns2:Abstract>
                <ns2:Identifier>longParam</ns2:Identifier>
                <ns4:LiteralData>
                    <ns4:Format encoding="UTF-8" default="true"/>
                    <LiteralDataDomain default="true">
                        <ns2:AnyValue/>
                        <ns2:DataType ns2:reference="http://www.w3.org/TR/xmlschema-2/#long">Long</ns2:DataType>
                        <ns2:DefaultValue>4</ns2:DefaultValue>
                    </LiteralDataDomain>
                </ns4:LiteralData>
            </ns4:Input>
            <ns4:Input minOccurs="1" maxOccurs="1">
                <ns2:Title>booleanParam</ns2:Title>
                <ns2:Abstract>A boolean value [false, true]</ns2:Abstract>
                <ns2:Identifier>booleanParam</ns2:Identifier>
                <ns4:LiteralData>
                    <ns4:Format encoding="UTF-8" default="true"/>
                    <LiteralDataDomain default="true">
                        <ns2:AnyValue/>
                        <ns2:DataType ns2:reference="http://www.w3.org/TR/xmlschema-2/#boolean">Boolean</ns2:DataType>
                        <ns2:DefaultValue>false</ns2:DefaultValue>
                    </LiteralDataDomain>
                </ns4:LiteralData>
            </ns4:Input>
            <ns4:Input minOccurs="1" maxOccurs="1">
                <ns2:Title>floatParam</ns2:Title>
                <ns2:Abstract>A long value [-2^63, 2^63-1]</ns2:Abstract>
                <ns2:Identifier>floatParam</ns2:Identifier>
                <ns4:LiteralData>
                    <ns4:Format encoding="UTF-8" default="true"/>
                    <LiteralDataDomain default="true">
                        <ns2:AnyValue/>
                        <ns2:DataType ns2:reference="http://www.w3.org/TR/xmlschema-2/#float">Float</ns2:DataType>
                        <ns2:DefaultValue>5.0</ns2:DefaultValue>
                    </LiteralDataDomain>
                </ns4:LiteralData>
            </ns4:Input>
            <ns4:Input minOccurs="1" maxOccurs="1">
                <ns2:Title>Product Id</ns2:Title>
                <ns2:Abstract>Product Identifier</ns2:Abstract>
                <ns2:Identifier>productId</ns2:Identifier>
                <ns4:LiteralData>
                    <ns4:Format encoding="UTF-8" default="true"/>
                    <LiteralDataDomain default="true">
                        <ns2:AnyValue/>
                        <ns2:DataType ns2:reference="http://www.w3.org/TR/xmlschema-2/#string">String</ns2:DataType>
                    </LiteralDataDomain>
                </ns4:LiteralData>
            </ns4:Input>
            <ns4:Output>
                <ns2:Title>Product</ns2:Title>
                <ns2:Abstract>Raw output</ns2:Abstract>
                <ns2:Identifier>product</ns2:Identifier>
                <ns4:ComplexData>
                    <ns4:Format encoding="raw" default="true"/>
                </ns4:ComplexData>
            </ns4:Output>
        </ns4:Process>
    </ns4:ProcessOffering>
</ns4:ProcessOfferings>
----


.`GetStatus` Operation
This operation allows a client to query status information of a processing job.

[[_get__status]]
.`GetStatus` KVP (Key-Value Pairs) Encoding
----
${secure_url}/services/wps?service=WPS&version=2.0.0&request=GetStatus&jobId=FB6DD4B0-A2BB-11E3-A5E2-0800200C9A66
----

[[_statusinfo]]
.Status Info
[source,xml]
----
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns4:StatusInfo xmlns:ns2="http://www.opengis.net/ows/2.0" xmlns:ns3="http://www.w3.org/1999/xlink" xmlns:ns4="http://www.opengis.net/wps/2.0">
    <ns4:JobID>FB6DD4B0-A2BB-11E3-A5E2-0800200C9A66</ns4:JobID>
    <ns4:Status>Running</ns4:Status>
    <ns4:PercentCompleted>50</ns4:PercentCompleted>
</ns4:StatusInfo>
----

.`GetResult` Operation
This operation allows a client to query the results of a processing job.
The response can be in several formats depending on the request:
* If the response attribute in the request is `document` the response will be in the Result format if the response attribute is `raw` then response will be in the format defined in the output definition.
* If the job failed an ExceptionReport will be returned.
* If the response format is 'raw' and no data is returned than an empty response with an HTTP status of 204 will be returned.

[[_get__result]]
.`GetResult` KVP (Key-Value Pairs) Encoding
----
${secure_url}/services/wps?service=WPS&version=2.0.0&request=GetResult&jobId=FB6DD4B0-A2BB-11E3-A5E2-0800200C9A66
----

[[_result_wps]]
.Result
[source,xml]
----
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns4:Result xmlns:ns2="http://www.opengis.net/ows/2.0" xmlns:ns3="http://www.w3.org/1999/xlink" xmlns:ns4="http://www.opengis.net/wps/2.0">
  <ns4:JobID>FB6DD4B0-A2BB-11E3-A5E2-0800200C9A66</wps:JobID>
  <ns4:ExpirationDate>2014-12-24T24:00:00Z</wps:ExpirationDate>
  <ns4:Output id="BUFFERED_GEOMETRY">
  <ns4:Reference xlink:href="http://result.data.server/FB6DD4B0-A2BB-11E3-A5E2-0800200C9A66/BUFFERED_GEOMETRY.xml"/>
  </ns4:Output>
</ns4:Result>
----


.`Execute` Operation
This operation allows a client to execute a process comprised of a process identifier, the desired data inputs, and the desired output formats.
The response can be in several formats depending on the request:
* If the mode is `async` the response will be in the StatusInfo format.
* If the mode is `sync` and the response attribute in the request is `document` the response will be in the Result format if the response attribute is `raw` then response will be in the format defined in the output definition`.
* If the mode is 'auto' then the response can be either of the aforementioned response formats.
* If the job failed an ExceptionReport will be returned.
* If the response format is 'raw' and no data is returned than an empty response with an HTTP status of 204 will be returned.

[[_post__executionrequest]]
.`PostAsyncExecutionRequest` HTTP POST
----
${secure_url}/services/wps?service=WPS&version=2.0.0&request=Execute
----

[[_executionrequest]]
.Async Execution Request
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<wps:Execute
	xmlns:wps="http://www.opengis.net/wps/2.0"
	xmlns:ows="http://www.opengis.net/ows/2.0"
	xmlns:xlink="http://www.w3.org/1999/xlink"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.opengis.net/wps/2.0 ../wps.xsd"

	service="WPS"
	version="2.0.0"
	response="document"
	mode="async">

<ows:Identifier>reprocess</ows:Identifier>
    <wps:Input id="imagery_id">
        <wps:Input id="mission_id">
            <wps:Data>A123</wps:Data>
        </wps:Input>
        <wps:Input id="scene_id">
            <wps:Data>10</wps:Data>
        </wps:Input>
    </wps:Input>
    <wps:Output id="product" transmission="reference"/>

</wps:Execute>
----

[[_executionrequest_response]]
.Execution Request Response
[source,xml]
----
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns4:StatusInfo xmlns:ns2="http://www.opengis.net/ows/2.0" xmlns:ns3="http://www.w3.org/1999/xlink" xmlns:ns4="http://www.opengis.net/wps/2.0">
    <ns4:JobID>615f5ed6-adac-4630-8b3e-4ec97b154cf6</ns4:JobID>
    <ns4:Status>Accepted</ns4:Status>
    <ns4:PercentCompleted>0</ns4:PercentCompleted>
</ns4:StatusInfo>
----