:title: Tika Input Transformer
:type: transformer
:subtype: input
:status: published
:link: _tika_input_transformer
:summary: Translates Microsoft Word, Microsoft Excel, Microsoft PowerPoint, OpenOffice Writer, and PDF documents into Catalog records.

The Tika Input Transformer is the default input transformer responsible for translating Microsoft Word, Microsoft Excel, Microsoft PowerPoint, OpenOffice Writer, and PDF documents into Catalog records.
This input transformer utilizes https://tika.apache.org[Apache Tika] to provide basic support for these mime types.
The metadata common to all these document types, e.g., creation date, author, last modified date, etc., is extracted and used to create the catalog record.
The Tika Input Transformer's main purpose is to ingest these types of content into the Metadata Catalog.

The Tika input transformer is most basic input transformer and the last to be invoked.
This allows any registered input transformers that are more specific to a document type to be invoked instead of this rudimentary input transformer.

.{title} Usage
[cols="1,2" options="header"]
|===
|Schema
|Mime-types

|N/A
|This basic transformer can ingest many file types. See <<{metadata-prefix}all_file_formats_supported,All Formats Supported>>.
|===

===== Installing the Tika Input Transformer

This transformer is installed by default with a standard installation in the ${ddf-catalog}.

===== Configuring the Tika Input Transformer

The properties below describe how to configure the Tika input transformer.

See <<{reference-prefix}ddf.catalog.transformer.input.tika.TikaInputTransformer,Tika Input Transformer configurations>> for all possible configurations.

