:type: plugin
:status: published
:title: Event Processor
:link: _event_processor
:plugintypes: postingest
:summary: Creates, updates, and deletes subscriptions.

The Event Processor creates, updates, and deletes subscriptions for event notification.
These subscriptions optionally specify a filter criteria so that only events of interest to the subscriber are posted for notification.

As metacards are created, updated, and deleted, the Catalog's Event Processor is invoked (as a post-ingest plugin) for each of these events.
The Event Processor applies the filter criteria for each registered subscription to each of these ingest events to determine if they match the criteria.

For more information on creating subscriptions, see <<{integrating-prefix}creating_a_subscription,Creating a Subscription>>.

== Installing the Event Processor

The Event Processor is installed by default with a standard installation in the ${ddf-catalog} application.

== Configuring the Event Processor

The Event Processor has no configurable properties.

== Usage Limitations of the Event Processor

The Standard Event processor currently broadcasts federated events and should not.
It should only broadcast events that were generated locally, all other events should be dropped.
See https://codice.atlassian.net/browse/DDF-3151[DDF-3151] for status.
// TODO: Remove this notice upon completion of https://codice.atlassian.net/browse/DDF-3151.

