:type: plugin
:status: published
:title: Metacard Attribute Security Policy Plugin
:link: {developing-prefix}metacard_attribute_security_policy_plugin
:plugintypes: policy
:summary: Collects attributes into a security field for the metacard.

The Metacard Attribute Security Policy Plugin combines existing metacard attributes to make new attributes and adds them to the metacard.
For example, if a metacard has two attributes,
`sourceattribute1` and `sourceattribute2`, the values of the two attributes could be combined into a new
 attribute, `destinationattribute1`. The `sourceattribute1` and `sourceattribute2` are the _source attributes_
 and `destinationattribute1` is the _destination attribute_.

There are two way to combine the values of source attributes. The first, and most common,
is to take all of the attribute values and put them together.
This is called the union.
For example, if the source attributes `sourceattribute1` and `sourceattribute2` had the values:

`sourceattribute1 = MASK, VESSEL`

`sourceattribute2 = WIRE, SACK, MASK`

...the **union** would result in the new attribute `destinationattribute1`:

`destinationattribute1 = MASK, VESSEL, WIRE, SACK`

The other way to combine attributes is use the values common to all of the attributes.
This is called the intersection. Using our previous example, the **intersection** of
`sourceattribute1` and `sourceattribute2` would create the new attribute `destinationattribute1`

`destinationattribute1 = MASK`

because only `MASK` is common to all  of the source attributes.

The policy plugin could also be used to rename attributes. If there is only one source attribute,
 and the combination policy is union, then the attribute's values are effectively renamed to the
 destination attribute.

===== Installing the Metacard Attribute Security Policy Plugin

The Metacard Attribute Security Policy Plugin is installed by default with a standard installation
 in the ${ddf-catalog} application.

See <<{reference-prefix}org.codice.ddf.catalog.security.policy.metacard.MetacardAttributeSecurityPolicyPlugin,Metacard
 Attribute Security Policy Plugin configurations>> for all possible configurations.

