:type: plugin
:status: published
:title: Event Processor
:link: _event_processor
:plugintypes: postingest
:summary: Creates, updates, and deletes subscriptions.

The Event Processor provides an engine that creates, updates, and deletes subscriptions for event notification.
These subscriptions optionally specify a filter criteria so that only events of interest to the subscriber are posted for notification.

An internal subscription tracker monitors the OSGi registry, looking for subscriptions to be added (or deleted).
When it detects a subscription being added, it informs the Event Processor, which sets up the subscription's filtering and is responsible for posting event notifications to the subscriber when events satisfying their criteria are met.

The Standard Event Processor is an implementation of the Event Processor and provides the ability to create/delete subscriptions.
Events are generated by the ${ddf-catalog}Framework as metacards are created/updated/deleted and the Standard Event Processor is called since it is also a Post-Ingest Plugin.
The Standard Event Processor checks each event against each subscription's criteria.

When an event matches a subscription's criteria the Standard Event Processor:

* invokes each pre-delivery plugin on the metacard in the event.
* invokes the `DeliveryMethod` operation corresponding to the type of event being processed, e.g., `created()` operation for the creation of a metacard.

===== Installing the Event Processor

The Event Processor is installed by default with a standard installation in the ${ddf-catalog} application.

===== Configuring the Event Processor

The Event Processor has no configurable properties.

===== Event Processing and Notification

As metacards are created, updated, and deleted, the Catalog's Event Processor is invoked (as a post-ingest plugin) for each of these events.
The Event Processor applies the filter criteria for each registered subscription to each of these ingest events to determine if they match the criteria.
If an event matches a subscription's criteria, any pre-delivery plugins that are installed are invoked, the subscription's `DeliveryMethod` is retrieved, and its operation corresponding to the type of ingest event is invoked. 
For example, the `DeliveryMethod` `created()` function is called when a metacard is created.
The `DeliveryMethod` operations subsequently invoke the corresponding operation in the client's event consumer service, which is specified by the callback URL provided when the `DeliveryMethod` was created.

For more information on creating subscriptions, see <<_creating_a_subscription,Creating a Subscription>>.

.Available Event Processors
* <<_event_processor,Standard Event Processor>>
* <<_fanout_event_processor,Fanout Event Processor>>

====== Using ${branding} Implementation

If applicable, the implementation of `Subscription` that comes with ${branding} should be used.
It is available at `ddf.catalog.event.impl.SubscriptionImpl` and offers a constructor that takes in all of the necessary objects.
Specifically, all that is needed is a `Filter`, `DeliveryMethod`, `Set<String>` of source IDs, and a `boolean` for enterprise.

The following is an example code stub showing how to create a new instance of Subscription using the ${branding} implementation. 

.Creating a Subscription
[source,java,linenums]
----
// Create a new filter using an imported FilterBuilder
Filter filter = filterBuilder.attribute(Metacard.ANY_TEXT).like().text("*");
 
// Create a implementation of DeliveryMethod
DeliveryMethod deliveryMethod = new MyCustomDeliveryMethod();
 
// Create a set of source ids
// This set is empty as the subscription is not specific to any sources
Set<String> sourceIds = new HashSet<String>();
 
// Set the isEnterprise boolean value
// This subscription example should notifications from all sources (not just local)
boolean isEnterprise = true;

Subscription subscription = new SubscriptionImpl(filter, deliveryMethod, sourceIds,isEnterprise);
----

===== Usage Limitations of the Event Processor

The Standard Event processor currently broadcasts federated events and should not.
It should only broadcast events that were generated locally, all other events should be dropped.
See https://codice.atlassian.net/browse/DDF-3151[DDF-3151] for status.
// TODO: Remove this notice upon completion of https://codice.atlassian.net/browse/DDF-3151.

