:type: plugin
:status: published
:title: Metacard Attribute Security Policy Plugin
:link: _metacard_attribute_security_policy_plugin
:plugintypes: policy
:summary: Collects attributes into a security field for the metacard.

The Metacard Attribute Security Policy Plugin collects attributes from a metacard and combines these attributes into a security field for the metacard.

This plugin assumes that the pertinent information has already been parsed out of the metadata and placed directly on the metacard itself.
The plugin supports mapping attributes from their names on the metacard to a different security policy name. Attributes can be mapped by union or intersection. E.g.
A union mapping of `src1=dest` and `src2=dest` will result in `dest` containing the union of all attributes from `src1` and `src2`; an intersection
 mapping of `src1=dest` and `src2=dest` will result in `dest` containing the intersection of common attributes from `src1` and `src2`.

===== Installing the Metacard Attribute Security Policy Plugin

The Metacard Attribute Security Policy Plugin is installed by default with a standard installation in the ${ddf-catalog} application.

===== Configuring the Metacard Attribute Security Policy Plugin

. Navigate to the *${admin-console}*.
. Select the *${ddf-catalog}* application tile
. Select the *Configuration* tab
. Select the *Metacard Attribute Security Policy Plugin*.

See <<org.codice.ddf.catalog.security.policy.metacard.MetacardAttributeSecurityPolicyPlugin,Metacard Attribute Security Policy Plugin configurations>> for all possible configurations.
