/**
 * Copyright (c) Codice Foundation
 *
 * <p>This is free software: you can redistribute it and/or modify it under the terms of the GNU
 * Lesser General Public License as published by the Free Software Foundation, either version 3 of
 * the License, or any later version.
 *
 * <p>This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details. A copy of the GNU Lesser General Public
 * License is distributed along with this program and can be found at
 * <http://www.gnu.org/licenses/lgpl.html>.
 */
package ddf.platform.solr.security;

import static javax.ws.rs.core.Response.Status.Family.SUCCESSFUL;

import com.google.common.annotations.VisibleForTesting;
import ddf.security.encryption.EncryptionService;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.security.AccessController;
import java.security.PrivilegedAction;
import javax.ws.rs.core.Response.StatusType;
import org.apache.felix.utils.properties.Properties;
import org.codice.ddf.cxf.client.ClientFactoryFactory;
import org.codice.ddf.cxf.client.SecureCxfClientFactory;
import org.codice.ddf.platform.util.uuidgenerator.UuidGenerator;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class SolrPasswordUpdateImpl implements SolrPasswordUpdate {

  private static final String SYSTEM_PROPERTIES_FILE = "custom.system.properties";
  private static final String KARAF_ETC = "karaf.etc";
  private static final String SET_USER_JSON_TEMPLATE = "{ \"set-user\": {\"%s\" : \"%s\"}}";
  private static final Logger LOGGER = LoggerFactory.getLogger(SolrPasswordUpdateImpl.class);

  @SuppressWarnings("squid:S2068")
  private static final String SOLR_PASSWORD_PROPERTY_NAME = "solr.password";

  private final java.util.Properties properties;
  private SolrAuthResource solrAuthResource;
  private String newPasswordPlainText;
  private UuidGenerator uuidGenerator;
  private String newPasswordEncrypted;
  private EncryptionService encryptionService;
  private StatusType solrResponse;

  public SolrPasswordUpdateImpl(
      UuidGenerator uuidGenerator,
      ClientFactoryFactory clientFactoryFactory,
      EncryptionService encryptionService) {
    properties =
        AccessController.doPrivileged(
            (PrivilegedAction<java.util.Properties>) System::getProperties);
    this.encryptionService = encryptionService;
    this.uuidGenerator = uuidGenerator;
    SecureCxfClientFactory<SolrAuthResource> factory =
        clientFactoryFactory.getSecureCxfClientFactory(
            properties.getProperty("solr.http.url"),
            SolrAuthResource.class,
            properties.getProperty("solr.username"),
            getPlaintextPasswordFromProperties());
    solrAuthResource = factory.getClient();
  }

  /**
   * If the password is not changed, change it. Only call this method if the system is configured to
   * use basic authentication for Solr. This method will only change the password if it detects that
   * the default password is still in use. This object is intended to be a singleton, a blueprint
   * bean. That is why is can use itself as the lock
   */
  public synchronized void start() {
    if (configuredToAttemptAutoPasswordChange() && isUsingDefaultPassword()) {
      generatePassword();
      setPasswordInSolr();
      if (isSolrPasswordChangeSuccessfull()) {
        setPasswordInMemory();
        setPasswordInPropertiesFile();
      }
    }
  }

  private void setPasswordInMemory() {
    properties.setProperty(SOLR_PASSWORD_PROPERTY_NAME, newPasswordEncrypted);
    LOGGER.info("Updated encrypted Solr password in memory.");
  }

  private boolean configuredToAttemptAutoPasswordChange() {
    return Boolean.valueOf(properties.getProperty("solr.attemptAutoPasswordChange"));
  }

  /**
   * The return value of this method will change after setPasswordInMemory() is called
   *
   * @return true if in-memory password is the same as hard coded default password
   */
  private boolean isUsingDefaultPassword() {
    return getPlaintextPasswordFromProperties().equals("autogenerated");
  }

  private String getPlaintextPasswordFromProperties() {
    return encryptionService.decrypt(properties.getProperty(SOLR_PASSWORD_PROPERTY_NAME));
  }

  /**
   * Persist the encrypted password to the system properties file. This change does not take effect
   * until the application is restarted.
   */
  private void setPasswordInPropertiesFile() {

    String etcDir = properties.getProperty(KARAF_ETC);
    String systemPropertyFilename = etcDir + File.separator + SYSTEM_PROPERTIES_FILE;
    File systemPropertiesFile = new File(systemPropertyFilename);

    AccessController.doPrivileged(
        (PrivilegedAction<Void>)
            () -> {
              try {
                Properties systemDotProperties = new Properties(systemPropertiesFile);
                systemDotProperties.setProperty(SOLR_PASSWORD_PROPERTY_NAME, newPasswordEncrypted);
                systemDotProperties.save();
                LOGGER.info(
                    "Updated encrypted Solr password in properties file {}.",
                    systemPropertyFilename);
              } catch (IOException e) {
                LOGGER.error(
                    "Exception while writing to {}. Solr password was changed, but new password was not saved.",
                    systemPropertyFilename);
              }
              return null;
            });
  }

  private void setPasswordInSolr() {
    try (InputStream is = new ByteArrayInputStream(getSetUserJson().getBytes())) {
      javax.ws.rs.core.Response response = solrAuthResource.sendRequest(is);
      solrResponse = response.getStatusInfo();
      if (isSolrPasswordChangeSuccessfull()) {
        LOGGER.info("New password was set in Solr server.");
      } else {
        LOGGER.error("Solr password update failed with status code {}.", getResponseStatus());
      }
    } catch (IOException e) {
      LOGGER.info("Solr administration request failed.", e);
    }
  }

  private String getResponseStatus() {
    return String.valueOf(
        solrResponse == null ? "REQUEST FAILED" : String.valueOf(solrResponse.getStatusCode()));
  }

  @VisibleForTesting
  boolean isSolrPasswordChangeSuccessfull() {
    return solrResponse != null && solrResponse.getFamily().equals(SUCCESSFUL);
  }

  /**
   * Create a secure password. Use a UUID because it is long enough and random enough to withstand
   * brute-force attacks.
   */
  private void generatePassword() {
    newPasswordPlainText = uuidGenerator.generateUuid();
    newPasswordEncrypted = encryptionService.encrypt(newPasswordPlainText);
  }

  /**
   * Create JSON object to use as the body of an HTTP request to be sent to Solr. Use the value of
   * the new password and the Solr user name as it is found in system properties.
   *
   * @return BODY of the POST message to set a new password in Solr
   */
  private String getSetUserJson() {
    return String.format(
        SET_USER_JSON_TEMPLATE, properties.getProperty("solr.username"), newPasswordPlainText);
  }
}
