:title: Catalog API
:type: catalogFrameworkIntro
:status: published
:summary: Introduction to Catalog API.
:order: 02

==== Catalog API

The Catalog API is an OSGi bundle (`catalog-core-api`) that contains the Java interfaces for the Catalog components and implementation classes for the Catalog Framework, Operations, and Data components.

===== Catalog API Search Interfaces

The Catalog API includes two different search interfaces.

${ddf-ui} Application Search Interface:: The ${branding} Search UI application provides a graphic interface to return results and locate them on an interactive globe or map.

SSH Search Interface:: Additionally, it is possible to use a client script to remotely access ${branding} via SSH and send console commands to search and ingest data.

===== Catalog Search Result Objects

Data is returned from searches as Catalog Search `Result` objects.
This is a subtype of Catalog `Entry` that also contains additional data based on what type of sort policy was applied to the search.
Because it is a subtype of Catalog `Entry`, a Catalog Search `Result` has all Catalog ``Entry``’s fields such as metadata, effective time, and modified time.
It also contains some of the following fields, depending on type of search, that are populated by ${branding} when the search occurs:

Distance:: Populated when a point-radius spatial search occurs. Numerical value that indicates the result’s distance from the center point of the search.
Units:: Populated when a point-radius spatial search occurs. Indicates the units (kilometer, mile, etc.) for the distance field.
Relevance:: Populated when a contextual search occurs. Numerical value that indicates how relevant the text in the result is to the text originally searched for.

===== Search Programmatic Flow

Searching the catalog involves three basic steps:

. Define the search criteria (contextual, spatial, or temporal).
.. Optionally define a sort policy and assign it to the criteria.
.. For contextual search, optionally set the `fuzzy` flag to `true` or `false` (the default value for the `Metadata Catalog` `fuzzy` flag is `true`, while the `portal` default value is `false`).
.. For contextual search, optionally set the `caseSensitive` flag to true (the default is that `caseSensitive` flag is NOT set and queries are not case sensitive).
Doing so enables case sensitive matching on the search criteria.
For example, if `caseSensitive` is set to true and the phrase is “Baghdad” then only metadata containing “Baghdad” with the same matching case will be returned.
Words such as “baghdad”, “BAGHDAD”,  and “baghDad” will not be returned because they do not match the exact case of the search term.
. Issue a search.
. Examine the results.

===== Sort Policies

Searches can also be sorted according to various built-in policies.
A sort policy is applied to the search criteria after its creation but before the search is issued.
The policy specifies to the ${branding} the order the Catalog search results should be in when they are returned to the requesting client.
Only one sort policy may be defined per search.

There are three policies available.

.Sort Policies
[cols="4" options="header"]
|===

|Sort Policy
|Sorts By
|Default Order
|Available for

|Temporal
|The catalog search result’s effective time field
|Newest to oldest
|All Search Types

|Distance
|The catalog search result’s distance field
|Nearest to farthest
|Point-Radius Spatial searches

|Relevance
|The catalog search result’s relevance field
|Most to least relevant
|Contextual

|===

If no sort policy is defined for a particular search, the temporal policy will automatically be applied.


===== Product Retrieval

The ${branding} is used to catalog resources.
A Resource is a URI-addressable entity that is represented by a Metacard.
Resources may exist either locally or on a remote data store.

.Examples of Resources

* NITF image
* MPEG video
* Live video stream
* Audio recording
* Document

.Product Retrieval Services

* SOAP Web services
* ${branding} JSON
* ${branding} REST

The Query Service Endpoint, the Catalog Framework, and the `CatalogProvider` are key
components for processing a retrieve resource request.
The Endpoint bundle contains a Web service that exposes the interface to retrieve resources.
The Endpoint calls the `CatalogFramework` to execute the operations of its specification.
The `CatalogFramework` relies on the Sources to execute the actual resource retrieval.
Optional `PreResource` and `PostResource` Catalog Plugins may be invoked by the `CatalogFramework` to modify the resource retrieval request/response prior to the Catalog Provider processing the request and providing the response.
It is possible to retrieve resources from specific remote Sources by specifying the site name(s) in the request.

.Product Caching
Product Caching is enabled by default.
Existing ${branding} clients are able to leverage product caching due to the product cache being implemented in the ${branding}.

.Product Retrieval Request
[ditaa,product_retrieval_request,png]
....
+------+             +---------------------------------------------------------------------------------------------------------------------------------+
| cDEF |             |/-----------------\/--------------------------\/-----------------\/------------------\/--------------------------\/-------------\|/--------------------\
|Client|             ||c369<<Endpoint>> ||c369<<CatalogFramework>>  ||c369             ||c369              ||c369<<DownloadManager>>   ||  <<Cache>>  |||c369<<External>>    |
+------+             || Service Endpoint||Standard Catalog Framework||PreResourcePlugin||PostResourcePlugin||     Download Manager     ||c369Cache    |||    Resource Host   |
  :                  |\-----------------/\--------------------------/\-----------------/\------------------/\--------------------------/\-------------/|\--------------------/
  |Service Retrieval |        :                       |                         |               |                     |                        |       |        |
  | Request          |        |                       :                         :               :                     :                        :       |        :
  |------------------|------->|                       |                         |               |                     |                        |       |        |
  |                  |        |query(ResourceRequest) |                         |               |                     |                        |       |        |
  |                  |        |---------------------->|process(ResourceRequest) |               |                     |                        |       |        |
  |                  |        |                       |------------------------>|               |                     |                        |       |        |
  |                  |        |                       |   ResourceRequest       |               |                     |                        |       |        |
  |                  |        |                       |<------------------------|               |                     |                        |       |        |
  |                  | cDEF   |                       | getResource             |               |                     |                        |       |        |
  |                  |        |                       |-------------------------------------------------------------->| download               |       |        |
  |                  |        |                       |                         :               :                     |------------------------|-------|------->|
  |                  |        |                       |                         |               |                     |    resource            |       |        |
  |                  |        |                       |                         |               |                     |<-----------------------|-------|--------|
  |                  |        |                       |                         |               |                     | resource               |       |        |
  |                  |        |                       |                         |               |                     |----------------------->|       |        |
  |                  |        |                       |      resource           |               |                     |                        |       |        |
  |                  |        |                       |<------------------------|-------------------------------------|                        |       |        |
  |                  |        |                       |process(ResourceResponse):               :                     |                        |       |        |
  |                  |        |                       |-------------------------|-------------->|                     |                        |       |        |
  |                  |        |                       |   ResourceResponse      |               |                     |                        |       |        |
  |                  |        |                       |<------------------------|---------------|                     |                        |       |        |
  |Web Service       |        |       ResourceResponse|                         |               |                     |                        |       |        |
  |     Retrieval Response    |<----------------------|                         :               |                     |                        |       |        |
  |<-----------------|--------|                       |                         |               |                     |                        |       |        |
  |                  |        |                       |                         |               |                     |                        |       |        |
  |                  +---------------------------------------------------------------------------------------------------------------------------------+        |
  |                                                                                                                                                             |
....

===== Notifications and Activities

${branding} can send/receive notifications of "Activities" occurring in the system.

====== Notifications

Currently, the notifications provide information about resource retrieval only.

====== Activities

Activity events include the status and progress of actions that are being performed by the user, such as searches and downloads.

