:title: ${ddf-security} Whitelist
:type: reference
:parent: Application Whitelists
:status: published
:order: 04
:summary: ${ddf-security} whitelist.

== {title}

The following classes have been exported by the ${ddf-security} application and are approved for use by third parties:

In package `ddf.security`

* `SecurityConstants`
* `Subject`

In package `ddf.security.assertion`

* `SecurityAssertion`

In package `ddf.security.common.util`

* `Security` Deprecated
* `SecurityProperties`
* `ServiceComparator`
* `SortedServiceList` Deprecated

In package `ddf.security.encryption`

* `EncryptionService`

In package `ddf.security.expansion`

* `Expansion`

In package `ddf.security.http`

* `SessionFactory`

In package `ddf.security.service`

* `SecurityManager`
* `SecurityServiceException`
* `TokenRequestHandler`

In package `ddf.security.sts.client.configuration`

* `STSClientConfiguration`

In package `ddf.security.ws.policy`

* `AbstractOverrideInterceptor`
* `PolicyLoader`

In package `ddf.security.ws.proxy`

* `ProxyServiceFactory`

In package `org.codice.ddf.security.handler.api`

* `AuthenticationHandler`

In package `org.codice.ddf.security.policy.context.attributes`

* `ContextAttributeMapping`

In package `org.codice.ddf.security.policy.context`

* `ContextPolicy`
* `ContextPolicyManager`

