
This section supports integration of this application with external frameworks.

Some notable features of the Solr Catalog Provider include:

* Supports extensible metacards
* Fast, simple contextual searching
* Indexes XML Attributes as well as CDATA sections and XML text elements
* Full XPath support.
* Works with an embedded, local Solr Server (all-in-one Catalog)
** No configuration necessary on a single-node distribution
** Data directory of Solr indexes are configurable
* Works with a standalone Solr Server

=== Embedded Solr Catalog Provider Pros and Cons

[cols="1,4a,2a" options="header"]
|===

|Feature
|Pro
|Con

|Scalability
|
|* Does not scale. Only runs one single server instance.
* Does not allow the middle tier to be scaled.

|Flexibility
|* Can be embedded in Java easily.
* Requires no HTTP connection.
* Uses the same interface as the Standalone Solr Server uses under the covers.
* Allows for full control over the Solr Server. No synchronous issues on startup; i.e., the Solr Server will synchronously start up with the Solr Catalog Provider
* Runs within the same JVM
* Setup and Installation is simple: unzip and run.
|Can only be interfaced using Java

|(Administrative)Tools
|* External open source tools like Luke will work to allow admins to check index contents
* JMX metrics reporting is enabled

|* No Web Console. 
* No easy way to natively access (out of the box) what is in the index files or health of server at the data store level.

|Security
|* Does not open any ports which means no ports have to be secured.
|
 
|Performance
|* Requires no HTTP or network overhead
* Near real-time indexing
* Can understand complex queries
|

|Backup/Recovery
|* Can manually or through custom scripts back up the indexes
|* Must copy files when server is shutdown

|===

==== When to Use

Use the local, embedded Solr Catalog Provider when only one {branding} instance is necessary and scalability is not an issue.
The local, embedded Solr Catalog Provider requires no installation and little to no configuration.
It is great for demonstrations, training exercises, or for sparse querying and ingesting.

=== Solr Catalog External Provider Pros and Cons

[cols="1,3a,3a" options="header"]
|===

|Feature
|Pro
|Con

|Scalability
|* Allows the middle-tier to be scaled by pointing
* various middle-tier instances to one server facade.
* Possible data tier scalability with
Solr Cloud. Solr Cloud allows for "high scale, fault tolerant, distributed indexing and search capabilities."
|* Solr Cloud Catalog Provider not implemented yet.

|Flexibility
|* REST-like HTTP/XML and JSON APIs that make it easy to use from virtually any programming language.
* Ability to run in separate or same JVM of middle tier.
|
 
|(Administrative) Tools
|* Contains Solr Admin GUI, which allows admins to query, check health, see metrics, see configuration files and preferences, etc.
* External open source tools like Luke will work to allow admins to check index contents.
* JMX metrics reporting is enabled.
|

|Security
|* Inherits app server security.
|* Web Console must be secured and is openly accessible.
* REST-like HTTP/XML and JSON APIs must be secured.
* Current Catalog Provider implementation requires sending unsecured messages to Solr. Without a coded solution, requires network or firewall restrictions in order to secure.

|Performance
|* If scaled, high performance.
* Near real-time indexing.
|* Possible network latency impact
* Extra overhead when sent over HTTP. Extra parsing for XML, JSON, or other interface formats.
* Possible limitations upon requests and queries dependent on HTTP server settings.

|Backup/Recovery

|* Built-in recovery tools that allow in-place backups (does not require server shutdown).
* Backup of Solr indexes can be scripted.
|* Recovery is performed as an HTTP request.

|===

==== When to Use

Use the Solr External Provider when the Standalone Solr Server is being used on a separate machine.
Refer to the Standalone Solr Server recommended configuration.

==== Implementation Details

===== Indexing Text

When storing fields, the Solr Catalog Provider will analyze and tokenize the text values of `STRING_TYPE` and `XML_TYPE` `AttributeTypes`.
These types of fields are indexed in at least three ways: in raw form, analyzed with case sensitivity, and analyzed without concern to case sensitivity.
Concerning XML, the Solr Catalog Provider will analyze and tokenize XML CDATA sections, XML element text values, and XML attribute values. 
