:title: Developing Attribute Injections
:type: developingComponent
:status: published
:link: _developing_attribute_injections
:summary: Creating a custom attribute injection.
:order: 05

Attribute injections are defined attributes that will be injected into all metacard types or into specific metacard types. This capability allows metacard types to be extended with new attributes.

==== Attribute Injection Definition

To define attribute injections, the definition file must have an `inject` key in the root object.

[source,json]
----
{
    "inject": [...]
}
----

The value of `inject` is simply a list of objects where each object contains the key `attribute` and optionally `metacardTypes`.

[source,json]
----
{
    "inject": [
        {
            "attribute": ...,
            "metacardTypes": [...]
        }
    ]
}
----

The value corresponding to the `attribute` key is the name of the attribute to inject.

The `metacardTypes` key is optional.
If it is left out, then the attribute will be injected into every metacard type.
In that case it can be thought of as a 'global' attribute injection.
If the `metacardTypes` key is included, then its value must be a list of strings where each string is the name of a metacard type.
In this case, the attribute will be injected only into metacard types that match one of the types given in the list.

Example:
[source,json]
----
{
    "inject": [
        {
            "attribute": "rating"
        },
        {
            "attribute": "cloud-cover",
            "metacardTypes": ["nitf", "video"]
        }
    ]
}
----

[NOTE]
====
Attributes must be registered in the attribute registry (see the `AttributeRegistry` interface) in order to be injected into metacard types. For example, attributes defined in JSON definition files are placed in the registry, so they can be injected.
====
