:title:  Developing Catalog Plugins
:type: developingComponent
:status: published
:link: _developing_catalog_plugins
:summary: Creating a custom catalog plugin.

Plugins extend the functionality of the Catalog Framework by performing actions at specified times during a transaction. 
Plugin interfaces are located in the Catalog Core API.
By implementing a plugin interface, actions can be performed at the desired time. 

[NOTE]
====
Catalog plugin interfaces are located in the catalog core API.
====

The following types of plugins can be created:

.Plugin Interfaces
[cols="1,2m,1", options="header"]
|===

|Plugin Type
|Plugin Interface
|Invocation Order

|<<_pre_authorization_plugins,Pre-Authorization>>
|ddf.catalog.plugin.PreAuthorizationPlugin
|Before any security rules are implemented.

|<<_policy_plugins,Policy>>
|ddf.catalog.plugin.PolicyPlugin
|After pre-authorization plugins, but before other catalog plugins to establish the policy for requests/responses.

|<<_access_plugins,Access>>
|ddf.catalog.plugin.AccessPlugin
|Directly after any policy plugins

|<<_pre_ingest_pluginsPre-Ingest>>
|ddf.catalog.plugin.PreIngestPlugin
|Before the Create/Update/Delete method is sent to the `CatalogProvider`.

|<<_post_ingest_plugins,Post-Ingest>>
|ddf.catalog.plugin.PostIngestPlugin
|After the Create/Update/Delete method is sent to the Catalog Provider.

|<<_post_process_plugins,Post-Process>>
|org.codice.ddf.catalog.async.plugin.api.internal.PostProcessPlugin
|After ingest for additional/asynchronous processing.

|<<_pre_query_plugins,Pre-Query>>
|ddf.catalog.plugin.PreQueryPlugin
|Prior to the Query/Read method being sent to the Source.

|<<_post_query_plugins,Post-Query>>
|ddf.catalog.plugin.PostQueryPlugin
|After results have been retrieved from the query but before they are posted to the Endpoint.

|<<_pre_resource_plugins,Pre-Resource>>
|ddf.catalog.plugin.PreResourcePlugin
|Prior to a Resource being retrieved.

|<<_post_resource_plugins,Post-Resource>>
|ddf.catalog.plugin.PostResourcePlugin
|After a Resource is retrieved, but before it is sent to the Endpoint.

|<<_pre_create_storage_plugins,Pre-Create Storage>>
|ddf.catalog.plugin.PreCreatePlugin
|Before an item is created in the content repository.

|<<_post_create_storage_plugins,Post-Create Storage>>
|ddf.catalog.plugin.PostResourcePlugin
|After an item is created in the content repository.

|<<_pre_update_storage_plugins,Pre-Update Storage>>>
|ddf.catalog.plugin.PostResourcePlugin
|Before an item is updated in the content repository.

|<<_post_update_storage_plugins,Post-Update Storage>>>
|ddf.catalog.plugin.PostResourcePlugin
|After an item is updated in the content repository.

|<<_pre_subscription_plugins,Pre-Subscription>>
|ddf.catalog.plugin.PreSubscriptionPlugin
|Prior to a Subscription being created or updated.

|<<_pre_delivery_plugins,Pre-Delivery>>
|ddf.catalog.plugin.PreDeliveryPlugin
|Prior to the delivery of a Metacard when an event is posted.

|===

==== Implement Plugins

The procedure for implementing any of the plugins follows a similar format:

. Create a new class that implements the specified plugin interface.

. Implement the required methods.

. Create an OSGi descriptor file to communicate with the OSGi registry.

.. Register the plugin class as a service to OSGi registry.

. Deploy to ${branding}.

.Plugin Performance Concerns
[NOTE]
====
Plugins should include a check to determine if requests are local or not. It is usually preferable to take no action on non-local requests.
====

[TIP]
====
Refer to the Javadoc for more information on all Requests and Responses in the `${ddf-branding-lowercase}.catalog.operation` and `${ddf-branding-lowercase}.catalog.event` packages.
====

===== Implementing Pre-Ingest Plugins

Develop a custom Pre-Ingest Plugin.

. Create a Java class that implements `PreIngestPlugin`. +
`public class SamplePreIngestPlugin implements ddf.catalog.plugin.PreIngestPlugin`
+
. Implement the required methods. +
 * `public CreateRequest process(CreateRequest input) throws PluginExecutionException, StopProcessingException;`
 * `public UpdateRequest process(UpdateRequest input) throws PluginExecutionException, StopProcessingException;`
 * `public DeleteRequest process(DeleteRequest input) throws PluginExecutionException, StopProcessingException;`
+
. Import the ${branding} interface packages to the bundle manifest (in addition to any other required packages). +
`Import-Package: ddf.catalog,ddf.catalog.plugin`
+
. Export the service to the OSGi registry. +
*Blueprint descriptor example*
`<service ref="[[SamplePreIngestPlugin ]]"interface="ddf.catalog.plugin.PreIngestPlugin" />`

====== Pre-Ingest Plugin Failure Behavior

In the event that this Catalog Plugin cannot operate but does not wish to fail the transaction, a `PluginExecutionException` will be thrown.
For any other Exceptions, the Catalog will "fail safe" and the Operation will be cancelled.
If processing is to be explicitly stopped, a `StopProcessingException` will be thrown.

====== Invoking Pre-Ingest Plugins

Pre-Ingest plugins are invoked serially, prioritized by descending OSGi service ranking. 
The plugin with the highest service ranking will be executed first. 

The output of a Pre-Ingest plugin is sent to the next Pre-Ingest plugin, until all have executed and the ingest operation is sent to the requested Source.

===== Implementing Post-Ingest Plugins

Develop a custom Post-Ingest Plugin.

. Create a Java class that implements `PostIngestPlugin`. +
`public class SamplePostIngestPlugin implements ddf.catalog.plugin.PostIngestPlugin`

. Implement the required methods. +
 * `public CreateResponse process(CreateResponse input) *throws* PluginExecutionException;`
 * `public UpdateResponse process(UpdateResponse input) *throws* PluginExecutionException;`
 * `public DeleteResponse process(DeleteResponse input) *throws* PluginExecutionException;`

. Import the ${branding} interface packages to the bundle manifest (in addition to any other required packages). +
`Import-Package: ddf.catalog,ddf.catalog.plugin`

. Export the service to the OSGi registry. +
*Blueprint descriptor example*
`<service ref="[[SamplePostIngestPlugin ]]"interface="ddf.catalog.plugin.PostIngestPlugin" />`

====== Post-Ingest Plugin Failure Behavior

In the event that this Catalog Plugin cannot operate but does not wish to fail the transaction, a `PluginExecutionException` will be thrown.

====== Invoking Post-Ingest Plugins

Post-Ingest plugins are invoked serially in rank order.

===== Implementing Pre-Query Plugins

Develop a custom Pre-Query Plugin

. Create a Java class that implements `PreQueryPlugin`. +
`public class SamplePreQueryPlugin implements ddf.catalog.plugin.PreQueryPlugin`

. Implement the required method. +
`public QueryRequest process(QueryRequest input) *throws* PluginExecutionException, StopProcessingException;`
. Import the ${branding} interface packages to the bundle manifest (in addition to any other required packages). +
`Import-Package: ddf.catalog,ddf.catalog.plugin`

. Export the service to the OSGi registry. +
`<service ref="[[SamplePreQueryPlugin]]"interface="ddf.catalog.plugin.PreQueryPlugin" />`

=====  Pre-Query Plugins Failure Behavior

In the event that this Catalog Plugin cannot operate but does not wish to fail the transaction, a `PluginExecutionException` will be thrown.
For any other Exceptions, the Catalog will "fail safe" and the Operation will be cancelled.
If processing is to be explicitly stopped, a `StopProcessingException` will be thrown.

===== Invoking Pre-Query Plugins

Pre-query plugins are invoked serially, prioritized by descending OSGi service ranking. 
The plugin with the highest service ranking will be executed first. 
The output of a pre-query plugin is sent to the next pre-query plugin, until all have executed and the query operation is sent to the requested Source.

===== Implementing Post-Query Plugins

Develop a custom Post-Query Plugin

. Create a Java class that implements `PostQueryPlugin`. +
`public class SamplePostQueryPlugin implements ddf.catalog.plugin.PostQueryPlugin`

. Implement the required method. +
`public QueryResponse process(QueryResponse input) *throws* PluginExecutionException, StopProcessingException;`

. Import the ${branding} interface packages to the bundle manifest (in addition to any other required packages). +
`Import-Package: ddf.catalog,ddf.catalog.plugin`

. Export the service to the OSGi registry. +
`<service ref="[[SamplePostQueryPlugin]]"interface="ddf.catalog.plugin.PostQueryPlugin" />`

====== Post-Query Plugin Failure Behavior

In the event that this Catalog Plugin cannot operate but does not wish to fail the transaction, a `PluginExecutionException` will be thrown.
For any other Exceptions, the Catalog will "fail safe" and the Operation will be cancelled.
If processing is to be explicitly stopped, a `StopProcessingException` will be thrown.

====== Invoking Post-Query Plugins

Post-query plugins are invoked serially, prioritized by descending OSGi service ranking. 
The plugin with the highest service ranking will be executed first. 
The output of the first plugin is sent to the next plugin, until all have executed and the response is returned to the requesting endpoint.

===== Implementing Pre-Delivery Plugins

Develop a custom Pre-Delivery Plugin.

. Create a Java class that implements `PreDeliveryPlugin`. +
`public class SamplePreDeliveryPlugin *implements* ddf.catalog.plugin.PreDeliveryPlugin`

. Implement the required methods. +
`public Metacard processCreate(Metacard metacard) *throws* PluginExecutionException, StopProcessingException;`
`public Update processUpdateMiss(Update update) *throws* PluginExecutionException,
StopProcessingException;`
 * `public Update processUpdateHit(Update update) *throws* PluginExecutionException, StopProcessingException;`
 * `public Metacard processCreate(Metacard metacard) *throws* PluginExecutionException, StopProcessingException;`

. Import the ${branding} interface packages to the bundle manifest (in addition to any other required packages). +
`Import-Package: ddf.catalog,ddf.catalog.plugin,ddf.catalog.operation,ddf.catalog.event`

. Export the service to the OSGi registry. +
*Blueprint descriptor example* +
`<service ref="[[SamplePreDeliveryPlugin]]"interface="ddf.catalog.plugin.PreDeliveryPlugin" />`

====== Pre-Delivery Plugin Failure Behavior

In the event that this Catalog Plugin cannot operate but does not wish to fail the transaction, a `PluginExecutionException` will be thrown.
For any other Exceptions, the Catalog will "fail safe" and the Operation will be cancelled.
If processing is to be explicitly stopped, a `StopProcessingException` will be thrown.

====== Invoking Pre-Delivery Plugins

Pre-delivery plugins are invoked serially, prioritized by descending OSGi service ranking.
The plugin with the highest service ranking will be executed first. 

The output of a pre-delivery plugin is sent to the next pre-delivery plugin, until all have executed and the Delivery Method is invoked on the associated Subscription.

===== Implementing Pre-Subscription Plugins

Develop a custom Pre-Subscription Plugin.

. Create a Java class that implements `PreSubscriptionPlugin`. +
`public class SamplePreSubscriptionPlugin *implements* ddf.catalog.plugin.PreSubscriptionPlugin

. Implement the required method.
 * `public Subscription process(Subscription input) *throws* PluginExecutionException, StopProcessingException;`

====== Pre-Subscription Plugin Failure Behavior

In the event that this Catalog Plugin cannot operate but does not wish to fail the transaction, a `PluginExecutionException` will be thrown.
For any other Exceptions, the Catalog will "fail safe" and the Operation will be cancelled.
If processing is to be explicitly stopped, a `StopProcessingException` will be thrown.

====== Invoking Pre-Subscription Plugin

Pre-subscription plugins are invoked serially, prioritized by descending OSGi service ranking. 
That is, the plugin with the highest service ranking will be executed first. 

The output of a pre-subscription plugin is sent to the next pre-subscription plugin, until all have executed and the create Subscription operation is sent to the Event Processor.

===== Implementing Pre-Resource Plugins

Develop a custom Pre-Resource Plugin.

. Create a Java class that implements `PreResourcePlugin`.
`public class SamplePreResourcePlugin *implements* ddf.catalog.plugin.PreResourcePlugin`

. Implement the required method. +
 * `public ResourceRequest process(ResourceRequest input) *throws* PluginExecutionException, StopProcessingException;`

. Import the ${branding} interface packages to the bundle manifest (in addition to any other required packages). +
`Import-Package: ddf.catalog,ddf.catalog.plugin,ddf.catalog.operation`

. Export the service to the OSGi registry.
.Blueprint descriptor example
[source,xml]
----
<service ref="[[SamplePreResourcePlugin]]" interface="ddf.catalog.plugin.PreResourcePlugin" />
----

===== Pre-Resource Plugin Failure Behavior

In the event that this Catalog Plugin cannot operate but does not wish to fail the transaction, a `PluginExecutionException` will be thrown.
For any other Exceptions, the Catalog will "fail safe" and the Operation will be cancelled. 
If processing is to be explicitly stopped, a `StopProcessingException` will be thrown.

===== Invoking Pre-Resource Plugins

Pre-Resource plugins are invoked serially, prioritized by descending OSGi service ranking. 
That is, the plugin with the highest service ranking will be executed first. 

The output of the first plugin is sent to the next plugin, until all have executed and the request is sent to the targeted Source.

===== Implementing Post-Resource Plugins

Develop a custom Post-Resource Plugin.

. Create a Java class that implements `PostResourcePlugin`. +
`public class SamplePostResourcePlugin *implements* ddf.catalog.plugin.PostResourcePlugin`

. Implement the required method. +
 * `public ResourceResponse process(ResourceResponse input) *throws* PluginExecutionException, StopProcessingException;`

. Import the ${branding} interface packages to the bundle manifest (in addition to any other required packages). +
`Import-Package: ddf.catalog,ddf.catalog.plugin,ddf.catalog.operation`

. Export the service to the OSGi registry.

.Blueprint descriptor example
[source,xml]
----
<service ref="[[SamplePostResourcePlugin]]" interface="ddf.catalog.plugin.PostResourcePlugin" />
----

===== Post-Resource Plugin Failure Behavior

In the event that this Catalog Plugin cannot operate but does not wish to fail the transaction, a `PluginExecutionException` will be thrown. 
For any other Exceptions, the Catalog will "fail safe" and the Operation will be cancelled.
If processing is to be explicitly stopped, a `StopProcessingException` will be thrown.

====== Invoking Post-Resource Plugins

Post-get resource plugins are invoked serially, prioritized by descending OSGi service ranking. 
The plugin with the highest service ranking will be executed first. 

The output of the first plugin is sent to the next plugin, until all have executed and the response is returned to the requesting endpoint.

===== Implementing Policy Plugins

Develop a custom Policy Plugin.

. Create a Java class that implements `PolicyPlugin`. +
`public class SamplePolicyPlugin *implements* ddf.catalog.plugin.PolicyPlugin`

. Implement the required methods. +
 * `PolicyResponse processPreCreate(Metacard input, Map<String, Serializable> properties) *throws* StopProcessingException;`
 * `PolicyResponse processPreUpdate(Metacard input, Map<String, Serializable> properties) *throws* StopProcessingException;`
 * `PolicyResponse processPreDelete(String attributeName, List<Serializable> attributeValues, Map<String, Serializable> properties) *throws* StopProcessingException;`
 * `PolicyResponse processPreQuery(Query query, Map<String, Serializable> properties) *throws* StopProcessingException;`
 * `PolicyResponse processPostQuery(Result input, Map<String, Serializable> properties) *throws* StopProcessingException;`

. Import the DDF interface packages to the bundle manifest (in addition to any other required packages). +
`Import-Package: ddf.catalog,ddf.catalog.plugin,ddf.catalog.operation`

. Export the service to the OSGi registry.  +
*Blueprint descriptor example* +
`<service ref="[[SamplePolicyPlugin]]" interface="ddf.catalog.plugin.PolicyPlugin" />`

====== Failure Behavior

All failure cases should be handled internally to the plugin with the exception of the `StopProcessingException`. If the exception encountered should stop/block the request then a `StopProcessingException` should be thrown.

===== Implementing Access Plugins

Develop a custom Access Plugin.

. Create a Java class that implements `AccessPlugin`. +
`public class SamplePostResourcePlugin *implements* ddf.catalog.plugin.AccessPlugin`

. Implement the required methods. +
 * `CreateRequest processPreCreate(CreateRequest input) *throws* StopProcessingException;`
 * `UpdateRequest processPreUpdate(UpdateRequest input) *throws* StopProcessingException;`
 * `DeleteRequest processPreDelete(DeleteRequest input) *throws* StopProcessingException;`
 * `QueryRequest processPreQuery(QueryRequest input) *throws* StopProcessingException;`
 * `QueryResponse processPostQuery(QueryResponse input) *throws* StopProcessingException;`

. Import the DDF interface packages to the bundle manifest (in addition to any other required packages). +
`Import-Package: ddf.catalog,ddf.catalog.plugin,ddf.catalog.operation`

. Export the service to the OSGi registry.  +
*Blueprint descriptor example* +
`<service ref="[[SampleAccessPlugin]]" interface="ddf.catalog.plugin.AccessPlugin" />`

===== Access Plugins Failure Behavior

All failure cases should be handled internally to the plugin with the exception of the `StopProcessingException`. If the exception encountered should stop/block the request then a `StopProcessingException` should be thrown.
