= Managing {branding} Spatial Application
include::config.adoc[]

== Overview
The {branding} Spatial Application provides KML transformer and a KML network link endpoint that allows a user to generate a View-based KML Query Results Network Link.

This page describes:

* which applications must be installed prior to installing this application. 
* how to install the {branding} Spatial Application.
* how to verify if the application was successfully installed.
* how to uninstall the application
* how to upgrade the application.

== Prerequisites

Before the {branding} Spatial Application can be installed:

* the {branding} Kernel must be running
* the {branding} Platform Application must be installed 
* the {branding} Catalog Application must be installed

== Installing
. Before installing a {branding} application, verify that its prerequisites have been met.
. Copy the {branding} application's KAR file to the `<INSTALL_DIRECTORY>/deploy` directory.

[NOTE]
====
These Installation steps are the same whether {branding} was installed from a distribution zip or a custom installation using the {branding} Kernel zip.
====

== Verifying
. Verify the appropriate features for the {branding} application have been installed using the `features:list` command to view the KAR file's features.
. Verify that the bundles within the installed features are in an active state.

== Uninstalling
[WARNING]
====
It is very important to save the KAR file or the feature repository URL for the application prior to an uninstall so that the uninstall can be reverted if necessary.
====

If the {branding} application is deployed on the {branding} Kernel in a custom installation (or the application has been upgraded previously), i.e., its KAR file is in the `<INSTALL_DIRECTORY>/deploy` directory, uninstall it by deleting this KAR file.

Otherwise, if the {branding} application is running as part of the {branding} distribution zip, it is uninstalled the first time and only the first time using the `features:removeurl` command:

.Uninstall {branding} application from {branding} distribution
----
features:removeurl -u <Application's feature repository URL>

Example:   features:removeurl -u mvn:org.codice.ddf.spatial/spatial-app/2.5.0/xml/features
----

The uninstall of the application can be verified by the absence of any of the {branding} application's features in the `features:list` command output.

[NOTE]
====
The repository URLs for installed applications can be obtained by entering:
      `features:listrepositories -u`
====

== Reverting the Uninstall

If the uninstall of the {branding} application needs to be reverted, this is accomplished by either:

* copying the application's KAR file previously in the `<INSTALL_DIRECTORY>/deploy` directory, OR
* adding the application's feature repository back into {branding} and installing its main feature, which typically is of the form `<applicationName>-app`, e.g., `catalog-app`.

.Reverting {branding} application's uninstall
----
features:addurl <Application's feature repository URL>
features:install <Application's main feature>

Example:

    ddf@local>features:addurl mvn:ddf.catalog/catalog-app/2.3.0/xml/features
    ddf@local>features:install catalog-app
----

== Upgrading

To upgrade an application, complete the following procedure.

. Uninstall the application by following the Uninstall Applications instructions above.
. Install the new application KAR file by copying the `admin-app-X.Y.kar` file to the `<INSTALL_DIRECTORY>/deploy` directory. 
. Start the application.
. Complete the steps in the Verify section above to determine if the upgrade was successful.

