== Applications

${branding} is comprised of several modular applications, to be installed or uninstalled as needed.

${ddf-branding} Administrative Application::
The administrative application enhances administrative capabilities when installing and managing ${branding}. It contains various services and interfaces that allow administrators more control over their systems.

${ddf-branding} Catalog Application::
The ${branding} Catalog provides a framework for storing, searching, processing, and transforming information.
Clients typically perform local and/or federated query, create, read, update, and delete (QCRUD) operations against the Catalog.
At the core of the Catalog functionality is the *Catalog Framework*, which routes all requests and responses through the system, invoking additional processing per the system configuration.

${ddf-branding} Platform Application::
The Platform application is considered to be a core application of the distribution.
The Platform application has fundamental building blocks that the distribution needs to run.

${ddf-branding} Security Application::
The Security application provides authentication, authorization, and auditing services for the ${branding}.
It is both a framework that developers and integrators can extend and a reference implementation that meets security requirements.

${ddf-branding} Solr Catalog Application::
The Solr Catalog Provider (SCP) is an implementation of the `CatalogProvider` interface using http://lucene.apache.org/solr/[Apache Solr] as a data store.

${ddf-branding} Spatial Application::
The ${ddf-branding} Spatial Application provides KML transformer and a KML network link endpoint that allows a user to generate a View-based KML Query Results Network Link.

${ddf-branding} Standard Search UI::
The ${ddf-branding} Standard Search UI application allows a user to search for records in the local Catalog (provider) and federated sources.
Results of the search are returned and displayed on a globe or map, providing a visual representation of where the records were found.

