:title: Starting Intro
:type: startingIntro
:status: published
:summary: Starting and stopping an instance.
:order: 01

Follow the below steps to start and stop ${branding}.

.Memory Considerations[[jvm-memory-configuration]]
[NOTE]
====
If the ${branding} will be running memory-intensive applications, consider increasing the java memory. The java memory can be changed by updating the setenv script:

.Setenv Script: *NIX
----
<${branding}_HOME>/bin/setenv
Update the JAVA_OPTS -Xmx value
----

.Setenv Script: Windows
----
<${branding}_HOME>/bin/setenv.bat
Update the JAVA_OPTS -Xmx value
----
====

.JMX Connectivity Considerations
[NOTE]
====
[[jmx-connectivity-configuration]]
By default the ${branding} prevents connections to JMX. To monitor the ${branding} via tools such as JConsole, consider removing the no attach mechanism by updating the setenv script:

.Setenv Script: *NIX
----
<${branding}_HOME>/bin/setenv
Remove -XX:+DisableAttachMechanism from JAVA_OPTS
----

.Setenv Script: Windows
----
<${branding}_HOME>/bin/setenv.bat
Remove -XX:+DisableAttachMechanism from JAVA_OPTS
----
====

==== Starting from Startup Scripts

Run one of the start scripts from a command shell to start the distribution and open a local console:

.Start Script: *NIX
----
<${branding}_HOME>/bin/${ddf-branding-lowercase}
----

.Start Script: Windows
----
<${branding}_HOME>/bin/${branding-lowercase}.bat
----

==== Starting as a Service

Alternatively, to run ${branding} as a background service, run the `start` script:

.*NIX
----
<${branding}_HOME>/bin/start
----

.Windows
----
<${branding}_HOME>/bin/start.bat
----

[NOTE]
====
If console access is needed while running as a service, run the `client` script on the host where the ${branding} is running:

.*NIX
----
<${branding}_HOME>/bin/client
----

.Windows
----
<${branding}_HOME>/bin/client.bat -h localhost
----

If running the `client` script form a different host, use the `-h` option followed by the name or IP of the host where ${branding} is running.
====

==== Stopping ${branding}

There are two options to stop a running instance:

* Call shutdown from the console:

.Shut down with a prompt
----
${branding-lowercase}${at-symbol}local>shutdown
----

.Force Shutdown without prompt
----
${branding-lowercase}${at-symbol}local>shutdown -f
----

* Keyboard shortcut for shutdown
** `Ctrl`-`D`
** `Cmd`-`D`
* Or run the stop script:

.*NIX
----
<${branding}_HOME>/bin/stop
----

.Windows
----
<${branding}_HOME>/bin/stop.bat
----

.Shut Down
[IMPORTANT]
====
Do not shut down by closing the window (Windows, Unix) or using the `kill -9 <pid>` command (Unix).
This prevents a clean shutdown and can cause significant problems when ${branding} is restarted.
Always use the shutdown command or the shortcut from the command line console.
====

==== Automatic Start on System Boot

Because ${branding} is built on top of Apache Karaf, ${branding} can use the Karaf Wrapper to enable automatic startup and shutdown.

. Create the Karaf wrapper.
+
.Within the ${branding} console
----
${branding-lowercase}${at-symbol}local> feature:install -r wrapper
${branding-lowercase}${at-symbol}local> wrapper:install -s AUTO_START -n ${branding-lowercase} -d ${branding-lowercase} -D "${branding} Service"
----
+
. (Windows users skip to next step) (All *NIX) If ${branding} was installed to run as a non-root user (recommended,) edit `<${branding}_HOME>/bin/${branding-lowercase}-service`.
+
Change:
+
.<${branding}_HOME>/bin/${branding-lowercase}-service
----
#RUN_AS_USER=
----
+
to:
+
.<${branding}_HOME>/bin/${branding-lowercase}-service
----
RUN_AS_USER=<${branding-lowercase}-user>
----
+
. (Windows users skip to next step) (All *NIX) Edit `<${branding}_HOME>/bin/${branding-lowercase}.service`. Add LimitNOFILE to the [Service] section.
+
.<${branding}_HOME>/bin/${branding-lowercase}.service
----
LimitNOFILE=6815744
----
+
. Set the memory in the wrapper config to match with ${branding} default memory setting.
+
.<${branding}_HOME>/etc/${branding-lowercase}-wrapper.conf
[source,java,linenums]
----
#Add the following:
wrapper.java.additional.11=-D${ddf-branding-lowercase}.home=%KARAF_HOME%
wrapper.java.additional.12=-Dderby.storage.fileSyncTransactionLog=true
wrapper.java.additional.13=-Djava.security.egd=file:/dev/./urandom
wrapper.java.additional.14=-Dfile.encoding=UTF8
wrapper.java.additional.15=-Dkaraf.instances=%KARAF_HOME%/instances
wrapper.java.additional.16=-Dkaraf.restart.jvm.supported=true
wrapper.java.additional.17=-Djava.util.logging.config.file=%KARAF_HOME%/etc/java.util.logging.properties
wrapper.java.additional.18=-XX:+UnlockDiagnosticVMOptions
wrapper.java.additional.19=-Dderby.system.home=%KARAF_HOME%/data/derby
wrapper.java.additional.20=-Djava.awt.headless=true

# Set the JVM max heap space as desired
wrapper.java.additional.21=-Xmx4g

# (Preferred) Optionally add the disable attach mechanism to prevent connections to JMX
wrapper.java.additional.22=-XX:+DisableAttachMechanism

----
+
Remove or comment out `wrapper.java.maxmemory=512`:
+
.<${branding}_HOME>/etc/${branding-lowercase}-wrapper.conf
----
#wrapper.java.maxmemory=512
----
+
. Install the wrapper startup/shutdown scripts.
+
*Windows*
+
Run the following command in a console window. The command must be run with elevated permissions.
+
----
<${branding}_HOME>/bin/${branding-lowercase}-service.bat install
----
Startup and shutdown settings can then be managed through *Services -> MMC Start -> Control Panel -> Administrative Tools -> Services*.
+
*Redhat*
+
----
root${at-symbol}localhost# ln -s <${branding}_HOME>/bin/${branding-lowercase}-service /etc/init.d/
root${at-symbol}localhost# chkconfig ${branding-lowercase}-service --add
root${at-symbol}localhost# chkconfig ${branding-lowercase}-service on
----
+
*Redhat 7 (systemd)*
+
----
root${at-symbol}localhost# systemctl enable <${branding}_HOME>/bin/${branding-lowercase}.service
----
+
*Ubuntu*
+
----
root${at-symbol}localhost# ln -s <${branding}_HOME>/bin/${branding-lowercase}-service /etc/init.d/
root${at-symbol}localhost# update-rc.d -f ${branding-lowercase}-service defaults
----
+
*Solaris*
+
----
root${at-symbol}localhost# ln -s <${branding}_HOME>/bin/${branding-lowercase}-service /etc/init.d/
root${at-symbol}localhost# ln -s /etc/init.d/${branding-lowercase}-service /etc/rc0.d/K20${branding-lowercase}-service
root${at-symbol}localhost# ln -s /etc/init.d/${branding-lowercase}-service /etc/rc1.d/K20${branding-lowercase}-service
root${at-symbol}localhost# ln -s /etc/init.d/${branding-lowercase}-service /etc/rc2.d/K20${branding-lowercase}-service
root${at-symbol}localhost# ln -s /etc/init.d/${branding-lowercase}-service /etc/rc3.d/S20${branding-lowercase}-service
----
+
[WARNING]
====
While it is not a necessary step, information on how to convert the System V init scripts to the Solaris System Management Facility can be found at http://www.oracle.com/technetwork/articles/servers-storage-admin/scripts-to-smf-1641705.html
====
+
.Solaris-Specific Modification
[WARNING]
====
Due to a slight difference between the Linux and Solaris implementation of the `ps` command, the `${ddf-branding-lowercase}-service` script needs to be modified.
====
+
. Locate the following line in <${branding}_HOME>/bin/${branding-lowercase}-service
+
.Solaris <${branding}_HOME>/bin/${branding-lowercase}-service
----
pidtest=`$PSEXE -p $pid -o command | grep $WRAPPER_CMD | tail -1`
----
+
. Change the word command to comm.
+
.Solaris <${branding}_HOME>/bin/${branding-lowercase}-service
----
pidtest=`$PSEXE -p $pid -o comm | grep $WRAPPER_CMD | tail -1`
----

===== Karaf Documentation

Because ${branding} is built on Apache Karaf, more information on operating ${branding} can be found in the http://karaf.apache.org/index/documentation.html[Karaf documentation].

