
=== Directory Monitors

====  Content Directory Monitor
The Content Directory Monitor provides the capability to easily add content and metacards into the ${ddf-catalog} by placing a file in a directory.

===== Installing the Content Directory Monitor

The Content Directory Monitor is installed by default with a standard installation of the ${ddf-catalog} application.

===== Configuring the Content Directory Monitor

Configure the Content Directory Monitor from the ${admin-console}:

. Navigate to the *${admin-console}*.
. Select the *${ddf-catalog}* application.
. Select the *Configuration* tab.
. Select *Catalog Content Directory Monitor*.

include::{adoc-include}/_tables/org.codice.ddf.catalog.content.monitor.ContentDirectoryMonitor-table-contents.adoc[]

===== Using the Content Directory Monitor

The Content Directory Monitor processes files in a directory, and all of its sub-directories. The Content Directory Monitor offers three options:

* Delete
* Move
* Monitor in place

Regardless of the option, the ${branding} takes each file in a monitored directory structure and creates a metacard for it. The metacard is linked to the file. The behavior of each option is given below.

* *Delete*
** Copies the file into the Content Repository.
** Creates a metacard in the Catalog from the file.
** *Erases the original file from the monitored directory.

* *Move*
** *Copies the file into the directory `.\ingested` (this will double the disk space used)*
** Copies the file into the Content Repository.
** Creates a metacard in the Catalog from the file.
** *Erases the original file from the monitored directory.

* *Monitor in place*
** Creates a metacard in the Catalog from the file.
** Creates a reference from the metacard to the original file in the monitored directory.
** If the original file is deleted, the metacard is removed from the Catalog.
** If the original file is modified, the metacard is updated to reflect the new content.
** If the original file is renamed, the old metacard is deleted and a new metacard is created.

.Atribute Mapper
The Content Directory Monitor supports setting metacard attributes directly when ${branding} ingests a file. Custom mappings are entered in the form:

`*attribute-name=attribute-value*`

For example, to set the contact email for all metacards, add the custom mapping:

`*contact.point-of-contact-email=doctor@clinic.com*`

Each mapping sets the value of a single metacard attribute. To set the value of an additional attribute, select the "plus"
 icon in the UI. This creates an empty line for the entry.

To set multi-valued attributes, use a separate override for each value. For example, to add the keywords _PPI_ and _radiology_ to each metacard, add the custom attribute mappings:

`*topic.keyword=PPI*` +
`*topic.keyword=radiology*`

.Errors
If the directory monitor fails to read the file, an error will be logged in the ingest log. If the directory monitor is
configured to *Delete* or *Move*, the original file is also moved to the `\.errors` directory.

.Other
* Multiple directories can be monitored. Each directory has an independent configuration.
* To support the monitoring in place behavior, ${branding} indexes the files to track their names and modification timestamps. This enables the Content Directory Monitor to take appropriate action when files are changed or deleted.
* The Content Directory Monitor recursively processes all subdirectories.

