.Resources Architecture
[ditaa, catalog_architecture_resources, png, ${image-width}]
....
+------------------------------------------------------------+
|                /-------------------\                       |
|                |cDEFEndpoints      |                       |
|                +------------+------+                       |
|                |cDEF        |cDEF  |                       |
|                | Operations | Data |                       |
|/---------------+------------+------+------------+---------\|
||cDEF           |cDEF               |cDEF        |cDEF     ||
||  Transformers |                   | Federation | Sources ||
|+---------------+ Catalog Framework +------------+---------+|
||cDEF           |                   |cDEF   Eventing       ||
||   Catalog     |                   +------------+---------+|
||   Plugins     |                   |c369   Resources      ||
|\---------------+-------------------+----------------------/|
|                |cDEF               |                       |
|                | Catalog Provider  |                       |
|                +-------------------+                       |
|                |cDEF               |                       |
|                | Storage Provider  |                       |
|                \-------------------/                       |
+------------------------------------------------------------+
....

Resources are the data that is represented by the cataloged metadata in ${branding}.

Metacards are used to describe those resources through metadata. 
This metadata includes the time the resource was created, the location where the resource was created, etc. 
A ${branding} `Metacard` contains the `getResourceUri` method, which is used to locate and retrieve its corresponding resource.

The Catalog Framework can interface with Storage providers to provide storage of resources to specific types of  storage, e.g., file system, relational database, XML database.
A default file system provider is provided by default.
Storage plugins provide pluggable functionality that can be executed either immediately before or immediately after content has been stored or updated.
Storage providers act as a proxy between the Catalog Framework and the mechanism storing the content, e.g., file system, relational database.
Storage providers expose the storage mechanism to the Catalog Framework.

Storage providers provide the capability to the Catalog Framework to create, read, update, and delete content in the content repository.

.Content Data Component Architecture
[ditaa, content_data_components, png,${image.width}]
....
+------------------------------------------------------------------------------+
|                 /-=-----------------\                                        |
|                 |      Clients      |                                        |
|                 \-------------------/                                        |
|                           ^                                                  |
|                           |                                                  |
|                           v                                                  |
|                 /-------------------\                                        |
|                 |cDEF Endpoints     |                                        |
|                 +------------+------+                                        |
|                 | cDEF       | c369 |                                        |
|                 | Operations | Data |                                        |
|                 +------------+------+-----------------------\                |
|                 | cDEF              |cDEF Transformers      |                |
|                 |                   +-----------------------+                |
|                 | Catalog Framework |cDEFStorage Plugins    |                |
|                 |                   +-----------------------+                |
|                 |                   |                                        |
|                 +-------------------|                                        |
|                 |cDEF               |                                        |
|                 | Storage Provider  |                                        |
|                 \-------------------/                                        |
|                           ^                                                  |
|                           |                                                  |
|                           v                                                  |
|                   +-=-------------+                LEGEND                    |
|                   |{s}            |                /--------------------\    |
|                   |   Content     |                |cDEF${branding} Component   |    |
|                   |  Repository   |                \--------------------/    |
|                   +---------------+                /-=------------------\    |
|                                                    | External Component |    |
|                                                    \--------------------/    |
+------------------------------------------------------------------------------+
....

=== Content Item

ContentItem is the domain object populated by the Storage Provider that represents the information about the content to be stored or content that has been stored in the Storage Provider.
A ContentItem encapsulates the content's globally unique ID, mime type, and input stream (i.e., the actual content).
The unique ID of a ContentItem will always correspond to a Metacard ID.

