
==== URL Resource Reader

The `URLResourceReader` is an implementation of `ResourceReader` which is included in the ${branding} Catalog. 
It obtains a resource given an http, https, or file-based URL. 
The `URLResourceReader` will connect to the provided Resource URL and read the resource's bytes into an `InputStream`.  

[WARNING]
====
When a resource linked using a file-based URL is in the product cache, the `URLResourceReader`&#8217;s rootResourceDirectories is not checked when downloading the product.
It is downloaded from the product cache which bypasses the `URLResourceReader`.
For example, if path `/my/valid/path` is configured in the `URLResourceReader`&#8217;s rootResourceDirectories and one downloads the product with resource-uri `file:///my/valid/path/product.txt` and then one removes `/my/valid/path` from the `URLResourceReader`&#8217;s `rootResourceDirectories` configuration, the product will still be accessible via the product cache.
====

===== Installing the URL Resource Reader

The `URLResourceReader` is installed by default with a standard installation in the ${ddf-catalog} application.

===== Configuring the URL Resource Reader

.URL Resource Reader Configurable Properties
[cols="1,1,3,1,1", options="header"]
|===

|Property
|Type
|Description
|Default Value
|Required

|`rootResourceDirectories`
|String array
|Specifies the only directories the `URLResourceReader` has access to when attempting to download resources linked using file-based URLs (i.e. the metacard attribute resource-uri uses the file URI scheme). This property is used to restrict the `URLResourceReader`&#8217;s access to the file system. The `URLResourceReader` can be given full access to the file system by setting the `rootResourceDirectories` property to the root directory (e.g. `/`), but this configuration is not recommended.
|<${ddf-branding}.home>/data/products
|yes

|===

===== Using the URL Resource Reader

`URLResourceReader` will be used by the Catalog Framework to obtain a resource whose metacard is cataloged in the local data store.
This particular `ResourceReader` will be chosen by the `CatalogFramework` if the requested resource's URL has a protocol of `http`, `https`, or `file`.  

For example, requesting a resource with the following URL will make the Catalog Framework invoke the `URLResourceReader` to retrieve the product.

.Example
[source,http]
----
file:///home/users/${ddf-branding}_user/data/example.txt
----

If a resource was requested with the URL `udp://123.45.67.89:80/SampleResourceStream`, the `URLResourceReader` would _not_ be invoked.

.Supported Schemes:
* http
* https
* file

[NOTE]
====
If a file-based URL is passed to the `URLResourceReader`, that file path needs to be accessible by the ${branding} instance.
====

===== Known Issues with the URL Resource Reader

None.
