:title: Compression Services
:type: subConfiguration
:status: published
:parent: Configuring Endpoints
:summary: Supports compression of outgoing and incoming messages.
:order: 06

== {title}

${branding} supports compression of outgoing and incoming messages through the Compression Services.
These compression services are based on http://cxf.apache.org/[CXF] message encoding.

The formats supported in ${branding} are:

gzip:: Adds GZip compression to messages through CXF components. Code comes with CXF.

exi:: Adds http://www.w3.org/XML/EXI/[Efficient XML Interchange (EXI)] {external-link} support to outgoing responses. EXI is an W3C standard for XML encoding that shrinks xml to a smaller size than normal GZip compression.

To Install a compression service:

* Navigate to the *${admin-console}*.
* Select the *System* tab.
* Select the *Features* tab.
* Start the service for the desired compression format:
** `compression-exi`
** `compression-gzip`

[WARNING]
====
The compression services either need to be installed BEFORE the desired CXF service is started or the CXF service needs to be refreshed / restarted after the compression service is installed.
====

Compression services have no configurable properties.
They can only be installed or uninstalled.
