:title: Configuration Files
:type: configuringIntro
:status: published
:parent: Configuring
:order: 03
:summary: Configuring files in home directory hierarchy.

== {title}

Many important configuration settings are stored in the `${home_directory}` directory.

[NOTE]
====
Depending on the environment, it may be easier for integrators and administrators to configure ${branding} using the ${admin-console} prior to disabling it for hardening purposes.
The ${admin-console} can be re-enabled for additional configuration changes.
====

In an environment hardened for security purposes, access to the ${admin-console} or the ${command-console} might be denied and using the latter in such an environment may cause configuration errors.
For this reason,`.config` files (such as providers, Schematron rulesets, etc.)
are necessary to configure ${branding}.

A template file is provided for some configurable ${branding} items so that they can be copied/renamed then modified with the appropriate settings.

[WARNING]
====
If the ${admin-console} is enabled again, all of the configuration done via `.config` files is loaded and displayed.
However, note that the name of the `.config` file is not used in the ${admin-console}.
Rather, a universally unique identifier (UUID) is added when the ${branding} item was created and displays this UUID in the console (for example, `OpenSearchSource.112f298e-26a5-4094-befc-79728f216b9b`)
====
