:title: Configuring KML Endpoint
:type: subConfiguration
:status: published
:parent: Configuring Endpoints
:summary: Configuring KML Endpoint
:order: 03

== {title}

Keyhole Markup Language (_KML_) is an XML notation for describing geographic annotation and visualization for 2- and 3- dimensional maps.

The root network link will create a network link for each configured source, including the local catalog.
The individual source network links will perform a query against the OpenSearch Endpoint periodically based on the current view in the KML client.
The query parameters for this query are obtained by a bounding box generated by Google Earth.
The root network link will refresh every 12 hours or can be forced to refresh.
As a user changes their current view, the query will be re-executed with the bounding box of the new view.
(This query gets re-executed two seconds after the user stops moving the view.)

This KML Network Link endpoint has the ability to serve up custom KML style documents and Icons to be used within that document.
The KML style document must be a valid XML document containing a KML style.
The KML Icons should be placed in a single level directory and must be an image type (png, jpg, tif, etc.).
The Description will be displayed as a pop-up from the root network link on Google Earth.
This may contain the general purpose of the network and URLs to external resources.￼￼￼


To install the KML endpoint:

. Navigate to the *${admin-console}*.
. Select *System*.
. Select *Features*.
. Install the `spatial-kml` feature.

To configure the KML endpoint:

. Navigate to the *${admin-console}*.
. Select *System*.
. Select *Features*.
. Select *KML Endpoint*.

See <<{reference-prefix}org.codice.ddf.spatial.kml.endpoint.KmlEndpoint,KML Endpoint configurations>> for all possible configurations.
