:title: Configuring Guest Access
:type: configuration
:status: published
:summary: Allow or prohibit guest user access
:parent: Configuring User Access
:order: 00

== {title}

Unauthenticated access to a secured ${branding} system is provided by the *Guest* user.
By default, ${branding} allows guest access.

Because ${branding} does not know the identity of a Guest user, it cannot assign security attributes to the Guest.
The administrator must configure the attributes and values (i.e. the "claims") to be assigned to Guests.
The Guest Claims become the default minimum attributes for every user, both authenticated and unauthenticated.
Even if a user claim is more restrictive, the guest claim will grant access, so ensure the guest claim is only as permissive as necessary.

The *Guest* user is uniquely identified with a Principal name of the format `Guest@UID`. The unique
identifier is assigned to a Guest based on its source IP address and is cached so that subsequent
Guest accesses from the same IP address within a 30-minute window will get the same unique identifier.
To support administrators' need to track the source IP Address for a given Guest user, the IP Address
and unique identifier mapping will be audited in the security log.

* Make sure that all the default logical names for locations of the security services are defined.

=== Denying Guest User Access

To disable guest access for a context, use the <<{managing-prefix}configuring_the_web_context_policy_manager, Web Context Policy Manager>> configuration to remove *Guest*.
from the *Authentication Type* for that context.
Only authorized users are then allowed to continue to the Search UI page.

[NOTE]
====
If using the included IdP for authentication, disable the `Allow Guest Access` option by <<{managing-prefix}configuring_the_idp_server, Configuring the IdP Server>>.
====

=== Allowing Guest User Access

Guest authentication must be enabled and configured to allow guest users.
Once the guest user is configured, redaction and filtering of metadata is done for the guest user the same way it is done for normal users.

To enable guest authentication for a context, use the <<{managing-prefix}configuring_the_web_context_policy_manager, Web Context Policy Manager>> configuration to select *Allow Guest Access*.

. Navigate to the *${admin-console}*.
. Select the *${ddf-security}* application.
. Select the *Configuration* tab.
. Select *Web Context Policy Manager*.
. Select *Allow Guest Access*

==== Configuring Guest Interceptor if Allowing Guest Users

* *{hardening-step}*

If a legacy client requires the use of the secured SOAP endpoints, the <<{developing-prefix}configuring_guest_interceptor,guest interceptor>> should be configured.
Otherwise, the guest interceptor and `public` endpoints should be uninstalled for a hardened system.

To uninstall the guest interceptor and `public` endpoints:
. Navigate to the *${admin-console}*.
. Select the *System* tab.
. Open the *Features* section.
. Search for *security-interceptor-guest*.
. Click the *Uninstall* button.

==== Configuring Guest Claim Attributes

A guest user's attributes define the most permissive set of claims for an unauthenticated user.

A guest user's claim attributes are stored in configuration, not in the LDAP as normal authenticated users' attributes are.

. Navigate to the *${admin-console}*.
. Select the *${ddf-security}* application.
. Select the *Configuration* tab.
. Select the **Security Guest Claims Handler**.
. Add any additional attributes desired for the guest user.
. Save changes.
