:title: Connecting to an External Identity Provider
:type: subConfiguration
:status: published
:parent: Configuring REST Services for Users
:summary: Configuring to use an existing IdP outside of ${branding}.
:order: 10

== {title}

To connect to an external Identity Provider,

. Provide the external IdP with ${branding}'s Service Provider (SP) metadata.
The SP metadata can found at `https://<FQDN>:<PORT>/services/saml/sso/metadata`.

. Replace the IdP metadata field in ${branding}.
.. Navigate to the *${admin-console}*.
.. Select the *${ddf-security}* application.
.. Select the *Configuration* tab.
.. Select *IdP Client*.
.. Populate the *IdP Metadata* field with the external IdP's metadata.

[NOTE]
====
The certificate that the external IdP uses for signing will need to be added to the ${branding}'s keystore. See <<{managing-prefix}updating_key_store_trust_store_via_the_admin_console,Updating Key Store / Trust Store via the Admin Console>> for details.
====

[NOTE]
====
${branding} may not interoperate successfully with all IdPs.
To idenify the ones it can interoperate with use the https://github.com/codice/saml-conformance[The Security Assertion Markup Language (SAML) Conformance Test Kit (CTK)] {external-link}
====

.Service Provider Metadata
It is not recommended to remove or replace the included Service Provider.
To add an additional, external Service Provider, add the SP metadata to the *IdP Server* configuration.
See <<{managing-prefix}configuring_idp_sp, Configuring Security IdP Service Provider>> for more detail.
