:title: Configuring Default Layout for ${catalog-ui}
:type: subConfiguration
:status: published
:parent: Configuring ${catalog-ui}
:order: 00
:summary: Configuring default layout for ${catalog-ui} using Default Layout UI.

== {title}

${catalog-ui} includes several options for users to display search results.
By default, users start with a *3D map* and an *Inspector* to view details of results or groups of results.
Add or remove additional *visualizations* to the default view through the *Default Layout UI*.
Users can customize their individual views as well.

.Available Visualizations
3D Map _(Default)_:: Display a fully-interactive three-dimensional globe.
2D Map:: Display a less resource-intensive two-dimensional map.
Inspector _(Default)_:: Display a view of detailed information about a search result.
Histogram:: Compare attributes of items in a search result set as a histogram.
Table:: Compare attributes of items in a search result set as a table.

.Configuring Enabled Visualizations
. Navigate to the *${admin-console}*.
. Select the *${ddf-ui}* application.
. Select the *Default Layout* tab.
. *Add* or *Remove* visualizations as desired.
.. To add a visualization, select the *Add* icon.
.. To remove a visualization, select the *Delete* icon on the tab for that visualization.
. Select *Save* to complete.

.Configuring Possible Visualizations
. Navigate to the *${admin-console}*.
. Select the *${ddf-ui}* applicatiAppender Beforeon.
. Select the *Configuration* tab.
. Select `org.codice.ddf.catalog.ui`
. *Edit* "Visualizations" JSON as desired.

+
Example JSON:
+
[source,json]
----
[
  {
    "name": "openlayers",
    "title": "2D Map",
    "icon": "map"
  },
  {
    "name": "cesium",
    "title": "3D Map",
    "icon": "globe"
  },
  {
    "name": "inspector",
    "title": "Inspector",
    "icon": "info"
  },
  {
    "name": "histogram",
    "title": "Histogram",
    "icon": "bar-chart"
  },
  {
    "name": "table",
    "title": "Table",
    "icon": "table"
  }
]

----


. Select *Save* to complete.
