:title: Environment Hardening
:type: configuringIntro
:status: published
:summary: Environment security mitigations.
:order: 09

== {title}

* *{hardening-step}*

[IMPORTANT]
====
It is recommended to apply the following security mitigations to the ${branding}.
====

=== Known Issues with Environment Hardening
The session timeout should be configured longer than the UI polling time or you may get session
timeout errors in the UI.


[cols="1,3,6",options="header]
|===

|Protocol/Type
|Risk
|Mitigation

|JMX
|tampering, information disclosure, and unauthorized access
a|* Stop the management feature using the command line console: `feature:stop management`. +

|File System Access
|tampering, information disclosure, and denial of service
a|Set OS File permissions under the `${home_directory}` directory (e.g. `/deploy`, `/etc`) to ensure unauthorized viewing and writing is not allowed.

 If Caching is installed:

* <<{managing-prefix}setting_directory_permissions,Set permissions>> for the installation directory `/data/product-cache` such that only the ${branding} process and users with the appropriate permissions can view any stored product. +
* Caching can be turned off as well to mitigate this risk. +
** To disable caching, navigate to ${admin-console}. +
** Select the *${ddf-catalog}* application. +
** Select *Resource Download Settings*. +
** Uncheck the `Enable Product Caching` box. +
* Install ${ddf-security} to ensure only the appropriate users are accessing the products. +
** Navigate to the ${admin-console} +
** Select *Manage*. +
** Install the ${ddf-security} application, if applicable. +
* Cached files are written by the user running the ${branding} `process/application`. +

On system: ensure that not everyone can change ACLs on your object.

|SSH
|tampering, information disclosure, and denial of service
a|By default, SSH access to ${branding} is only enabled to connections originating from the same
host running ${branding}.
For remote access to ${branding},
 first establish an SSH session with the host running
 ${branding}. From within that session, initiate a new SSH connection (to **localhost**), and use
 the `sshPort` as configured in the file
 `${home_directory}/etc/org.apache.karaf.shell.cfg`.

To allow direct remote access to the ${branding} shell from any host, change the value of the
`sshHost` property to `0.0.0.0` in the `${home_directory}/etc/org.apache.karaf.shell.cfg` file.

SSH can also be authenticated and authorized through an external Realm,
such as LDAP. This can be accomplished by editing the `${home_directory}/etc/org.apache.karaf.shell.cfg` file and setting the
value for `sshRealm`, e.g. to `ldap`. No restart of ${branding} is necessary after this change.

By definition, all connections over SSH will be authenticated and authorized and secure from eavesdropping.

[WARNING]
====
Enabling SSH will expose your file system such that any user with access to your ${branding} shell will
have read/write/execute access to all directories and files accessible to your installation user.

*Because of this, SSH is not recommended in a secure environment and should be turned off
in a fully hardened system.*
====

Set `karaf.shutdown.port=-1` in `${home_directory}/etc/custom.properties` or `${home_directory}/etc/config.properties`.

|SSL/TLS
|man-in-the-middle, information disclosure
a|Update the `${home_directory}/etc/org.ops4j.pax.web.cfg` file to add the entry `org.ops4j.pax.web.ssl.clientauthneeded=true`.

[WARNING]
====
Setting this configuration may break compatibility to legacy systems that do not support two-way SSL.
====

[WARNING]
====
Setting this configuration will require a certificate to be installed in the browser.
====

|Session Inactivity Timeout
|unauthorized access
a|Update the Session configuration to have no greater than a 10 minute Session Timeout. +

 * Navigate to the *${admin-console}*. +
 * Select the *${ddf-security}* application. +
 * Select the *Configuration* tab. +
 * Select `Session`. +
 * Set `Session Timeout (in minutes)` to `10` (or less). +

|Shell Command Access
|command injection
a|By default, some shell commands are disabled in order to secure the system.
${branding} includes a whitelist of allowed shell commands in
`${home_directory}/etc/org.apache.karaf.command.acl.shell.cfg`.

By default, this list includes commands that are whitelisted only to administrators:

* `complete`
* `echo`
* `format`
* `grep`
* `if`
* `keymap`
* `less`
* `set`
* `setopt`
* `sleep`
* `tac`
* `wc`
* `while`
* `.invoke`
* `unsetopt`

|===
