:title: Hardening Solr
:type: subConfiguration
:status: published
:parent: Configuring Solr
:summary: Hardening Solr.
:order: 02

== {title}

The following sections provide hardening guidance for Solr; however, they are to serve only as reference and other an additional security requirements may be added.

=== Hardening Solr Server Configuration

The Solr server configuration is configured to be secure by default. No additional
hardening should be necessary. The default configuration starts Solr with TLS enabled and
basic authentication required. That means ${branding} must trust Solr's PKI certificate.

=== Solr Server Password Management

By default, ${branding} is confifured to use Solr server. To verfiy this, view the property
<<{managing-prefix}solr_client,`solr.client`>>. If the property is set to `HttpSolrClient`,
${branding} is configured to use Solr server.

To ensure the security of its communication with Solr server, ${branding} sends HTTP requests
over TLS. Solr is configured to use basic authentication to further ensure the requests
originated from ${branding}. There are several system properties that control basic authentication
and password management.

* <<{managing-prefix}solr_usebasicauth, `solr.useBasicAuth`>>Send basic authentication header
if property is `true`
* <<{managing-prefix}solr_username,`solr.username`>>Username for basic authentication with Solr server.
* <<{managing-prefix}solr_password,`solr.password`>>Password for basic authentication.
* <<{managing-prefix}solr_autopassword,`solr.attemptAutoPasswordChange`>>
If this property is `true`, ${branding} attempts to change the default password to a randomly
gernated secure password if it detects the default password is in use.
The new password is encrypted and then stored in the system properties.

The Solr distrubition included with ${branding} comes already configured with a user. To see the
username or default password, either inspect the file
`${home_directory}/etc/customer.system.properties` or refer to the properities
<<{managing-prefix}managed_solr_properties,here>>.

A limitation of the current implementation is that the Solr password is not recoverable. Further,
the migration command does not currently migrate the password. It may
be necessary reset the password:
* After a migration
* If the administator needs access to the Solr admin UI.
* If the administator wants to use their own password.

==== Do not Autogenerate a Solr Password

. Edit the file ${home_directory}/etc/custom.system.properties`
. Change the value of `solr.password` to `autogenerated`.
. **To prevent ${branding} from attempting to change the password** set the property
`solr.attemptAutoPasswordChange` to `false`.

==== Change the Password to a Specific String

To change the password the Solr password to a specific string, send Solr and HTTP POST request.
This is covered in the official Solr documentation. Here is an example that uses the
command line utitily `curl` to change the password from `autogenerated` to `newpassword`:

 curl -k -u "ddf:autogenerated" "https://localhost:8994/solr/admin/authentication" -H 'Content-type:application/json' -d "{ 'set-user': {'ddf' : 'newpassword'}}"

==== Restore the Default Password

. Restore the `${home_directory}/solr/server/solr/security.json` from a zip file of the
${branding} distrubtion.

**OR**

. Edit the `${home_directory}/solr/server/solr/security.json` file. Solr stores a salted hash of
the user passwords in this file.
. is string.Assuming the Solr username is `ddf`, change the credentials section to match
this string:

```
 "credentials": {
      "ddf": "31u3dZLhFmlhsyYzlLxtUDoKR2j8oRnLwWcAH7Lbor4= F9eRJs+ZMI95YSQnBP/lGrLH8h60lKKizjMgC69J+WM="
    }
```

The quoted string following `ddf` is the salted hash for the password `autogenerated`.

=== Configuring Solr Encryption

While it is possible to encrypt the Solr index, it decreases performance significantly.
An encrypted Solr index also can only perform exact match queries, not relative or contextual queries.
As this drastically reduces the usefulness of the index, this configuration is not recommended.
The recommended approach is to encrypt the entire drive through the Operating System of the server
on which the index is located.
