:title: Hardening Solr
:type: subConfiguration
:status: published
:parent: Configuring Solr
:summary: Hardening Solr.
:order: 02

== {title}

The following sections provide hardening guidance for Solr; however,
they are to serve only as reference and other an additional security requirements may be added.

=== Changing Default Solr Server Password

The Solr server configuration included with the ${branding} uses
a default password that is insecure. To harden the Solr server,
the default password must be changed to a secure password.

. Complete the ${branding} installation process.
. ${branding} and the Solr server should be running.
. Choose a password that meets to your organization's requirements for secure passwords.
. Update the Sold server user's password to the new password you have chosen. Note that
changing the password will prevent ${branding} from communicating with Solr server
until the ${branding} configuration is updated in
subsequent steps.
  .. Use a utility like curl to send an HTTP request to the Solr server
  change the password.

  curl --insecure --user ddf:changeit http://localhost:8983/solr/admin/authentication
  -H 'Content-type:application/json'
  -d '{ "set-user": {"ddf" : "PASSWORD"}}'

. Use the ${command-console} to encrypt the password. This is necessary to protect
the password because the encrypted password is stored in a file.

 .. `${branding-lowercase}${at-symbol}local>encrypt PASSWORD`

. Copy the encrypted string. Include the `ENC(` and the closing parenthesis `)`.
For example, copy the string:

 ENC(AOROh0hmIfqJseeLzt30aCrAjzBvZRbLTv_pszuctKaaD4UHqDVoL-gDyQRaOE3FJdRmz3Oc5hTe)

. Change the Solr password in the `custom.system.properties` files.
Modify the property `solr.password`. For example:

  solr.password=ENC(AOROh0hmIfqJseeLzt30aCrAjzBvZRbLTv_pszuctKaaD4UHqDVoL-gDyQRaOE3FJdRmz3Oc5hTe)

. Save your changes to the `custom.system.properties` and restart ${branding}. After a restart,
${branding} should be communicating normally with Solr server.

==== Chan


=== Configuring Solr Encryption

While it is possible to encrypt the Solr index, it decreases performance significantly.
An encrypted Solr index also can only perform exact match queries, not relative or contextual queries.
As this drastically reduces the usefulness of the index, this configuration is not recommended.
The recommended approach is to encrypt the entire drive through the Operating System of the server
on which the index is located.
