:title: Connecting to an LDAP Server
:type: configuration
:status: published
:parent: Configuring User Access
:summary: Configurations to enable using an LDAP server.
:order: 03

== {title}

[WARNING]
====
The configurations for Security STS LDAP and Roles Claims Handler and Security STS LDAP Login contain plain text default passwords for the embedded LDAP, which is insecure to use in production.
====

Use the <<{integrating-prefix}encrypting_passwords,Encryption Service>>, from the ${command-console} to set passwords for your LDAP server.
Then change the LDAP Bind User Password in the <<{reference-prefix}Claims_Handler_Manager, Security STS LDAP and Roles Claims Handler>> configurations to use the encrypted password.

A claim is an additional piece of data about a principal that can be included in a token along with basic token data.
A claims manager provides hooks for a developer to plug in claims handlers to ensure that the STS includes the specified claims in the issued token.

Claims handlers convert incoming user credentials into a set of attribute claims that will be populated in the SAML assertion.
For example, the `LDAPClaimsHandler` takes in the user's credentials and retrieves the user's attributes from a backend LDAP server.
These attributes are then mapped and added to the SAML assertion being created.
Integrators and developers can add more claims handlers that can handle other types of external services that store user attributes.

See the <<{reference-prefix}Claims_Handler_Manager,Security STS LDAP and Roles Claims Handler>> for all possible configurations.
