:title: Reusing Configurations
:type: subConfiguration
:status: published
:parent: Multiple Installations
:summary: Export a current ${branding} configuration and use it to restore the system to the same state on a brand new installation.
:order: 00

== {title}

The Migration Export/Import capability allows administrators to export the current ${branding} configuration and use it to restore the same state for either a brand new installation or a second node for a Highly Available Cluster.

[IMPORTANT]
====
There are some key limitations when following this process to reuse configurations for a different versions of ${branding}. See <<{managing-prefix}reusing_configurations_across_different_versions, Reusing Configurations Across Different Versions>> below.
====

To export the current configuration settings:

. Run the command migration:export from the ${command-console}.
. Files named `${branding-lowercase}-${project.version}.dar`, `${branding-lowercase}-${project.version}.dar.key`, and `${branding-lowercase}-${project.version}.dar.sha256` will be created in the `exported` directory underneath `${home_directory}`.
The `.dar` file contains the encrypted information. The `.key` and `.sha256` files contains the encryption key and a validation checksum. Copy the '.dar' file to a secure location and copy the '.key' and '.sha256' to a different secure location.
Keeping all 3 files together represents a security risk and should be avoided.

To import previously exported configuration settings:

. Install ${branding} by unzipping its distribution.
. Restore all external files, softlinks, and directories that would not have been exported and for which warnings would have been generated during export. This could include (but is not limited to) external certificates or monitored directories.
. Launch the newly installed ${branding}.
. Make sure to install and re-enable the ${branding} <<{managing-prefix}managed_services,service>> on the new system if it was installed and enabled on the original system.
. Copy the previously exported files from your secure locations to the `exported` directory underneath `${home_directory}`.
. Either:
.. Step through the installation process.
.. Run the command migration:import from the ${command-console}.
. Or if an administrator wishes to restore the original profile along with the configuration (experimental):
.. Run the command migration:import with the option `--profile` from the ${command-console}.
. ${branding} will automatically restart if the command is successful. Otherwise address any generated warnings before manually restarting ${branding}.

It is possible to decrypt the previously exported configuration settings but doing so is insecure and appropriate measures should be taken to secure the resulting decrypted file.
To decrypt the exported file:

. Copy all 3 exported files (i.e. `.dar`, `.key`, and `.sha256`) to the `exported` directory underneath `${home_directory}`.
. Run the command migration:decrypt from the ${command-console}.
. A file named `${branding-lowercase}-${project.version}.zip` will be created in the `exported` directory underneath `${home_directory}`.
This file represents the decrypted version of the `.dar` file.

[IMPORTANT]
====
* The following is currently not supported when importing configuration files:
** importing from a system installed on a different OS
** importing from a system installed in a different directory location
* To keep the export/import process simple and consistent, all system configuration files are required to be under the `${home_directory}` directory and not be softlinks. Presence of external files or symbolic links during export will not fail the export; they will yield warnings. It will be up to the administrator to manually copy these files over to the new system before proceeding with the import. The import process will verify their presence and consistency and yield warnings if they don't match the original files.
* The import process will restore all configurations done on the original system as part of the <<{reference-prefix}hardening_checklist,hardening process>> including changes to starting scripts and certificates.
* The import process can also restore the profile from the original system by restoring all applications, features, and/or bundles to the same state (i.e., installed, uninstalled, started, stopped, ...) they were in originally. Doing so is currently experimental and was tested only with the standard and HA profiles.
====

=== Reusing Configurations Across Different Versions

The same step-by-step process above can be followed when migrating configurations between ${branding} instances of different versions, with a few key constraints:

* Only a subset of configuration files are currently imported:
** Files under `etc/ws-security`
** Files under `etc/pdp`
** `etc/users.attributes` and `etc/users.properties`
** `security/configurations.policy`
** `etc/custom.system.properties` (the `solr.password` property will be preserved)
** Keystores
** Truststores
** Service wrapper `*.conf` files, if the ${branding} is installed as a service
* There is a list of specific ${branding} versions that have been tested that can be found in `etc/migration.properties` under the property `supported.versions`, as a comma-delimited list. The system will only allow importing configurations from those versions.
