:title: Setting Internal Policies
:type: subConfiguration
:status: published
:parent: Configuring Catalog Filtering Policies
:summary: Setting Internal Policies.
:order: 00

== {title}

. Navigate to the *${admin-console}*.
. Select the *${ddf-security}* application.
. Click the *Configuration* tab.
. Click on the *Security AuthZ Realm* configuration.
. Add any attribute mappings necessary to map between subject attributes and the attributes to be asserted.
.. For example, the above example would require two Match All mappings of `subjectAttribute1=assertedAttribute1` and `subjectAttribute2=assertedAttribute2`
.. Match One mappings would contain `subjectAttribute3=assertedAttribute3` and `subjectAttribute4=assertedAttribute4`.

With the `security-pdp-authz` feature configured in this way, the above Metacard would be displayed to the user.
Note that this particular configuration would not require any XACML rules to be present.
All of the attributes can be matched internally and there is no reason to call out to the external XACML processing engine.
For more complex decisions, it might be necessary to write a XACML policy to handle certain attributes.
