:title: Configuring Solr Catalog Provider Synonyms
:type: subConfiguration
:status: published
:parent: Configuring Solr
:summary: Configuring solr catalog provider synonym matching
:order: 01

== {title}

When configured, text searches in Solr utilize synonyms when attempting to match text within the catalog.
Synonyms are used during keyword/anyText searches as well as when searching on specific text attributes when using the `like` / `contains` operator.
Text searches using the `equality` / `exact match` operator do not utilize synonyms.

Solr utilizes a `synonyms.txt` file which exists for each Solr core.
Synonym matching is most pertinent to metacards which are contained within 2 cores: `catalog` and `metacard_cache`.

=== Defining synonym rules in the Solr Provider

* Edit the `synonyms.txt` file under the `catalog` core.
For each synonym group you want to define, add a line with the synonyms separated by a comma.
For example:
[source]
----
United States, United States of America, the States, US, U.S., USA, U.S.A
----
* Save the file

* Repeat the above steps for the `metacard_cache` core.

* Restart the ${branding}.

[NOTE]
====
Data does not have to be re-indexed for the synonyms to take effect.
====
