:title: Configuring the ${catalog-search-ui} Upload Editor
:type: subConfiguration
:status: published
:parent: Configuring ${catalog-search-ui}
:order: 021
:summary: Configuring user ability to edit metadata of uploads in ${catalog-search-ui}.

== {title}

The upload editor in ${catalog-search-ui} allows users to specify attribute overrides which should be
applied on ingest. Administrators control the list of attributes that users may edit and can
mark certain attributes as required. They may also disable the editor if desired.

.Configure attribute list
. Navigate to the *${admin-console}*.
. Select the *${ddf-ui}* application.
. Select the *Configuration* tab.
. Select *Catalog UI Search*.
. Use the "Upload Editor: Attribute Configuration" field to configure the attributes shown in the
editor.
. Use the "Upload Editor: Required Attributes" field to mark attributes as required.
. Select *Save* to complete.

See <<{reference-prefix}org.codice.ddf.catalog.ui,Catalog UI Search Configurations>> for more information
regarding these configurations.


.Disabling
The editor only appears if it has attributes to show. If the upload editing capability is not
desired, simply remove all entries from the attribute configuration and the editor will be hidden.