:title: Configuring the Web Context Policy Manager
:type: configuration
:status: published
:parent: Configuring Security Policies
:summary: Configuring the Web Context Policy Manager.
:order: 00

== {title}

The Web Context Policy Manager defines all security policies for REST endpoints within ${branding}.
It defines:

* the type of authentication for web pages (such as /admin and /search) and endpoints (context paths that start with /services)
* any user attributes required for authorization
* a list of whitelisted contexts

See <<{reference-prefix}org.codice.ddf.security.policy.context.impl.PolicyManager, Web Context Policy Manager Configurations>> for detailed descriptions of all fields.

=== Guest Access
Guest access is a toggleable configuration.
Enabling guest access will cause all users to be assigned a guest principal for use throughout the entire system.
The guest principal will be used either by itself or along with any other principals acquired from configured authentication types.

=== Session Storage
Enabling session storage allows the system to persist the user login through the use of cookies.
Note that the `SAML` and `OIDC` authentication types require session storage to be enabled.

=== Authentication Types

Through the Web Context Policy Manager, authentication types for ${branding} may be configured with the following format:

----
<AUTH_TYPE>|<AUTH_TYPE|...
----

Authentication types can be configured separately for:
* web pages (these are all context paths that do not start with `/services` such as `/admin` and `/search`)
* endpoints (these are all context paths that start with `/services`)

Configuring separate authentication types for specific contexts is supported through the `web-context-policy-config.properties` configuration file.
* Navigate to `${home_directory}/etc/`
* Edit the `web-context-policy-config.properties` file
* Restart ${branding}

The `web-context-policy-config.properties` file format is:

----
/<CONTEXT>=<AUTH_TYPE> then <AUTH_TYPE then ...
----

[WARNING]
====
If the file-based configuration is used, the *authentication type* configuration for web pages and endpoints in the ${admin-console} is ignored.
All other configurations in the Web Context Policy Manager such as Guest Access, Required Attributes, and White Listed Contexts will *not* be ignored.
====

.Default Types of Authentication
[cols="1,4" options="header"]
|===

|Authentication Type
|Description

|`BASIC`
|Activates basic authentication.

|`PKI`
|Activates public key infrastructure authentication.

|`SAML`
|Activates single-sign on (SSO) across all REST endpoints that use SAML.

|`OIDC`
|Activates single-sign on (SSO) across all REST endpoints that use OIDC.

|===

==== Terminating and Non-Terminating Authentication Types
Terminating authentication types are authentication types where, once hit, must either allow or forbid access to the system.
No other authentication types will be checked once a terminating authentication type is hit.

Non-Terminating authentication types are authentication types where, once hit, must first verify that the client supports the authentication type's method of obtaining credentials.
If the client supports the non-terminating authentication type's method of obtaining credentials, it either allows or forbids access to the system.
However if the client does not support the non-terminating authentication type's method of obtaining credentials, the system will continue to the next configured authentication type.

`PKI` is the only non-terminating authentication type.
`BASIC`, `OIDC`, and `SAML` are terminating authentication types.

For example: assume ${branding} is protected by the terminating `SAML` authorization type.
The system first checks to see if the client supports the acquisition of SAML credentials.

- If the connecting client is a browser, the system can acquire SAML credentials.
- If the connecting client is a machine that supports SAML ECP, the system can acquire SAML credentials.
- If the connecting client is a machine that does not support SAML ECP, the system cannot acquire SAML credentials.

If the system can acquire SAML credentials from the client, the system will attempt to acquire said credentials and either allow or forbid access.
If the system cannot acquire SAML credentials from the client, the system will forbid access.

Otherwise, if ${branding} is protected by the non-terminating `PKI` authorization type and the system cannot acquire PKI certificates from the client, the system will continue to the next configured authentication type.

=== Required Attributes

The fields for required attributes allows configuring certain contexts to only be accessible to users with pre-defined attributes.
For example, the default required attribute for the `/admin` context is `role=system-admin`, limiting access to the ${admin-console} to system administrators

=== White Listed Contexts

White listed contexts are trusted contexts which will bypass security.
Any sub-contexts of a white listed context will be white listed as well, unless they are specifically assigned a policy.
