:title: Configuring the Web Context Policy Manager
:type: configuration
:status: published
:parent: Configuring Security Policies
:summary: Configuring the Web Context Policy Manager.
:order: 00

== {title}

The Web Context Policy Manager defines all security policies for REST endpoints within ${branding}.
It defines:

* the realms a context should authenticate against.
* the type of authentication that a context requires.
* any user attributes required for authorization.

See <<{reference-prefix}org.codice.ddf.security.policy.context.impl.PolicyManager, Web Context Policy Manager Configurations>> for detailed descriptions of all fields.

=== Authentication Types

As you add REST endpoints, you may need to add different types of authentication through the Web Context Policy Manager.

Any web context that allows or requires specific authentication types should be added here with the following format:

----
/<CONTEXT>=<AUTH_TYPE>|<AUTH_TYPE|...
----

.Default Types of Authentication
[cols="1,4" options="header"]
|===

|Authentication Type
|Description

|`saml`
|Activates single-sign on (SSO) across all REST endpoints that use SAML.

|`basic`
|Activates basic authentication.

|`PKI`
|Activates public key infrastructure authentication.

|`IdP`
|Activates SAML Web SSO authentication support. Additional configuration is necessary.

|`guest`
|provides guest access

|===

=== Required Attributes

The fields for required attributes allows configuring certain contexts to only be accessible to users with pre-defined attributes.
For example, the default required attribute for the `/admin` context is `role=system-admin`, limiting access to the ${admin-console} to system administrators

=== White Listed Contexts

White listed contexts are trusted contexts which will bypass security.
Any sub-contexts of a white listed context will be white listed as well, unless they are specifically assigned a policy.
