:title: Federated Source for Atlassian Confluence(R)
:type: source
:status: published
:link: _federated_source_for_atlassian_Confluence
:summary: Retrieve pages, comments, and attachments from an Atlassian Confluence(R) REST API.
:federated: x
:connected:
:catalogprovider:
:storageprovider:
:catalogstore:

The Confluence source provides a Federated Source to retrieve pages, comments, and attachments from an Atlassian Confluence(R) REST API and turns the results into Metacards the system can use.
The Confluence source does provide a Connected Source interface but its functionality has not been verified.

Confluence Source has been tested against the following versions of Confluence with REST API v2

* Confluence 1000.444.5 (Cloud)
* Confluence 5.10.6 (Server)
* Confluence 5.10.7 (Server)

===== Installing the Confluence Federated Source

The Confluence Federated Source is installed by default with a standard installation in the ${ddf-catalog} application.

Add a New Confluence Federated Source through the ${admin-console}:

. Navigate to the *${admin-console}*.
. Select the *${ddf-catalog}* application.
. Select the *Sources* tab.
. Add a New source.
. Name the New source.
. Select *Confluence Federated Source* from *Binding Configurations*.

===== Configuring the Confluence Federated Source

Configure an Existing Confluence Federated Source through the ${admin-console}:

. Navigate to the *${admin-console}*.
. Select the *${ddf-catalog}* application.
. Select the *Sources* tab.
. Select the name of the source to edit.

See <<Confluence_Federated_Source, Confluence Federated Source configurations>> for all possible configurations.

===== Usage Limitations of the Confluence Federated Source

Most of the fields that can be queried on Confluence have some sort of restriction on them. Most of the fields do not support the `like` aka `~` operation so the source will convert `like` queries to `equal` queries for attributes that don't support `like`. If the source receives a query with attributes it doesn't understand, it will just ignore them. If the query doesn't contain any attributes that map to Confluence search attributes, an empty result set will be returned.

Depending on your version of Confluence, when downloading attachments you might get redirected to a different download URL. If this happens the default URLResourceReader configuration does not allow redirects and will fail the download. This can be fixed by enabling redirects in the `URLResourceReader` <<_configuring_the_url_resource_reader,configuration>>.
