:title: CSW Federation Profile Source
:type: source
:status: published
:link: _csw_federation_profile_source
:summary: Queries a CSW version 2.0.2 compliant service.
:federated: x
:connected:
:catalogprovider:
:storageprovider:
:catalogstore:


The CSW Federation Profile Source supports the ability to search collections of descriptive information (metadata) for data, services, and related information objects.

Use the CSW source if querying a CSW version 2.0.2 compliant service.

===== Installing the CSW Federation Profile Source

The CSW Federation Profile Source is installed by default with a standard installation in the ${ddf-spatial} application.

Configure the CSW Federation Profile Source through the ${admin-console}:

* Navigate to the *${admin-console}*.
* Select the *${ddf-catalog}* application.
* Add a New source.
* Name the New source.
* Select *CSW Specification Profile Federated Source* from *Binding Configurations*.

===== Configuring the CSW Federation Profile Source

Configure an Existing CSW Federated Source through the ${admin-console}:

* Navigate to the *${admin-console}*.
* Select the *${ddf-catalog}* application.
* Select the *Sources* tab.
* Select the name of the source to edit.

See <<Csw_Federation_Profile_Source,CSW Federation Profile Source configurations>> for all possible configurations.

===== Usage Limitations of the CSW Federation Profile Source

* The CSW Federation Profile Source does not support text path searches.
* Nearest neighbor spatial searches are not supported.
