:title: OpenSearch Source
:type: source
:status: published
:link: _opensearch_source
:summary: Performs OpenSearch queries for metadata.
:federated: x
:connected:
:catalogprovider:
:storageprovider:
:catalogstore:

== {title}

The OpenSearch source provides a <<_federated_source,Federated Source>> that has the capability to do http://www.opensearch.org/Home[OpenSearch] queries for metadata from Content Discovery and Retrieval (CDR) Search V1.1 compliant sources.
The OpenSearch source does not provide a <<_connected_source,Connected Source>> interface.

.Installing an OpenSearch Source
The OpenSearch Source is installed by default with a standard installation in the ${ddf-catalog} application.

Configure a new OpenSearch Source through the ${admin-console}:

* Navigate to the *${admin-console}*.
* Select the *${ddf-catalog}* application.
* Select the *Sources* tab.
* Add a New source.
* Name the New source.
* Select *OpenSearch Source* from *Binding Configurations*.

.Configuring an OpenSearch Source
Configure an existing OpenSearch Source through the ${admin-console}:

* Navigate to the *${admin-console}*.
* Select the *${ddf-catalog}* application.
* Select the *Sources* tab.
* Select the name of the source to edit.

See <<OpenSearchSource,OpenSearch Source configurations>> for all possible configurations.

.Using OpenSearch Source
Use the OpenSearch source if querying a CDR-compliant search service is desired.

.Query to OpenSearch Parameter Mapping
[cols="1,1m,2" options="header"]
|===
|Element
|OpenSearch HTTP Parameter
|${branding} Data Location

|searchTerms
|q
|Pulled from the query and encoded in UTF-8.

|routeTo
|src
|Pulled from the query.

|maxResults
|mr
|Pulled from the query.

|count
|count
|Pulled from the query.

|startIndex
|start
|Pulled from the query.

|maxTimeout
|mt
|Pulled from the query.

|userDN
|dn
|${branding} subject

|lat
|lat
.3+|Pulled from the query if it is a point-radius query.

|lon
|lon

|radius
|radius

|box
|bbox
|Pulled from the query if it is a bounding-box query. +
 +
Or else, calculated from the query if it is a polygon query and the <<shouldConvertToBBox,`shouldConvertToBBox`>> configuration option is `true`.
NOTE: Converting a polygon that crosses the antimeridian to a bounding box will produce an incorrect bounding box. +
//TODO DDF-3742
 +
Or else, calculated from query if it is a point-radius query and the <<shouldConvertToBBox,`shouldConvertToBBox`>> configuration option is `true`.

|polygon
|polygon
|Pulled from the ${branding} query.

|start
|dtstart
|Pulled from the query.

|end
|dtend
|Pulled from the query.

|filter
|filter
|Pulled from the query.

|sort
|sort
|Calculated from the query.
Format: `relevance` or `date`.
Supports `asc` and `desc` using `:` as delimiter.

|===

.Usage Limitations of the OpenSearch Source
The OpenSearch source does not provide a <<_connected_source,Connected Source>> interface.
