:title: Solr Catalog Provider
:type: source
:status: published
:link: _solr_catalog_provider
:summary: Uses Solr as a catalog.
:federated:
:connected:
:catalogprovider: x
:storageprovider:
:catalogstore:

== {title}

The Solr Catalog Provider is included with a standard installation of ${branding}.
The following are the three ways to configure the Solr Catalog Provider:

<<_http_solr,HTTP Solr>> (default):: Used with an external (HTTP) Solr server.

Embedded Solr:: Used with an embedded Solr server with no HTTP interface.

<<_solr_cloud,Solr Cloud>>:: Used with a cluster of Solr servers.

If not using Solr Cloud, whenever the {branding} Solr ingests data, it creates an index for it in the data directory.
This data indexing enables the data to be searchable by the {branding} Solr. The data in the data directory can then be persisted by performing a `commit` on the {branding} Solr.
When the {branding} Solr is restarted, it reloads the data to get back the index.

.[[_http_solr]]HTTP Solr
The HTTP Solr is an external Apache Solr server instance.
There are two possible installations for the HTTP Solr configuration:

Internal (default):: Points to an Apache Solr server that runs in the same container as {branding}.
External:: Points to an Apache Solr server in a different container or on a different system.

.HTTP Solr Internal Deployment
[ditaa,http-solr-internal-diagram,png]
....
 Container (JVM)
 +=----------------+
 |                 |
 | /-----\         |
 | |cDEF |         |
 | | DDF +--\      |
 | |     |  |http  |
 | \-----/  |      |
 |          |      |
 |          v      |
 |      +--------+ |
 |      |SolrcFF0| |
 |      +--------+ |
 |                 |
 +-----------------+
....

.HTTP Solr External Deployment
[ditaa,http-solr-external-diagram,png]
....
 Container (JVM)
 +=----------------+
 |                 |
 | /-----\         |
 | |cDEF |         |  +--------+
 | | DDF +----------->|SolrcFF0|
 | |     |   http  |  +--------+
 | \-----/         |
 |                 |
 +-----------------+
....

.When to Use HTTP Solr
The HTTP Solr configuration is good for most use cases. See below for details.

.HTTP Solr Tradeoffs
* Solr Admin UI can be used.
* Backup can be performed manually or using the Backup command.
* External installation allows isolation of data storage.
* Requires additional protection to be secured.
* Not scalable.
* External installation has network overhead

.Installing HTTP Solr

By default, the ${ddf-solr} application installs a Solr server inside the same container as {branding}.
To install an External Solr server, refer to https://cwiki.apache.org/confluence/display/solr/Apache+Solr+Reference+Guide[Apache Solr Reference Guide].

.Configuring HTTP Solr

. Edit the `${home_directory}/etc/system.properties`
.. Comment out the Solr Client Configuration for *Cloud Solr Client* and *Embedded Solr Client* sections.
.. Uncomment the section for the *Http Solr Client*.

[NOTE]
====
To point to an External Solr server instead of the default Internal one, put the url in `solr.http.url` (see below for example).
Also, two jar files need to be added to the Solr installation as described in <<Installing Solr Cloud,Installing Solr Cloud>>.
====

.system.properties
----

solr.client = HttpSolrClient
solr.http.url = https://solr-host-name:8993/solr
solr.data.dir = ${karaf.home}/data/solr

----

.[[_http_solr]]Embedded Solr
The Embedded Solr is an embedded, local Apache Solr server instance.
It is a local instance that is a lightweight Catalog Provider solution.
However, it does not provide a Solr Admin UI or a REST-like HTTP/XML and JSON API.
If that is necessary, see <<HTTP Solr,HTTP Solr>> or <<Solr Cloud,Solr Cloud>>.

.Embedded Solr Deployment
[ditaa,embedded-solr-diagram,png]
....
 Container (JVM)
 +=-----------------+
 |                  |
 | /--------------\ |
 | |cDEF          | |
 | | DDF          | |
 | |              | |
 | |  +---------+ | |
 | |  |Solr cFF0| | |
 | |  +---------+ | |
 | |              | |
 | \--------------/ |
 |                  |
 |                  |
 +------------------+
....

.When to Use the Embedded Solr
The Embedded Solr configuration is great for demonstrations, training exercises, or for sparse querying and ingesting. See below for details.

.Embedded Solr Tradeoffs
* Requires no installation and very little configuration.
* No HTTP connection required. As a result, there is no network overhead.
* Not scalable.
* There is no Solr Admin UI.
* Backup must be performed manually.

.Installing Embedded Solr

No installation required. Follow the Configuring section below and restart the {branding}.

.Configuring Embedded Solr
. Edit the `${home_directory}/etc/system.properties`

.. Comment out the Solr Client Configuration for *Cloud Solr Client* and *Http Solr Client* sections.
.. Uncomment the section for the *Embedded Solr Client*:

.system.properties
----
solr.client = EmbeddedSolrServer
solr.data.dir = ${karaf.home}/data/solr
----

.[[_solr_cloud]]Solr Cloud
Solr Cloud is a cluster of Solr Server instances that are fault tolerant and highly available.
Each Solr Server instance in Solr Cloud provides a Solr Admin UI.

Configuration shared between Solr Server instances is managed by Zookeeper.
Zookeeper helps manage the overall structure.

.Solr Cloud Deployment
[ditaa,solrcloud-diagram,png]
....
  Container(JVM)         Solr Cloud
 +=-----------------+   +=--------------------+
 |                  |   |                     |
 | /-----------\    |   | +---------+         |
 | |cDEF       |    |   | |Solr cFF0|         |
 | | DDF       |    |   | +---------+         |
 | |           |    |   |                     |
 | |           |  http  |         +---------+ |
 | |           +------->|         |Solr cFF0| |
 | |           |    |   |         +---------+ |
 | |           |    |   |                     |
 | |           |    |   | +---------+         |
 | |           |    |   | |Solr cFF0|         |
 | \-----------/    |   | +---------+         |
 |                  |   |                     |
 +------------------+   +---------------------+
....

[NOTE]
====
Solr Cloud is currently in Beta version.
Bugs and feature changes may affect the final release.
====

.When to Use Solr Cloud
If the ${branding} needs to be accessible for a higher than normal period with low downtime, then Solr Cloud should be used. See below for details.

.Solr Cloud Tradeoffs
* Scalable. Can exceed ~2 billion indexed documents.
* Solr Admin UI can be used.
* Has network overhead and requires additional protection to be secure.
* Installation is more involved (requires Zookeeper)
* Configuration and administration is more complex due to replicate, sharding, etc.
* No way to backup currently, but will automatically recover from system failure.

[NOTE]
====
The instructions on setting up Solr Cloud for ${branding} only include setup in a *NIX environment.
====

.Solr Cloud Prerequisites
Before Solr Cloud can be installed:

* ZooKeeper 3.4.5 (Refer to https://zookeeper.apache.org/doc/r3.1.2/zookeeperStarted.html#sc_Download for installation instructions.)
* *NIX environment
* JDK 8 or greater

[NOTE]
====
A minimum of three Zookeeper nodes required.
Three Zookeeper nodes are needed to form a quorum.
A three Zookeeper ensemble allows for a single server to fail and the service will still be available.
More Zookeeper nodes can be added to achieve greater fault tolerance. The total number of nodes must always be an odd number.
See https://lucene.apache.org/solr/guide/6_6/setting-up-an-external-zookeeper-ensemble.html#SettingUpanExternalZooKeeperEnsemble-SettingupaZooKeeperEnsemble[
Setting Up an External Zoo Keeper Ensemble] for more information.
====

.Installing Solr Cloud

Before starting the install procedure, download the extension jars. The jars are needed to support
geospatial and xpath queries and need to be installed on every Solr server instance after the Solr
Cloud installation instructions have been followed.

The jars can be found here:

.. http://artifacts.codice.org/service/local/repositories/releases/content/org/codice/thirdparty/jts/1.12_1/jts-1.12_1.jar
.. http://artifacts.codice.org/service/local/artifact/maven/content?r=public&g=ddf.platform.solr&a=solr-xpath&v=${ddf.version}

Repeat the following procedure for each Solr server instance that will be part of the Solr Cloud cluster:

. Refer to https://cwiki.apache.org/confluence/display/solr/Apache+Solr+Reference+Guide for installation instructions.
. Copy downloaded jar files to: `<SOLR_INSTALL_DIR>/server/solr-webapp/webapp/WEB-INF/lib/`

[NOTE]
====
A minimum of two Solr server instances is required. Each Solr server instance must have a minimum of two shards.
Having two Solr server instances guarantees that at least one Solr server is available if one fails.
The two shards enables the document mapping to be restored if one shard becomes unavailable.
====

.Configuring Solr Cloud
. On the ${branding} server, edit `${home_directory}/etc/system.properties`:
.. Comment out the Solr Client Configuration for *Http Solr Client* and *Embedded Solr Client* sections.
.. Uncomment the section for the *Cloud Solr Client*:
.. Set `solr.cloud.zookeeper` to `<ZOOKEEPER_1_HOSTNAME>:<PORT_NUMBER>`, `<ZOOKEEPER_2_HOSTNAME>:<PORT_NUMBER>`, `<ZOOKEEPER_n_HOSTNAME>:<PORT_NUMBER>`
.. Set `solr.data.dir` to the desired data directory.

.system.properties
----
solr.client = CloudSolrClient
solr.data.dir = ${karaf.home}/data/solr
solr.cloud.zookeeper = zk1:2181,zk2:2181,zk3:2181
----
