:title: WFS Services
:type: developingComponent
:status: published
:link: {developing-prefix}wfs_services
:order: 31
:summary: Using WFS Services

The Web Feature Service (WFS) is an http://www.opengeospatial.org/[Open Geospatial Consortium (OGC)] Specification.
${branding} supports the ability to integrate WFS 1.0 and WFS 2.0 Web Services.

[NOTE]
====
${branding} does not include a supported WFS Web Service (Endpoint) implementation.
Therefore, federation for 2 ${branding} instances is not possible via WFS.
====

.WFS Features
When a query is issued to a WFS server, the output of the query is an XML document that contains a collection of feature member elements.
Each WFS server can have one or more feature types with each type being defined by a schema that extends the WFS `featureMember` schema.
The schema for each type can be discovered by issuing a `DescribeFeatureType` request to the WFS server for the feature type in question.
The WFS source handles WFS capability discovery and requests for feature type description when an instance of the WFS source is configured and created.

See the <<{managing-prefix}wfs_1_0_source,WFS v1.0.0 Source>> or <<{managing-prefix}wfs_2_0_source,WFS v2.0.0 Source>> for more information about how to configure a WFS source.

.Converting a WFS Feature
In order to expose WFS features to ${branding} clients, the WFS feature must be converted into the common data format of the ${branding}, a metacard.
The OGC package contains a `GenericFeatureConverter` that attempts to populate mandatory metacard fields with properties from the WFS feature XML.
All properties will be mapped directly to new attributes in the metacard.
However, the `GenericFeatureConverter` may not be able to populate the default metacard fields with properties from the feature XML.

.Creating a Custom Converter
To more accurately map WFS feature properties to fields in the metacard, a custom converter can be created.
The OGC package contains an interface, `FeatureConverter`, which extends the http://xstream.codehaus.org/javadoc/com/thoughtworks/xstream/converters/Converter.htmlConverter[] interface provided by the http://xstream.codehaus.org/[XStream] project.
XStream is an open source API for serializing XML into Java objects and vice-versa.
Additionally, a base class, `AbstractFeatureConverter`, has been created to handle the mapping of many fields to reduce code duplication in the custom converter classes.

. Create the `CustomConverter` class extending the `ogc.catalog.common.converter.AbstractFeatureConverter` class.
+
[source,java]
----
public class CustomConverter extends ogc.catalog.common.converter.AbstractFeatureConverter
----
+
. Implement the `FeatureConverterFactory` interface and the `createConverter()` method for the `CustomConverter`.
+
[source,java,linenums]
----
public class CustomConverterFactory implements FeatureConverterFactory {
    private final featureType;
    public CustomConverterFactory(String featureType) {
        this.featureType = featureType;
    }
    public FeatureConverter createConverter() {
        return new CustomConverter();
    }
    public String getFeatureType() {
        return featureType;
    }
}
----
+
. Implement the `unmarshal` method required by the `FeatureConverter` interface. The `createMetacardFromFeature(reader, metacardType)` method implemented in the `AbstractFeatureConverter` is recommended. +
+
[source,java,linenums]
----
public Metacard unmarshal(HierarchicalStreamReader reader, UnmarshallingContext ctx) {
  MetacardImpl mc = createMetacardFromFeature(reader, metacardType);
  //set your feature specific fields on the metacard object here
  //
  //if you want to map a property called "beginningDate" to the Metacard.createdDate field
  //you would do:
  mc.setCreatedDate(mc.getAttribute("beginningDate").getValue());
}
----
+
. Export the `ConverterFactory` to the OSGi registry by creating a `blueprint.xml` file for its bundle. The bean id and argument value must match the WFS Feature type being converted.
+
[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<blueprint xmlns="http://www.osgi.org/xmlns/blueprint/v1.0.0" xmlns:cm="http://aries.apache.org/blueprint/xmlns/blueprint-cm/v1.1.0">
  <bean id="custom_type" class="com.example.converter.factory.CustomConverterFactory">
    <argument value="custom_type"/>
  </bean>
  <service ref="custom_type" interface="ogc.catalog.common.converter.factory.FeatureConverterFactory"/>
</blueprint>
----
