:title: WFS 2.0 Source
:type: source
:status: published
:link: _wfs_2_0_source
:summary: Allows for requests for geographical features across the web.
:federated: x
:connected: x
:catalogprovider:
:storageprovider:
:catalogstore:

== {title}
The WFS 2.0 Source allows for requests for geographical features across the web using platform-independent calls.

Use the WFS Source if querying a WFS version 2.0.0 compliant service. Also see <<_working_with_wfs_sources,Working with WFS Sources>>.

.Installing the WFS v2.0.0 Source
The WFS v2.0.0 Source is installed by default with a standard installation in the ${ddf-spatial} application.

Configure a new WFS v2.0.0 Source through the ${admin-console}:

* Navigate to the *${admin-console}*.
* Select the *${ddf-catalog}* application.
* Select the *Sources* tab.
* Add a New source.
* Name the New source.
* Select *WFS v2.0.0 Source* from *Binding Configurations*.

.Configuring the WFS v2.0.0 Source
Configure an existing WFS v2.0.0 Source through the ${admin-console}:

* Navigate to the *${admin-console}*.
* Select the *${ddf-catalog}* application.
* Select the *Sources* tab.
* Select the name of the source to edit.

See <<Wfs_v2_0_0_Federated_Source,WFS v.2.0 Federated source configurations>> or <<Wfs_v2_0_0_Connected_Source,WFS v2.0 Connected source configurations>> for all possible configurations.

.WFS URL
The WFS URL must match the endpoint for the service being used.
The type of service and version is added automatically, so they do not need to be included.
Some servers will throw an exception if they are included twice, so do not include those.

The syntax depends on the server.
However, in most cases, the syntax will be everything before the `?` character in the URL that corresponds to the `GetCapabilities` query.

.Example GeoServer 2.5 Syntax
----
http://www.example.org:8080/geoserver/ows?service=wfs&version=2.0.0&request=GetCapabilities
----

In this case, the WFS URL would be
----
http://www.example.org:8080/geoserver/ows
----

.Mapping WFS Feature Properties to Metacard Attributes

The WFS 2.0 Source allows for virtually any schema to be used to describe a feature.
A feature is relatively equivalent to a metacard. The `MetacardMapper` was added to allow an administrator to configure which feature properties map to which metacard attributes.

.Using the WFS `MetacardMapper`
Use the WFS `MetacardMapper` to configure which feature properties map to which metacard attributes when querying a WFS version 2.0.0 compliant service.
When feature collection responses are returned from WFS sources, the metacard mapper places the feature properties into metacard attributes, which are then presented to the user via ${branding}.
Rules for determining the values of each attribute are defined along with each mapping.
The mapper will omit attributes or features that don't have a mapping defined.

.Installing the WFS `MetacardMapper`
The WFS `MetacardMapper` is not installed by default with a standard application in the ${ddf-spatial} application.

.Configuring the WFS `MetacardMapper`
The `MetacardMapper` is configurable through the ${admin-console}. Mappings are added using a JSON formatted string.

.Example WFS MetacardMapper Configuration
The following shows how to configure the `MetacardMapper` to be used with the sample data provided with GeoServer.
This configuration shows a custom mapping for the feature type ‘states’.
For the given type, we are taking the feature property ‘STATE_NAME’ and mapping it to the metacard attribute ‘title’.
In this particular case, since we mapped the state name to title in the metacard, it will now be fully searchable.
The 'template' field value is a Handlebars template that is used to determine the value for the metacard attribute. So
the value of a given attribute is the result of applying the template to the feature values in the WFS response. The
template may contain references to any mapped feature.

.Example `MetacardMapper` Attribute Mapping:
[source,json,linenums]
----
{"attributeName": "title",
 "featureName": "STATE_NAME",
 "template": "{{STATE_NAME}}"}

{"attributeName": "modified",
 "featureName": "updated",
 "template": "{{dateFormat updated format=\"yyyy-MM-dd\"}}"}
----



