==== Subscriptions

Subscriptions represent "standing queries" in the Catalog.
Like a query, subscriptions are based on the OGC Filter specification.

===== Subscription Lifecycle

====== Creation

* Subscriptions are created directly with the <<_event_processor,Event Processor>> or declaratively through use of the Whiteboard Design Pattern.
* The Event Processor will invoke each Pre-Subscription Plugin and, if the subscription is not rejected, the subscription will be activated.

====== Evaluation

* When a metacard matching the subscription is created, updated, or deleted in any Source, each Pre-Delivery Plugin will be invoked.

* If the delivery is not rejected, the associated Delivery Method callback will be invoked.

====== Update Evaluation

Notably, the Catalog allows event evaluation on both the previous value (if available) and new value of a Metacard when an update occurs.

====== Durability

Subscription durability is not provided by the Event Processor.
Thus, all subscriptions are transient and will not be recreated in the event of a system restart.
It is the responsibility of Endpoints using subscriptions to persist and re-establish the subscription on startup.
This decision was made for the sake of simplicity, flexibility, and the inability of the Event Processor to recreate a fully-configured Delivery Method without being overly restrictive.

[IMPORTANT]
====
*Subscriptions are not persisted by the Catalog itself.* +
Subscriptions must be explicitly persisted by an endpoint and are not persisted by the Catalog.
The Catalog Framework, or more specifically the Event Processor itself, does not persist subscriptions.
Certain endpoints, however, can persist the subscriptions on their own and recreate them on system startup.
====

==== Creating a Subscription

Currently, the Catalog reference implementation does not contain a subscription endpoint.
Nevertheless, an endpoint that exposes a web service interface to create, update, and delete subscriptions would provide a client's subscription's filtering criteria to be used by Catalog's Event Processor to determine which create, update, and delete events are of interest to the client.
The endpoint client also provides the callback URL of the event consumer to be called when an event matching the subscription's criteria is found.
This callback to the event consumer is made by a Delivery Method implementation that the client provides when the subscription is created. 
Whenever an event occurs in the Catalog matching the subscription, the Delivery Method implementation will be called by the Event Processor. 
The Delivery Method will, in turn, send the event notification out to the event consumer. 
As part of the subscription creation process, the Catalog verifies that the event consumer at the specified callback URL is available to receive callbacks.
Therefore, the client must ensure the event consumer is running prior to creating the subscription.
The Catalog completes the subscription creation by executing any pre-subscription Catalog Plugins, and then registering the subscription with the OSGi Service Registry.
The Catalog does not persist subscriptions by default.

===== Delivery Method

A Delivery Method provides the operation (created, updated, deleted) for how an event's metacard can be delivered.

A Delivery Method is associated with a subscription and contains the callback URL of the event consumer to be notified of events.
The Delivery Method encapsulates the operations to be invoked by the Event Processor when an event matches the criteria for the subscription.
The Delivery Method's operations are responsible for invoking the corresponding operations on the event consumer associated with the callback URL.
