
==== Guest Interceptor

The goal of the `GuestInterceptor` is to allow non-secure clients (SOAP requests without security headers) to access secure service endpoints. 

All requests to secure endpoints must include, as part of the incoming message, a user's credentials in the form of a SAML assertion or a reference to a SAML assertion.
For REST/HTTP requests, either the assertion itself or the session reference (that contains the assertion) is included.
For SOAP requests, the assertion is included in the SOAP header. 

Rather than reject requests without user credentials, the guest interceptor
detects the missing credentials and inserts an assertion that represents the "guest" user.
The attributes included in this guest user assertion are configured by the administrator to represent any unknown user on the current network.

===== Installing Guest Interceptor

The `GuestInterceptor` is installed by default with ${ddf-security} Application.

===== Configuring Guest Interceptor

. Navigate to the ${admin-console} at ${secure_url}/admin
. Click the ${ddf-security} application tile
. Click the *Configuration* tab
. Click the *Security STS Guest Claims Handler* configuration
. Click the + next to Attributes to add a new attribute
. Add any addtional attributes that you want every user to have
. Click *Save changes*

Once these configurations have been added, the GuestInterceptor is ready for use.
Both secure and non-secure requests will be accepted by all secure ${branding} service endpoints.
