==== Security STS LDAP Claims Handler

The ${ddf-security} STS LDAP Claims Handler bundle adds functionality to the STS server that allows it to retrieve claims from an LDAP server.
It also adds mappings for the LDAP attributes to the STS SAML claims.

[NOTE]
====
All claims handlers are queried for user attributes regardless of realm.
This means that two different users with the same username in different LDAP servers will end up with both of their claims in each of their individual assertions.
====

===== Installing Security STS LDAP Claims Handler

This bundle is not installed by default and can be added by installing the
`security-sts-ldapclaimshandler`
 feature.

===== Configuring the Security STS LDAP Claims Handler

Configure the Security STS LDAP Claims Handler from the ${admin-console}:

. Navigate to the ${admin-console}.
. Select *${ddf-security} Application*
. Select *Configuration* tab.
. Select *Security STS LDAP and Roles Claims Handler*.


include::{adoc-include}/_tables/Claims_Handler_Manager-table-contents.adoc[]
