
The ${branding} Security Framework utilizes http://shiro.apache.org/[Apache Shiro] as the underlying security framework.
The classes mentioned in this section will have their full package name listed, to make it easy to tell which classes come with the core Shiro framework and which are added by ${branding}.

=== Subject

`${ddf-branding-lowercase}.security.Subject <extends> org.apache.shiro.subject.Subject`

The Subject is the key object in the security framework.
Most of the workflow and implementations revolve around creating and using a Subject.
The Subject object in ${branding} is a class that encapsulates all information about the user performing the current operation.
The Subject can also be used to perform permission checks to see if the calling user has acceptable permission to perform a certain action (e.g., calling a service or returning a metacard).
This class was made ${branding}-specific because the Shiro interface cannot be added to the Query Request property map.

.Implementations of Subject:
[cols="2" options="header"]
|===

|Classname
|Description

|${ddf-branding-lowercase}.security.impl.SubjectImpl
|Extends `org.apache.shiro.subject.support.DelegatingSubject`

|===

==== Security Manager

`${ddf-branding-lowercase}.security.service.SecurityManager`

The Security Manager is a service that handles the creation of Subject objects.
A proxy to this service should be obtained by an endpoint to create a Subject and add it to the outgoing `QueryRequest`.
The Shiro framework relies on creating the subject by obtaining it from the current thread.
Due to the multi-threaded and stateless nature of the ${branding} framework, utilizing the Security Manager interface makes retrieving Subjects easier and safer.

.Implementations of Security Managers:
[cols="1m,1" options="header"]
|===

|Classname
|Description

|${ddf-branding-lowercase}.security.service.SecurityManagerImpl
|This implementation of the Security Manager handles taking in both `org.apache.shiro.authc`.
AuthenticationToken and `org.apache.cxf.ws.security.tokenstore.SecurityToken` objects.

|===

==== Authentication Tokens

`org.apache.shiro.authc.AuthenticationToken`

Authentication Tokens are used to verify authentication of a user when creating a subject.
A common use-case is when a user is logging directly in to the ${branding} framework.

[cols="1m,2" options="header"]
|===

|Classname
|Description

|${ddf-branding-lowercase}.security.service.impl.cas.CasAuthenticationToken
|This Authentication Token is used for authenticating a user that has logged in with CAS.
It takes in a proxy ticket which can be validated on the CAS server.

|===

==== Realms

${branding} uses Realms for Authentication and Authorization.

===== Authenticating Realms

`org.apache.shiro.realm.AuthenticatingRealm`

Authenticating Realms are used to authenticate an incoming authentication token and create a Subject on successful authentication.

.Implementations of Authenticating Realms in ${branding}:
[cols="1m,2" options="header"]
|===

|Classname
|Description

|${ddf-branding-lowercase}.security.realm.sts.StsRealm
|This realm delegates authentication to the Secure Token Service (STS). It creates a `RequestSecurityToken` message from the incoming Authentication Token and converts a successful STS response into a Subject.

|===

===== Authorizing Realms

`org.apache.shiro.realm.AuthorizingRealm`

Authorizing Realms are used to perform authorization on the current Subject.
These are used when performing both Service AuthZ and Filtering.
They are passed in the `AuthorizationInfo` of the Subject along with the Permissions of the object wanting to be accessed. The response from these realms is a true (if the Subject has permission to access) or false (if the Subject does not).

.Other implementations of the Security API within ${branding}
[cols="1m,2" options="header"]
|===

|Classname
|Description

|org.codice.${ddf-branding-lowercase}.platform.filter.delegate.DelegateServletFilter
|The `DelegateServletFilter` detects any servlet filters that have been exposed as OSGi services implementing `org.codice.ddf.platform.filter.SecurityFilter` and places them in-order in front of any servlet or web application running on the container.

|org.codice.${ddf-branding-lowercase}.security.filter.websso.WebSSOFilter
|This filter serves as the main security filter that works in conjunction with a number of handlers to protect a variety of contexts, each using different authentication schemes and policies.

|org.codice.${ddf-branding-lowercase}.security.handler.saml.SAMLAssertionHandler
|This handler is executed by the WebSSOFilter for any contexts configured to use it.
This handler should always come first when configured in the Web Context Policy Manager, as it provides a caching capability to web contexts that use it.
The handler will first check for the existence of an HTTP Authorization header of type SAML, whose value is a Base64 + deflate SAML assertion.
If that is not found, then the handler will check for the existence of the deprecated `org.codice.websso.saml.token` cookie with the same value.
Failing that, it will check for a JSESSIONID cookie to use as a reference to a cached assertion.
If the JSESSIONID is valid, the `SecurityToken` will be retrieved from the cache.

|org.codice.${ddf-branding-lowercase}.security.handler.basic.BasicAuthenticationHandler
|Checks for basic authentication credentials in the http request header.
If they exist, they are retrieved and passed to the `LoginFilter` for exchange.

|org.codice.${ddf-branding-lowercase}.security.handler.pki.PKIHandler
|Handler for PKI based authentication.
X509 chain will be extracted from the HTTP request and converted to a `BinarySecurityToken`.

|org.codice.${ddf-branding-lowercase}.security.handler.guest.GuestHandler
|Handler that allows guest user access via a guest user account.
The guest account credentials are configured via the org.codice.${ddf-branding-lowercase}.security.claims.guest.GuestClaimsHandler.
The `GuestHandler` also checks for the existence of basic auth credentials or PKI credentials that might be able to override the use of the guest user.

|org.codice.${ddf-branding-lowercase}.security.filter.login.LoginFilter
|This filter runs immediately after the WebSSOFilter and exchanges any authentication information found in the request with a Subject via Shiro.

|org.codice.${ddf-branding-lowercase}.security.filter.authorization.AuthorizationFilter
|This filter runs immediately after the `LoginFilter` and checks any permissions assigned to the web context against the attributes of the user via Shiro.

|org.apache.shiro.realm.AuthenticatingRealm
|This is an abstract authenticating realm that exchanges an `org.apache.shiro.authc.AuthenticationToken` for a `${ddf-branding-lowercase}.security.Subject` in the form of an `org.apache.shiro.authc.AuthenticationInfo`

|${ddf-branding-lowercase}.security.realm.sts.StsRealm
|This realm is an implementation of `org.apache.shiro.realm.AuthenticatingRealm` and connects to an STS (configurable) to exchange the authentication token for a Subject.

|${ddf-branding-lowercase}.security.service.AbstractAuthorizingRealm
|This is an abstract authorizing realm that takes care of caching and parsing the Subject's `AuthorizingInfo` and should be extended to allow the implementing realm to focus on making the decision.

|${ddf-branding-lowercase}.security.pdp.realm.AuthZRealm
|This realm performs the authorization decision and may or may not delegate out to the external XACML processing engine. It uses the incoming permissions to create a decision.
However, it is possible to extend this realm using the ${ddf-branding-lowercase}.security.policy.extension.PolicyExtension interface.
This interface allows an integrator to add additional policy information to the PDP that can't be covered via its generic matching policies.
This approach is often easier to configure for those that are not familiar with XACML.
Note that no `PolicyExtension` implementations are provided out of the box.

|org.codice.${ddf-branding-lowercase}.security.validator.*
|A number of STS validators are provided for X.509 (BinarySecurityToken), UsernameToken, SAML Assertion, and ${branding} custom tokens.
The ${branding} custom tokens are all `BinarySecurityTokens` that may have PKI or username/password information as well as an authentication realm (correlates to JAAS realms installed in the container).
The authentication realm allows an administrator to restrict which services they wish to use to authenticate users.
For example: installing the `security-sts-ldaplogin` feature will enable a JAAS realm with the name "ldap".
This realm can then be specified on any context using the Web Context Policy Manager.
That realm selection is then passed via the token sent to the STS to determine which validator to use.

|===

[WARNING]
====
An update was made to the SAML Assertion Handler to pass SAML assertions via headers instead of cookies.
Cookies are still accepted and processed to maintain legacy federation compatibility, but only headers are used when federating out.
This means that it is still possible to federate and pass a machine's identity, but federation of a user's identity will ONLY work when federating from 2.7.x to 2.8.x+ or between 2.8.x+ and 2.8.x+.
====
