:title: Auditing
:type: securing
:status: published
:parent: Securing
:summary: Configure auditing.
:order: 01
:project: ${branding}

== {title}

* *{hardening-step}*

Audit logging captures security-specific system events for monitoring and review.
${branding} provides an <<{developing-prefix}security_logging_plugin,Audit Plugin>> that logs all catalog transactions to the `security.log`.
Information captured includes user identity, query information, and resources retrieved.

Follow all operational requirements for the retention of the log files.
This may include using cryptographic mechanisms, such as encrypted file volumes or databases, to protect the integrity of audit information.

[NOTE]
====
The Audit Log default location is `${home_directory}/data/log/security.log`
====

.Audit Logging Best Practices
[NOTE]
====
For the most reliable audit trail, it is recommended to configure the operational environment of the ${branding} to generate alerts to notify adminstrators of:

* auditing software/hardware errors
* failures in audit capturing mechanisms
* audit storage capacity (or desired percentage threshold) being reached or exceeded.
====

[WARNING]
====
The security audit logging function does not have any configuration for audit reduction or report generation.
The logs themselves could be used to generate such reports outside the scope of ${branding}.
====

=== Enabling Fallback Audit Logging

* *{hardening-step}*

In the event the system is unable to write to the `security.log` file, ${branding} must be configured to fall back to report the error in the application log:

* edit `${home_directory}/etc/org.ops4j.pax.logging.cfg`
** uncomment the line (remove the `#` from the beginning of the line) for `log4j2` (`org.ops4j.pax.logging.log4j2.config.file = ${karaf.etc}/log4j2.xml`)
** delete all subsequent lines

If you want to change the location of your systems security backup log from the default location: `${home_directory}/data/log/securityBackup.log`, follow the next two steps:

* edit `${home_directory}/security/configurations.policy`
** find "Security-Hardening: Backup Log File Permissions"
** below `grant codeBase "file:/pax-logging-log4j2"` add the path to the directory containing the new log file you will create in the next step.
* edit `${home_directory}/etc/log4j2.xml`
** find the entry for the `securityBackup` appender. (see example)
** change value of `filename` and prefix of `filePattern` to the name/path of the desired failover security logs

.`securityBackup` Appender Before
[source,xml,linenums]
----
<RollingFile name="securityBackup" append="true" ignoreExceptions="false"
                     fileName="${sys:karaf.log}/securityBackup.log"
                     filePattern="${sys:karaf.log}/securityBackup.log-%d{yyyy-MM-dd-HH}-%i.log.gz">
----

.`securityBackup` Appender After
[source,xml,linenums]
----
<RollingFile name="securityBackup" append="true" ignoreExceptions="false"
                     fileName="<NEW_LOG_FILE>"
                     filePattern="<NEW_LOG_FILE>-%d{yyyy-MM-dd-HH}-%i.log.gz">
----

[WARNING]
====
If the system is unable to write to the `security.log` file on system startup, fallback logging will be unavailable.
Verify that the `security.log` file is properly configured and contains logs before configuring a fall back.
====
