:title: Disallowing Login Without Certificates
:type: configuration
:status: published
:parent: Configuring User Access
:summary: Requiring certificate to log in.
:order: 08

== {title}

${branding} can be configured to prevent login without a valid PKI certificate.

* Navigate to the *${admin-console}*.
* Select *${ddf-security}*.
* Select *Web Context Policy Manager*.
* Add a policy for each context requiring restriction.
** For example, just configuring `PKI` as the authentication type for web pages will disallow login without certificates to ${branding}.
* Click *Save*.

If the `web-context-policy-config.properties` configuration file is used instead,

* Navigate to `<${branding}_HOME>`.
* Edit the `web-context-policy-config.properties` file.
* Add a policy for each context requiring restriction.
** For example: `/search=PKI` will disallow login without certificates to the Search UI.
** The format for the policy should be: `/<CONTEXT>=PKI`

[NOTE]
====
Ensure certificates comply with organizational hardening policies.
====
