:title: Managing Keystores
:type: subSecuring
:status: published
:parent: Managing Keystores and Certificates
:summary: Managing keystores.
:order: 00

== {title}

Certificates, and sometimes their associated private keys, are stored in keystore files.
${branding} includes two default keystore files, the server key store and the server trust store.
The server keystore holds the certificates and private keys that ${branding} uses to identify itself to other nodes on the network.
The truststore holds the certificates of nodes or other entities that ${branding} needs to trust.

=== Adding an Existing Server Keystore

If provided an existing keystore for use with ${branding}, follow these steps to replace the default keystore.

. Remove the default keystore at `etc/keystores/serverKeystore.jks`.
. Add the desired keystore file to the `etc/keystores` directory.
. Edit `custom.system.properties` file to set filenames and passwords.
.. If using a type of keystore other than `jks` (such as `pkcs12`), change the `javax.net.ssl.keyStoreType` property as well.
. If the truststore has the correct certificates, restart server to complete configuration.
.. If provided with an existing server truststore, continue to <<{managing-prefix}adding_an_existing_server_truststore,Adding an Existing Server Truststore>>.
.. Otherwise, <<{managing-prefix}creating_a_server_keystore,create a server truststore>>.

=== Adding an Existing Server Truststore

. Remove the default truststore at `etc/keystores/serverTruststore.jks`.
. Add the desired truststore file to the `etc/keystores` directory.
. Edit `custom.system.properties` file to set filenames and passwords.
.. If using a type of truststore other than `jks` (such as `pkcs12`), change the `javax.net.ssl.trustStoreType` property as well.

If the provided server keystore does not include the CA certificate that was used to sign the server's certificate, <<{managing-prefix}creating_a_server_keystore,add the CA certificate into the `serverKeystore` file>>.

=== Creating a New Keystore/Truststore with an Existing Certificate and Private Key

If provided an existing certificate, create a new keystore and truststore with it.

[NOTE]
====
${branding} requires that the keystore contains both the private key and the CA.
====

. [[_creating_a_server_keystore]]Using the private key, certificate, and CA certificate, create a new keystore containing the data from the new files.
+
[source]
----
cat client.crt >> client.key
openssl pkcs12 -export -in client.key -out client.p12
keytool -importkeystore -srckeystore client.p12 -destkeystore serverKeystore.jks -srcstoretype pkcs12 -alias 1
keytool -changealias -alias 1 -destalias client -keystore serverKeystore.jks
keytool -importcert -file ca.crt -keystore serverKeystore.jks -alias "ca"
keytool -importcert -file ca-root.crt -keystore serverKeystore.jks -alias "ca-root"
----
+
. [[_creating_a_server_truststore]]Create the truststore using only the CA certificate. Based on the concept of CA signing, the CA should be the only entry needed in the truststore.
+
----
keytool -import -trustcacerts -alias "ca" -file ca.crt -keystore truststore.jks
keytool -import -trustcacerts -alias "ca-root" -file ca-root.crt -keystore truststore.jks
----
+
. Create a PEM file using the certificate, as some applications require that format.
+
----
openssl x509 -in client.crt -out client.der -outform DER
openssl x509 -in client.der -inform DER -out client.pem -outform PEM
----

[IMPORTANT]
====
The localhost certificate must be removed if using a system certificate.
====

=== Updating Key Store / Trust Store via the ${admin-console}

Certificates (and certificates with keys) can be managed in the ${admin-console}.

. Navigate to the ${admin-console}.
. Select the *${ddf-security}* application.
. Select the *Certificates* tab.
. Add and remove certificates and private keys as necessary.
. Restart ${branding}.

[IMPORTANT]
====
The default trust store and key store files for ${branding} included in `etc/keystores` use self-signed certificates.
Self-signed certificates should never be used outside of development/testing areas.
====

This view shows the alias (name) of every certificate in the trust store and the key store.
It also displays if the entry includes a private key ("Is Key") and the encryption scheme (typically "RSA" or "EC").

This view allows administrators remove certificates from ${branding}'s key and trust stores.
It also allows administrators to import certificates and private keys into the keystores with the "+" button.
The import function has two options: import from a file or import over HTTPS.
The file option accepts a Java Keystore file or a PKCS12 keystore file.
Because keystores can hold many keys, the import dialog asks the administrator to provide the alias of the key to import.
Private keys are typically encrypted and the import dialog prompts the administrator to enter the password for the private key.
Additionally, keystore files themselves are typically encrypted and the dialog asks for the keystore ("Store") password.

The name and location of the ${branding} trust and key stores can be changed by editing the system properties files, `etc/custom.system.properties`.
Additionally, the password that ${branding} uses to decrypt (unlock) the key and trust stores can be changed here.

[IMPORTANT]
====
${branding} assumes that password used to unlock the keystore is the same password that unlocks private keys in the keystore.
====

The location, file name, passwords and type of the server and trust key stores can be set in the `custom.system.properties` file:

. Setting the Keystore and Truststore Java Properties
[source]
----
javax.net.ssl.keyStore=etc/keystores/serverKeystore.jks
javax.net.ssl.keyStorePassword=changeit
javax.net.ssl.trustStore=etc/keystores/serverTruststore.jks
javax.net.ssl.trustStorePassword=changeit
javax.net.ssl.keyStoreType=jks
javax.net.ssl.trustStoreType=jks
----

[NOTE]
====
If the server's fully qualified domain name is not recognized, the name may need to be added to the network's DNS server.
====

[TIP]
====
The ${branding} instance can be tested even if there is no entry for the FQDN in the DNS.
First, test if the FQDN is already recognized.
Execute this command:

`ping <FQDN>`

If the command responds with an error message such as unknown host, then modify the system's `hosts` file to point the server's FQDN to the loopback address.
For example:

`127.0.0.1 <FQDN>`
====

.Changing Default Passwords
[NOTE]
====
This step is not required for a hardened system.

* The default password in `custom.system.properties` for `serverKeystore.jks` is `changeit`. This needs to be modified.
** `ds-cfg-key-store-file: ../../keystores/serverKeystore.jks`
** `ds-cfg-key-store-type: JKS`
** `ds-cfg-key-store-pin: password`
** `cn: JKS`
* The default password in `custom.system.properties` for `serverTruststore.jks` is `changeit`.  This needs to be modified.
** `ds-cfg-trust-store-file: ../../keystores/serverTruststore.jks`
** `ds-cfg-trust-store-pin: password`
** `cn: JKS`
====
