:title: Managing Certificate Revocation
:type: configuration
:status: published
:parent: Configuring User Access
:summary: Managing certificate revocation list.
:order: 09

== {title}

* *{hardening-step}*

For hardening purposes, it is recommended to implement a way to verify a Certificate Revocation List (CRL) at least daily or an Online Certificate Status Protocol (OCSP) server.

=== Managing a Certificate Revocation List (CRL)
A Certificate Revocation List is a collection of formerly-valid certificates that should explicitly _not_ be accepted.

==== Creating a CRL

Create a CRL in which the token issuer's certificate is valid.
The example uses OpenSSL.

`$> openssl ca -gencrl -out crl-tokenissuer-valid.pem`

.Windows and OpenSSL
[NOTE]
====
Windows does not include OpenSSL by default.
For Windows platforms, a additional download of https://www.openssl.org/source/[OpenSSL] or an alternative is required.
====

===== Revoke a Certificate and Create a New CRL that Contains the Revoked Certificate

----
$> openssl ca -revoke tokenissuer.crt

$> openssl ca -gencrl -out crl-tokenissuer-revoked.pem
----

===== Viewing a CRL

. Use the following command to view the serial numbers of the revoked certificates:
`$> openssl crl -inform PEM -text -noout -in crl-tokenissuer-revoked.pem`

==== Enabling Certificate Revocation

[NOTE]
====
Enabling CRL revocation or modifying the CRL file will require a restart of ${branding} to apply updates.
====

. Place the CRL in ${home_directory}/etc/keystores.
. Add the line `org.apache.ws.security.crypto.merlin.x509crl.file=etc/keystores/<CRL_FILENAME>` to the following files (Replace `<CRL_FILENAME>` with the URL or file path of the CRL location):
.. `${home_directory}/etc/ws-security/server/encryption.properties`
.. `${home_directory}/etc/ws-security/issuer/encryption.properties`
.. `${home_directory}/etc/ws-security/server/signature.properties`
.. `${home_directory}/etc/ws-security/issuer/signature.properties`
. (Replace <CRL_FILENAME> with the file path or URL of the CRL file used in previous step.)

Adding this property will also enable CRL revocation for any context policy implementing PKI authentication.
For example, adding an authentication policy in the Web Context Policy Manager of `/search=PKI` will disable basic authentication and require a certificate for the search UI.
If a certificate is not in the CRL, it will be allowed through, otherwise it will get a 401 error.
If no certificate is provided, and guest access is enabled on the web context policy, guest access will be granted.

This also enables CRL revocation for the STS endpoint.
The STS CRL Interceptor monitors the same `encryption.properties` file and operates in an identical manner to the PKI Authenication's CRL handler. Enabling the CRL via the `encryption.properties` file will also enable it for the STS, and also requires a restart.

If the CRL cannot be placed in ${home_directory}/etc/keystores but can be accessed via an *HTTPS* URL:

. Navigate to the *${admin-console}*.
. Select the *${ddf-security}* application.
. Select the *Configuration* tab.
. Select *Certificate Revocation List (CRL)*
. Add the *HTTPS* URL under *CRL URL address*
. Check the *Enable CRL via URL* option

A local CRL file will be created and the `encryption.properties` and `signature.properties` files will be set as mentioned above.

===== Add Revocation to a Web Context

The PKIHandler implements CRL revocation, so any web context that is configured to use PKI authentication will also use CRL revocation if revocation is enabled.

. After enabling revocation (see above), open the *Web Context Policy Manager*.
. Add or modify a Web Context to use PKI in authentication. For example, enabling CRL for the search ui endpoint would require adding an authorization policy of `/search=PKI`
. If guest access is also required, check the `Allow Guest Access` box in the policy.

With guest access, a user with a revoked certificate will be given a 401 error, but users without a certificate will be able to access the web context as the guest user.

The STS CRL interceptor does not need a web context specified.
The CRL interceptor for the STS will become active after specifying the CRL file path, or the URL for the CRL, in the `encryption.properties` file and restarting ${branding}.

[NOTE]
====
Disabling or enabling CRL revocation or modifying the CRL file will require a restart of ${branding} to apply updates.
If CRL checking is already enabled, adding a new context via the *Web Context Policy Manager* will not require a restart.
====

===== Adding Revocation to an Endpoint

[NOTE]
====
This section explains how to add CXF's CRL revocation method to an endpoint and not the CRL revocation method in the `PKIHandler`.
====

This guide assumes that the endpoint being created uses CXF and is being started via Blueprint from inside the OSGi container.
If other tools are being used the configuration may differ.

Add the following property to the `jasws` endpoint in the endpoint's `blueprint.xml`:

[source]
----
<entry key="ws-security.enableRevocation" value="true"/>
----

.Example xml snippet for the `jaxws:endpoint` with the property:
[source]
----
<jaxws:endpoint id="Test" implementor="#testImpl"
                wsdlLocation="classpath:META-INF/wsdl/TestService.wsdl"
                address="/TestService">

    <jaxws:properties>
        <entry key="ws-security.enableRevocation" value="true"/>
    </jaxws:properties>
</jaxws:endpoint>
----

===== Verifying Revocation

A *Warning* similar to the following will be displayed in the logs of the source and endpoint showing the exception encountered during certificate validation:

[source]
----
11:48:00,016 | WARN  | tp2085517656-302 | WSS4JInInterceptor               | ecurity.wss4j.WSS4JInInterceptor  330 | 164 - org.apache.cxf.cxf-rt-ws-security - 2.7.3 |
org.apache.ws.security.WSSecurityException: General security error (Error during certificate path validation: Certificate has been revoked, reason: unspecified)
    at org.apache.ws.security.components.crypto.Merlin.verifyTrust(Merlin.java:838)[161:org.apache.ws.security.wss4j:1.6.9]
    at org.apache.ws.security.validate.SignatureTrustValidator.verifyTrustInCert(SignatureTrustValidator.java:213)[161:org.apache.ws.security.wss4j:1.6.9]

[ ... section removed for space]

Caused by: java.security.cert.CertPathValidatorException: Certificate has been revoked, reason: unspecified
    at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:139)[:1.6.0_33]
    at sun.security.provider.certpath.PKIXCertPathValidator.doValidate(PKIXCertPathValidator.java:330)[:1.6.0_33]
    at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:178)[:1.6.0_33]
    at java.security.cert.CertPathValidator.validate(CertPathValidator.java:250)[:1.6.0_33]
    at org.apache.ws.security.components.crypto.Merlin.verifyTrust(Merlin.java:814)[161:org.apache.ws.security.wss4j:1.6.9]
    ... 45 more
----

=== Managing an Online Certificate Status Protocol (OCSP) Server

An Online Certificate Status Protocol is a protocol used to verify the revocation status of a certificate.
An OCSP server can be queried with a certificate to verify if it is revoked.

The advantage of using an OCSP Server over a CRL is the fact that a local copy of the revoked certificates is not needed.

==== Enabling OCSP Revocation

. Navigate to the *${admin-console}*.
. Select the *${ddf-security}* application.
. Select the *Configuration* tab.
. Select *Online Certificate Status Protocol (OCSP)*
. Add the URL of the OCSP server under *OCSP server URL*.
. Check the *Enable validating a certificate against an OCSP server* option.

[NOTE]
====
If an error occurs while communicating with the OCSP server, an alert will be posted to the ${admin-console}.
Until the error is resolved, certificates will not be verified against the server.
====