= Extending {branding} Spatial App
<<<<<<< HEAD
Copyright (c) Codice Foundation
:imagesdir: target/docs/images
:toc: right
:branding: DDF
:audience: Developer
:icons: font
:example-caption!:
:source-highlighter: coderay
:linkcss:

////
Copyright (c) Codice Foundation
 
 This is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or any later version.
 
 This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. A copy of the GNU Lesser General Public License is distributed along with this program and can be found at <http://www.gnu.org/licenses/lgpl.html>.

////
=======
include::../config.adoc[]
>>>>>>> 9648ab46634db6ffbcb1dddfae5c9664f2ef57f7

== Overview
The DDF Spatial Application provides KML transformer and a KML network link endpoint that allows a user to generate a View-based KML Query Results Network Link.

This guide supports developers creating extensions of the existing framework.
