= Managing {branding} Standard Search UI
include::../includes/config.adoc[]

== Overview

The Standard Search UI is a user interface that enables users to search a catalog and associated sites for content and metadata.

This page describes:

* Which applications must be installed prior to installing this application.
* How to install the DDF Standard Search UI.
* How to verify if the DDF Standard Search UI was successfully installed.
* How to uninstall the DDF Standard Search UI.
* How to upgrade the DDF Standard Search UI.

== Prerequisites

Before the DDF Search UI application can be installed: 

* the DDF Kernel must be running.
* the DDF Platform Application must be installed.
* the DDF Catalog Application must be installed.

== Installing 

The Search UI application is installed by default

If using the Admin application, this app can be installed via the Admin Console or the System Console (at `http://localhost:8181/system/console/features`). Otherwise, follow steps below.

. Before installing a DDF application, verify that its prerequisites have been met. 
. Copy the DDF application's KAR file to the `<INSTALL_DIRECTORY>/deploy` directory.

[NOTE]
====
These Installation steps are the same whether DDF was installed from a distribution zip or a custom installation using the DDF Kernel zip.
====

=== Verifying Installation

. Verify the appropriate features for the DDF application have been installed using the
`features:list` command to view the KAR file's features.
. Verify that the bundles within the installed features are in an active state.

== Configuring

Configure individual features within the application with the
Admin Console.

=== Configurable Properties

==== Search UI Endpoint
[cols="1,1,1,4,1" options="header"]
|===

|Title really
|Property
|Type
|Description
|Required

|Disable Cache
|cacheDisabled
|Boolean
|Disables use of cache.
|no

|===

==== Standard Search UI
[cols="1,1,1,4,1" options="header"]
|===

|Title really
|Property
|Type
|Description
|Required

|Header
|header
|String
|The header text to be rendered on the Search UI.
|no

|Footer
|footer
|String
|The footer text to be rendered on the Search UI.
|no

|Style
|style
|String
|The style name (background color) of the Header and Footer.
|yes

|Text Color
|textColor
|String
|The text color of the Heater and Footer.
|yes

|Result count
|resultCount
|Integer
|The max number of results to display.
|yes

|Imagery Providers
|imageryProviders
|String
|List of imagery providers to use. Valid types are: +
OSM (OpenStreetMap), +
AGM (ArcGisMap), +
BM (BingMap),+
WMS (WebMapService), +
WMT (WebMapTile), +
TMS (TileMapService), +
GE (GoogleEarth).

Example: TYPE={url=
{"type" "WMS" "url" "http://example.com" "layers" ["layer1" "layer2"] "parameters" {"FORMAT" "image/png" "VERSION" "1.1.1"} "alpha" 0.5}}
|no

|Terrain Providers
|terrainProvider
|String
|Terrain provider to use for height data. Valid types are: +
CT (CesiumTerrain), +
AGS (ArcGisImageServer), +
VRW (VRTheWorld).

Example: +
{"type" "CT" "url" "http://example.com"}
|no

|Map Projection	
|projection	
|String	
|Projection of imagery providers	
|no

|Connection timeout
|timeout
|Integer
|The WMS connection timeout.
|yes

|Show sign in
|signIn
|Boolean
|Whether or not to authenticate users.
|no

|Show tasks
|task
|Boolean
|Whether or not to display progress of background tasks.
|no

|Show Gazetteer
|gazetteer
|Boolean
|Whether or not to show gazetteer for searching place names.
|no

|Show Uploader
|ingest
|Boolean
|Whether or not to show upload menu for adding new metadata.
|no

|Type Name Mapping
|typeNameMapping
|String[]
|The mapping of content types to displayed names.
|no
 
|===

== Uninstalling

If using the Admin application, applications can be removed via the Admin Console. 

=== Uninstalling manually
[WARNING]
====
It is very important to save the KAR file or the feature repository URL for the application prior to an uninstall so that the uninstall can be reverted if necessary.
====

If the DDF application is deployed on the DDF Kernel in a custom installation (or the application has been upgraded previously), i.e., its KAR file is in the `<INSTALL_DIRECTORY>/deploy` directory, uninstall it by deleting this KAR file.

Otherwise, if the DDF application is running as part of the DDF distribution zip, it is uninstalled *the first time and only the first time* using the `features:removeurl` command:


.Uninstall DDF application from DDF distribution
----
features:removeurl -u <DDF application's feature repository URL>

Example:   features:removeurl -u mvn:ddf.ui.search/search-app/2.5.0/xml/features
----

The uninstall of the application can be verified by the absence of any of the DDF application's features in the `features:list` command output.


[NOTE]
====
The repository URLs for installed applications can be obtained by entering:

`features:listrepositories -u`
====

=== Reverting the Uninstall

If the uninstall of the DDF application needs to be reverted, this is accomplished by either:

* copying the application's KAR file previously in the `<INSTALL_DIRECTORY>/deploy`
 directory, OR 
* adding the application's feature repository back into DDF and installing its main feature, which typically is of the form `<applicationName>-app`, e.g., `catalog-app`.

.Reverting DDF application's uninstall
----
features:addurl <DDF application's feature repository URL>
features:install <DDF application's main feature>

Example:

    ddf@local>features:addurl mvn:ddf.catalog/catalog-app/2.3.0/xml/features
    ddf@local>features:install catalog-app
----

== Upgrading

Upgrading to a newer version of the app can be performed by the Admin Console.

=== Upgrading manually

To upgrade an application, complete the following procedure.

. Uninstall the application by following the Uninstall Applications instructions above.
. Install the new application KAR file by copying the admin-app-X.Y.kar file to the `<INSTALL_DIRECTORY>/deploy` directory. +
`features:install admin-app`
. Start the application.
. Complete the steps in the Verify section above to determine if the upgrade was successful.

== Troubleshooting {branding} Standard Search UI

=== Deleted Records Are Being Displayed In The Standard Search UI's Search Results

When queries are issued by the Standard Search UI, the query results that are returned are also cached in an internal Solr database for faster retrieval when the same query may be issued in the future. As records are deleted from the catalog provider, this Solr cache is kept in sync by also deleting the same records from the cache if they exist.

Sometimes the cache may get out of sync with the catalog provider such that records that should have been deleted are not. When this occurs, users of the Standard Search UI may see stale results since these records that should have been deleted are still being returned from the cache. When this occurs records in the cache can be manually deleted using the URL commands listed below from a browser. In these command URLs, metacard_cache is the name of the Solr query cache. These command URL examples are for a non-secured DIB. If the DIB is secured, then the command URLs would start with `https://localhost:8993/` assuming the secure port is configured for 8993.

* To delete all of the records in the Solr cache:

.Deletion of all records in Solr query cache
----
http://localhost:8181/solr/metacard_cache/update?stream.body=<delete><query>*:*</query></delete>&commit=true
----
* To delete a specific record in the Solr cache by ID (specified by the original_id_txt field):

.Deletion of record in Solr query cache by ID
----
http://localhost:8181/solr/metacard_cache/update?stream.body=<delete><query>original_id_txt:50ffd32b21254c8a90c15fccfb98f139</query></delete>&commit=true
----
* To delete record(s) in the Solr cache using a query on a field in the record(s) - in this example, the title_txt field is being used with wildcards to search for any records with word remote in the title:

.Deletion of records in Solr query cache using search criteria
----
http://localhost:8181/solr/metacard_cache/update?stream.body=<delete><query>title_txt:*remote*</query></delete>&commit=true
----
