
==== Creating and Installing Keys and Certificates

To create a private key and certificate signed by the Demo Certificate Authority, use the provided scripts.
To use the scripts, run them out of the <INSTALL_HOME>/etc/certs directory. For *NIX, use the CertNew.sh script.

`sh CertNew.sh <FQDN>`

The above command creates a new entry in the keystore for a server named `my.server.com`.

Alternatively, a FQDN can be provided to the script with a comma-delimited string.

`sh CertNew.sh -dn "c=US, st=California, o=Yoyodyne, l=San Narciso, cn=<FQDN>"`

To create and install the certificates on Windows, use the `CertNew.cmd` file in the same directory.

`CertNew <FQDN>`

Alternatively, a FQDN can be provided to the script with a comma-delimited string.

`CertNew -dn "c=US, st=California, o=Yoyodyne, l=San Narciso, cn=<FQDN>"`

To install a certificate signed by a different Certificate Authority, see <<Import into a Java Keystore (JKS)>>.

===== Restart and Test

Finally, restart the ${branding} instance.
Browse the ${admin-console} at \https://<FQDN>:8993/admin to test changes.

[WARNING]
====
If the server's fully qualified domain name is not recognized, the name may need to be added to the network's DNS server.
====

[TIP]
====
The ${branding} instance can be tested even if there is no entry for the FQDN in the DNS.
First, test if the FQDN is already recognized.
Execute this command:

`ping <FQDN>`

If the command responds with an error message such as unknown host, then modify the system's `hosts` file to point the server's FQDN to the loopback address.
For example:

`127.0.0.1 <FQDN>`
====

[NOTE]
====
By default, the Catalog Backup Post-Ingest Plugin is *NOT* enabled.
To enable, the Enable Backup Plugin configuration item must be checked in the Backup Post-Ingest Plugin configuration.

`Enable Backup Plugin: true`
====

[IMPORTANT]
====
The Embedded LDAP has hard-coded values for the keystore path, truststore path, keystore password, and truststore password (https://github.com/codice/opendj-osgi/blob/d5021cbac4db831467ceb109ffd7ffd2c734dcd4/embedded/opendj-embedded-server/src/main/resources/config/config.ldif).
So if using a non-default keystore and non-default truststore, the Embedded LDAP will not work.
You will see errors in `<INSTALL_HOME>/etc/org.codice.opendj/ldap/logs/errors` similar to the one below:

[source]
----
`21/Jan/2015:08:58:57 -0700] category=CORE severity=NOTICE msgID=458891 msg=The Directory Server has sent an alert notification generated by class org.opends.server.protocols.ldap.LDAPConnectionHandler (alert type org.opends.server.LDAPHandlerDisabledByConsecutiveFailures, alert ID 2425016):  The LDAP connection handler defined in configuration entry cn=LDAP Connection Handler,cn=Connection Handlers,cn=config has experienced consecutive failures while trying to accept client connections:  An error occurred while attempting to initialize the SSL context for use in the LDAP Connection Handler:  An error occurred while trying to load the keystore contents from file ../../keystores/serverKeystore.jks:  IOException(Keystore was tampered with, or password was incorrect) (id=1310782) (LDAPConnectionHandler.java:1324 LDAPConnectionHandler.java:1255 LDAPConnectionHandler.java:1091 LDAPConnectionHandler.java:974).  This connection handler will be disabled`
----

A workaround is to modify `config.ldif` as seen in the steps below and hot deploy `opendj-embedded-app-<version>.kar.`
====

** The default password in `config.ldif` for `serverKeystore.jks` is `changeit`. This needs to be modified.
*** `ds-cfg-key-store-file: ../../keystores/serverKeystore.jks`
*** `ds-cfg-key-store-type: JKS`
*** `ds-cfg-key-store-pin: password`
*** `cn: JKS`
** The default password in `config.ldif` for `serverTruststore.jks` is `changeit`.  This needs to be modified.
*** `ds-cfg-trust-store-file: ../../keystores/serverTruststore.jks`
*** `ds-cfg-trust-store-pin: password`
*** `cn: JKS`

