Follow these procedures to build ${branding} from source code.

==== Prerequisites

* Install http://www.oracle.com/technetwork/java/javase/downloads/index.html[J2SE 8 SDK].
* Verify that the `JAVA_HOME` environment variable is set to the newly installed JDK location, and that the PATH includes `%JAVA_HOME%\bin` (for Windows) or `$JAVA_HOME$/bin` (*nix).
* Install http://git-scm.com/download[Git], if not previously installed.
* Install http://maven.apache.org/download.cgi[Maven 3.1.0] or later. Verify that the `PATH` includes the `MVN_HOME/bin` directory.
** In addition, access to a Maven repository with the latest project artifacts and dependencies is necessary in order for a successful build.
The following sample `settings.xml` (the default settings file) can be used to access the public repositories with the required artifacts.
For more help on how to use the `settings.xml` file, refer to the http://maven.apache.org/settings.html[Maven settings reference page].

.Sample `settings.xml` file
[source,xml,linenums]
----
<settings>
	<!-- If proxy is needed
	<proxies>
		<proxy>
		</proxy>
	</proxies>
	-->
</settings>
----

.Handy Tip on Encrypting Passwords
[TIP]
====
See this http://maven.apache.org/guides/mini/guide-encryption.html[Maven guide] on how to encrypt the passwords in your `settings.xml`.
====

==== Procedures

===== Clone the ${ddf-branding} Repository

.Using HTTPS
----
https://github.com/codice/ddf.git
----

.Using SSH
----
git@github.com:codice/ddf.git
----

[NOTE]
====
Generally, SSH is faster than HTTPS, but requires setting an SSH git and passphrase with http://github.com[Github]. Additionally, there may be restrictions on the use of SSH on some networks.
====

===== Run the Build


* Build command example for one individual repository.
----
# Build is run from the top level of the specified repository in a command line prompt or terminal.
cd ddf-support
mvn clean install

# At the end of the build, a BUILD SUCCESS will be displayed.
----


[NOTE]
====
The zip distribution of ${branding} is contained in the ${branding} app in the distribution/ddf/target directory after the ${branding} app is built.
====

[NOTE]
====
It may take several moments for Maven to download the required dependencies in the first build.
Build times may vary based on network speed and machine specifications.
====

[WARNING]
====
In certain circumstances, the build may fail due to a ``java.lang.OutOfMemory: Java heap space` error.
This error is due to the large number of sub-modules in the ${branding} build, which causes the heap space to run out in the main Maven JVM.
To fix this issue, set the system variable `MAVEN_OPTS` with the value `-Xmx2048m` before running the build.
Example on Linux system with the bash shell: `export MAVEN_OPTS='-Xmx2048m'`
====

==== Troubleshooting Build Errors on ddf-admin and ddf-ui on a Windows Platform

Currently, the developers are using the following tools:

[cols="2" options="header"]
|===

|Name
|Version

|bower
|1.3.2

|node.js
|v0.10.26

|npm
|1.4.3

|===

[NOTE]
====
There have been intermittent build issues during the bower install.
The error code that shows is an EPERM related to either 'renaming' files or 'unlinking' files.
This issue has been tracked multiple times on the bower github page.
The following link contains the most recent issue that was tracked:
https://github.com/bower/bower/issues/991

This issue will be closely monitored for a full resolution.
Until a proper solution is found, there are some options that may solve the issue.

. Re-run the build.
Occasionally, the issue occurs on first run and will resolve itself on the next.
. Clean out the cache.
There may be a memory issue, and a cache clean may help solve the issue.
+
----
bower cache clean
npm cache clean
----
+
.Reinstall bower.
An occasional reinstall may solve the issue.
+
----
npm uninstall -g bower && npm install -g bower
----
+
. Download and use Cygwin to perform the build.
This may allow a user to simulate a run on a *nix system, which may not experience these issues.

These options are taken from suggestions provided on github issue tickets.
There have been several tickets created and closed, and several workarounds have been suggested.
However, it appears that the issue still exists.
Once more information develops on the resolution of this issue, this page will be updated.
====
