===== Accessing the ${admin-console}

* Navigate to the ${admin-console}. (Default: \${secure_url}/admin)
* Enter Username and Password. (Default: `admin/admin`)

===== Initial Configuration

The first time the ${branding} ${admin-console} runs, the initial configuration steps appear.

. Click *Start* to begin.
. On the next screen, general configuration settings such as host address, port and site name can all be configured. (See <<Configuring ${branding} Global Settings>> for important settings to configure)
. Next, choose between a standard installation and a full installation. (Individual applications can be added, removed or deactivated later)

[WARNING]
====
Platform App, Admin App, and Security Services App CANNOT be selected or unselected as it is installed by default and can cause errors if removed.
====

===== Viewing Currently Active Applications from ${admin-console}

====== Tile View

The first view presented is the Tile View, displaying all active applications as individual tiles.

====== List View

Optionally, active applications can be displayed in a list format by clicking the list view button.

Either view has an `>` arrow to view more information about the application as currently configured.

====== Configuration

The Configuration tab lists all bundles associated with the application as links to configure any configurable properties of that bundle.

====== Details

The Details tab gives a description, version, status, and list of other applications that either required for , or rely on, the current application.

====== Features

The features tab breaks down the individual features of the application that can be installed or uninstalled as configurable features.

===== Managing Applications

The Manage button enables activation/deactivation and adding/removing applications.

====== Activating / Deactivating Applications

The Deactivate button stops individual applications and any dependent apps.
Certain applications are central to overall functionality and cannot be deactivated.
These will have the Deactivate button disabled.
Disabled apps will be moved to a list at the bottom of the page, with an enable button to reactivate, if desired.

[IMPORTANT]
====
Deactivating the `platform-app`, `admin-app`, and `security-services-app` will cause errors within the system, so the capabilities to do so have been DISABLED.
====

====== Adding Applications

The Add Application button is at the end of the list of currently active applications.

====== Removing Applications

To remove an application, it must first be deactivated.
This enables the Remove Application button.

====== Upgrading Applications

Each application tile includes an upgrade but to select a new version to install.

===== System Settings Tab

The configuration and features installed can be viewed and edited from the System tab as well, however, it is recommended that configuration be managed from the applications tab.

[IMPORTANT]
====
In general, applications should be managed via the applications tab.
Configuration via this page could result in an unstable system.
Proceed with caution!
====

===== Managing Features Using the ${admin-console}

. Select the appropriate application.
. Select the *Features* tab.
. Uninstalled features are shown with a *play* arrow under the Actions column.
.. Select the *play* arrow for the desired feature.
.. The *Status* will change from *Uninstalled* to *Installed*.
. Installed features are shown with a *stop* icon under the Actions column.
.. Select the *stop* icon for the desired feature.
.. The *Status* will change from *Installed* to *Uninstalled*.

====== Add Feature Repositories

. Select the *Manage* button in the upper right.
. Select the *Add an Application* tile
. Select *File Upload* to add a new `.kar`, `.jar`, OR
. Select the *Maven URL* tab and enter the URL of the feature repository.
.. Select the *Add URL* button.
. Select the *Save Changes* button.

===== Configuring HTTP Port from ${admin-console}

[IMPORTANT]
====
Do not use the ${admin-console} to change the HTTP port.
While the Admin Console's Pax Web Runtime offers this configuration option, it has proven to be unreliable and may crash the system.
====

===== Configuring HTTP to HTTPS Proxy From the ${admin-console}

The `platform-http-proxy` feature proxies https to http for clients that cannot use HTTPS and should not have HTTP enabled for the entire container via the `etc/org.ops4j.pax.web.cfg` file.

. Click the *${ddf-platform}* application tile.
. Choose the *Features* tab.
. Select `platform-http-proxy`.
. Click on the *Play* button to the right of the word “Uninstalled”

====== Configuring the proxy:

[NOTE]
====
The hostname should be set by default.
Only configure the proxy if this is not working.
====

. Select *Configuration* tab.
. Select *HTTP to HTTPS Proxy Settings*
.. Enter the Hostname to use for HTTPS connection in the proxy.
. Click *Save changes*.

