==== Configuring ${branding} Global Settings

Global configuration settings are configured via the properties file `system.properties`.
These properties can be manually set by editing this file or set via the initial configuration from the ${admin-console}.

.Configurable Properties
[cols="1,1,1,6,2,1"]
|===
|Title
|Property
|Type
|Description
|Default Value
|Required

6+^|Keystore and truststore java properties

|Keystore
|`javax.net.ssl.keyStore`
|String
|Path to server keystore
|`etc/keystores/serverKeystore.jks`
|Yes

|Keystore Password
|`javax.net.ssl.keyStorePassword`
|String
|Password for accessing keystore
|`changeit`
|Yes

|Truststore
|`Truststorejavax.net.ssl.trustStore`
|String
|The trust store used for SSL/TLS connections. Path is relative to `<INSTALL_HOME>`.
|`etc/keystores/serverTruststore.jks`
|Yes

|Truststore Password
|`javax.net.ssl.trustStorePassword`
|String
|Password for server Truststore
|`changeit`
|Yes

|Keystore Type
|`javax.net.ssl.keyStoreType`
|String
|File extension to use with server keystore
|`jks`
|Yes

|Truststore Type
|`javax.net.ssl.trustStoreType`
|String
|File extension to use with server truststore
|`jks`
|Yes

6+^| Global URL Properties

|Protocol
|`org.codice.${ddf-branding-lowercase}.system.protocol`
|String
|Default protocol that should be used to connect to this machine.
|`https://`
|Yes

|Hostname
|`org.codice.${ddf-branding-lowercase}.system.hostname`
|String
|The hostname or IP address used to advertise the system. Do not enter `localhost`. Possibilities include the address of a single node or that of a load balancer in a multi-node deployment.

NOTE: Does not change the address the system runs on.
|`localhost`
|Yes

|HTTPS Port
|`org.codice.${ddf-branding-lowercase}.system.httpsPort`
|String
|The https port used by the system.

NOTE: This *DOES* change the port the system runs on.
|`8993`
|Yes

|HTTP Port
|`org.codice.${ddf-branding-lowercase}.system.httpPort`
|String
|The http port used by the system.

NOTE: This *DOES* change the port the system runs on.
|`8181`
|Yes

|Default Port
|`org.codice.${ddf-branding-lowercase}.system.port`
|String
|The default port used to advertise the system. This should match either the http or https port.

NOTE: Does not change the port the system runs on.
|`8993`
|Yes

|Root Context
|`org.codice.${ddf-branding-lowercase}.system.rootContext`
|String
|The the base or root context that services will be made available under.
|`/services`
|Yes

6+^|System Information Properties

|Site Name
|`org.codice.${ddf-branding-lowercase}.system.id`
|String
|The site name for ${branding}.
|`${ddf-branding-lowercase}.distribution`
|Yes

|Site Contact
|`org.codice.${ddf-branding-lowercase}.system.siteContact`
|String
|The email address of the site contact.
|
|No

|Version
|`org.codice.${ddf-branding-lowercase}.system.version`
|String
|The version of ${branding} that is running.

This value should not be changed from the factory default.
|`${project.version}`
|Yes

|Organization
|`org.codice.${ddf-branding-lowercase}.system.organization`
|String
|The organization responsible for this installation of ${branding}.
|Codice Foundation
|Yes

6+^|Thread Pool Settings

|Thread Pool Size
|`org.codice.${ddf-branding-lowercase}.system.threadPoolSize`
|Integer
|Size of thread pool used for handling UI queries, federating requests, and downloading resources
|`128`
|Yes

6+^|HTTPS Specific Settings

|Cipher Suites
|`https.cipherSuites`
|String
|Cipher suites to use with secure sockets
|`TLS_DHE_RSA_WITH_AES_128_CBC_SHA,

TLS_DHE_RSA_WITH_AES_128_CBC_SHA,

TLS_DHE_DSS_WITH_AES_128_CBC_SHA,

TLS_RSA_WITH_AES_128_CBC_SHA`
|No

|Https Protocols
|`https.protocols`
|String
|Protocols to allow for secure connections
|`TLSv1.1,TLSv1.2`
|No

|Allow Basic Auth Over Http
|`org.codice.allowBasicAuthOverHttp`
|Boolean
|Set to true to allow Basic Auth credentials to be sent over HTTP unsecurely. This should only be done in a test environment. These events will be audited.
|`false`
|Yes

|Restrict the Security Token Service to allow connections only from DNs matching these patterns
|`ws-security.subject.cert.constraints`
|String
|Set to a comma separated list of regex patterns to define which hosts are allowed to connect to the STS
|`.*`
|Yes

6+^|XML Settings

|Parse XML documents into DOM object trees
|`javax.xml.parsers.DocumentBuilderFactory`
|String
|Enables Xerces-J implementation of `DocumentBuilderFactory`
|`org.apache.xerces.jaxp.DocumentBuilderFactoryImpl`
|Yes

6+^|File Upload Settings

|File extensions flagged as potentially dangerous to the host system or external clients
|`bad.file.extensions`
|String
|Files uploaded with these bad file extensions will have their file names sanitized before being saved
|`.exe,.jsp,.html,.js,.php,.phtml,.php3,.php4,.php5,.phps,.shtml,.jhtml,.pl,.py,.cgi,.msi,.com,.scr,.gadget,.application,.pif,.hta,.cpl,.msc,.jar,.kar,.bat,.cmd,.vb,.vbs,.vbe,.jse,.ws,.wsf,.wsc,.wsh,.ps1,.ps1xml,.ps2,.ps2xml,.psc1,.psc2,.msh,.msh1,.msh2,.mshxml,.msh1xml,.msh2xml,.scf,.lnk,.inf,.reg,.dll,.vxd,.cpl,.cfg,.config,.crt,.cert,.pem,.jks,.p12,.p7b,.key,.der,.csr,.jsb,.mhtml,.mht,.xhtml,.xht`
|Yes

|File names flagged as potentially dangerous to the host system or external clients
|`bad.files`
|String
|Files uploaded with these bad file names will have their file names sanitized before being saved
|`crossdomain.xml,clientaccesspolicy.xml,.htaccess,.htpasswd,hosts,passwd,group,resolv.conf,nfs.conf,ftpd.conf,ntp.conf,web.config,robots.txt`
|Yes

|Mime types flagged as potentially dangerous to external clients
|`bad.mime.types`
|String
|Files uploaded with these mime types will be rejected from the upload
|`text/html,text/javascript,text/x-javascript,application/x-shellscript,text/scriptlet,application/x-msdownload,application/x-msmetafile`
|Yes

|===

These properties are available to be used as variable parameters in input url fields within the ${admin-console}.
For example, the url for the local csw service (\${secure_url}/services/csw) could be defined as:

[source]
----
${variable-prefix}org.codice.${ddf-branding-lowercase}.system.protocol}${variable-prefix}org.codice.${ddf-branding-lowercase}.system.hostname}:${variable-prefix}org.codice.${ddf-branding-lowercase}.system.port}${variable-prefix}org.codice.${ddf-branding-lowercase}.system.rootContext}/csw
----

This variable version is more verbose, but will not need to be changed if the system `host`, `port` or `root` context changes.


[IMPORTANT]
====
Since certain bundles can only be configured using the `.config` file format, this file format should be used.
====

[WARNING]
====
Only root can access ports < 1024 on Unix systems.
For suggested ways to run ${branding} with ports < 1024 see <<How do I use port 80 as a non-root user?>>.
====

===== Configuring ${branding} `.config` Files

The ${branding} is configured using `.config` files.
Like the Karaf `.cfg` files, these configuration files must be located in the `<${ddf-branding}_HOME>/etc/` directory, have a name that matches the _configuration persistence ID_ (PID) they represent, and have a `service.pid` property set to the configuration PID.

As opposed to `.cfg` however, this type of configuration file supports lists within configuration values (metatype `cardinality` attribute greater than 1).

[IMPORTANT]
====
This new configuration file format *must* be used for any configuration that makes use of lists.
Examples include Web Context Policy Manager (PID: `org.codice.${ddf-branding-lowercase}.security.policy.context.impl.PolicyManager`)
and Security STS Guest Claims Handler (PID: `${ddf-branding-lowercase}.security.sts.guestclaims`).
====

[WARNING]
====
Only one configuration file should exist for any given PID.
The result of having both a `.cfg` and a `.config` file for the same PID is undefined and could cause the application to fail.
====

The main purpose of the configuration files is to allow administrators to pre-configure ${branding} without having to use the ${admin-console}.
In order to do so, the configuration files need to be copied to the `<${branding}_HOME>/etc` directory after ${branding} zip has been extracted.

Upon start up, all the `.config` files located in `<${branding}_HOME>/etc` are automatically read and processed.
Files that have been processed successfully are moved to `<${branding}_HOME>/etc/processed` so they will not be processed again when the system is restarted.
Files that could not be processed are moved to the `<${branding}_HOME>/etc/failed` directory.

${branding} also monitors the `<${branding}_HOME>/etc` directory for any new `.config` file that gets added.
As soon as a new file is detected, it is read, processed and moved to the appropriate directory based on whether it was successfully processed or not.

===== Configuring Managed Service Factory Bundles

Services that are created using a Managed Service Factory can be configured using `.config` files as well.
The configuration files follow a different naming convention however.
The files must start with the Managed Service Factory PID, be followed by a unique identifier and have a `.config` extension.
For instance, assuming that the Managed Service Factory PID is `org.codice.${ddf-branding-lowercase}.factory.pid` and two instances of the service need to be configured, files `org.codice.${ddf-branding-lowercase}.factory.pid.uniqueID1.config` and `org.codice.${ddf-branding-lowercase}.factory.pid.uniqueID2.config` should be created and added to `<${branding}_HOME>/etc`.

The unique identifiers used in the file names have no impact on the order in which the configuration files are processed.
No specific processing order should be assumed.
Also, a new service will be created and configured every time a configuration file matching the Managed Service Factory PID is added to the directory, regardless of the number used.

These configuration files must also contain a `service.factoryPid` property set to the factory PID (without the sequential number).
They should not however contain the `service.pid` property.

====== File Format

The basic syntax of the `.config` configuration files is similar to the older `.cfg` files but introduces support for lists and types other than simple strings.
The type associated with a property must match the `type` attribute used in the corresponding `metatype.xml` file when applicable.

The following table shows the format to use for each property type supported.

[cols="1,2,4" options="header"]
|===

|Type
|Format
|Example

|Service PID
|`service.pid = "servicePid"`
|`service.pid = "org.codice.${ddf-branding-lowercase}.security.policy.context.impl.PolicyManager"`

|Factory PID
|`service.factoryPid = "serviceFactoryPid"`
|`service.factoryPid = "Csw_Federated_Source"`

|Strings
|`name = "value"`
|`name = "john"`

|Booleans
|`name = B"true\|false"`
|`authorized = B"true"`

|Integers
|`name = I"value"`
|`timeout=I"60"`

|Longs
|`name = L"value"`
|`diameter = L"10000"`

|Floats
|`name = F"value"`
|`cost = F"10.50"`

|Doubles
|`name = D"value"`
|`latitude = D"45.0234"`

|Lists of Strings
|`name = [ "value1", "value2", ... ]`
|`authenticationTypes = [ "/\=SAML\|GUEST", "/admin\=SAML\|basic", "/system\=basic", "/solr\=SAML\|PKI\|basic", "/sources\=SAML\|basic", "/security-config\=SAML\|basic" ]`

|Lists of Integers
|`name = I[ "value1", "value1", ... ]`
|`sizes = I[ "10", "20", "30" ]`

|===

[NOTE]
====
* Lists of values can be prefixed with any of the supported types (`B`, `I`, `L`, `F` or `D`)
* To prevent any configuration issues, the `=` signs used in values should be escaped using `\`
* Boolean values will default to `false` if any value other than `true` is provided
====

.Sample configuration file
[source,java,linenums]
----
service.pid="org.codice.${ddf-branding-lowercase}.security.policy.context.impl.PolicyManager"

authenticationTypes=["/\=SAML|GUEST","/admin\=SAML|basic","/system\=basic","/solr\=SAML|PKI|basic","/sources\=SAML|basic","/security-config\=SAML|basic","/search\=basic"]

realms=["/\=karaf"]

requiredAttributes=["/\=","/admin\={http://schemas.xmlsoap.org/ws/2005/05/identity/claims/role\=admin}","/solr\={http://schemas.xmlsoap.org/ws/2005/05/identity/claims/role\=admin}","/system\={http://schemas.xmlsoap.org/ws/2005/05/identity/claims/role\=admin}","/security-config\={http://schemas.xmlsoap.org/ws/2005/05/identity/claims/role\=admin}"]

whiteListContexts=["/services/SecurityTokenService","/services/internal/metrics","/services/saml","/proxy","/services/csw"]
----

====== Editing HTTP Ports for Multiple Local ${branding} Nodes

Edit the port numbers in the files in the ${branding} install folder.

[cols="4" options="header"]
|===

|File to Edit
|Property(ies)
|Original Value
|Example of New Value

|`bin/karaf.bat`
|`address`
|`5005`
|`5006`

.2+|`etc/org.apache.karaf.management.cfg`
|`rmiRegistryPort`
|`1099`
|`1199`


|`rmiServerPort`
|`44444`
|`44445`

.2+|`etc/system.properties`
|`httpsPort`,`port`
|`8993`
|`8994`

|`httpPort`
|`8181`
|`8281`

|===

==== Editing ${branding} Web Service Providers Configuration Files

[IMPORTANT]
====
If the hostname is changed during the install to something other than `localhost` a new keystore and truststore must be provided.
====

[TIP]
====
When changing the hostname for testing or development purposes, the installer can be started with a `?dev=true` URL query parameter. This will cause the system to automatically generate self signed certificates for any hostname that is entered during the install process.
====

===== Configuring Files in HOME Directory Hierarchy

[IMPORTANT]
====
The passwords configured in this section reflect the passwords used to decrypt JKS (Java KeyStore) files.
Changing these values without also changing the passwords of the JKS causes undesirable behavior.
====
* In `<${branding}_HOME>/etc/users.properties`, modify the line:
----
localhost=localhost,group,admin,manager,viewer,system-admin
----
To be:
----
<FQDN>=<PASSWORD>,group,admin,manager,viewer,system-admin
----

* Next ,configure `<${branding}_HOME>/etc/system.properties`
[source,bash]
----
#START ${branding} SETTINGS
# Set the keystore and truststore Java properties
javax.net.ssl.keyStore=etc/keystores/serverKeystore.jks
javax.net.ssl.keyStorePassword=<NewPassword>
javax.net.ssl.trustStore=etc/keystores/serverTruststore.jks
javax.net.ssl.trustStorePassword=<NewPassword>
javax.net.ssl.keyStoreType=jks

# Set the global url properties
org.codice.${ddf-branding-lowercase}.system.protocol=https://
org.codice.${ddf-branding-lowercase}.system.hostname=<FQDN>
org.codice.${ddf-branding-lowercase}.system.httpsPort=8993
org.codice.${ddf-branding-lowercase}.system.httpPort=8181
org.codice.${ddf-branding-lowercase}.system.port=8993
org.codice.${ddf-branding-lowercase}.system.rootContext=/services

# HTTPS Specific settings. If making a Secure Connection not leveraging the HTTPS Java libraries and
# classes (e.g. if you are using secure sockets directly) then you will have to set this directly
https.cipherSuites=TLS_DHE_RSA_WITH_AES_128_CBC_SHA,TLS_DHE_RSA_WITH_AES_128_CBC_SHA,TLS_DHE_DSS_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_128_CBC_SHA
https.protocols=TLSv1.1,TLSv1.2
----

==== Configuring Notifications

Notifications are messages that are sent to clients to inform them of some significant event happening in ${branding}.
Clients must subscribe to a ${branding} notification channel to receive these messages.

===== Using Notifications

${branding} notifications are currently being utilized in the ${ddf-branding} Catalog application for resource retrieval.
When a user initiates a resource retrieval via the ${ddf-branding} Standard Search UI, ${branding} opens the channel `/${ddf-branding-lowercase}/notification/catalog/downloads`, where notifications indicating the progress of that resource download are sent.
Any client interested in receiving these progress notifications must subscribe to that channel.
When ${branding} starts downloading the resource to the client that requested it, a notification with a status of "Started" will be broadcast.
If the resource download fails, a notification with a status of "Failed" will be broadcast.
Or, if the resource download is being attempted again after a failure, "Retry" will be broadcast.

When a notification is received, ${ddf-branding} Standard UI displays a popup containing the contents of the notification, so a user is made aware of how their downloads are proceeding.

Behind the scenes, the ${ddf-branding} Standard Search UI invokes the REST endpoint to retrieve a resource.
In this request, it adds the query parameter "user" with the CometD session ID or the unique User ID as the value.
This allows the CometD server to know which subscriber is interested in the notification.
For example, \http://${branding}_HOST:8993/services/catalog/sources/${ddf-branding-lowercase}.distribution/2f5db9e5131444279a1293c541c106cd?transform=resource&user=1w1qlo79j6tscii19jszwp9s2i55 notifications contain the following information:

[cols="1,4,1" options="header"]
|===

|Parameter Name
|Description
|Required by ${branding} Standard UI

|`application`
|"Downloads" for resource retrieval.
This is used as a "type" or category of messages.
|Yes

|`title`
|Resource/file name for resource retrieval.
|Yes

|`message`
|Human-readable message containing status and a more detailed message.
|Yes

|`timestamp`
|Timestamp in milliseconds of when event occurs.
|Yes

|`user`
|CometD Session ID or unique User ID.
|Yes

|`status`
|Status of event.
|No

|`option`
|Resource retrieval option.
|No

|`bytes`
|Number of bytes transmitted.
|No

|===

====== Receive Notifications

* If interested in retrieve resource notifications, a client must subscribe to the CometD `channel/${ddf-branding-lowercase}/notification/catalog/downloads`.
* If interested in all notification types, a client must subscribe to the CometD `channel/${ddf-branding-lowercase}/notification/**`
* A client will only receive notifications for resources they have requested.
* ${ddf-branding} Standard UI is subscribed to all notifications of interest to that `user/browser session: /${ddf-branding-lowercase}/notification/**`

====== Publish Notifications

Any application running in ${branding} can publish notifications that can be viewed by the ${ddf-branding} Standard UI or received by another notifications client.
. Set a properties map containing entries for each of the parameters listed above in the Usage section.
+
. Set the OSGi event topic to `${ddf-branding-lowercase}/notification/<application-name>/<notification-type>`.
Notice that there is no preceding slash on an OSGi event topic name, while there is one on the CometD channel name.
The OSGi event topic corresponds to the CometD channel this is published on.
+
. Post the notification to the OSGi event defined in the previous step.

.Example for Publishing Notification
[source,java,linenums]
----
Dictionary <String, Object> properties = new Hashtable<String, Object>();
properties.put("application", "Downloads");
properties.put("title", resourceResponse.getResource().getName());
Long sysTimeMillis = System.currentTimeMillis();
properties.put("message", generateMessage(status, resourceResponse.getResource().getName(), bytes, sysTimeMillis, detail));
properties.put("user", getProperty(resourceResponse, USER));
properties.put("status", "Completed");
properties.put("bytes", 1024);
properties.put("timestamp", sysTimeMillis);

Event event = new Event("${ddf-branding-lowercase}/notification/catalog/downloads", properties);

eventAdmin.postEvent(event);
----
==== Configuring Solr Catalog Provider Data Directory

The Solr Catalog Provider writes index files to the file system.
By default, these files are stored under `${branding}_HOME/data/solr/catalog/data`.
If there is inadequate space in `${branding}_HOME`, or if it is desired to maintain backups of the indexes only, this directory can be changed.

In order to change the Data Directory, the `system.properties` file in `${branding}_HOME/etc` must be edited prior to starting ${branding}.

.Edit the `system.properties` file
[source]
----
# Uncomment the following line and set it to the desired path
#solr.catalog.data.dir=/opt/solr/catalog/data
----

===== Changing the Data Directory after ${branding} has ingested data

. Shut down ${branding}.
. Create the new directory to hold the indexes.
+
.Make new Data Directory
[source,bash]
----
mkdir /path/to/new/data/dir
----
+
. Copy the indexes to the new directory.
+
.Copy the indexes to the new Directory.
[source,bash]
----
cp /path/to/old/data/dir/* /path/to/new/data/dir/.
----
+
. Set the `system.properties` file to use the new directory.
+
.Set the SOLR_CATALOG_DATA_DIR
[source,java]
----
solr.catalog.data.dir=/path/to/new/data/dir
----
+
. Restart ${branding}.

===== Configuring Thread Pools

The `system.properties` file found under `${branding}_HOME/etc` contains properties that will be made available through system properties at the beginning of Karaf's boot process. The `org.codice.${ddf-branding-lowercase}.system.threadPoolSize` property can be used to specify the size of thread pools used by:
* Federating requests between ${branding} systems
* Downloading resources
* Handling asynchronous queries, such as queries from the UI

By default, this value is set to 128.
It is not recommended to set this value extremely high.
If unsure, leave this setting at it's default value of 128.

