The {branding} documentation is segmented by user needs, with users categorized as Users, Administrators, Integrators, and Developers.

=== Documentation Outline

The documentation is segmented by user needs, with users categorized as Users, Administrators, Integrators, and Developers. 

Users::
Users are end users interacting with the applications at the most basic level.
User help is available through the *Help* link in the User Interface.

Administrators::
<<Managing {branding}>> |
Administrators will be installing, maintaining, and supporting existing applications.
Sections titled with Managing support administrators.

Integrators::
<<Integrating {branding}>> |
Integrators will use the existing applications to support their external frameworks.
Sections titled with Integrating support administrators.

Developers::
<<Extending {branding}>> |
Developers will build or extend the functionality of the applications. 
Sections titled with Extending support administrators.

==== Documentation Updates
The most current Distributed Data Framework {branding}) documentation is available at: https://codice.atlassian.net/wiki/display/DDF/DDF+Documentation[{branding} Documentation].

==== Conventions

The following conventions are used within this documentation:

===== Callouts

[TIP]
====
This is a *Tip*, used to provide helpful information.
====

[NOTE]
====
This is an *Informational Note*, used to emphasize points, remind users of beneficial information, or indicate minor problems in the outcome of an operation.
====

[WARNING]
====
This is an *Emphasized Note*, used to inform of important information.
====

[IMPORTANT]
====
This is a *Warning*, used to alert users about the possibility of an undesirable outcome or condition.
====

===== Customizable Values

Many values used in descriptions are customizable and should be changed for specific use cases.
These values are denoted by `< >`, and by `[[ ]]` when within XML syntax. When using a real value, the placeholder characters should be omitted.

===== Code Values

Java objects, lines of code, or file properties are denoted with the `Monospace` font style.
Example: `ddf.catalog.CatalogFramework`

===== Hyperlinks

Some hyperlinks (e.g., `/admin`) within the documentation assume a locally running installation of {branding}. 
Simply change the hostname if accessing a remote host.

==== Questions

Questions about {branding} or this documentation should be posted to the https://groups.google.com/d/forum/{branding}-users[{branding}-users forum], https://groups.google.com/d/forum/{branding}-announcements[{branding}-announcements forum], or https://groups.google.com/d/forum/{branding}-developers[{branding}-developers forum], where they will be responded to quickly by a member of the {branding} team.
