
=== Installing ${branding}

[IMPORTANT]
====
Although ${branding} can be installed by any user, it is recommended for security reasons to have a non-`root` user execute the ${branding} installation.
====

==== Prerequisites

===== Directory Permissions

Restrict access to sensitive files by ensuring that the only users with access privileges are administrators.

====== Directory Permissions on Windows

. Right-click on the file or directory noted below then select *Full Control → Administrators → System*.
. Click *Properties → Security → Advanced* and select Creator Owner for `INSTALLATION_HOME` (e.g., `C:\ddf`).
. Restrict access to sensitive files by ensuring that only *System* and *Administrators* have Full Control to the below files by right-clicking on the file or directory below then selecting *Properties → Security → Advanced*
. Delete any other groups or users listed with access to `INSTALLATION_HOME/etc` and `INSTALLATION_HOME/deploy`.

* Install/Upgrade to Java 8 http://www.oracle.com/technetwork/java/javase/downloads/index.html[J2SE 8 SDK]
* Supported platforms are *NIX - Unix/Linux/OSX, Solaris, and Windows.
* http://www.oracle.com/technetwork/java/javase/downloads/index.html[JDK8] must be installed.
* The `JAVA_HOME` environment variable must be set to the location where the JDK is installed.

.Setting `JAVA_HOME` on *NIX
----
JAVA_HOME=/usr/java/jdk1.8.0
export JAVA_HOME
----

.Setting `JAVA_HOME` on Windows
----
set JAVA_HOME=C:\Program Files\Java\jdk1.8.0
----

.*NIX
[WARNING]
====
Unlink `/usr/bin/java` if it is already linked to a previous version of the JRE:
`unlink /usr/bin/java`
====

[TIP]
====
Verify that the `JAVA_HOME` was set correctly.

.*NIX
----
echo $JAVA_HOME
----

.Windows
----
echo %JAVA_HOME%
----
====

* ${branding} installation zip file.
* A web browser.
* For Linux systems, increase the file descriptor limit by editing `/etc/sysctl.conf` to include or change the following:

.File Descriptor Limit
----
fs.file-max = 6815744
----

.Restart
[WARNING]
====
For the change to take effect, a restart is required.
====

.Restart Command
----
init 6
----

===== Directory Permissions on *NIX

Protect the ${ddf-branding} from unauthorized access.

. As root, change the owner and group of critical ${ddf-branding} directories to the `NON_ROOT_USER`.
+
[WARNING]
====
A `NON_ROOT_USER` (e.g., ddf) is recommended for installation.
====
+
[source, bash, linenums]
----
chown -R NON_ROOT_USER ${branding}_HOME ${branding}_HOME/etc ${branding}_HOME/data
chgrp -R NON_ROOT_USER ${branding}_HOME/etc ${branding}_HOME/data
chmod -R og-w ${branding}_HOME/etc ${branding}_HOME/data
----
+
. Restrict access to sensitive files by ensuring that the only users with “group” permissions (e.g., ${ddf-branding-lowercase}-group) have access.
. Execute the following command on the above files (examples assume `INSTALLATION_HOME` is `/opt/${branding-lowercase}`):
+
[source,bash]
----
chmod -R o /opt/${branding-lowercase}
----
+
. As the the application owner (e.g., ${ddf-branding-lowercase} user), restrict access to sensitive files.
+
[source,bash,linenums]
----
chmod 640 /opt/${branding-lowercase}/etc
chmod 640 /opt/${branding-lowercase}/deploy
----

[IMPORTANT]
====
The system administrator must restrict certain directories to ensure that the application (user) cannot access restricted directories on the system.
For example the `NON_ROOT_USER` should only have read access to `/opt/${branding-lowercase}`.
====


==== Deployment Guidelines

${branding} relies on the Directory Permissions of the host platform to protect the integrity of the ${branding} during operation.
System administrators should perform the following steps when deploying bundles added to the ${branding}.

. Prior to allowing a hot deployment, check the available storage space on the system to ensure the deployment will not exceed the available space.
. Set maximum storage space on the `INSTALLATION_HOME/deploy` and `INSTALLATION_HOME/system` directories to restrict the amount of space used by deployments.
. Do not assume the deployment is from a trusted source; verify its origination.
. Use the source code to verify a deployment is required for ${branding} to prevent unnecessary/vulnerable deployments.

==== Installing With the ${branding} Distribution Zip

* After the prerequisites have been met, as a root user if for *NIX, change the current directory to the desired install location.
This will be referred to as `<INSTALL_DIRECTORY>`.

.*NIX Tip
[TIP]
It is recommended that the root user create a new install directory that can be owned by a non-root user (e.g., ${branding-lowercase}-user).
The non-root user (e.g., ${branding-lowercase}-user) can now be used for the remaining installation instructions.

.Example: Create a Directory and Switch User on *NIX
----
mkdir new_installation
chown ${branding-lowercase}-user:${branding-lowercase}-group new_installation

su - ${branding-lowercase}-user
----

* Change the current directory to location of zip file (${branding-lowercase}-X.Y.zip).

.Example: Where the Zip File may be Located in *NIX
----
cd /home/user/cdrom
----

.Windows (Example assumes ${branding} has been downloaded to the D drive)
----
cd D:\
----
* Copy ${branding-lowercase}-X.Y.zip to <INSTALL_DIRECTORY>.

.*NIX
----
cp ${branding-lowercase}-X.Y.zip <INSTALL_DIRECTORY>
----

.Windows
----
copy ${branding-lowercase}-X.Y.zip <INSTALL_DIRECTORY>
----

* Change the current directory to the desired install location.

.*NIX or Windows
----
cd <INSTALL_DIRECTORY>
----

* The ${branding} zip is now located within the `<INSTALL_DIRECTORY>`. Unzip ${branding-lowercase}-X.Y.zip.

.*NIX
----
unzip ${branding-lowercase}-X.Y.zip
----

.Example: Use Java to Unzip in Windows
----
"C:\Program Files\Java\jdk1.8.0\bin\jar.exe" xf ${branding-lowercase}-X.Y.zip
----

* Run ${branding} using the appropriate script.

.*NIX
----
<INSTALL_DIRECTORY>/${branding-lowercase}-X.Y/bin/${branding-lowercase}
----

.Windows
----
<INSTALL_DIRECTORY>/${branding-lowercase}-X.Y/bin/${branding-lowercase}.bat
----

Execute the following command at the command line for status:

.View Status
----
${branding-lowercase}${at-symbol}local>list
----

// Verify this step is still required.
* If the ${branding} Standalone Solr Server will be installed later, an additional configuration step is required for the ${branding} kernel.
Add the following lines to the bottom of the `<INSTALL_DIR>/etc/org.ops4j.pax.web.cfg` file:

.Additional Configuration Step
----
# Jetty Configuration
`org.ops4j.pax.web.config.file=<KARAF.HOME>/etc/jetty.xml`
----

* Run the ${branding} using the appropriate script.

.*NIX
----
<INSTALL_DIRECTORY>/${branding-lowercase}-${project.version}/bin/${branding-lowercase}
----

.Windows
----
<INSTALL_DIRECTORY>/${branding-lowercase}-${project.version}/bin/${branding-lowercase}.bat
----

The distribution takes a few moments to load depending on the hardware configuration.
Execute the following command at the command line for status:

.View Status
----
${branding}${at-symbol}local>list
----
The list of bundles should look similar to this:

.${branding} List of Apps Installed
----
.${branding}${at-symbol}local>list
START LEVEL 100 , List Threshold: 50
   ID   State         Blueprint      Spring    Level  Name
[ 111] [Active     ] [            ] [       ] [   80] Commons IO (2.1.0)
[ 113] [Active     ] [Created     ] [       ] [   80] ${branding} :: Distribution :: Console Branding Plugin (${project.version})
----

.${branding} Application Installation Dependencies

[WARNING]
====
If completing a non-standard installation, be aware that some applications depend on other ${branding} applications being installed.

This hierarchy can be shown using the `app:tree` command

[source]
----
${ddf-branding-lowercase}${at-symbol}local>app:tree
+- opendj-embedded
+- platform-app
|   +- catalog-app
|   |   +- search-ui-app
|   |   |   +- spatial-app
|   |   +- solr-app
|   +- security-services-app
|   |   +- admin-app
----

====

===== Verifying Installation

At this point, ${branding} should be configured and running with a Solr Catalog Provider.
New features (endpoints, services, and sites) can be added as needed.

Verification is achieved by checking that all of the ${branding} bundles are in an Active state (excluding fragment bundles which remain in a Resolved state).

The following command displays the status of all the ${branding} bundles:

.View Status
----
${branding-lowercase}${at-symbol}local>list  grep -i ${branding-lowercase}

----

[WARNING]
====
// This sentence is formatted unusually because of the double colons.
Entries in the *Resolved* state are expected, they are OSGi bundle fragments.
Bundle fragments are distinguished from other bundles in the command line console list by a field named `Hosts`, followed by a bundle number.
Bundle fragments remain in the *Resolved* state and can never move to the *Active* state.
====

.Example: Bundle Fragment in the Command Line Console
----
215 | Resolved |  80 | ${project.version}     | DDF :: Platform :: Security :: Session, Hosts: 90
----

===== ${branding} Directory Contents after Installation and Initial Startup

During ${branding} installation, the major directories and files shown in the table below are created, modified, or replaced in the destination directory.

[cols="1,1,8" options="header"]
|===

|Directory Name
2+|Description

|`bin`
2+|Scripts to start and stop ${branding}

.4+|`data`
2+|The working directory of the system – installed bundles and their data

|`data/log/${branding}.log`
|Log file for ${branding}, logging all errors, warnings, and (optionally) debug statements. This log rolls up to 10 times, frequency based on a configurable setting (default=1 MB)

|`data/log/ingest.log`
|Log file for any ingest errors that occur within ${branding}.

|`data/log/security.log`
|Log file that records user interactions with the system for auditing purposes.

|`deploy`
2+|Hot-deploy directory – KARs and bundles added to this directory will be hot-deployed (Empty upon ${branding} installation)

|`documentation`
2+|HTML and PDF copies of ${branding} documentation.

.4+|`etc`
2+|Directory monitored for addition/modification/deletion of `.config` configuration files or third party `.cfg` configuration files.

|`etc/failed`
|If there is a problem with any of the `.config` files, such as bad syntax or missing tokens, they will be moved here.

|`etc/processed`
|All successfully processed `.config` files will be moved here.

|`etc/templates`
|Template `.config` files for use in configuring ${branding} sources, settings, etc., by copying to the etc directory.

|`lib`
2+|The system's bootstrap libraries. Includes the `${branding-lowercase}-branding.jar` file which is used to brand the system console with the ${branding} logo.

|`licenses`
2+|Licensing information related to the system.

|`system`
2+|Local bundle repository. Contains all of the JARs required by ${branding}, including third-party JARs.

|===

After successfully completing these steps, the ${branding} is ready to be configured.
