This section supports integrating ${branding} with existing applications or frameworks.

=== Understanding Metadata and Metacards

Metadata is information about a resource, organized into a schema to make it possible to search against.
The ${ddf-catalog} stores this metadata and allows access to it. If desired, the ${ddf-content} application can be installed to store the resources themselves.
Metacards are single instances of metadata, representing a single record, in the Metadata Catalog (MDC).
Metacards follow one of several schemas to ensure reliable, accurate, and complete metadata.
Essentially, Metacards function as containers of metadata.

=== Populating Metacards (during ingest)

Upon ingest, a metacard transformer will read the data from the ingested file and populate the fields of the metacard.
Exactly how this is accomplished depends on the origin of the data, but most fields (except id) are imported directly.

=== Searching Metadata

${branding} provides the capability to search the Metadata Catalog (MDC) for metadata.
There are a number of different types of searches that can be performed on the MDC, and these searches are accessed using one of several interfaces.
This section provides a very high level overview of introductory concepts of searching with ${branding}.
These concepts are expanded upon in later sections.

==== Search Types

There are four basic types of metadata search.
Additionally, any of the types can be combined to create a compound search.

===== Contextual Search

A contextual search is used when searching for textual information.
It is similar to a Google search over the metadata contained in the MDC.
Contextual searches may use wildcards, logical operators, and approximate matches.

===== Spatial Search

A spatial search is used for Area of Interest (AOI) searches.
Polygon and point radius searches are supported.
Specifically, the spatial search looks at the metacards' location attribute and coordinates are specified in *WGS 84* decimal degrees.

===== Temporal Search

A temporal search finds information from a specific time range.
Two types of temporal searches are supported: _relative_ and _absolute_.
Relative searches contain an offset from the current time, while absolute searches contain a start and an end timestamp.
Temporal searches can look at the effective date attribute or the modified date.

===== Datatype
A datatype search is used to search for metadata based on the datatype, and optional versions.
Wildcards (*) can be used in both the datatype and version fields.
Metadata that matches any of the datatypes (and associated versions if specified) will be returned.
If a version is not specified, then all metadata records for the specified datatype(s) regardless of version will be returned.

===== Compound Search

These search types may be combined to create Compound searches.
For example, a Contextual and Spatial search could be combined into one Compound search to search for certain text in metadata in a particular region of the world.

==== Search Interfaces

===== ${ddf-ui} Application

The ${branding} Search UI application provides a graphic interface to return results and locate them on an interactive globe or map.

===== SSH

Additionally, it is possible to use a client script to remotely access ${branding} via SSH and send console commands to search and ingest data.

=== Catalog Search Result Objects

Data is returned from searches as Catalog Search Result objects.
This is a subtype of Catalog Entry that also contains additional data based on what type of sort policy was applied to the search.
Because it is a subtype of Catalog Entry, a Catalog Search Result has all Catalog Entry’s fields such as metadata, effective time, and modified time.
It also contains some of the following fields, depending on type of search, that are populated by ${branding} when the search occurs:

* Distance: Populated when a point radius spatial search occurs.
Numerical value that indicates the result’s distance from the center point of the search.
* Units: Populated when a point radius spatial search occurs.
Indicates the units (kilometer, mile, etc.) for the distance field.
* Relevance: Populated when a contextual search occurs.
Numerical value that indicates how relevant the text in the result is to the text originally searched for.

==== Search Programmatic Flow

Searching the catalog involves three basic steps:

. Define the search criteria (contextual, spatial, temporal, or compound – a combination of two or more types of searches).
.. Optionally define a sort policy and assign it to the criteria.
.. For contextual search, optionally set the `fuzzy` flag to `true` or `false` (the default value for the `Metadata Catalog` `fuzzy` flag is `true`, while the `portal` default value is `false`).
.. For contextual search, optionally set the caseSensitive flag to true (the default is that caseSensitive flag is NOT set and queries are not case sensitive).
Doing so enables case sensitive matching on the search criteria.
For example, if caseSensitive is set to true and the phrase is “Baghdad” then only metadata containing “Baghdad” with the same matching case will be returned.
Words such as “baghdad”, “BAGHDAD”,  and “baghDad” will not be returned because they do not match the exact case of the search term.
. Issue a search
. Examine the results

===== Sort Policies

Searches can also be sorted according to various built-in policies.
A sort policy is applied to the search criteria after its creation but before the search is issued.
The policy specifies to the ${branding} the order the MDC search results should be in when they are returned to the requesting client.
Only one sort policy may be defined per search.

There are three policies available.

.Sort Policies
[cols="4" options="header"]
|===

|Sort Policy
|Sorts By
|Default Order
|Available for

|Temporal
|The catalog search result’s effective time field
|Newest to oldest
|All Search Types

|Distance
|The catalog search result’s distance field
|Nearest to farthest
|Point-Radius Spatial searches

|Relevance
|The catalog search result’s relevance field
|Most to least relevant
|Contextual

|===

If no sort policy is defined for a particular search, the temporal policy will automatically be applied.

[WARNING]
====
For Compound searches, the parent Compound search’s sort policy is used.
For example, if a Spatial search and Contextual search are the components of a Compound search, the Spatial search might have a distance policy and the Contextual search might have a relevance policy.
The parent Compound search, though, does not use the policy of its child objects to define its sorting approach.
The Compound search itself has its own temporal sort policy field that it will use to order the results of the search.
====

=== Asynchronous Search & Retrieval

Asynchronous Search & Retrieval allows a requestor to execute multiple queries at once, begin multiple product downloads while query results are being returned, cancel queries and downloads, and receive status on the state of incoming query results and product downloads.

.Important Terms for Asynchronous Search
[cols="3" options="header"]
|===
|Capability
|Description
|Endpoint Integration

|Asynchronous Search
|Search multiple sources simultaneously
|Search UI

|Product caching
|Allows quick retrieval of already downloaded products
|${ddf-catalog}

|Canceling Product Downloads
|The ability to cancel a download in progress
|${ddf-catalog}

|Activities
a|Activities
* `download`
* `retry`
* `cancel`
* `pause`
* `remove`
* `resume`
|${ddf-catalog}, CometD endpoint

|Notifications
|Time-stamped messages of an action
|${ddf-catalog}, DDF UI/CometD endpoint

|Workspaces
|Ability to save and manage queries and save metacards
|${ddf-platform}, DDF UI/CometD endpoint

|3D Map support
|Ability to execute a geospatial search using a 3D map
|N/A

|===

===== Product Retrieval

The ${branding} is used to catalog resources.
A Resource is a URI-addressable entity that is represented by a Metacard.
Resources may also be known as products or data.
Resources may exist either locally or on a remote data store.

.Examples of Resources

* NITF image
* MPEG video
* Live video stream
* Audio recording
* Document

.Product Retrieval Services

* SOAP Web services
* ${branding} JSON
* ${branding} REST

The Query Service Endpoint, the Catalog Framework, and the `CatalogProvider` are key
components for processing a retrieve product request.
The Endpoint bundle contains a Web service that exposes the interface to retrieve products, also referred to as Resources.
The Endpoint calls the `CatalogFramework` to execute the operations of its specification.
The `CatalogFramework` relies on the Sources to execute the actual product retrieval.
Optional PreResource and PostResource Catalog Plugins may be invoked by the `CatalogFramework` to modify the product retrieval request/response prior to the Catalog Provider processing the request and providing the response.
It is possible to retrieve products from specific remote Sources by specifying the site name(s) in the request.

.Product Caching
[NOTE]
====
Existing ${branding} clients are able to leverage product caching due to the product cache being implemented in the ${branding}.
Enabling the product cache is an administrator function.

Product Caching is bundled with the `catalog-core-standardframework` feature.
It can be configured using the " Enable Product Caching" property in the *Catalog Standard Framework* configuration.

Product Caching is disabled by default.
====

.Product Retrieval Request
[ditaa,product_retrieval_request,png]
....
+------+             +---------------------------------------------------------------------------------------------------------------------------------+
| cDEF |             |/-----------------\/--------------------------\/-----------------\/------------------\/--------------------------\/-------------\|/--------------------\
|Client|             ||c369<<Endpoint>> ||c369<<CatalogFramework>>  ||c369             ||c369              ||c369<<DownloadManager>>   ||  <<Cache>>  |||c369<<External>>    |
+------+             || Service Endpoint||Standard Catalog Framework||PreResourcePlugin||PostResourcePlugin||     Download Manager     ||c369Cache    |||    Resource Host   |
  :                  |\-----------------/\--------------------------/\-----------------/\------------------/\--------------------------/\-------------/|\--------------------/
  |Service Retrieval |        :                       |                         |               |                     |                        |       |        |
  | Request          |        |                       :                         :               :                     :                        :       |        :
  |------------------|------->|                       |                         |               |                     |                        |       |        |
  |                  |        |query(ResourceRequest) |                         |               |                     |                        |       |        |
  |                  |        |---------------------->|process(ResourceRequest) |               |                     |                        |       |        |
  |                  |        |                       |------------------------>|               |                     |                        |       |        |
  |                  |        |                       |   ResourceRequest       |               |                     |                        |       |        |
  |                  |        |                       |<------------------------|               |                     |                        |       |        |
  |                  | cDEF   |                       | getResource             |               |                     |                        |       |        |
  |                  |        |                       |-------------------------------------------------------------->| download               |       |        |
  |                  |        |                       |                         :               :                     |------------------------|-------|------->|
  |                  |        |                       |                         |               |                     |    resource            |       |        |
  |                  |        |                       |                         |               |                     |<-----------------------|-------|--------|
  |                  |        |                       |                         |               |                     | resource               |       |        |
  |                  |        |                       |                         |               |                     |----------------------->|       |        |
  |                  |        |                       |      resource           |               |                     |                        |       |        |
  |                  |        |                       |<------------------------|-------------------------------------|                        |       |        |
  |                  |        |                       |process(ResourceResponse):               :                     |                        |       |        |
  |                  |        |                       |-------------------------|-------------->|                     |                        |       |        |
  |                  |        |                       |   ResourceResponse      |               |                     |                        |       |        |
  |                  |        |                       |<------------------------|---------------|                     |                        |       |        |
  |Web Service       |        |       ResourceResponse|                         |               |                     |                        |       |        |
  |     Retrieval Response    |<----------------------|                         :               |                     |                        |       |        |
  |<-----------------|--------|                       |                         |               |                     |                        |       |        |
  |                  |        |                       |                         |               |                     |                        |       |        |
  |                  +---------------------------------------------------------------------------------------------------------------------------------+        |
  |                                                                                                                                                             |
....


The Catalog Framework optionally provides caching of products, so future requests to retrieve the same product will be serviced much quicker.
If caching is enabled, each time a retrieve product request is received, the Catalog Framework will look in its cache (default location: `<INSTALL_DIR>/data/productcache`)to see if the product has been cached locally.
If it has, the product is retrieved from the local site and returned to the client, providing a much quicker turnaround because remote product retrieval and network traffic was avoided.
If the requested product is not in the cache, the product is retrieved from the Source (local or remote) and cached locally while returning the product to the client.
The caching to a local file of the product and the streaming of the product to the client are done simultaneously so that the client does not have to wait for the caching to complete before receiving the product.
If errors are detected during the caching, caching of the product will be abandoned, and the product will be returned to the client.

The Catalog Framework attempts to detect any network problems during the product retrieval, such as long pauses where no bytes are read, implying a network connection was dropped.
(The amount of time that a "long pause" is defined as is configurable, with the default value being five seconds.)
The Catalog Framework will attempt to retrieve the product up to a configurable number of times (default = three), waiting for a configurable amount of time (default = 10 seconds) between each attempt, trying to successfully retrieve the product.
If the Catalog Framework is unable to retrieve the product, an error message is returned to the client.

If the admin has enabled the *Always Cache When Canceled* option, caching of the product will occur even if the client cancels the product retrieval so that future requests will be serviced quickly.
Otherwise, caching is canceled if the user cancels the product download.

===== Product Download Status

As part of the caching of products, the Catalog Framework also posts events to the OSGi notification framework.
Information includes when the product download started, whether the download is retrying or failed (after the number of retrieval attempts configured for product caching has been exhausted), and when the download completes.
These events are retrieved by the Search UI and presented to the user who initiated the download.


===== Notifications and Activities

====== Notifications

Currently, the notifications provide information about product retrieval only.
For example, in the ${branding} Search UI, after a user initiates a resource download, they receive notifications when the download completed, failed, canceled, or is being retried.

====== Activities

Activities can be enabled by selecting "Show tasks" in the Standard Search UI configuration.
Activity events include the status and progress of actions that are being performed by the user, such as searches and downloads.
A list of all activities opens in a drop-down menu, from which activities can be read and deleted.
If a download activity is being performed, the Activity drop-down menu provides the link to retrieve the product.
If caching is enabled, a progress bar is displayed in the Activity (Product Retrieval) drop-down menu until the action being performed is complete.

==== Integrating with the Asynchronous Capabilities Endpoint

The following section shows examples of integration.
The channels are used for clients to subscribe, followed by examples of request and responses.
There is only one endpoint hosted at `<${branding}_IP>:<${branding}_PORT_NUMBER>/search/cometd`

===== [[asynchronous_search_subscribing]]Subscribing to Notifications

====== Notifications Overview

Notifications are messages that are sent to clients to inform them of some significant event happening.
Clients must subscribe to a notification channel to receive these messages.

====== Usage

[NOTE]
====
The ${branding} Search UI serves as a reference implementation of how clients can use
notifications.
====

Notifications are currently being utilized in the Catalog application for resource retrieval.
When a user initiates a resource retrieval, the channel `/ddf/notification/catalog/downloads` is opened, where notifications indicating the progress of that resource download are sent.
Any client interested in receiving these progress notifications must subscribe to that channel.
${branding} starts downloading the resource to the client that requested it, a notification with a status of "Started" will be broadcast.
If the resource download fails, a notification with a status of "Failed" will be broadcast.
Or, if the resource download is being attempted again after a failure, "Retry" will be broadcast.
When a notification is received, ${branding} Search UI displays a popup containing the contents of the notification, so a user is made aware of how their downloads are proceeding.
Behind the scenes, the ${branding} Search UI invokes the REST endpoint to retrieve a resource.
In this request, it adds the query parameter "user" with the CometD session ID or the unique User ID as the value.
This allows the CometD server to know which subscriber is interested in the notification.
For example, `http://${branding}_HOST:8181/services/catalog/sources/${branding-lowercase}.
distribution/2f5db9e5131444279a1293c541c106cd?
transform=resource&user=1w1qlo79j6tscii19jszwp9s2i55` notifications contain the
following information:

[cols="1m,3,1" options="header"]
|===
|Parameter Name
|Description
|Required by ${branding} Search UI

|application
|"Downloads" for resource retrieval. This is used as a "type" or category of messages.
|Yes

|title
|Resource/file name for resource retrieval.
|Yes

|message
|Human-readable message containing status and a more detailed message.
|Yes

|timestamp
|Timestamp in milliseconds of when event occurs.
|Yes

|user
|CometD Session ID or unique User ID.
|Yes

|status
|Status of event.
|No

|option
|Resource retrieval option.
|No

|bytes
|Number of bytes transmitted.
|No

|===

===== Receive Notifications

* If interested in retrieve resource notifications, a client must subscribe to the CometD channel `/ddf/notification/catalog/downloads`.
* If interested in all notification types, a client must subscribe to the CometD channel `/ddf/notification/\*\*`
* A client will only receive notifications for resources they have requested.
* Standard UI is subscribed to all notifications of interest to that user/browser session: `/ddf/notification/\*\*`
* See the Usage section for the data that a notification contains.

===== Notification Events

Notifications are messages that are sent to clients to inform them of some significant event
happening. Clients must subscribe to a notification channel to receive these messages.

====== Notifications Channel

/*TODO: fix subscribe link*/
To receive all notifications, subscribe to `/ddf/notifications/\*\*`

====== Notification Message Format

Notifications follow a specific format when they are published to the notifications channel.
This message contains a data map that encapsulates the notification information.

[cols="1m,3,1,5,5" options="header"]
|===
|Map Key
|Description
|Value Type
|Possible Values
|Example Values

|application
|Name of the application that caused the notification to be sent
|String
|Any (Downloads is the only application currently implemented)
|"Downloads"

|id
|ID of the notification "thread" – Notifications about the same event should use the same id to allow clients to filter out notifications that may be outdated.
|String
|Any
|"27ec3222af1144ff827a351b1962a236"

|message
|User-readable message that explains the notification
|String
|Any
|"The requested product was retrieved successfully and is available for download. "

|timestamp
|Time that the notification was sent
|String
|Positive long value (seconds since unix epoch)
|"1403734355420"

|title
|User-readable title for the notification
|String
|Any String
|"Product retrieval successful"

|user
|User who the notification relates to
|String
|Any String
|"admin"

|===

.Example: Notification Message
[source,json,linenums]
----
"data": {
	"application": "Downloads",
	"title": "Product retrieval successful",
	"message": "The requested product was retrieved successfully
		and is available for download.",
	"id": "27ec3222af1144ff827a351b1962a236",
	"timestamp": "1403734355420",
	"user": "admin"
}
----

==== Notification Operations

===== Notification Operations Channel

A notification operation is performed by publishing a list of commands to the CometD endpoint at `/notification/action`

.Operation Format
[cols="1m,2,1,1,2,2" options="header"]
|===
|Map Key
|Description
|Value Type
|Possible Values
|Example Values
|Comments

|action
|Type of action to request
|String
|Any
|"remove" (Currently only used action)
|If a client publishes with the `remove` action, it removes the notification with the given id from the persistence store.

|id
|ID of the notification to which the action relates
|String
|Any
|"27ec3222af1144ff827a351b1962a236"
|This is the id of the notification

|===

.Example: Notification Operation Request
[source,json,linenums]
----
"data": [ {
	"action": "remove",
 	"id": "27ec3222af1144ff827a351b1962a236"
} ]
----

==== Activity Events

===== Activity Events Channel

To receive all activity updates, follow the instructions at <<asynchronous_search_subscribing, Subscribing to Notifications>> and subscribe to `/ddf/activities/\*\*`

===== Activity Format

Activity update messages follow a specific format when they are published to the activities channel.
These messages contain a data map that encapsulates the activity information.

[cols="1m,3,1,1,1" options="header"]
|===
|Map Key
|Description
|Value Type
|Possible Values
|Example Values

|category
|Category of the activity
|String
|Any String
|"Product Retrieval"

|id
|ID that uniquely identifies the activity that sent out the update. Not required
to be unique per update.
|String
|Any String
|"b72ccdf6-8ca7-4f53-a0f6-b0ad264393b0"

|message
|User-readable message that explains the current activity status
|String
|Any String
|"Resource retrieval downloading."

|operations
|Map of operations that can be performed on this activity
|JSON Map
|A map of keys with populated values (that evaluate to 'true' rather than 'null' 'undefined' or 'false') These operations and their values can be used by clients to communicate back to the server by sending a message back on the same channel.

If the value is a URL, the client should invoke the URL as a result of the user invoking the activity operation.

a|
[source,json,linenums]
----
"operations" : {
	"download" : "http://example.com/product"
}
----

If the value is not a URL, the client should send a message back to the server on the same topic with the operation name.

Note: the ${ddf-branding} UI will interpret several values with special icons:
* `download`
* `retry`
* `cancel`
* `pause`
* `remove`
* `resume`

|progress
|Percentage value of activity completion
|String
|Integer between 0 - 100 followed by a %
|"45%"

|status
|Enumerated value that displays the current state of the activity
|String
a|
* `STARTED`,
* `RUNNING`,
* `FINISHED`,
* `STOPPED`,
* `PAUSED`, or
* `FAILED`
|`RUNNING`

|timestamp
|Time that the activity update was sent
|String
|Positive long value (seconds
since unix epoch)
|`1403801920875`

|title
|User-readable title for the activity update
|String
|Any String
|"Download Complete"

|subject
|User who started the activity
|String
|Any String
|"admin"

|bytes
|Number of bytes the activity consumed (upload or download)
|Integer
|Any Integer
|11

|session
|The session ID of the user/subject
|String
|Any String
|"6q2lfmmwh9dwv1c4gevboyp297"

|Custom Value
|Additional keys can be inserted by the component sending the activity notification
|Any JSON Type
|Any JSON
|"{}"

|===

.Example: Activity update with custom 'bytes' field
[source,json,linenums]
----
data: {
 	"category": "Product Retrieval",
 	"event.topics": "ddf/activities/broadcast",
 	"id": "a62f6666-fc41-4a19-91f1-485e73a564b5",
 	"message": "The requested product is being retrieved.
		Standby.",
 	"operations": {
 		"cancel" : true
	},
 	"progress": "",
	"status": "RUNNING",
	"timestamp": "1403801920875",
 	"title": "Product downloading",
 	"user": "admin",
 	"bytes": 635084800
}
----

==== Activity Operations

===== Channel

An activity operation is published to the channel `/service/action`

.Activity Format
[cols="1m,2,1,1,2,2" options="header"]
|===
|Map Key
|Description
|Value Type
|Possible Values
|Example Values
|Comments

|action
|Requested action
|String
|Any String.
a|Common values are

* "download",
* "retry",
* "cancel",
* "pause",
* "remove",
* "resume"
* "cancel"

|Based on the operations map that comes in from an activity event.

|id
|ID of the activity
|String
|Any String
|"a62f6666-fc41-4a19-91f1-485e73a564b5"
|The Activity ID to which the requested operation relates
|===

.Example: Activity Operation Request Message
[source,json,linenums]
----
"data": [ {
	"action":"cancel",
 	"id":"a62f6666-fc41-4a19-91f1-485e73a564b5"
} ]
----

==== Query Service

===== Query Service Channel

All query requests should be published to the `/service/query` channel.

===== Query Request Format

When performing a CometD publish command, the data being published must be valid json with 'data' being the key to a map that contains the following values:

[cols="1m,3,1,1,1,1" options="header"]
|===
|Map Key
|Description
|Value Type
|Possible Search UI Values
|Example Values
|Comments

|count
|Number of entries to return in the response
|Number
|Positive integer
|250
|

|format
|Format that the results should be displayed in
|String
|"geojson"
|"geojson"
|"geojson" is the recommended format to use

|id
|
|String
|
|"4303ba5d-21af-4878-9a4c-808e80052e6c"
|

|src
|Comma-delimited list of federated sites to search over
|String
|Any
|list of site names.
|"${ddf-branding}-OS,${ddf-branding-lowercase}.distribution"

|start
|Specifies the number of the first result that should be returned
|Number
|Positive integer
|1
10 would mean the 10th result from the query would be returned as the first one in the response.

|cql
|Search Filter
|String
|OGC CQL formatted string
|"anyText LIKE '*'"
|See http://www.opengeospatial.org/standards/cat[OpenGIS® Catalogue Services Specification] for more details.
|===

====== Query Request Examples

.Enterprise Contextual
[source,json,linenums]
----
"data": {
	"count": 250,
 	"format": "geojson",
 	"id": "4303ba5d-21af-4878-9a4c-808e80052e6c",
 	"cql": "anyText LIKE '*'",
 	"src": "${ddf-branding}-OS,${ddf-branding-lowercase}.distribution",
 	"start": 1
}
----

.Multiple Site Temporal Absolute
[source,json,linenums]
----
"data": {
	"count": 250,
	"format": "geojson",
	"id": "4303ba5d-21af-4878-9a4c-808e80052e6c",
	"cql": "modified DURING 2014-09-01T00:00:00Z/2014-09-30T00:00:00Z",
 	"src": "${ddf-branding}-OS,${ddf-branding-lowercase}.distribution",
 	"start": 1,
}
----

.Enterprise Spatial Bounding Box
[source,json,linenums]
----
"data": {
	"count": 250,
	"format": "geojson",
	"id": "4303ba5d-21af-4878-9a4c-808e80052e6c",
	"cql": "INTERSECTS(anyGeo, POLYGON ((-112.7786 32.2159, -112.7786 45.6441, -83.7297 45.6441, -83.7297 32.2159, -112.7786 32.2159)))",
	"start": 1
}
----

==== Query Responses

===== Query Response Channel

The query responses are returned on the `/<id>` channel, which should be subscribed to in order to retrieve the results.
Replace `<id>` with the id that was used in the request.
The <<<<asynchronous_search_subscribing, Subscribing to Notifications>>>> section details how to subscribe to a CometD channel.

===== Query Response Message Format

The response is returned as a data map that contains an internal map with the following keys:

[cols="1m,3,1,1,1" options="header"]
|===
|Map Key
|Description
|Value Type
|Possible Values
|Example Values

|id
|ID that corresponds to the request
|String
|ID value
|

|hits
|Total number of query hits that were found by the server
|Number
|Integer >= 0
|This contains the total amount of items that were found by the query. Depending on the 'count' in the request, not all of the results may be returned.

|results
|Array of metacard results
|Array of Maps
|GeoJson-formatted value
|This format is defined by the GeoJSON Metacard Transformer.

|results/metacard/properties/resource.cached
|A property indicating whether a metacard's associated resource is cached
|Boolean
|true, false
|true, false

|results/metacard/actions
|An array of actions that applies to each metacard, injected into each metacard
|Array of Maps
|Array of objects, possibly empty if no actions are available
|Each Action will contain an id, title, description, and url

|status
|Array of status for each source queried
|Array
|
|

|status.state
|Specifies the state of the query
|String
|SUCCEEDED, FAILED, ACTIVE
|

|status.elapsed
|Time in milliseconds that it took for the source to complete the request
|Number
|Integer >= 0
|

|status.hits
|Number of records that were found on the source that matched the query
|Number
|Integer >= 0
|

|status.id
|ID of the federated source
|String
|Any string value
|

|status.results
|Number of results that were returned in this response from the source
|Number
|Integer >= 0
|

|types
|A Map mapping a metacard-type's name to a map about that metacard-type. Only metacard-types represented by the metacards returned in the query are represented.
|Map of Maps
|
|The Map defining a particular `metacard-type` maps the fields supported by that `metacardtype` to the datatype for that particular field.
|===

====== Query Response Examples

.Example Query Response
[source,json,xml]
----
{
    "data": {
        "hits": 1,
        "metacard-types": {
            "ddf.metacard": {...}
        },
        "id": "857f76c0-da8c-72f5-09cd-536b69e427af",
        "results": [
           {
                "metacard": {
                    "cached": "2016-06-09T22:46:57.258+0000",
                    "geometry": {
                        "coordinates": [
                            -97.03125,
                            35.173808
                        ],
                        "type": "Point"
                    },
                    "type": "Feature",
                    "actions": [ ... ],
                    "properties": {
                        "thumbnail": "..."
                        "metadata": "<?xml version=\"1.0\" encoding=\"UTF-8\"?><metadata> ... </metadata>",
                        "resource-size": "92314",
                        "created": "2016-06-09T22:46:37.707+0000",
                        "metacard-tags": [
                            "resource"
                        ],
                        "resource-uri": "content:1a83781dd56a4050afc420016d078e22",
                        "checksum-algorithm": "Adler32",
                        "metadata-content-type": "image/jpeg",
                        "metacard-type": "ddf.metacard",
                        "title": "fixTheBugs_geotagged.jpg",
                        "resource-download-url": "${secure_url}services/catalog/sources/ddf.distribution/1a83781dd56a4050afc420016d078e22?transform=resource",
                        "source-id": "ddf.distribution",
                        "effective": "2016-06-09T22:46:37.707+0000",
                        "point-of-contact": "",
                        "checksum": "edfa1836",
                        "modified": "2016-06-09T22:46:37.707+0000",
                        "id": "1a83781dd56a4050afc420016d078e22"
                    }
                }
            }
        ],
        "status": [
           {
                "hits": 1,
                "elapsed": 432,
                "reasons": [],
                "id": "ddf.distribution",
                "state": "SUCCEEDED",
                "results": 1
            }
        ],
        "successful": true
    },
    "channel": "/857f76c0-da8c-72f5-09cd-536b69e427af"
}
----
