{branding} is a free and open-source common data layer that abstracts services and business logic from the underlying data structures to enable rapid integration of new data sources.

Licensed under http://www.gnu.org/licenses/gpl.html[LGPL], {branding} is an interoperability platform that provides secure and scalable discovery and retrieval from a wide array of disparate sources.
{branding} is built to "unzip and run" while having the ability to scale to large enterprise systems.

Distributed Data Framework ({branding}) is an agile and modular integration framework.
It is primarily focused on data integration, enabling clients to insert, query and transform information from disparate data sources via the {branding} Catalog.
A Catalog API allows integrators to insert new capabilities at various stages throughout each operation.

{branding} is designed with the following architectural qualities to benefit integrators.

* Standardization
** Building on established Free and Open Source Software (FOSS) and open standards avoids vendor lock-in.
* Extensibility
** System Integrators can extend capabilities by developing and sharing new features.
** Built on top of http://karaf.apache.org/[Apache Karaf] for OSGi support.
** http://camel.apache.org/[Apache Camel] and http://cxf.apache.org/[Apache CXF] integration.
* Flexibility
** System Integrators may deploy only those features required.
* Simplicity of installation and operation.
** Unzip and run.
** Configuration via a modern {admin-console}.
* Simplicity of Development
** Build simple Plain Old Java Objects (POJOs) and wire them in via a choice of dependency injection frameworks
** Make use of widely available documentation and components for {branding}'s underlying technologies
** Modular development supports multi-organizational and multi-regional teams.
* Federated Open Geospatial Consortium (OGC) Filter-powered Metadata Catalog
** Enterprise Service Bus (ESB) performs transformation between query standards.
** Apache Solr integration.
*** Well Known Text (WKT) indexing and search for spatial awareness
*** Full text search
*** XPath searches
*** XML indexing
** Open Geospatial Consortium (OGC) KML, CSW, and WFS federated services
** OpenSearch federated services.
** REST API for catalog operations.
** Integrated content framework to store actual products associated with the indexed metadata.
** Tika parser for extracting metadata from products.
** Plugin support for pre and post processing on all operations.
** Eventing for notifications
** Metrics
* Security
** Web Security Service (WSS) functionality that comes with DDF is integrated throughout the system.
*** SAML 2.0 Web Browser SSO Profile with included IdP server and client.
*** SAML Security Token Service (STS) based on WS-Trust.
*** Automatic protection and Single Sign On (SSO) for web applications without modifying the application itself.
*** Extensible Java/XACML PDP for authorization decisions.
*** LDAP integration
**** Included OSGi enabled OpenDJ LDAP server.
*** CAS integration
*** X.509 authentication
*** Basic authentication
*** SAML authentication
*** Guest login support
*** Multiple realm login support to mix and match different authentication types and services between endpoints.
*** WS-Security, WS-SecurityPolicy, WS-Policy, WS-Trust, WS-SecureConversation, WS-Addressing
** Provides a Security Framework (a set of APIs that define the integration with the DDF framework).
** Provides Security Service reference implementations for a realistic end-to-end use case.
** Role and Attribute based access control.
** Attribute based filtering for searches performed throughout the system.
** Federated identity through metadata catalog.
* Search User Interface
** 3D WebGL map built off of Cesium.
** 2D map built off of OpenLayers 3.
** USNG/MGRS grid support.
** GeoNames geocoder integrated into both maps.
** CometD integration for push notifications.
** Upload and edit capability.
** Saved workspaces (searches and metadata artifacts).
* Admin Web User Interface
** Web based install wizard.
** Application grid to organize configurations.
** Pluggable configuration pages for applications to simplify configurations for complex scenarios.
** Metrics web application to view up to date system metrics.

More information about {branding} is located at: https://tools.codice.org/wiki/display/{branding}[{branding} Home].

=== Applications

{branding} is comprised of several modular applications, to be installed or uninstalled as needed.

{branding} Administrative Application::
The administrative application enhances administrative capabilities when installing and managing {branding}. It contains various services and interfaces that allow administrators more control over their systems.
{branding} Catalog Application::
The {branding} Catalog provides a framework for storing, searching, processing, and transforming information.
Clients typically perform query, create, read, update, and delete (QCRUD) operations against the Catalog.
At the core of the Catalog functionality is the *Catalog Framework*, which routes all requests and responses through the system, invoking additional processing per the system configuration.
{branding} Content Application::
The {branding} Content application provides a framework for storing, reading, processing, transforming and cataloging data.
{branding} Platform Application::
The Platform application is considered to be a core application of the distribution. The Platform application has fundamental building blocks that the distribution needs to run. +
These building blocks include subsets of: http://karaf.apache.org/[Karaf], http://cxf.apache.org/[CXF], http://karaf.apache.org/index/subprojects/cellar.html[Cellar], and http://camel.apache.org/[Camel]. +
Included as part of the Platform application is also a Command Scheduler.
The Command Scheduler allows users to schedule Command Line Shell Commands to run at certain specified intervals.

{branding} Security Application::
The Security application provides authentication, authorization, and auditing services for the {branding}. They comprise both a framework that developers and integrators can extend and a reference implementation that meets security requirements. More information about the security framework and how everything works as a single security solution can be found on the Managing Web Service Security page.
{branding} Solr Catalog Application::
The Solr Catalog Provider (SCP) is an implementation of the `CatalogProvider` interface using Apache Solr (http://lucene.apache.org/solr/) as a data store.
{branding} Spatial Application::
The {branding} Spatial Application provides KML transformer and a KML network link endpoint that allows a user to generate a View-based KML Query Results Network Link.
{branding} Standard Search UI::
The {branding} Standard Search UI application allows a user to search for records in the local Catalog (provider) and federated sources.
Results of the search are returned in HTML format and are displayed on a globe, providing a visual representation of where the records were found.

