${ddf-branding-expanded} (${branding}) is a free and open-source common data layer that abstracts services and business logic from the underlying data structures to enable rapid integration of new data sources.

Licensed under http://www.gnu.org/licenses/gpl.html[LGPL], ${ddf-branding} is an interoperability platform that provides secure and scalable discovery and retrieval from a wide array of disparate sources.

${ddf-branding} is:

* a flexible and modular integration framework.
* built to "unzip and run" while having the ability to scale to large enterprise systems.
* primarily focused on data integration, enabling clients to insert, query, and transform information from disparate data sources via the ${ddf-branding} Catalog.

== Applications

${branding} is comprised of several modular applications, to be installed or uninstalled as needed.

${ddf-branding} Administrative Application::
The administrative application enhances administrative capabilities when installing and managing ${branding}. It contains various services and interfaces that allow administrators more control over their systems.

${ddf-branding} Catalog Application::
The ${branding} Catalog provides a framework for storing, searching, processing, and transforming information.
Clients typically perform local and/or federated query, create, read, update, and delete (QCRUD) operations against the Catalog.
At the core of the Catalog functionality is the *Catalog Framework*, which routes all requests and responses through the system, invoking additional processing per the system configuration.

${ddf-branding} Platform Application::
The Platform application is considered to be a core application of the distribution.
The Platform application has fundamental building blocks that the distribution needs to run.

${ddf-branding} Security Application::
The Security application provides authentication, authorization, and auditing services for the ${branding}.
It is both a framework that developers and integrators can extend and a reference implementation that meets security requirements.

${ddf-branding} Solr Catalog Application::
The Solr Catalog Provider (SCP) is an implementation of the `CatalogProvider` interface using http://lucene.apache.org/solr/[Apache Solr] as a data store.

${ddf-branding} Spatial Application::
The ${ddf-branding} Spatial Application provides KML transformer and a KML network link endpoint that allows a user to generate a View-based KML Query Results Network Link.

${ddf-branding} Standard Search UI::
The ${ddf-branding} Standard Search UI application allows a user to search for records in the local Catalog (provider) and federated sources.
Results of the search are returned and displayed on a globe or map, providing a visual representation of where the records were found.

== Understanding Metadata and Metacards

Metadata is information about a resource, organized into a schema to make it possible to search against.
The ${ddf-catalog} stores this metadata and allows access to it. If desired, the ${ddf-content} application can be installed to store the resources themselves.
Metacards are single instances of metadata, representing a single record, in the Metadata Catalog (MDC).
Metacards follow one of several schemas to ensure reliable, accurate, and complete metadata.
Essentially, Metacards function as containers of metadata.

=== Populating Metacards (during ingest)

Upon ingest, a metacard transformer will read the data from the ingested file and populate the fields of the metacard.
Exactly how this is accomplished depends on the origin of the data, but most fields (except id) are imported directly.

=== Searching Metadata

${branding} provides the capability to search the Metadata Catalog (MDC) for metadata.
There are a number of different types of searches that can be performed on the MDC, and these searches are accessed using one of several interfaces.
This section provides a very high level overview of introductory concepts of searching with ${branding}.
These concepts are expanded upon in later sections.

==== Search Types

There are four basic types of metadata search.
Additionally, any of the types can be combined to create a compound search.

===== Contextual Search

A contextual search is used when searching for textual information.
It is similar to a Google search over the metadata contained in the MDC.
Contextual searches may use wildcards, logical operators, and approximate matches.

===== Spatial Search

A spatial search is used for Area of Interest (AOI) searches.
Polygon and point radius searches are supported.
Specifically, the spatial search looks at the metacards' location attribute and coordinates are specified in *WGS 84* decimal degrees.

===== Temporal Search

A temporal search finds information from a specific time range.
Two types of temporal searches are supported: _relative_ and _absolute_.
Relative searches contain an offset from the current time, while absolute searches contain a start and an end timestamp.
Temporal searches can look at the effective date attribute or the modified date.

===== Datatype

A datatype search is used to search for metadata based on the datatype, and optional versions.
Wildcards (*) can be used in both the datatype and version fields.
Metadata that matches any of the datatypes (and associated versions if specified) will be returned.
If a version is not specified, then all metadata records for the specified datatype(s) regardless of version will be returned.

==== Compound Search

These search types may be combined to create Compound searches.
For example, a Contextual and Spatial search could be combined into one Compound search to search for certain text in metadata in a particular region of the world.
