
=== Getting Started

This quick tutorial will enable install, configuring and using a basic instance of {branding}.

These steps will demonstrate:

- [*] Prerequisites
- [*] Installation
- [*] Catalog Capabilities: Ingest and query using every endpoint
- [*] Use of the Content Framework
- [*] Metrics Reporting

==== Prerequisites

* Install/Upgrade to Java 8 http://www.oracle.com/technetwork/java/javase/downloads/index.html[J2SE 8 SDK]
* Supported platforms are *NIX - Unix/Linux/OSX, Solaris, and Windows.
* http://www.oracle.com/technetwork/java/javase/downloads/index.html[JDK8] must be installed.
* The `JAVA_HOME` environment variable must be set to the location where the JDK is installed.

.Example of Setting Up on *NIX
----
JAVA_HOME=/usr/java/jdk1.8.0
export JAVA_HOME
----

.Example of Setting Up JAVA_HOME on Windows
----
set JAVA_HOME=C:\Program Files\Java\jdk1.8.0
----

.*NIX
[WARNING]
====
Unlink `/usr/bin/java` if it is already linked to a previous version of the JRE:
`unlink /usr/bin/java`
====

[TIP]
====
Verify that the JAVA_HOME was set correctly.

.*NIX
----
echo $JAVA_HOME
----

.Windows
----
echo %JAVA_HOME%
----
====

* {branding} installation zip file.
* A web browser.
* For Linux systems, increase the file descriptor limit by editing `/etc/sysctl.conf` to include or change the following:

.File Descriptor Limit
----
fs.file-max = 6815744
----

.Restart
[WARNING]
====
For the change to take effect, a restart is required.
====

.Restart Command
----
init 6
----

==== Installing {branding}

. Install {branding} by unzipping the https://github.com/codice/ddf/releases/latest[zip file].
. This will create an installation directory, which is typically created with the name and version of the application.
This installation directory will be referred to as `<DISTRIBUTION_INSTALL_DIR>`.
(Substitute the actual directory name.)
. Start {branding} by running the `<DISTRIBUTION_INSTALL_DIR>/bin/ddf` script (or `ddf.bat` on Windows).

==== Configuring

.. Go to https://localhost:8993/admin.
.. Enter the default username of "admin" (no quotes) and the password of "admin" (no quotes).
.. Follow the prompts installer prompts for a standard installation.
... Click start to begin the setup process.
... Configure guest claims attributes or use defaults.
... Select Standard Installation.
... On the System Configuration page, configure any port or protocal changes desired and add any keystores/truststores needed.
... Click *Finish*

==== Catalog Capabilities

. Create an entry in the Catalog by ingesting a valid https://codice.atlassian.net/wiki/download/attachments/1179756/geojson_valid.json?version=1&modificationDate=1368249436010&api=v2[GeoJson file].
// Should this be rewritten to use Search UI to ingest? or should that be added?This ingest can be performed using:
* A REST client, such as Google Chrome's Advanced REST Client. OR
* Using the following curl command to POST to the Catalog REST CRUD endpoint.
+
.Windows Example
----
curl -H "Content-type: application/json;id=geojson" -i -X POST -d @"C:\path\to\geojson_valid.json" https://localhost:8993/services/catalog
----
+
.*NIX Example
----
curl -H "Content-type: application/json;id=geojson" -i -X POST -d @geojson_valid.json https://localhost:8993/services/catalog
----
+
Where:
*-H* adds an HTTP header. In this case, Content-type header `application/json;id=geojson` is added to match the data being sent in the request.
*-i* requests that HTTP headers are displayed in the response.
*-X* specifies the type of HTTP operation. For this example, it is necessary to POST (ingest) data to the server.
*-d* specifies the data sent in the POST request. The `@` character is necessary to specify that the data is a file.
+
The last parameter is the URL of the server that will receive the data.
+
This should return a response similar to the following (the actual catalog ID in the id and Location URL fields will be different):
+
.Sample Response
[source,http,linenums]
----
HTTP/1.1 201 Created
Content-Length: 0
Date: Mon, 22 Apr 2013 22:02:22 GMT
id: 44dc84da101c4f9d9f751e38d9c4d97b
Location: https://localhost:8993/services/catalog/44dc84da101c4f9d9f751e38d9c4d97b
Server: Jetty(7.5.4.v20111024)
----
+
. Verify the entry was successfully ingested by entering in a browser the URL returned in the POST response's HTTP header. For instance in our example, it was `/services/catalog/44dc84da101c4f9d9f751e38d9c4d97b`. This should display the catalog entry in XML within the browser.
. Verify the catalog entry exists by executing a query via the OpenSearch endpoint.
. Enter the following URL in a browser /services/catalog/query?q=ddf. A single result, in Atom format, should be returned.

==== Using the Content Framework Directory Monitor

Using the Content framework's directory monitor, ingest a file so that it is stored in the content repository with a metacard created and inserted into the Catalog.

. In the {admin-console}, select the *{branding} Content* application tile.
. Select *Configuration* tab.
. Select the *Content Directory Monitor*.
. Set the directory path to `inbox`.
. Set *Processing Directive* to `Store and Process` (default).
. Click the *Save* button.
. Copy the attached https://codice.atlassian.net/wiki/download/attachments/1179756/geojson_valid.json?version=1&modificationDate=1368249436010&api=v2[geojson file] to the `<DISTRIBUTION_INSTALL_DIR>/inbox` directory.
+
The Content Framework will:
+
.. ingest the file,
.. store it in the content repository at `<DISTRIBUTION_INSTALL_DIR>/content/store/<GUID>/geojson_valid.json`,
.. look up the GeoJson Input Transformer based on the mime type of the ingested file,
.. create a metacard based on the metadata parsed from the ingested GeoJson file, and
.. insert the metacard into the Catalog using the `CatalogFramework`.
+
Note that XML metadata for text searching is not automatically generated from GeoJson fields.

===== Verifying Ingest

. Verify GeoJson file was stored using the Content REST endpoint.
.. Send a GET command to read the content from the content repository using the Content REST endpoint. This can be done using `cURL` command below. Note that the GUID will be different for each ingest. The GUID can be determined by going to the `<DISTRIBUTION_INSTALL_DIR>/content/store` directory and copying the sub-directory in this folder (there should only be one).

.Windows Example
[source,terminal]
----
curl -X GET https://localhost:8993/services/content/c90147bf86294d46a9d35ebbd44992c5
----

.*NIX Example
[source,terminal]
----
curl -X GET https://localhost:8993/services/content/c90147bf86294d46a9d35ebbd44992c5
----

The response to the GET command will be the contents of the `geojson_valid.json` file originally ingested.
