
=== Troubleshooting ${branding}
////
Troubleshooting
////

.General Troubleshooting
// Do any of these still exist?
[cols="3a,7a" options="header"]
|===

|Issue
|Solution

|Ingest more than 200,000 data files stored NFS shares may cause Java Heap Space error (Linux-only issue).
|This is an NFS bug where it creates duplicate entries for some files when doing a file list.  Depend on the OS, some Linux machines can handle the bug better and able get a list of files but get an incorrect number of files. Others would have a Java Heap Space error because there are too many file to list.

|Ingest millions of complicated data into Solr can cause Java heap space error.
|Complicated data has spatial types and large text.

|Ingest serialized data file with scientific notation in WKT string causes RuntimeException.
|WKT string with scientific notation such as POINT (-34.8932113039107 -4.77974239601E-5) won't ingest. This occurs with serialized data format only.

|Exception Starting ${branding} (Windows)

An exception is sometimes thrown starting ${branding} on a Windows machine (x86).

If using an unsupported terminal, `java.lang.NoClassDefFoundError: Could not initialize class org.fusesource.jansi.internal.Kernel32` is thrown.

|Install missing Windows libraries.

Some Windows platforms are missing libraries that are required by ${branding}.  These libraries are provided by the http://www.microsoft.com/en-us/download/details.aspx?id=15336[Microsoft Visual C++ 2008 Redistributable Package x64].

|CXF BusException

The following exception is thrown:
`org.apache.cxf.BusException: No conduit initiator`

|Restart ${branding}.
. Shut down ${branding}: +
`${branding-lowercase}${at-symbol}local>shutdown`
. Start up ${branding}:
`./${branding-lowercase}`

|Distribution Will Not Start

${branding} will not start when calling the start script defined during installation.
|Complete the following procedure.

. Verify that Java is correctly installed.
+
`java -version`
. This should return something similar to:
+
`java version "1.8.0_45" Java(TM) SE Runtime Environment (build 1.8.0_45-b14) Java HotSpot(TM) Server VM (build 25.45-b02, mixed mode)`
. If running *nix, verify that bash is installed.
+
`echo $SHELL`
. This should return:
+
`/bin/bash`

a|${branding} Is Unresponsive to Incoming Requests

An example of the log file when this problem is encountered:

----
Feb 7, 2013 10:51:33 AM org.apache.karaf.main.SimpleFileLock lock
INFO: locking
Feb 7, 2013 10:51:33 AM org.apache.karaf.main.Main doLock
INFO: Waiting for the lock ...
Feb 7, 2013 10:51:33 AM org.apache.karaf.main.SimpleFileLock lock
INFO: locking
Feb 7, 2013 10:51:33 AM org.apache.karaf.main.Main doLock
INFO: Waiting for the lock ...
Feb 7, 2013 10:51:34 AM org.apache.karaf.main.SimpleFileLock lock
INFO: locking
Feb 7, 2013 10:51:34 AM org.apache.karaf.main.SimpleFileLock lock
INFO: locking
Feb 7, 2013 10:51:35 AM org.apache.karaf.main.SimpleFileLock lock
INFO: locking
Feb 7, 2013 10:51:35 AM org.apache.karaf.main.SimpleFileLock lock
INFO: locking
----

|

|Multiple `java.exe` processes running, indicating more than one ${branding} instance is running.

This can be caused when another ${branding} is not properly shut down.

a|Perform one or all of the following recommended solutions, as necessary.

* Wait for proper shutdown of ${branding} prior to starting a new instance.
* Verify running java.exe are not ${branding} (e.g., kill/close if necessary).
* Utilize automated start/stop scripts to run ${branding} as a service.

|===
