
==== Catalog Fanout Framework 

The Fanout Catalog Framework (`fanout-catalogframework` bundle) provides an implementation of the Catalog Framework that acts as a proxy, federating requests to all available sources. 
All requests are executed as federated queries and resource retrievals, allowing the fanout site to be the sole site exposing the functionality of all of its Federated Sources.
The Fanout Catalog Framework is the implementation of the Fanout Catalog Framework.

The Fanout Catalog Framework provides the capability to configure ${branding} to be a fanout proxy to other federated sources within the enterprise.
The Fanout Catalog Framework has no catalog provider configured for it, so it does not allow catalog modifications to take place.
Therefore, create, update, and delete operations are not supported.

.Catalog Fanout Framework
[ditaa,query-flow,png, ${image-width}]
....
           /------\
           |Client|
           |cDEF  |
           \------/
              ^
              |
+-------------|------------------------------------------------------------\
|DDF          |                                                       cCCC |
|             v                                                            |
|         /--------\   /-----------------\   /-------------------\         |
|         |Endpoint|<->|Catalog Framework|<->|Federation Strategy|         |
|         | cDEF   |   | cDEF            |   | cDEF              |         |
|         \--------/   \-----------------/   \-------------------/         |
|                                                     ^ ^                  |
|                                                     | |                  |
|                                          /----------/ \---------\        |
|                                          |                      |        |
| +----------------------------------------|----------------------|------+ |
| |Enterprise Query c369                   v                      v      | |
| |+--------------------------------------------+ +---------------------+| |
| ||Local Query                                 | |Federated Query      || |
| ||/------------------\ /---------------------\| |/-------------------\|| |
| ||| Catalog Provider | | Connected Source(s) || ||Federated Source(s)||| |
| |||  cDEF            | |  cDEF               || || cDEF              ||| |
| ||\------------------/ \---------------------/| |\-------------------/|| |
| |+-------^----------------------^-------------+ +----^----------^-----+| |
| +--------|----------------------|--------------------|----------|------+ |
\----------|----------------------|--------------------|----------|--------/
           |                      |                    |          \-------------------\
           |                      |                    |                              |
           v                      v                    v                              v
/=-------------------\ /----------------------\ /---------=------------\     /----------------------\
|Internal Data Source| |External Data Source 1| |External Data Source 3| ... |External Data Source N|
\--------------------/ \--------------------=-/ \----------------------/     \-------=--------------/
....

In addition, the Fanout Catalog Framework provides the following benefits:

* Backwards compatibility (e.g., federating with older versions) with existing older versions of ${branding}.
* A single node being exposed from an enterprise, thus hiding the enterprise from an external client.
* Ensures all queries and resource retrievals are federated.

The Fanout Catalog Framework is a core class of ${branding} when configured as a fanout proxy.
It provides the methods for query and resource retrieval operations on the Sources, where all operations are enterprise-wide operations.
By contrast, the Standard Catalog Framework supports create/update/delete operations of metacards, in addition to the query and resource retrieval operations.

Use the Fanout Catalog Framework if:

* exposing a single node for enterprise access and hiding the details of the enterprise, such as federate source's names, is desired.
* access to individual federated sources is not required.
* access to a catalog provider to create, update, and delete metacards is not required.

The Fanout Catalog Framework also maintains a list of `ResourceReaders` for resource retrieval operations.
A resource reader is matched to the scheme (i.e., protocol, such as `file://`) in the URI of the resource specified in the request to be retrieved.

Site information about the fanout configuration can be retrieved using the Fanout Catalog Framework.
Site information includes the source's name, version, availability, and the list of unique content types currently stored in the source (e.g., NITF).
Details of the individual federated sources is not included, only the fanout catalog framework.

===== Installing the Fanout Catalog Framework

The Fanout Catalog Framework is bundled as the `catalog-core-fanoutframework` feature and can be installed and uninstalled using the normal processes described in Configuration.

[WARNING]
====
When this feature is installed, the Standard Catalog Framework feature `catalog-core-standardframework` should be uninstalled, as both catalog frameworks should not be installed simultaneously.
====

===== Configuring the Fanout Catalog Framework

The Fanout Catalog Framework can be configured using the normal processes described in Configuring ${branding}.

The configurable properties for the Fanout Catalog Framework are accessed from the Catalog Fanout Framework configuration in the Admin Console.

.Fanout Catalog Framework Configurable Properties
[cols="1,2,1,3,1,1" options="header"]
|===
|Title
|Property
|Type
|Description
|Default Value
|Required

|Default Timeout
(in milliseconds)
|`defaultTimeout`
|Integer
|The maximum amount of time to wait for a response from the Sources.
|60000
|yes

|Product Cache Directory
|`productCacheDirectory`
|String
|Directory where retrieved products will be cached for faster, future retrieval. If a directory path is specified with directories that do not exist, Catalog Framework will attempt to create those directories. Out of the box (without configuration), the product cache directory is `<INSTALL_DIR>/data/product-cache`. If a relative path is provided, it will be relative to the `<INSTALL_DIR>`.

It is recommended to enter an absolute directory path, such as `/opt/product-cache` in Linux or `C:\product-cache` in Windows.
|(empty)
|no

|Enable Product Caching
|`cacheEnabled`
|Boolean
|Check to enable caching of retrieved products to provide faster retrieval for subsequent requests for the same product.
|false
|no

|Delay (in seconds) between product retrieval retry attempts
|`delayBetweenRetryAttempts`
|Integer
|The time to wait (in seconds) between attempting to retry retrieving a product.
|10
|no

|Max product retrieval retry attempts
|`maxRetryAttempts`
|Integer
|The maximum number of attempts to retry retrieving a product.
|3
|no

|Caching Monitor Period
|`cachingMonitorPeriod`
|Integer
|How many seconds to wait and not receive product data before retrying to retrieve a product.
|5
|no

|Always Cache Product
|`cacheWhenCanceled`
|Boolean
|Check to enable caching of retrieved products, even if client cancels the download.
|false
|no

|===

[cols="2*" options="header"]
|===
|Managed Service PID
|`${ddf-branding}.catalog.impl.service.fanout.FanoutCatalogFramework`
|Managed Service Factory PID
|N/A
|===

.Catalog Fanout Framework Exported Services
[cols="3*" options="header"]
|===
|Registered Interface
|Service Property
|Value

|`${ddf-branding}.catalog.federation.FederationStrategy`
|shortname
|sorted

|`org.osgi.service.event.EventHandler`
|event.topics
|`${ddf-branding}/catalog/event/CREATED`, `${ddf-branding}/catalog/event/UPDATED`, `${ddf-branding}/catalog/event/DELETED`

|`${ddf-branding}.catalog.CatalogFramework`
|
|

|`${ddf-branding}.catalog.event.EventProcessor`
|
| 

|`${ddf-branding}.catalog.plugin.PostIngestPlugin`
|
|

|===

.Catalog Fanout Framework Imported Services
[cols="3*" options="header"]
|===

|Registered Interface
|Availability
|Multiple

|`${ddf-branding}.cache.CacheManager`
|
|false

|`${ddf-branding}.catalog.plugin.PostFederatedQueryPlugin`
|optional
|true

|`${ddf-branding}.catalog.plugin.PostIngestPlugin`
|optional
|true

|`${ddf-branding}.catalog.plugin.PostQueryPlugin`
|optional
|true

|`${ddf-branding}.catalog.plugin.PostResourcePlugin`
|optional
|true

|`${ddf-branding}.catalog.plugin.PreDeliveryPlugin`
|optional
|true

|`${ddf-branding}.catalog.plugin.PreFederatedQueryPlugin`
|optional
|true

|`${ddf-branding}.catalog.plugin.PreIngestPlugin`
|optional
|true

|`${ddf-branding}.catalog.plugin.PreQueryPlugin`
|optional
|true

|`${ddf-branding}.catalog.plugin.PreResourcePlugin`
|optional
|true

|`${ddf-branding}.catalog.plugin.PreSubscriptionPlugin`
|optional
|true

|`${ddf-branding}.catalog.plugin.PolicyPlugin`
|optional
|true

|`${ddf-branding}.catalog.plugin.AccessPlugin`
|optional
|true

|`${ddf-branding}.catalog.resource.ResourceReader`
|optional
|true

|`${ddf-branding}.catalog.source.ConnectedSource`
|optional
|true

|`${ddf-branding}.catalog.source.FederatedSource`
|optional
|true

|`org.osgi.service.event.EventAdmin`
| 
|false

|===

===== Known Issues with Catalog Fanout Framework

None.
