==== Developing Complementary Catalog Frameworks

${branding} and the underlying OSGi technology can serve as a robust infrastructure for developing frameworks that complement the ${ddf-catalog}.

===== Recommendations for Framework Development

. Provide extensibility similar to that of the ${ddf-catalog}.
.. Provide a stable API with interfaces and simple implementations (refer to `http://www.ibm.com/developerworks/websphere/techjournal/1007_charters/1007_charters.html`).
. Make use of the ${ddf-catalog} wherever possible to store, search, and transform information.
. Utilize OSGi standards wherever possible.
.. ConfigurationAdmin
.. MetaType
. Utilize the sub-frameworks available in ${branding}.
.. Karaf
.. CXF
.. PAX Web and Jetty

===== Implementing Catalog Methods

.Query Response Transform Example
[source,java,linenums]
----
// inject CatalogFramework instance or retrieve an instance
private CatalogFramework catalogFramework;

public RSSEndpoint(CatalogFramework catalogFramework)
{
     this.catalogFramework = catalogFramework ;
     // implementation
}

 // Other implementation details ...

private void convert(QueryResponse queryResponse ) {
    // ...
    String transformerId = "rss";

    BinaryContent content = catalogFramework.transform(queryResponse, transformerId, null);

    // ...

}
----

[cols="2,5" options="header"]
|===
|Line #
|Action
|4
|`CatalogFramework` is injected, possibly by dependency injection framework.

|16
|`queryResponse` is transformed into the RSS format, which is stored in the `BinaryContent` instance
|===

==== Dependency Injection
Using Blueprint or another injection framework, transformers can be injected from the OSGi Service Registry.

.Blueprint Service Reference
[source,xml]
----
<reference id="[[Reference Id]]" interface="${ddf-branding}.catalog.transform.[[Transformer Interface Name]]" filter="(shortname=[[Transformer Identifier]])" />
----

Each transformer has one or more `transform` methods that can be used to get the desired output.

.Input Transformer Example
[source,java,linenums]
----
${ddf-branding}.catalog.transform.InputTransformer inputTransformer = retrieveInjectedInstance() ;

Metacard entry = inputTransformer.transform(messageInputStream);
----

.Metacard Transformer Example
[source,java,linenums]
----
${ddf-branding}.catalog.transform.MetacardTransformer metacardTransformer = retrieveInjectedInstance() ;

BinaryContent content = metacardTransformer.transform(metacard, arguments);
----

.Query Response Transformer Example
[source,java,linenums]
----
${ddf-branding}.catalog.transform.QueryResponseTransformer queryResponseTransformer = retrieveInjectedInstance() ;

BinaryContent content = queryResponseTransformer.transform(sourceSesponse, arguments);
----

==== OSGi Service Registry

[IMPORTANT]
====
In the vast majority of cases, working with the OSGi Service Reference directly should be avoided.
Instead, dependencies should be injected via a dependency injection framework like Blueprint.
====

Transformers are registered with the OSGi Service Registry.
Using a `BundleContext` and a filter, references to a registered service can be retrieved.

.OSGi Service Registry Reference Example
[source,java,linenums]
----
ServiceReference[] refs =
    bundleContext.getServiceReferences(${ddf-branding}.catalog.transform.InputTransformer.class.getName(),"(shortname=" + transformerId + ")");
InputTransformer inputTransformer = (InputTransformer) context.getService(refs[0]);
Metacard entry = inputTransformer.transform(messageInputStream);
----

