==== Event Processor

The Standard Event Processor is an implementation of the Event Processor and provides the ability to create/delete subscriptions.
Events are generated by the ${ddf-catalog}Framework as metacards are created/updated/deleted and the Standard Event Processor is called since it is also a Post-Ingest Plugin.
The Standard Event Processor checks each event against each subscription's criteria.

When an event matches a subscription's criteria the Standard Event Processor:

* invokes each pre-delivery plugin on the metacard in the event
* invokes the Delivery Method's operation corresponding to the type of event being processed, e.g., created operation for the creation of a metacard

===== Installing Event Processor

The Event Processor is  installed by default with a standard installation in the ${ddf-catalog} application.

===== Configuring Event Processor

None

===== Known Issues with Event Processor

The Standard Event processor currently broadcasts federated events and should not.
It should only broadcast events that were generated locally, all other events should be dropped.

