
==== XML Attribute Security Policy Plugin

The *XML Attribute Security Policy Plugin* parses XML metadata contained within a metacard for security attributes on any number of XML elements in the metadata.
The configuration for the plugin contains one field for setting the XML elements that will be parsed for security attributes and the other two configurations contain the XML attributes that will be pulled off of those elements.
The *Security Attributes (union)* field will compute the union of values for each attribute defined.
While the *Security Attributes (intersection)* field will compute the intersection of values for each attribute defined.

===== Installing the XML Attribute Security Policy Plugin

The XML Attribute Security Policy Plugin is installed by default with a standard installation in the ${ddf-catalog} application.

===== Configuring the XML Attribute Security Policy Plugin

. Navigate to the ${admin-console}.
. Select the *${ddf-catalog}* application tile.
. Select the *Configuration* tab.
. Select the *XML Attribute Security Policy Plugin* configuration.

include::{adoc-include}/_tables/org.codice.ddf.catalog.security.policy.xml.XmlAttributeSecurityPolicyPlugin-table-contents.adoc[]
