:title: ${ddf-catalog}
:status: published
:type: applicationReference
:summary: Provides a framework for storing, searching, processing, and transforming information.
:order: 03

== {title} Application Reference
((({title})))

The ${ddf-catalog} provides a framework for storing, searching, processing, and transforming information.

Clients typically perform create, read, update, and delete (CRUD) operations against the Catalog.

At the core of the Catalog functionality is the Catalog Framework, which routes all requests and responses through the system, invoking additional processing per the system configuration.

=== ${ddf-catalog} Application Prerequisites

To use the ${ddf-catalog} Application, the following applications/features must be installed:

* ${ddf-platform}

=== Installing the ${ddf-catalog} Application

Install the ${ddf-catalog} application through the ${admin-console}.

. Navigate to the *${admin-console}*.
. Select the *System* tab.
. Select the *Features* tab.
. Install the `catalog-app` feature.
