:title: Ingest Command
:type: dataManagement
:status: published
:summary: Ingesting data from the ${command-console}.
:parent: Ingesting Data
:order: 00

== {title}
((({title})))

The ${command-console} has a command-line option for ingesting data.

[NOTE]
====
Ingesting with the console ingest command creates a metacard in the catalog, but does not copy the resource to the content store.
The Ingest Command requires read access to the directory being ingested. See the <<{architecture-prefix}url_resource_reader, URL Resource Reader>> for configuring read permission entries to the directory.
====

The syntax for the ingest command is

`ingest -t <transformer type> <file path>`

Select the `<transformer type>` based on the type of files ingested.
Metadata is extracted if it exists in a format compatible with the transformer.
The default transformer is the <<{developing-prefix}xml_input_transformer,XML input transformer>>, which supports the metadata schema `catalog:metacard`.
To see a list of all transformers currently installed, and the file types supported by each, run the `catalog:transformers` command.

For more information on the schemas and file types(mime-types) supported by each transformer see the <<{integrating-prefix}available_input_transformers, Input Transformers>>.

The `<file path>` is relative to the ${home_directory} directory.
This can be the path to a file or a directory containing the desired files.

.Windows Users
[NOTE]
====
On Windows, put the file path in quotes: `"path/to/file"`.
====

Successful command line ingest operations are accompanied with messaging indicating how many files were ingested and how long the operations took.
The ingest command also prints which files could not be ingested with additional details recorded in the ingest log.
The default location of the log is `${home_directory}/data/log/ingest_error.log`.

