:title: Migrate Commands
:type: subMaintaining
:status: published
:parent: Available Console Commands
:summary: Data migration commands available.
:order: 05

== {title}

.[[_migrate_command_descriptions]]Migrate Command Descriptions

[NOTE]
====
Performing a data migration creates, updates, or deletes existing metacards within the system.
A data migration needs to be run when the structure of the data changes to ensure that existing resources function as expected.
The effects of this command cannot be reverted or undone. It is highly recommended to back up the catalog before performing a data migration.
====

The syntax for the migration command is

* `migrate:data --list`
* `migrate:data --all`
* `migrate:data <serviceId>`

Select the `<serviceId>` based on which data migration task you wish to run.
To see a list of all data migrations tasks that are currently available, run the
`migrate:data --list` command.

The `--all` option runs every data migration task that is available.

The `--list` option lists all available data migration tasks.

[NOTE]
====
If an error occurrs performing a data migration the specifics of that error are
available in the logs or are printed to the karaf console.
====
