:title: Subscriptions Commands
:type: subMaintaining
:status: published
:parent: Available Console Commands
:summary: Subscription commands available.
:order: 03

== {title}

[NOTE]
====
The subscriptions commands are installed when the Catalog application is installed.
====

.[[_subscription_command_descriptions]]Subscription Command Descriptions
[cols="1m,4" options="header"]
|===

|Command
|Description

|subscriptions:delete
|Deletes the subscription(s) specified by the search phrase or LDAP filter.

|subscriptions:list
|List the subscription(s) specified by the search phrase or LDAP filter.
|===

.subscriptions:list Command Usage Examples
Note that no arguments are required for the `subscriptions:list` command.
If no argument is provided, all subscriptions will be listed.
A count of the subscriptions found matching the list command's search phrase (or LDAP filter) is displayed first followed by each subscription's ID.

.List All Subscriptions
[source]
----
${branding-lowercase}${at-symbol}local>subscriptions:list

Total subscriptions found: 3

Subscription ID
my.contextual.id.v20|http://172.18.14.169:8088/mockCatalogEventConsumerBinding?WSDL
my.contextual.id.v30|http://172.18.14.169:8088/mockEventConsumerBinding?WSDL
my.contextual.id.json|http://172.18.14.169:8088/services/json/local/event/notification
----

.List a Specific Subscription by ID
[source]
----
${branding-lowercase}${at-symbol}local>subscriptions:list "my.contextual.id.v20|http://172.18.14.169:8088/mockCatalogEventConsumerBinding?WSDL"

Total subscriptions found: 1

Subscription ID
my.contextual.id.v20|http://172.18.14.169:8088/mockCatalogEventConsumerBinding?WSDL
----

[WARNING]
====
It is recommended to always quote the search phrase (or LDAP filter) argument to the command so that any special characters are properly processed.
====

.List Subscriptions Using Wildcards
[source]
----
${branding-lowercase}${at-symbol}local>subscriptions:list "my*"

Total subscriptions found: 3

Subscription ID
my.contextual.id.v20|http://172.18.14.169:8088/mockCatalogEventConsumerBinding?WSDL
my.contextual.id.v30|http://172.18.14.169:8088/mockEventConsumerBinding?WSDL
my.contextual.id.json|http://172.18.14.169:8088/services/json/local/event/notification


${branding-lowercase}${at-symbol}local>subscriptions:list "*json*"

Total subscriptions found: 1

Subscription ID
my.contextual.id.json|http://172.18.14.169:8088/services/json/local/event/notification


${branding-lowercase}${at-symbol}local>subscriptions:list "*WSDL"

Total subscriptions found: 2

Subscription ID
my.contextual.id.v20|http://172.18.14.169:8088/mockCatalogEventConsumerBinding?WSDL
my.contextual.id.v30|http://172.18.14.169:8088/mockEventConsumerBinding?WSDL

----

The example below illustrates searching for any subscription that has "json" or "v20" anywhere in its subscription ID.

.List Subscriptions Using an LDAP Filter
[source]
----
${branding-lowercase}${at-symbol}local>subscriptions:list -f "(|(subscription-id=*json*) (subscription-id=*v20*))"

Total subscriptions found: 2

Subscription ID
my.contextual.id.v20|http://172.18.14.169:8088/mockCatalogEventConsumerBinding?WSDL
my.contextual.id.json|http://172.18.14.169:8088/services/json/local/event/notification
----

The example below illustrates searching for any subscription that has `json` and `172.18.14.169` in its subscription ID. This could be a handy way of finding all subscriptions for a specific site.

----
${branding-lowercase}${at-symbol}local>subscriptions:list -f "(&(subscription-id=*json*) (subscription-id=*172.18.14.169*))"

Total subscriptions found: 1

Subscription ID
my.contextual.id.json|http://172.18.14.169:8088/services/json/local/event/notification
----

.subscriptions:delete Command Usage
The arguments for the `subscriptions:delete` command are the same as for the `list` command, except that a search phrase or LDAP filter must be specified.
If one of these is not specified an error will be displayed.
When the `delete` command is executed it will display each subscription ID it is deleting.
If a subscription matches the search phrase but cannot be deleted, a message in red will be displayed with the ID.
After all matching subscriptions are processed, a summary line is displayed indicating how many subscriptions were deleted out of how many matching subscriptions were found.

.Delete a Specific Subscription Using Its Exact ID
[source]
----
${branding-lowercase}${at-symbol}local>subscriptions:delete "my.contextual.id.json|http://172.18.14.169:8088/services/json/local/event/notification"

Deleted subscription for ID = my.contextual.id.json|http://172.18.14.169:8088/services/json/local/event/notification

Deleted 1 subscriptions out of 1 subscriptions found.
----

.Delete Subscriptions Using Wildcards
[source]
----
${branding-lowercase}${at-symbol}local>subscriptions:delete "my*"

Deleted subscription for ID = my.contextual.id.v20|http://172.18.14.169:8088/mockCatalogEventConsumerBinding?WSDL
Deleted subscription for ID = my.contextual.id.v30|http://172.18.14.169:8088/mockEventConsumerBinding?WSDL

Deleted 2 subscriptions out of 2 subscriptions found.

${branding-lowercase}${at-symbol}local>subscriptions:delete "*json*"

Deleted subscription for ID = my.contextual.id.json|http://172.18.14.169:8088/services/json/local/event/notification

Deleted 1 subscriptions out of 1 subscriptions found.
----

.Delete All Subscriptions
[source]
----
${branding-lowercase}${at-symbol}local>subscriptions:delete *

Deleted subscription for ID = my.contextual.id.v30|http://172.18.14.169:8088/mockEventConsumerBinding?WSDL
Deleted subscription for ID = my.contextual.id.v20|http://172.18.14.169:8088/mockCatalogEventConsumerBinding?WSDL
Deleted subscription for ID = my.contextual.id.json|http://172.18.14.169:8088/services/json/local/event/notification

Deleted 3 subscriptions out of 3 subscriptions found.
----

.Delete Subscriptions Using an LDAP Filter
[source]
----
${branding-lowercase}${at-symbol}local>subscriptions:delete -f "(&(subscription-id=*WSDL) (subscription-id=*172.18.14.169*))"

Deleted subscription for ID = my.contextual.id.v20|http://172.18.14.169:8088/mockCatalogEventConsumerBinding?WSDL
Deleted subscription for ID = my.contextual.id.v30|http://172.18.14.169:8088/mockEventConsumerBinding?WSDL

Deleted 2 subscriptions out of 2 subscriptions found.
----
