:title: Filters
:type: architecture
:status: published
:parent: Queries
:children: FilterBuilder API
:order: 00
:summary: Filters.

((({title})))
An ((OGC Filter)) is a http://www.opengeospatial.org/standards/filter[Open Geospatial Consortium (OGC) standard] {external-link} that describes a query expression in terms of Extensible Markup Language (XML) and key-value pairs (KVP).
The OGC Filter is used to represent a query to be sent to sources and the Catalog Provider, as well as to represent a Subscription.
The OGC Filter provides support for expression processing, such as adding or dividing expressions in a query, but that is not the intended use for ${branding}.

The ${ddf-catalog} Framework does not use the XML representation of the OGC Filter standard. ${branding} instead uses the Java implementation provided by http://geotools.org/[GeoTools] {external-link}.
GeoTools provides Java equivalent classes for OGC Filter XML elements.
GeoTools originally provided the standard Java classes for the OGC Filter Encoding 1.0 under the package name `org.opengis.filter`.
The same package name is used today and is currently used by ${branding}.
Java developers do not parse or view the XML representation of a Filter in ${branding}. Instead, developers use only the Java objects to complete query tasks.

Note that the `ddf.catalog.operation.Query` interface extends the `org.opengis.filter.Filter` interface, which means that a Query object is an OGC Java Filter with Query Options.

.A Query is an OGC Filter
[source,java]
----
public interface Query extends Filter
----
