
==== CSW Transactional Federated Source

The CSW Transactional Federated Source supports the ability to search collections of descriptive information (metadata) for data, services, and related information objects.  Additionally the transactional source supports CSW transactions including create, update, and delete operations to the remote source.

Use the CSW source if querying a CSW version 2.0.2 compliant service.

===== Installing the CSW Transactional Federated Source

The CSW Federated Source is installed by default with a standard installation in the ${ddf-spatial} application.

Add a New CSW Transactional Federated Source through the ${admin-console}:

* Navigate to the *${admin-console}*.
* Select the *${ddf-catalog}* application.
* Select the *Sources* tab.
* Add a New source.
* Name the New source.
* Select *CSW Transactional Federated Source* from *Binding Configurations*.

===== Configuring the CSW Transactional Federated Source

Configure an Existing CSW Transactional Federated Source through the ${admin-console}:

* Navigate to the *${admin-console}*.
* Select the *${ddf-catalog}* application.
* Select the *Sources* tab.
* Select the name of the source to edit.

include::{adoc-include}/_tables/Csw_Transactional_Federated_Source-table-contents.adoc[]

===== Usage Limitations of the CSW Transactional Federated Source

* The CSW Federated Source does not support text path searches.
* Nearest neighbor spatial searches are not supported.



