==== Embedded Solr

The Embedded Solr is an embedded, local Apache Solr server instance.
It is a local instance that is a lightweight Catalog Provider solution.
However, it does not provide a Solr Admin UI or a REST-like HTTP/XML and JSON API.
If that is necessary, see <<HTTP Solr,HTTP Solr>> or <<Solr Cloud,Solr Cloud>>.

.Embedded Solr Deployment
[ditaa,embedded-solr-diagram,png]
....
 Container (JVM)
 +=-----------------+
 |                  |
 | /--------------\ |
 | |cDEF          | |
 | | DDF          | |
 | |              | |
 | |  +---------+ | |
 | |  |Solr cFF0| | |
 | |  +---------+ | |
 | |              | |
 | \--------------/ |
 |                  |
 |                  |
 +------------------+
....

===== When to Use the Embedded Solr

The Embedded Solr configuration is great for demonstrations, training exercises, or for sparse querying and ingesting. See below for details.

====== Tradeoffs
* Requires no installation and very little configuration.
* No HTTP connection required. As a result, there is no network overhead.
* Not scalable.
* There is no Solr Admin UI.
* Backup must be performed manually.


===== Installation/Configuration Guide

====== Installing

No installation required. Follow the Configuring section below and restart the {branding}.

====== Configuring
. Edit the `<INSTALLATION_DIR>/etc/system.properties`

.. Comment out the Solr Client Configuration for *Cloud Solr Client* and *Http Solr Client* sections.
.. Uncomment the section for the *Embedded Solr Client*:

.system.properties
----
solr.client = EmbeddedSolrServer
solr.data.dir = ${karaf.home}/data/solr
----
