
==== Solr Embedded Provider

The Solr Embedded Provider is an embedded, local Solr Server instance used in conjunction with an Apache Solr Server data store.
It is a local instance that is a lightweight Catalog provider solution.
However, it does not provide a Solr Admin GUI or a REST-like HTTP/XML and JSON API.
If that is necessary, see Standalone Solr Server or Solr Cloud.

Use the local, embedded Solr Provider when only one ${branding} instance is necessary and scalability is not an issue.
The local, embedded Solr Provider requires no installation and little to no configuration.
It is great for demonstrations, training exercises, or for sparse querying and ingesting.

==== Configuring Embedded Solr Server and Solr Provider

The *system.properties* file needs to be updated to use the Embedded Solr Provider.

Some notable features of the Solr Provider include:

* Supports extensible metacards
* Fast, simple contextual searching
* Indexes XML Attributes as well as CDATA sections and XML text elements
* Full XPath support.
* Works with an embedded, local Solr Server (all-in-one Catalog)
** No configuration necessary on a single-node distribution
** Data directory of Solr indexes are configurable
* Works with a standalone Solr Server
* Works with Solr Cloud

.Embedded Solr Provider Pros and Cons
[cols="1,4a,2a" options="header"]
|===

|Feature
|Pro
|Con

|Scalability
|
a|* Does not scale. Only runs one single server instance.
* Does not allow the middle tier to be scaled.

|Flexibility
a|* Requires no HTTP connection.
* Uses the same interface as the Standalone Solr Server uses under the covers.
* Allows for full control over the Solr Server.
No synchronous issues on startup; i.e., the Solr Server will synchronously start up with the Solr Provider
* Runs within the same JVM
* Setup and Installation is simple: unzip and run.
|* Can only be interfaced using Java

|(Administrative)Tools
a|* External open source tools like Luke will work to allow admins to check index contents
* JMX metrics reporting is enabled

a|* No Web Console. 
* No easy way to natively access (out of the box) what is in the index files or health of server at the data store level.

|Security
a|* Does not open any ports which means no ports have to be secured.
|
 
|Performance
a|* Requires no HTTP or network overhead
* Near real-time indexing
* Can understand complex queries
|

|Backup/Recovery
a|* Backups of indexes can be performed manually or through custom scripts
a|* Must copy files when server is shutdown

|===
