
==== Catalog Solr Embedded Provider

The Solr Catalog Embedded Provider is an embedded, local Solr Server instance used in conjunction with an Apache Solr Server data store.
It is a local instance that is a lightweight Catalog provider solution. However, it does not provide a Solr Admin GUI or a "REST-like HTTP/XML and JSON API." If that is necessary, see Standalone Solr Server.

Use the local, embedded Solr Catalog Provider when only one ${branding} instance is necessary and scalability is not an issue.
The local, embedded Solr Catalog Provider requires no installation and little to no configuration.
It is great for demonstrations, training exercises, or for sparse querying and ingesting.

===== Installing Solr Catalog Embedded Provider

The Solr Catalog Embedded Provider is not installed by default with a standard installation.

To install:

. Navigate to the ${ddf-solr} application in the ${admin-console}.
. Select *Features*.
. Uninstall the `catalog-solr-external-provider` feature.
. Install the `catalog-solr-embedded-provider`.

==== Configuring Embedded Solr Server and Solr Catalog Provider

No configuration is necessary for the embedded Solr Server and the Solr Catalog Provider.
The standard installation described above is sufficient.
When the `catalog-solr-embedded-provider` feature is installed, it stores the Solr index files to `<DISTRIBUTION_INSTALLATION_DIRECTORY>/data/solr` by default.
A user does not have to specify any parameters and the `catalog-solr-embedded-provider` feature contains all files necessary for Solr to start the server. 

However, this component _can_ be configured to specify the directory to use for data storage. 

The configurable properties for the SCP are accessed from the *Catalog Embedded Solr Catalog Provider* configurations in the ${admin-console}.

[TIP]
====
The Embedded (Local) Solr Catalog Provider works on startup without any configuration because a local embedded Solr Server is automatically started and pre-configured.
====

include::{adoc-include}/_tables/ddf.catalog.source.solr.SolrCatalogProvider-table-contents.adoc[]

Some notable features of the Solr Catalog Provider include:

* Supports extensible metacards
* Fast, simple contextual searching
* Indexes XML Attributes as well as CDATA sections and XML text elements
* Full XPath support.
* Works with an embedded, local Solr Server (all-in-one Catalog)
** No configuration necessary on a single-node distribution
** Data directory of Solr indexes are configurable
* Works with a standalone Solr Server
* Works with Solr Cloud

.Embedded Solr Catalog Provider Pros and Cons
[cols="1,4a,2a" options="header"]
|===

|Feature
|Pro
|Con

|Scalability
|
a|* Does not scale. Only runs one single server instance.
* Does not allow the middle tier to be scaled.

|Flexibility
a|* Can be embedded in Java easily.
* Requires no HTTP connection.
* Uses the same interface as the Standalone Solr Server uses under the covers.
* Allows for full control over the Solr Server. No synchronous issues on startup; i.e., the Solr Server will synchronously start up with the Solr Catalog Provider
* Runs within the same JVM
* Setup and Installation is simple: unzip and run.
|* Can only be interfaced using Java

|(Administrative)Tools
a|* External open source tools like Luke will work to allow admins to check index contents
* JMX metrics reporting is enabled

a|* No Web Console. 
* No easy way to natively access (out of the box) what is in the index files or health of server at the data store level.

|Security
a|* Does not open any ports which means no ports have to be secured.
|
 
|Performance
a|* Requires no HTTP or network overhead
* Near real-time indexing
* Can understand complex queries
|

|Backup/Recovery
a|* Can manually or through custom scripts back up the indexes
a|* Must copy files when server is shutdown

|===
