:title: Controlling File System Access
:type: subInstalling
:status: published
:summary: Restrict access to sensitive files.
:parent: Installing With the ${branding} Distribution Zip
:order: 00

== Configuring Operating Permissions and Allocations

Restrict access to sensitive files by ensuring that the only users with access privileges are administrators.

Within the `${home_directory}`, a directory is created named ${branding-lowercase}-${project.version}.
This directory will be referred to in the documentation as `${home_directory}`.

. Do not assume the deployment is from a trusted source; verify its origination.
. Check the available storage space on the system to ensure the deployment will not exceed the available space.
. Set maximum storage space on the `${home_directory}/deploy` and `${home_directory}/system` directories to restrict the amount of space used by deployments.

=== Setting Directory Permissions

* *{hardening-step}*

${branding} relies on the Directory Permissions of the host platform to protect the integrity of the ${branding} during operation.
System administrators MUST perform the following steps prior to deploying bundles added to the ${branding}.

[IMPORTANT]
====
The system administrator must restrict certain directories to ensure that the application (user) cannot access restricted directories on the system.
For example the `${branding}USER` should have read-only access to `${home_directory}`, except for the sub-directories `etc`, `data` and `instances`.
====

.Setting Directory Permissions on Windows
****
Set directory permissions on the `${home_directory}`; all sub-directories except `etc`, `data`, and `instances`; and any directory intended to interact with the ${branding} to protect from unauthorized access.

. Right-click on the `${home_directory}` directory.
. Select *Properties -> Security -> Advanced*.
. Under *Owner*, select *Change*.
. Enter `Creator Owner` into the *Enter the Object Name...* field.
. Select *Check Names*.
. Select *Apply*.
.. If prompted *Do you wish to continue*, select *Yes*.
. Remove all Permission Entries for any groups or users with access to ${home_directory} other than *System*, *Administrators*, and *Creator Owner*.
.. Note: If prompted with a message such as: *You can’t remove X because this object is inheriting permissions from its parent.* when removing entries from the Permission entries table:
... Select *Disable Inheritance*.
... Select *Convert Inherited Permissions into explicit permissions on this object*.
... Try removing the entry again.
. Select the option for *Replace all child object permission entries with inheritable permission entries from this object*.
. Close the *Advanced Security Settings* window.

****

.Setting Directory Permissions on *NIX
****
Set directory permissions to protect the ${branding} from unauthorized access.

* Change ownership of `${home_directory}`
** `chown -R ${branding-lowercase}-user ${home_directory}`
* Create instances sub-directory if does not exist
** `mkdir -p ${home_directory}/instances`
* Change group ownership on sub-directories
** `chgrp -R ${branding}GROUP ${home_directory}/etc ${home_directory}/data ${home_directory}/instances`
* Change group permissions
** `chmod -R g-w ${home_directory}/etc ${home_directory}/data ${home_directory}/instances`
* Remove permissions for other users
** `chmod -R o-rwx ${home_directory}/etc ${home_directory}/data ${home_directory}/instances`
****

=== Configuring Memory Allocation for the ${branding} Java Virtual Machine

[[_jvm_memory_configuration]]
The amount of memory allocated to the Java Virtual Machine host ${branding} by the operating
system can be increased by updating the `setenv` script:

.Setenv Scripts: *NIX
----
${home_directory}/bin/setenv
Update the JAVA_OPTS -Xmx value
${home_directory}/bin/setenv-wrapper.conf
Update the wrapper.java.additional -Xmx value
----

.Setenv Scripts: Windows
----
${home_directory}/bin/setenv.bat
Update the JAVA_OPTS -Xmx value
${home_directory}/bin/setenv-windows-wrapper.conf
Update the wrapper.java.additional -Xmx value
----

=== Enabling JMX

[[jmx-connectivity-configuration]]
By default, ${branding} prevents connections to JMX because the system is more secure when JMX
 is not enabled. However, many monitoring tools require a JMX connection to the Java Virtual
 Machine. To enable JMX, update the setenv script:

.Setenv Scripts: *NIX
----
${home_directory}/bin/setenv
Remove -XX:+DisableAttachMechanism from JAVA_OPTS
${home_directory}/bin/setenv-wrapper.conf
Comment out the -XX:+DisableAttachMechanism line and re-number remainder lines appropriately
----

.Setenv Scripts: Windows
----
${home_directory}/bin/setenv.bat
Remove -XX:+DisableAttachMechanism from JAVA_OPTS
${home_directory}/bin/setenv-windows-wrapper.conf
Comment out the -XX:+DisableAttachMechanism line and re-number remainder lines appropriately
----
