:title: Additional Internet Explorer 11 Security Configuration
:type: installing
:status: published
:summary: Configuring Internet Explorer Enhanced Security used in ${branding}.
:project: ${branding}
:order: 09

=== Internet Explorer 11 Enhanced Security Configuration

Below are steps listing all of the changes that ${branding} requires to run on Internet Explorer 11 and several additional considerations to keep in mind.

. In the IE11 `Settings` > `Compatibility View Settings` dialog, un-check `Display intranet sites in Compatibility View`.
. In the `Settings` > `Internet Options` > `Security` tab, `Local intranet` zone:
.. Click the `Sites` > `Advanced` button, add the current host name to the list, e.g., https://windows-host-name.domain.edu, and close the dialog.
.. Make sure the security level for the `Local intranet` zone is set to `Medium-low` in `Custom level...`.
... `Enable Protected Mode` is checked by default, but it may need to be disabled if the above changes do not fully resolve access issues.
. Restart the browser.

[NOTE]
====
During installation, make sure to use the host name and not localhost when setting up the ${branding}'s hostname, port, etc.
====
