:title: Initial Startup
:type: installing
:status: published
:summary: System state at initial startup.
:project: ${branding}
:order: 02

== Initial Startup

Run the ${branding} using the appropriate script.

.*NIX
----
${home_directory}/bin/${branding-lowercase}
----

.Windows
----
${home_directory}/bin/${branding-lowercase}.bat
----

The distribution takes a few moments to load depending on the hardware configuration.

[TIP]
====
To run ${branding} as a service, see <<{managing-prefix}managed_services,Starting as a Service>>.
====

=== Verifying Startup

At this point, ${branding} should be configured and running with a Solr Catalog Provider.
New features (endpoints, services, and sites) can be added as needed.

Verification is achieved by checking that all of the ${branding} bundles are in an *Active* state (excluding fragment bundles which remain in a *Resolved* state).

[NOTE]
====
It may take a few moments for all bundles to start so it may be necessary to wait a few minutes before verifying installation.
====

Execute the following command to display the status of all the ${branding} bundles:

.View Status
----
${branding-lowercase}${at-symbol}local>list | grep -i ${branding-lowercase}
----

[WARNING]
====
Entries in the *Resolved* state are expected, they are OSGi bundle fragments.
Bundle fragments are distinguished from other bundles in the command line console list by a field named `Hosts`, followed by a bundle number.
Bundle fragments remain in the *Resolved* state and can never move to the *Active* state.
====

.Example: Bundle Fragment in the Command Line Console
----
96 | Resolved |  80 | 2.10.0.SNAPSHOT | DDF :: Platform :: PaxWeb :: Jetty Config, Hosts: 90
----

After successfully completing these steps, the ${branding} is ready to be configured.

=== ${branding} Directory Contents after Installation and Initial Startup

During ${branding} installation, the major directories and files shown in the table below are created, modified, or replaced in the destination directory.

.${branding} Directory Contents
[cols="1,4" options="header"]
|===

|Directory Name
|Description

|`bin`
|Scripts to start, stop, and connect to ${branding}.

|`data`
|The working directory of the system – installed bundles and their data

|`data/log/${branding-lowercase}.log`
|Log file for ${branding}, logging all errors, warnings, and (optionally) debug statements. This log rolls up to 10 times, frequency based on a configurable setting (default=1 MB)

|`data/log/ingest_error.log`
|Log file for any ingest errors that occur within ${branding}.

|`data/log/security.log`
|Log file that records user interactions with the system for auditing purposes.

|`deploy`
|Hot-deploy directory – KARs and bundles added to this directory will be hot-deployed (Empty upon ${branding} installation)

|`documentation`
|HTML and PDF copies of ${branding} documentation.

|`etc`
|Directory monitored for addition/modification/deletion of `.config` configuration files or third party `.cfg` configuration files.

|`etc/templates`
|Template `.config` files for use in configuring ${branding} sources, settings, etc., by copying to the etc directory.

|`lib`
|The system's bootstrap libraries. Includes the `${branding-lowercase}-branding.jar` file which is used to brand the system console with the ${branding} logo.

|`licenses`
|Licensing information related to the system.

|`system`
|Local bundle repository. Contains all of the JARs required by ${branding}, including third-party JARs.

|===

=== Completing Installation

Upon startup, complete installation from either the ${admin-console} or the ${command-console}.
