:title: Configuring
:type: managingSection
:status: published
:summary: Introduction to system configuration.
:order: 01

== {title}

${branding} is highly configurable and many of the components of the system can be configured to use an included ${branding} implementation or replaced with an existing component of an integrating system.

.Configuration Requirements
[NOTE]
====
Because components can easily be installed and uninstalled, it's important to remember that for proper ${branding} functionality, at least the Catalog API, one Endpoint, and one Catalog Framework implementation must be active.
====

.Configuration Tools
${branding} provides several tools for configuring the system.
The <<{managing-prefix}admin_console_tutorial,${admin-console}>> is a useful interface for configuring applications, their features, and important settings.
Alternatively, many configurations can be updated through <<{managing-prefix}console_command_reference,console commands>> entered into the ${command-console}.
Finally, configurations are stored in <<{managing-prefix}configuration_files,configuration files>> within the `${home_directory}` directory.

.Configuration Outline
While many configurations can be set or changed in any order, for ease of use of this documentation, similar subjects have been grouped together sequentially.

See <<{managing-prefix}managing_keystores_and_certificates,Keystores and certificates>> to set up the certificates needed for messaging integrity and authentication.
Set up <<{managing-prefix}configuring_user_access,Users>> with security attributes, then configure <<{managing-prefix}configuring_data_management,data>> attribute handling, and finally, define the <<{managing-prefix}configuring_security_policies,Security Policies>> that map between users and data and make decisions about access.

Connecting ${branding} to other data sources, including other instances of ${branding} is covered in the <<{managing-prefix}configuring_federation,Configuring Federation>> section.

Lastly, see the <<{managing-prefix}configuring_for_special_deployments,Configuring for Special Deployments>> section for guidance on common specialized installations, such as <<{managing-prefix}configuring_for_a_fanout_proxy,fanout>>.
