:title: Environment Hardening
:type: configuringIntro
:status: published
:summary: Environment security mitigations.
:order: 09

== {title}
((({title})))

* *{hardening-step}*

[IMPORTANT]
====
It is recommended to apply the following security mitigations to the ${branding}.
====

=== Known Issues with Environment Hardening

[cols="1,3,6",options="header]
|===

|Protocol/Type
|Risk
|Mitigation

|JMX
|tampering, information disclosure, and unauthorized access
a|* Stop the management feature using the command line console: `feature:stop management`. +

|File System Access
|tampering, information disclosure, and denial of service
a|Set OS File permissions under the `${home_directory}` directory (for example, `/deploy` or `/etc`) to ensure unauthorized viewing and writing is not allowed.

|SSH
|tampering, information disclosure, and denial of service
a|By default, SSH access to ${branding} is only enabled to connections originating from the same
host running ${branding}.
For remote access to ${branding},
 first establish an SSH session with the host running
 ${branding}. From within that session, initiate a new SSH connection (to **localhost**), and use
 the `sshPort` as configured in the file
 `${home_directory}/etc/org.apache.karaf.shell.cfg`.

To allow direct remote access to the ${branding} shell from any host, change the value of the
`sshHost` property to `0.0.0.0` in the `${home_directory}/etc/org.apache.karaf.shell.cfg` file.

SSH can also be authenticated and authorized through an external Realm,
such as LDAP. This can be accomplished by editing the `${home_directory}/etc/org.apache.karaf.shell.cfg` file and setting the
value for `sshRealm` to the appropriate realm, such as `ldap`. No restart of ${branding} is necessary after this change.

By definition, all connections over SSH are authenticated and authorized and secure from eavesdropping.

[WARNING]
====
Enabling SSH exposes your file system because any user with access to your ${branding} shell has read/write/execute access to all directories and files accessible to your installation user.

*Because of this, SSH is not recommended in a secure environment and should be turned off
in a fully hardened system.*
====

Set `karaf.shutdown.port=-1` in `${home_directory}/etc/custom.properties` or `${home_directory}/etc/config.properties`.

|SSL/TLS
|man-in-the-middle, information disclosure
a|Update the `${home_directory}/etc/org.ops4j.pax.web.cfg` file to add the entry `org.ops4j.pax.web.ssl.clientauthneeded=true`.

[WARNING]
====
Setting this configuration may break compatibility to legacy systems that do not support two-way SSL.
====

[WARNING]
====
Setting this configuration requires a certificate to be installed in the browser.
====

|Shell Command Access
|command injection
a|By default, some shell commands are disabled in order to secure the system.
${branding} includes a whitelist of allowed shell commands in
`${home_directory}/etc/org.apache.karaf.command.acl.shell.cfg`.

By default, this list includes commands that are whitelisted only to administrators:

* `complete`
* `echo`
* `format`
* `grep`
* `if`
* `keymap`
* `less`
* `set`
* `setopt`
* `sleep`
* `tac`
* `wc`
* `while`
* `.invoke`
* `unsetopt`

|===
