:title: Feature Commands
:type: configuration
:status: published
:parent: Console Command Reference
:order: 02
:summary: Managing features from the ${command-console}.

== {title}
((({title})))

Individual features can also be added via the ${command-console}.

. Determine which feature to install by viewing the available features on ${branding}. +
`${branding-lowercase}${at-symbol}local>feature:list`
. The console outputs a list of all features available (installed and uninstalled). A snippet of the list output is shown below (the versions may differ):

----
State         Version            Name                                     Repository                           Description
[installed  ] [${project.version}  ] security-handler-api                     security-services-app-${project.version} API for authentication handlers for web applications.
[installed  ] [${project.version}  ] security-core                            security-services-app-${project.version} DDF Security Core
[uninstalled] [${project.version}  ] security-expansion                       security-services-app-${project.version} DDF Security Expansion
[installed  ] [${project.version}  ] security-pdp-authz                       security-services-app-${project.version} DDF Security PDP.
[uninstalled] [${project.version}  ] security-pep-serviceauthz                security-services-app-${project.version} DDF Security PEP Service AuthZ
[uninstalled] [${project.version}  ] security-expansion-user-attributes       security-services-app-${project.version} DDF Security Expansion User Attributes Expansion
[uninstalled] [${project.version}  ] security-expansion-metacard-attributes   security-services-app-${project.version} DDF Security Expansion Metacard Attributes Expansion
[installed  ] [${project.version}  ] security-realm-saml                       security-services-app-${project.version} DDF Security SAML Realm.
[uninstalled] [${project.version}  ] security-jaas-ldap                   security-services-app-${project.version} DDF Security JAAS LDAP Login.
[uninstalled] [${project.version}  ] security-claims-ldap           security-services-app-${project.version} Retrieves claims attributes from an LDAP store.
----
. Check the bundle status to verify the service is started. +
`${branding-lowercase}${at-symbol}local>list`

The console output should show an entry similar to the following:
----
[ 117] [Active     ] [            ] [Started] [   75] ${ddf-branding} :: Catalog :: Source :: Dummy (<version>)
----

=== Uninstalling Features from the ${command-console}

. Check the feature list to verify the feature is installed properly. +
`${branding-lowercase}${at-symbol}local>feature:list`

----
State         Version          Name                          Repository  		   Description
framework-security                │ 4.4.1            │          │ Started     │ standard-4.4.1                  │ OSGi Security for Karaf
service-security                  │ 4.4.1            │          │ Uninstalled │ standard-4.4.1                  │ Services Security for Karaf
aries-proxy                       │ 4.4.1            │          │ Started     │ standard-4.4.1                  │ Aries Proxy
aries-blueprint                   │ 4.4.1            │          │ Started     │ standard-4.4.1                  │ Aries Blueprint
feature                           │ 4.4.1            │          │ Started     │ standard-4.4.1                  │ Features Support
----

. Uninstall the feature. +
`${branding-lowercase}${at-symbol}local>feature:uninstall framework-security`

[WARNING]
====
Dependencies that were auto-installed by the feature are not automatically uninstalled.
====

. Verify that the feature has uninstalled properly. +
`${branding-lowercase}${at-symbol}local>feature:list`

----
State         Version          Name                          Repository  Description
framework-security                │ 4.4.1            │          │ Uninstalled │ standard-4.4.1                  │ OSGi Security for Karaf
service-security                  │ 4.4.1            │          │ Uninstalled │ standard-4.4.1                  │ Services Security for Karaf
aries-proxy                       │ 4.4.1            │          │ Started     │ standard-4.4.1                  │ Aries Proxy
aries-blueprint                   │ 4.4.1            │          │ Started     │ standard-4.4.1                  │ Aries Blueprint
feature                           │ 4.4.1            │          │ Started     │ standard-4.4.1                  │ Features Support
----
