:title: Feature Commands
:type: configuration
:status: published
:parent: Console Command Reference
:order: 02
:summary: Managing features from the ${command-console}.

== {title}
((({title})))

Individual features can also be added via the ${command-console}.

. Determine which feature to install by viewing the available features on ${branding}. +
`${branding-lowercase}${at-symbol}local>feature:list`
. The console outputs a list of all features available (started and uninstalled). A snippet of the list output is shown below (the versions may differ):

----
Name                              │ Version          │ Required │ State       │ Repository                      │ Description
──────────────────────────────────┼──────────────────┼──────────┼─────────────┼─────────────────────────────────┼───────────────────────────────────────────────────
catalog-core-api                  │ 3.0.0.SNAPSHOT   │          │ Started     │ catalog-app-X.0.0               │ Catalog API interfaces and simple implementations.
catalog-core-impl                 │ 3.0.0.SNAPSHOT   │          │ Started     │ catalog-app-X.0.0               │ Catalog Core feature containing the API, third pa
catalog-core-attachment           │ 3.0.0.SNAPSHOT   │          │ Started     │ catalog-app-X.0.0               │ Generate Filenames for Ingested Attachments
catalog-transformer-xlsx          │ 3.0.0.SNAPSHOT   │          │ Started     │ catalog-app-X.0.0               │
catalog-core-plugins              │ 3.0.0.SNAPSHOT   │          │ Started     │ catalog-app-X.0.0               │ Catalog core plugins
catalog-core-content              │ 3.0.0.SNAPSHOT   │          │ Started     │ catalog-app-X.0.0               │ Core features for content
catalog-rest                      │ 3.0.0.SNAPSHOT   │          │ Started     │ catalog-app-X.0.0               │
catalog-rest-endpoint             │ 3.0.0.SNAPSHOT   │          │ Started     │ catalog-app-X.0.0               │ REST Endpoint provides CRUD operations on the Cat
catalog-opensearch                │ 3.0.0.SNAPSHOT   │          │ Started     │ catalog-app-X.0.0               │
catalog-opensearch-endpoint       │ 3.0.0.SNAPSHOT   │          │ Started     │ catalog-app-X.0.0               │ OpenSearch Query Endpoint with Atom Transformer.
catalog-opensearch-source         │ 3.0.0.SNAPSHOT   │          │ Started     │ catalog-app-X.0.0               │ OpenSearch Federated Source queries a Federated S
----
. Check the bundle status to verify the service is started. +
`${branding-lowercase}${at-symbol}local>list`

The console output should show an entry similar to the following:
----
[ 117] [Active     ] [            ] [Started] [   75] ${ddf-branding} :: Catalog :: Source :: Dummy (<version>)
----

=== Uninstalling Features from the ${command-console}

. Check the feature list to verify the feature is installed properly. +
`${branding-lowercase}${at-symbol}local>feature:list`

----
State         Version          Name                          Repository  		   Description
framework-security                │ 4.4.1            │          │ Started     │ standard-4.4.1                  │ OSGi Security for Karaf
service-security                  │ 4.4.1            │          │ Uninstalled │ standard-4.4.1                  │ Services Security for Karaf
aries-proxy                       │ 4.4.1            │          │ Started     │ standard-4.4.1                  │ Aries Proxy
aries-blueprint                   │ 4.4.1            │          │ Started     │ standard-4.4.1                  │ Aries Blueprint
feature                           │ 4.4.1            │          │ Started     │ standard-4.4.1                  │ Features Support
----

. Uninstall the feature. +
`${branding-lowercase}${at-symbol}local>feature:uninstall framework-security`

[WARNING]
====
Dependencies that were auto-installed by the feature are not automatically uninstalled.
====

. Verify that the feature has uninstalled properly. +
`${branding-lowercase}${at-symbol}local>feature:list`

----
State         Version          Name                          Repository  Description
framework-security                │ 4.4.1            │          │ Uninstalled │ standard-4.4.1                  │ OSGi Security for Karaf
service-security                  │ 4.4.1            │          │ Uninstalled │ standard-4.4.1                  │ Services Security for Karaf
aries-proxy                       │ 4.4.1            │          │ Started     │ standard-4.4.1                  │ Aries Proxy
aries-blueprint                   │ 4.4.1            │          │ Started     │ standard-4.4.1                  │ Aries Blueprint
feature                           │ 4.4.1            │          │ Started     │ standard-4.4.1                  │ Features Support
----
