:title: Restricting Access to Features, Apps, Services, and Configurations
:type: configuration
:status: published
:parent: Configuring User Access
:summary: Restricting User Access to Features, Apps, Services, and Configurations
:order: 051

== {title}
((({title})))

* *{hardening-step}*

Limit access to the individual applications, features, or services to those users who need access.
Organizational requirements should dictate which applications are restricted and the extent to which they are restricted.

. Navigate to the *${admin-console}*.
. Select the *${ddf-admin}* application.
. Select the *Configuration* tab.
. Select the *Admin Configuration Policy*.
. To add a feature or app permission:
.. Add a new field to "Feature and App Permissions" in the format of:
+
`<feature name>/<app name> = "attribute name=attribute value","attribute name2=attribute value2", ...`
+
.. For example, to restrict access of any user without an admin role to the catalog-app:
+
`catalog-app = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/role=admin", ...`
+
. To add a configuration permission:
.. Add a new field to "Configuration Permissions" in the format of:
+
`configuration id = "attribute name=attribute value","attribute name2=attribute value2", ...`
.. For example, to restrict access of any user without an admin role to the Web Context Policy Manager:
+
`org.codice.ddf.security.policy.context.impl.PolicyManager="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/role=admin"`

If a permission is specified, any user without the required attributes is unable to see or modify the feature, app, or configuration.
