
=== Ingesting Data

Ingesting is the process of getting metacard(s) into the Catalog Framework.
Ingested files are "transformed" into a neutral format that can be searched against as well as migrated to other formats and systems.
There are multiple methods available for ingesting files into the ${branding}.

==== Methods of Ingest

There are many methods of ingest supported by the ${branding} to support different needs.

===== Methods for ingesting small sets of records

These methods are the simplest for small data sets or for testing purposes.

====== Ingest Command (${command-console})

The ${branding} console application has a command-line option for ingesting files

The syntax for the ingest command is `ingest -t <transformer type> <file path>` relative to the installation path.

For more information on available transformers see the <<_input_transformers, Input Transformers>> or run the `catalog:transformers` command.

For metacard XML data, run this command:
----
ingest -t xml examples/metacards/xml
----

[NOTE]
====
Ingesting with the console ingest command will only create and store a metacard and not the resource itself.
====

====== User Interface Ingest

Files can also be ingested directly from <<_ui_ingest, ${catalog-ui}>>.

===== Methods for ingesting large sets of records

These methods are useful for slightly larger data sets or infrequent ingests.

====== Directory Monitor Ingest

The ${ddf-catalog} application contains a Directory Monitor feature that allows files placed in a single directory to be monitored and ingested automatically.
For more information about configuring a directory to be monitored, see <<_configuring_the_content_directory_monitor,Configuring the Content Directory Monitor>>.

Simply place the desired files in the monitored directory and it will be ingested automatically.
If, for any reason, the files cannot be ingested, they will be moved to an automatically created sub-folder named `.errors`.
Optionally, ingested files can be automatically moved to a sub-folder called `.ingested`.

====== External Methods

Several third-party tools, such as https://curl.haxx.se/[cURL.exe] and the https://advancedrestclient.com/[Chrome Advanced Rest Client], can be used to send files and other types of data to ${branding} for ingest.

.Windows Example
----
curl -H "Content-type: application/json;id=geojson" -i -X POST -d ${at-symbol}"C:\path\to\geojson_valid.json" ${secure_url}/services/catalog
----

.*NIX Example
----
curl -H "Content-type: application/json;id=geojson" -i -X POST -d ${at-symbol}geojson_valid.json ${secure_url}/services/catalog
----

Where: +
*-H* adds an HTTP header. In this case, Content-type header `application/json;id=geojson` is added to match the data being sent in the request. +
*-i* requests that HTTP headers are displayed in the response. +
*-X* specifies the type of HTTP operation. For this example, it is necessary to POST (ingest) data to the server. +
*-d* specifies the data sent in the POST request. The `${at-symbol}` character is necessary to specify that the data is a file. +

The last parameter is the URL of the server that will receive the data.

This should return a response similar to the following (the actual catalog ID in the id and Location URL fields will be different):

.Sample Response
[source,http,linenums]
----
HTTP/1.1 201 Created
Content-Length: 0
Date: Mon, 22 Apr 2015 22:02:22 GMT
id: 44dc84da101c4f9d9f751e38d9c4d97b
Location: ${secure_url}/services/catalog/44dc84da101c4f9d9f751e38d9c4d97b
Server: Jetty(7.5.4.v20111024)
----

. Verify the entry was successfully ingested by entering in a browser the URL returned in the POST response's HTTP header. For instance in our example, it was `/services/catalog/44dc84da101c4f9d9f751e38d9c4d97b`. This should display the catalog entry in XML within the browser.
. Verify the catalog entry exists by executing a query via the OpenSearch endpoint.
. Enter the following URL in a browser /services/catalog/query?q=ddf. A single result, in Atom format, should be returned.

A resource can also be ingested with metacard metadata associated with it using the multipart/mixed content type.

.Example
----
curl -k -X POST -i -H "Content-Type: multipart/mixed" -F parse.resource=@/path/to/resource -F parse.metadata=@/path/to/metacard ${secure_url}/services/catalog
----

====== Other Methods

The ${branding} provides endpoints for both REST and SOAP services, allowing integration with other data systems and the ability to further automate ingesting data into the catalog. See <<_available_endpoints, Available Endpoints>> for more information.

==== Verifying Ingest by REST Endpoint

Verify file was stored using the Content REST endpoint.

* Send a GET command to read the content from the content repository using the Content REST endpoint. This can be done using `cURL` command below. Note that the GUID will be different for each ingest. The GUID can be determined by going to the `<${branding}_HOME>/content/store` directory and copying the sub-directory in this folder (there should only be one).

.Windows Example
[source,terminal]
----
curl -X GET ${secure_url}/services/content/c90147bf86294d46a9d35ebbd44992c5
----

.*NIX Example
[source,terminal]
----
curl -X GET ${secure_url}/services/content/c90147bf86294d46a9d35ebbd44992c5
----

The response to the GET command will be the contents of the file originally ingested.
