:title: Managing Keystores
:type: subInstalling
:status: published
:parent: Installing With the ${branding} Distribution Zip
:summary: Managing keystores.
:order: 03

== {title}

(((Keystores)))Certificates, and sometimes their associated private keys, are stored in keystore files.
${branding} includes two default keystore files, the server key store and the server trust store.
The server keystore holds ${branding}'s certificate and private key.
It also holds the certificates of other nodes whose signature ${branding} accept.
(((Truststore)))The truststore holds the certificates of nodes or other entities that ${branding} needs to trust.

[NOTE]
====
Individual certificates of other nodes should be added to the keystore instead of CA certificates.
If a CA's certificate is added, ${branding} automatically trusts any certificate that is signed by that CA.
====

=== Adding an Existing Server Keystore

If provided an existing keystore for use with ${branding}, follow these steps to replace the default keystore.

. Remove the default keystore at `etc/keystores/serverKeystore.jks`.
. Add the desired keystore file to the `etc/keystores` directory.
. Edit `custom.system.properties` file to set filenames and passwords.
.. If using a type of keystore other than `jks` (such as `pkcs12`), change the `javax.net.ssl.keyStoreType` property as well.
. If the truststore has the correct certificates, restart server to complete configuration.
.. If provided with an existing server truststore, continue to <<{managing-prefix}adding_an_existing_server_truststore,Adding an Existing Server Truststore>>.
.. Otherwise, <<{managing-prefix}creating_a_server_keystore,create a server truststore>>.

=== Adding an Existing Server Truststore

. Remove the default truststore at `etc/keystores/serverTruststore.jks`.
. Add the desired truststore file to the `etc/keystores` directory.
. Edit `custom.system.properties` file to set filenames and passwords.
.. If using a type of truststore other than `jks` (such as `pkcs12`), change the `javax.net.ssl.trustStoreType` property as well.

If the provided server keystore does not include the CA certificate that was used to sign the server's certificate, <<{managing-prefix}creating_a_server_keystore,add the CA certificate into the `serverKeystore` file>>.

.Trust Chain[[_trust_chain]]
[NOTE]
====
All CAs in the trust chain, including all intermeditate certificates, must be included in the trust store.
====

=== Creating a New Keystore / Truststore with an Existing Certificate and Private Key

If provided an existing certificate, create a new keystore and truststore with it.
Use a tool such as the standard Java https://docs.oracle.com/en/java/javase/17/docs/specs/man/keytool.html[keytool certificate management utility] {external-link}.


[NOTE]
====
${branding} requires that the keystore contains both the private key and the CA.
====

. [[_creating_a_server_keystore]]Using the private key, certificate, and CA certificate, create a new keystore containing the data from the new files.
+
[source]
----
cat client.crt >> client.key
openssl pkcs12 -export -in client.key -out client.p12
keytool -importkeystore -srckeystore client.p12 -destkeystore serverKeystore.jks -srcstoretype pkcs12 -alias 1
keytool -changealias -alias 1 -destalias client -keystore serverKeystore.jks
keytool -importcert -file ca.crt -keystore serverKeystore.jks -alias "ca"
keytool -importcert -file ca-root.crt -keystore serverKeystore.jks -alias "ca-root"
----
+
. [[_creating_a_server_truststore]]Create the truststore using only the CA certificate. Based on the concept of CA signing, the CA should be the only entry needed in the truststore.
+
----
keytool -import -trustcacerts -alias "ca" -file ca.crt -keystore truststore.jks
keytool -import -trustcacerts -alias "ca-root" -file ca-root.crt -keystore truststore.jks
----
+
. Create a PEM file using the certificate, as some applications require that format.
+
----
openssl x509 -in client.crt -out client.der -outform DER
openssl x509 -in client.der -inform DER -out client.pem -outform PEM
----

[IMPORTANT]
====
The localhost certificate must be removed if using a system certificate.
====

[IMPORTANT]
====
The default trust store and key store files for ${branding} included in `etc/keystores` use self-signed certificates.
Self-signed certificates should never be used outside of development/testing areas.
====

The name and location of the ${branding} trust and key stores can be changed by editing the system properties files, `etc/custom.system.properties`.
Additionally, the password that ${branding} uses to decrypt (unlock) the key and trust stores can be changed here.

.Keystore Password[[_keystore_password]]
[IMPORTANT]
====
${branding} assumes that password used to unlock the keystore is the same password that unlocks private keys in the keystore.
====

The location, file name, passwords, type of the server, and trust key stores can be set in the `custom.system.properties` file:

. Setting the Keystore and Truststore Java Properties
[source]
----
javax.net.ssl.keyStore=etc/keystores/serverKeystore.jks
javax.net.ssl.keyStorePassword=changeit
javax.net.ssl.trustStore=etc/keystores/serverTruststore.jks
javax.net.ssl.trustStorePassword=changeit
javax.net.ssl.keyStoreType=jks
javax.net.ssl.trustStoreType=jks
----

[NOTE]
====
If the server's fully qualified domain name is not recognized, the name may need to be added to the network's DNS server.
====

[TIP]
====
The ${branding} instance can be tested even if there is no entry for the FQDN in the DNS.
First, test if the FQDN is already recognized.
Execute this command:

`ping <FQDN>`

If the command responds with an error message such as unknown host, then modify the system's `hosts` file to point the server's FQDN to the loopback address.
For example:

`127.0.0.1 <FQDN>`
====

.Changing Default Passwords
[NOTE]
====
This step is not required for a hardened system.

* The default password in `custom.system.properties` for `serverKeystore.jks` is `changeit`. This needs to be modified.
** `ds-cfg-key-store-file: ../../keystores/serverKeystore.jks`
** `ds-cfg-key-store-type: JKS`
** `ds-cfg-key-store-pin: password`
** `cn: JKS`
* The default password in `custom.system.properties` for `serverTruststore.jks` is `changeit`.  This needs to be modified.
** `ds-cfg-trust-store-file: ../../keystores/serverTruststore.jks`
** `ds-cfg-trust-store-pin: password`
** `cn: JKS`
====
