:title: SearchUI Transformer
:type: transformer
:subtype: queryResponse
:status: published
:link: _searchui_transformer
:summary: Provides results in html format and a convenient, simple querying user interface.

The Simple SearchUI is a `QueryResponseTransformer` that provides results in html format and a convenient, simple querying user interface.
It is primarily used as a test tool and verification of configuration.
The left pane of the Simple SearchUI contains basic fields to query the Catalog and other Sources.
The right pane consists of the results returned from the query.

===== Installing Simple SearchUI

This transformer is installed by default with a standard installation in the ${ddf-catalog} application as the feature, `catalog-transformer-ui`.

===== Configuring Simple SearchUI

From the ${admin-console}, the Simple SearchUI can be configured under the *Catalog HTML Query Response Transformer*.

See <<org.codice.ddf.ui.search.simple.properties,Simple Search UI configurations>> for all possible configurations.

===== Using Simple SearchUI

In order to access the Simple SearchUI, a user must use the transformer with an endpoint that queries the Catalog, such as the OpenSearch Endpoint.
If a distribution is running locally, ${secure_url}/search/simple should bring up the Simple Search UI.
After the page has loaded, enter the desired search criteria in the appropriate fields.
Then click the "*Search*" button in order to execute the search on the Catalog.

The "*Clear*" button will reset the query criteria specified.

.Simple SearchUI Query Response Result Mapping
[cols="1,2m,3" options="header"]
|===

|Simple SearchUI Column Title
|Catalog Result
|Notes

|Title
|Metacard.TITLE
|The title may be hyperlinked to view the full Metacard.

|Source
|Metacard.getSourceId()
|Source where the Metacard was discoved.

|Location
|Metacard.LOCATION
|Geographical location of the Metacard.

|Time
|Metacard.CREATED or Metacard.EFFECTIVE
|Time received/created.

|Thumbnail
|Metacard.THUMBNAIL
|Column not shown if no results have thumbnail.

|Resource
|Metacard.RESOURCE_URI
|Column not shown if no results have a resource.

|===

====== Search Criteria

The Simple SearchUI allows for querying a Catalog in the following methods:

Keyword Search:: searching with keywords using the grammar of the underlying endpoint/Catalog.
Temporal Search:: searching based on relative or absolute time.
Spatial search:: searching spatially with a Point-Radius or Bounding Box.
Content Type Search:: searching for specific `Metacard.CONTENT_TYPE` values

===== Usage Limitations of the Simple SearchUI

* If the Simple SearchUI results do not provide usable links on the metacard results, verify that a valid host has been entered in the Platform Global Configuration.

'''
