:title: XML Query Response Transformer
:type: transformer
:subtype: queryResponse
:status: published
:link: _xml_query_response_transformer
:summary: Translates a query response into an XML-formatted document.

The XML Query Response Transformer is responsible for translating a query response into an XML-formatted document.
The metacard element generated is an extension of `gml:AbstractFeatureCollectionType`, which makes the output of this transformer http://www.opengeospatial.org/projects/groups/gmldwg[GML 3.1.1] compatible.

===== Installing the XML Query Response Transformer

This transformer is installed by default with a standard installation in the ${ddf-catalog} application.
To uninstall, uninstall the `catalog-transformer-xml` feature.

===== Configuring the XML Query Response Transformer

To configure the XML Query Response Transformer:

. Navigate to the *${admin-console}*.
. Select the *${ddf-catalog}* application.
. Select the *Configuration* tab.
. Select the XML Query Response Transformer.


See <<{reference-prefix}ddf.catalog.transformer.xml.XmlResponseQueueTransformer,XML Query Response Transformer configurations>> for all possible configurations.

===== Using the XML Query Response Transformer

Using the OpenSearch Endpoint, for example, query with the format option set to the XML shortname `xml`.

.XML Query Response Transformer Query Example
[source,http]
----
${public_url}/services/catalog/query?q=input?format=xml
----

.XML Query Response Transformer Example Output
[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns3:metacards xmlns:ns1="http://www.opengis.net/gml" xmlns:ns2="http://www.w3.org/1999/xlink" xmlns:ns3="urn:catalog:metacard" xmlns:ns4="http://www.w3.org/2001/SMIL20/" xmlns:ns5="http://www.w3.org/2001/SMIL20/Language">
    <ns3:metacard ns1:id="000ba4dd7d974e258845a84966d766eb">
        <ns3:type>ddf.metacard</ns3:type>
        <ns3:source>southwestCatalog1</ns3:source>
        <ns3:dateTime name="created">
          <ns3:value>2013-04-10T15:30:05.702-07:00</ns3:value>
        </ns3:dateTime>
        <ns3:string name="title">
            <ns3:value>Input 1</ns3:value>
        </ns3:string>
    </ns3:metacard>
    <ns3:metacard ns1:id="00c0eb4ba9b74f8b988ef7060e18a6a7">
        <ns3:type>ddf.metacard</ns3:type>
        <ns3:source>southwestCatalog1</ns3:source>
        <ns3:dateTime name="created">
          <ns3:value>2013-04-10T15:30:05.702-07:00</ns3:value>
        </ns3:dateTime>
        <ns3:string name="title">
            <ns3:value>Input 2</ns3:value>
        </ns3:string>
    </ns3:metacard>
</ns3:metacards>
----

'''
