:title: Metrics Reporting Application
:type: architecture
:status: published
:parent: Metrics
:children: Viewing Metrics
:order: 01
:summary: Metrics Reporting Application.

The ${branding} Metrics Reporting Application provides access to historical data in several formats: a graphic, a comma-separated values file, a spreadsheet, a PowerPoint file, XML, and JSON formats for system metrics collected while ${branding} is running.
Aggregate reports (weekly, monthly, and yearly) are also provided where all collected metrics are included in the report.
Aggregate reports are available in Excel and PowerPoint formats.

To use the Metrics Reporting Application:

. Navigate to the *${admin-console}*.
. Select the *${ddf-platform}* Application.
. Select the *Metrics* tab.

With each metric in the list, a set of hyperlinks is displayed under each column.
Each column's header is displayed with the available time ranges. The time ranges currently supported are 15 minutes, 1 hour, 1 day, 1 week, 1 month, 3 months, 6 months, and 1 year, measured from the time that the hyperlink is clicked.

All metrics reports are generated by accessing the collected metric data stored in the `${home_directory}/data/metrics` directory.
All files in this directory are generated by the JmxCollector using RRD4J, a Round Robin Database for a Java open source product.
All files in this directory will have the `.rrd` file extension and are binary files, hence they cannot be opened directly.
These files should only be accessed using the Metrics tab's hyperlinks.
There is one RRD file per metric being collected.
Each RRD file is sized at creation time and will never increase in size as data is collected.
One year's worth of metric data requires approximately 1 MB file storage.

[WARNING]
====
Do not remove the `${home_directory}/data/metrics` directory or any files in the directory.
If this is done, all existing metrics data will be permanently lost.

Also note that if ${branding} is uninstalled/re-installed, all existing metrics data will be permanently lost.
====

Hyperlinks are provided for each metric and each format in which data can be displayed.
For example, the PNG hyperlink for 15m for the Catalog Queries metric maps to \${secure_url}/services/internal/metrics/catalogQueries.png?dateOffset=900, where the `dateOffset=900` indicates the previous 900 seconds (15 minutes) to be graphed.

Note that the date format will vary according to the regional/locale settings for the server.

All of the metric graphs displayed are in PNG format and are displayed on their own page. 
The user may use the back button in the browser to return to the ${admin-console}, or, when selecting the hyperlink for a graph, they can use the right mouse button in the browser to display the graph in a separate browser tab or window, which will keep the ${admin-console} displayed.
The user can also specify custom time ranges by adjusting the URL used to access the metric's graph.
The Catalog Queries metric data may also be graphed for a specific time range by specifying the `startDate` and `endDate` query parameters in the URL.

For example, to map the Catalog Queries metric data for March 31, 6:00 am, to April 1, 2013, 11:00 am, (Arizona timezone, which is -07:00) the URL would be: 

[source,http]
----
${secure_url}/services/internal/metrics/catalogQueries.png?startDate=2013-03-31T06:00:00-07:00&endDate=2013-04-01T11:00:00-07:00
----

Or to view the last 30 minutes of data for the Catalog Queries metric, a custom URL with a `dateOffset=1800` (30 minutes in seconds) could be used:

[source,http]
----
${secure_url}/services/internal/metrics/catalogQueries.png?dateOffset=1800
----

==== Metrics Aggregate Reports

The Metrics tab also provides aggregate reports for the collected metrics.
These are reports that include data for all of the collected metrics for the specified time range.

The aggregate reports provided are:

* Weekly reports for each week up to the past four *complete* weeks from current time. A complete week is defined as a week from Monday through Sunday. For example, if current time is Thursday, April 11, 2013, the past complete week would be from April 1 through April 7.
* Monthly reports for each month up to the past 12 *complete* months from current time. A complete month is defined as the full month(s) preceding current time. For example, if current time is Thursday, April 11, 2013, the past complete 12 months would be from April 2012 through March 2013.
* Yearly reports for the past *complete* year from current time.  A complete year is defined as the full year preceding current time. For example, if current time is Thursday, April 11, 2013, the past complete year would be 2012.

An aggregate report in XLS format would consist of a single workbook (spreadsheet) with multiple worksheets in it, where a separate worksheet exists for each collected metric's data. Each worksheet would display:

* the metric's name and the time range of the collected data, 
* two columns: Timestamp and Value, for each sample of the metric's data that was collected during the time range, and
* a total count (if applicable) at the bottom of the worksheet.

An aggregate report in PPT format would consist of a single slideshow with a separate slide for each collected metric's data. Each slide would display:

* a title with the metric's name.
* the PNG graph for the metric's collected data during the time range.
* a total count (if applicable) at the bottom of the slide.

Hyperlinks are provided for each aggregate report's time range in the supported display formats, which include Excel (XLS) and PowerPoint (PPT). Aggregate reports for custom time ranges can also be accessed directly via the URL: 
----
${secure_url}/services/internal/metrics/report.<format>?startDate=<start_date_value>&endDate=<end_date_value>
----
where `<format>` is either `xls` or `ppt` and the `<start_date_value>` and `<end_date_value>` specify the custom time range for the report.

These example reports represent custom aggregate reports.
NOTE: all example URLs begin with \${secure_url}, which is omitted in the table for brevity.

.Example Aggregate Reports
[cols="2" options="header"]
|===

|Description
|URL

|XLS aggregate report for March 15, 2013 to April 15, 2013
|`/services/internal/metrics/report.xls?startDate=2013-03-15T12:00:00-07:00&endDate=2013-04-15T12:00:00-07:00`

|XLS aggregate report for last 8 hours
|`/services/internal/metrics/report.xls?dateOffset=28800`

|PPT aggregate report for March 15, 2013 to April 15, 2013
|`/services/internal/metrics/report.ppt?startDate=2013-03-15T12:00:00-07:00&endDate=2013-04-15T12:00:00-07:00`

|PPT aggregate report for last 8 hours
|`/services/internal/metrics/report.ppt?dateOffset=28800`

|===
