:title: Application Commands
:type: subMaintaining
:status: published
:parent: Available Console Commands
:summary: Application commands available.
:order: 01

== {title}

Application commands are installed with the ${ddf-admin} application to manage applications in the ${branding}.

[NOTE]
====
The Application Commands are installed automatically with the ${ddf-admin} Application.
====

.[[app_command_descriptions]]App Command Descriptions
[cols="1m,5" options="header"]
|===

|Command
|Description

|app:add
|Adds an application with the given uri.

|app:remove
|Removes an application with the given name.

|app:start
|Starts an application with the given name.

|app:stop
|Stops an application with the given name.

|app:list
|Lists the applications that are in the system and gives their current state.

|app:status
|Shows status of an application.
Gives information on the current state, features within the application, and if any features and bundles are not started.

|app:tree
|Creates a hierarchy tree of all of the applications.

|===

.Application Command Usage
Use `app:list` to show all applications installed in ${branding}.

.Listing All Applications
[source]
----
${branding-lowercase}${at-symbol}local>app:list
State      Name
[ACTIVE  ] catalog-app-<VERSION>
[ACTIVE  ] distribution-<VERSION>
[ACTIVE  ] platform-app-<VERSION>

[...]
----

From here, use the name of an application to get more information on its status.

.Getting Status for a Specific Application
[source]
----
${branding-lowercase}${at-symbol}local>app:status catalog-app-<VERSION>
catalog-app-<VERSION>

Current State is: ACTIVE

Features Located within this Application:
    catalog-security-filter
    catalog-transformer-resource
    catalog-rest-endpoint
    abdera
    catalog-transformer-xml
    catalog-transformer-thumbnail
    catalog-transformer-metadata
    catalog-transformer-xsltengine
    catalog-core-fanoutframework
    catalog-transformer-tika
    catalog-core-api
    catalog-opensearch-source
    catalog-plugin-federationreplication
    catalog-opensearch-endpoint
    catalog-schematron-plugin
    catalog-transformer-geoformatter
    catalog-transformer-atom
    catalog-core-sourcemetricsplugin
    catalog-core-metricsplugin
    catalog-app
    catalog-transformer-json
    catalog-core-standardframework
    catalog-core

Required Features Not Started
    NONE

Required Bundles Not Started
    NONE

----

.Application in Failed State
If an application is in a `FAILED` state, it means that there is a required feature or bundle that is not started.

.App in Failed State
[source]
----
${branding-lowercase}${at-symbol}local>app:list
State      Name
[FAILED  ] catalog-app-<VERSION>
[ACTIVE  ] distribution-<VERSION>
[ACTIVE  ] platform-app-<VERSION>
----

In the above case, the catalog app is in a failed state.
Checking the status of that application will show what did not start correctly.

.Check Application Status
[source]
----
${branding-lowercase}${at-symbol}local>app:status catalog-app-<VERSION>
catalog-app-<VERSION>

Current State is: FAILED

Features Located within this Application:
    catalog-security-filter
    catalog-transformer-resource
    catalog-rest-endpoint
    abdera
    catalog-transformer-xml
    catalog-transformer-thumbnail
    catalog-transformer-metadata
    catalog-transformer-xsltengine
    catalog-core-fanoutframework
    catalog-transformer-tika
    catalog-core-api
    catalog-opensearch-source
    catalog-plugin-federationreplication
    catalog-opensearch-endpoint
    catalog-schematron-plugin
    catalog-transformer-geoformatter
    catalog-transformer-atom
    catalog-core-sourcemetricsplugin
    catalog-core-metricsplugin
    catalog-app
    catalog-transformer-json
    catalog-core-standardframework
    catalog-core

Required Features Not Started
    NONE

Required Bundles Not Started
    [261]   catalog-opensearch-endpoint
----

This status shows that bundle `261`, the `catalog-opensearch-endpoint`, did not start. Performing an `app:list` command on the console verifies this:

[source]
----
${branding-lowercase}${at-symbol}local>app:list
[ 261] [Resolved   ] [            ] [       ] [   80] DDF :: Catalog :: OpenSearch :: Endpoint (<VERSION>)
----

Once that bundle is started by fixing its error, the catalog application will show as being in an ACTIVE state.
