:title: Run ${branding} as a Managed Service
:type: startingIntro
:status: published
:summary: Install ${branding} as a Service.
:project: ${branding}
:order: 07

==== {title}

===== Running as a Service with Automatic Start on System Boot

Because ${branding} is built on top of Apache Karaf, ${branding} can use the Karaf Wrapper to run ${branding} as a service and enable automatic startup and shutdown.
When ${branding} is started using Karaf Wrapper, new `wrapper.log` and `wrapper.log.n` (where n goes from 1 to 5 by default) log files will be generated to include wrapper and console specific information.

[WARNING]
====
When installing as a service on *NIX, do not use spaces in the path for ${home_directory} as the service scripts that are generated by the wrapper cannot handle spaces.
====
[WARNING]
====
Ensure that JAVA_HOME is properly set before beginning this process.
See <<{introduction-prefix}java_requirements,Java Requirements>>
====

. Create the service wrapper.
+
${branding} can create native scripts and executable files to run itself as
an operating system service. This is an optional feature that is not installed by default.
To install the service wrapper feature, go the ${branding} console and enter the command:
+
`${branding-lowercase}${at-symbol}local> feature:install -r wrapper`

. Generate the script, configuration, and executable files:
+
.*NIX
----
${branding-lowercase}${at-symbol}local> wrapper:install -i setenv-wrapper.conf -n ${branding-lowercase} -d ${branding-lowercase} -D "${branding} Service"
----
+
.Windows
----
${branding-lowercase}${at-symbol}local> wrapper:install -i setenv-windows-wrapper.conf -n ${branding-lowercase} -d ${branding-lowercase} -D "${branding} Service"
----
. (Windows users skip this step) (All *NIX) If ${branding} was installed to run as a non-root
user (as-recommended,) edit `${home_directory}/bin/${branding-lowercase}-service` and change
the property `#RUN_AS_USER=` to:
+
.${home_directory}/bin/${branding-lowercase}-service
----
RUN_AS_USER=<${branding-lowercase}-user>
----
where <${branding-lowercase}-user> is the intended username:
. (Windows users skip down) (All *NIX) Edit `${home_directory}/bin/${branding-lowercase}-service`.
Add `LimitNOFILE` to the [Service] section.
+
.${home_directory}/bin/${branding-lowercase}.service
----
LimitNOFILE=6815744
----
+
. (Windows users skip this step) (*NIX _with_ `systemd`) Install the wrapper startup/shutdown scripts.
+

Install the service and start it when the system boots, use `systemctl` From an OS console, execute:
+
`root${at-symbol}localhost# systemctl enable ${home_directory}/bin/${branding-lowercase}.service`

. (Windows users skip this step) (*NIX _without_ `systemd`) Install the wrapper startup/shutdown scripts.
+
If the system does not use `systemd`, use the `init.d` system to install and configure the service.
Execute these commands as root or superuser:
+
----
root${at-symbol}localhost# ln -s ${home_directory}/bin/${branding-lowercase}-service /etc/init.d/
root${at-symbol}localhost# chkconfig ${branding-lowercase}-service --add
root${at-symbol}localhost# chkconfig ${branding-lowercase}-service on
----
. (Windows only, if the system's `JAVA_HOME` variable has spaces in it) Edit `${home_directory}/etc/${branding-lowercase}-wrapper.conf`.
Put quotes around `wrapper.java.additional.n` system properties for n from 1 to 13 like so:
+
.${home_directory}/etc/${branding-lowercase}-wrapper.conf
----
wrapper.java.additional.1=-Djava.endorsed.dirs="%JAVA_HOME%/jre/lib/endorsed;%JAVA_HOME%/lib/endorsed;%KARAF_HOME%/lib/endorsed"
wrapper.java.additional.2=-Djava.ext.dirs="%JAVA_HOME%/jre/lib/ext;%JAVA_HOME%/lib/ext;%KARAF_HOME%/lib/ext"
wrapper.java.additional.3=-Dkaraf.instances="%KARAF_HOME%/instances"
wrapper.java.additional.4=-Dkaraf.home="%KARAF_HOME%"
wrapper.java.additional.5=-Dkaraf.base="%KARAF_BASE%"
wrapper.java.additional.6=-Dkaraf.data="%KARAF_DATA%"
wrapper.java.additional.7=-Dkaraf.etc="%KARAF_ETC%"
wrapper.java.additional.8=-Dkaraf.restart.jvm.supported=true
wrapper.java.additional.9=-Djava.io.tmpdir="%KARAF_DATA%/tmp"
wrapper.java.additional.10=-Djava.util.logging.config.file="%KARAF_BASE%/etc/java.util.logging.properties"
wrapper.java.additional.11=-Dcom.sun.management.jmxremote
wrapper.java.additional.12=-Dkaraf.startLocalConsole=false
wrapper.java.additional.13=-Dkaraf.startRemoteShell=true
----

. (Windows only) Install the wrapper startup/shutdown scripts.
+
Run the following command in a console window. The command must be run with elevated permissions.
+
----
${home_directory}\bin\${branding-lowercase}-service.bat install
----
Startup and shutdown settings can then be managed through *Services -> MMC Start -> Control Panel -> Administrative Tools -> Services*.


===== Karaf Documentation

Because ${branding} is built on top of Apache Karaf, more information on operating ${branding} can be found in the http://karaf.apache.org/index/documentation.html[Karaf documentation] {external-link}.

