:title: Starting Intro
:type: startingIntro
:status: published
:summary: Starting and stopping an instance.
:order: 01

Follow the below steps to start and stop ${branding}.

.Memory Considerations[[_jvm_memory_configuration]]
[NOTE]
====
If the ${branding} will be running memory-intensive applications, consider increasing the java memory. The java memory can be changed by updating the setenv script:

.Setenv Scripts: *NIX
----
${home_directory}/bin/setenv
Update the JAVA_OPTS -Xmx value
${home_directory}/bin/setenv-wrapper.conf
Update the wrapper.java.additional -Xmx value
----

.Setenv Scripts: Windows
----
${home_directory}/bin/setenv.bat
Update the JAVA_OPTS -Xmx value
${home_directory}/bin/setenv-windows-wrapper.conf
Update the wrapper.java.additional -Xmx value
----
====

.Solr Memory Considerations
[NOTE]
====
If the ${branding} will be ingesting many records at a time, consider increasing the `solr.max.heap.size` in the `system.properties` file. More information can be found in the https://lucene.apache.org/solr/guide/7_4/taking-solr-to-production.html[Solr documentation].
====

.JMX Connectivity Considerations
[NOTE]
====
[[jmx-connectivity-configuration]]
By default the ${branding} prevents connections to JMX. To monitor the ${branding} via tools such as JConsole, consider removing the no attach mechanism by updating the setenv script:

.Setenv Scripts: *NIX
----
${home_directory}/bin/setenv
Remove -XX:+DisableAttachMechanism from JAVA_OPTS
${home_directory}/bin/setenv-wrapper.conf
Comment out the -XX:+DisableAttachMechanism line and re-number remainder lines appropriately
----

.Setenv Scripts: Windows
----
${home_directory}/bin/setenv.bat
Remove -XX:+DisableAttachMechanism from JAVA_OPTS
${home_directory}/bin/setenv-windows-wrapper.conf
Comment out the -XX:+DisableAttachMechanism line and re-number remainder lines appropriately
----
====

==== Starting from Startup Scripts

Run one of the start scripts from a command shell to start the distribution and open a local console:

.Start Script: *NIX
----
${home_directory}/bin/${branding-lowercase}
----

.Start Script: Windows
----
${home_directory}/bin/${branding-lowercase}.bat
----

==== Starting as a Background Process

Alternatively, to run ${branding} as a background process, run the `start` script:

.*NIX
----
${home_directory}/bin/start
----

.Windows
----
${home_directory}/bin/start.bat
----

[NOTE]
====
If console access is needed while running as a service, run the `client` script on the host where the ${branding} is running:

.*NIX
----
${home_directory}/bin/client
----

.Windows
----
${home_directory}/bin/client.bat -h <FQDN>
----

Use the `-h` option followed by the name (`<FQDN>`) or IP of the host where ${branding} is running.
U
====

==== Stopping ${branding}

There are two options to stop a running instance:

* Call shutdown from the console:

.Shut down with a prompt
----
${branding-lowercase}${at-symbol}local>shutdown
----

.Force Shutdown without prompt
----
${branding-lowercase}${at-symbol}local>shutdown -f
----

* Keyboard shortcut for shutdown
** `Ctrl`-`D`
** `Cmd`-`D`
* Or run the stop script:

.*NIX
----
${home_directory}/bin/stop
----

.Windows
----
${home_directory}/bin/stop.bat
----

.Shut Down
[IMPORTANT]
====
Do not shut down by closing the window (Windows, Unix) or using the `kill -9 <pid>` command (Unix).
This prevents a clean shutdown and can cause significant problems when ${branding} is restarted.
Always use the shutdown command or the shortcut from the command line console.
====
