:title: Starting Intro
:type: startingIntro
:status: published
:summary: Starting and stopping an instance.
:order: 01

Follow the below steps to start and stop ${branding}.

.Memory Considerations[[jvm-memory-configuration]]
[NOTE]
====
If the ${branding} will be running memory-intensive applications, consider increasing the java memory. The java memory can be changed by updating the setenv script:

.Setenv Scripts: *NIX
----
${home_directory}/bin/setenv
Update the JAVA_OPTS -Xmx value
${home_directory}/bin/setenv-wrapper.conf
Update the wrapper.java.additional -Xmx value
----

.Setenv Scripts: Windows
----
${home_directory}/bin/setenv.bat
Update the JAVA_OPTS -Xmx value
${home_directory}/bin/setenv-windows-wrapper.conf
Update the wrapper.java.additional -Xmx value
----
====

.JMX Connectivity Considerations
[NOTE]
====
[[jmx-connectivity-configuration]]
By default the ${branding} prevents connections to JMX. To monitor the ${branding} via tools such as JConsole, consider removing the no attach mechanism by updating the setenv script:

.Setenv Scripts: *NIX
----
${home_directory}/bin/setenv
Remove -XX:+DisableAttachMechanism from JAVA_OPTS
${home_directory}/bin/setenv-wrapper.conf
Comment out the -XX:+DisableAttachMechanism line and re-number remainder lines appropriately
----

.Setenv Scripts: Windows
----
${home_directory}/bin/setenv.bat
Remove -XX:+DisableAttachMechanism from JAVA_OPTS
${home_directory}/bin/setenv-windows-wrapper.conf
Comment out the -XX:+DisableAttachMechanism line and re-number remainder lines appropriately
----
====

==== Starting from Startup Scripts

Run one of the start scripts from a command shell to start the distribution and open a local console:

.Start Script: *NIX
----
${home_directory}/bin/${branding-lowercase}
----

.Start Script: Windows
----
${home_directory}/bin/${branding-lowercase}.bat
----

==== Starting as a Background Process

Alternatively, to run ${branding} as a background process, run the `start` script:

.*NIX
----
${home_directory}/bin/start
----

.Windows
----
${home_directory}/bin/start.bat
----

[NOTE]
====
If console access is needed while running as a service, run the `client` script on the host where the ${branding} is running:

.*NIX
----
${home_directory}/bin/client
----

.Windows
----
${home_directory}/bin/client.bat -h <FQDN>
----

Use the `-h` option followed by the name (`<FQDN>`) or IP of the host where ${branding} is running.
U
====

==== Stopping ${branding}

There are two options to stop a running instance:

* Call shutdown from the console:

.Shut down with a prompt
----
${branding-lowercase}${at-symbol}local>shutdown
----

.Force Shutdown without prompt
----
${branding-lowercase}${at-symbol}local>shutdown -f
----

* Keyboard shortcut for shutdown
** `Ctrl`-`D`
** `Cmd`-`D`
* Or run the stop script:

.*NIX
----
${home_directory}/bin/stop
----

.Windows
----
${home_directory}/bin/stop.bat
----

.Shut Down
[IMPORTANT]
====
Do not shut down by closing the window (Windows, Unix) or using the `kill -9 <pid>` command (Unix).
This prevents a clean shutdown and can cause significant problems when ${branding} is restarted.
Always use the shutdown command or the shortcut from the command line console.
====

==== Starting as a Service with Automatic Start on System Boot

Because ${branding} is built on top of Apache Karaf, ${branding} can use the Karaf Wrapper to run ${branding} as a service and enable automatic startup and shutdown. 
When ${branding} is started using Karaf Wrapper, new `wrapper.log` and `wrapper.log.n` (where n goes from 1 to 5 by default) log files will be generated to include wrapper and console specific information.

[WARNING]
====
When installing as a service on *NIX, do not use spaces in the path for ${home_directory} as the service scripts that are generated by the wrapper can not handle spaces.
====

. Create the Karaf wrapper.
+
Within the ${branding} console:
+
.*NIX
----
${branding-lowercase}${at-symbol}local> feature:install -r wrapper
${branding-lowercase}${at-symbol}local> wrapper:install -i setenv-wrapper.conf -s AUTO_START -n ${branding-lowercase} -d ${branding-lowercase} -D "${branding} Service"
----
+
.Windows
----
${branding-lowercase}${at-symbol}local> feature:install -r wrapper
${branding-lowercase}${at-symbol}local> wrapper:install -i setenv-windows-wrapper.conf -s AUTO_START -n ${branding-lowercase} -d ${branding-lowercase} -D "${branding} Service"
----
+
. (Windows users skip to next step) (All *NIX) If ${branding} was installed to run as a non-root user (recommended,) edit `${home_directory}/bin/${branding-lowercase}-service`.
+
Change:
+
.${home_directory}/bin/${branding-lowercase}-service
----
#RUN_AS_USER=
----
+
to (<${branding-lowercase}-user> is the intended username):
+
.${home_directory}/bin/${branding-lowercase}-service
----
RUN_AS_USER=<${branding-lowercase}-user>
----
+
. (Windows users skip to next step) (All *NIX) Edit `${home_directory}/bin/${branding-lowercase}-service`. Add LimitNOFILE to the [Service] section.
+
.${home_directory}/bin/${branding-lowercase}.service
----
LimitNOFILE=6815744
----
+
. Install the wrapper startup/shutdown scripts.
+
*Windows*
+
Run the following command in a console window. The command must be run with elevated permissions.
+
----
${home_directory}\bin\${branding-lowercase}-service.bat install
----
Startup and shutdown settings can then be managed through *Services -> MMC Start -> Control Panel -> Administrative Tools -> Services*.
+
*Redhat, Fedora, or Centos (SystemV)*
+
----
root${at-symbol}localhost# ln -s ${home_directory}/bin/${branding-lowercase}-service /etc/init.d/
root${at-symbol}localhost# chkconfig ${branding-lowercase}-service --add
root${at-symbol}localhost# chkconfig ${branding-lowercase}-service on
----
+
*Redhat 7 or Centos 7 (systemd)*
+
----
root${at-symbol}localhost# systemctl enable ${home_directory}/bin/${branding-lowercase}.service
----
+
*Ubuntu*
+
----
root${at-symbol}localhost# ln -s ${home_directory}/bin/${branding-lowercase}-service /etc/init.d/
root${at-symbol}localhost# update-rc.d -f ${branding-lowercase}-service defaults
----
+
[NOTE]
====
If the system fails to start automatically on boot with any messages about the JVM, ensure that JAVA_HOME is properly set. <<_java_requirements_quick_install,Java Requirements (Quick Install)>>
====

===== Karaf Documentation

Because ${branding} is built on top of Apache Karaf, more information on operating ${branding} can be found in the http://karaf.apache.org/index/documentation.html[Karaf documentation].

