:title: Starting Intro
:type: startingIntro
:status: published
:summary: Starting and stopping an instance.
:order: 01

Follow the below steps to start and stop ${branding}.

.Memory Considerations[[_jvm_memory_configuration]]
[NOTE]
====
If the ${branding} will be running memory-intensive applications, consider increasing the java memory. The java memory can be changed by updating the setenv script:

.Setenv Scripts: *NIX
----
${home_directory}/bin/setenv
Update the JAVA_OPTS -Xmx value
${home_directory}/bin/setenv-wrapper.conf
Update the wrapper.java.additional -Xmx value
----

.Setenv Scripts: Windows
----
${home_directory}/bin/setenv.bat
Update the JAVA_OPTS -Xmx value
${home_directory}/bin/setenv-windows-wrapper.conf
Update the wrapper.java.additional -Xmx value
----
====

.JMX Connectivity Considerations
[NOTE]
====
[[jmx-connectivity-configuration]]
By default the ${branding} prevents connections to JMX. To monitor the ${branding} via tools such as JConsole, consider removing the no attach mechanism by updating the setenv script:

.Setenv Scripts: *NIX
----
${home_directory}/bin/setenv
Remove -XX:+DisableAttachMechanism from JAVA_OPTS
${home_directory}/bin/setenv-wrapper.conf
Comment out the -XX:+DisableAttachMechanism line and re-number remainder lines appropriately
----

.Setenv Scripts: Windows
----
${home_directory}/bin/setenv.bat
Remove -XX:+DisableAttachMechanism from JAVA_OPTS
${home_directory}/bin/setenv-windows-wrapper.conf
Comment out the -XX:+DisableAttachMechanism line and re-number remainder lines appropriately
----
====

==== Starting from Startup Scripts

Run one of the start scripts from a command shell to start the distribution and open a local console:

.Start Script: *NIX
----
${home_directory}/bin/${branding-lowercase}
----

.Start Script: Windows
----
${home_directory}/bin/${branding-lowercase}.bat
----

==== Starting as a Background Process

Alternatively, to run ${branding} as a background process, run the `start` script:

.*NIX
----
${home_directory}/bin/start
----

.Windows
----
${home_directory}/bin/start.bat
----

[NOTE]
====
If console access is needed while running as a service, run the `client` script on the host where the ${branding} is running:

.*NIX
----
${home_directory}/bin/client
----

.Windows
----
${home_directory}/bin/client.bat -h <FQDN>
----

Use the `-h` option followed by the name (`<FQDN>`) or IP of the host where ${branding} is running.
U
====

==== Stopping ${branding}

There are two options to stop a running instance:

* Call shutdown from the console:

.Shut down with a prompt
----
${branding-lowercase}${at-symbol}local>shutdown
----

.Force Shutdown without prompt
----
${branding-lowercase}${at-symbol}local>shutdown -f
----

* Keyboard shortcut for shutdown
** `Ctrl`-`D`
** `Cmd`-`D`
* Or run the stop script:

.*NIX
----
${home_directory}/bin/stop
----

.Windows
----
${home_directory}/bin/stop.bat
----

.Shut Down
[IMPORTANT]
====
Do not shut down by closing the window (Windows, Unix) or using the `kill -9 <pid>` command (Unix).
This prevents a clean shutdown and can cause significant problems when ${branding} is restarted.
Always use the shutdown command or the shortcut from the command line console.
====

==== Starting as a Service with Automatic Start on System Boot

Because ${branding} is built on top of Apache Karaf, ${branding} can use the Karaf Wrapper to run ${branding} as a service and enable automatic startup and shutdown. 
When ${branding} is started using Karaf Wrapper, new `wrapper.log` and `wrapper.log.n` (where n goes from 1 to 5 by default) log files will be generated to include wrapper and console specific information.

[WARNING]
====
When installing as a service on *NIX, do not use spaces in the path for ${home_directory} as the service scripts that are generated by the wrapper can not handle spaces.
====

. Create the Karaf wrapper.
+
Within the ${branding} console:
+
.*NIX
----
${branding-lowercase}${at-symbol}local> feature:install -r wrapper
${branding-lowercase}${at-symbol}local> wrapper:install -i setenv-wrapper.conf -s AUTO_START -n ${branding-lowercase} -d ${branding-lowercase} -D "${branding} Service"
----
+
.Windows
----
${branding-lowercase}${at-symbol}local> feature:install -r wrapper
${branding-lowercase}${at-symbol}local> wrapper:install -i setenv-windows-wrapper.conf -s AUTO_START -n ${branding-lowercase} -d ${branding-lowercase} -D "${branding} Service"
----
+
. (Windows users skip to next step) (All *NIX) If ${branding} was installed to run as a non-root user (recommended,) edit `${home_directory}/bin/${branding-lowercase}-service`.
+
Change:
+
.${home_directory}/bin/${branding-lowercase}-service
----
#RUN_AS_USER=
----
+
to (<${branding-lowercase}-user> is the intended username):
+
.${home_directory}/bin/${branding-lowercase}-service
----
RUN_AS_USER=<${branding-lowercase}-user>
----
+
. (Windows users skip to next step) (All *NIX) Edit `${home_directory}/bin/${branding-lowercase}-service`. Add LimitNOFILE to the [Service] section.
+
.${home_directory}/bin/${branding-lowercase}.service
----
LimitNOFILE=6815744
----
+
. Install the wrapper startup/shutdown scripts.
+
*Windows*
+
Run the following command in a console window. The command must be run with elevated permissions.
+
----
${home_directory}\bin\${branding-lowercase}-service.bat install
----
Startup and shutdown settings can then be managed through *Services -> MMC Start -> Control Panel -> Administrative Tools -> Services*.
+
*Redhat, Fedora, or Centos (SystemV)*
+
----
root${at-symbol}localhost# ln -s ${home_directory}/bin/${branding-lowercase}-service /etc/init.d/
root${at-symbol}localhost# chkconfig ${branding-lowercase}-service --add
root${at-symbol}localhost# chkconfig ${branding-lowercase}-service on
----
+
*Redhat 7 or Centos 7 (systemd)*
+
----
root${at-symbol}localhost# systemctl enable ${home_directory}/bin/${branding-lowercase}.service
----
+
*Ubuntu*
+
----
root${at-symbol}localhost# ln -s ${home_directory}/bin/${branding-lowercase}-service /etc/init.d/
root${at-symbol}localhost# update-rc.d -f ${branding-lowercase}-service defaults
----
+
[NOTE]
====
If the system fails to start automatically on boot with any messages about the JVM, ensure that JAVA_HOME is properly set. <<{introduction-prefix}java_requirements,Java Requirements>>
====

===== Karaf Documentation

Because ${branding} is built on top of Apache Karaf, more information on operating ${branding} can be found in the http://karaf.apache.org/index/documentation.html[Karaf documentation].


==== Automatically Starting Solr as a Process

If ${branding} is configured to start as a service automatically on system boot, then Solr will also need to be configured to start automatically.

*Linux*

From the https://lucene.apache.org/solr/guide/7_4/taking-solr-to-production.html[Solr documentation]:
====
Solr includes a service installation script (bin/install_solr_service.sh) to help you install Solr as a service on Linux. Currently, the script only supports CentOS, Debian, Red Hat, SUSE and Ubuntu Linux distributions.
====

. Locate the Installation Script
+
Identify the Solr distribution installation script (install_solr_service.sh) in the solr directory. By default they are located in  the `${home_directory}/solr/bin` directory.
+

. Prepare the Solr distribution
+
Move all the contents of the solr directory into a new folder named solr-_version_ (where _version_ is `7.4.0` or whichever release is being used) and compress the folder into a tgz or zip.
+

. Run the installation script as root:
+
-----
sudo bash ./install_solr_service.sh solr-version.tgz -p 8994
-----
+
[NOTE]
The `-p 8994` is the default port that ${branding} uses for Solr. If an alternate port is specified here, make sure the system.properties port values for Solr are also updated.
+
By default, the script extracts the distribution archive into /opt, configures Solr to write files into /var/solr, and runs Solr as the solr user. Consequently, the following command produces the same result as the previous command:
+
-----
sudo bash ./install_solr_service.sh solr-7.4.0.tgz -i /opt -d /var/solr -u solr -s solr -p 8994
-----
. Confirm service status
+
To confirm the script has completed and that Solr is running as a service in the background you can type:
+
-----
sudo service solr status
-----
[NOTE]
Review all https://lucene.apache.org/solr/guide/7_4/taking-solr-to-production.html#Fine_Tune_Your_Production_Setup[Solr guidelines] before Taking Solr into production if you plan to run it as a background service.

*Windows*

Windows users will be able to utilize the built in Task Scheduler to start Solr as a background process.

. Install ${branding} and locate the `\solr\bin\` directory in the same location as the ${branding} `\bin\` directory.
. Start the Windows Task Scheduler and open the Task Scheduler Library.
. Under the Actions pane, select `Create Basic Task...`.
. Provide a useful name and description, then click `Next >`.
. Configure the Trigger option to the desired frequency (When the computer starts) and click `Next >`.
. Set the Action to `Start a program` and then click `Next >`.
. Change the program script to start Solr on the desired port:
+
-----
\path\to\solr\bin\solr.cmd
-----
+
This path can also be found using the `Browse...` button provided. Make sure to add the following arguments as well with the desired port in place of the default 8994:
+
-----
start -p 8994
-----
+
Then click `Next >`.
. Review the settings and click `Finish`. Additional settings can be made by right clicking the task and updating the Properties. It may be necessary to update the Security Options under the task Properties to `Run with highest privileges` or even setting user to "SYSTEM".
Additionally, the process can be set to restart if it fails under the Properties > Settings tab. Depending on the system it may also make sense to delay the process from starting for a few minutes until the machine has fully booted. This can be adjusted under Properties > Triggers > Edit > Advanced Settings > Delay Task

[NOTE]
====
If either process is shutdown (${branding} or Solr) the other will continue running.
====