:title: Migration API
:type: architectureIntro
:status: published
:children:
:order: 07
:summary: Introduction to the Migration API.

[NOTE]
====
This code is experimental. While the interfaces and classes provided are functional and tested, they may change or be removed in a future version of the library.
====

${branding} currently has an experimental API for making bundles migratable. Interfaces and classes in `platform/migration/platform-migratable-api` are
used by the system to identify bundles that provide implementations for export and import operations.

The migration API provides a mechanism for bundles to handle exporting data required to clone or backup/restore a ${branding} system. The migration process is meant to
be flexible, so an implementation of `org.codice.ddf.migration.Migratable` can handle exporting data for a single bundle or groups of bundles such as applications.
For example, the `org.codice.ddf.platform.migratable.impl.PlatformMigratable` handles exporting core system files for the ${ddf-platform} application. Each migratable
must provide a unique identifier via its `getId()` method used by the migration API to uniquely identify the migratable between exports and imports. +
${branding} defines migratables of its own to export/import all configurations stored in `org.osgi.service.cm.ConfigurationAdmin`.

These do not need to be handled by implementations of `org.codice.ddf.migration.Migratable`.

An export and an import operation can be performed through the ${command-console}.

When an export operation is processed, the migration API will do a look-up for all registered OSGi services
that are implementing `Migratable` and call their `doExport()` method. As part of the exported data, information about the migratable as required by the `org.codice.ddf.platform.services.common.Describable`
interface will be included. In particular the version string returned will help the migration API identify the version of the exported data from the corresponding migratable and must
be provided as a non-blank string.

When an import operation is processed when the current ${branding} version matches the exported @{branding} version, the migration API will do another look-up for all registered OSGi services that are
implementing `Migratable` and call their `doImport()` or `doIncompatibleImport()` methods based on whether the recorded version string at export time is equal to the version string currently provided
by the migratable or not. The `doMissingImport()` method will be called instead of one of the other two methods when the migration API detects that the corresponding migratable data is missing from the
exported data. Any migratables that are tagged using the `OptionalMigratable` tag interface will automatically be skipped unless otherwise specified when the import phase is initiated.

When an import operation is processed when the current ${branding} version does not the exported @{branding} version, the migration API will do a look-up for all registered OSGi services that are
implementing `Migratable` and call their `doVersionUpgradeImport()` method.

The services that implement the migratable interface will be called one at a time based on their service ranking order, and do not need to be thread safe.
A bundle or a feature can have as many services implementing the interfaces as needed.

=== The Migration API Interfaces and Classes

. `org.codice.ddf.migration.Migratable`
. `org.codice.ddf.migration.OptionalMigratable`
. `org.codice.ddf.migration.MigrationContext`
. `org.codice.ddf.migration.ExportMigrationContext`
. `org.codice.ddf.migration.ImportMigrationContext`
. `org.codice.ddf.migration.MigrationEntry`
. `org.codice.ddf.migration.ExportMigrationEntry`
. `org.codice.ddf.migration.ImportMigrationEntry`
. `org.codice.ddf.migration.MigrationOperation`
. `org.codice.ddf.migration.MigrationReport`
. `org.codice.ddf.migration.MigrationMessage`
. `org.codice.ddf.migration.MigrationException`
. `org.codice.ddf.migration.MigrationWarning`
. `org.codice.ddf.migration.MigrationInformation`
. `org.codice.ddf.migration.MigrationSuccessfulInformation`

==== `Migratable`
The contract for a migratable is stored here. This is the only interface that should be implemented by implementers and registered as an OSGi
service. All other interfaces will be implemented by the migration API that provides support for migratables.

The `org.codice.ddf.migration.Migratable` interface defines these methods:

- `String getId()`
- `String getVersion()`
- `String getTitle()`
- `String getDescription()`
- `String getOrganization()`
- `void doExport(ExportMigrationContext context)`
- `void doImport(ImportMigrationContext context)`
- `void doIncompatibleImport(ImportMigrationContext context)`
- `void doVersionUpgradeImport(ImportMigrationContext context)`
- `void doMissingImport(ImportMigrationContext context)`

The `getId()` method returns a unique identifier for this migratable that must remain constant between the export and the import operations in order for the migration API to correlate the exported data with the migratable during the import operation. It
must be unique across all migratables. +
The `getVersion()` method returns a unique version string which is meant to identify the version of the data exported or supported at import time by the migratable. It cannot be blank and its format is left to the
migratable. The only noticeable requirement is that when the string compares equal using the `String.equals()` method, the migration API will call `doImport()` instead of `doIncompatibleImport()` to restore previously exported data for the migratable. +
The `getTitle()` method returns a simple title for the migratable. +
The `getDescription()` method returns a short description of the type of data exported by the migratable. +
The `getOrganization()` method provides the name of the organization responsible
for the migratable. +
The `doExport()` method is called by the migration API along with a context for the current export operation to store data. +
The `doImport()` method is called by the migration API along with a context for the current import operation when
the version of exported data matches the current version reported by the migratable. This method can be used to restore previously exported data. +
The `doIncompatibleImport()` method is called to restore incompatible data which might require transformation. It is provided a context for the current import operation and the previously exported version. It can then proceed with restoring incompatible data which might require transformation. +
The `doVersionUpgradeImport()` method is called to restore data from a different ${branding} version which might require transformation. It is provided a context for the current import operation and the previously exported version. +
Finally, the `doMissingImport()` method will be called along with the context for the current import operation when data had not been exported for the corresponding migratable.
This will be the case when a migratable is later introduced in the software distribution.

In order to create a `Migratable` for a module of the system, the `org.codice.ddf.migration.Migratable` interface must be implemented and the implementation must be registered under the `org.codice.ddf.migration.Migratable` interface as an OSGi service in the OSGi service registry.
Creating an OSGi service allows for the migration API to lookup all implementations of `org.codice.ddf.migration.Migratable` and command them to export or import.

==== `OptionalMigratable`
This interface is designed as a tagged interface to identify optional migratables. An optional migratable will be skipped by default during the import phase. It can still be manually marked as mandatory when initiating the import phase.

==== `MigrationContext`
The `org.codice.ddf.migration.MigrationContext` provides contextual information about an operation in progress for a given migratable. This is a sort of sandbox that is unique to each migratable. This interface defines the following methods:

- `MigrationReport getReport()`
- `String getId()`
- `Optional<String> getMigratableVersion()`

The `getReport()` method returns a migration report that can be used to record messages while processing an export or an import operation. +
The `getId()` method returns the identifier for the currently processing migratable.
The `getMigratableVersion()` method returns the version for the currently processing migratable.

==== `ExportMigrationContext`
The export migration context provides methods for creating new migration entries and system property referenced migration entries to track exported migration files for a given migratable
while processing an export migration operation. It defines the following methods:

- `Optional<ExportMigrationEntry> getSystemPropertyReferencedEntry(String name)`
- `Optional<ExportMigrationEntry> getSystemPropertyReferencedEntry(String name, BiPredicate<MigrationReport, String> validator)`
- `ExportMigrationEntry getEntry(Path path)`
- `Stream<ExportMigrationEntry> entries(Path path)`
- `Stream<ExportMigrationEntry> entries(Path path, PathMatcher filter)`
- `Stream<ExportMigrationEntry> entries(Path path, boolean recurse)`
- `Stream<ExportMigrationEntry> entries(Path path, boolean recurse, PathMatcher filter)`

The `getSystemPropertyReferencedEntry()` methods create a migration entry to track a file referenced by a given system property value. +
The `getEntry()` method creates a migration entry given the path for a specific file or directory. +
The `entries()` methods create multiple entries corresponding to all files recursively (or not) located underneath a given path with an optional path matcher to filter which files to create entries for.

Once an entry is created, it is not stored with the exported data. It is the migratable's responsibility to store the data using one of the entry's provided methods.
Entries are uniquely identified using a relative path and are specific to each migratable meaning that an entry with the same path in two migratables will not conflict with each other. Each migratable is given its own context (a.k.a. sandbox) to work with.

==== `ImportMigrationContext`
The import migration context provides methods for retrieving migration entries and system property referenced migration entries corresponding to exported files for a given migratable
while processing an import migration operation. It defines the following methods:

- `Optional<ImportMigrationEntry> getSystemPropertyReferencedEntry(String name)`
- `ImportMigrationEntry getEntry(Path path)`
- `Stream<ImportMigrationEntry> entries(Path path)`
- `Stream<ImportMigrationEntry> entries(Path path, PathMatcher filter)`

The `getSystemPropertyReferencedEntry()` method retrieves a migration entry for a file that was referenced by a given system property value. +
The `getEntry()` method retrieves a migration entry given the path for a specific file or directory. +
The `entries()` methods retrieve multiple entries corresponding to all exported files recursively located underneath a given relative path with an optional path matcher to filter which files to retreive entries for.

Once an entry is retrieved, its exported data is not restored. It is the migratable's responsibility to restore the data using one of the entry's provided methods.
Entries are uniquely identified using a relative path and are specific to each migratable meaning that an entry with the same path in two migratables will not conflict with each other. Each migratable is given its own context (a.k.a. sandbox) to work with.

==== `MigrationEntry`

This interface provides supports for exported files. It defines the following methods:

- `MigrationReport getReport()`
- `String getId()`
- `String getName()`
- `Path getPath()`
- `boolean isDirectory()`
- `boolean isFile()`
- `long getLastModifiedTime()`

The `getReport()` method provides access to the associated migration report where messages can be recorded. +
The `getId()` method returns the identifier for the migratable responsible for this entry. +
The `getName()` method provides the unique name for this entry in an OS-independent way. +
The `getPath()` method provides the unique path to the corresponding file for this entry in an OS-specific way. +
The `isDirectory()` method indicates if the entry represents a directory.
The `isFile()` method indicates if the entry represents a file.
The `getLastModifiedTime()` method provides the last modification time for the corresponding file or directory as available when the file or directory is exported.

==== `ExportMigrationEntry`
The export migration entry provides additional methods available for entries created at export time. It defines the following methods:

- `Optional<ExportMigrationEntry> getPropertyReferencedEntry(String name)`
- `Optional<ExportMigrationEntry> getPropertyReferencedEntry(String name, BiPredicate<MigrationReport, String> validator)`
- `boolean store()`
- `boolean store(boolean required)`
- `boolean store(PathMatcher filter)`
- `boolean store(boolean required, PathMatcher filter)`
- `boolean store(BiThrowingConsumer<MigrationReport, OutputStream, IOException> consumer)`
- `OutputStream getOutputStream() throws IOException`

The `getPropertyReferencedEntry()` methods create another migration entry for a file that was referenced by a given property value in the file represented by this entry. +
The `store()` and `store(boolean required)` methods will automatically copy the content of the corresponding file as part of the export making sure the file exists (if required) on disk otherwise an error will be recorded. If the path represents a directory then all files recursively found under the path will be automatically exported. +
The `store(PathMatcher filter)` and `store(boolean required, PathMatcher filter)` methods will automatically copy the content of the corresponding file if it matches the filter as part of the export making sure the file exists (if required) on disk otherwise an error will be recorded. If the path represents a directory then all matching files recursively found under the path will be automatically exported. +
The `store(BiThrowingConsumer<MigrationReport, OutputStream, IOException> consumer)` method allows the migratable to control the export process by specifying a callback consumer that will be called back with an output stream where the data can be writen to instead of having a file on disk being copied by the migration API.
The `OutputStream getOutputStream()` method provides access to the low-level output stream where the migratable can write data directly as opposed to having a file on disk copied automatically.

==== `ImportMigrationEntry`
The import migration entry provides additional methods available for entries retrieved at import time. It defines the following methods:

- `Optional<ImportMigrationEntry> getPropertyReferencedEntry(String name)`
- `boolean restore()`
- `boolean restore(boolean required)`
- `boolean restore(PathMatcher filter)`
- `boolean restore(boolean required, PathMatcher filter)`
- `boolean restore(BiThrowingConsumer<MigrationReport, Optional<InputStream>, IOException> consumer)`
- `Optional<InputStream getInputStream() throws IOException`

The `getPropertyReferencedEntry()` method retrieves another migration entry for a file that was referenced by a given property value in the file represented by this entry. +
The `restore()` and `restore(boolean required)` methods will automatically copy the exported content of the corresponding file back to disk if it was exported; otherwise an error will be recorded. If the path represents a directory then all file entries originally recursively exported under this entry's path will be automatically imported. If the directory had been completely exported using one of the `store()` or `store(boolean required)` methods then in addition to restoring all entries recursively, calling this method will also remove any existing files or directories that were not on the original system. +
The `restore(PathMatcher filter)` and `restore(boolean required, PathMatcher filter)` methods will automatically copy the exported content of the corresponding file if it matches the filter back to disk if it was exported; otherwise an error will be recorded. If the path represents a directory then all matching file entries originally recursively exported under this entry's path will be automatically imported. +
The `restore(BiThrowingConsumer<MigrationReport, Optional<InputStream>, IOException> consumer)` method allows the migratable to control the import process by specifying a callback consumer that will be called back with an optional input stream (empty if the data was not exported) where the data can be read from instead of having a file on disk being created or updated by the migration API. +
The `Optional<InputStream> getInputStream()` method provides access to the optional low-level input stream (empty if the data was not exported) where the migratable can read data directly as opposed to having a file on disk created or updated automatically.

==== `MigrationOperation`
The `org.codice.ddf.migration.MigrationOperation` provides a simple enumeration for identifying the various migration operations available.

==== `MigrationReport`
The `org.codice.ddf.migration.MigrationReport` interface provides information about the execution of a migration operation. It defines the following methods:

- `MigrationOperation getOperation()`
- `Instant getStartTime()`
- `Optional<Instant> getEndTime()`
- `MigrationReport record(String msg)`
- `MigrationReport record(String format, @Nullable Object... args)`
- `MigrationReport record(MigrationMessage msg)`
- `MigrationReport doAfterCompletion(Consumer<MigrationReport> code)`
- `Stream<MigrationMessage> messages()`
- `default Stream<MigrationException> errors()`
- `Stream<MigrationWarning> warnings()`
- `Stream<MigrationInformation> infos()`
- `boolean wasSuccessful()`
- `boolean wasSuccessful(@Nullable Runnable code)`
- `boolean wasIOSuccessful(@Nullable ThrowingRunnable<IOException> code) throws IOException`
- `boolean hasInfos()`
- `boolean hasWarnings()`
- `boolean hasErrors()`
- `void verifyCompletion()`

The `getOperation()` method provides the type of migration operation (i.e. export or import) currently in progress. +
The `getStartTime()` method provides the time at which the corresponding operation started. +
The `getEndTime()` method provides the optional time at which the corresponding operation ended. The time is only available if the operation has ended. +
The `record()` methods enable messages to be recorded with the report. Messages are displayed on the console for the administrator. +
The `doAfterCompletion()` methods enable code to be registered such that it is invoked at the end before a successful result is returned. Such code can still affect the result of the operation. +
The `messages()` method provides access to all recorded messages so far. +
The `errors()` method provides access to all recorded error messages so far. +
The `warnings()` method provides access to all recorded warning messages so far. +
The `infos()` method provides access to all recorded informational messages so far. +
The `wasSuccessful()` method provides a quick check to see if the report is successful. A successful report might have warnings recorded but cannot have errors recorded. +
The `wasSuccessful(Runnable code) method allows code to be executed. It will return true if no new errors are recorded as a result of executing the provided code. +
The `wasIOSuccessful(ThrowingRunnable<IOException> code) method allows code to be executed which can throw I/O exceptions which are automatically recorded as errors. It will return true if no new errors are recorded as a result of executing the provided code. +
The `hasInfos()` method will return true if at least one information message has been recorded so far. +
The `hasWarnings()` method will return true if at least one warning message has been recorded so far. +
The `hasErrors()` method will return true if at least one error message has been recorded so far. +
The `verifyCompletion() method will verify if the report is successful and if not, it will throw back the first recorded exception and attach as suppressed exceptions all other recorded exceptions.

==== `MigrationMessage`
The `org.codice.ddf.migration.MigrationException is defined as a base class for all recordable messages during migration operations. It defines the following methods:

- `String getMessage()`

The `getMessage()` method provides a message for the corresponding exception, warning, or info that will be displayed to the administrator on the console.

==== `MigrationException`
An `org.codice.ddf.migration.MigrationException` should be thrown when an unrecoverable exception occurs that prevents the export or the import operation from continuing. It is also possible to simply record one or many exception(s) with the migration report in order to fail the export or import operation
while not aborting it right away. This provides for the ability to record as many errors as possible and report all of them back to the administrator. All migration exception messages are displayed to the administrator.

==== `MigrationWarning`
An `org.codice.ddf.migration.MigrationWarning` should be used when a migratable wants to warn the administrator that certain aspects of the export or the import may cause problems. For example, if an absolute path is encountered, that path may not exist on the target system and cause the installation to fail.
All migration warning messages are displayed to the administrator.

==== `MigrationInformation`
An `org.codice.ddf.migration.MigrationInformation` should be used when a migratable simply wants to provide useful information to the administrator. All
migration information messages are displayed to the administrator.

==== `MigrationSuccessfulInformation`
The `org.codice.ddf.migration.MigrationSuccessfulInformation` can be used to further qualify an information message as representing the success of an operation.
