The ${ddf-spatial} Application provides KML transformer and a KML network link endpoint that allows a user to generate a View-based KML Query Results Network Link.

This guide supports integration of this application with external frameworks.

=== Integrating ${branding} with CSW
Catalog Services for Web (_CSW_) is an Open Geospatial Consortium (OGC) standard.



===== CSW Endpoint




==== Configuration




=== CSW v2.0.2 Source

The CSW source supports the ability to search collections of descriptive information (metadata) for data, services, and related information objects.

==== Using

Use the CSW source if querying a CSW version 2.0.2 compliant service.

==== Installing and Uninstalling

The CSW source can be installed and uninstalled using the normal processes described in the Configuring ${branding} section.

==== Configuring

The configurable properties for the CSW source are accessed from the CSW Federated Source Configuration in the Admin Console.

===== Configure the CSW Source

[cols="6*", options="header"]
.Configurable Properties
|===
|Title
|Property
|Type
|Description
|Default Value
|Required
￼
|Source ID
|`id`
|String
|Unique Name of this Source.
|CSW
|Yes

|CSW URL
|`cswUrl`
|String
|URL to the Catalogue Services for the Web site that will be queried by this source
|
|Yes

|Event Service Address
|`eventServiceAddress`
|String
|DDF Event Service endpoint.
|
|No

|Register for Events
|`registerForEvents`
|Boolean
|Check to register for events from this source.
|false
|No

|Username
|`username`
|String
|Username to log into the CSW service
|
|No
￼
|Password
|`password`
|String
|Password to log into the CSW service
|
|No
￼
|Disable CN Check
|`disableCnCheck`
|Boolean
|Disable CN check for the server certificate. This should only be used when testing.
|false
|Yes

|Force Longitude/Latitude coordinate order
|`isLonLatOrder`
|Boolean
|Force Longitude/Latitude coordinate order
|false
|Yes

|Use `posList` in `LinearRing`
|`usePosList`
|Boolean
|Use a `<posList>` element rather that a series of `<pos>` elements when issuing geospatial queries containing a `LinearRing`
|false
|Yes

|Metacard Mappings
|`metacardMappings`
|String
|Mapping of the Metacad Attribute names to their CSW property names. The format should be 'title=dc:title'.
|`effective=created,created=dateSubmitted,modified=modified,thumbnail=references,content-type=type,id=identifier,resource-uri=source`
|No

|Poll Interval
|pollInterval
|Integer
|Poll Interval to Check if the Source is available (in minutes - minimum 1)
|5
|Yes

|Connection Timeout
|`connectionTimeout`
|Integer
|Amount of time (in milliseconds) to attempt to establish a connection before timing out.
|30000
|Yes
￼
|Receive Timeout
|`receiveTimeout`
|Integer
|Amount of time (in milliseconds) to attempt to establish a connection before timing out.
|60000
|Yes

|Output schema
|`outputSchema`
|String
|Output Schema
|http://www.opengis.net/cat/csw/2.0.2
|Yes

|Query Type Name
|`queryTypeName`
|String
|Qualified Name for the Query Type used in the CSW GetRecords request
|csw:Record
|Yes

|Query Type Namespace
|`queryTypeNamespace`
|String
|Namespace for the Query Type used in the CSW GetRecords request
|http://www.opengis.net/cat/csw/2.0.2
|Yes

|Force CQL Text as the Query Language
|`isCqlForced`
|Boolean
|Force CQL Text
|false
|Yes

|Forced Spatial Filter Type
|`forceSpatialFilter`
|String
|Force only the selected None No Spatial Filter Type as the only available Spatial Filter.
|
|

|===

==== Known Issues

* The CSW Source does not support text path searches.
* Nearest neighbor spatial searches are not supported.


=== GMD CSW APISO v2.0.2 Source

The GMD CSW source supports the ability to search collections of descriptive information (metadata) for data, services, and related information objects, based on the Application Profile ISO 19115/ISO19119.

==== Using

Use the GMD CSW source if querying a GMD CSW APISO compliant service.

==== Installing and Uninstalling

The GMD CSW source can be installed and uninstalled using the normal processes described in the Configuring ${branding} section.

==== Configuring

The configurable properties for the GMD CSW source are accessed from the GMD CSW ISO Federated Source Configuration in the Admin Console.

===== Configure the CSW Source

[cols="6*", options="header"]
.Configurable Properties
|===
|Title
|Property
|Type
|Description
|Default Value
|Required
￼
|Source ID
|`id`
|String
|Unique Name of this Source.
|CSW
|Yes

|CSW URL
|`cswUrl`
|String
|URL to the Catalogue Services for the Web site that will be queried by this source
|
|Yes

|Event Service Address
|`eventServiceAddress`
|String
|DDF Event Service endpoint.
|
|No

|Register for Events
|`registerForEvents`
|Boolean
|Check to register for events from this source.
|false
|No

|Username
|`username`
|String
|Username to log into the CSW service
|
|No
￼
|Password
|`password`
|String
|Password to log into the CSW service
|
|No
￼
|Disable CN Check
|`disableCnCheck`
|Boolean
|Disable CN check for the server certificate. This should only be used when testing.
|false
|Yes

|Force Longitude/Latitude coordinate order
|`isLonLatOrder`
|Boolean
|Force Longitude/Latitude coordinate order
|false
|Yes

|Use `posList` in `LinearRing`
|`usePosList`
|Boolean
|Use a `<posList>` element rather that a series of `<pos>` elements when issuing geospatial queries containing a `LinearRing`
|false
|Yes

|Metacard Mappings
|`metacardMappings`
|String
|Mapping of the Metacad Attribute names to their CSW property names. The format should be 'title=dc:title'.
|`id=apiso:Identifier,effective=apiso:PublicationDate,created=apiso:CreationDate,modified=apiso:RevisionDate,title=apiso:AlternateTitle,AnyText=apiso:AnyText,ows:BoundingBox=apiso:BoundingBox`
|No

|Poll Interval
|pollInterval
|Integer
|Poll Interval to Check if the Source is available (in minutes - minimum 1)
|5
|Yes

|Connection Timeout
|`connectionTimeout`
|Integer
|Amount of time (in milliseconds) to attempt to establish a connection before timing out.
|30000
|Yes
￼
|Receive Timeout
|`receiveTimeout`
|Integer
|Amount of time (in milliseconds) to attempt to establish a connection before timing out.
|60000
|Yes

|Output schema
|`outputSchema`
|String
|Output Schema
|http://www.isotc211.org/2005/gmd
|Yes

|Query Type Name
|`queryTypeName`
|String
|Qualified Name for the Query Type used in the CSW GetRecords request
|gmd:MD_Metadata
|Yes

|Query Type Namespace
|`queryTypeNamespace`
|String
|Namespace for the Query Type used in the CSW GetRecords request
|http://www.isotc211.org/2005/gmd
|Yes

|Force CQL Text as the Query Language
|`isCqlForced`
|Boolean
|Force CQL Text
|false
|Yes

|Forced Spatial Filter Type
|`forceSpatialFilter`
|String
|Force only the selected None No Spatial Filter Type as the only available Spatial Filter.
|
|

|===

=== Integrating ${branding} with KML



=== KML Network Link Endpoint





=== KML Query Response Transformer

The KML Query Response Transformer is responsible for translating a query response into a KML-formatted document.
The KML will contain an HTML description for each metacard that will display in the pop-up bubble in Google Earth.
The HTML contains links to the full metadata view as well as the product.

==== Using

Using the OpenSearch Endpoint, for example, query with the format option set to the KML shortname: `kml`.

----
${public_url}/services/catalog/query?q=schematypesearch&format=kml
----

.Example Output
[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<kml xmlns:ns2="http://www.google.com/kml/ext/2.2" xmlns="http://www.opengis.net/kml/2.2" xmlns:ns4="urn:oasis:names:tc:ciq:xsdschema:xAL:2.0" xmlns:ns3="http://www.w3.org/2005/Atom">
  <Document id="f0884d8c-cf9b-44a1-bb5a-d3c6fb9a96b6">
    <name>Results (1)</name>
    <open xsi:type="xs:boolean" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">false</open>
    <Style id="bluenormal">
      <LabelStyle>
        <scale>0.0</scale>
      </LabelStyle>
      <LineStyle>
        <color>33ff0000</color>
        <width>3.0</width>
      </LineStyle>
      <PolyStyle>
        <color>33ff0000</color>
        <fill xsi:type="xs:boolean" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">true</fill>
      </PolyStyle>
      <BalloonStyle>
        <text>&lt;h3&gt;&lt;b&gt;$[name]&lt;/b&gt;&lt;/h3&gt;&lt;table&gt;&lt;tr&gt;&lt;td width="400"&gt;$[description]&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;</text>
      </BalloonStyle>
    </Style>
    <Style id="bluehighlight">
      <LabelStyle>
        <scale>1.0</scale>
      </LabelStyle>
      <LineStyle>
        <color>99ff0000</color>
        <width>6.0</width>
      </LineStyle>
      <PolyStyle>
        <color>99ff0000</color>
        <fill xsi:type="xs:boolean" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">true</fill>
      </PolyStyle>
      <BalloonStyle>
        <text>&lt;h3&gt;&lt;b&gt;$[name]&lt;/b&gt;&lt;/h3&gt;&lt;table&gt;&lt;tr&gt;&lt;td width="400"&gt;$[description]&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;</text>
      </BalloonStyle>
    </Style>
    <StyleMap id="default">
      <Pair>
        <key>normal</key>
        <styleUrl>#bluenormal</styleUrl>
      </Pair>
      <Pair>
        <key>highlight</key>
        <styleUrl>#bluehighlight</styleUrl>
      </Pair>
    </StyleMap>
    <Placemark id="Placemark-0103c77e66d9428d8f48fab939da528e">
      <name>MultiPolygon</name>
      <description>&lt;!DOCTYPE html&gt;
&lt;html&gt;
  &lt;head&gt;
    &lt;meta content="text/html; charset=windows-1252" http-equiv="content-type"&gt;
    &lt;style media="screen" type="text/css"&gt;
      .label {
        font-weight: bold
      }
      .linkTable {
width: 100% }
      .thumbnailDiv {
        text-align: center
} img {
        max-width: 100px;
        max-height: 100px;
        border-style:none
      }
    &lt;/style&gt;
  &lt;/head&gt;
  &lt;body&gt;
        &lt;div class="thumbnailDiv"&gt;&lt;a
href="${public_url}/services/catalog/sources/${branding-lowercase}.distribution/0103c77e66d9428d8f
48fab939da528e?transform=resource"&gt;&lt;img alt="Thumnail"
src="data:image/jpeg;charset=utf-8;base64, CA=="&gt;&lt;/a&gt;&lt;/div&gt;
    &lt;table&gt;
      &lt;tr&gt;
        &lt;td class="label"&gt;Source:&lt;/td&gt;
        &lt;td&gt;${ddf-branding-lowercase}.distribution&lt;/td&gt;
      &lt;/tr&gt;
      &lt;tr&gt;
        &lt;td class="label"&gt;Created:&lt;/td&gt;
        &lt;td&gt;Wed Oct 30 09:46:29 MDT 2013&lt;/td&gt;
      &lt;/tr&gt;
      &lt;tr&gt;
￼￼￼        &lt;td class="label"&gt;Effective:&lt;/td&gt;
        &lt;td&gt;2014-01-07T14:48:47-0700&lt;/td&gt;
      &lt;/tr&gt;
    &lt;/table&gt;
    &lt;table class="linkTable"&gt;
      &lt;tr&gt;
        &lt;td&gt;&lt;a
href="${public_url}/services/catalog/sources/${branding-lowercase}.distribution/0103c77e66d9428d8f
48fab939da528e?transform=html"&gt;View Details...&lt;/a&gt;&lt;/td&gt;
        &lt;td&gt;&lt;a
href="${public_url}/services/catalog/sources/${branding-lowercase}.distribution/0103c77e66d9428d8f
48fab939da528e?transform=resource"&gt;Download...&lt;/a&gt;&lt;/td&gt;
      &lt;/tr&gt;
    &lt;/table&gt;
  &lt;/body&gt;
&lt;/html&gt;
</description>
      <TimeSpan>
        <begin>2014-01-07T21:48:47</begin>
      </TimeSpan>
      <styleUrl>#default</styleUrl>
      <MultiGeometry>
        <Point>
          <coordinates>102.0,2.0</coordinates>
        </Point>
        <MultiGeometry>
          <Polygon>
            <outerBoundaryIs>
              <LinearRing>
                <coordinates>102.0,2.0 103.0,2.0 103.0,3.0 102.0,3.0
102.0,2.0</coordinates>
              </LinearRing>
100.8,0.2
  </outerBoundaryIs>
</Polygon>
<Polygon>
  <outerBoundaryIs>
    <LinearRing>
      <coordinates>100.0,0.0 101.0,0.0 101.0,1.0 100.0,1.0 100.0,0.0 100.2,0.2
        100.8,0.8 100.2,0.8 100.2,0.2</coordinates>
              </LinearRing>
            </outerBoundaryIs>
          </Polygon>
        </MultiGeometry>
      </MultiGeometry>
    </Placemark>
  </Document>
</kml>
----

==== Installing and Uninstalling

The `spatial-kml-transformer` feature is installed by default with the Spatial App.

----
${public_url}/services/catalog/0103c77e66d9428d8f48fab939da528e?transform=kml
----

==== Configuring

None.

==== Implementation Details

[cols="2*", options="header"]
|===
|Transformer Shortname
|MIME Type

|`kml`
|`application/vnd.google-earth.kml+xml`

|===

==== Known Issues

None.

=== KML Metacard Transformer

The KML Metacard Transformer is responsible for translating a metacard into a KML-formatted document.
The KML will contain an HTML description that will display in the pop-up bubble in Google Earth.
The HTML contains links to the full metadata view as well as the product.

==== Using

Using the REST Endpoint for example, request a metacard with the transform option set to the KML shortname.

.Example Output
[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<kml xmlns:ns2="http://www.google.com/kml/ext/2.2" xmlns="http://www.opengis.net/kml/2.2" xmlns:ns4="urn:oasis:names:tc:ciq:xsdschema:xAL:2.0" xmlns:ns3="http://www.w3.org/2005/Atom">
  <Placemark id="Placemark-0103c77e66d9428d8f48fab939da528e">
    <name>MultiPolygon</name>
    <description>&lt;!DOCTYPE html&gt;
    &lt;html&gt;
      &lt;head&gt;
        &lt;meta content="text/html; charset=windows-1252" http-equiv="content-type"&gt;
        &lt;style media="screen" type="text/css"&gt;
          .label {
            font-weight: bold
          }
          .linkTable {
width: 100% }
          .thumbnailDiv {
            text-align: center
          }
          img {
            max-width: 100px;
￼￼￼         max-height: 100px;
            border-style:none
          }
    &lt;/style&gt;
  &lt;/head&gt;
  &lt;body&gt;
        &lt;div class="thumbnailDiv"&gt;&lt;a href="${public_url}/services/catalog/sources/${ddf-branding-lowercase}.distribution/0103c77e66d9428d8f48fab939da528e?transform=resource"&gt;&lt;img alt="Thumnail" src="data:image/jpeg;charset=utf-8;base64, CA=="&gt;&lt;/a&gt;&lt;/div&gt;
    &lt;table&gt;
      &lt;tr&gt;
        &lt;td class="label"&gt;Source:&lt;/td&gt;
        &lt;td&gt;${ddf-branding-lowercase}.distribution&lt;/td&gt;
      &lt;/tr&gt;
      &lt;tr&gt;
        &lt;td class="label"&gt;Created:&lt;/td&gt;
        &lt;td&gt;Wed Oct 30 09:46:29 MDT 2013&lt;/td&gt;
      &lt;/tr&gt;
      &lt;tr&gt;
        &lt;td class="label"&gt;Effective:&lt;/td&gt;
        &lt;td&gt;2014-01-07T14:58:16-0700&lt;/td&gt;
      &lt;/tr&gt;
    &lt;/table&gt;
    &lt;table class="linkTable"&gt;
      &lt;tr&gt;
        &lt;td&gt;&lt;a href="${public_url}/services/catalog/sources/${ddf-branding-lowercase}.distribution/0103c77e66d9428d8f48fab939da528e?transform=html"&gt;View Details...&lt;/a&gt;&lt;/td&gt;
        &lt;td&gt;&lt;a href="${public_url}/services/catalog/sources/${ddf-branding-lowercase}.distribution/0103c77e66d9428d8f48fab939da528e?transform=resource"&gt;Download...&lt;/a&gt;&lt;/td&gt;
      &lt;/tr&gt;
    &lt;/table&gt;
  &lt;/body&gt;
&lt;/html&gt;
</description>
    <TimeSpan>
      <begin>2014-01-07T21:58:16</begin>
    </TimeSpan>
    <Style id="bluenormal">
      <LabelStyle>
        <scale>0.0</scale>
      </LabelStyle>
      <LineStyle>
        <color>33ff0000</color>
        <width>3.0</width>
      </LineStyle>
      <PolyStyle>
        <color>33ff0000</color>
        <fill xsi:type="xs:boolean" xmlns:xs="http://www.w3.org/2001/XMLSchema"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">true</fill>
      </PolyStyle>
      <BalloonStyle>
<text>&lt;h3&gt;&lt;b&gt;$[name]&lt;/b&gt;&lt;/h3&gt;&lt;table&gt;&lt;tr&gt;&lt;td
width="400"&gt;$[description]&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;</text>
      </BalloonStyle>
    </Style>
    <Style id="bluehighlight">
      <LabelStyle>
        <scale>1.0</scale>
      </LabelStyle>
      <LineStyle>
        <color>99ff0000</color>
        <width>6.0</width>
      </LineStyle>
      <PolyStyle>
        <color>99ff0000</color>
        <fill xsi:type="xs:boolean" xmlns:xs="http://www.w3.org/2001/XMLSchema"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">true</fill>
      </PolyStyle>
      <BalloonStyle>
        <text>&lt;h3&gt;&lt;b&gt;$[name]&lt;/b&gt;&lt;/h3&gt;&lt;table&gt;&lt;tr&gt;&lt;td width="400"&gt;$[description]&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;</text>
      </BalloonStyle>
    </Style>
    <StyleMap id="default">
      <Pair>
        <key>normal</key>
        <styleUrl>#bluenormal</styleUrl>
      </Pair>
      <Pair>
        <key>highlight</key>
        <styleUrl>#bluehighlight</styleUrl>
      </Pair>
    </StyleMap>
    <MultiGeometry>
      <Point>
        <coordinates>102.0,2.0</coordinates>
      </Point>
      <MultiGeometry>
        <Polygon>
          <outerBoundaryIs>
            <LinearRing>
              <coordinates>102.0,2.0 103.0,2.0 103.0,3.0 102.0,3.0 102.0,2.0</coordinates>
            </LinearRing>
          </outerBoundaryIs>
        </Polygon>
        <Polygon>
100.8,0.2
    <outerBoundaryIs>
      <LinearRing>
        <coordinates>100.0,0.0 101.0,0.0 101.0,1.0 100.0,1.0 100.0,0.0 100.2,0.2 100.8,0.8 100.2,0.8 100.2,0.2</coordinates>
      </LinearRing>
    </outerBoundaryIs>
  </Polygon>
</MultiGeometry>
</Placemark>
</kml>
----

==== Installing and Uninstalling

The `spatial-kml-transformer` feature is installed by default with the Spatial App.

==== Configuring

None.

==== Implementation Details

[cols="2*", options="header"]
|===
|Transformer Shortname
|MIME Type

|kml
|application/vnd.google-earth.kml+xml
|===

==== Known Issues

None.

=== KML Style Mapper

The KML Style Mapper provides the ability for the `KmlTransformer` to map a KML Style URL to a metacard based on that metacard's attributes.
For example, if a user wanted all JPEGs to be blue, the KML Style Mapper provides the ability to do so.
This would also allow an administrator to configure metacards from each source to be different colors.

The configured style URLs are expected to be HTTP URLs.
For more information on style URL's, refer to the https://developers.google.com/kml/documentation/kmlreference#styleurl[KML Reference].

The KML Style Mapper supports all basic and extended metacard attributes.
When a style mapping is configured, the resulting transformed KML contain a `<styleUrl>` tag pointing to that style, rather than the default KML style supplied by the `KmlTransformer`.

==== Configuring

The properties below describe how to configure a Style Mapping.
The configuration name is `Spatial KML Style Map Entry`.

[cols="6*", options="header"]
.Configurable Properties
|===

|Title
|Property
|Type
|Description
|Default Value
|Required

|Attribute Name
|`attributeName`
|The name of the metacard attribute to match against (e.g., `title`, `metadata-content-type`).
|String
|
|Yes

|Attribute Value
|`attributeValue`
|String
|The value of the metacard attribute.
|
|Yes

|Style URL
|`styleUrl`
|String
|The full qualified URL to the KML style (e.g., http://example.com/styles#myStyle).
|
|Yes

|===

==== Example Values

[source,xml,linenums]
----
xmlns="http://www.opengis.net/kml/2.2"
  xmlns:ns4="urn:oasis:names:tc:ciq:xsdschema:xAL:2.0"
xmlns:ns3="http://www.w3.org/2005/Atom">
  <Placemark id="Placemark-0103c77e66d9428d8f48fab939da528e">
    <name>MultiPolygon</name>
    <description>&lt;!DOCTYPE html&gt;
&lt;html&gt;
  &lt;head&gt;
    &lt;meta content="text/html; charset=windows-1252" http-equiv="content-type"&gt;
    &lt;style media="screen" type="text/css"&gt;
      .label {
        font-weight: bold
      }
      .linkTable {
width: 100% }
      .thumbnailDiv {
        text-align: center
} img {
        max-width: 100px;
        max-height: 100px;
        border-style:none
      }
    &lt;/style&gt;
  &lt;/head&gt;
  &lt;body&gt;
        &lt;div class="thumbnailDiv"&gt;&lt;a
href="${public_url}/services/catalog/sources/${ddf-branding-lowercase}.distribution/0103c77e66d9428d8f48fab939da528e?transform=resource"&gt;&lt;img alt="Thumnail"
src="data:image/jpeg;charset=utf-8;base64, CA=="&gt;&lt;/a&gt;&lt;/div&gt;
    &lt;table&gt;
      &lt;tr&gt;
        &lt;td class="label"&gt;Source:&lt;/td&gt;
        &lt;td&gt;${ddf-branding-lowercase}.distribution&lt;/td&gt;
      &lt;/tr&gt;
      &lt;tr&gt;
        &lt;td class="label"&gt;Created:&lt;/td&gt;
        &lt;td&gt;Wed Oct 30 09:46:29 MDT 2013&lt;/td&gt;
      &lt;/tr&gt;
      &lt;tr&gt;
        &lt;td class="label"&gt;Effective:&lt;/td&gt;
        &lt;td&gt;2014-01-07T14:58:16-0700&lt;/td&gt;
      &lt;/tr&gt;
    &lt;/table&gt;
    &lt;table class="linkTable"&gt;
      &lt;tr&gt;
        &lt;td&gt;&lt;a
href="${public_url}/services/catalog/sources/${ddf-branding-lowercase}.distribution/0103c77e66d9428d8f48fab939da528e?transform=html"&gt;View Details...&lt;/a&gt;&lt;/td&gt;
        &lt;td&gt;&lt;a href="${public_url}/services/catalog/sources/${ddf-branding-lowercase}.distribution/0103c77e66d9428d8f48fab939da528e?transform=resource"&gt;Download...&lt;/a&gt;&lt;/td&gt;
      &lt;/tr&gt;
    &lt;/table&gt;
  &lt;/body&gt;
&lt;/html&gt;
</description>
    <TimeSpan>
      <begin>2014-01-07T21:58:16</begin>
    </TimeSpan>
 <styleUrl>http://example.com/kml/style#sampleStyle</styleUrl>
    <MultiGeometry>
      <Point>
        <coordinates>102.0,2.0</coordinates>
      </Point>
      <MultiGeometry>
        <Polygon>
          <outerBoundaryIs>
            <LinearRing>
              <coordinates>102.0,2.0 103.0,2.0 103.0,3.0 102.0,3.0
102.0,2.0</coordinates>
            </LinearRing>
          </outerBoundaryIs>
        </Polygon>
        <Polygon>
100.8,0.2
<outerBoundaryIs>
  <LinearRing>
    <coordinates>100.0,0.0 101.0,0.0 101.0,1.0 100.0,1.0 100.0,0.0 100.2,0.2
      100.8,0.8 100.2,0.8 100.2,0.2</coordinates>
  </LinearRing>
    </outerBoundaryIs>
  </Polygon>
</MultiGeometry>
</MultiGeometry>
</Placemark>
</kml>
----

==== Installing and Uninstalling

The KML Style Mapper is included in the `spatial-kml-transformer` feature and is installed by default with the Spatial App.

==== Implementation Details

[cols="2*", options="header"]
|===
|Transformer Shortname
|MIME Type

|`kml`
|`application/vnd.google-earth.kml+xml`
|===

==== Known Issues

None.

=== Integrating ${branding} with WFS

The Web Feature Service (WFS) is an Open Geospatial Consortium (OGC) Specification.
${branding} supports the ability to integrate WFS 1.0 and WFS 2.0 Web Services.

[NOTE]
====
${branding} does not include a supported WFS Web Service (Endpoint) implementation.
Therefore, federation for 2 ${branding} instances is not possible via WFS.
====

=== Working with WFS Sources

A Web Feature Service (WFS) source is an implementation of the FederatedSource interface provided by the ${branding} Framework.
A WFS source provides capabilities for querying an Open Geospatial Consortium (OGC) WFS 1.0.0-compliant server.
The results are made available to ${branding} clients.

==== WFS Features

When a query is issued to a WFS server, the output of the query is an XML document that contains a collection of feature member elements.
Each WFS server can have one or more feature types with each type being defined by a schema that extends the WFS featureMember schema.
The schema for each type can be discovered by issuing a `DescribeFeatureType` request to the WFS server for the feature type in question.
The WFS source handles WFS capability discovery and requests for feature type description when an instance of the WFS source is configured and created.

See the WFS v1.0.0 Source for more information about how to configure a WFS source.

===== Convert a WFS Feature

In order to expose WFS features to ${branding} clients, the WFS feature must be converted into the common data format of the ${branding}, a metacard.
The OGC package contains a `GenericFeatureConverter` that attempts to populate mandatory metacard fields with properties from the WFS feature XML.
All properties will be mapped directly to new attributes in the metacard.
However, the `GenericFeatureConverter` may not be able to populate the default metacard fields with properties from the feature XML.

===== Create a Custom Converter

To more accurately map WFS feature properties to fields in the metacard, a custom converter can be created.
The OGC package contains an interface, `FeatureConverter`, which extends the [] http://xstream.codehaus.org/javadoc/com/thoughtworks/xstream/converters/Converter.htmlConverter interface provided by the http://xstream.codehaus.org/[XStream] project.
XStream is an open source API for serializing XML into Java objects and vice-versa.
Additionally, a base class, `AbstractFeatureConverter`, has been created to handle the mapping of many fields to reduce code duplication in the custom converter classes.

* Create the `CustomConverter` class extending the `ogc.catalog.common.converter.AbstractFeatureConverter` class.

[source,java]
----
public class CustomConverter extends ogc.catalog.common.converter.AbstractFeatureConverter
----

* Implement the `FeatureConverterFactory` interface and the `createConverter()` method for the `CustomConverter`.
￼￼
----
public class CustomConverterFactory implements FeatureConverterFactory {
 private final featureType;
 public CustomConverterFactory(String featureType) {
  this.featureType = featureType;
 }
 public FeatureConverter createConverter() {
  return new CustomConverter();
 }
 public String getFeatureType() {
  return featureType;
} }
----

* Implement the `unmarshal` method required by the `FeatureConverter` interface. The `createMetacardFromFeature(reader, metacardType)` method implemented in the `AbstractFeatureConverter` is recommended.

[source,java,linenums]
----
public Metacard unmarshal(HierarchicalStreamReader reader, UnmarshallingContext ctx) {
  MetacardImpl mc = createMetacardFromFeature(reader, metacardType);
  //set your feature specific fields on the metacard object here
  //
  //if you want to map a property called "beginningDate" to the Metacard.createdDate field
  //you would do:
  mc.setCreatedDate(mc.getAttribute("beginningDate").getValue());
}
----

* Export the `ConverterFactory` to the OSGi registry by creating a blueprint.xml file for its bundle. The bean id and argument value must match the WFS Feature type being converted.

[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<blueprint xmlns="http://www.osgi.org/xmlns/blueprint/v1.0.0" xmlns:cm="http://aries.apache.org/blueprint/xmlns/blueprint-cm/v1.1.0">
  <bean id="custom_type" class="com.example.converter.factory.CustomConverterFactory">
    <argument value="custom_type"/>
  </bean>
  <service ref="custom_type" interface="ogc.catalog.common.converter.factory.FeatureConverterFactory"/>
</blueprint>
----

=== WFS v1.0.0 Source

The WFS Source allows for requests for geographical features across the web using platform-independent calls.

==== Using

Use the WFS Source if querying a WFS version 1.0.0 compliant service.

==== Installing and Uninstalling

The WFS Source can be installed and uninstalled using the normal processes described in the Configuring ${branding} section.

==== Configuring

The configurable properties for the WFS Source are accessed from the WFS Federated Source Configuration in the Admin Console.

===== Configuring WFS Source

====== Configurable Properties
[cols="6*", options="header"]
|===
|Title
|Property
|Type
|Description
|Default Value
|Required

|Source ID
|`id`
|String
|Unique name of the Source.
|WFS_v1_0_0
|Yes

|WFS URL
|`wfsUrl`
|String
|URL to the Web Feature Service (WFS) that will be queried by this source (see below).
|
|Yes

|Disable CN Check
|`disableCnCheck`
|Boolean
|Disable CN check for the server certificate. This should only be used when testing.
|false
|Yes

|Username
|`username`
|String
|Username to log in to the WFS service. Password to log in to the WFS service.
|
|No

|Password
|`password`
|String
|Password to log in to the WFS service.
|
|No

|Forced Feature Type
|`forcedFeatureType`
|String
|Force only a specific FeatureType to be queried instead of all featureTypes
|
|No

|Non Queryable Properties
|`nonQueryableProperties`
|List of Strings
|Multivalued list of properties in the feature XML that should not be used as filters.
|
|No

|Poll Interval
|`pollInterval`
|Integer
|Poll interval to check if the source is available (in minutes; minimum = 1).
|5
|Yes

|Forced Spatial Filter Type
|`forceSpatialFilter`
|String
|Force the selected Spatial Filter Type to be the only available Spatial Filter.
|None
|No

|Connection Timeout
|`connectionTimeout`
|Integer
|Amount of time to attempt to establish a connection before timing out, in milliseconds
|30000
|Yes

|Receive Timeout
|`receiveTimeout`
|Integer
|Amount of time to wait for a response before timing out, in milliseconds.
|60000
|Yes

|===

==== WFS URL

The WFS URL must match the endpoint for the service being used.
The type of service and version are added automatically, so they do not need to be included.
Some servers will throw an exception if they are included twice, so do not include those.

The syntax depends on the server.
However, in most cases, the syntax will be everything before the `?` character in the URL that corresponds to the `GetCapabilities` query.

.Example GeoServer 2.5 Syntax
----
http://www.example.org:8080/geoserver/ows?service=wfs&version=1.0.0&request=GetCapabilities
----

In this case, the WFS URL would be

----
http://www.example.org:8080/geoserver/ows
----

==== Known Issues

None.

=== WFS v2.0.0 Source

The WFS 2.0 Source allows for requests for geographical features across the web using platform-independent calls.

==== Using

Use the WFS Source if querying a WFS version 2.0.0 compliant service. Also see Working with WFS Sources.

==== Installing and Uninstalling

The WFS Source can be installed and uninstalled using the normal processes described in the Configuring ${branding} section.

==== Configuring

The configurable properties for the WFS 2.0.0 Source are accessed from the WFS 2.0.0 Federated Source Configuration in the Admin Console.

===== Configuring WFS 2.0.0 Source

====== Configurable Properties

[cols="6*", options="header"]
|===
|Title
|Property
|Type
|Description
|Default Value
|Required

|Source ID
|`id`
|String
|Unique name of the source
|WFS_v2_0_0
|Yes

|WFS URL
|`wfsUrl`
|String
|URL to the endpoint implementing the Web Feature Service (WFS) 2.0.0 spec.
|
|Yes

|Disable CN Check
|`disableCnCheck`
|Boolean
|Disable CN Check for the server certificate. This should only be used when testing.
|false
|Yes

|Coordinate Order
|`coordinateOrder`
|String
|Coordinate order that remote source expects and returns spatial data in.
|Lat/Lon
|Yes

|Disable Sorting
|`disableSorting`
|Boolean
|When selected, the system will not specify sort criteria with the query.
This should only be used if the remote source is unable to handle sorting even when the capabilities states `ImplementsSorting` is supported.
|false
|Yes

|Username
|`username`
|String
|Username for the WFS service.
|
|No

|Password
|`password`
|String
|Password for the WFS service.
|
|No

|Forced Feature Type
|`forcedFeatureType`
|String
|Force only a specific FeatureType to be queried instead of all featureTypes
|
|No

|Non Queryable Properties
|`nonQueryableProperties`
|List of Strings
|Properties listed here will NOT be queryable and any attempt to filter on these properties will result in an exception.
|
|No

|Poll Interval
|`pollInterval`
|Integer
|Poll interval to check if the source is available (in minutes; minimum = 1).
|5
|Yes

|Forced Spatial Filter Type
|`forceSpatialFilter`
|String
|Force only the selected Spatial Filter Type as the only available Spatial Filter.
|
|No

|Connection Timeout
|`connectionTimeout`
|Integer
|Amount of time to attempt to establish a connection before timing out, in milliseconds
|30000
|Yes

|Receive Timeout
|`receiveTimeout`
|Integer
|Amount of time to wait for a response before timing out, in milliseconds.
|60000
|Yes
|===

==== WFS URL

The WFS URL must match the endpoint for the service being used.
The type of service and version is added automatically, so they do not need to be included.
Some servers will throw an exception if they are included twice, so do not include those.

The syntax depends on the server.
However, in most cases, the syntax will be everything before the `?` character in the URL that corresponds to the `GetCapabilities` query.

.Example GeoServer 2.5 Syntax
----
http://www.example.org:8080/geoserver/ows?service=wfs&version=2.0.0&request=GetCapabilities
----

In this case, the WFS URL would be
----
http://www.example.org:8080/geoserver/ows
----

==== Known Issues

None.

==== Mapping WFS Feature Properties to Metacard Attributes

The WFS 2.0 Source allows for virtually any schema to be used to describe a feature.
A feature is relatively equivalent to a metacard. The `MetacardMapper` was added to allow an administrator to configure which feature properties map to which metacard attributes.

==== Using

Use the WFS `MetacardMapper` to configure which feature properties map to which metacard attributes when querying a WFS version 2.0.0 compliant service.
When feature collection responses are returned from WFS sources, a default mapping occurs which places the feature properties into metacard attributes, which are then presented to the user via ${branding}.
There can be situations where this automatic mapping is not optimal for your solution.
Custom mappings of feature property responses to metacard attributes can be achieved through the `MetacardMapper`.
The `MetacardMapper` is set by creating a feature file configuration which specifies the appropriate mapping. The mappings are specific to a given feature type.

==== Installing and Uninstalling

The WFS `MetacardMapper` can be installed and uninstalled using the normal processes described in the Configuring ${branding} section.

==== Configuring

This component can be configured using the normal processes described in the Configuring ${branding} section.

The configurable properties for the WFS MetacardMapper are accessed from the Metacard to WFS Feature Map Configuration in the Admin Console.

===== Configuring WFS MetacardMapper

====== Configurable Properties

[cols="6*", options="header"]
|===
|Title
|Property
|Type
|Description
|Default Value
|Required


|Feature Type
|`featureType`
|String
|Feature Type. Format is `{URI}local-name`
|
|Yes

|Metacard Attribute to WFS Feature Property Mapping
|`metacardAttrToFeaturePropMap`
|String
|Metacard Attribute to WFS Feature Property Mapping. Format is `metacardAttribute=featureProperty`
|
|Yes

|Temporal Sort By Feature Property
|`sortByTemporalFeatureProperty`
|String
|When Sorting Temporally, Sort By This Feature Property.
|
|No

|Relevance Sort By Feature Property
|`sortByRelevanceFeatureProperty`
|String
|When Sorting By Distance, Sort By This Feature Property.
|
|No

|Distance Sort By Feature Property
|`sortByDistanceFeatureProperty`
|String
|When Sorting By Relevance, Sort By This Feature Property.
|
|No
|===

===== Example Configuration

There are two ways to configure the `MetcardMapper`, one is to use the Configuration Admin available via the Admin Console.
Additionally, a `feature.xml` file can be created and copied into the "deploy" directory.
The following shows how to configure the `MetacardMapper` to be used with the sample data provided with GeoServer.
This configuration shows a custom mapping for the feature type ‘states’.
For the given type, we are taking the feature property ‘states.STATE_NAME’ and mapping it to the metacard attribute ‘title’.
In this particular case, since we mapped the state name to title in the metacard, it will now be fully searchable.
More mappings can be added to the `featurePropToMetacardAttrMap` line through the use of comma as a delimiter.

.Example `MetacardMapper` Configuration Within a `feature.xml` file:
[source,xml,linenums]
----
<feature name="geoserver-states" version="${project.version}"
    description="WFS Feature to Metacard mappings for GeoServer Example {http://www.openplans.org/topp}states">
    <config name="org.codice.${ddf-branding-lowercase}.spatial.ogc.wfs.catalog.mapper.MetacardMapper-geoserver.http://www.openplans.org/topp.states">
        featureType = {http://www.openplans.org/topp}states
        service.factoryPid = org.codice.${ddf-branding-lowercase}.spatial.ogc.wfs.catalog.mapper.MetacardMapper
        featurePropToMetacardAttrMap = states.STATE_NAME=title
    </config>
</feature>
----

===== Known Issues

None.
