:title: Startup Types
:type: installing
:status: published
:summary: Installation profiles available.
:project: ${ddf-branding}
:order: 05

.Setup Types
****
${branding} is pre-configured with several installation profiles.

* Standard Installation: *Recommended*. Includes these applications by default:
** <<_admin_reference,${ddf-admin}>>
** <<_catalog_reference,${ddf-catalog}>>
** <<_platform_reference,${ddf-platform}>>
** <<_security_reference,${ddf-security}>>
** <<_solr_reference,${ddf-solr}>>
** <<_spatial_reference,${ddf-spatial}>>
** <<_search_ui_reference,${ddf-ui}>>

* Development: Includes all demo, beta, and experimental applications.
* Custom Installation: *Advanced*. Click *Customize* on either profile to add or remove applications to be installed.

** If apps are preselected when the *Select Applications* page is reached, they will be uninstalled if unselected.

[WARNING]
====
The ${ddf-platform}, ${ddf-admin}, and ${ddf-security} applications are required and CANNOT be selected or unselected.

The ${ddf-security} Application appears to be unselected upon first view of the tree structure, but it is in fact automatically installed with a later part of the installation process.
====

****
