:title: High Availability Initial Setup Exceptions
:type: subInstalling
:status: published
:parent: High Availability Initial Setup
:project: ${branding}
:order: 00

==== {title}

These steps are handled differently for the initial setup of a Highly Available Cluster.

===== HTTP Proxy Integration

In order to integrate with an HTTP proxy, the ${branding} node's system properties (in `<${branding}_HOME>/etc/system.properties`) must be changed to publish the correct port to external systems and users.
This must be done before installing the first ${branding} node.

There are two internal port properties that must be changed to whatever ports the ${branding} will use on its system.
Then there are two external port properties that must be changed to whatever ports the HTTP proxy is forwarding traffic through.

[WARNING]
====
Make sure that the HTTP proxy is already running and forwarding traffic on the chosen ports before starting the ${branding}.
There may be unexpected behavior otherwise.
====

In the below example, the HTTP proxy is forwarding https traffic via 8993 and http traffic via 8181.
The ${branding} node will run on 1111 for https and 2222 for http (on the host that it's hosted on).
[source]
----
org.codice.ddf.system.httpsPort=8993
org.codice.ddf.system.httpPort=8181
org.codice.ddf.system.port=${org.codice.ddf.system.httpsPort}
org.codice.ddf.system.internalHttpsPort=1111
org.codice.ddf.system.internalHttpPort=2222
----

===== Identical Directory Structures

The two ${branding} nodes need to be under identical root directories on their corresponding systems.
On Windows, this means they must be under the same drive.

===== Highly Available Security Auditing

A third party tool will have to be used to persist the logs in a highly available manner.

* Edit the `<${branding}_HOME>/etc/org.ops4j.pax.logging.cfg` file to enable log4j2, following the steps in <<_enabling_fallback_audit_logging, Enabling Fallback Audit Logging>>.
* Then put the appropriate log4j2 appender in `<${branding}_HOME>/etc/log4j2.config.xml` to send logs to the chosen third party tool.
See https://logging.apache.org/log4j/2.x/manual/appenders.html[Log4j Appenders].

===== Shared Storage Provider

The storage provider must be in a location that is shared between the two ${branding} nodes and must be highly available.
If hardening the Highly Available Cluster, this shared storage provider must be trusted/secured.
One way to accomplish this is to use the default <<org.codice.ddf.catalog.content.impl.FileSystemStorageProvider,Content File System Storage Provider>> and configure it to point to a highly available shared directory.

===== High Availability Certificates

Certificates need to have Subject Alternative Names (SANs) which will include the host for the HTTP proxy and for both ${branding} nodes.
A certificate with SANs signed by the Demo CA can be obtained by following the steps at <<_creating_new_server_keystore_entry_with_the_certnew_scripts,Creating New Server Keystore Entry with the CertNew Scripts>>.
This certificate is intended for testing purposes only, and should not be used in production.

===== High Availability Installation Profile

Instead of having to manually turn features on and off, there is a High Availability installation profile.
This profile will not show up in the UI Installer, but can be installed by executing `profile:install ha` on the command line *instead* of stepping through the UI Installer.
This profile will install all of the High Availability supported features.
