==== FTP Endpoint

The FTP Endpoint provides a method for ingesting files directly into the ${branding} Catalog using the FTP protocol.
The files sent over FTP are not first written to the file system, like the Directory Monitor, but instead the FTP stream of the file is ingested directly into the ${branding} catalog, thus avoiding extra I/O overhead.

===== Installing FTP Endpoint

The FTP Endpoint is not installed by default with a standard installation.

To install:
* Navigate to ${admin-console}.
* Navigate to *${ddf-catalog}* application.
* Navigate to *Features* tab.
* Install the *catalog-core-ftp* feature.

===== Configuring FTP Endpoint

The configurable properties for the FTP Endpoint are accessed from the *FTP Endpoint* Configuration in the ${admin-console} under the ${ddf-catalog} application.

.FTP Endpoint Configurable Properties
[cols="1,1m,1,4a,1,1," options="header"]
|===

|Title
|Property
|Type
|Description
|Default Value
|Required

|FTP Port
|port
|Integer
|Specifies the port for the server to listen on for connections.
|8021
|Yes

|===

===== Using FTP Endpoint

.FTP Endpoint URL
----
${secure_url}/path/to/endpoint
----

the FTP endpoint supports the PUT and MPUT operations. Any other operation, such as DELETE, will return a 550 action not taken response.

====== From Code:

Custom Ftplets can be implemented by extending the `DefaultFtplet` class provided by Apache FTP Server. Doing this will allow custom handling of various FTP commands by overriding the methods of the `DefaultFtplet`. Refer to `https://mina.apache.org/ftpserver-project/ftplet.html` for available methods that can be overridden.
After creating a custom Ftplet, it needs to be added to the FTP server’s Ftplets before the server is started. Any Ftplets that are registered to the FTP server will execute the FTP command in the order that they were registered.

====== From an FTP client:

The FTP endpoint can be accessed from any FTP client of choice. Some common clients are FileZilla, PuTTY, or the FTP client provided in the terminal. The default port number is *8021*. If FTPS is enabled with 2-way TLS, a client that supports client authentication is required.

====== Implementation Details

The FTP endpoint is implemented using the Apache FTP Server and Apache Mina.
Apache Mina provides an API for transport protocols such as TCP and UDP.
The FTP server is built on top of Apache Mina to transport its messages.
${branding} implements a custom Ftplet by overriding the `DefaultFtplet` class provided by Apache FTP Server.

====== Known Issues

None


