
The ${branding} Catalog provides a framework for storing, searching, processing, and transforming information.
Clients typically perform query, create, read, update, and delete (QCRUD) operations against the Catalog.
At the core of the Catalog functionality is the `Catalog Framework`, which routes all requests and responses through the system, invoking additional processing per the system configuration.

=== Catalog Architecture

.Catalog Architecture
[ditaa,catalog_architecture]
....

                /-=-----------------\
                |      Clients      |
                \-------------------/
                          |
                          v
                /-------------------\
                |cDEFEndpoints      |
                +------------+------+
                |cDEF        |cDEF  |
                | Operations | Data |
/---------------+------------+------+------------+---------\    +--------+
|cDEF           |cDEF               |cDEF        |cDEF     |<-> |        |
|  Transformers |                   | Federation | Sources |    |External|
+---------------+ Catalog Framework +------------+---------+<-> |  Data  |
|cDEF           |                   |cDEF   Eventing       |    |Holdings|
|   Catalog     |                   +------------+---------+<-> |    {s} |
|   Plugins     |                   |cDEF   Resources      |    +------=-+
\---------------+-------------------+----------------------/
                |cDEF               |
                | Catalog Provider  |
                \-------------------/
                          ^
                          |
                          v                         Legend
                  +---------------+                /---------------------\
                  |{s}            |                |cDEF ${ddf-branding} Component   |
                  |  Data Store   |                \---------------------/
                  |               |                /---------------------\
                  +------------=--+                | External Component  |
                                                   \--------------------=/

....

=== Installing ${ddf-catalog}

==== Prerequisites

Before the ${ddf-catalog} application can be installed:

* the ${branding} Kernel must be running

* the ${branding} Platform application must be installed

==== Installing

The ${ddf-catalog} is preinstalled with a standard installation.

==== Configuring

[cols="1,1,2" options="header"]
|===
|Configuration
|ID
|Description

|Backup Post-Ingest Plugin
|`plugin.backup`
|Enable and configure Backup Plugin

|Catalog Federation Strategy
|`${ddf-branding-lowercase}.catalog.federation.impl.CachingFederationStrategy`
|Configuration options for federation caching

|Catalog OpenSearch Federated Source
|`OpenSearchSource`
|Settings for OpenSearch Source

|Catalog Standard Framework
|`${ddf-branding-lowercase}.catalog.CatalogFrameworkImpl`
|Settings for product retrieval through Catalog Standard Framework

|Ingest Security Plugin
|`${ddf-branding-lowercase}.catalog.security.ingest.IngestPlugin`
|Configure roles/attributes required to ingest

|URL Resource Reader
|`${ddf-branding-lowercase}.catalog.resource.impl.URLResourceReader`
|Configure directories for product downloads

|Xml Query Transformer
|`${ddf-branding-lowercase}.catalog.transformer.xml.XmlResponseQueueTransformer`
|Set threshold for running marshalling in parallel

|===

=== Federation UI

The federation user interface is a convenient way to manage federated data sources for the ${branding}.

Federation enables including remote sources, including other ${branding} installations in queries.

==== Installing

The Federation UI is installed by default.

==== Configuring

No configuration is required.

==== Using

. Go to the admin ui at `http://localhost:8181/admin/index.html`.

. Open ${ddf-catalog} Application

==== Adding a Source

. Press *Add* button. 

. Name the source.

. Choose source type. The type of source selected will determine the options to configure.

==== Editing a Source

. Click the name of the source to edit.

. Update relevant properties.

. Click *Save*.

==== Enabling/Disabling a Source

. Select the drop down menu for the source under the heading *Type*.

. Set to `enabled`/`disabled`.

==== Removing a Source

. Click the delete source icon.

. Check box next to the source to delete.

. Click *Delete*.
