:title: Developing Input Transformers
:type: developingComponent
:status: published
:link: _developing_input_transformers
:summary: Creating a custom input transformer.
:order: 07

(((Input Transformers)))
${branding} supports the creation of custom <<{architecture-prefix}types_of_transformers,input transformers>> for use cases not covered by the included implementations.

.Creating a custom input Transformer:
. Create a new Java class that implements `ddf.catalog.transform.InputTransformer`. +
`public class SampleInputTransformer implements ddf.catalog.transform.InputTransformer`
. Implement the transform methods. +
`public Metacard transform(InputStream input) throws IOException, CatalogTransformerException` +
`public Metacard transform(InputStream input, String id) throws IOException, CatalogTransformerException`
. Import the ${branding} interface packages to the bundle manifest (in addition to any other required packages). +
`Import-Package: ddf.catalog,ddf.catalog.transform`
. Create an OSGi descriptor file to communicate with the OSGi Service Registry (described in the <<{developing-prefix}osgi_basics,OSGi Basics>> section). Export the service to the OSGi Registry and declare service properties.
+
.Input Transformer Blueprint Descriptor Example
[source,xml,linenums]
----
...
<service ref="SampleInputTransformer" interface="ddf.catalog.transform.InputTransformer">
    <service-properties>
        <entry key="shortname" value="[[sampletransform]]" />
        <entry key="title" value="[[Sample Input Transformer]]" />
        <entry key="description" value="[[A new transformer for metacard input.]]" />
    </service-properties>
</service>
...
----
+
.Input Transformer Variable Descriptions / Blueprint Service Properties
[cols="1m,3,2m" options="header"]
|===

|Key
|Description of Value
|Example

|`shortname`
|(Required) An abbreviation for the return-type of the `BinaryContent` being sent to the user.
|_atom_

|`title`
|(Optional) A user-readable title that describes (in greater detail than the shortname) the service.
|_Atom Entry Transformer Service_

|`description`
|(Optional) A short, human-readable description that describes the functionality of the service and the output.
|_This service converts a single metacard xml document to an atom entry element._

|===
+
. Deploy OSGi Bundle to OSGi runtime.

== Create an XML Input Transformer using SaxEventHandlers [[saxEventHandlers]]

For a transformer to transform XML, (as opposed to JSON or a Word document, for example) there is a simpler solution than fully implementing a `MetacardValidator`.
DDF includes an extensible, configurable `XmlInputTransformer`.
This transformer can be instantiated via blueprint as a managed service factory and configured via metatype.
The `XmlInputTransformer` takes a configuration of `SaxEventHandlers`.
A `SaxEventHandler` is a class that handles SAX Events (a very fast XML parser) to parse metadata and create metacards.
Any number of `SaxEventHandlers` can be implemented and included in the `XmlInputTransformer` configuration.
See the `catalog-transformer-streaming-impl` bundle for examples (`XmlSaxEventHandlerImpl` which parses the ${ddf-branding} Metacard XML Metadata and the `GmlHandler` which parses GML 2.0)
Each `SaxEventHandler` implementation has a `SaxEventHandlerFactory` associated with it.
The `SaxEventHandlerFactory` is responsible for instantiating new `SaxEventHandlers` - each transform request gets a new instance of `XmlInputTransformer` and set of `SaxEventHandlers` to be _thread-_ and _state-safe_.

The following diagrams intend to clarify implementation details:

The `XmlInputTransformer` Configuration diagram shows the `XmlInputTransformer` configuration, which is configured using the metatype and has the `SaxEventHandlerFactory` ids.
Then, when a transform request is received, the `ManagedServiceFactory` instantiates a new `XmlInputTransformer`.
This `XmlInputTransformer` then instantiates a new `SaxEventHandlerDelegate` with the configured `SaxEventHandlersFactory` ids.
The factories all in turn instantiate a `SaxEventHandler`.
Then, the `SaxEventHandlerDelegate` begins parsing the XML input document, handing the SAX Events off to each `SaxEventHandler`, which handle them if they can.
After parsing is finished, each `SaxEventHandler` returns a list of `Attributes` to the `SaxEventHandlerDelegate` and `XmlInputTransformer` which add the attributes to the metacard and then return the fully constructed metacard.

.`XMLInputTransformer` Configuration
[ditaa, XmlInputTransformer_configuration, png]
....
/--------------------------------------------------------\
| +---------------------------------+                    |
| |XmlInputTransformer Configuration|        cCCC        |
| +---------------------------------+                    |
|    ||                                                  |
|    ||    +-------------------------------------------+ |
|    |\--->|String value of SaxEventHandlerFactory1 id | |
|    |     +-------------------------------------------+ |
|    |                                                   |
|    |     +-------------------------------------------+ |
|    \---->|String value of SaxEventHandlerFactory2 id | |
|          +-------------------------------------------+ |
\--------------------------------------------------------/
....

.`XMLInputTransformer` `SaxEventHandlerDelegate` Configuration
[ditaa, XmlInputTransformer_saxeventhandlerdelegate, png]
....
/--------------------------------------------------------\
| +---------------------------------+                    |
| |XmlInputTransformer              |                    |
| +---------------------------------+        cCCC        |
|    |||                                                 |
|    |||   +-----------------------+                     |
|    ||\-->|SaxEventHandlerDelegate|                     |
|    ||    +-----------------------+                     |
|    ||                                                  |
|    ||    +-----------------------+  +----------------+ |
|    |\--->|SaxEventHandlerFactory1|->|SaxEventHandler1| |
|    |     +-----------------------+  +----------------+ |
|    |                                                   |
|    |     +-----------------------+  +----------------+ |
|    \---->|SaxEventHandlerFactory2|->|SaxEventHandler2| |
|          +-----------------------+  +----------------+ |
\--------------------------------------------------------/
....

For more specific details, see the Javadoc for the `org.codice.ddf.transformer.xml.streaming.*` package.
Additionally, see the source code for the `org.codice.ddf.transformer.xml.streaming.impl.GmlHandler.java`, `org.codice.ddf.transformer.xml.streaming.impl.GmlHandlerFactory`, `org.codice.ddf.transformer.xml.streaming.impl.XmlInputTransformerImpl`, and `org.codice.ddf.transformer.xml.streaming.impl.XmlInputTransformerImplFactory`.

[NOTE]
====
1. The `XmlInputTransformer` & `SaxEventHandlerDelegate` create and configure themselves based on String matches of the configuration ids with the `SaxEventHandlerFactory` ids, so ensure these match.
2. The `XmlInputTransformer` uses a `DynamicMetacardType`.
This is pertinent because a metacards attributes are only stored in the `CatalogProvider` if they are declared on the `MetacardType`.
Since the `DynamicMetacardType` is constructed dynamically, attributes are declared by the `SaxEventHandlerFactory` that parses them, as opposed to the `MetacardType`. See `org.codice.ddf.transformer.xml.streaming.impl.XmlSaxEventHandlerFactoryImpl.java` vs `ddf.catalog.data.impl.BasicTypes.java`
====

