:title: Assuring Authenticity of Bundles and Applications
:type: developingComponent
:status: published
:link: _assuring_authenticity_of_bundles_and_applications
:order: 22
:summary: Assuring Authenticity of Bundles and Applications.

${branding} Artifacts in the JAR file format (such as bundles or KAR files) can be signed and verified using the tools included as part of the Java Runtime Environment.

== Prerequisites

To work with Java signatures, a keystore/truststore is required.
For testing or trial purposes ${branding} can sign and validate using a self-signed certificate, generated with the keytool utility.
In an actual installation, a certificate issued from a trusted Certificate Authority is used.

Additional documentation on keytool can be found at http://docs.oracle.com/javase/6/docs/technotes/tools/windows/keytool.html[Keytool home] {external-link}.

.Using keytool to generate a self-signed certificate keystore
[source]
----
~ $ keytool -genkey -keyalg RSA -alias selfsigned -keystore keystore.jks -storepass password -validity 360 -keysize 2048
What is your first and last name?
  [Unknown]:  Nick Fury
What is the name of your organizational unit?
  [Unknown]:  Marvel
What is the name of your organization?
  [Unknown]:  SHIELD
What is the name of your City or Locality?
  [Unknown]:  New York
What is the name of your State or Province?
  [Unknown]:  NY
What is the two-letter country code for this unit?
  [Unknown]:  US
Is CN=Nick Fury, OU=SHIELD, O=Marvel, L="New  York", ST=NY, C=US correct?
  [no]:  yes
Enter key password for <selfsigned>
    (RETURN if same as keystore password):
Re-enter new password:
----

== Signing a JAR/KAR

Once a keystore is available, the JAR can be signed using the `jarsigner`
 tool.

Additional documentation on jarsigner can be found at http://docs.oracle.com/javase/6/docs/technotes/tools/windows/jarsigner.html[Jarsigner] {external-link}.

.Using jarsigner to sign a KAR
[source]
----
~ $ jarsigner -keystore keystore.jks -keypass shield -storepass password  catalog-app-2.5.1.kar selfsigned
----

=== Verifying a JAR/KAR
The jarsigner utility is also used to verify a signature in a JAR-formatted file.

.Using jarsigner to verify a file
[source]
----
~ $ jarsigner -verify -verbose -keystore keystore.jks catalog-app-2.5.1.kar
        9447 Mon Oct 06 17:05:46 MST 2014 META-INF/MANIFEST.MF
        9503 Mon Oct 06 17:05:46 MST 2014 META-INF/SELFSIGN.SF

[... section abbreviated for space]

smk     6768 Wed Sep 17 17:13:58 MST 2014 repository/${ddf-branding-lowercase}/catalog/security/catalog-security-logging/2.5.1/catalog-security-logging-2.5.1.jar
  s = signature was verified
  m = entry is listed in manifest
  k = at least one certificate was found in keystore
  i = at least one certificate was found in identity scope
jar verified.
----

Note the last line: _jar verified_.
This indicates that the signatures used to sign the JAR (or in this case, KAR) were valid according to the trust relationships specified by the keystore.
