:title: Developing Action Components
:type: developingComponent
:status: published
:link: _developing_catalog_plugins
:order: 19
:summary: Creating a custom Action Component.

To provide a service, such as a link to a metacard, the `ActionProvider` interface should be implemented.
An `ActionProvider` essentially provides a List of `Actions` when given input that it can recognize and handle.
For instance, if a REST endpoint ActionProvider was given a metacard, it could provide a link based on the metacard's ID. 
An Action Provider performs an action when given a subject that it understands.
If it does not understand the subject or does not know how to handle the given input, it will return `Collections.emptyList()`.
An Action Provider is required to have an ActionProvider id.
The Action Provider must register itself in the OSGi Service Registry with the `${ddf-branding-lowercase}.action.ActionProvider` interface and must also have a service property value for `id`. 
An action is a URL that, when invoked, provides a resource or executes intended business logic. 

==== Action Component Naming Convention

For each Action, a title and description should be provided to describe what the action does.
The recommended naming convention is to use the verb 'Get' when retrieving a portion of a metacard, such as the metadata or thumbnail, or when downloading a resource.
The verb 'Export' or the expression 'Export as' is recommended when the metacard is being exported in a different format or presented after going some transformation.

===== Action Component Taxonomy

An Action Provider registers an `id` as a service property in the OGSi Service Registry based on the type of service or action that is provided.
Regardless of implementation, if more than one Action Provider provides the same service, such as providing a URL to a thumbnail for a given metacard, they must both register under the same `id`.
Therefore, Action Provider implementers must follow an Action Taxonomy. 


The following is a sample taxonomy: 

. `catalog.data.metacard` shall be the grouping that represents Actions on a Catalog metacard.
.. `catalog.data.metacard.view`
.. `catalog.data.metacard.thumbnail`
.. `catalog.data.metacard.html`
.. `catalog.data.metacard.resource`
.. `catalog.data.metacard.metadata`

.Action ID Service Descriptions
[cols="2,4,1" options="header"]
|===
|ID
|Required Action
|Naming Convention

|`catalog.data.metacard.view`
|Provides a valid URL to view a metacard. Format of data is not specified; i.e. the representation can be in XML, JSON, or other.
|Export as ...

|`catalog.data.metacard.thumbnail`
|Provides a valid URL to the bytes of a thumbnail (`Metacard.THUMBNAIL`) with MIME type image/jpeg.
|Export as Thumbnail

|`catalog.data.metacard.map.overlay.thumbnail`
|Provides a metacard URL that translates the metacard into a geographically aligned image (suitable for overlaying on a map).
|Export as Thumbnail Overlay

|`catalog.data.metacard.html`
|Provides a valid URL that, when invoked, provides an HTML representation of the metacard.
|Export as HTML

|`catalog.data.metacard.xml`
|Provides a valid URL that, when invoked, provides an XML representation of the metacard.
|Export as XML

|`catalog.data.metacard.geojson`
|Provides a valid URL that, when invoked, provides an XML representation of the metacard.
|Export as GeoJSON

|`catalog.data.metacard.resource`
|Provides a valid URL that, when invoked, provides the underlying resource of the metacard.
|Export as Resource

|`catalog.data.metacard.metadata`
|Provides a valid URL to the XML metadata in the metacard (`Metacard.METADATA`).
|Export as Metadata

|===
