:title: Developing Query Options
:type: developingComponent
:status: published
:link: _developing_query_options
:order: 19
:summary: Creating a custom Query Option.

The easiest way to create a Query is to use the `ddf.catalog.operation.QueryImpl` object.
It is first necessary to create an OGC Filter object then set the Query Options after `QueryImpl` has been constructed.

.`QueryImpl` Example
[source,java,linenums]
----
/*
  Builds a query that requests a total results count and
  that the first record to be returned is the second record found from
  the requested set of metacards.
 */

 String property = ...;

 String value = ...;

 org.geotools.filter.FilterFactoryImpl filterFactory = new FilterFactoryImpl() ;

 QueryImpl query = new QueryImpl( filterFactory.equals(filterFactory.property(property),

filterFactory.literal(value))) ;

 query.setStartIndex(2) ;

 query.setRequestsTotalResultsCount(true);
----

==== Evaluating a query

Every Source must be able to evaluate a Query object.
Nevertheless, each Source could evaluate the Query differently depending on what that Source supports as to properties and query capabilities.
For instance, a common property all Sources understand is id, but a Source could possibly store frequency values under the property name "frequency."
Some Sources may not support frequency property inquiries and will
throw an error stating it cannot interpret the property.
In addition, some Sources might be able to handle spatial operations, while others might not.
A developer should consult a Source's documentation for the limitations, capabilities, and properties that a Source can support.


.[[_query_options]]Query Options
[cols="2*", options="header"]
|===
|Option
|Description

|`StartIndex`
|1-based index that states which metacard the Source should return first out of the requested metacards.

|`PageSize`
|Represents the maximum amount of metacards the Source should return.

|`SortBy`
|Determines how the results are sorted and on which property.

|`RequestsTotalResultsCount`
|Determines whether the total number of results should be returned.

|`TimeoutMillis`
|The amount of time in milliseconds before the query is to be abandoned. If a zero or negative timeout is set, the catalog framework will default to a value configurable via the Admin UI under Catalog -> Configuration -> Query Operations.

|===

==== Commons-DDF Utilities

The `commons-${ddf-branding}` bundle provides utilities and functionality commonly used across other ${branding} components, such as the endpoints and providers. 

===== FuzzyFunction

`${ddf-branding}.catalog.impl.filter.FuzzyFunction` class is used to indicate that a `PropertyIsLike` filter should interpret the search as a fuzzy query. 

===== XPathHelper

`${ddf-branding}.util.XPathHelper` provides convenience methods for executing XPath operations on XML.
It also provides convenience methods for converting XML as a `String` from a `org.w3c.dom.Document` object and vice versa.

