:title: Developing Sources
:type: developingComponent
:status: published
:link: _developing_sources
:summary: Creating a custom source.
:order: 10

Sources are components that enable ${branding} to talk to back-end services.
They let ${branding} perform query and ingest operations on catalog stores and query operations on federated sources.

.Source Architecture
[ditaa, sources_architecture, png, ${image-width}]
....
+----------------------------------------------------------------------------------------------+
|                /-------------------\            /-----------------------------\    +-=------+|
|                |cDEFEndpoints      |            |c369   Remote Sources        |    |External||
|                +------------+------+            | /-------------------------\ |    | Data{s}||
|                |cDEF        |cDEF  |            | |c369Federated Sources    |-+--->|Holdings||
|                | Operations | Data |            | +-------------------------+ |    +--------+|
|/---------------+------------+------+------------+ |c369Connected Sources    |-+--->          |
||cDEF           |cDEF               |cDEF        | +-------------------------+ |    +-=------+|
||               |                   |            | |c369 Catalog Stores      |-+--->|External||
||  Transformers |                   | Federation | \-------------------------/ |    | Data{s}||
|+---------------+ Catalog Framework +------------+-----------------------------+    |Holdings||
||cDEF           |                   |cDEF           Eventing                   |    +--------+|
||   Catalog     |                   +------------------------------------------+              |
||   Plugins     |                   |cDEF           Resources                  |              |
|\---------------+-------------------+------------------------------------------/              |
|                |c369               |                                                         |
|                | Catalog Provider  |              cCCC                                       |
|                +-------------------+                                                         |
|                |cDEF               |                                                         |
|                | Storage Provider  |                                                         |
|                \-------------------/                                                         |
|                          |                                                                   |
|                          v                                                                   |
|                  +-=-------------+                                                           |
|                  |               |                                                           |
|                  |{s}Data Store  |                                                           |
|                  +---------------+                                                           |
+----------------------------------------------------------------------------------------------+
....

==== Implement a Source Interface

There are three types of sources that can be created to perform query operations.
All of these sources must also be able to return their availability and the list of content types currently stored in their back-end data stores.

Catalog Provider:: `ddf.catalog.source.CatalogProvider` _is used to communicate with back-end storage and allows for Query and Create/Update/Delete operations._
Federated Source:: `ddf.catalog.source.FederatedSource` _is used to communicate with remote systems and only allows query operations._
Connected Source:: `ddf.catalog.source.ConnectedSource` _is similar to a Federated Source with the following exceptions:_
* _Queried on all local queries_
* ``SiteName`` _is hidden (masked with the ${branding} sourceId) in query results_
* ``SiteService`` _does not show this Source's information separate from ${branding}'s._
Catalog Store:: `catalog.store.interface` _is used to store data._

The procedure for implementing any of the source types follows a similar format:

. Create a new class that implements the specified Source interface, the `ConfiguredService` and the required methods.
. Create an OSGi descriptor file to communicate with the OSGi registry. (Refer to <<_osgi_basics,OSGi Services>>.)
.. Import ${branding} packages.
.. Register source class as service to the OSGi registry.
. Deploy to ${branding}.

[IMPORTANT]
====
The `factory-pid` property of the metatype must contain one of the following in the name: service, Service, source, Source
====

[NOTE]
====
Remote sources currently extend the `ResourceReader` interface. However, a `RemoteSource` is not treated as a `ResourceReader`. The `getSupportedSchemes()` method should never be called on a `RemoteSource`, thus the suggested implementation for a `RemoteSource` is to return an empty set. The `retrieveResource( …​ )` and `getOptions( …​ )` methods will be called and MUST be properly implemented by a `RemoteSource`.
====

===== Developing Catalog Providers

Create a custom implementation of a catalog provider.

. Create a Java class that implements `CatalogProvider`. +
`public class TestCatalogProvider implements ddf.catalog.source.CatalogProvider`
. Implement the required methods from the `ddf.catalog.source.CatalogProvider` interface. +
`public CreateResponse create(CreateRequest createRequest) throws IngestException;`
`public UpdateResponset update(UpdateRequest updateRequest) throws IngestException;`
`public DeleteResponse delete(DeleteRequest deleteRequest) throws IngestException;`

. Import the ${branding} interface packages to the bundle manifest (in addition to any other required packages). +
`Import-Package: ddf.catalog, ddf.catalog.source`
. Export the service to the OSGi registry.

.Catalog Provider Blueprint example
[source,xml]
----
<service ref="TestCatalogProvider" interface="ddf.catalog.source.CatalogProvider" />
----

See the <<{managing-prefix}connecting_to_sources,existing Catalog Provider list>> for examples of Catalog Providers included in ${branding}.

===== Developing Federated Sources

. Create a Java class that implements `FederatedSource` and `ConfiguredService`. +
`public class TestFederatedSource implements ddf.catalog.source.FederatedSource, ddf.catalog.service.ConfiguredService`
. Implement the required methods of the `ddf.catalog.source.FederatedSource` and `ddf.catalog.service.ConfiguredService` interfaces.
. Import the ${branding} interface packages to the bundle manifest (in addition to any other required packages). +
`Import-Package: ddf.catalog, ddf.catalog.source`
. Export the service to the OSGi registry.

.Federated Source Blueprint example
[source,xml]
----
<service ref="TestFederatedSource" interface="ddf.catalog.source.FederatedSource" />
----

===== Developing Connected Sources

Create a custom implementation of a connected source.

. Create a Java class that implements `ConnectedSource` and `ConfiguredService`. +
`public class TestConnectedSource implements ddf.catalog.source.ConnectedSource, ddf.catalog.service.ConfiguredService`
. Implement the required methods of the `ddf.catalog.source.ConnectedSource` and `ddf.catalog.service.ConfiguredService` interfaces.
. Import the ${branding} interface packages to the bundle manifest (in addition to any other required packages). +
`Import-Package: ddf.catalog, ddf.catalog.source`
. Export the service to the OSGi registry.

.Connected Source Blueprint example
[source,xml,linenums]
----
<service ref="TestConnectedSource" interface="ddf.catalog.source.ConnectedSource" />
----
[IMPORTANT]
====
In some Providers that are created, there is a need to make Web Service calls through JAXB clients.
It is best to NOT create a JAXB client as a global variable.
There may be intermittent failures with the creation of Providers and federated sources when clients are created in this manner.
To avoid this issue, create any JAXB within the methods requiring it.
====

===== Exception Handling

In general, sources should only send information back related to the call, not implementation details.

====== Exception Examples

Follow these guidelines for effective exception handling:

* Use a "Site XYZ not found" message rather than the full stack trace with the original site not found exception.
* If the caller issues a malformed search request, return an error describing the right form, or specifically what was not recognized in the request. Do not return the exception and stack trace where the parsing broke.
* If the caller leaves something out, do not return the null pointer exception with a stack trace, rather return a generic exception with the message "xyz was missing."

====== External Resources for Developing Sources

* http://today.java.net/pub/a/today/2003/12/04/exceptions.html[Three Rules for Effective Exception Handling] {external-link}.
