:title: Developing Applications
:type: developingComponemt
:status: published
:summary: Developing applications.
:order: 01

The ${branding} applications are a collection of OSGi bundles that contain configurations to be displayed in the ${admin-console}.
The applications are defined in the ${etc/application-definitions} directory.
Any json file added to the ${etc/application-definitions} with name, description and bundleLocations keys will be displayed in the ${admin-console}.
The application will only display if one of the bundles listed in the bundleLocations key is running or there is at least 1 plugin associated with that application running.

A KAR file is a Karaf-specific archive format (*K*araf *AR*chive).
It is a jar file that contains a feature descriptor file and one or more OSGi bundle jar files.
The feature descriptor file identifies a set of bundles that need to be installed, and any dependencies on other features that may need to be installed.

== Describing Application Services

Given the modular nature of OSGi, some applications perform operations on the services themselves.
In order to present, identify, and manipulate the services, they need descriptive identifying information.
Any service that implements the `Describable` interface in `org.codice.ddf.platform.services.common` will
have an obligation to provide this information.
The relevant fields are as follows:

ID:: a unique identifier for the service
Title:: the informal name for the service
Description:: a short, human-consumable description of the service
Organization:: the name of the organization that wrote the service
Version:: the current version of the service (example: 1.0)

The only field with stringent requirements is the ID field.
The format is `[*product*].[*component*]`
such as `ddf.metacards` or `ddf.platform`; while the [*component*] within a [*product*] may simply be a module or bundle name, the [*product*] itself should be the unique name of the plug-in or integration that belongs to the organization provided.
Note that `ddf` as a [*product*] is reserved for core features
only and is not meant to be used during extension or integration.

== Creating a KAR File

The recommended method for creating a KAR file is to use the `features-maven-plugin`, which has a `create-kar` goal.
This goal reads all of the features specified in the feature's descriptor file.
For each feature in this file, it resolves the bundles defined in the feature.
All bundles are then packaged into the KAR archive.

.`create-kar` Goal Example
[source,xml,linenums]
----
<plugin>
<groupId>org.apache.karaf.tooling</groupId>
<artifactId>features-maven-plugin</artifactId>
<version>2.2.5</version>
	<executions>
	    <execution>
	        <id>create-kar</id>
	        <goals>
	            <goal>create-kar</goal>
	        </goals>
	        <configuration>
	            <descriptors>
	                <!-- Add any other <descriptor> that the features file may reference here -->
	            </descriptors>
	            <!--
	            Workaround to prevent the target/classes/features.xml file from being included in the
	            kar file since features.xml already included in kar's repository directory tree.
	            Otherwise, features.xml would appear twice in the kar file, hence installing the
	            same feature twice.
	            Refer to Karaf forum posting at http://karaf.922171.n3.nabble.com/Duplicate-feature-repository-entry-using-archive-kar-to-build-deployable-applications-td3650850.html
	            -->
	            <resourcesDir>${variable-prefix}project.build.directory}/doesNotExist</resourcesDir>

	            <!--
	            Location of the features.xml file. If it references properties that need to be filtered, e.g., ${variable-prefix}project.version}, it will need to be
	            filtered by the maven-resources-plugin.
	            -->
	            <featuresFile>${variable-prefix}basedir}/target/classes/features.xml</featuresFile>

	            <!-- Name of the kar file (.kar extension added by default). If not specified, defaults to ${variable-prefix}project.build.finalName} -->
	            <finalName>${ddf-branding-lowercase}-ifis-${variable-prefix}project.version}</finalName>
	        </configuration>
	    </execution>
    </executions>
</plugin>
----

Examples of how KAR files are created for ${branding} components can be found in the ${branding} source code under the `${branding-lowercase}/distribution/${branding-lowercase}-kars directory`.

The `.kar` file generated should be deployed to the application author's maven repository.
The URL to the application's KAR file in this Maven repository should be the installation URL that is used.

== Including Data Files in a KAR File

The developer may need to include data or configuration files in a KAR file.
An example of this is a properties file for the JDBC connection properties of a catalog provider.

It is recommended that:

* Any `data/configuration` files be placed under the `src/main/resources` directory of the maven project.
Sub-directories under `src/main/resources` can be used, for example, `etc/security`.
* The Maven project's pom file should be updated to attach each `data/configuration` file as an artifact (using the `build-helper-maven-plugin`).
* Add each `data/configuration` file to the KAR file using the `<configfile>` tag in the KAR's `features.xml` file.

== Installing a KAR File

When the user downloads an application by clicking on the *Installation* link, the application's KAR file is downloaded.
To install manually, the KAR file can be placed in the `${home_directory}/deploy` directory of the running ${branding} instance. ${branding} then detects that a file with a `.kar` file extension has been placed in this monitored directory, unzips the KAR file into the `${home_directory}/system` directory, and installs the bundles listed in the KAR file's feature descriptor file.
To install via the ${admin-console}:
. Navigate to the *${admin-console}*.
. Select *Manage* button.
. Select *Add an Application*,
. Upload the KAR file via the popup window.
. Select *Save Changes* to activate,
The new application can be viewed via the ${admin-console}'s Active Applications list.

=== Developing Application Configuration Modules

An application within ${branding} is a collection of bundles contained in a KAR file that may or may not have configurations associated with it.
Plugins are used to advertise applications.
These configuration module plugins are often used to add user interface elements to make the use of the ${branding} simpler and/or more intuitive.

==== Creating an Application Configuration Module

This example demonstrates a plugin that allows the ${branding} to use the Admin UI.

. Create an application plugin to advertise your configuration by extending `AbstractApplicationPlugin`.
+
[source,java,linenums]
----
import org.codice.${ddf-branding-lowercase}.admin.application.plugin.AbstractApplicationPlugin;

public class SourcesPlugin extends AbstractApplicationPlugin {
    /**
     * Constructor.
     */

    public SourcesPlugin() {
        this.displayName = "Sources";
        this.iframeLocation = URI.create("./sources/index.html");
        List<String> apps = new ArrayList<String>();
        apps.add("catalog-app");
        this.setAssociations(apps);
    }
}
----
+
. Configure as shown with a name, URI, and any dependency applications.
. Register the application with Blueprint through a `blueprint.xml` file.
+
.`blueprint.xml`
[source,xml,linenums]
----
<blueprint xmlns="http://www.osgi.org/xmlns/blueprint/v1.0.0"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="
  http://www.osgi.org/xmlns/blueprint/v1.0.0 http://www.osgi.org/xmlns/blueprint/v1.0.0/blueprint.xsd">

    <bean id="appModule" class="org.codice.ui.admin.applications.ApplicationModule"></bean>

    <service interface="org.codice.ddf.ui.admin.api.module.AdminModule" ref="appModule" />

</blueprint>
----
+
. Create application to use this configuration.

=== Including KAR Files

Sometimes a developer may need to include data or configuration files in a KAR file.
An example of this would be a properties file for the JDBC connection properties of a catalog provider.

It is recommended that:

* Any data/configuration files be placed under the `src/main/resources` directory of the maven project.
(Sub-directories under `src/main/resources` can also be used, for example, `etc/security`)
* The maven project's pom file should be updated to attach each data/configuration file as an artifact (using the `build-helper-maven-plugin`)
* Add each data/configuration file to the KAR file by using the `<configfile>` tag in the KAR's `features.xml` file
