:title: Developing Endpoints
:type: developingComponent
:status: published
:link: _developing_endpoints
:summary: Creating a custom endpoint.
:implements: https://www.w3.org/2001/sw/wiki/REST[REST specification] {external-link}.
:order: 06

Custom endpoints can be created, if necessary.
See <<{integrating-prefix}endpoint_details,Endpoints>> for descriptions of provided endpoints.

Complete the following procedure to create an endpoint. 

. Create a Java class that implements the endpoint's business logic. Example: Creating a web service that external clients can invoke.

. Add the endpoint's business logic, invoking `CatalogFramework` calls as needed.  

. Import the ${branding} packages to the bundle's manifest for run-time (in addition to any other required packages): +
`Import-Package: ddf.catalog, ddf.catalog.*`

. Retrieve an instance of `CatalogFramework` from the OSGi registry. (Refer to <<{developing-prefix}osgi_basics,OSGi Basics - Service Registry>> for examples.)

. Deploy the packaged service to ${branding}.
(Refer to <<{developing-prefix}osgi_basics,OSGi Basics - Bundles>>.)

[NOTE]
====
It is recommended to use the maven bundle plugin to create the Endpoint bundle's manifest as opposed to directly editing the manifest file.
====

[TIP]
====
*No implementation of an interface is required* +
Unlike other ${branding} components that require you to implement a standard interface, no implementation of an interface is required in order to create an endpoint.
====

.Common Endpoint Business Logic
[cols="1m,2", options="header"]
|===
|Methods
|Use

|Ingest
|Add, modify, and remove metadata using the ingest-related `CatalogFramework` methods: 

create, update, and delete. 

|Query
|Request metadata using the `query` method.

|Source
|Get available `Source` information.

|Resource
|Retrieve resources referenced in Metacards from Sources.

|Transform
|Convert common Catalog Framework data types to and from other data formats.

|===
