:title: Configuring Managed Service Factory Bundles
:type: developingComponent
:status: published
:link: _configuring_managed_service_factory_bundles
:summary: Configuring Managed Service Factory bundles.
:order: 20

==== Configuring Managed Service Factory Bundles

Services that are created using a Managed Service Factory can be configured using `.config` files as well.
These configuration files, however, follow a different naming convention than `.cfg` files.
The filenames must start with the Managed Service Factory PID, be followed by a dash and a unique identifier, and have a `.config` extension.
For instance, assuming that the Managed Service Factory PID is `org.codice.ddf.factory.pid` and two instances of the service need to be configured, files `org.codice.ddf.factory.pid-<UNIQUE ID 1>.config` and `org.codice.ddf.factory.pid-<UNIQUE ID 2>.config` should be created and added to `${home_directory}/etc`.

The unique identifiers used in the file names have no impact on the order in which the configuration files are processed.
No specific processing order should be assumed.
Also, a new service will be created and configured every time a configuration file matching the Managed Service Factory PID is added to the directory, regardless of the _unique id_ used.

Any `service.factoryPid` and `service.pid` values in these `.config` files will be overridden by the values parsed from the file name, so `.config` files should not contain these properties.

===== File Format

The basic syntax of the `.config` configuration files is similar to the older `.cfg` files but introduces support for lists and types other than simple strings.
The type associated with a property must match the type attribute used in the corresponding `metatype.xml` file when applicable.

The following table shows the format to use for each property type supported.

.Property Formats
[cols="1,2,3" options="header"]
|===
|Type
|Format (see details below for variations)
|Example

|String
|name="value"
a|`name="John"`

|Boolean
|name=B"true\|false"
a|`authorized=B"true"`

|Integer
|name=I"value"
a|`timeout=I"10"`

|Long
|name=L"value"
a|`diameter=L"100"`

|Float
|name=F"value"
a|`cost=F"1093140480"`

|Double
|name=D"value"
a|`latitude=D"4636745974857667812"`

|List of Strings
|name=["value1","value2",…​]
a|```
complexStringArray=[ \
  "{\"url\"\ \"http://test.sample.com\"\ \"layers\"\ [\"0\"]\ \"VERSION\"\ \"1.1\|1.2\"\ \"image/png\"}\ \"beta\"\ 1}", \
  "{\"url\"\ \"http://test.sample.com"\ 0.5}", \
  "/security-config\=SAML\|basic", \
  ]
```

|List of Booleans
|name=B["true\|false","true\|false",…​]
a|```
authorizedList=B[ \
  "true", \
  "false", \
  ]
```

|List of Integers
|name=I["value1","value2",…​]
a|```
sizes=I[ \
  "10", \
  "20", \
  "30", \
  ]
```

|List of Longs
|name=L["value1","value2",…​]
a|```
sizes=L[ \
  "100", \
  "200", \
  "300", \
  ]
```

|List of Floats
|name=F["value1","value2",…​]
a|```
sizes=F[ \
  "1066192077", \
  "1074580685", \
  "1079194419", \
  ]
```

|List of Doubles
|name=D["value1","value2",…​]
a|```
sizes=D[ \
  "4607736361554183979", \
  "4612212939583790252", \
  "4614714689176794563", \
  ]
```

|===

[NOTE]
====
* Values with types other than String must be prefixed with a lower-case or upper-case character. See the examples in the table.
** Boolean: `B` or `b`
** Integer: `I` or `i`
** Long: `L` or `l`
** Float: `F` or `f`
** Double: `D` or `d`
* Equal signs (`=`), double quotes (`"`), and spaces within values must must be escaped using a backslash (`\`).
* When properties are split over multiple lines for readability, end of lines must be specified with a backslash (`\`). See the examples for lists in the table.
* A comma (`,`) after the last value in a list is optional.
* Surrounding the equal signs (`=`) with spaces for properties is optional.
// TODO DDF-3291 Upgrade Felix and remove .config file spaces work-around
Because there is a known issue when using OPS4J Pax Exam 4.11.0 and modifying `.config` files that include spaces, all default `.config` files that may be modified in OPS4J Pax Exam 4.11.0 tests should not include spaces.
* Boolean values will default to `false` if any value other than `true` is provided.
* Float values must be representated in the IEEE 754 floating-point "single format" bit layout, preserving Not-a-Number (NaN) values.
For example, `F"1093140480"` corresponds to `F"10.5"`.
See the documentation for https://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html#parseInt(java.lang.String)[java.lang.Integer#parseInt(java.lang.String)] and https://docs.oracle.com/javase/7/docs/api/java/lang/Float.html#intBitsToFloat(int)[java.lang.Float#intBitsToFloat(int)] for more details.
* Double values must be represented in the IEEE 754 floating-point "double format" bit layout, preserving Not-a-Number (NaN) values.
For example, `D"4636745974857667812"` corresponds to `D"100.1234"`.
See the documentation for https://docs.oracle.com/javase/7/docs/api/java/lang/Long.html#parseLong(java.lang.String)[java.lang.Long#parseLong(java.lang.String)] and https://docs.oracle.com/javase/7/docs/api/java/lang/Double.html#longBitsToDouble(long)[java.lang.Double#longBitsToDouble] for more details.

====

.Sample configuration file
[source,linenums]
----
authenticationTypes=[ \
  "/\=", \
  "/admin\=basic", \
  "/system\=basic", \
  "/sources\=basic", \
  "/security-config\=basic", \
  "/search\=basic", \
  ]
sessionAccess=B"true"
guestAccess=B"true"
realms=[ \
  "/\=karaf", \
  ]
requiredAttributes=[ \
  "/\=", \
  "/admin\={http://schemas.xmlsoap.org/ws/2005/05/identity/claims/role\=admin}", \
  "/system\={http://schemas.xmlsoap.org/ws/2005/05/identity/claims/role\=admin}", \
  "/security-config\={http://schemas.xmlsoap.org/ws/2005/05/identity/claims/role\=admin}", \
  ]
whiteListContexts=[ \
  "/services/SecurityTokenService", \
  "/services/internal/metrics", \
  "/services/saml", \
  "/proxy", \
  "/services/csw", \
  ]

----
