:title: Developing Query Response Transformers
:type: developingComponent
:status: published
:link: _developing_query_response_transformers
:summary: Creating a custom query response transformer.
:order: 09

A `QueryResponseTransformer` is used to transform a List of Results from a `SourceResponse`.
Query Response Transformers can be used through the Catalog transform convenience method or requested from the OSGi Service Registry by endpoints or other bundles.

. Create a new Java class that implements `ddf.catalog.transform.QueryResponseTransformer`. +
`public class SampleResponseTransformer implements ddf.catalog.transform.QueryResponseTransformer`
. Implement the `transform` method. +
`public BinaryContent transform(SourceResponse upstreamResponse, Map<String, Serializable> arguments) throws CatalogTransformerException`
. Import the DDF interface packages to the bundle manifest (in addition to any other required packages). +
`Import-Package: ddf.catalog, ddf.catalog.transform`
. Create an OSGi descriptor file to communicate with the OSGi Service Registry (described in <<{developing-prefix}osgi_basics,OSGi Basics>>). Export the service to the OSGi registry and declare service properties.
+
. Deploy OSGi Bundle to OSGi runtime.
+
.Query Response Transformer Blueprint Descriptor Example
[source,xml,linenums]
----
...
<service ref="SampleResponseTransformer" interface="ddf.catalog.transform.QueryResponseTransformer">
    <service-properties>
        <entry key="id" value="[[sampleId]]" />
        <entry key="shortname" value="[[sampletransform]]" />
        <entry key="title" value="[[Sample Response Transformer]]" />
        <entry key="description" value="[[A new transformer for response queues.]]" />
    </service-properties>
</service>
...
----

.Query Response Transformer Blueprint Service Properties / Variable Descriptions
[cols="3" options="header"]
|===
|Key
|Description of Value
|Example

|`id`
|A unique identifier to target a specific query response transformer.
|atom

|`shortname`
|An abbreviation for the return type of the BinaryContent being sent to the user.
|atom

|`title`
|A user-readable title that describes (in greater detail than the shortname) the service.
|Atom Entry Transformer Service

|`description`
|A short, human-readable description that describes the functionality of the service and the output.
|_This service converts a single metacard xml document to an atom entry element_.

|===

'''
